### ISSUE TITLE
Can kustomize edit set-image be "context" aware?

### ISSUE THREAD

**Issue by nabadger** [kubernetes-sigs/kustomize#1015]
Maybe "container" aware is a better title?

We would like to use kustomize to generate manifests for our entire cluster-state. 

The problem we have is that we may be running multiple versions of an application - i.e. `redis:v1.0` and `redis:v2.0`. Maybe different teams have different versions, or we want to upgrade certain versions first and ensure they pass QA (or whatever really).

Generally speaking we can get all manifests generated from a single `kustomize build` command for the whole cluster.

I would like to use: `kustomize edit set image redis somerepo/redis:v2.0`, but only apply it to certain workloads (deployments).

At the moment this doesn't work, as it would bump all instances to `v2.0` in this example.

It feels like we could achieve this by making use of the container name perhaps.

i.e. the same concept could be applied to a single deployment running multiple versions of the same container 
```
   spec:
      containers:
      - image: redis
        name: my-old-redis
      - image:  redis
       name: my-new-redis
```

What might be nice is to make use of the `name` attribute when setting the image, so you could do:

```
kustomize edit set image my-old-redis/redis=somerepo/redis:v3.0
```

Hopefully this makes sense - are there anyways to achieve this already, without splitting this up into multiple `kustomize build` and multiple workloads?

Thanks!

**Comment by vreon** [comment]
Say you have a kustomization with two Deployments, and you want to set the image on each one independently:

```
.
├── kustomization.yaml
├── redis-a-deployment.yaml
└── redis-b-deployment.yaml
```

You can move each into a lower kustomization, then use those as bases in the upper kustomization. 
Any `kustomize edit set image [...]` on the lower kustomizations will then be scoped to just those resources.

```
.
├── kustomization.yaml
├── redis-a
│   ├── deployment.yaml
│   └── kustomization.yaml
└── redis-b
    ├── deployment.yaml
    └── kustomization.yaml
```

**Comment by nabadger** [comment]
Yes - restructuring would help the general case.

We ended up resolving the issue another way (via json-merge patches).

In my original scenario, the tooling running the kustomize command was updating the images on the underlying deployments (automagically), but it wouldn't know which directories (or even which remote bases) the lower kustomization files were in. It only knew of the deployment name, container name, and container image.

**Comment by Liujingfang1** [comment]
Agree with the suggestion from @vreon.
Kustomize sets all images inside one kustomization target. That's the expected behavior.
