### ISSUE TITLE
kustomize should support set value for configmap.

### ISSUE THREAD

**Issue by jinchihe** [kubernetes-sigs/kustomize#1028]
There is a requirement that we defined a configmap and with same default value (for some variables in container), we want to update some key-values in the configmap by using kustomize. Any plan to support that? From below help info, the current kustomize does not support that. Thanks.

```
#kustomize edit set --help
Sets the value of different fields in kustomization file.

Usage:
  kustomize edit set [command]

Examples:

	# Sets the nameprefix field
	kustomize edit set nameprefix <prefix-value>

	# Sets the namesuffix field
	kustomize edit set namesuffix <suffix-value>


Available Commands:
  image       Sets images and their new names, new tags or digests in the kustomization file
  nameprefix  Sets the value of the namePrefix field in the kustomization file.
  namespace   Sets the value of the namespace field in the kustomization file
  namesuffix  Sets the value of the nameSuffix field in the kustomization file.

```

**Comment by Liujingfang1** [comment]
You can use `kustomize edit add configmap`. Since `confimapGenerator` can generate ConfigMaps from files, literals, envs, only allowing set value for a key doesn't work.

**Comment by jinchihe** [comment]
@Liujingfang1 Thanks for replying. if user wnat to update the configmap (literals) after set that by `kustomize edit add configmap`, kustomize cannot do that. I agree we may conver all type of ConfigMaps, but is that possiable to support literals? seems that's very common.

**Comment by Liujingfang1** [comment]
@jinchihe You can create an overlay to customize the configmap. In the overlay, you add the configmap with the behavior `merge`. 
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/combineConfigs.md

**Comment by jinchihe** [comment]
> In the overlay

OK, will try that, thanks!

**Comment by mwmahlberg** [comment]
What does not work is an actual update of an existing ConfigMap. The use case goes like this: several scripts are maintained in a git submodule and then need to be added to a ConfigMap. Since existing file references cannot be added a second time something like

```
kustomize edit add configmap scripts --from-file='scripts/*.sh'
```

with `scripts` being the submodule. So `set` should actually have the semantic of replacing an existing configMapGenerator definition.

**Comment by MaurGi** [comment]
Does not seem to be idempotent, running it twice errors out - 
`Error: configmap deployer-info illegally repeats the key `cluster-id``
