### ISSUE TITLE
Failed to find an object with apps_v1_Deployment to apply the patch, differing output between darwin and linux binaries

### ISSUE THREAD

**Issue by Kampe** [kubernetes-sigs/kustomize#1032]
Having a pretty odd issue, I'm attempting to utilize Kustomize in my cloudbuild pipeline using the newest available image (Kustomize 2.0.3) - I've also tried downloading via grep and attempting to use the linux binary on its own as a build step.

When utilizing kustomize locally with (darwin) I have no issues, I can output both my base and development kustomized manifests.  However, when using in the cloudbuild pipeline, I'm unable to get Kustomize to run and receive the error: 

`Error: failed to find an object with apps_v1_Deployment|my-app to apply the patch`

Both my patch and my base have `apiVersion: apps/v1` defined as I'm able to replicate the issues by not including those values.   The cloudbuild image I'm using is utilizing the same version of Kustomize as my local machine.  I even went as far as to downgrade my Kustomize container to an earlier version with no avail (seeing as cloudbuild-community just updated the image for 2.0.3.)

**Comment by nictrix** [comment]
@Kampe I'm running into this same problem, the only thing I did was change where the files were located (in a subdirectory) - since you closed this were you able to resolve it?

**Comment by nictrix** [comment]
Disregard, I found I renamed an item, but so slightly - took a bit to notice.

**Comment by Abrishges** [comment]
I am running in the same issue using powershell script  `kubectl.exe kustomize . | kubectl.exe apply -f -`
were you be able to find solution ?

**Comment by Kampe** [comment]
malformed yaml on my end I do believe.
