### ISSUE TITLE
kustomize: command not found (Installation) 

### ISSUE THREAD

**Issue by joost14** [kubernetes-sigs/kustomize#1033]
Hi there, 

After installing kustomize using `go get sigs.k8s.io/kustomize` and executing the command kustomize i get the follwoing error: 
`kustomize: command not found`

Am I missing an installation step? I am trying to install kustomize on a ubuntu 18.04 machine using go 1.12

**Comment by joost14** [comment]
Fixed. Needed to do the following: 
`export PATH=$PATH:$(go env GOPATH)/bin`

**Comment by MaisaDaoud** [comment]
non of the solutions worked for me, any help please

**Comment by Shell32-Natsu** [comment]
@MaisaDaoud If you are using `go get` to install, the binary should be in `GOPATH/bin`.

**Comment by MaisaDaoud** [comment]
> @MaisaDaoud If you are using `go get` to install, the binary should be in `GOPATH/bin`.
 I tried different ways and  the only thing worked for me is by setting the path as mentioned here: https://www.kubeflow.org/docs/other-guides/kustomize/.  Thank you

**Comment by MaisaDaoud** [comment]
> @MaisaDaoud If you are using `go get` to install, the binary should be in `GOPATH/bin`.

 I tried different ways and  the only thing worked for me is by setting the path as mentioned here: https://www.kubeflow.org/docs/other-guides/kustomize/.  Thank you

**Comment by cuongrep** [comment]
You can install as the following commands:
`curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash`
and then
`sudo install -o root -g root -m 0755 kustomize /usr/local/bin/kustomize`

I don't know why autocomple in zsh always show `_kubectl_kustomize`. Does anyone know how to fix that?
references:
1. Install Kustomize by downloading precompiled binaries.
https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/
2. install kubectl on Linux
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
