### ISSUE TITLE
multiple matchers error

### ISSUE THREAD

**Issue by wuxingzhong** [kubernetes-sigs/kustomize#1034]
Error: Multiple matches for name apps_v1_Deployment|example|example-:config-|dep
loy|~S:
  [apps_v1_Deployment|example|example-:system-config-|deploy|~S apps_v1_Deployme
nt|example|example-:config-|deploy|~S]

**Comment by Liujingfang1** [comment]
Seems like the same failure as #1036.
Close it as duplication.
