### ISSUE TITLE
Ability to restrict fields that can be patched or merged

### ISSUE THREAD

**Issue by stevejr** [kubernetes-sigs/kustomize#1035]
Is it possible in kustomize to restrict the fields that can be merged or patched or is the only to achieve this setup is via linting the output from the `kustomize build` command?

**Comment by Liujingfang1** [comment]
I don't think there is such restriction in Kustomize.  If you need the output to be valid yaml files, you can lint the output; If you want to do more validation, such as that a field must have a predefined value or in a predefined range, the [transformer plugin](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins.md) can help.

**Comment by monopole** [comment]
kustomize has no notion of restricting edits.

**Comment by monopole** [comment]
Please file a feature request if you can think of way to phrase this.  I don't understand the use case - is this so a devops team can somehow prevent some change in a gitops pipeline?  Sounds out of scope.
