### ISSUE TITLE
name clashes when using the same base twice

### ISSUE THREAD

**Issue by bcbrockway** [kubernetes-sigs/kustomize#1036]
Please see https://github.com/bcbrockway/kustomize-name-clash for a working example of this issue.

We have a multi-layered kustomize config similar to the following (actually in practice they're in many different places to keep them modular but this should illustrate the issue we have):

```
.
└── dev1
    ├── dev
    │   ├── elasticstack-log
    │   │   ├── elasticstack
    │   │   │   ├── elasticsearch
    │   │   │   │   ├── elasticsearch-statefulSet.yml
    │   │   │   │   └── kustomization.yaml
    │   │   │   ├── elasticsearch-data
    │   │   │   │   ├── add-data-node-settings.yaml
    │   │   │   │   ├── elasticsearch-data-service.yml
    │   │   │   │   └── kustomization.yaml
    │   │   │   ├── elasticsearch-master
    │   │   │   │   ├── add-master-node-settings.yaml
    │   │   │   │   ├── elasticsearch-master-service.yml
    │   │   │   │   └── kustomization.yaml
    │   │   │   ├── kustomization.yaml
    │   │   │   ├── networkPolicy.yml
    │   │   │   └── README.md
    │   │   └── kustomization.yaml
    │   ├── kustomization.yaml
    │   └── properties
    │       └── environment.properties
    ├── kustomization.yaml
    ├── properties
    │   └── cluster.properties
    └── README.md
```

We're trying to reduce the amount of double-keying as much as possible by having an elasticsearch StatefulSet in its own base and then deriving master and data nodes from it, but we've run into a naming issue. We want to name the `elasticsearch-master` and `elasticsearch-data` resources simply `elasticsearch` and then have the `nameSuffix` field append the necessary `-master` or `-data` strings onto the end, however when you run a `kustomize build dev1` it complains:

```
Error: Multiple matches for name ~G_v1_Service|monitoring|~P|elasticsearch|-master:-log:
  [~G_v1_Service|monitoring|~P|elasticsearch|-master:-log ~G_v1_Service|monitoring|~P|elasticsearch|-data:-log]
```

I get a completely different error if I use `namePrefix` instead of `nameSuffix` in the `elasticsearch-master/kustomization.yaml` and `elasticsearch-data/kustomization.yaml` files:

```
Error: found 2 resId matches for var {elasticsearch-data-service-name ~G_v1_Service {metadata.name}} (unable to disambiguate)
```

This, I presume, is because the variable values are pulled _before_ the prefix/suffix is applied.

What are we doing wrong here? Are we missing something? Are there any best practices for this kind of structure?

**Comment by Liujingfang1** [comment]
This is related to `vars`. When looking for targets to resolve the vars, only one target is expected. With this layout, it found two.
This is bug in Kustomize. It should include prefix and suffix when looking for the target.

**Comment by nabadger** [comment]
I've just hit this issue as well - would be great to get more input on this.

**Comment by qiujian16** [comment]
i'v submittd a pr to try to fix it, @Liujingfang1 would you help to review it?

**Comment by Liujingfang1** [comment]
@qiujian16 Thank you for working on this. I'll review the PR.

**Comment by rehevkor5** [comment]
Is there a workaround? The fix does not appear to be available in `kubectl` yet.
