### ISSUE TITLE
[Feature request]: Add possibility to add json 6902 patches via edit

### ISSUE THREAD

**Issue by alexppg** [kubernetes-sigs/kustomize#1038]
Hi

Actually there's the possibility to add SMP via `kustomize edit add patch`. This is useful in the cases that you want to add stuff to the `kustomize.yml` file dinamycally. In the same way, it would be very useful to add json 6902 patches. 
I imagine that since the nature of the 6902 patches are more complex, this option would need some more parameters. Also, I guess that [this](https://github.com/kubernetes-sigs/kustomize/issues/720) should be take into account.

PD: Thanks for your work!

**Comment by Liujingfang1** [comment]
We can extend current `kustomize edit add patch` to support both `patchesStrategicMerge` and `patchesJson6902`. It could be done with a type flag.  Then for `patchesJson6902`, we need more arguments for target group, version, kind and name.

**Comment by Shell32-Natsu** [comment]
`kustomize edit add patch` should be refactored to add [`patches`](https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/patches/) field instead of either `patchesStrategicMerge` or `patchesJson6902`.

**Comment by ambis** [comment]
@Shell32-Natsu Could you please elaborate why `edit add patch` is no longer able to add to `patchesStrategicMerge`?

I believe `patchesStrategicMerge` is not deprecated or anything?

Flux CD (v1) creates a flux-patch.yml file which we validate in CI by adding it in `patchesStrategicMerge`. The file contains multiple patches, and cannot be applied, AFAIK, via the kustomize v4 edit add patch in anyway that would work. 

What was the reasoning to drop support for this?

**Comment by Shell32-Natsu** [comment]
@ambis Because `patches` supports both SMP and JSON patch.

**Comment by ambis** [comment]
I tried adding an SMP but failed to find the correct combo of arguments/options. 

I tried `kustomize edit add patch --patch flux-patch.yml` but it just added it into `patches`, not `patchesStrategicMerge`. Any help?

**Comment by Shell32-Natsu** [comment]
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/ Here is the doc for how to use `patches`.

**Comment by john-tipper** [comment]
@Shell32-Natsu @Liujingfang1 please can you clarify why glob support was removed here? I understand why it’s not supported inside a kustomization file itself, but the edit command was specifically modified to enable the addition of multiple files into the kustomization file (https://github.com/kubernetes-sigs/kustomize/issues/218).
