### ISSUE TITLE
transformers and configurations example in need

### ISSUE THREAD

**Issue by hougangliu** [kubernetes-sigs/kustomize#1049]
it is easy to mix transformers up with configurations field, please add an example to describe the difference between them.
In particular, an example with transformers field is absent now

**Comment by monopole** [comment]
modified https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins.md

There are now several transformer plugin examples (in particular, all the builtin transformations are implemented and tested as plugins).  See doc for pointers.

It's true however that we don't have an example of a kustomization file explicitly  referencing a custom transformer plugin.  We do have an example of a kustomization file referencing a custom generator.
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/secretGeneratorPlugin.md
