### ISSUE TITLE
Visualizing output of kustomize build

### ISSUE THREAD

**Issue by jpreese** [kubernetes-sigs/kustomize#1119]
Kustomize team, thanks for putting this together. We've recently switched from Helm to kustomize and are loving everything that kustomize brings to the table.

One question we had was, do you feel kustomize would benefit from a command that displays the dependency graph when `kustomize build` is executed? Very similar to `terraform graph` as documented here (https://www.terraform.io/docs/commands/graph.html). 

We put together a working example of this feature as a standalone tool called kustomize-graph (https://github.com/jpreese/kustomize-graph) but if there is a consensus that a large portion of the community would find value in this, we'd like to open a PR to add a graph command in `kustomize` itself.

If you feel they should be separate features, we will continue to build out kustomize-graph by itself. Otherwise, we'll open a PR that marries the two together. 

Thanks!

**Comment by monopole** [comment]
sounds awesome.
a new command would be nicely orthogonal to other stuff in flight.

please do a PR.  :)

**Comment by jerguslejko** [comment]
hey @monopole, has this been addressed elsewhere? I'd be happy to give it a try!
