### ISSUE TITLE
Request to isolate core yaml-altering code from kubernetes-specific code

### ISSUE THREAD

**Issue by mikeleonard** [kubernetes-sigs/kustomize#112]
Hi. Quick fly-by idea for you while the project is early on:

Could you aim to/continue to separate the yaml-altering code from the kubernetes-specific code? ie either as a separate repo or, failing that, as a separate go-gettable library.

### Why?

I've been thinking about infrastructure-as-code recently and really like this project's approach. It's possible that the OSS community might find other uses for the approach and could reuse and also contribute to the core non-kubernetes-specific code if it were an isolated go library. 

### Examples
As a example, take Hashicorp's memberlist package that implements the SWIM gossip protocol. It is a separate repo to their Consul repo and receives lots of contributions and use in other projects that I suspect it wouldn't have received if it was inside of the Consul repo.

What other possible uses for the core approach are there? Probably a few, yaml manifests are popular! Take Google Cloud's deployment manager for example. Very similar to Helm it does declarative deploys based on yaml config files. I was wondering if there was a nice way to add some Kustomize magic to it instead of having to use python or jinja for templating just to change a few params between dev/prod environments - which lead me to post this. 

PS Ignore me if this doesn't really make sense. I haven't gone through the codebase to determine if there's much non-kubernetes-specific code to isolate. Thought I'd just suggest the idea.

**Comment by Liujingfang1** [comment]
I'm not sure I fully understand you.  As far as I know, many kubernetes projects are developed in separate repos, such as kustomize, or [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder). 
If you are looking for some yaml-altering tool, this one seems to be good. https://github.com/kubernetes-sigs/kustomize/issues/167
