### ISSUE TITLE
Proposal:  Remote bases with container registry

### ISSUE THREAD

**Issue by anarcher** [kubernetes-sigs/kustomize#1140]
Currently, kustomize supports local and URL based remote bases.  It will be great if kustomize will support container registries as remote bases.  Helm3 also supports container registry as helm chart registry [1]. IMHO, if kustomize supports a container registry as remote base, It means that kustomize uses a local cache as local container registry image to prevent downloading bases every time.

[1]: https://github.com/helm/community/blob/3689b3202e35361274241dc4ec188e1e6f1a2e53/proposals/helm-repo-container-registry-convergence/readme.md

**Comment by Liujingfang1** [comment]
By `support container registries as remote bases`, do you mean storing kustomize bases as image in container registries?

**Comment by mxey** [comment]
This is probably relevant: https://stevelasker.blog/2019/01/25/cloud-native-artifact-stores-evolve-from-container-registries/
