### ISSUE TITLE
Reference deployment selector in service

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes-sigs/kustomize#1150]
Hi,

I am using kustomize do generate some resources and I have the following structure:
- a `base/deployment.yml` that represents a generic deployment template
- overlays such as web, worker, etc that add some labels, resources and commands

Some of my labels, such as `app.kubernetes.io/part-of` should be common to all my variants and are set in the `base/kustomization.yml`.
Others are variant specific and are set in my overlays.

One of my variant adds a service. Since this service is a resource in my overlay, the selector doesn't not get the labels set in my `base/kustomization.yml` (which makes sense). So I am looking for a way to duplicate or reference the selector of my deployment in my service to make sure that they are always in sync.

**Comment by Liujingfang1** [comment]
@benjamin-bergia When you add commonLabels to the overlay with the service, you can also include the label from the base.
