### ISSUE TITLE
`kubectl kustomize`: good way to redact secrets?

### ISSUE THREAD

**Issue by nickatsegment** [kubernetes-sigs/kustomize#1156]
I'm using `kubectl apply -k` as part of a CI deployment flow. I want to be able to record what was applied by persisting `kubectl kustomize` to a build artifact. However, this output includes secrets. 

Considering the output is a series of YAML docs, it's kind of tough to redact (or omit) the secrets' data.

Is there a good way? Alternatively, a flag to redact secrets would be great.

**Comment by nickatsegment** [comment]
I arrived at this `yq` script, but having in-tool support for this sort of thing would be cool.

```
yq -y 'if (.kind == "Secret") then .data = ([.data | to_entries[] | .value = "<redacted>"] | from_entries) else . end'
```

**Comment by monopole** [comment]
If i understand this correctly, one would have to perform two kustomizations;
1. send everything to a cluster
2. send everything minus secrets to storage

 - could add a flag to drop secrets from output
 - one could do a sed to remove the secretGeneration from kustomize file between step 1 and 2.
 - one could write a transformer plugin to remove secrets, and add it to the kustomization file to do 2.
 - leave the secrets in, but encrypt all the yaml on the way to storage.

**Comment by monopole** [comment]
or yq, that looks good to me :+1:

**Comment by etiennecoutaud** [comment]
@monopole I can work on it if noboby does

**Comment by nickatsegment** [comment]
Don't go out of your way to implement if it's just for me. We're trying to avoid Kubernetes Secrets in favour of fetching secrets at runtime
