### ISSUE TITLE
Cannot use the same plugin more than once in one kustomization file.

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#1164]
If a plugin is used twice in one kustomization file, the last config "wins",
overwriting earlier configs.

This is because plugin loading and config are done in one step per kustomization file
(see plugins.Loader::loadAndConfigurePlugin).  This problem doesn't exist
 for overlays using the same plugin used by some base -
it only applies to the same plugin used multiple times
in the same kustomization file.

**Comment by sethpollack** [comment]
Running into this one as well. Its also an issue if multiple bases use the same plugin as well.

**Comment by sethpollack** [comment]
@monopole I can open a PR for this. 

Thoughts on just returning a new configured plugin from `Config` rather than modifying the plugin?
