### ISSUE TITLE
Is the hashing too restrictive for custom transformation of custom resources?

### ISSUE THREAD

**Issue by NicolasRouquette** [kubernetes-sigs/kustomize#1167]
I wrote a simple custom transformation plugin to apply [sealed-secrets](https://github.com/bitnami-labs/sealed-secrets) to the 'Secrets' resource only of an input yaml. This results in a new custom resource, `SealedSecrets` that, unfortunately, `kustomize` rejects because it can't hash it:

https://github.com/kubernetes-sigs/kustomize/blob/master/k8sdeps/kunstruct/hasher.go#L25

For details of the experiment, see: https://github.com/bitnami-labs/sealed-secrets/issues/167#issuecomment-500570809

It seems to me that with custom generator and transformer plugins, `kustomize` ought to be able to pass custom resources that it does not recognize as-is instead of failing completely.

**Comment by Liujingfang1** [comment]
For other types, maybe just hash the bytes for the unstructured object.
