### ISSUE TITLE
Improve error messages on Go errors.

### ISSUE THREAD

**Issue by shanna** [kubernetes-sigs/kustomize#117]
It's a lot of work but it would be helpful if errors had some notion of the YAML file that caused the error so you don't have to dig through the source code. For example today I saw
```
Error: <nil> is not expected to be a primitive type
```
When you look at the source it could be one of two errors and there is no context provided so I couldn't have guessed (other than a diff of the configuration changes).

https://github.com/kubernetes-sigs/kustomize/blob/83b3eb9d5415663169e580982b373667762f6af8/pkg/transformers/util.go#L68
https://github.com/kubernetes-sigs/kustomize/blob/a95b26182a99e650d15592e30f302be22aaa9e36/pkg/resource/resource.go#L134

**Comment by Liujingfang1** [comment]
related to #114

**Comment by Liujingfang1** [comment]
duplicate with #124, we will address this issue there.
