### ISSUE TITLE
Kustomize for CircleCI

### ISSUE THREAD

**Issue by moismail109** [kubernetes-sigs/kustomize#1209]
We are working on using `Kustomize` to deploy our applications using `CircleCI` to GKE.

I followed the below steps to re-produce the use case:

1.  Install kustomize using
```
          name: Install kustomize
          command: |
            KUSTOMIZE_VERSION=2.1.0
            curl -L -o /usr/local/bin/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64
            chmod +x /usr/local/bin/kustomize
            kustomize version
```
2. Install kubernetes
3. Update image tag using kustomize:
```          name: Update image tag and deploy
          command: |
            kustomize edit set image IMAGE_NAME=$IMAGE_NAME$CIRCLE_SHA1
            kustomize build << parameters.deployment_path >> | kubectl apply -f -
```

Unfortunately I can't so far deploy it but every time I am trying to set the image tag, it fails.
So I have 2 questions:

1. Can you post an example for any CI/CD pipeline with kustomize
2. If I change the image name using `kustomize edit set image` how can I change it on `deployment.yaml` for the containers image? 
```
containers:
      - image:
```

**Comment by taxpon** [comment]
@moismail109 
> Can you post an example for any CI/CD pipeline with kustomize

I am using kustomize in CircleCI without facing any problems as follows.
```
# Set image and tag
kustomize edit set image ${IMAGE}:${TAG}
kustomize build . | kubectl apply -f -
```
> If I change the image name using kustomize edit set image how can I change it on deployment.yaml for the containers image?

`kustomize edit set image` add image configuration(s) to `kustomization.yaml`, then you execute `kustomize build`, the image configuration(s) are applied to deployment setting in runtime, afaik. Help message (`kustomize edit set image -h`) might be a good help for you.

**Comment by Liujingfang1** [comment]
Need to an example for any CI/CD pipeline with kustomize. Ideas and help are welcome.

**Comment by moismail109** [comment]
It was not an issue actually and It has been fixed already. Thanks a lot
