### ISSUE TITLE
Windows binary for v2.1.0?

### ISSUE THREAD

**Issue by erick-thompson** [kubernetes-sigs/kustomize#1212]
When should we expect a Windows binary for v2.1.0?

**Comment by alexeldeib** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/1374 is a blocker I assume, fwiw you can very easily patch this for version 2.1.0 or 3.0.3. e.g. https://github.com/alexeldeib/kustomize/releases/tag/v3.0.3-win which is the diff in that PR (lacking the tempfile cleanup).

**Comment by BenTheElder** [comment]
AFAICT windows is broken in the latest release, isn't this a blocker for kubectl?
CC @Liujingfang1 @monopole

**Comment by BenTheElder** [comment]
Thanks for the fix @alexeldeib

**Comment by monopole** [comment]
An official Windows release (i.e. distributed at https://github.com/kubernetes-sigs/kustomize/releases) is blocked by #834.

**Comment by Naramsim** [comment]
This issue shouldn't be marked as closed. The issue still persists. When #834 will be closed then you could also close this one.

**Comment by solacens** [comment]
Absolutely agree with @Naramsim

I come back today and I thought the issue has been fix because the issue has been closed for a while.

Now I leave with disappointment. 😢

**Comment by erick-thompson** [comment]
I agree - this issue should remain open until #834 is closed. Speaking of which, are we close to getting a Windows binary? It's been quite a while since we've had one, and it's starting to cause problems with users who want to use newer features but can't.

**Comment by alexeldeib** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/1496 is the blocker. The tests run but the configuration needs some further tweaking I think. And we probably want some configuration on the Github side (?) to make the checks look correct for PRs. 

I've been a bit squeezed recently on capacity, but would like to finish this soon.

**Comment by alexeldeib** [comment]
Since #834 is the known remaining issue, let's track status there for now. If we close that out and there are further issues to a windows binary we can track them in a meta-issue.
