### ISSUE TITLE
Add extensible transformation

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#122]
This is to make kustomize libraries more flexible and extensible. Consider a kustomization, if an extra transformation is allowed, then user can specify their own transformations, such as replacing certain field to other strings, filling an docker image name.

**Comment by Liujingfang1** [comment]
Some thoughts: an extended transformer reads in []byte and returns []byte. The transformer itself can be written in other language.  
For example, a transformer that patches multiple object based on matched labels need to
- filter the []byte to get resources to patch
- update the matched resources
- return the new []byte

**Comment by mxey** [comment]
When you say another language, do you mean running an external program that would need to have its own understanding of how to parse Kubernetes manifests?

I was just thinking, what about embedding Skylark? Just passing a data structure with the matching resources to a Skylark function and having the function return a modified version.

**Comment by mxey** [comment]
Actually, Jsonnet probably makes more sense than Skylark.

**Comment by monopole** [comment]
IMO, once #300 is in and #169 is closed, we've done enough to support for creation of simple variants on a base.

ksonnet, helm et al. already provide completely general transformation languages for folks that want that sort of thing.

**Comment by Liujingfang1** [comment]
With JSON patch support added and transformer configurations added, we can close this issue.
