### ISSUE TITLE
Modify VarSet to use a set data type

### ISSUE THREAD

**Issue by ian-howell** [kubernetes-sigs/kustomize#1223]
The `VarSet` type currently uses a slice [under the hood](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/types/var.go#L75). This will cause dramatic performance issues due to [multiple expensive calls to `copy`](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/types/var.go#L126) as well as [linear time lookups](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/types/var.go#L137-L141). I suggest switching from from `[]Var` to a more suitable type, such as `map[string]Var`, as this will cause many of the O(n) and O(n<sup>2</sup>) operations to drop to O(1).

**Comment by monopole** [comment]
https://stackify.com/premature-optimization-evil/

the code was "optimized" for debugging, not building kustomizations with tens of thousands of vars.

thanks though, appreciate the effort.
made comments on the pr - can accept it, but need a String method that retains existing behavior.
