### ISSUE TITLE
plugin was built with a different version of package...

### ISSUE THREAD

**Issue by objectiveous** [kubernetes-sigs/kustomize#1234]
aligning versions of kustomize and its dependencies w/ ones plugins is... challenging. Please consider documenting how to go about aligning versions or, but yet, provide real working examples w/ working go.mod files.

**Comment by Liujingfang1** [comment]
Kustomize v3.0.0 is coming with more docs.

**Comment by alexec** [comment]
I'm getting the same problem:

"plugin was built with a different version of package internal/cpu"

It's pretty clear I need to build this with the same env an kustomize was built with, but how to determine that?
