### ISSUE TITLE
provide a simpler local build scheme. 

### ISSUE THREAD

**Issue by objectiveous** [kubernetes-sigs/kustomize#1235]
building kustomize locally currently requires cloud-build-local and that requires: 

```Configure your project for the gcloud tool, where [PROJECT_ID] is your Cloud Platform project ID:```

Do I really have to understand the ins and outs of GCP in order to work w/ a core component of kubectl? 

Consider providing a simple Makefile and removing the dependency on platform specific build components.

**Comment by Liujingfang1** [comment]
You can run `go build cmd/kustomize/main.go` after clone the repo.

**Comment by Liujingfang1** [comment]
Yes, we can provide a Makefile for building the binary.

**Comment by anthonyho007** [comment]
Hi! Can I pickup this issue ?

**Comment by Liujingfang1** [comment]
@anthonyho007 Sure, feel free to create a PR for it.
