### ISSUE TITLE
Exec style plugin load failure when not executable. 

### ISSUE THREAD

**Issue by objectiveous** [kubernetes-sigs/kustomize#1236]
When an Exec style plugin is not executable and error is thrown with a misleading message: 

```Error: loading generator plugins: plugin /Users/kenpo/.config/kustomize/plugin/foo.bar.xx.com/v1/foopipelinetenat/FooPipelineTenat fails to load: plugin.Open("/Users/kenpo/.config/kustomize/plugin/foo.bar.apple.com/v1/acipipelinetenat/FooPipelineTenat.so"): realpath failed```

Notice that reference to ```FooPipelineTenat.so```. This is an exec style plugin not a go plugin, so there should be no expectation of a so file being present.

**Comment by Liujingfang1** [comment]
When the exec plugin is not found, Kustomize looks for a goplugin.
We can improve the error message for the case when the exec plugin file exists, but not executable.
