### ISSUE TITLE
TFS resource URL striped

### ISSUE THREAD

**Issue by mleneveut** [kubernetes-sigs/kustomize#1252]
Using latest version Kustomize v2.1.0 , we are having trouble trying to use a base TFS Git repository.

We have a overlays/ci/kustomization.yaml : 
```
resources:
- https://itfs.mycompany.com/MainCollection/InformationSystem/_git/devtools_basekustomize
```

And a `kustomize build overlays/ci` strips the URL to `https://itfs.mycompany.com/MainCollection/InformationSystem.git` : 
```
/usr/bin/git init /tmp/kustomize-969835344
/usr/bin/git remote add origin https://itfs.mycompany.com/MainCollection/InformationSystem.git
/usr/bin/git fetch --depth=1 origin master
```

We tried with `git::https://...`, with `git:ssh://...`, with  `InformationSystem//_git`, nothing works.

Modifying the source code and rebuilding it works : 

Setting `repoSpec.raw` instead of `repoSpec.CloneSpec()` at https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/git/cloner.go#L61

The git code is pulled in the /tmp/kustomize-xxx directory.

We can't figure out why the URL is striped if it contains a `_git`

But after we have other symlink problems : 

```
Error: accumulating resources: accumulating resources from '/tmp/kustomize-945955159/kustomization.yaml': evalsymlink failure on '/tmp/kustomize-945955159/kustomization.yaml' : lstat /tmp/kustomize-945955159/kustomization.yaml: permission denied
```

Doing it with sudo : 
```
sudo kustomize build overlays/ci
Error: accumulating resources: accumulating resources from '/tmp/kustomize-945955159/kustomization.yaml': security; file '/tmp/kustomize-945955159/kustomization.yaml' is not in or below '/home/devops/sources/devtools_helloworld/overlays/ci'
```

If I manually create the symlink `ln -s /tmp/kustomize-945955159 subgit` : 
```
2251217 lrwxrwxrwx 1 devops devops         24 Jun 16 19:46 subgit -> /tmp/kustomize-945955159
   6981    drwxrwxr-x 5 devops devops     4096 Jun 16 16:34 overlays
```

it works by setting ../../subgit in the overlays.

Anybody using TFS as git with kustomize ?

**Comment by mleneveut** [comment]
It works fine with a github URL :

```
resources:
- https://github.com/mleneveut/kustomize-base.git
```

**Comment by Liujingfang1** [comment]
In the remote url parsing, need to add the support for `_git`.

**Comment by etiennecoutaud** [comment]
@lichuqiang if help is needed, I can add the support.

**Comment by Liujingfang1** [comment]
@etiennecoutaud Yes, help is welcome and appreciated. You can open a PR for the change and we'll review it.
