### ISSUE TITLE
Remote Build from non-github sources

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kustomize#1272]
Is it possible to do a [remote build](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md) from a source other than github? The docs mention it follows https://github.com/hashicorp/go-getter#url-format format, which allows S3, GCS, etc, but I can't seem to get them working with kustomize.

Is this possible? Specifically I care about GCS.

**Comment by howardjohn** [comment]
From slack:

Yujun Zhang [5:56 PM]
AFAIK, `go-getter` is NOT supported at the moment. See discussion in https://github.com/kubernetes-sigs/kustomize/issues/923

dexhorthy [6:11 PM]
wow. TIL -- thanks for the correction @Yujun Zhang
that issue is interesting

Yujun Zhang [6:13 PM]
As @Liujingfang1 suggested, we may write a plugin to execute go-getter.
Not sure if `loaders` plugin has been supported in v2.1.0 or not.


So no, only github support currently

**Comment by saamalik** [comment]
@howardjohn - could you please re-open this bug? Would be great to see if someone could write a plugin to load from GCS Google Cloud Storage buckets.

**Comment by yujunz** [comment]
The plugin is available. See example in https://github.com/kubernetes-sigs/kustomize/blob/master/examples/goGetterGeneratorPlugin.md

Working also on a builtin integration in https://github.com/yujunz/kustomize/commit/f43f61e37d1c41c8af453139559caa6ea8bf9a3d . There were some concerns from @Liujingfang1 about the extra dependency introduced to support various remote. We may consider exec an external binary just as the git cloner in https://github.com/kubernetes-sigs/kustomize/blob/1a330f89d981aaa30e81755e7046267afe015f7b/api/internal/git/cloner.go#L21 and possibly make it configurable.

**Comment by howardjohn** [comment]
The plugin is useful for users, but as a developer of kustomize bases that we need to distribute to users we don't want to depend on users doing extra setup, so we are limited to the base kustomize. That is why gcs would be so nice, as we already publish our releases there

**Comment by yujunz** [comment]
Proposed an enhancement with go-getter module. Could you help test it on GCS? @howardjohn

**Comment by howardjohn** [comment]
Sure, I'll try it out later this weekend. Thank you!

**Comment by howardjohn** [comment]
Seems like it will fetch the kustomization.yaml ok, but doesn't grab all the depenencies?

```
$ go run main.go build https://storage.googleapis.com/howardjohn/kustomize/istio-ingress/
Error: Error demand directory "evalsymlink failure on 'https://storage.googleapis.com/howardjohn/kustomize/istio-ingress/' : lstat /home/howardjohn/go/src/sigs.k8s.io/kustomize/kustomize/https:: no such file or directory" and create loader "error downloading 'https://storage.googleapis.com/howardjohn/kustomize/istio-ingress/': bad response code: 404"
exit status 1
$ go run main.go build https://storage.googleapis.com/howardjohn/kustomize/istio-ingress/kustomization.yaml
2020/02/01 20:50:39 cannot load at directory "evalsymlink failure on '/tmp/kustomize-721250466/roles.yaml' : lstat /tmp/kustomize-721250466/roles.yaml: no such file or directory" nor load at git clone "url lacks orgRepo: roles.yaml"
Error: accumulating resources: accumulating resources from 'roles.yaml': evalsymlink failure on '/tmp/kustomize-721250466/roles.yaml' : lstat /tmp/kustomize-721250466/roles.yaml: no such file or directory
exit status 1
```

**Comment by howardjohn** [comment]
nevermind, I just was doing to go-getter syntax wrong.

```
go run main.go build gcs::https://www.googleapis.com/storage/v1/howardjohn/kustomize/istio-ingress/
```

works!

**Comment by yujunz** [comment]
Good. Is it a public and permanent repository suitable for integration test?

**Comment by howardjohn** [comment]
it's public but definitely shouldn't be used for integration test though, I just threw that up for a one off test. if needed I could put a more permanent one up somewhere but it probably makes more sense to put it in a kustomize/kubernetes owned gcs bucket?

**Comment by yujunz** [comment]
> kustomize/kubernetes owned gcs bucket?

Do we have such bucket? @kubernetes-sigs/kustomize-admins @kubernetes-sigs/kustomize-maintainers

**Comment by ipleten** [comment]
I'm interested in checkout from private Gitlab repo via ssh. And it also seems broken.
