### ISSUE TITLE
Kustomize not executable upon installation

### ISSUE THREAD

**Issue by jessica-dl** [kubernetes-sigs/kustomize#1276]
Upon installation using [these instructions](https://book.kubebuilder.io/quick-start.html) on my peers and my machines, kustomize was not immediately executable, causing issues when trying to deploy another application. 

A temporary fix was suggested in the kubebuilder book [quick start](https://github.com/kubernetes-sigs/kubebuilder/pull/825).

/kind bug

**Comment by monopole** [comment]
This is a bug in the kubebuilder docs.
try filing here:  https://github.com/kubernetes-sigs/kubebuilder/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.md&title=
