### ISSUE TITLE
kustomize 2.1.0 broke image tagging

### ISSUE THREAD

**Issue by Benjamintf1** [kubernetes-sigs/kustomize#1281]
If an image is changed or added in a jsonpatch, it no longer gets modified in the imagetag process. 

If we jsonpatch in a container(for example), and set it's tag(or change the image name).

In 2.0.3 it modifies the tag of the jsonpatched added image to be the correct tag

In 2.1.0 it does nothing. We did discover the workaround of adding another kustomize layer above for  image patching, but it seems like this shouldn't be necessary. (I don't see why jsonpatches wouldn't be applied before imagtaging)

**Comment by monopole** [comment]
can you throw in a test showing this, per this [note](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/bugs.md#a-great-report-is-a-bug-reproduction-test)
really speeds up the process to get regression coverage in place ASAP

**Comment by Benjamintf1** [comment]
Sorry about the lack of details, I'll try and include details as per the instructions if I notice anything going forward. I'll probably be able to test it next week when I'm off vacation.

**Comment by Benjamintf1** [comment]
@monopole Thanks for the fix, I got back and tested it and everything looks good to me.

**Comment by pianohacker** [comment]
This seems to be working as of kustomize 3.0. Thanks for the fix!
