### ISSUE TITLE
Inconsistency between execPlugin and goPlugin generators

### ISSUE THREAD

**Issue by ptemmer** [kubernetes-sigs/kustomize#1296]
goPlugins add a hash suffix to the generated resource name out of the box. This is not true for execPlugins, leaving the resource name as is.

**Comment by vreon** [comment]
I got pretty far into implementing a secret generator exec plugin and ran into this :dizzy_face:

From here, I'm not sure if I should be handling the hash suffix + ref replacement in a custom transformer, or what... but I'd definitely like to avoid reimplementing that if I can somehow rely on a built-in transformer.

**Comment by richardmarshall** [comment]
I have some thoughts on how we can enable this for exec plugins but haven't yet had a chance to write anything down. Hopefully will have some cycles in the next few days and can put together a PR to discuss the approach.

@monopole FYI ☝️

**Comment by richardmarshall** [comment]
@ptemmer @vreon Would appreciate your thoughts on if #1473 would work to resolve this inconsistency for your use cases.

**Comment by vreon** [comment]
That would solve the problem for my use case! I dig the approach of using annotations to pass information from generators to transformers.

**Comment by ptemmer** [comment]
@richardmarshall Yes, I think it would also solve my use case. Thank you!
