### ISSUE TITLE
edit set image does not quote tags that will become non-string values in YAML

### ISSUE THREAD

**Issue by dantman** [kubernetes-sigs/kustomize#1303]
The `kustomize edit set image` command sets `newTag` it does not quote it when necessary to ensure it remains a string.

I use hashes for tag names and by random chance I ended up with one starting with `0e`. Because in YAML this is considered a number rather than a string my deployments were silently not actually deploying.

This will be an issue for other people if their could tags look like numbers, booleans, etc...

**Comment by fantasy4z** [comment]
It's an issue in the wild.

I tag my docker images with `git rev-parse --short=8 HEAD`.
Yesterday I got `706798e8` which was parsed as a number by kustomize.

Please help fix this minor yet annoying issue. 😢

**Comment by pwittrock** [comment]
Could we use setters as an alternative to the `kustomize edit` commands?

**Comment by agemooij** [comment]
I can reproduce this with kustomize 3.5.5. 
I use `kustomize edit add annotation gitRev:3114577` (a short git hash that this time happens to start with a number). The resulting `kustomization.yaml` has the correctly quoted value:

```yaml
  commonAnnotations:
    gitRev: "3114577"
```

But when I use `kustomize build` the resulting yaml file has unquoted values and causes errors when interpreted by `kubectl apply`:

```yaml
  metadata:
    annotations:
      gitRev: 3114577
```

Are there any workarounds for this behavior?

**Comment by dantman** [comment]
@agemooij I've just been stuck adding a sed script after each kustomize edit command I have in a bash script.
```bash
sed -i '' "s/\(newTag: *\)\([0-9a-f]\{8\}\)/\1'\2'/" kustomization.yaml
```

That'll cleanup a newTag set by a `kustomize edit set image` command. You can tweak that for your annotation command.

**Comment by agemooij** [comment]
@dantman I didn't run into that specific one. Which edit command are you using? I am using `kustomize edit set image ...`, which creates a clear YAML String so no interpretation errors occur. 

My issue was with annotations, where the short git hash was the value. I worked around it for now by always adding a prefix.

**Comment by agemooij** [comment]
@dantman Ah, I now see that you were getting YAML interpretation errors from kustomize itself while I was getting them from the _results_ of running `kustomize build`.

With kustomize version 3.5.5, I get nicely quoted strings in the resulting `kustomization.yaml` file. Here's an example:

```
$ kustomize edit set image foo=bar:1234567
$ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: foo
  newName: bar
  newTag: "1234567"
```

Which version of kustomize are you using?

**Comment by fantasy4z** [comment]
Tested with kustomize v3.8.1.

```bash
$ kustomize edit set image foobar=foobar:706798e8
$ cat kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1                                                                                                                                                                      kind: Kustomization
images:
- name: foobar
  newName: foobar
  newTag: "706798e8"
...
```

I guess this bug is fixed by kyaml.
