### ISSUE TITLE
Error messages are not human friendly

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kustomize#1304]
Example: `error: MergeResourcesWithErrorOnIdCollision: id '"~G_v1_Namespace|~X|~P|istio-system|~S"' already used`

I have no clue what all of these symbols mean which makes this hard to debug. I *think* this means I have a duplicate namespace defined?

Another example: `error: rawResources failed to read Resources: GroupVersionKindName: resid.ResId{gvKind:gvk.Gvk{Group:"config.istio.io", Version:"v1alpha2", Kind:"attributemanifest"}, name:"istioproxy", prefix:"", suffix:"", namespace:"istio-system"} already exists b the map`

This one is even harder to understand, what does "already exists b the map" mean?

It would be great if the errors could be more humanly consumable for a better UX

**Comment by monopole** [comment]
agreed.  might try a later release though.  not sure where you are, but those strings aren't in head.

**Comment by howardjohn** [comment]
I'm on kubectl `Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}` so pretty recent, or does the kustomize support in kubectl lag behind?

**Comment by monopole** [comment]
kubectl 1.15 has kustomize 2.0.3 embedded.

Kustomize just released 3.0.0. 

See https://github.com/kubernetes-sigs/kustomize/releases

Not saying the error messages are vastly better, but many other things are improved.

**Comment by howardjohn** [comment]
Cool, I'll have to check that out. Feel free to close this if its been improved

**Comment by monopole** [comment]
Yeah, I'm sure these are better, though not perfect.
You won't see `~P` or `~S` again, and id collisions errors are improved.
```
kustomize build $target | kubectl apply -f - 
```
with v3 kustomize and v1.15 kubectl is the best option right now.

**Comment by johntellsall** [comment]
Error message "already exists b the map" still exists in latest Kubectl. I'm not sure how to check the Kustomize version.

```
$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
```

`error: rawResources failed to read Resources: GroupVersionKindName: resid.ResId{gvKind:gvk.Gvk{Group:"", Version:"v1", Kind:"Service"}, name:"wordpress", prefix:"", suffix:"", namespace:""} already exists b the map`

**Comment by Shell32-Natsu** [comment]
@johntellsall #1500 We have technical problems to update the kustomize version in kubectl. But we are working on it.
