### ISSUE TITLE
Use case for microservices project 

### ISSUE THREAD

**Issue by chunytan** [kubernetes-sigs/kustomize#1312]
I have been using Kustomize in simple projects and it works as expected. However, I am struggled to apply this to an existing project containing multiple microservices.

What I think it should look like: 
```
.
+-- app1
|   +-- kustomization.yaml
|   +-- app1-deployment.yaml
|
+-- app2
|   +-- kustomization.yaml
|   +-- app2-deployment.yaml
|
+-- app3
|   +-- kustomization.yaml
|   +-- app3-deployment.yaml
|
+-- overlays
|   +-- production
|    |  +--  kustomization.yaml
|    |  +-- patch.yaml
|   +-- staging
|    |  +--  kustomization.yaml
|    |  +-- patch.yaml

```
My main goal is to run “kustomize build ” on a specific app for a specific overlay(environment) but currently I cannot find the solution. The motivation is, upon development process, the modification of single microservice should not result in the (potential) re-rolling of existing services.

Are there any ways to e.g. let kustomize understand the existence of different components, or configure the base dynamically? And would it work if I need to have certain patches for certain components in the patch.yaml?

**Comment by bkuschel** [comment]
You could create app1, 2 & 3 subdirectories in production & staging that have kustomization.yaml files refering to the `resources` in the top level app 1,2 & 3 directories.  

To get the patches to work you probably need to create a custom transformer resource and at it as a `transformer` at the production and staging level kustomization.yaml that is referred to by the kustomization.yaml files in app1,2,3 subdirectories that takes the patches individually (you'd need to separate them out to individual files) and runs kustomize child process (using a temporary kustomization.yaml) on them one at a time (piped) and ignore failures.

Then you could execute kustomize build . in the production/app1 directory, for example and get the

**Comment by LeonardAukea** [comment]
Hi @bkuschel, Could you please elaborate on your answer or provide references with relevant info. What is not completely clear to me is  create `custom transformer resource`  and example would be awesome as well. We have a very similar issue as @chunytan. Also, is there any best  practices on handling cases like this? Thank you in advance!

**Comment by minorbug** [comment]
@chunytan Can you share your solution to this issue?
