### ISSUE TITLE
Distribute built-in plugins as part of the release

### ISSUE THREAD

**Issue by callicles** [kubernetes-sigs/kustomize#1313]
I've read through the caveat of plugins and it looks like the main point is that kustomize and plugins need to be compiled with the same dependencies to ensure that the link is happening properly.

That being said since some of the plugins are built-in by the kustomize team, the binary could also be distributed with the release. That would prevent user to have to build versions of kustomize for all deployments when using built in plugins.

Specifically I am trying to use the `PatchJson6902Transformer` to be able to reuse patches from a github repository

**Comment by Liujingfang1** [comment]
@callicles Are you writing a transformer on top of the `PatchJson6902Transformer`? You can import kustomize libraries when writing the transformer.
