### ISSUE TITLE
PodPreset selector not updated by kustomize

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes-sigs/kustomize#1319]
When creating prodpresets with kustomize the selector is not updated with the labels defined in commonLabels. It should work the same way that it does for services.

**Comment by Liujingfang1** [comment]
This should be related to the common label transformer [configurations](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/config/defaultconfig/commonlabels.go).

**Comment by benjamin-bergia** [comment]
Can I change this setting on my side?

**Comment by yujunz** [comment]
Yes, you can @benjamin-bergia 

Added an FAQ in https://github.com/kubernetes-sigs/kustomize/pull/1349
