### ISSUE TITLE
transformation for simultaneously update name and namespace 

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#1323]
When an object refers another object, sometimes, the reference needs both name and namespace. We have seen this pattern more than once. https://github.com/kubernetes-sigs/kustomize/pull/1321  and https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/namespacetransformer/NamespaceTransformer.go#L90

We can create a new transformer or extend current namereference transformer to update the name and namespace at the same time.

**Comment by jbrette** [comment]
@Liujingfang1 I'll try to address this one. The mirroring issue with ClusterRoleBinding happened in the namereference transformer where we have to use the namespace and the name to look for the replacement name See https://github.com/kubernetes-sigs/kustomize/pull/1325/commits/08ae6cb3012d8e98614747f254d6333b7f6bb8f7#diff-c9aa1ebf15951fe590c4241e95321901R142

**Comment by jbrette** [comment]
Fixed by [Update Namespace and Name simultaneously](https://github.com/kubernetes-sigs/kustomize/pull/1379)

**Comment by jbrette** [comment]
@Liujingfang1 The PR #1379 has been merged. We should close the bug
