### ISSUE TITLE
edit subcommand for creating a new kustomization.yaml

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#1329]
This could be used to support following use cases:
- create an overlay from a base
- create a kustomization directory from another kustomization directory
- optional: with parameters to set nameprefix, namespace, labels, annotations...

Thoughts or comments?

**Comment by yujunz** [comment]
Create a patch target. Currently I rely on copy and pasting the original resource and remove the unchanged parts.

Looking for something like `kustomize edit patch g/v/k name path` with auto complete support.

**Comment by yujunz** [comment]
Another use case:

Create `kustomizeconfig.yaml` with configurable options and guide comments and include it in `kustomization.yaml`

**Comment by richardmarshall** [comment]
This would definitely simplify the workflow for creating new overlays. I'd be happy to submit a PR or a google doc stubbing out the CLI UX for discussion if work hasn't been started on this yet.

> create a kustomization directory from another kustomization directory

Would the intent with this use case be to copy an existing directory and tweak some values (namespace, nameprefix, etc) in one command? Versus having to run `cp`, `kustomize edit ...`, `kustomize edit ...`, etc.

> Create kustomizeconfig.yaml with configurable options and guide comments and include it in kustomization.yaml

@yujunz Having a sub-command for managing the `.configurations` field would be nice, that brings up a broader question regarding the edit sub-commands. Does it make sense to keep the edit sub-commands in sync with all the top level kustomization fields or a more curated sub-set based on common use cases?
