### ISSUE TITLE
kustomize edit set image changes "bases" to "resources" inside kustomization.yaml

### ISSUE THREAD

**Issue by pfyod** [kubernetes-sigs/kustomize#1342]
As title says, running `kustomize edit set image` changes `bases` to `resources` inside kustomization.yaml

Here's the minimal example:
```
DEMO_HOME=$(mktemp -d)
mkdir -p $DEMO_HOME
cat <<EOF >$DEMO_HOME/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
EOF
cd $DEMO_HOME
kustomize edit set image test=test
cat kustomization.yaml
```

Expected output / kustomization.yaml content:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
images:
- name: test 
  newName: test
```

Actual output / kustomization.yaml content:
```
apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization
resources:
- ../base
images:
- name: test 
  newName: test
```

kustomize versions 3.0.1 & 2.1.0 are both affected

**Comment by richardmarshall** [comment]
The bases field was [deprecated in v2.1.0](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/v2.1.0.md#resources-expanded-bases-deprecated). The read / write cycle for the kustomization file with `kustomize edit` sub-commands will perform cleanup of deprecated fields in the same way as explicitly running `kustomize edit fix`.

Additional documentation is probably warranted to help make this less of a surprise.

**Comment by pfyod** [comment]
Whoops. I got confused by the differences between kubectl's built in kustomize and standalone... What I've been trying to do is run `kustomize edit set image` and then `kubectl apply -k`. That didn't work because kubectl's kustomize does not accept directories inside resources (yet, I guess). My bad!

**Comment by guhcampos** [comment]
I was about to open an issue about this exact problem. I have kustomize updating images on a gitops workflow and my resources were simply breaking up.

Whatever fixes kustomize is doing are not working: the resulting change breaks my previously working deploy, so at the very least it must not be a silent edit.

A warning with a return value different than zero, in my humble opinion, should be enough.

**Comment by rihardssceredins** [comment]
> Whoops. I got confused by the differences between kubectl's built in kustomize and standalone... What I've been trying to do is run `kustomize edit set image` and then `kubectl apply -k`. That didn't work because kubectl's kustomize does not accept directories inside resources (yet, I guess). My bad!

How did you get around this? Having the exact same issue.

**Comment by rihardssceredins** [comment]
> Whoops. I got confused by the differences between kubectl's built in kustomize and standalone... What I've been trying to do is run `kustomize edit set image` and then `kubectl apply -k`. That didn't work because kubectl's kustomize does not accept directories inside resources (yet, I guess). My bad!

@pfyod how did you get around this? Having the exact same issue.

**Comment by pfyod** [comment]
@rihardssceredins IMO, the only proper solution is not to use `kubectl -k` but rather something like `kustomize build <directory> | kubectl apply -f -`...

**Comment by jasper-d** [comment]
Looks like kubectl is currently still using kustomize 2.0.3. https://github.com/kubernetes/kubectl/blob/master/go.mod#L46

Direct download for those who need a compatible version (cannot get it using `install_kustomize.sh`): https://github.com/kubernetes-sigs/kustomize/releases/download/v2.0.3/kustomize_2.0.3_linux_amd64

**Comment by yurigene** [comment]
Still having the same issue in 2021!
kubctl & kustomize versions:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e12ee36645295b14a1c726bc104f0dbe8638bfbf", GitTreeState:"clean", BuildDate:"2021-02-05T07:45:55Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
{Version:kustomize/v4.0.1 GitCommit:516ff1fa56040adc0173ff6ece66350eb4ed78a9 BuildDate:2021-02-13T21:21:14Z GoOs:linux GoArch:amd64}
```

After running `kustomize edit set image` bases was changed to resources, but when after that I run `kubectl apply -k .` getting following error:
`error: rawResources failed to read Resources: Load from path ../../base failed: '../../base' must be a file`

**Comment by yurigene** [comment]
For those who still facing this problem there is a step by step explanation: https://codeflex.co/github-actions-deployment-to-eks-with-kustomize/
