### ISSUE TITLE
Support for commonNodeSelectors and commonTolerations 

### ISSUE THREAD

**Issue by sidps** [kubernetes-sigs/kustomize#1358]
Similar to how commonAnnotations works, it would bee useful to be able to apply a common set of nodeSelectors and tolerations that apply to all podSpecs referenced by a kustomization.yaml. 

This would allow running an entire application, defined by the kustomization.yaml, on dedicated hardware. So if I wanted to isolate production hardware from staging hardware, such a feature would enable that with ease. 

The current workaround is perhaps to patch each podSpec individually.

**Comment by richardmarshall** [comment]
We have a similar desire and are planning on writing external transformer plugins to set common nodeAffinity and tolerations for all podSpecs. nodeSelectors would be pretty trivial to include as well. If there is interest in this I can work on either opensourcing the external plugins we create and/or incorporating them as builtin transformer plugins.

**Comment by richardmarshall** [comment]
@sidps We actually decided today to use the new extended patch system that was merged in #1355 instead of a plugin to accomplish what we need with nodeAffinity maybe that would work for your use case as well.

**Comment by sidps** [comment]
We are using the patch system for now, as a workaround.

**Comment by mattmceuen** [comment]
Was a decision made around whether the commonNodeSelectors and commonTolerations might be added in the future?  This can be done via patching of course, but common* seems general-purpose and straightforward, and my project would use them if it were available.

**Comment by realshuting** [comment]
Is there a way to change the default patch strategy from `replace` to `merge` for `tolerations`? 

My use case is to add to `tolerations`, the following `patchesStrategicMerge` does not seem to work for me:
````yaml
        tolerations:
        - key: "node-role.kubernetes.io/test"
          effect: "NoSchedule"
          operator: "Exists"
          $patch: merge
````

**Comment by Shell32-Natsu** [comment]
@realshuting https://github.com/kubernetes-sigs/kustomize/issues/3265#issuecomment-732475022
