### ISSUE TITLE
no Go files found

### ISSUE THREAD

**Issue by bendiaz** [kubernetes-sigs/kustomize#1361]
when attempting to install kustomize with this command `go get -u github.com/kubernetes-sigs/kustomize`

I'm met with this error:

`package github.com/kubernetes-sigs/kustomize: no Go files in /home/benjamindiaz/go/src/github.com/kubernetes-sigs/kustomize`

I have minikube and kubectl installed on my machine. Working out of ubuntu 18.04

**Comment by jbrette** [comment]
@bendiaz Try that instead: go get -u sigs.k8s.io/kustomize/cmd/kustomize

**Comment by bendiaz** [comment]
It unfortunately didn't work. I'm met with this error:
`package sigs.k8s.io/kustomize/cmd/kustomize: unrecognized import path "sigs.k8s.io/kustomize/cmd/kustomize" (https fetch: Get https://sigs.k8s.io/kustomize/cmd/kustomize?go-get=1: x509: certificate signed by unknown authority)
`

**Comment by richardmarshall** [comment]
Seems like something is wrong with the CA certificates in your environment. Are you able to reach `https://sigs.k8s.io` without TLS errors by other means, browser, curl?

**Comment by benjamin-bergia** [comment]
Got the same initial error when trying to use the command from [here](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md#install-from-the-head-of-master-branch).
Would it be possible to update the doc to use @jbrette solution?
