### ISSUE TITLE
Error: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch

### ISSUE THREAD

**Issue by luisdavim** [kubernetes-sigs/kustomize#1373]
This was working file with `v3.0.0`, I've updated to `v3.0.3` and I'm getting the error:
```
Error: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch
```

This is the kustomization file:
```
# Adds namespace to all resources.
namespace: marquis-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: marquis-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
- ./rbac/rbac_role.yaml
- ./rbac/rbac_role_binding.yaml
- ./manager/manager.yaml
- ./rbac/auth_proxy_service.yaml
- ./rbac/auth_proxy_role.yaml
- ./rbac/auth_proxy_role_binding.yaml

patches:
- manager_image_patch.yaml
  # Protect the /metrics endpoint by putting it behind auth.
  # Only one of manager_auth_proxy_patch.yaml and
  # manager_prometheus_metrics_patch.yaml should be enabled.
- manager_auth_proxy_patch.yaml
  # If you want your controller-manager to expose the /metrics
  # endpoint w/o any authn/z, uncomment the following line and
  # comment manager_auth_proxy_patch.yaml.
  # Only one of manager_auth_proxy_patch.yaml and
  # manager_prometheus_metrics_patch.yaml should be enabled.
#- manager_prometheus_metrics_patch.yaml
```

**Comment by jbrette** [comment]
"patches:" was obsolete. You are supposed to use "patchesStrategicMerge:" instead.

Since "patches:" is used for more extended patching.

**Comment by luisdavim** [comment]
thanks, I guess that was it. I think the readme should be updated.

**Comment by functicons** [comment]
+1, I hit the same error. My yaml files were generated by kubebuilder, they worked with Kustomize v2, but upgrading Kustomize to v3.0.3 breaks it.

**Comment by jbrette** [comment]
Interesting...Was looking at the log. patches has been deprecated last year [v1.0.9](https://github.com/kubernetes-sigs/kustomize/blob/v1.0.9/pkg/types/kustomization.go#L129).

I guess we will have to check if kubebuilder needs to be updated. Meanwhile the easiest workaround is 
replaced `patches:` by `patchesStrategicMerge:`

**Comment by jbrette** [comment]
@functicons Created a PR in [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/pull/876)

**Comment by jmichalek132** [comment]
Hi since patches is obsolete, this [example](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md) should be removed or updated.

**Comment by leoskyrocker** [comment]
I think "patches" means something else - not obsolete as of today.
It is used for patching multiple objects at once via the same patch file.

**Comment by jmichalek132** [comment]
Okay so the use of "patches" above is not working because it's missing target? And with target it's still working/valid use?

**Comment by jgriff** [comment]
I think the problem is `kubectl` uses a much older version of `kustomize`.  It appears the "multiple patching" support was added in `v3.1.0` of `kustomize` (based on when `examples/patchMultipleObjects.md` was added in [this commit](https://github.com/kubernetes-sigs/kustomize/commit/b2967d2f773dc05c9c9a958bd9d6f596f249aee0)).

## Works in `kustomize` `3.5.4`

```shell
❯ kustomize version
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-17T14:23:25+00:00 GoOs:darwin GoArch:amd64}
```

**`overlays/my-overlay/kustomization.yaml`**
```yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: does-not-matter
      spec:
        template:
          spec:
            priorityClassName: my-priority-class
    target:
      kind: Deployment
```
This works:
```shell
kustomize build overlays/my-overlay
```

## But not in `kubectl` (`1.18`) with `kustomize` (`2.0.3`)

```shell
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-10T21:53:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
```
_Currently the only way to know which version of `kustomize` is used in `kubectl` is to [consult the README](https://github.com/kubernetes-sigs/kustomize#kubectl-integration), which currently states its using `v2.0.3`._

So this does **not** work:
```shell
❯ kubectl kustomize overlays/my-overlay
Error: AccumulateTarget: couldn't make target for {redacted}: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type patch.StrategicMerge
```

**Comment by leoskyrocker** [comment]
Yep that’s right

**Comment by manishtanwar19** [comment]
As opposed to pointed out in other comments, `patches` should be used only, as `patchesStrategicMerge` field was deprecated in v5.0.0.

The change that worked for me while using `patches:` only, was:

```
 patches:
- ./patch-deployment.yaml
- ./patch-hpa.yaml
```

```
 patches:
- path: ./patch-deployment.yaml
- path: ./patch-hpa.yaml
```

Adding `path:` in patches.

**Comment by Stef16Robbe** [comment]
> As opposed to pointed out in other comments, `patches` should be used only, as `patchesStrategicMerge` field was deprecated in v5.0.0.
> 
> The change that worked for me while using `patches:` only, was:
> 
> ```
>  patches:
> - ./patch-deployment.yaml
> - ./patch-hpa.yaml
> ```
> 
> ```
>  patches:
> - path: ./patch-deployment.yaml
> - path: ./patch-hpa.yaml
> ```
> 
> Adding `path:` in patches.

This can be automatically fixed by running `kustomize edit fix`.

**Comment by CameronHudson8** [comment]
I had loads of kustomization.yaml files to convert, and this is what I used to find and update all of them:
```
find -E . -iregex '.*/kustomization\.ya?ml$' | xargs -I'{}' yq -i '.patches = (.patchesStrategicMerge | map({ "path": . })) | del(.patchesStrategicMerge)' {}
```

**Comment by martinwunderlich-celonis** [comment]
Just came across this issue and had the same problem. It was due to a very complex env var value with several levels of escaping. I was able to fix by moving this env var from the literals in the configMapGenerator to an external env file.
