### ISSUE TITLE
$patch: delete on an object results in object name being retained

### ISSUE THREAD

**Issue by verult** [kubernetes-sigs/kustomize#1384]
Kustomize 2.1.0

kustomization.yaml
```
resources:
- base.yaml

patchesStrategicMerge:
- patch.yaml
```

base.yaml
```                                                
apiVersion: v1
kind: ServiceAccount
metadata:
  name: some-sa
```

patch.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: some-sa
$patch: delete
```
result:
```
metadata:
  name: some-sa
```

expected:
```
{}
```

**Comment by richardmarshall** [comment]
Deleting entire objects has never been a fully supported feature (see #106 and [eschewed features](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md)).

**Comment by verult** [comment]
Thanks for pointing this out, will close this issue then

/close

**Comment by verult** [comment]
Note this behavior is causing the fix for #768 to not work as expected - since the entry is non-empty, the namespace is still added to the object

**Comment by Liujingfang1** [comment]
Since `$patch: delete` is supported by Strategic Merge Patch. We should support it consistently.

**Comment by mengqiy** [comment]
Is it a good pattern using SMP to delete object in kustomize?
IIUC kustomize suggests additive patches.
If users don't need an object, it should not be generated in the first place.
It should be skipped by
```
resources:
#- base.yaml
```

**Comment by mengqiy** [comment]
Chatted with @Liujingfang1 offline a bit, it seems using patch to delete resources has been used by quite some users already. So supporting this doesn't make things worse.
