### ISSUE TITLE
support gcp cloud source repository

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#1386]
The cloud source repository url:
https://source.cloud.google.com/project/repo

```
git clone https://source.developers.google.com/p/[PROJECT_NAME]/r/[REPOSITORY_NAME]
git clone ssh://EMAIL@source.developers.google.com:2022/p/PROJECT_ID/r/REPO_NAME
git clone ssh://user@gmail.com@source.developers.google.com:2022/p/example-project/r/test-repo
```

**Comment by max-sixty** [comment]
Is there some format that works here? I can't get either `https://source.developers.google.com/p/[PROJECT_NAME]/r/[REPOSITORY_NAME]` nor the simpler `https://source.developers.google.com/[PROJECT_NAME]/[REPOSITORY_NAME]` to work. The latter worked with previous versions of kustomize

**Comment by max-sixty** [comment]
This seems to work:
```
  - https://source.developers.google.com/p/[project]/r/[repo].git//[path]?ref=[ref]
```
