### ISSUE TITLE
Documentation and Behavior Inconsistent for Bases

### ISSUE THREAD

**Issue by maxsmythe** [kubernetes-sigs/kustomize#1391]
Using kustomize v3.0.3 I tried to follow the same directory structure as the "hello world" example, but it was failing with:

```
$ kustomize build config/overlays/dev

Error: accumulating resources: accumulating resources from '../../../config': '/usr/local/home/smythe/go/src/github.com/open-policy-agent/gatekeeper/config' must be a file
```

The following reformat appears to have fixed the error:

https://github.com/open-policy-agent/gatekeeper/pull/190/commits/d9c0bd39695e97451f1843042ca07bed94b2074d

Note the relocation of the `overlays` directory.

I fixed the patchesStrategicMerge issue prior to the failure reported above. I also tried numerous ways of expressing the reference to the base kustomization.

Is the structure:

```
config/kustomization.yaml
config/overlays/dev/kustomization.yaml
```
intended to work?

Links to docs that demonstrate this layout:
https://github.com/kubernetes-sigs/kustomize/blob/cc531af66540bb312ccb494b5dbfa28738a0fde2/examples/helloWorld/README.md

https://github.com/kubernetes-sigs/kustomize/blame/dc6dcd815074318bd27a4a840fd53f07099e0712/README.md#L83

**Comment by stevegore** [comment]
If I'm not mistaken, you've circumvented the error by replacing `bases` with `resources` - is that right? You've got `resources` referencing the `config` directory just like you would if it were base (it contains a `kustomization.yaml` file). I was under the impression that `resources` had to be under or below the `kustomization.yaml` file so the fact that it works is surprising.

I'm getting the same error when nesting bases - i.e. using a base that already declares a base: `Error: accumulating resources: accumulating resources from '..': '/Users/steve/Source/repo-name/dev' must be a file`. Given the documentation states that bases should be directories the error is not very helpful.

**Comment by maxsmythe** [comment]
Renaming `bases` to `resources` didn't help. The only thing that helped was the rearranging of the directory structure.

`bases` was deprecated in favor of listing everything in `resources`

**Comment by stevegore** [comment]
Thanks @maxsmythe for the pointer regarding `bases` being deprecated.

Confirming my issue was resolved when I moved everything to a more flat directory structure.

**Comment by illeatmyhat** [comment]
I'm having the same issue and honestly I would rather not have to rearrange my files
```
resources:
- foo/bar/baz
```
should just work. It does work with `bases`, but doing the same with `resources` will give you this error:
`rawResources failed to read Resources: Load from path foo/bar/baz failed: 'foo/bar/baz' must be a file (got d='/Users/john.doe/project/foo/bar/baz')`

**Comment by stevegore** [comment]
> I had a similar issue and resolved it by using `kustomize build` rather than `kubectl kustomize .` It seems that whatever is integrated with kubectl 1.15 is out of date and will lead to confusion.

Definitely. For those wondering, the best syntax is probably `kustomize build <dir> | kubectl apply -f -`

**Comment by creinig** [comment]
I have a similar issue, using `kustomize build <DIR>` with kustomize Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T18:11:16Z GoOs:linux GoArch:amd64}

Referencing the base via

```
resources:
- ../
```

results in the described error message.

@illeatmyhat : What version of kustomize are you using?

**Comment by illeatmyhat** [comment]
@creinig I'm using version `{KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T18:11:16Z GoOs:darwin GoArch:amd64}`
I can reproduce your error--I don't attempt to reference base images in parent folders.
Incidentally, if you reference the kustomization.yaml directly
```
resources:
- ../kustomization.yaml
```
you will get this error:
```
Error: accumulating resources: accumulating resources from '../kustomization.yaml': security; file '/foobar/kustomization.yaml' is not in or below '/foobar/env'
```
which implies that you're not supposed to be able to do it anyways. I don't really understand how this dockerfile-like error is intended to help security though.

**Comment by kristianjaeger** [comment]
Are there any plans to update the examples / docs if there is a recommended directory structure to avoid this bug? Thanks.
