### ISSUE TITLE
Kustomize edit modify indentation of the whole file

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes-sigs/kustomize#1395]
Just noticed that in our CI pipeline.
For some reason when running `kustomize edit set image xxx:yyy` the whole kustomization.yml get re-indented. It fails passing our linter checks but also messes up the diff of the following commit.

By the way, it would be also nice to be able to specify the directory to use in `edit`, the same way that it is done for `build`.

**Comment by odannyc** [comment]
This is also an issue for me.
Is there a fix for this?

**Comment by Shell32-Natsu** [comment]
What kustomize does is reading the source file, parsing it into internal struct, modifying it and then serialize it. It only guarantees that the output is a valid yaml file but it's impossible to keep it *exactly and literally* same as the original one.

**Comment by bluebrown** [comment]
Would be nice to have a setting in some global kustomize config file. I.e. ~/.config/kustomizeconfig.yaml

**Comment by bharatiraja** [comment]
+1 after kustomize edit, our lint check fails. Specifically the array start indentation, yamllint expects it start at 2 but kustomize adds at 0. 
Any suggestions to fix it?
