### ISSUE TITLE
simpler kustomize version

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/kustomize#1408]
currently
```
$ kustomize version
Version: {KustomizeVersion:v2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8 BuildDate:2019-03-18T22:15:21+00:00 GoOs:darwin GoArch:amd64}
```

desired
```
$ kustomize version --something-to-make-life-easier
2.0.3
```

**Comment by richardmarshall** [comment]
Aligning with `kubectl version --short` would be a nice addition.

/help
/good-first-issue

**Comment by lcostea** [comment]
I can work on this.
Looks simple to start with and it is a good incentive to check the repo, build it, get familiar with it.
