### ISSUE TITLE
Support for arbitrary nameGenerators on single/arbitrary collections of resource types and paths

### ISSUE THREAD

**Issue by bd** [kubernetes-sigs/kustomize#1415]
It is possible that what I want is already supported, but after extensive inspection of the documentation I'm still don't know how to achieve my goal. 

In particular, I want to create a new Job with every `kubectl apply -k mydir/` based on the Job resource I have defined via the yaml file. As currently configured, this works the first time I apply the build, but since the Job is created with the same name each time, the second application fails with the error `Field Immutable` and a large json obj. 

If I use `generateName` instead of `name` in the `metadata` stanza of the Job definition yaml (which according to the docs is all I'm looking for), I get `error: rawResources failed to read Resources: missing metadata.name in object`. This makes sense in keeping with https://github.com/kubernetes/kubernetes/pull/44527, though I disagree with the underlying logic behind closing that case. 

Thus, I would like a way to specify, as with `ConfigMaps` and `Secrets`, a pattern for unique names of Jobs, and in theory, arbitrary resource types. 

The goal in general is to have a workflow in which 'kubectl apply -k` is the only command used in the normal course of deployment, meaning that the state of the cluster is entirely described by the files themselves (excepting the auto-generated suffixes), and does not rely on imperative operations.

**Comment by displague** [comment]
Do https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#nameprefix and https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#namesuffix provide the functionality you are looking for?

**Comment by bd** [comment]
No they do not. Those are static strings to append or prepend to _all_ the elements, which does not allow me to 1.) target only specific resource types or 2.) generate a unique name for each job, as required.

**Comment by dobesv** [comment]
I think a nice solution here would be to support "kustomize.config.k8s.io/needs-hash" on Jobs (and possibly arbitrary other resources).  It could rename the job according to a hash of the data in the resource spec.
