### ISSUE TITLE
create examples/docs for using kustomize library functions

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#142]
some examples to show how to use kustomize as library. Examples are like applying a patch, applying a name reference substitution

**Comment by BenTheElder** [comment]
Does kustomize support usage as a library? I'm very interested in this for configuration in [sigs.k8s.io/kind](https://sigs.k8s.io/kind)

**Comment by Liujingfang1** [comment]
@BenTheElder Yes, it does. If you want to apply kustomize build to a directory, you can try
```
kt, _:= target.NewKustTarget(rootLoader, fSys, "")
allResources, err := kt.MakeCustomizedResMap()
if err != nil {
   return err
}
// Output the objects.
res, err := allResources.EncodeAsYaml()
if err != nil {
	return err
}
if o.outputPath != "" {
	return fSys.WriteFile(o.outputPath, res)
}
// Write output to file
_, err = out.Write(res)
```
It is the same function calls as in `kustomize build` https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/commands/build.go#L117

**Comment by BenTheElder** [comment]
I've got something wrapping the `build` cobra command now for anyone else wanting to embed `kustomize build` as a library: https://github.com/kubernetes-sigs/kind/pull/77

**Comment by BenTheElder** [comment]
/remove-lifecycle rotten
I think what I actually need is just some unstructured patching code, currently these types (kubeadm config) aren't known as structured types to kustomize anyhow.

It would be nice if this logic could be re-used and had documentation :sweat_smile:

**Comment by akutz** [comment]
I also did some work on this [here](https://github.com/akutz/cluster-api-provider-vsphere/blob/feature/go-manifests/cmd/manifests/pkg/kustomize/kustomize.go). It eschews the need for the external `kustomize` command, and even supports virtual patches.

**Comment by migueleliasweb** [comment]
> It is the same function calls as in `kustomize build` https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/commands/build.go#L117

In the case someone is (like myself) looking for ways to embed kustomize and stumbles across this issue, here's a more recent link to the above function: https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/commands/build/build.go#L69
