### ISSUE TITLE
Placement for plugins

### ISSUE THREAD

**Issue by guludo** [kubernetes-sigs/kustomize#1463]
Hi there!

Currently, according to the docs, custom plugins are supposed to be placed under `$XDG_CONFIG_HOME/kustomize/plugin`. I believe there are some issues regarding that approach:

1. *It makes distributing plugins not very convenient*, as opposed to having them installed via a package manager. It would be nice if `kustomize` could look for plugins from a system-wide standard location like `/usr/lib/kustomize/plugins/`.
2. If I have plugins in a different location, I'd have to:
    1. Override `XDG_CONFIG_HOME`, which does not feel right, since conceptually that variable relates more to the user's environment than to `kustomize`.
    2. Necessarily maintain the structure `kustomize/plugin` under my custom directory, and it seems to me that that *should not be necessary* -- I could keep my plugin under `my_custom_dir/myDevOpsTeam/sillyconfigmapgenerator`, for example (instead of `my_custom_dir/kustomize/plugin/myDevOpsTeam/sillyconfigmapgenerator`).

With that said, my proposal for addressing those issues is to:

1. **Define standard search paths for plugins**. It could be the following (in that order):
    1. System-wide plugins: `/usr/lib/kustomize/plugins/`. I believe that could be the default value, but we should allow it being changed at build time (for distributions that wish to use a different location).
    2. User plugins: `$XDG_CONFIG_HOME/kustomize/plugin`, which is the one currently used. (Could also be `$XDG_CONFIG_HOME/kustomize/plugins`, just me being silly and picky :stuck_out_tongue:)
2. **Allow extra search paths for plugins**. This could come in two flavors:
    1. Environment variable `KUSTOMIZE_PLUGINS` containing search paths separated by `:`. And those would not need to have the `kustomize/plugin` subpath.
    2. A field named `pluginDirs` in `kustomization.yml` as a list of places to search for plugins. This is particularly useful for the case when one desires to ship her custom plugins alongside the kustomization files (*that's my case :smiley:*). Also, those paths would not need to have the `kustomize/plugin` subpath.

Looking forward to hear your thoughts on this!

Regards,
Gustavo Sousa

**Comment by embik** [comment]
/reopen

(hope I'm able to do this)

this would still be a nice addition to distribute kustomize plugins with a git repository (and set `KUSTOMIZE_PLUGINS=$(pwd)/plugins`, for example).

**Comment by embik** [comment]
@guludo can you re-open this? It's still relevant.

**Comment by guludo** [comment]
Sure.

/reopen
/remove-lifecycle rotten

**Comment by numbsafari** [comment]
The last option discussed in the original submission would be helpful in my case.

We would like to use plugins that are specific to our codebase, not for redistribution. Being able to have those be a part of the repository, having their behavior versioned along with the rest of our code, would be very helpful. It's actually kind of odd that this isn't the default case, to be honest.

Regardless, I would love to see either a CLI arg to specify the plugin path, or possibly follow the same mechanism as base resolution and make them relative to the kustomization file (realizing that could get complicated).
