### ISSUE TITLE
There is an ingress.yaml in overlay but base doesn't have ingress.yaml.It failed to build finally.

### ISSUE THREAD

**Issue by zkcarterlau** [kubernetes-sigs/kustomize#1477]
All my java projects share only one base.There are service.yaml,deployment.yaml in base while there are  service.yaml,deployment.yaml and ingress.yaml in overley in java porject.It showed me "Error: no matches for OriginalId extensions_v1beta1_Ingress|~X|java.." when I tried to kustomize build.
 
  However, when I put an ingress.yaml  in base I succeeded to kustomize build.The question is I don't need all my java projects to deploy ingress but I what to share the same base at the same time.

**Comment by richardmarshall** [comment]
Hi @zkcarterlau. Will need some more information to be able to help. Could you please share how you have setup your base and overlay kustomization.yaml files?

**Comment by zkcarterlau** [comment]
Sure, you can download deployment files here http://cnbj2.fds.api.xiaomi.com/viomi-fileupload/deployment.zip?GalaxyAccessKeyId=5151729087601&Expires=1566784948308&Signature=IN73IAqA5bLVuGO5NTa3jwXDM60=

When I exclude the ingress.yaml file in base it doesn't work.I don't need all the java apps share the same base which has ingress.Thanks for help.

**Comment by zkcarterlau** [comment]
@Liujingfang1 Yes,there is patchesStrategicMerge config in base kustomization.yaml. Sorry for the expired link. Here is another link---->http://cnbj2.fds.api.xiaomi.com/viomi-fileupload/deployment.zip?GalaxyAccessKeyId=5151729087601&Expires=9223372036854775807&Signature=WFEIPkJ7M5kwhCy2DPSCDNVy06A=

**Comment by zkcarterlau** [comment]
done
