### ISSUE TITLE
[question] should kustomize support version managed and just generate part of config? 

### ISSUE THREAD

**Issue by HusterWan** [kubernetes-sigs/kustomize#1497]
As we know, kustomize can manage multi-cluster configurations, and by using `build` command will generate a total config of a cluster. 

It is convenient when we just initialize a k8s cluster, but when we want to update the k8s cluster configurations, it is dangerous to apply all configurations to the cluster.

So we may consider the kustomize can support two features:
  * support version management: we can use the old version to rollback when the new configuration got something wrong.
  * support just generate a part of configuration: so that we can just update specified component's configuration

I don't know my idea is right, maybe anyone can tell me how to deal with the situation I  focus de? thanks a lot.

**Comment by jbrette** [comment]
@HusterWan This is partly the goal of this [KEP](https://github.com/kubernetes/enhancements/pull/1231) and [PR](https://github.com/kubernetes-sigs/kustomize/pull/1451).

Without that feature, users are quite often running:
kustomize build . | somefilterpythonscript | kubectl apply -f -

If the structure of your kustomize tree is simple, your can always create a filter transformer and add it to the latest entry of the transformers: list of your top level/last overlay kustomization.yaml

/cc  @ian-howell
