### ISSUE TITLE
Is there a better way to get DefaultSrcRoot in compile.go in test

### ISSUE THREAD

**Issue by nimohunter** [kubernetes-sigs/kustomize#1502]
hello, i'm new to this repo, and follow the good first issue, find #1182 interest me.

so i run `ConfigMapGenerator_test.go` but a find use `DefaultSrcRoot` to get plugin go source code, but maybe from global gopath , .config, or /home/yourname/kustomize does not meet our requirement... 

Is there a more elegant way to solve this?
thanks

**Comment by jbrette** [comment]
@nimohunter Try this way:  

```bash
go test -v ./plugin/builtin/configmapgenerator/...

=== RUN   TestConfigMapGenerator
--- PASS: TestConfigMapGenerator (3.30s)
PASS
ok      sigs.k8s.io/kustomize/plugin/builtin/configmapgenerator 3.355s
```

**Comment by nimohunter** [comment]
@jbrette thanks! It's work! but do you know how to work in jetbrain goland ide?  I click the test button in goland IDE and return error, so i add a little code in `DefaultSrcRoot` . i know it's not good, but it's work..
