### ISSUE TITLE
kustomize logging

### ISSUE THREAD

**Issue by Arun-devsecops** [kubernetes-sigs/kustomize#1512]
Hello,
Is there a way to turn on logging in Kustomize to see what it is doing>? This is essentially helpful if we use github as the bases for kustomize. When kustomize is attempting to resolve bases it is helpful to find out what is going on.

Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T19:21:45+01:00 GoOs:darwin GoArch:amd64}

**Comment by rosscdh** [comment]
great question +1

**Comment by jcmcken** [comment]
I would also like to see this functionality, after spending an embarrassing amount of time using manual trial and error to figure out why Kustomize wasn't rendering the objects the way I expected. There's literally no feedback in this tool and it makes it pretty hostile to users.

Can we add some kind of tracing/debugging functionality (e.g. via a CLI option) that steps through the transformations in detail? For example, logs the before and after structs for each transformation and where in the code the transformation is occurring?

**Comment by c10l** [comment]
Yes, please. It's very hard to troubleshoot issues without knowing what kustomize is trying to do.

**Comment by jfklingler** [comment]
> Is there a way to turn on logging in Kustomize to see what it is doing>? This is essentially helpful if we use github as the bases for kustomize. When kustomize is attempting to resolve bases it is helpful to find out what is going on.

That seemed pretty clear to me. Like, `--debug` to turn on logging like `DEBUG: Fetching URL https://blah.com/blah.yaml`.

Is there really a need to open a new issue? It wouldn't be a similar topic - it would be the exact same topic.

**Comment by larrywest** [comment]
Given the complexity implied by importing bases and the absolute opacity in which this is done, a `--verbose` or `--debug` flag, as most developer tools have, seems like a natural feature.

Without that, it's hard to scale this to be used by developers who aren't familiar with kustomize, since there's at best a vague hint as to where they should look to find the origin of particular lines.

It truly surprises me that the active maintainers here didn't embrace this very straightforward suggestion.

**Comment by sftim** [comment]
> It truly surprises me that the active maintainers here didn't embrace this very straightforward suggestion.

Until there's code to review, maintainers' only option would be to find time to do the work themselves.
I recommend filing a **feature request**; this one was framed as a support query.

**Comment by larrywest** [comment]
Ah, thanks: my mistake.  And I realize I should _really_ submit a PR ... but face the same problem as you: limited time.
