### ISSUE TITLE
inventory plugin fails with length error for large # of objects

### ISSUE THREAD

**Issue by jack0** [kubernetes-sigs/kustomize#1516]
I tried the [inventory plugin](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/inventory_object.md) and found that it will fail if there are too many k8s objects because the annotation `kustomize.config.k8s.io/Inventory` exceeds the max annotation length. We are trying to use it with cli-experimental to automatically clean up old deployments but are unable to do so due to this limitation.

**Comment by Liujingfang1** [comment]
@jack0 Yes, using annotation has this limitation. How many objects do you have that exceeds the limit? Can you do a manual clean up at the beginning? Then after that, run `prune` after every `apply`.

**Comment by jack0** [comment]
We have over 300+ objects total (100s of deployments each with an associated ingress and service object) per deployment. Currently, we can't even create the initial inventory ConfigMap nor can we do a manual cleanup at the beginning. I wonder if we can encode the data currently in the inventory in an inverse bloom filter so that we can know for certainty which objects to prune...

**Comment by jack0** [comment]
@jbrette If we do it this way, we still need the cli-experimental tool to be able to diff between the folder output and that of a running cluster. I'm not sure how that workaround would help in that case.
