### ISSUE TITLE
Ideas on how to prevent accidental deployment to production?

### ISSUE THREAD

**Issue by pascalgn** [kubernetes-sigs/kustomize#1530]
Say we have the following file structure:

```
kustomize-files
├── README.md
├── base
│   ├── app1
│   │   ├── app1.yaml
│   │   └── kustomization.yaml
│   └── app2
│       ├── app2.yaml
│       └── kustomization.yaml
└── env
    ├── staging
    │   ├── kustomization.yaml
    │   └── patches.yaml
    └── production
        ├── kustomization.yaml
        └── patches.yaml
```

And in both `env/staging/kustomization.yaml` and `env/production/kustomization.yaml` we have something like

```yaml
bases:
  - ../../base/app1
  - ../../base/app2
```

Now we change `base/app1/app1.yaml`, for example we switch our proxy server from nginx to traefik. We will then deploy these changes to staging and check if they are working.

The problem here is, by changing files in the `base` directory, we also affect the production environment and the next time someone runs `kustomize` in the production directory, they would also get these new changes (traefik instead of nginx). Before, we just had a directory `staging` and a directory `production` and manually copied files between these directories. Changes in one directory did not affect the other.

**How could we make sure that in the meantime, nobody accidentally deploys these changes to production?** Did anyone else have this problem and maybe found a solution already?

**Comment by nabadger** [comment]
You could use branches:

- `master` - stable / latest
- `staging|qa` 
- `production`

It obviously adds extra steps in terms of PR's, but gives you this protection.

**Comment by nabadger** [comment]
Also see https://kubectl.docs.kubernetes.io/pages/app_composition_and_deployment/structure_branches.html

I guess the issues / concerns here are how you actually promote changes. For example do you always go via `staging` to get `production`. 

There's obviously going to be prod specific updates you won't require in other environments (prod-specific resource settings for example). 

Going straight from master -> production in this manner (and sometimes via staging) could well lead to conflicts. This is our current concern, but not sure how well it works in practise.

**Comment by pascalgn** [comment]
Thanks for the reply! We were thinking about branches, but as you said, it depends on how you're going from staging to production. For us it would add too much complexity, I think, as sometimes we will try out multiple things on staging and we cannot simply merge everything. So then we would need to cherry-pick, which could lead to conflicts and/or confusing history quite quickly, but not sure yet.

Also, thanks for the link, I didn't know this document exists!

What I'm thinking now is having the `env/production` folder, but an additional `env/production/generated.yaml`, so that one needs to explicitly store the generated yaml in this file, from where it gets applied. This would have the advantage that in the diff, you could get the complete diff of what will be applied to production. It has the drawback, however, that the secrets would be stored in plain text in this file (we currently use sops to encrypt them in the repository)

**Comment by nabadger** [comment]
We also pre-render like this - it's very useful as it allow you to run golden tests (i.e. against expected output). Helpful when testing kustomize upgrades.

You could also look at https://github.com/bitnami-labs/sealed-secrets - this allows you to commit secrets (which are really secret), and the in-cluster controller does the de-cryption.

**Comment by max-sixty** [comment]
We found an approach of splitting up the change 'vectors' into two repos very helpful:
1. Your app, containing all your code, dependencies, etc
2. Your deployments, containing multiple kustomize deployments

These are two different vectors—you can change your app without changing what version is deployed. In particular, when you're ready to deploy to production, you can change the app version / tag in your deployment repo's `production` template. 

`master` of your deployment repo is always the deployed version. `master` of your app repo is your latest code (which might be deployed in a staging repo with CD). So there's no need to have complicated branch workflows.

**Comment by pascalgn** [comment]
To wrap this up: In the end we decided to keep it fairly simple and just copied the folder. So the structure is now

```
kustomize-files
├── README.md
├── base
│   ├── app1
│   │   ├── app1.yaml
│   │   └── kustomization.yaml
│   └── app2
│       ├── app2.yaml
│       └── kustomization.yaml
└── env
    ├── staging
    │   ├── kustomization.yaml
    │   └── patches.yaml
    └── production
        ├── .base
        │   ├── app1 [...]
        │   └── app2 [...]
        ├── kustomization.yaml
        └── patches.yaml
```

The `env/production/kustomization.yaml` is basically the same as `env/staging/kustomization.yaml`, but references `./.base/...` (the copy)

Now we regularly copy the `base` folder to `env/production/.base`, whenever the changes have been tested and we feel safe to apply them to production.

Pro:
- Explicit, easy to understand
- No additional tooling needed
- Commands like `git log -p -- env/production` give meaningful output

Contra:
- In GitHub, there is the possibility to protect branches, but not directories, so there isn't an easy way to limit access to production settings
- People could edit files in `env/production/.base` (accidentally or on purpose), leading to a "drift" between the real base and env/production/.base
- When copying, people could forget to delete old files first (could be solved by a shell script like `rm -rf env/production/.base && cp -r base env/production/.base`)
- During code navigation (e.g. in Visual Code), files in base will be displayed twice (once from base, once from env/production/.base)

Due to the first item in the contra list, we might switch to branches at some later point, but for now this workflow is running quite nicely for us.

Thank you everyone for your input! 👍

**Comment by scurvydoggo** [comment]
In case anyone finds this thread, we found a way of pinning `base` without copying files:

**prod/kustomization.yaml:**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/MyOrg/MyApp/base?ref=21221925d047df6906f15864bd1deff5fb5f00ab
```
