### ISSUE TITLE
apply -k --dry-run should not require server auth

### ISSUE THREAD

**Issue by hk-vmg** [kubernetes-sigs/kustomize#1533]
```bash
$ kubectl apply -k ./ --dry-run -o yaml 
error: unable to recognize "./": Unauthorized
```

But this works fine after loading valid tokens for Kubernetes access. This implies that something is trying to contact the K8s API server even when running in dry-run mode. It would be extremely useful if it were possible to test kustomize without server access. (The existing behavior makes lots of sense for --server-dry-run.)

```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by rochacon** [comment]
@hk-vmg have you tried offline rendering using `kubectl kustomize` or straight with `kustomize` binary instead?

Also, not sure this issue should be here or on kubernetes/kubernetes repo, since kubectl itself lives there.

Kind of related to https://github.com/kubernetes/kubernetes/issues/77332

**Comment by hk-vmg** [comment]
Thanks - this is clearly a duplicate of  kubernetes/kubernetes#77332
