### ISSUE TITLE
multi-namespace issue with kubectl version 1.14-1.16

### ISSUE THREAD

**Issue by MxNxPx** [kubernetes-sigs/kustomize#1543]
Hello,
When attempting to run through the documentation for multi-namespace setup here:
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/multibases/multi-namespace.md

Using (kubectl v1.14.0, 15.0, and v1.16.0) this command to build:
`kubectl kustomize $DEMO_HOME`

I get the following:
Error: rawResources failed to read Resources: Load from path namespace-a failed: 'namespace-a' must be a file (got d=$LOCALAPPDATA\Temp\tmp.3H3pUT8W2r\namespace-a')

Is this approach no longer supported?  And if so, can the documentation be updated to reflect what is now supported to solve for the multi-namespace use-case?

Thanks!

**Comment by MxNxPx** [comment]
Also tried it with kustomize (v2.0.3) directly and got the same error:

`# kustomize build $DEMO_HOME`
> Error: rawResources failed to read Resources: Load from path namespace-a failed: 'namespace-a' must be a file (got d='$LOCALAPPDATA\Temp\tmp.3H3pUT8W2r\namespace-a')

**Comment by jbrette** [comment]
@MxNxPx kubectl 1.16 is still using kustomize 2.0.3

**Comment by MxNxPx** [comment]
I proposed a change to the documentation so it would work with kustomize 2.0.3 and above:
https://github.com/kubernetes-sigs/kustomize/commit/230ad0652a7375c6d374c353f8e8db3193e1557d
