### ISSUE TITLE
`kustomize edit add base` command adds dir as resource and not base

### ISSUE THREAD

**Issue by reegnz** [kubernetes-sigs/kustomize#1556]
# Version
```
➜ kustomize version
Version: {KustomizeVersion:3.2.0 GitCommit:a3103f1e62ddb5b696daa3fd359bb6f2e8333b49 BuildDate:2019-09-20T10:10:22+02:00 GoOs:darwin GoArch:amd64}
```

# Expected behavior
The command `kustomize edit add base ../base` should add a base to the kustomization file:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
```

#Actual behavior
Running the `kustomize edit add base ../base` command results in this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
```

# How to reproduce
```
~
➜ mkdir test

~
➜ cd test

~/test
➜ mkdir base

~/test
➜ mkdir overlay

~/test
➜ cd base

~/test/base
➜ touch kustomization.yaml

~/test/base
➜ cd ..

~/test
➜ cd overlay

~/test/overlay
➜ touch kustomization.yaml

~/test/overlay
➜ kustomize edit add base ../base

~/test/overlay
➜ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
```

**Comment by linkvt** [comment]
Hi, see https://github.com/kubernetes-sigs/kustomize/blob/master/docs/v2.1.0.md#resources-expanded-bases-deprecated

**Comment by reegnz** [comment]
Would it be possible for kustomize to explicitly warn about these deprecation on stderr?

**Comment by brunojcm** [comment]
> Hi, see https://github.com/kubernetes-sigs/kustomize/blob/master/docs/v2.1.0.md#resources-expanded-bases-deprecated

Thanks for pointing that out!

The issue is, I'm trying to apply my newly created `kustomization.yaml` file, after the relocation, and I get:

```
$ kubectl apply -k .
error: rawResources failed to read Resources: Load from path ../base failed: '../base' must be a file (got d='/Users/bruno.medeiros/git/apps-portal/base')
```

It seems that `kubectl` is failing when there is a resource that is a directory, not a file.

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-e9b1d0", GitCommit:"e9b1d0551216e1e8ace5ee4ca50161df34325ec2", GitTreeState:"clean", BuildDate:"2019-09-21T08:33:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Do you know where can I report that?

**Comment by reegnz** [comment]
Another thing that is quite confusing with the deprecation is that only using `resources` breaks kubectl apply -k, since kubectl doesn't really know about that deprecation yet...

So now if you edit kustomizations with the kustomize cli and not by hand they won't be compatible with kubectl.

eg.:
```
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

➜ kubectl apply -k local
error: rawResources failed to read Resources: Load from path ../base failed: '../base' must be a file (got d='/Users/reegnz/example/base')
```

My kustomization in that case looks like this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
```

When can one expect a feature to also drip downstream into kubectl?
Also how can I find out what features are in downstream kubectl and what I cannot use with kubectl apply -k?

**Comment by tomjohnburton** [comment]
I am still getting this error.
```
$ kustomize edit add base ../../../bases/environment/staging-base

```
```
resources:
- Ingress.yml
- ../../../bases/microservice/services/account
- ../../../bases/environment/staging-base
```

**Comment by marcusjwhelan** [comment]
@tomjohnburton  @reegnz https://github.com/kubernetes-sigs/kustomize/issues/1647#issuecomment-567367909 It worked for me as well using `bases:` instead of `resources`

working on windows docker for desktop
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pommelinho** [comment]
> Another thing that is quite confusing with the deprecation is that only using `resources` breaks kubectl apply -k, since kubectl doesn't really know about that new feature yet...
> 
> So now if you edit kustomizations with the kustomize cli and not by hand they won't be compatible with kubectl.
> 
> eg.:
> 
> ```
> ➜ kubectl version
> Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
> 
> ➜ kubectl apply -k local
> error: rawResources failed to read Resources: Load from path ../base failed: '../base' must be a file (got d='/Users/reegnz/example/base')
> ```
> 
> My kustomization in that case looks like this:
> 
> ```
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> 
> resources:
>   - ../base
> ```
> 
> When can one expect a feature to also drip downstream into kubectl?
> Also how can I find out what features are in downstream kubectl and what I cannot use with kubectl apply -k?

hey are there any news?

**Comment by reegnz** [comment]
@pommelinho Didn't use kustomize for a while now, but checking the go.mod for kubectl: 

https://github.com/kubernetes/kubectl/blob/18e781fa774127786b5a2092ed2dc0351dafdb87/go.mod#L46

Nope, it's still the same kustomize version that's used. :(

**Comment by marcellodesales** [comment]
Any news on this???? Still with a problem with kubectl... 

```console
$ kubectl apply -k env/xxxx-westus-ppd-dev
error: rawResources failed to read Resources: Load from path ../../base failed: '../../base' must be
   a file (got d='/Users/marcello.desales/dev/gitlab.xxx.com/xxx/yyy/k8s/helm/charts/agent/output/agent/templates/base')
```

**Comment by oofpez** [comment]
Also experiencing this.  Using `kustomize build` works, but `kubectl kustomize` gives me this error.

**Comment by Shell32-Natsu** [comment]
We are in the last (hopefully) step to remove apimachinery from kustomize. #2506 is used to track this work.

**Comment by AntonFriberg** [comment]
Seems like it is still an issue with kubectl 1.20.5

Using the multibase example from https://github.com/kubernetes-sigs/kustomize/tree/master/examples/multibases
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ git clone --depth 1 git@github.com:kubernetes-sigs/kustomize.git
$ cd kustomize/example/multibases
$ kubectl kustomize .
Error: rawResources failed to read Resources: Load from path dev failed: 'dev' must be a file (got d='/home/antonfr/Git/github/kustomize/examples/multibases/dev')
```

It still works without issue using `kustomize build`.

```
$ kustomize build .
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: cluster-a-dev-myapp-pod
spec:
  containers:
  - image: nginx:1.7.9
    name: nginx
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: cluster-a-prod-myapp-pod
spec:
  containers:
  - image: nginx:1.7.9
    name: nginx
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: cluster-a-staging-myapp-pod
spec:
  containers:
  - image: nginx:1.7.9
    name: nginx
```

**Comment by natasha41575** [comment]
this is fixed in the most recent version of kubectl.
