### ISSUE TITLE
Less restrictive selectors for patching

### ISSUE THREAD

**Issue by linkvt** [kubernetes-sigs/kustomize#1568]
Hi,

we wanted to patch three PVs with a single patch as they all need the same configuration. When trying to do this we found out, that we have to specify three patches with almost the exact same content.

IMO patches should not have such strong requirements on the selectors, they should just find all that match and patch all of them.
The restriction [specified here](https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#patchesstrategicmerge) does not make sense to me ` (by Group/Version/Kind + Name/Namespace).`

Please share your view or alternative solutions, thanks!

**Comment by bzub** [comment]
Hi @linkvt have you tried the transformations detailed in the [patch-multiple-objects document](https://github.com/kubernetes-sigs/kustomize/blob/v3.2.0/examples/patchMultipleObjects.md)?

**Comment by linkvt** [comment]
Thanks @bzub, works like a charm!
Info for all trying to use `kubectl`, it might not work if an outdated version of kustomize is used.
