### ISSUE TITLE
New release tag format seems to break go modules

### ISSUE THREAD

**Issue by rochacon** [kubernetes-sigs/kustomize#1572]
Last two release tags have prefixes `pluginator/` and `kustomize/` and this seems to break Go modules normal usage. Could we also provide normal tags for main kustomize releases, e.g., `v3.2.1`?

```
λ go get -v sigs.k8s.io/kustomize/v3@v3.2.0
go: finding sigs.k8s.io v3.2.0
go: finding sigs.k8s.io/kustomize v3.2.0
go: finding sigs.k8s.io/kustomize/v3 v3.2.0
go: downloading sigs.k8s.io/kustomize/v3 v3.2.0
go: extracting sigs.k8s.io/kustomize/v3 v3.2.0
```

```
λ go get -v sigs.k8s.io/kustomize/v3@v3.2.1
go: finding sigs.k8s.io/kustomize/v3 v3.2.1
go: finding sigs.k8s.io v3.2.1
go: finding sigs.k8s.io/kustomize v3.2.1
get "sigs.k8s.io/kustomize": found meta tag get.metaImport{Prefix:"sigs.k8s.io/kustomize", VCS:"git", RepoRoot:"https://github.com/kubernetes-sigs/kustomize"} at //sigs.k8s.io/kustomize?go-get=1
get "sigs.k8s.io/kustomize/v3": found meta tag get.metaImport{Prefix:"sigs.k8s.io/kustomize", VCS:"git", RepoRoot:"https://github.com/kubernetes-sigs/kustomize"} at //sigs.k8s.io/kustomize/v3?go-get=1
get "sigs.k8s.io/kustomize/v3": verifying non-authoritative meta tag
go: finding sigs.k8s.io/kustomize v3.2.1
go: finding sigs.k8s.io/kustomize/v3 v3.2.1
go get sigs.k8s.io/kustomize/v3@v3.2.1: sigs.k8s.io/kustomize/v3@v3.2.1: invalid version: unknown revision v3.2.1

λ go get -v sigs.k8s.io/kustomize/v3@kustomize/v3.2.1
go: finding sigs.k8s.io/kustomize/v3 kustomize/v3.2.1
go get sigs.k8s.io/kustomize/v3@kustomize/v3.2.1: sigs.k8s.io/kustomize/v3@kustomize/v3.2.1: invalid version: version "kustomize/v3.2.1" invalid: disallowed version string
```

Note: This also makes release links less obvious. Instead of going to `https://github.com/kubernetes-sigs/kustomize/releases/<version>` you must add the prefix and escape the additional slash.

Note 2: I tried to find a discussion regarding the tag format but did not find one, sorry if this was previously discussed and agreed upon, feel free to close the issue.

cc @droot which published both releases

**Comment by rochacon** [comment]
Binary embedded version format also looks different:

```
λ kustomize-3.2.0 version
Version: {KustomizeVersion:3.2.0 GitCommit:a3103f1e62ddb5b696daa3fd359bb6f2e8333b49 BuildDate:2019-09-18T16:26:36Z GoOs:darwin GoArch:amd64}

λ kustomize-3.2.1 version
Version: {Version:kustomize/v3.2.1 GitCommit:d89b448c745937f0cf1936162f26a5aac688f840 BuildDate:2019-09-27T00:10:52Z GoOs:darwin GoArch:amd64}
```

Maybe this should have been released as v3.3 to highlight the changes, since this can break integration scripts? (It broke some of my CI scripts after the minor upgrade)

**Comment by monopole** [comment]
The goal is
 * kustomize/go.mod represents packages for clients (e.g. kubectl, kops, kubeadm, kubeflow, etc)
 * kustomize/kustomize/go.mod is the client known as kustomize, which will depend on released versions of the module upstairs, and serve as in-repo validation to defining that API.  We could have made a toy example binary, but might as well use the real thing.

The term `kustomize` is appearing in many contexts (repo name, module name, binary name) but our hands are tied at this point.  people are linking to packages at the top level module, and we cannot change the name of the binary.

The github URL thing is annoying but its a github thing, not a Go thing.  The [install instructions](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md) still work and are scriptable.

As for v3.3 - that particular thing - the dropping of the redundant "Kustomize" string in the version output was the only change from v3.2.0 to v3.2.1.  if you feel strongly about this, i can revert the  string and release at that tag.  regardless, the point was to get a tagged binary out there in the new format.

**Comment by rochacon** [comment]
Thank you for explaining @monopole. My use case fits the one similar to kubectl, I'm embedding kustomize into an internal tool.

If I understood this correcly, I believe this refactoring should have been released as v3.3, not because of the version string (this is not critical and easy to fix, don't worry in reverting it), but because it broke the way to consume its packages in a minor release, which was unexpected.
By that I mean, I used to depend on `sigs.k8s.io/kustomize/v3@v3.2.0` (I mainly use `sigs.k8s.io/kustomize/v3/pkg/commands/build` btw) but that same package cannot be retrieved with `sigs.k8s.io/kustomize/v3@v3.2.1`? Also, I believe Go modules will not find the new v3.2.1 release when running `go get -u`.

Did I get this right? How should one consume and keep in sync when using Go modules as a dependency manager?

**Comment by jgustie** [comment]
Is it intended that the binary name on the release changed to `kustomize_kustomize.v3.2.1_linux_amd64` from `kustomize.v3.2.1_linux_amd64`? This breaking some automation that depended on the old URL for me.

**Comment by monopole** [comment]
@jgustie yes, that was intentional. 

The client and the API must not be in the same module, if we're to adopt strict semver with the Go API module.  And without strict semver, its simply dangerous to have any automation downloading new versions.

@rochacon PTAL at  https://github.com/kubernetes-sigs/kustomize/pull/1575, feel free to chime in.

**Comment by monopole** [comment]
@jgustie BTW, sorry!  Something has to change here precisely because of these kinds of automated dependencies.

**Comment by jgustie** [comment]
No worries, I just want to make sure I was doing the right thing updating my download URLs.

**Comment by rochacon** [comment]
I'm closing this since the main question is now answered by the fixes to the release documentation introduced by https://github.com/kubernetes-sigs/kustomize/pull/1590
