### ISSUE TITLE
var replacement doesn't occur on commonLabels

### ISSUE THREAD

**Issue by kkasravi** [kubernetes-sigs/kustomize#1585]
use case:

1. add a commonLabels section in kustomization.yaml that includes a var 
2. when kustomize generates the resources it will replace the var when it adds the labels to the `<resource>`.metadata.labels.
3 when kustomize adds the selector to a resource like deployment, no var substitution occurs unless you explicitly add a configurations file that includes
```
- path: spec/selector/matchLabels/app.kubernetes.io\/instance
  kind: Deployment
```
4. when kustomize adds the labels to the resource's template, no var substitution occurs unless you explicitly add a configurations file that includes
```
- path: spec/template/metadata/labels/app.kubernetes.io\/instance
  kind: Deployment
```
5. this happens for deployment, statefulset, job, daemonset, poddisruptionbudget

**Comment by jbrette** [comment]
@kkasravi Have a look [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1585). The list of issues that would be solved in kubeflow by [Automatic Creation of 'vars:' and 'varReferences:' sections](https://github.com/kubernetes-sigs/kustomize/pull/1217) is endless. You could get rid of the hundreds of params.yaml and point directly at the KfDef values.

/cc @ian-howell

**Comment by kkasravi** [comment]
awesome @jbrette 

@monopole or @Liujingfang1 any thoughts about whether this will be merged for v3.2.2?

**Comment by kkasravi** [comment]
@jbrette do you have an example of using CRD values directly rather than ConfigMap?

**Comment by ismaeIfm** [comment]
@kkasravi can you share an example of point 3 and 4? I encountered the same problem in kustomize v3.9.0 but could follow the proposed solution. Thanks in advance

**Comment by ismaeIfm** [comment]
@kkasravi nevermind at the end I think I understood. I added this to my customization file:

```yaml
...
configurations:
- configurations.yaml
```
and this is the content of configurations.yaml
```yaml
varReference:
- path: spec/selector/matchLabels
  kind: Deployment
- path: spec/template/metadata/labels
  kind: Deployment

```

Hope it helps someone
