### ISSUE TITLE
kustomize does not generate a selector for Application kind from commonLabels

### ISSUE THREAD

**Issue by kkasravi** [kubernetes-sigs/kustomize#1591]
the Application kind - defined [here](https://github.com/kubernetes-sigs/application/blob/master/pkg/apis/app/v1beta1/application_types.go#L85) is not generated when commonLabels is used.

**Comment by jbrette** [comment]
A possible solution is [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1591)
