### ISSUE TITLE
3.3.0 release assets

### ISSUE THREAD

**Issue by alcohol** [kubernetes-sigs/kustomize#1598]
Not sure I completely understand the changelog/path going forward as of version 3.3.0. Does the restructuring process mean you will no longer add release assets on Github as with previous versions?

**Comment by Liujingfang1** [comment]
The new release process is documented [here](https://github.com/kubernetes-sigs/kustomize/tree/master/releasing)
There will be 3 modules and each of them will be released separately. Each release will contain its own assets.
