### ISSUE TITLE
a --strict mode for build?

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#16]
Such a mode would advise user about poor idioms YAML, or features about to be deprecated,

**Comment by Liujingfang1** [comment]
`Kustomize build` outputs yaml syntax failures and deprecation messages. Not necessary to have one more mode for showing those.

**Comment by mitchnielsen** [comment]
My use case for `--strict` would be in a CI environment to fail the build if Kustomize returns any errors. Without this flag, is there a way I can accomplish this?

**Comment by Liujingfang1** [comment]
You can check the exit code of `kustomize build`. When it is non zero, you can set the CI build to fail.

**Comment by mitchnielsen** [comment]
Ah, my builds continued on even with the failure so I had assumed it was returning a 0 exit code. I see now that it's 1. Thank you!
