### ISSUE TITLE
Publish old CLI binaries using the new release tag format

### ISSUE THREAD

**Issue by vreon** [kubernetes-sigs/kustomize#1602]
We've got some automation that downloads particular versions of the Kustomize CLI from GitHub, and since the last few releases use a new scheme, it has to do some version parsing to determine the correct URL.

It would be convenient if binaries for previous releases could also be published using the new scheme so that the correct URL is always:

```sh
https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${version}/kustomize_kustomize.v${version}_${os}_${arch}
```

**Comment by monopole** [comment]
The change was we had one module and didn't obey Go API semver, and we've moved to three modules (a Go API and two binaries) and want to obey semver going forward (see versioning policy notes).

Releases are performed via google cloud build, triggered by tags, determined by three cloudbuild_*.yaml files in the `releasing` directory, and the goreleaser tool to slap all the right stuff into the github releases pages.

That, combined with changes in directory structure required by Go modules, resulted in a change in download URL.

Anyone with more goreleaser skills than i is welcome to try to improve the outcome here.
