### ISSUE TITLE
Installation Instructions Broken

### ISSUE THREAD

**Issue by dmmatson** [kubernetes-sigs/kustomize#1604]
Installation instructions no longer work with 3.3.1.

```
$ opsys=linux  # or darwin, or windows
$ curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest |\
>   grep browser_download |\
>   grep $opsys |\
>   cut -d '"' -f 4 |\
>   xargs curl -O -L
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   630    0   630    0     0   1260      0 --:--:-- --:--:-- --:--:--  1260
100  564k  100  564k    0     0   414k      0  0:00:01  0:00:01 --:--:-- 1583k
 mv kustomize_*_${opsys}_amd64 kustomize
mv: cannot stat 'kustomize_*_linux_amd64': No such file or directory
```

**Comment by Lngramos** [comment]
Hi @monopole, one of my build pipelines have encountered the same issue as reported when attempting to installing the latest version of Kustomize onto an image as per the following instructions in the docs: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md#quickly-curl-the-latest-binary

This just started happening as a result to the latest release no longer being the the Kustomize CLI release, instead being this the [API v0.1.1](https://github.com/kubernetes-sigs/kustomize/releases/tag/api%2Fv0.1.1).

**Comment by Lngramos** [comment]
I've raised a pull request https://github.com/kubernetes-sigs/kustomize/pull/1677 to propose updating the documentation to where a particular tagged release is installed instead of using "latest" which is no longer reliable.
