### ISSUE TITLE
Up-to-date JsonSchema for Kustomize?

### ISSUE THREAD

**Issue by Ilyes512** [kubernetes-sigs/kustomize#1608]
Is there a up-to-date json schema for kustomize? Vscode (or one of my extensions - probably the yaml extension) uses http://json.schemastore.org/kustomization. This schema does not seem to match whats being said in the documentation.

If I get a up-to-date schema I will check if I can update it in the schemastore .

**Comment by thievery80** [comment]
pls reopen the issue, problem still persists

**Comment by via-jordan-sokolic** [comment]
Hi @Ilyes512 , did you find a solution for this? It is indeed frustrating...
