### ISSUE TITLE
`kustomize edit add resource` moves bases to resource

### ISSUE THREAD

**Issue by lundbird** [kubernetes-sigs/kustomize#1627]
starting with following in kustomization.yaml:

```
bases:
- ../../base
```
running:
`kustomize edit add resource nginx-conf.yaml`

results in following kustomization.yaml
```
resources:
- ../../base
- nginx-conf.yaml
```
Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T19:21:45+01:00 GoOs:darwin GoArch:amd64}

**Comment by jbrette** [comment]
base is deprecated since kustomize 2.3.0. Kustomize is doing the right thing

**Comment by brunojcm** [comment]
> base is deprecated since kustomize 2.3.0. Kustomize is doing the right thing
https://github.com/kubernetes-sigs/kustomize/blob/master/docs/v2.1.0.md#resources-expanded-bases-deprecated

Duplicated of https://github.com/kubernetes-sigs/kustomize/issues/1556
