### ISSUE TITLE
kustomize add annotation only supports DNS-1123 subdomain characters

### ISSUE THREAD

**Issue by lundbird** [kubernetes-sigs/kustomize#1628]
I try to add an annotation used for gitlab monitoring that uses a /
`kustomize edit add annotation  {app.gitlab.com/env2:app}`
which results in the following error message:
```
Error: field: Invalid value: "{app.gitlab.com\\/env2": prefix part a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T19:21:45+01:00 GoOs:darwin GoArch:amd64}

**Comment by georgej-github** [comment]
Running into the same issue, any advice? 
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-17T14:23:25+00:00 GoOs:darwin GoArch:amd64}
