### ISSUE TITLE
configMapGenerator can or should not have double quotation for its values

### ISSUE THREAD

**Issue by doi-t** [kubernetes-sigs/kustomize#165]
Relates #160.

I'm trying [helloWorld](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/helloWorld) demo and I realized that launched pods keep getting the following error after I run the command `kustomize build $OVERLAYS/production | kubectl apply -f -` given by the [README.md](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/helloWorld/README.md).

```
"invalid boolean value "\"false\"" for -enableRiskyFeature: strconv.ParseBool: parsing "\"false\"": invalid syntax
```

This is because quoting in built ConfigMap looks like below:
```sh
$ kustomize build $OVERLAYS/production
apiVersion: v1
data:
  altGreeting: '"Good Morning!"'
  enableRisky: '"false"'
kind: ConfigMap
......
```
If I remove double quotations from [the values in base/kustomization.yaml](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/helloWorld/kustomization.yaml#L13-L14), it works without the error.

The same thing happened for `base`.
```sh
$ kustomize build $DEMO_HOME/base
apiVersion: v1
data:
  altGreeting: '"Good Morning!"'
  enableRisky: '"false"'
kind: ConfigMap
......
```

Since `staging` has `map.yaml` in its overlay, it works without the problem.
```sh
$ kustomize build $OVERLAYS/staging
apiVersion: v1
data:
  altGreeting: Have a pineapple!
  enableRisky: "true"
kind: ConfigMap
......
```

I'm not sure how it is supposed to be in general but I'm guessing `'"false"'` and `'"Good Morning!"'` is not expected quoting.

------

I've also tried to check version but can not get version number for some reason. I downloaded `kustomize` with `go get github.com/kubernetes-sigs/kustomize` today.
```
$ file `which kustomize`
/Users/doi-t/go/bin/kustomize: Mach-O 64-bit executable x86_64
$ kustomize version
Version: {KustomizeVersion:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:unknown GoArch:unknown}
```

**Comment by Liujingfang1** [comment]
@doi-t The `helloWorld` example has been updated to use a file `configmap.yaml` instead of a ConfigMapGenerator. It won't block trying the demo. Also the `kustomize version` is fixed in v1.0.5.

The improper quoting in ConfigMapGenerator need to be fixed.
