### ISSUE TITLE
Homebrew bottle for MacOS Catalina installs invalid executable

### ISSUE THREAD

**Issue by ylogx** [kubernetes-sigs/kustomize#1650]
The binary from catalina bottle doesn't work:

```bash
wget https://homebrew.bintray.com/bottles/kustomize-3.2.1.catalina.bottle.tar.gz
```

<img width="693" alt="Screen Shot 2019-10-17 at 3 56 39 PM" src="https://user-images.githubusercontent.com/3508878/67042840-bc1aba00-f0f6-11e9-91ab-b543ca439fe0.png">

Likely because of this automated commit in homebrew repo: 
https://github.com/Homebrew/formulae.brew.sh/commit/f937e84e6c87567044c6d71ea973cd04e4309979#diff-1925185cc226c55db236d51194b4767c

### Workaround
Download the mojave bottle and manually replace the binary:

```bash
wget https://homebrew.bintray.com/bottles/kustomize-3.2.1.mojave.bottle.tar.gz
tar -xf kustomize-3.2.1.mojave.bottle.tar.gz
mv kustomize/3.2.1/bin/kustomize /usr/local/Cellar/kustomize/3.2.1/bin/kustomize
```

**Comment by yujunz** [comment]
How does the automated commit corrupt the release?

**Comment by austinchambers** [comment]
Related brew issue is here: https://github.com/Homebrew/homebrew-core/issues/45909

**Comment by knajjars** [comment]
Thanks!
