### ISSUE TITLE
Validate generated yaml

### ISSUE THREAD

**Issue by nicksnyder** [kubernetes-sigs/kustomize#167]
Thanks for the great project!

It would be nice if kustomize validated the generated yaml.

According to the [Kubeval](https://github.com/garethr/kubeval) readme, you could pull that in as a Go dependency.

**Comment by Liujingfang1** [comment]
Instead of validating the generated yaml, I suggest to validate the `resources` and `patches` files. So that it is easy to locate the invalid part and make suggestions.

**Comment by Liujingfang1** [comment]
This tool may help find the invalid resources such as in #232

**Comment by monopole** [comment]
Yes, sounds good.  Both validate the incoming resources and patchs, and since we have the deps anyway, validate the outgoing stuff as a sanity check.
