### ISSUE TITLE
"Quickly curl the latest binary" on INSTALL.md is old

### ISSUE THREAD

**Issue by atoato88** [kubernetes-sigs/kustomize#1680]
I tried to install kustomize written at [here](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md#quickly-curl-the-latest-binary), but I got error following:

```
$ curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest |\
>   grep browser_download |\
>   grep $opsys |\
>   cut -d '"' -f 4 |\
>   xargs curl -O -L
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   620    0   620    0     0   1850      0 --:--:-- --:--:-- --:--:--  1850
100  571k  100  571k    0     0  78756      0  0:00:07  0:00:07 --:--:--  159k
$ mv kustomize_kustomize\.v*_${opsys}_amd64 kustomize
mv: cannot stat 'kustomize_kustomize.v*_linux_amd64': No such file or directory
```

It may be because that [latest release](https://github.com/kubernetes-sigs/kustomize/releases/latest) changed to api/v0.1.1
Actually, script above downloaded `api_v0.1.1_linux_amd64.tar.gz`.

I could install kustomize from [here](https://github.com/kubernetes-sigs/kustomize/releases). So, it isn't critical.
But It should update script "[Quickly curl the latest binary](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md#quickly-curl-the-latest-binary)" on `docs/INSTALL.md`, I think.

**Comment by fedebike** [comment]
Having the same issue. @atoato88 are you saying that for now, it is not an issue because you download kustomize manually?

**Comment by atoato88** [comment]
@fedebike As for now, I think this is a small issue about ["Quickly curl the latest binary" docoumentation](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md#quickly-curl-the-latest-binary), because I could download kustomize from [here](https://github.com/kubernetes-sigs/kustomize/releases) manually for an alternative.

**Comment by fedebike** [comment]
Yes my issue is that I am currently having a jenkins job downloading via curl kustomize.  Now I don't really know to what should I point to... or how should I install api_v0.1.1_linux_amd64.tar.gz.

**Comment by sterchelen** [comment]
You should be able to download via
```bash
curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases |\
 grep browser_download |\
 grep $opsys |\
 grep kustomize_kustomize |
 head -n1 |\
 cut -d '"' -f 4 |\
 xargs curl -O -L
mv kustomize_*_${opsys}_amd64 kustomize
chmod u+x kustomize
```

**Comment by nigimaster** [comment]
Yes, having the same issue in our Jenkins pipeline and I was able to fix, thanks @sterchelen for the input!

btw, you are missing a \ on the code line:
grep kustomize_kustomize | \

and the version also, see below 
mv kustomize_kustomize.v*_linux_amd64 /usr/bin/kustomize; \

The working command is here:

curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases |\
 grep browser_download |\
 grep $opsys |\
 grep kustomize_kustomize |\
 head -n1 |\
 cut -d '"' -f 4 |\
 xargs curl -O -L
mv kustomize_kustomize.v*_${opsys}_amd64 kustomize
chmod u+x kustomize

**Comment by fedebike** [comment]
maybe better:

``mv kustomize_kustomize.*_${opsys}_amd64 kustomize``

**Comment by monopole** [comment]
Hey folks, my apologies.

I've just ground out a bunch of moves to break the repo into multiple modules, and things have changed slightly.

I've updated the INSTALL.md instructions per the lastest behavior.

If anyone is terribly unhappy with the tar file (some people like the executable to be compressed and wrapped with other artifacts, some people want a bare, uncompressed executable), please take a look at changing the behavior of `goreleaser` in the script :  https://github.com/kubernetes-sigs/kustomize/blob/master/releasing/cloudbuild.sh.
