### ISSUE TITLE
I have a private repository that I am using as base

### ISSUE THREAD

**Issue by muhammad-fahad2068** [kubernetes-sigs/kustomize#1682]
so my kustomization.yaml looks like following 
  
bases:
  - https://github.com/MyGithub/myrepo.git

and below is the error that I am getting

ts=2019-10-23T13:22:30.099130068Z caller=loop.go:101 component=sync-loop err="loading resources from repo: error executing generator command \"kustomize build .\" from file \".flux.yaml\": exit status 1\nerror output:\n2019/10/23 13:22:30 Error performing git fetch: Initialized empty Git repository in /tmp/kustomize-647178852/.git/\nfatal: could not read Username for 'https://github.com'

by looking at the code https://github.com/kubernetes-sigs/kustomize/blob/master/api/git/cloner.go it isnt going to clone using ssh 

I have tried giving https://<GIT_AUTHUSER>:<GIT_AUTHKEY>@github.com/repo/base/ https validation but it did not work as well and I had the same error

Do we have ssh enabled for cloning private repos and using them as base?

**Comment by JohnPaton** [comment]
You can use this form for cloning with ssh:
```yaml
resources:
- ssh://github.com/<username>/<repo>.git//path/to/kustomize/directory
```
