### ISSUE TITLE
Issue with --enable_alpha_goplugins_accept_panic_risk "Unknown flag"

### ISSUE THREAD

**Issue by knajjars** [kubernetes-sigs/kustomize#1687]
I use SOPS plugin and have been running kustomize build with **--enable_alpha_goplugins_accept_panic_risk** for a few months until recently the flag is marked as unknown. 

Nothing has changed besides that my OS was updated to MacOS Catalina, has anybody experienced a similar issue?

**Comment by vreon** [comment]
Which version of kustomize are you using? In recent versions the flag is named `--enable_alpha_plugins`
