### ISSUE TITLE
Add resources in overlays

### ISSUE THREAD

**Issue by nicksnyder** [kubernetes-sigs/kustomize#170]
Thanks for creating kustomize!

At Sourcegraph we deploy our Kubernetes application to customers. We have core services that are deployed to every customer and then a few optional services that each customer can choose to deploy or not (e.g. monitoring, alerting, SSDs, etc.).

kustomize does not currently allow patches to add new resources. I get an error like this:

> Error: failed to find an object with schema.GroupVersionKind{Group:"", Version:"v1", Kind:"Service"} to apply the patch

This means that all our optional services need to be bundled in our base yaml (i.e. with replica count 0), even though many customers don't need it. This causes and undesirable amount of clutter when inspecting our base yaml and inspecting a running cluster for our customers.

It would be ideal if patches were allowed to add new resources. Thanks!

**Comment by Liujingfang1** [comment]
You can create a kustomization for every customer, then in `kustomization.yaml`, add the customer specific resources to `resources` field rather than `patches` field.
