### ISSUE TITLE
is it possible to rename a specific object instead of using nameprefix or suffix.

### ISSUE THREAD

**Issue by dsekhart** [kubernetes-sigs/kustomize#1700]
I am trying to create PV for different environments along with other resources. In my case since each environment has it's own namespace, I have no need to blanketly apply name prefix or suffix. But in case of PVs since they are cluster resources, I need the names to be different for each environment. I could handle this outside of the application deployment, but I am trying to explore if I can keep it as part of the application resources as it's only used by this app. Another option I have is to have the full PV yaml in each environment overlay without base. Please share your inputs.

**Comment by Liujingfang1** [comment]
> have the full PV yaml in each environment overlay without base

This should work.

Or you can put PV yaml in a different base. Then have different overlays, where you can add nameprefix or namesuffix. These overlays are used in the corresponding application overlay.

**Comment by alun** [comment]
I've just faced a similar problem. Patching unexisting object would show me an error like:
```
Error: no matches for OriginalId ~G_v1_PersistentVolume|~X|etcd-volume-prod; no matches for CurrentId ~G_v1_PersistentVolume|~X|etcd-volume-prod; failed to find unique target for patch ~G_v1_PersistentVolume|etcd-volume-prod
```

So I ended up having 2 different bases for my `pv` in prod and `qa` my structure looks like this:
```
./prod
./prod/kustomization.yaml
./prod/etcd
./prod/etcd/sts.yaml
./prod/etcd/pv.yaml
./prod/base
./prod/base/kustomization.yaml
./prod/base/etcd
./prod/base/etcd/pv.yaml
./qa
./qa/kustomization.yaml
./qa/base
./qa/base/kustomization.yaml
./qa/base/etcd
./qa/base/etcd/pv.yaml
./base
./base/kustomization.yaml
./base/etcd
./base/etcd/svc.yaml
./base/etcd/sts.yaml
```

**Comment by Shell32-Natsu** [comment]
This should be covered by #3280. Close this and please use that one to track.
