### ISSUE TITLE
variations of Kustomization build

### ISSUE THREAD

**Issue by muhammad-fahad2068** [kubernetes-sigs/kustomize#1705]
Hi,

By running (kustomization build .)  its is generating one big output of all the files present in the base

Is there any way I can get the output which only has one Deployment resource with name xxxx that I give in command

Kindly let me know

**Comment by Liujingfang1** [comment]
Do you mean you want to filter the Deployment with name xxxx out?

Kusotmize dosn't support it, but there is a workaround. You can create a direction, say `output`. Then run 
```
kustomize build . --output ./output
```
When the flag `--output` points to a directory, Kusotmize splits the output into multiple files, with the names indicating gorup, version, kind, name of resources.
So you can look for the file with the filename containing deployment and xxxx.

**Comment by muhammad-fahad2068** [comment]
Thank you Liujingfang1
Let me try
