### ISSUE TITLE
Clean up outside collaborators

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-sigs/kustomize#1708]
Hey there @kubernetes-sigs/kustomize-admins ,

One of the github-admins here. -- We have a [longstanding issue] on cleaning up outside collaborators, and are now actively planning on removing them on December 1st.

At this point, people that are actively contributing to the Kubernetes project should be promoted to [org members][mem], and any repo specific permissions should be managed through their associated configuration in [kubernetes/org].

With that in mind, the following people are listed as outside collaborators:

- @barney-s 
- @damienr74
- @selfmanagingresource

Of those, @barney-s and @damienr74 have been active and I'd encourage [applying for membership to the kubernetes-sigs org][mem]. 😄 

@selfmanagingresource  has been inactive (<5 [devstats] recorded contributions in the past year across all Kubernetes orgs), and I'd opt for removal from direct repo permissions. 

Just a general reminder, not having direct permissions **does not stop** folk from contributing. It just means they'd have less permissions (would need  `/ok-to-test` on PRs etc).

If you have any questions or comments, please don't hesitate to ask in here or feel free to poke me in slack 👍 

Thanks!

assigning to kustomize-admins
/assign @droot @monopole @pwittrock 

/sig contributor-experience
/priority important-soon

[longstanding issue]: https://github.com/kubernetes/community/issues/3178
[mem]: https://github.com/kubernetes/community/blob/master/community-membership.md#member
[kubernetes/org]: https://github.com/kubernetes/org
[devstats]: https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All

**Comment by mrbobbytables** [comment]
Permissions for the above people have been cleaned up. However it looks like a few more people have been granted access. - @haiyanmeng @joncwong

@barney-s @damienr74 @haiyanmeng @joncwong -- If you need access -- Please go ahead and file for [org membership to the kubernetes-sigs org](https://github.com/kubernetes/community/blob/master/community-membership.md#member) and we can pursue adding you the appropriate groups for repo permissions 👍

I'll leave this open for another week (December 8th) before any further permissions clean up.

If you have any questions, please don't hesitate to reopen or ping me on slack.

Thanks!

**Comment by haiyanmeng** [comment]
> go ahead and file for org membership to the kubernetes-sigs org and we can pursue adding you the appropriate groups for repo permissions 

@mrbobbytables , all my [PRs](https://github.com/pulls?q=is%3Apr+author%3Ahaiyanmeng+archived%3Afalse+is%3Aclosed) submitted to the kubernetes-sigs org are reviewed by contributors from Google, which means that I cannot complete the Organization Membership Request. Any recommendations?

**Comment by mrbobbytables** [comment]
@haiyanmeng feel free to include me as a sponsor :)

**Comment by haiyanmeng** [comment]
Thanks for the help, Bob. Here is the membership request: https://github.com/kubernetes/org/issues/1450

**Comment by mrbobbytables** [comment]
Now that @haiyanmeng and @joncwong have become members, all outside collaborators have been removed or joined \o/

I've created https://github.com/kubernetes/org/pull/1454 to update the teams to reflect the current individually granted permissions.

Will close this out once it is merged.

**Comment by mrbobbytables** [comment]
https://github.com/kubernetes/org/pull/1454 has been merged. I've gone ahead and removed the individual permissions. Going to go ahead and close.
Thanks all!

/close
