### ISSUE TITLE
Spring boot example doesn't work as a remote resource

### ISSUE THREAD

**Issue by dsyer** [kubernetes-sigs/kustomize#1718]
The example in the [docs](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md) works:

```
$ kustomize build github.com/kubernetes-sigs/kustomize/examples/multibases/dev?ref=master
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: dev-myapp-pod
spec:
  containers:
  - image: nginx:1.7.9
    name: nginx
```

but another example doesn't:

```
$ kustomize build github.com/kubernetes-sigs/kustomize/examples/springboot/overlays/staging?ref=master
Error: accumulating resources: couldn't make target for path '../../base': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/tmp/kustomize-859811940/examples/springboot/base'
```

It looks like a bug potentially, because the only obvious difference is that the overlay in the second case is not a sibling of the base.

**Comment by jbrette** [comment]
This is not really not the actual source of the issues
1) The staging directory you picked is pointing at base which does not have a kustomization.yaml. This was done on purpose as part of the tutorial
2) The configmap section of the staging/kustomization.yaml is using a construct which has been deprecated.

For more detail to your questions, have a look [here where your issue has been reproduced](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_1718)

and here where the springboot example has been updated to work with kubernetes 1.16 and fixes the configmap syntax issue: [springboot](https://github.com/keleustes/kustomize/tree/allinone/examples/springboot)

**Comment by dsyer** [comment]
Thanks for that. I'm not really sure how to interpret though. Your links are all to someone else's repo. Is it fixed or going to be fixed here? What's the point?

**Comment by yujunz** [comment]
Specify the root with`//` may solve your problem @dsyer 

`kustomize build github.com/kubernetes-sigs/kustomize//examples/multibases/dev\?ref=master`
