### ISSUE TITLE
[question] Same configMap in multiple bases

### ISSUE THREAD

**Issue by boernd** [kubernetes-sigs/kustomize#172]
Is this a supported/valid use case?

I have two bases with the same configMap but different configuration (configMapGenerator with same name but different files). The intention is that referencing those two bases in an overlay results in a merged configMap. At the moment I get a `Merge failed: id '"v1_ConfigMap_test.yaml"' already used`  error. When changing the `behavior` to `merge` I get an error stating `[...] does not exist; cannot merge or replace.`.

**Comment by Liujingfang1** [comment]
@boernd In a kustomization, you can't have two objects with the same group version kind and name. To solve your problem, you can change one of the ConfigMap to a different name.

**Comment by boernd** [comment]
Thx for clearing that up.
