### ISSUE TITLE
Create `help api` command for printing API help from json schema

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#1771]
Goal: Provide documentation for the Kustomize API Schema (and future APIs) as a **built-in `kustomize docs kustomization` command, and as markdown files.**

Secondary Goal: Provide machine-readable Kustomization API Schema for IDEs, UIs, etc to parse.

Example workflow:

Running:

```sh
kyaml docs kustomization
```

Would output documentation about the Kustomization api:

e.g. something like

```sh
The Kustomization API defines a set Resource Configuration inputs and common transformations to those inputs.

ApiVersion: kustomize.config.kubernetes.io/v1beta1
Kind: Kustomization

Schema:

  PUT SOME REPRESENTATION OF THE KUSTOMIZE SCHEMA HERE -- e.g.

  namespace string
    namespace is applied to all input Resources by setting metadata.namespace...

  resources []string 
    resources is a list of files or directories...

Example:

    apiVersion: kustomize.config.kubernetes.io/v1beta1
    kind: Kustomization
    resources:
    - pod.yaml
    
    namespace: foo
    commonAnnotations:
      bar: baz

```

Ideally this documentation would be available both in the built-in command and in markdown.

My thought was to generate this from json-schema, so that the kustomize schema would be available to other tools such as IDEs -- enabling autocompletion and checking.  We *could* generate the json-schema from the go types and comment fields, but I am not sure it is worth it -- the go comments wouldn't easily capture things like examples, allowed value ranges for fields, etc.  So manually hand-coding the openapi might be the simplest approach -- the Kustomize API isn't huge.  At some point in the future, we could follow up with tooling to make sure each proto field existed in the json-schema.

The `kyaml` filters (e.g. `Pipeline`) may be serialized to yaml and used as APIs, so we could re-use the tooling for documenting those APIs as well.

Background on json-schema: https://json-schema.org/

Part 1:
- [ ] Write a simple json schema file for the Kustomize API -- something simple to work against
- [ ] Create a directory under `kyaml` for the code
- [ ] Use some existing golang library for parsing the json schema -- e.g. https://github.com/qri-io/jsonschema (you pick)
- [ ] Render the openAPI as help messaging to the console from a `kustomize docs kustomization` command
- [ ] Add a command to Kustomize to print the API docs from the json schema
- [ ] Improve the json schema file for the Kustomize API with examples

Part 2:
- [ ] Using a tool to generate API .md documentation from the json schema
- [ ] Add a command to run the doc generation to the Makefile

**Comment by joncwong** [comment]
I'll give this one a shot if that's okay.

**Comment by pwittrock** [comment]
Done

**Comment by joncwong** [comment]
I'll unassign myself for now. Will pick it back up if no one else gives it a shot.
