### ISSUE TITLE
Fix linter issues in kyaml package

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#1772]
A number of the linters in `kyaml/.golangci.yml` and `cmd/kyaml/.golangci.yml` have been disabled.  Enable them and address the issues:

- [x] errcheck
- [ ] funlen
- [x] gochecknoinits
- [ ] goconst
- [ ] gocritic
- [x] golint
- [x] lll
- [x] scopelint
- [x] stylecheck
- [x] unparam
- [x] whitespace

**Comment by artmello** [comment]
I would like to give this one a try if no one is already working on it.

**Comment by pwittrock** [comment]
Thanks!

**Comment by pwittrock** [comment]
I'd recommend doing them 1 at a time to minimize merge conflicts -- 1 PR per-linter.

**Comment by pwittrock** [comment]
@artmello Are you still planning on working on this?  Looks like @hypnoglow has completed a few.

**Comment by artmello** [comment]
hey @pwittrock sorry for the late reply. I pushed a MR enabling linters that were passing with no errors on a local test. Will work on the others next.

**Comment by hypnoglow** [comment]
@pwittrock It looks like all listed linter problems are solved, should we close the issue?
