### ISSUE TITLE
Exec plugin examples are broken

### ISSUE THREAD

**Issue by masterofkfit** [kubernetes-sigs/kustomize#1791]
I tried running the BashedConfigMap example by placing the script into the right folder.

```
$ kustomize build --enable_alpha_plugins
Error: the transformer $(PWD)/.config/kustomize/plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap should not remove annotation kustomize.config.k8s.io/id
```

It doesn't work with any of the exec plugins examples.

Using kustomize version  `3.4.0`

**Comment by metasim** [comment]
@masterofkfit What was the resolution of this? I'm having the same problem.
