### ISSUE TITLE
CommonLabels apply to pod templates of Jobs and Cronjobs by default

### ISSUE THREAD

**Issue by lundbird** [kubernetes-sigs/kustomize#1816]
This can cause pods that are spun up by jobs and cronjobs to be selected by the service that selects pods with commonLabels. This can give some strange behavior when the cronjob runs and will be difficult to debug if connecting to that service. Should we consider changing the default config for this?

**Comment by bzub** [comment]
To make this more granular in targeting you can either separate the jobs/cronjobs vs. everything else into two kustomizations and continue using `commonLabels:` as-is, or use the label transformer [as a plugin](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md#usage-via-plugin-3) and use `fieldSpecs` to target specific kinds of resources.

**Comment by lundbird** [comment]
I ran into this issue while using the label transformers: https://github.com/kubernetes-sigs/kustomize/issues/817 because doing so overlaps with the default transformer config.

**Comment by pwittrock** [comment]
What about the first suggestion -- split the Resource into different groups?
