### ISSUE TITLE
not can create image

### ISSUE THREAD

**Issue by MikelPan** [kubernetes-sigs/kustomize#1833]
kubectl kustomize  member-tenant-system

Error: json: cannot unmarshal number into Go struct field Image.newTag of type string

Examples:
  # Use the current working directory
  kubectl kustomize .
  
  # Use some shared configuration directory
  kubectl kustomize /home/configuration/production
  
  # Use a URL
  kubectl kustomize github.com/kubernetes-sigs/kustomize.git/examples/helloWorld?ref=v1.0.6

Usage:
  kubectl kustomize <dir> [flags] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

json: cannot unmarshal number into Go struct field Image.newTag of type string

this is kustomization.yaml
bases:
- ../../base
resources:
- env_cm.yaml
configMapGenerator:
- name: env-config
  files:
  - env
images:
- name: alpine
  newName: alpine
  newTag: 3.6
patchesStrategicMerge:
- resource-patch.yaml
- env-patch.yaml
generatorOptions:
  disableNameSuffixHash: true

**Comment by bzub** [comment]
It sounds like a kustomization you're using has an `images:` section that defines an object or string, rather than a list/array.

Double check that it looks like this: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md#usage-via-kustomizationyaml-2

```
images:
- name: postgres
  newName: my-registry/my-postgres
  newTag: v1
- name: nginx
  newTag: 1.8.0
```

**Comment by bzub** [comment]
You need to put quotes around `3.6` in your kustomization.yaml.

Like:
```yaml
- name: alpine
  newTag: "3.6"
```
