### ISSUE TITLE
updating volumeClaimTemplates storage in statefulset

### ISSUE THREAD

**Issue by muhammad-fahad2068** [kubernetes-sigs/kustomize#1844]
So in base I have defined an stateful set as it has volume claim template as describe below

  volumeClaimTemplates:
    - metadata:
        name: mypvc
        annotations:
          volume.beta.kubernetes.io/storage-class: "gp2"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi

So when I changed the storage from 1 to 3 GB. It gives error that sts can update only few of it fields. So I deleted the sts and pvc and flux bring the new sts and pvc with update storage

Now if I need to patch the pvc and attach more storage with it. can I create a patch for PVC and increase storage there. will it take effect like that?

**Comment by nlamirault** [comment]
Any news on this issue ?

**Comment by ElSamhaa** [comment]
I've hit this issue very recently too. Is there a workaround?
