### ISSUE TITLE
Make the examples coded in tests more visible.

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#1862]
Do more PR's like #1861

The tests down in `api/internal/target` are useful examples of high level functionality and should be moved up to the high level public API  `krusty` package - the package that provides exactly the functionality that these tests cover.  They are buried down there for code arrangement reasons that no longer apply.

Also, the test pattern in krusty is better, because the kustomization root is specified on the `Run` line rather than at test harness creation time. The latter pattern is harder to read, and means one can't run against a different kustomization target in the filesystem without building a new harness in a new test.

**Comment by Dingshujie** [comment]
\assign

**Comment by monopole** [comment]
thanks @Dingshujie!
