### ISSUE TITLE
Custom transformer configuration does not consider apiVersion of resources

### ISSUE THREAD

**Issue by muvaf** [kubernetes-sigs/kustomize#1885]
I am trying to use custom transformer configuration for our CRDs. I've gone through the document here https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md

The thing is the CRDs are identified only by using `kind` property. However, this causes problems when different CRDs that have the same kind but different `apiVersion`. For example, in [Crossplane](https://github.com/crossplaneio/crossplane) we have `Provider` types for each cloud provider stack that refer to credential secret for the given cloud provider.
GCP Provider CRs look like:
```
apiVersion: gcp.crossplane.io/v1alpha3
kind: Provider
metadata:
  name: some-name
...
```
AWS Provider CRs look like:
```
apiVersion: aws.crossplane.io/v1alpha3
kind: Provider
metadata:
  name: some-name
...
```

Since custom transformer configuration takes only `kind`, these two different resources conflict. As far as I know, in Kubernetes ecosystem `kind` and `apiVersion` fields are always tied with each other for identification. Can we have the same in kustomize as well?

**Comment by ydarb** [comment]
@muvaf If you haven't figured this out yet, you can target specific GVK resources in the `fieldSpecs`.

For example, let's assume we want to add annotations to particular resources. To target something from the core API, like a Namespace:

```
fieldSpecs:
- kind: Namespace
  path: metadata/annotations
```

To target a custom resource, such as the `Provider` resource for GCP from your OP:

```
fieldSpecs:
- kind: Provider
  group: gcp.crossplane.io
  version: v1alpha3
```

Relevant code: https://github.com/kubernetes-sigs/kustomize/blob/master/api/types/fieldspec.go#L13-L35
