### ISSUE TITLE
configMapGenerator should allow directories as input, like kubectl

### ISSUE THREAD

**Issue by andsens** [kubernetes-sigs/kustomize#189]
Given this dir tree:
```
configs/
├── config.d/
│   ├── 10-input.conf
│   ├── 50-filter.conf
│   └── 90-output.conf
├── ssl.conf
└── app.conf
```
You can do the following with kubectl:
```
kubectl create configmap my-config --from-file=configs
```

This creates a configmap containing all first level files from the `configs/` folder (i.e. `ssl.conf` and `app.conf`). This is quite useful when you have `.d` folders like the one above where you can just drop in new config files and be done with it.

I would love to be able to do that with `configMapGenerator` as well. Right now there is only the option to include individual files (unless I missed something [in the code](https://github.com/kubernetes-sigs/kustomize/blob/08be3f06/pkg/configmapandsecret/configmapfactory.go#L112-L149)).

**Comment by Liujingfang1** [comment]
Similar to resources from a directory
```
resources:
- res/*.yaml
```
we can add glob support in configMapGenerator, then this can be declared as
```
configMapGenerator:
- name: some-name
  files:
   - configs/*.conf
   - configs/config.d/*.conf
```

**Comment by monopole** [comment]
To move towards explicit dependency declaration, we're moving away from allowing globs in the kustomization file, and towards adding kustomization editting commands that support globbing - see
 #217, #218

The existing command `kustomize edit add configmap` could be modified to act as described :)

**Comment by Liujingfang1** [comment]
To add files under a directory to a configmap, use following command
```
kustomize edit add configmap some-name --from-files=somedir/*.conf
```

**Comment by andsens** [comment]
Sweet! Can't wait to test it! Awesome job on the implementation speed :-)

**Comment by mamoit** [comment]
Is this still working?
I'm running `2.0.1` (shiny and new) and am trying to use globbing but it throws:
```
Error: NewResMapFromConfigMapArgs: NewResMapFromConfigMapArgs: file sources: [configs/*.yaml]: evalsymlink failure on '/<somepath>/configs/*.yaml' : lstat /<somepath>/configs/*.yaml: no such file or directory
```
But the files are most definitely there.
Was the support for globbing in configMapGenerator dropped?

**Comment by bittner** [comment]
@mamoit This is working. You have to quote the path with the asterisk:
```console
kustomize edit add configmap some-name --from-files='somedir/*.conf'
```
Somewhat related: #914

**Comment by bittner** [comment]
I'm running the latest stable [kubectl](https://github.com/kubernetes/kubernetes/releases) version 1.15.3, and for comparison, standalone `kustomize` version 3.1.0. Neither of them has a `--from-files='...'` option.

Can someone clarify whether this feature was removed (or has never worked)?

**Comment by dijitali** [comment]
This worked for me (`from-file` singular, not plural as suggested):

```
kustomize edit add configmap my-configmap --from-file='config/files/*.conf'
```

On Kustomize version `{Version:3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T05:15:32+01:00 GoOs:darwin GoArch:amd64}`.

**Comment by AkashKrDutta** [comment]
Wait, so the kustomization binary allows you to add using a generic directory, but not the `configmapGenerator`? More shocking since the 'config/files/*.conf' is not using shell glob expansion but inbuilt to the binary. Why not add it also into `configmapGenerator`?

**Comment by anthraxn8b** [comment]
This issue is closed. Does it make sense to open a new one regarding the configMapGenerator and another one for the shell glob expansion?

**Comment by asteven** [comment]
So now we have this nice tool (kustomize) that allows me to write declarative configuration.
And now you are removing the possibility to use it declaratively because some discussion about java imports calls globbing evil.
And instead I'm supposed to use some new cli which is by definition imperative aka the opposite of declarative?

My git repo already gives me a clear explicit dependency declaration. Why am I supposed to replicate that again in a kustomization file?

Now I basically have to create/use yet another tool to wrap/generate my kustomization file.

This seems somewhat stupid, or at least confusing, and/or redundant.

**Comment by asteven** [comment]
> So now we have this nice tool (kustomize) that allows me to write declarative configuration.
> And now you are removing the possibility to use it declaratively because some discussion about java imports calls globbing evil.
> And instead I'm supposed to use some new cli which is by definition imperative aka the opposite of declarative?
> 
> My git repo already gives me a clear explicit dependency declaration. Why am I supposed to replicate that again in a kustomization file?
> 
> Now I basically have to create/use yet another tool to wrap/generate my kustomization file.
> 
> This seems somewhat stupid, or at least confusing, and/or redundant.

Never mind. I misunderstood how `kustomize edit` works. Sorry for the noise.

**Comment by TomyLobo** [comment]
If you're looking for this like me, glob support has been removed.
See https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/#globs-in-kustomization-files

**Comment by antwacky** [comment]
whyyyyyyyyyyyyyyy!!!! :(
