### ISSUE TITLE
Needs a `latest` tag for kustomize

### ISSUE THREAD

**Issue by mipnw** [kubernetes-sigs/kustomize#1898]
There does not seem to be an easy way to download the latest release of kustomize. The `latest` tag is currently taken by the pluginator. That would make it possible to wget latest kustomize tar.gz

**Comment by monopole** [comment]
This repo will ship several binaries, so one `latest` tag won't work.  As part of the release process, will manually add `latest_kustomize`, `latest_foo`, etc.

In the meantime, see notes at top of [INSTALL.md](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md).  The script `hack/install_kustomize.sh` is supported as a means to install the latest kustomize with a rudimentary attempt to work on multiple OS'es.

It relies on the github API returning the releases in order, most recent first.  Does that work for you?
