### ISSUE TITLE
Restrict few yaml files from base

### ISSUE THREAD

**Issue by muhammad-fahad2068** [kubernetes-sigs/kustomize#1912]
I have kustomization.yaml as below

bases:
  - git@github.com:repoistory/repo-name.git

above repository contains many YAML files that Kustomize will use to stdout

Can I restrict any manifest to be used

Is there any way I can ask kustomize not to use this manifest from base and expect it use all?

**Comment by monopole** [comment]
If you want to use the remote URL as a base, please fork the remote, make your own copy, and edit it as desired.  You can always rebase from the remote to get updates.  It's dangerous to depend on a remote you don't control.

It's also possible to specificy a path inside the repo, e.g.
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

reopen if this doesn't answer your question.
