### ISSUE TITLE
Importing kustomize causes duplicate proto registration errors

### ISSUE THREAD

**Issue by muvaf** [kubernetes-sigs/kustomize#1915]
In Crossplane, I'm writing a controller that imports kustomize api and calls kustomize via Go. I got it working and it's well functioning. However, the following errors are printed since I imported kustomize:
```
...
2019/12/09 23:08:10 proto: duplicate proto type registered: k8s.io.api.apps.v1beta1.Deployment
2019/12/09 23:08:10 proto: duplicate proto type registered: k8s.io.api.apps.v1beta1.DeploymentCondition
2019/12/09 23:08:10 proto: duplicate proto type registered: k8s.io.api.apps.v1beta1.DeploymentList
2019/12/09 23:08:10 proto: duplicate proto type registered: k8s.io.api.apps.v1beta1.DeploymentRollback
...
```

It simply lists all native Kubernetes types. I dog a little bit and saw that both `kustomize` and `k8s` api imports have the similar `init()` functions that registers the native Kubernetes types to proto. Having both in the same module causes the logs above.

I haven't seen any problems, at least in the functionality I use, but it's misleading.

**Comment by muvaf** [comment]
As far as I understand from https://github.com/golang/protobuf/issues/268#issuecomment-519756844 , in the future, that issue will cause the program to panic.

**Comment by bzub** [comment]
Are you using the [krusty](https://github.com/kubernetes-sigs/kustomize/tree/master/api/krusty) high-level API or another way? The [`kustomize` binary imports krusty](kustomize/internal/commands/build/build.go).

**Comment by muvaf** [comment]
I'm using the krusty high-level API. You can take a look at how I use kustomize here https://github.com/muvaf/configuration-stacks/pull/1/files#diff-771461f5838d27bc2ce2efe842627885R27

**Comment by bzub** [comment]
Possibly related to https://github.com/kubernetes-sigs/kustomize/issues/1906

**Comment by monopole** [comment]
same underlying cause: https://github.com/kubernetes-sigs/kustomize/tree/master/pseudo/k8s

will call this a dupe.  it will be fixed by removing pseudo/k8s
