### ISSUE TITLE
compiling from source gives bad version string

### ISSUE THREAD

**Issue by symbiont-sam-halliday** [kubernetes-sigs/kustomize#1926]
following the instructions at https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md#build-the-kustomize-cli-from-local-source I get a version string like 

```
Version: {Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}
```

rather than the version matching the release tag, e.g. I expected

```
Version: {Version:kustomize/v3.3.0 GitCommit:7050c6a7b692fdba6e831e63c7b83920ab03ad76 BuildDate:2019-10-24T17:54:30Z GoOs:linux GoArch:amd64}
```

(with a different BuildDate, obviously)

This seems to be coming from api/provenance but if I change that file manually, it isn't picked up by the build.

**Comment by monopole** [comment]
That's WAI.  This is only set when publishing at a specific tag, using --ldflags

building from head won't / cannot set this.

**Comment by symbiont-sam-halliday** [comment]
thanks for confirming! I am not a Go developer, could you please explain what you mean by "publishing at a specific tag using `--ldflags`"? I'd like to have a self-built binary with the correct version string (some other tooling checks it).

**Comment by symbiont-sam-halliday** [comment]
I tried

```
GO111MODULE=on go get sigs.k8s.io/kustomize/kustomize/v3@v3.3.0 -ldflags "-X provenance.version=3.3.0
```

but the Version is still `unknown` :man_shrugging:

**Comment by symbiont-sam-halliday** [comment]
This works!

```
GO111MODULE=on go get -ldflags "-s -X sigs.k8s.io/kustomize/api/provenance.version=kustomize/v3.3.0 -X sigs.k8s.io/kustomize/api/provenance.gitCommit=7050c6a7b692fdba6e831e63c7b83920ab03ad76 -X sigs.k8s.io/kustomize/api/provenance.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"  sigs.k8s.io/kustomize/kustomize/v3@v3.3.0
```
