### ISSUE TITLE
go get / go install fails

### ISSUE THREAD

**Issue by symbiont-sam-halliday** [kubernetes-sigs/kustomize#1929]
The instructions in https://github.com/kubernetes-sigs/kustomize/blob/master/docs/INSTALL.md#try-go result in the following with go 1.13.5 (on Archlinux)

```
$ go install sigs.k8s.io/kustomize/kustomize/v3
can't load package: package sigs.k8s.io/kustomize/kustomize/v3: cannot find package "sigs.k8s.io/kustomize/kustomize/v3" in any of:
	/usr/lib/go/src/sigs.k8s.io/kustomize/kustomize/v3 (from $GOROOT)

$ go get sigs.k8s.io/kustomize/kustomize/v3@v3.3.0
go: cannot use path@version syntax in GOPATH mode
```

I tried running these commands from the `kustomize/v3.3.0` branch, incase that was relevant, and got the same output.

**Comment by monopole** [comment]
Updated doc to add `GO111MODULE=on` out front, to trump GOPATH settings.

please reopen if that doesn't work for you

**Comment by symbiont-sam-halliday** [comment]
Thanks! It unfortunately has the same problem as in https://github.com/kubernetes-sigs/kustomize/issues/1926
