### ISSUE TITLE
`kustomize apply`: sort resources when apply

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#1958]
Sort resources by references when apply.  Only re-order Resources which have references to one another, and keep the others in their order.

- Namespace
- Roles
- ClusterRules

Support disabling this with a flag -- `--sort=false`

**Comment by tehmoon** [comment]
I almost gave up making this work until I ended up on the `--reorder none` flag from `kustomize`.
This flag will respect the order from the yaml list, making this work as expected. Of course, you need to include your namespace resource first then.
