### ISSUE TITLE
kyaml: config.kubernetes.io/index annotation should be a string

### ISSUE THREAD

**Issue by bzub** [kubernetes-sigs/kustomize#1975]
`config.kubernetes.io/index` is a number during configuration function execution which makes the Resource technically invalid while set.

https://github.com/kubernetes-sigs/kustomize/blob/01105af14d36d4bb7f54aecf5e9d1ed40194e88a/functions/examples/validator-kubeval/image/main.go#L104-L109

**Comment by pwittrock** [comment]
I suspect it isn't an int specifically, but the yaml is ambiguous and some tools parse it as an int.
