### ISSUE TITLE
Referring another git repository in kustomize while git-crypting some files in the target repo

### ISSUE THREAD

**Issue by AliGouta** [kubernetes-sigs/kustomize#2008]
Suppose, we have 2 git repositories: A and B and we refer repository B in some kustomize files from repository A.  These files (in repo B) are being crypted with `git-crypt`. And as a user running `kustomize build` command from repo A, I have my gpg key being declared on both repositories A and B and it is working correctly.

Example, Suppose in repository A, we have:

```
cicd/kustomization.yaml:
namespace:
  cicd-prod
resources:
  - github.com/<Org>/k8s-infra/cicd/k8s-deploy/overlays/prod?ref=workflow-deploy
```

We run `kustomize `build on repository A:

```
kustomize build cicd/
```

Error we get:

```
Error: accumulating resources: recursed accumulation of path 'infra': accumulating resources: recursed accumulation of path 'cicd': accumulating resources: recursed accumulation of path 'github.com/<ORG>/k8s-infra/cicd/k8s-deploy/overlays/prod?ref=workflow-deploy': accumulating resources: recursed accumulation of path '../../base': accumulating resources: accumulating resources from 'secrets/gpg.yaml': YAML file [secrets/gpg.yaml] encounters a format error.
error converting YAML to JSON: yaml: control characters are not allowed
```

I assume that while cloning or referencing repositroy B, something prevented decrypting `secrets/gpg.yaml` on the fly. Any idea ?

**Comment by mihaigalos** [comment]
@AliGouta, would the snippet of code work with non-crypted files, would kustomize fetch from repo `B`?
