### ISSUE TITLE
Add support for patchesJson6902 in kustomize edit command

### ISSUE THREAD

**Issue by dijitali** [kubernetes-sigs/kustomize#2015]
I'm trying to use the `kustomize edit` command to manipulate a `patchesJson6902` kustomization but it looks like it's currently only able to produce the `patchesStrategicMerge` patch type.

It would be handy if [all kustomize fields](https://github.com/kubernetes-sigs/kustomize/blob/kustomize/v3.5.1/docs/fields.md) could be supported within the `edit` command.

**Comment by Liujingfang1** [comment]
@phanimarupaka
