### ISSUE TITLE
Make annotation names consistent

### ISSUE THREAD

**Issue by prachirp** [kubernetes-sigs/kustomize#2033]
Rename "config.kubernetes.io/local-config" to "config.k8s.io/local-config" since k8s.io is widely adopted while kubernetes.io is not. This will make kustomize annotations have a consistent "config.k8s.io" prefix.

**Comment by prachirp** [comment]
Hey @t0rr3sp3dr0 do you want to take over this issue?

**Comment by t0rr3sp3dr0** [comment]
Hi @prachirp! If we make this change, would we still need to support the old annotations with `kubernetes` instead of `k8s`?

**Comment by t0rr3sp3dr0** [comment]
Another thing to consider is that K8s itself uses `kubernetes.io` sometimes. An example of this is the recommended labels for labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/.

**Comment by prachirp** [comment]
Hey @t0rr3sp3dr0 , yes we'd still need to support the existing annotations. We do that already to support multiple function annotations [here](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/fn/runtime/runtimeutil/functiontypes.go#L15).

Thanks for linking to the recommended labels page! I don't have a strong preference between "k8s" and "kubernetes". This bug was just to review and make kustomize consistently recommend one style of annotation.

**Comment by t0rr3sp3dr0** [comment]
Given that Kustomize uses `kustomize.config.k8s.io` as API Group for `Kustomization`, other resources like `KubeletConfiguration` and `KubeSchedulerConfiguration` also use API Groups with `config.k8s.io`, and I couldn’t find anything on Google unrelated to Kustomize that uses `config.kubernetes.io`, I think makes sense to move to `config.k8s.io`.

**Comment by t0rr3sp3dr0** [comment]
@prachirp, maybe we can go further and use `kustomize.config.k8s.io` instead. `KubeletConfiguration` and `KubeSchedulerConfiguration` use respectively `kubelet.config.k8s.io` and `kubescheduler.config.k8s.io`, not just `config.k8s.io`. The annotation would be visually related to Kustomize and it is already used by plugins: https://github.com/kubernetes-sigs/kustomize/blob/855ce1a8db6c2e9c05fb15e66d92dbfdd60de4f1/api/internal/plugins/utils/utils.go#L23-L25

**Comment by prachirp** [comment]
Hey @t0rr3sp3dr0, that's a good suggestion to tag it as `kustomize.config.k8s.io`. But for configuration functions there's work to interoperate with kpt: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.7.0
So I'd rather stick to `config.k8s.io` especially for function annotations in order to keep it more generic for now. What do you think?

@monopole, @Shell32-Natsu FYI

**Comment by Shell32-Natsu** [comment]
These annotations may not only be used by Kustomize. Is it a good idea to add `kustomize` to them?
