### ISSUE TITLE
travis osx tests (mac darwin) failing to download tools

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#2045]
travis tests on osx often (but not always)  fail to download related tools need in tests.

e.g.: https://travis-ci.org/kubernetes-sigs/kustomize/jobs/634020821

linux, OTOH, never fails for these reasons.

Can someone who knows more about osx on travis look into this?

**Comment by pwittrock** [comment]
Seems to be specific to travis OSX VMs, not MacOS specifically.
