### ISSUE TITLE
Provide a JSON Schema for kustomization.yaml

### ISSUE THREAD

**Issue by mxey** [kubernetes-sigs/kustomize#205]
Several editors, like VS Code and IntelliJ, support JSON Schema to provide validation and autocompletion for YAML files. I'd like Kustomize to provide a JSON Schema file for its configuration. 

Ideally would be available on http://schemastore.org/json/

**Comment by fentas** [comment]
Using vs code its kind of irritating that `kustomization.yaml` files marked as wrong.

**Comment by mxey** [comment]
Since Kustomize now has `apiVersion` and `kind` in the file, maybe the schema can be put where the other Kubernetes API schemas are, so all editors that import the Kubernetes API schemas will just get it?

**Comment by gorkem** [comment]
fixed with https://github.com/SchemaStore/schemastore/pull/700

**Comment by ralgozino** [comment]
Hello! 

I'm getting `Unexpected property patches` error for all my `kustomization.yaml` files in VSCode and COCVim :( 

Am I doing something wrong?

**Comment by michaelkrupp** [comment]
@ralgozino there is no `patches` anymore in latest kustomize. Only `patchesJson6902` and `patchesStrategicMerge`.

**Comment by pgpx** [comment]
@michaelkrupp Are you sure that it has been removed?  It was only introduced in 3.2.0 ([inlinePatch doc on master branch](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/inlinePatch.md) and [3.2.0 release notes](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/v3.2.0.md)), and I can't see anything in later release notes that say it has been removed.

**Comment by michaelkrupp** [comment]
@pgpx you [appear to be correct](https://github.com/kubernetes-sigs/kustomize/blob/master/api/types/kustomization.go#L50). I could not find any official documentation for this though, aside from the release notes you already linked.

**Comment by GuyPaddock** [comment]
@michaelkrupp Closing the loop on this old issue -- you were partially correct. "patches" got removed in https://github.com/kubernetes-sigs/kustomize/releases/tag/v1.0.8 and then re-introduced and repurposed in https://github.com/kubernetes-sigs/kustomize/releases/tag/v3.2.0.
