### ISSUE TITLE
Sharing an object when applying labels 

### ISSUE THREAD

**Issue by cscetbon** [kubernetes-sigs/kustomize#2055]
I have x overlays that share a base made of a ConfigMap, Secret and Deployment. in each overlay I apply labels using commonLabels, add a prefix and a suffix to names, however the ConfigMap is identical for all of my overlays. How can I do to keep that file shared and not apply labels, prefix, suffix etc.. to it ?

secrets.yaml in each overlay just change the key path of the secret
```
.
├── base
│   ├── deployment.yaml
│   ├── kustomization.yaml
│   ├── secrets.yaml
│   └── set-configuration.sh
└── o1
    ├── deployment.yaml
    ├── kustomization.yaml
    └── secrets.yaml
└── o2
    ├── deployment.yaml
    ├── kustomization.yaml
    └── secrets.yaml
...
```

**Comment by le-duane** [comment]
@cscetbon You can specify which Kind of objects to apply labels to when using the label transformer plugin explicitly. 

https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md#usage-via-plugin-3

**Comment by cscetbon** [comment]
@le-duane I can make it work by creating a transformer in each overlay. I can't move it to the base folder cause I need to add a specific label in each overlay. Is there a way to do it other than the options below ?
- creating the LabelTransformer in each overlay
- creating a plugin that should be copied to each machine where the deployment happens 
I'd like to have something simple as **commonLabels**

**Comment by cscetbon** [comment]
I also tried to put my transformer in the base and patch it in overlays but I get :

_Error: no matches for OriginalId ~G_builtin_LabelTransformer|~X|skipConfigMap; no matches for CurrentId ~G_builtin_LabelTransformer|~X|skipConfigMap; failed to find unique target for patch ~G_builtin_LabelTransformer|skipConfigMap_

It seems I can't patch builtin objects
