### ISSUE TITLE
Why does the new TestHarness not load Go plugins from $KUSTOMIZE_PLUGIN_HOME ? 

### ISSUE THREAD

**Issue by devstein** [kubernetes-sigs/kustomize#2059]
Hi, 

The older test harness used to load the Go plugin from the usual `$KUSTOMIZE_PLUGIN_HOME` (or `$XDG_CONFIG_HOME/kustomize/plugin/`), but now it searches a variety of other directories. I’ve adjusted my tests to accommodate this, but this seems like a bug to me. Is there a reason for this change?

The source of the change comes from [func DeterminePluginSrcRoot(fSys filesys.FileSystem) (string, error)](https://github.com/kubernetes-sigs/kustomize/blob/f749a4a194e1bfa50287e0c60889ca1f6eaf14bd/api/internal/plugins/compiler/compiler.go#L35)

**Comment by devstein** [comment]
Still curious why this behavior change

**Comment by devstein** [comment]
@monopole Can you help me understand why the [test harness loads the plugin from these directories?](https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/plugins/utils/utils.go#L22) As opposed to the [`KUSTOMIZE_PLUGIN_HOME` or `$XDG_CONFIG_HOME/kustomize/plugin/` directory](https://github.com/kubernetes-sigs/kustomize/blob/2d699f93fc664838aa41db05ff17f836383862f2/api/konfig/plugins.go#L78)

**Comment by monopole** [comment]
The test harness as written just covers plugins placed in the canonical repo (i.e. it follows relative paths from the unit test process).

Please send a PR to modify `DeterminePluginSrcRoot` to try `KUSTOMIZE_PLUGIN_HOME`.

Do you happen to know which PR made the change you're alluding to?  Might help with recalling the reason, if any.

**Comment by monopole** [comment]
Be sure to run all the tests of course.

I don't think we intentionally set `KUSTOMIZE_PLUGIN_HOME` in a global location for global impact on tests.  If it's set in an example, we can unset it at the end of the example.

Also, would appreciate your help in writing a more flexible plugin test tool.  curious about your development process.
