### ISSUE TITLE
Provide a multi-platform wrapper for easier distribution of the binary

### ISSUE THREAD

**Issue by schweikert** [kubernetes-sigs/kustomize#206]
Distributing a binary across our organization with developers working both on linux and on mac is a bit of a challenge. I implemented a short shell wrapper that eases this a bit for kustomize. It does:

- download the appropriate binary from github
- verify that the checksum is ok
- cache the binary for further executions

See:
[kustomize.sh.txt](https://github.com/kubernetes-sigs/kustomize/files/2235567/kustomize.sh.txt)

Maybe it would be possible to publish such a script as part of a release?

**Comment by monopole** [comment]
If you want, make a PR to add a kustomize/scripts directory, toss this in there, and add a pointer to it from the [INSTALL](https://github.com/kubernetes-sigs/kustomize/blob/master/INSTALL.md) page.  It will need a copyright header :)

**Comment by schweikert** [comment]
The idea was rejected in #206
