### ISSUE TITLE
Kustomize doesn't fetch YAML from HTTPS URLs

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/kustomize#2068]
Based on the documentation , I was expecting that I could use a https:// URL as a YAML resource, but kustomize doesn't seem to find it (or doesn't follow the GitHub redirects?).

```
$ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/knative/serving/releases/download/v0.11.0/serving-crds.yaml
- https://github.com/knative/serving/releases/download/v0.11.0/serving-core.yaml
```

```
$ kustomize build .
2020/01/10 16:29:09 evalsymlink failure on '/private/var/folders/d9/tpzrvxbs7s98zqy4c5yq8bk40000gr/T/kustomize-632648700/releases/download/v0.11.0/serving-crds.yaml' : lstat /private/var/folders/d9/tpzrvxbs7s98zqy4c5yq8bk40000gr/T/kustomize-632648700/releases: no such file or directory
Error: accumulating resources: accumulating resources from 'https://github.com/knative/serving/releases/download/v0.11.0/serving-crds.yaml': evalsymlink failure on '/Users/jpeach/src/kustomize/knative/base/https:/github.com/knative/serving/releases/download/v0.11.0/serving-crds.yaml' : lstat /Users/jpeach/src/kustomize/knative/base/https:: no such file or directory
```

```
$ kustomize version
{Version:3.5.3 GitCommit:5ba90fe5ef1dc4599e359edd41d1d0e6373b247d BuildDate:2019-12-18T03:07:49+00:00 GoOs:darwin GoArch:amd64}
```

**Comment by yujunz** [comment]
AFAIK, remote target is limited to a few git repo URL scheme.

You may have a look at https://github.com/kubernetes-sigs/kustomize/blob/master/examples/goGetterGeneratorPlugin.md for your use case.

**Comment by piyushGoyal2** [comment]
+1 . 
We also want to segregate sidecars and init containers common across applications. We were planning to have following section in all applications base folders with Kustomization.yaml having
`patches:
- path: patchSidecarSplunk.yaml
  target:
    kind: Deployment`
but referring to one single file based on Github URL doesn't seem possible.

@yujunz

**Comment by jpeach** [comment]
I was reading [this](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md) documentation, which made me think that all kinds of go-getter URLs were supported generally.

So this sounds like "behaves correctly"?

**Comment by yujunz** [comment]
@jpeach the documents says all url should be go-getter conformant. But not all go-getter url are supported. Related discussion in #923

**Comment by yujunz** [comment]
@piyushGoyal2 you are right about single file cannot be referenced

We may play some trick in go-getter plugin to make it work for generator

https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/someteam.example.com/v1/gogetter/GoGetter_test.go#L72

But it does not apply for transformers like patches.

**Comment by piyushGoyal2** [comment]
@yujunz - Does it always look out for kustomization.yaml in remote repository? My assumption was that using go-getter, it just clones the repo as a sub directory in the current folder and then rest of the kustomize logic applies on top of it. 

Looks like a pretty strong use case to me. What would you suggest?

**Comment by yujunz** [comment]
The go-getter plugin does not expect kustomization, you may override the command.

The builtin resource generator does looking for a directory with `kustomization.yaml` file.

**Comment by daurnimator** [comment]
I would expect to be able to reference a remote resource.

**Comment by yujunz** [comment]
> I would expect to be able to reference a remote resource.

It should be supported in version >3.5.5 now.
