### ISSUE TITLE
Support loading OpenAPI from sources

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#2070]
/assign @KnVerey 

The `openapi` package as implemented today [loads schema from a statically compiled in source](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/openapi/openapi.go#L165).

It would be useful to be able to extend these capabilities to load openAPI specs explicitly.

Example functions:

```go

// SetSchemas parses and indexes the schema definitions by their apiVersion
// and kind, replacing any schemas previously set.  The default schemas will
// not be used.
// If multiple schemas contain the same definitions, the latter definitions
// replace the former definitions.
func SetSchemas(schemas ...string)

// AddSchemas parses and indexes the schema definitions by their apiVersion
// and kind.
// If multiple schemas contain the same definitions, the latter definitions
// replace the former definitions.
func AddSchemas(schemas ...string) error

```

As a follow up we can consider which sources might make sense to load implicitly -- e.g. keyword environment variables, default disk locations, aggregator service which catalogues schema for popular OSS APIs, etc

**Comment by pwittrock** [comment]
cc @tkellen

**Comment by apelisse** [comment]
> // If multiple schemas contain the same definitions, the latter definitions
> // replace the former definitions.

This could be a problem of course, and might get thorny. I suspect in general the schemas are going to be "compatible", but it'd be ideal if you could verify that somehow ...

**Comment by pwittrock** [comment]
@apelisse there is probably a lot someone could dig into on this if they were interested.

Maybe someone wants to override the schema because certain features are considered harmful in their organization, in which you would want to override.

Another case may be want to fix values to enumerations or regexes, in which case the schemas might be merged.

We probably don't want to make any assumptions initially and give users the most direct control over which definitions are used.

**Comment by apelisse** [comment]
Sounds good!
