### ISSUE TITLE
document broken usage for vars

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#2071]
`vars` was introduced to fetch value from one object config and inject it to another object config. It's not aiming for the general substitution or templating. `vars` is broken for use cases, as listed in #2052. We should also document those cases in kustomize documents.

**Comment by tkellen** [comment]
Can we accomplish this with a deprecation warning as suggested in https://github.com/kubernetes-sigs/kustomize/issues/2052#issuecomment-577279491?

**Comment by Liujingfang1** [comment]
We can first document the broken use cases. Once we confirmed that `vars` is to be deprecated, we can add the deprecation message.
