### ISSUE TITLE
Remote bases do not appear to work - unless path is on master?

### ISSUE THREAD

**Issue by alexec** [kubernetes-sigs/kustomize#2072]
This should work

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/argoproj/argo//manifests/quick-start/postgres?ref=apiserverimpl
```

```
Error: accumulating resources: accumulating resources from 'github.com/argoproj/argo//manifests/quick-start?ref=apiserverimpl': evalsymlink failure on '/Users/acollins8/cdp-deployments/argo-workflows/envs/tools-sgmnt-ppd/github.com/argoproj/argo/manifests/quick-start?ref=apiserverimpl' : lstat /Users/acollins8/cdp-deployments/argo-workflows/envs/tools-sgmnt-ppd/github.com: no such file or directory
```

The path `manifests/quick-start/postgres` is not on branch `apiserverimpl`.

**Comment by yujunz** [comment]
It might be related to the hardcoded ref in
https://github.com/kubernetes-sigs/kustomize/blob/3af514fa9f85430f0c1557c4a0291e62112ab026/api/internal/git/cloner.go#L81

**Comment by yujunz** [comment]
Does it solve your problem @alexec

**Comment by pfremm** [comment]
@yujunz when is next release going to be cut?  I would like this fix, but would rather use an official release.

**Comment by yujunz** [comment]
Probably @pwittrock will have the answer.

**Comment by saravanakumar-periyasamy** [comment]
this doesn't work if ref='commit sha', and doc says you can use commit sha in ref - https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md#url-format

Also, current release version (v3.5.4) doesn't support commit sha either, instead it silently fails and pulls master branch - https://github.com/kubernetes-sigs/kustomize/blob/kustomize/v3.5.4/api/internal/git/cloner.go#L76-L99
