### ISSUE TITLE
LoadCRDs: security when using CRD definition in parent directory

### ISSUE THREAD

**Issue by sb2nov** [kubernetes-sigs/kustomize#2078]
I have been trying to kustomize something where the crd definition is in another directory and i get the `error: LoadCRDs: security` is there a way to avoid this. 

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
crds:
  - ../../kubernetes/spark/crds/spark-crds.yaml
bases:
  - ../../kubernetes/spark/scheduled
patchesStrategicMerge:
  - spark-patch.yaml
```

I want each spark job to patch an existing yaml file.

**Comment by yujunz** [comment]
Possibly related to https://github.com/kubernetes-sigs/kustomize/blob/5d4e45c24dbe5c5aee5c5767a33ee76de2f90f74/docs/FAQ.md#security-file-foo-is-not-in-or-below-bar

Try putting a `kustomization.yaml` in the crd folder and refer the directory instead.

**Comment by sb2nov** [comment]
but that means you've a copy of the CRDS for each spark job.
