### ISSUE TITLE
Option to reenable name hashing for literally declared configMaps/secrets?

### ISSUE THREAD

**Issue by robbyt** [kubernetes-sigs/kustomize#210]
In #159 automatic name hashing was removed. This was a **very** useful feature for my workflow.

Is it possible to optionally control this behavior? Or is there a replacement/analogous workflow for managing config changes for a very large infrastructure?

Also related to: #50

**Comment by Liujingfang1** [comment]
@robbyt ConfigMaps declared as `resources` won't have name hashing any more, but ConfigMaps created from ConfigMapGenerator will keep name hashing.  You can change those ConfigMaps to ConfigMapGenerators. The most simple change is like this

change
```
resources:
# this file declares a ConfigMap named `the-map`
- configMap.yaml
```
to
```
patches:
- configMap.yaml

configMapGenerator:
- name: the-map
```

**Comment by robbyt** [comment]
@Liujingfang1 This is an unfortunate change because we have hundreds of config maps in our base, and so the migration will require some effort. I think this was a very useful feature, and I don't really understand why it was removed.

If I understand the new workflow you're suggesting, we will need to move each configMap from `resource` to `patches` (in the base kustomize.yaml), and then also define it a second time as a `configMapGenerator` (with no additional parameters)?

**Comment by Liujingfang1** [comment]
The previous default behavior of adding name hashing to ConfigMap was actually a bug. The ConfigMap declared as resource should behave the same as other resources, which means no name hashing should be added.  So we changed the behavior and fixed that bug. With the new behavior, you will have to migrate them ConfigMapGenerator. 
> If I understand the new workflow you're suggesting, we will need to move each configMap from resource to patches (in the base kustomize.yaml), and > then also define it a second time as a configMapGenerator (with no additional parameters)?

This is the minimal change to do the migration. You can also remove all configmap.yaml and use ConfigMapGenerators with filled parameters.

If we need to add an option to enable name hashing for `configmap.yaml` is debatable. I understand adding a flag to control this behavior is convenient. On the other side, it may also lead to some unclear boundaries and non best practices. Currently If users don't need name hashing, then use ConfigMaps as resources; if they need name hashing, then they can pick up ConfigMapGenerator.

**Comment by monopole** [comment]
@robbyt Could you describe why one would want to have a generated suffix added to _literal_ configmaps?   Is this just a case of having a so many configmaps that you don't want to have to name them?  If there are this many, are they created by some process? and could that process apply unique names?

Another option is allowing configMapGenerator to accept literal configmaps in its `files` list.  It would then merge them into one map with a generated name.

**Comment by robbyt** [comment]
@monopole Yes, we have so many configmaps and kustomize's auto-hashing (bug) made it simple to handle changes from an operations perspective. Sadly, all of our configmaps were manually created and have been hand-tuned, and these files have a lot of churn.

If I understand your idea about the `configMapGenerator` merging all into one map, this may be excessively disruptive because it would cause unnecessary/unrelated pod restarts.

Thank you both for explaining why this was removed. It makes sense, the bug was just a handy feature for us. I'll test the alternative workflow that @Liujingfang1 provided, and report back with my results

**Comment by robbyt** [comment]
I started the process of migrating the explicit configMap resources into the configMapGenerator and I've hit an unfortunate issue, which is related to my design. I was overriding the configmap resources on my overlays, to optionally replace entire config maps when needed.

Here is a simplified version of what I've already built (and is working great with v1.0.4). In this example, the base config has sensible defaults for development, but production has the entire configMap replaced.

```
.
├── base
│   ├── config
│   │   └── map1.yaml
│   └── kustomization.yaml
└── overlays
    ├── prod
    │   ├── config
    │   │   └── map1.yaml
    │   └── kustomization.yaml
    └── test
        └── kustomization.yaml
```

With this new change to the configMapGenerator, I get the following error because I've already defined the patch and configMapGenerator resources in the base:

`Error: id resource.ResId{gvk:schema.GroupVersionKind{Group:"", Version:"v1", Kind:"ConfigMap"}, name:"redirect1"} exists; must merge or replace`

**Comment by Liujingfang1** [comment]
In the prod overlay, you can mark the configmapGenerator with `replace` behavior.
https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/types/kustomization.go#L107

**Comment by robbyt** [comment]
Thank you @Liujingfang1 - but this still means that my once simple kustomize files will grow from 655 lines to about 1800 lines.

**Comment by robbyt** [comment]
@Liujingfang1 is there a way to set the replace behavior by default, so it doesn't need to be set for every configMapGenerator entry?

**Comment by bsuh** [comment]
Why should this only be name hashing only be limited to generators? I mean that feature was the biggest value add for us personally. I can concatenate resource files and replace certain resource files with others to create variants using shell scripts. Checking and updating references with a hash isn't so easily doable with shell scripting and solves a real pain point in Kubernetes (see the number of thumbs up on https://github.com/kubernetes/kubernetes/issues/22368). Now having to whitelist every config map is quite the bummer and if someone forgets to update the whitelist then you can expect a few headaches trying to figure it out.

**Comment by robbyt** [comment]
@Liujingfang1 I understand that, sorry I meant can I change the default from create to replace?

**Comment by Liujingfang1** [comment]
@robbyt you can do that only if there is something like this
```
configmapGenerators:
default: <the default behavior user wants to set>
-name: some-configmap
-name: another-map
```
This default behavior should only govern the generators in current kustomization. That means, for different overlays, you need to set the default for each of them. I'm not sure if that will help a lot.

**Comment by robbyt** [comment]
@Liujingfang1 yes, that does help. Thank you!

**Comment by robbyt** [comment]
Btw, I migrated everything to use the configMapGenerator. It works, but my kustomize.yaml is much larger now unfortunately.

However, it seems the previous behavior is completely gone, and if there is no possibility for it to return, we should close this ticket. Agreed?

**Comment by Liujingfang1** [comment]
Opened #230 for tracking the default  behavior
