### ISSUE TITLE
Image Tag Validation rejects valid image names

### ISSUE THREAD

**Issue by iamnoah** [kubernetes-sigs/kustomize#212]
The image tag validation assumes the image will contain only one `:`. However, the image name may include the host and *port* of the (often private) repository holding the image:
https://github.com/moby/moby/blob/master/image/spec/v1.1.md

So this fails:

```
kustomize edit set imagetag myprivaterepohostname:1234/my/image:latest
```

**Comment by Liujingfang1** [comment]
Instead of splitting by `:`, we can use regex to parse image names and get the tag.
