### ISSUE TITLE
`status` reports resources as deleted that exist 

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#2121]
Even though the resources exist, it still prints the message they are deleted

```
EVENT TYPE       AGG STATUS  TYPE                  NAMESPACE        NAME                  STATUS      MESSAGE                                             
ResourceUpdate   Unknown     apps/v1/Deployment                     helloworld-gke        Current     Resource has been deleted                           
ResourceUpdate   Current     v1/Service                             helloworld-gke        Current     Resource has been deleted                           
Completed        Current     
```

and later this even though they exist...

```
TYPE                       NAMESPACE        NAME                  STATUS      MESSAGE                                 
apps/v1/Deployment                          helloworld-gke        Current     Resource does not exist                 
v1/Service                                  helloworld-gke        Current     Resource does not exist 
```

**Comment by mortent** [comment]
Is this running against HEAD?

If I'm in the examples/helloWorld folder and run the following two commands  `kubectl apply -k .` and `resource status fetch .`, I do get the expected results. 

There is an issue I am aware of with the resource commands. It currently only reads the yaml files with the kio library and captures the resource identifiers from those files. If there is a kustomization that changes the name and/or namespace of the resources, the status commands will fail.

If we want the resource command to exist on its own outside of `apply`, this will need to be fixed.
