### ISSUE TITLE
Feature request: Reverse order for deleting resources

### ISSUE THREAD

**Issue by lukasmrtvy** [kubernetes-sigs/kustomize#2138]
Is there something like `kustomize build --reverse . | kubectl delete -f -` as oposite to `kustomize build  . | kubectl apply  -f -` ? 
Would be nice to have reverse order for proper deleting. Deployments where are CRDs involved can return exit code != 0.
Possible workaround:
 `--all=true` will probably suppress errors from uninitialized resources.

**Comment by ofek** [comment]
Hello @monopole @pwittrock @prachirp @mortent ! Has there been any update on such a feature? I noticed an attempted KEP https://github.com/kubernetes/enhancements/pull/1231#issuecomment-534729651

I ran into this when trying to delete dynamically provisioned volumes https://github.com/ofek/csi-gcs/pull/8#issuecomment-615944642

**Comment by ofek** [comment]
Any update?

**Comment by mortent** [comment]
@ofek We have a PR related to this at https://github.com/kubernetes-sigs/cli-utils/pull/207. I'm not sure if it will address your issue, but I'm interested in understanding your use-case better if it isn't sufficient.

**Comment by donmstewart** [comment]
I too am interested in a `reverse` order. All is well when doing. `kubectl apply` to generate namespaces then other resources. When deleting resources again the namespaces are deleted first, but then I receive lots of errors for all the sub-resources, which leads to an exit code of 1 which breaks tooling/automation.
