### ISSUE TITLE
install_kustomize.sh script can't detect alpine linux (docker opperating system)

### ISSUE THREAD

**Issue by karl-gustav** [kubernetes-sigs/kustomize#2146]
The install script runs this check 
```
opsys=windows
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  opsys=linux
elif [[ "$OSTYPE" == "darwin"* ]]; then
  opsys=darwin
fi
```

But $OSTYPE in alpine linux is `linux-musl`
i.e.

```
bash-4.4# echo $OSTYPE
linux-musl
```

which will result in the install script thinking that alpine linux is in fact winwdows.

The fix as I see it would be to just check if the $OSTYPE environment variable starts with "linux"

**Comment by monopole** [comment]
feel free to send a pr

**Comment by karl-gustav** [comment]
@monopole done 😀
https://github.com/kubernetes-sigs/kustomize/pull/2154
