### ISSUE TITLE
Option to disable security check on configmap generator

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes-sigs/kustomize#2159]
I am currently refactoring all our resources to work around the issues we had in the past with nested overlays and configmap generators.

Unfortunately when trying to build I have the following error: 
Error: file sources: [../../base/common/xxx.cfg]: security; file 'base/common/xxx.cfg' is not in or below 'environment/qa'

In my current situation this check doesn't make much sense and there is no other way for me to generate my configmaps.

Is there any way or option to disable this security check?
This is a blocker for me.

**Comment by pre** [comment]
`--load-restrictor LoadRestrictionsNone` is now available
