### ISSUE TITLE
--load_restrictor=none Does not working with remote source

### ISSUE THREAD

**Issue by pastukhov** [kubernetes-sigs/kustomize#2162]
Hi all!
I'm trying to do 
```kustomize build --load_restrictor=none   https://gitlab.domain.local/k8s-addons/flannel```
and i get 
```Error: loading KV pairs: env source files: [/etc/environment]: security; file '/etc/environment' is not in or below '/tmp/kustomize-046091891'```
but if i do same with local copy ```kustomize build  --load_restrictor=none .``` 
everything is going fine.

I need to patch a flannel CNI with my runtime vars of POD_CIDR from current cluster.

**Comment by yujunz** [comment]
This is the expected behavior

https://github.com/kubernetes-sigs/kustomize/blob/c626eae9bd440fd6fa68a165af030c9d85ec3129/api/loader/fileloader.go#L220

**Comment by pastukhov** [comment]
It would be nice to describe this in the documentation.
