### ISSUE TITLE
Error on nil storageClassName Error: <nil> is expected to be either a string or a []interface{} 

### ISSUE THREAD

**Issue by chancez** [kubernetes-sigs/kustomize#2166]
I have a statefulset with `storageClassName: null` and it causes kustomize to fail with:
```
Error: <nil> is expected to be either a string or a []interface{} 
```

I expect that this would simply not care that the field is nil. Tracing it to the code, it seems this is caused by the type switch in https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/accumulator/namereferencetransformer.go#L215 not checking if `in` is nil before type switching. I'm not familiar so I don't know the correct fix, but I've had success with the following:

```
        return func(in interface{}) (interface{}, error) {
+               if in == nil {
+                       return nil, nil
+               }
                switch thing := in.(type) {
```

The only thing with this simple change is it seems like it wouldn't catch issues when a name is required, but without this it's preventing valid configurations from working.

**Comment by lukasmrtvy** [comment]
I can confirm this.  ( especially if You are using upstream helm charts with chartInflator plugin )

**Comment by bjhaid** [comment]
@chancez any reason why you did not submit a PR with the change you have in:

https://github.com/chancez/kustomize/commit/293f1f693b5650d9559659b4b0beb7c330393d64

?

**Comment by chancez** [comment]
I had some questions on whether or not it was the correct fix and hadn't dug into it deeply enough.

**Comment by Shell32-Natsu** [comment]
I cannot reproduce the error with the latest kustomize. Please reopen and provide your resources files if you still have the issue.

/close
