### ISSUE TITLE
Remove globbing support

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#217]

**Comment by Place1** [comment]
why was globbing support removed? this is a useful feature

**Comment by coderanger** [comment]
Asking again, is there a reason this was removed? It's kind of required for a lot of existing use cases. The stated replacement is that you should regenerate your kustomization.yml every run, which is kind of pointless, why not just make the regen tool handle what I need then, defeats the point of static config data being static.

**Comment by codecyclist** [comment]
I would really appreciate this change to be reverted, as it heavily limits the flexibility and integration options for kustomize.
As a first-time kustomize user, I thought this was a bug or an early-release problem until I found that issue..

**Comment by zfrank** [comment]
Explanation is in #207

**Comment by fuog** [comment]
i also vote strongly for globbing support. But I also understand the concerns. Why not an optional feature flag as a compromise? CLI / ENV Var? Default should stay off imo.
`--enable-globbing` ?

**Comment by sne4ky** [comment]
The whole rationale from removing this feature comes from a development perspective. This is not software architecture, this is Infrastructure as Code. There is big push to bring this feature back, and that is a sign that the feature **should have never been removed**.
