### ISSUE TITLE
nameSuffix and namePrefix as Vars

### ISSUE THREAD

**Issue by mojtabacazi** [kubernetes-sigs/kustomize#2171]
It would be nice to have a nameSuffix and Prefix available as a var, for example :

```spec:
  template:
     spec:
       containers:
         - name: nginx-ingress-internal-controller
           args:
             - /nginx-ingress-controller
             - '--ingress-class=nginx-$(KUSTOMIZE_NAME_SUFFIX)'
```

**Comment by smakam** [comment]
I have a similar requirement where I am having a service name as an environment variable in the yaml file and if I use the name prefix or suffix, I dont have a way to change the environment variable value dynamically. If the NAME_SUFFIX or NAME_PREFIX can be used, that will solve this problem...
        env:
          - name: VOTING_API_ADDR
            value: voting-service:3001

**Comment by neilharris123** [comment]
This would be useful.

**Comment by schrej** [comment]
In case anyone else stumbles across this issue in the future:

The 'name reference transformer' keeps track of all resource names and magically substitutes them everywhere. But not actually everywhere. It only works for fields where kustomize expects a reference to another resource. Fortunately this list of fields [can be extended quite easily](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#name-reference-transformer).

If you want to, for example, replace the name of a service in an env variable of a container in a deployment, you can use the following config:

```yaml
# name: namereferences.yaml
nameReference:
  - kind: Service
    fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/containers/env/value

```

```yaml
# in kustomization.yaml
# [...]
configurations:
  - namereferences.yaml
```
