### ISSUE TITLE
visitNAList in `kyaml/yaml/merge3/visitor.go` ought to merge on GVK for objects of kind *List

### ISSUE THREAD

**Issue by khrisrichardson** [kubernetes-sigs/kustomize#2187]
In the `visitNAList` method of `kyaml/yaml/merge3/visitor.go`, when a difference is detected (`values.Update != values.Origin`) the method ought not return the updated node in its entirety, but rather should keep walking to find the smallest subset of differences between nodes. This is exhibited by a pretty large disparity in the results when a set of objects is wrapped with `kind: List` versus when each object is treated individually.

**Comment by pwittrock** [comment]
IIUC, you are requesting that it recursively walk non-associative lists (associative lists should be walked).  In this case, what would it use as the merge key to identify same items?

**Comment by khrisrichardson** [comment]
I gave it a stab and also couldn't quite grapple with how that comparison would work sans merge key, although I do suspect that something could be done to address the disparity of outcomes when the object is or isn't wrapped in a List (merge on metadata.name). Using type List has the bonus side-effect that added or removed items are properly handled with the merge command versus out-of-band handling of those cases.

**Comment by pwittrock** [comment]
@khrisrichardson I put together a solution that i think can address this -- you can directly annotate the list field with what you want to use as the merge key

See #2245
