### ISSUE TITLE
please improve kustomize tutorial & intro info

### ISSUE THREAD

**Issue by rvandegrift** [kubernetes-sigs/kustomize#2190]
A few kubectl issues have lead me to kustomize, and I'd like to learn about it.  But the tutorial page [1] is kind of perplexing:
* It doesn't instruct me to do anything, and it isn't obvious how I make it go.  I think it's waiting on me?
* Maybe I'm supposed to upload yaml manifests, but I'm nervous because I don't know what'll happen to data that I upload.  And since I don't really know what kustomize does, I don't know what data would be useful.

I think it'd help to have a directed walkthrough of a simple kustomize use-case.  If data is required for an interactive tutorial, please supply a sample data set that illustrates some useful beginner lessons.

[1] - https://kustomize.io/tutorial

**Comment by wiorka** [comment]
It also simply doesn't work for me. I uploaded a simple manifest and it loaded in the left tab, but clicking on a line does nothing, it's impossible to edit anything. Tried in Opera and Firefox. 
The docs seem detailed, but there is no clear structure to them and it's not obvious what the steps should be to have a simple working flow.

**Comment by lucbas** [comment]
When clicking on any line, I also get a 500 error:

<img width="682" alt="Screenshot 2020-05-08 at 14 16 20" src="https://user-images.githubusercontent.com/14868134/81404757-87c02700-9136-11ea-95e5-7a2dce839025.png">

**Comment by robax** [comment]
@rvandegrift would appreciate a /reopen on this - the web editor is still not working.

**Comment by rvandegrift** [comment]
hi @robax - as far as I can tell kustomize.io is abandoned.  I don't think reopening makes sense, it'll just be closed again in a while.

**Comment by robax** [comment]
Thanks for the swift reply @rvandegrift , such is life!

**Comment by sqqqrly** [comment]
Another tool named spruce may work for you.  It has many more features such as semantic diff between yamls along with deep merges. https://github.com/geofffranks/spruce
