### ISSUE TITLE
error: AccumulateTarget: trouble cloning Gitlab repository: exit status 128

### ISSUE THREAD

**Issue by FelixRodriguezJara** [kubernetes-sigs/kustomize#2198]
Hello, Kustomize team,

I am getting crazy with this error. I am using "minikube" and kubectl version 1.16, that comes with Kustomize 2.0.3. I have read many posts about the stucture that the repository URL should have, but none of them works for me. 

My kustomization file contains two resources that are based in a remote Gitlab repository, like this:

````
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://gitlab.com/mindcurv-k8s-kustomize/vendors/prometheus.git
- https://gitlab.com/mindcurv-k8s-kustomize/vendors/thanos.git
resources:
- ./pv-prometheus.yaml
- ./prometheus-operator-serviceAccount.yaml
````

When executing "kubectl apply -k .", I ge the error below:

````
[root@devvm prometheus]# kubectl apply -k .
error: couldn't make loader for https://gitlab.com/mindcurv-k8s-kustomize/vendors/prometheus.git: trouble cloning https://gitlab.com/mindcurv-k8s-kustomize/vendors/prometheus.git: exit status 128
couldn't make loader for https://gitlab.com/mindcurv-k8s-kustomize/vendors/thanos.git: trouble cloning https://gitlab.com/mindcurv-k8s-kustomize/vendors/thanos.git: exit status 128
````

I have tried multiple ways of defining the URL, but, or I get the cloning error, or I get a "File does not exist". Could you please let me know how the URL should be written?

Thank you very much.

Kind regards.

**Comment by Liujingfang1** [comment]
@FelixRodriguezJara  Is this a private repo? Please change it to the link for ssh clone.

**Comment by FelixRodriguezJara** [comment]
Hello Liu,

Yes, it is indeed. Thing is I switched to the http url and it works! The only issue is that it prompts for the gitlab username and pwd. Is there any way of storing the credentials somewhere so it picks them up automatically at connection time?

Thank you very much.

Kind regards.

**Comment by Liujingfang1** [comment]
@FelixRodriguezJara Handling the credentials is out of the scope of Kustomize. You need to address it by either ssh key or username/password.

**Comment by pdgistio** [comment]
username:password when provided in the url "git::http://username:password@github.com/repo.git?ref=r"
throwing error 
Error: couldn't make loader for <url>
without username:password, when provided the same when prompted it is working.
Note: username and password are url encoded
could you please point me to the example which has username and password incorporated in url
