### ISSUE TITLE
kustomize edit add base/resource with remote URL not working

### ISSUE THREAD

**Issue by Shplorf** [kubernetes-sigs/kustomize#2208]
When I try to do something like
`kustomize edit add resource github.com/org/repo//config?ref=master` or
`kustomize edit add base github.com/org/repo//config?ref=master`
I keep getting errors like `Error: [URL] does not exist`

Is there a way to do this?

Using kustomize version `v3.5.4`

**Comment by Liujingfang1** [comment]
As for now, `kustomize edit add` only works for local files or dirs. We need to improve it.

**Comment by joncwong** [comment]
I can take a look into this.

**Comment by timbocau** [comment]
Is there any chance that this problem will be resolved soon?

**Comment by pwittrock** [comment]
@timbocau because this is in the porcelain command it is considered less critical than other areas we are focussed on right now.

Would you consider filing a PR to address it?  [link to edit command](https://github.com/kubernetes-sigs/kustomize/tree/master/kustomize/internal/commands/edit)

Do you rely upon this command as part of any automated workflows?

**Comment by timbocau** [comment]
@pwittrock The Best Practice for using remote bases / resources recommends usage of explicit references (e.g. Git revisions). On a new revision of the remote resource we want to automatically replace the current revision with the new one in kustomization.yaml. This change should also trigger ArgoCD to update resources in Kubernetes.

Filing a PR would be hard as I am not familiar with the Go Language.

**Comment by julianwilkinson** [comment]
@timbocau what we're doing is just using the program yq if that helps. It's pretty intuitive in our workflow

**Comment by laurosn** [comment]
A possible workaround could be clone the base repo first and then use kustomize edit add pointing to the local file.

**Comment by andrewmclagan** [comment]
> A possible workaround could be clone the base repo first and then use kustomize edit add pointing to the local file.

I would have thought this more "best practice" rather than a workaround
