### ISSUE TITLE
Unable to change image if it contains a colon

### ISSUE THREAD

**Issue by christopherL91** [kubernetes-sigs/kustomize#221]
I'm unable to use `kustomize edit set imagetag "localhost:5000/operator":1.0.0` as I like to build and push my images locally. The code here https://github.com/kubernetes-sigs/kustomize/blob/3b3a272d278bcdf0f7752732d0e7281ae9deb65b/pkg/transformers/imagetag.go#L84-L88 suggests that there can only be one colon inside the image field

**Comment by Liujingfang1** [comment]
Similar to #213, we should use regexp to parse the set imagetag arguments
