### ISSUE TITLE
Adding a variable in a ConfigMap creates a new ConfigMap resource instead of updating the existing one.

### ISSUE THREAD

**Issue by mfaur** [kubernetes-sigs/kustomize#2226]
Hey, I am currently running my Kubernetes cluster using Kustomize and have several ConfigMaps being generated by the ConfigMap generator.  The problem I have run into is that whenever I update a variable within the ConfigMap, Kustomize generates a whole new ConfigMap with a new hash. This causes a buildup of old ConfigMaps that must be deleted manually and it causes all the services using the ConfigMap to be recreated even if the new variable isn't relevent to them.
Example:
`cat kustomization.yaml`:
```
configMapGenerator:
  - name: general-configmap
    namespace: demo
    envs: [configmap.env]
```
`cat configmap.env`:
```
node_env=dev
db_ip=10.0.0.1
app_id=123456
```
when running `kustomize build . | kubectl apply -f -` a new ConfigMap will be generated with a hash and `kubectl get configmaps` will show:
```
NAME                           DATA   AGE
general-configmap-5hchgdk59b   3     1m6s
````
But then If I want to add a new variable in `configmap.env` for example:
```
node_env=dev
db_ip=10.0.0.1
app_id=123456
new_env=test
```
after I run `kustomize build. | kubectl apply -f -` another new ConfigMap will be generated with a new hash and `kubectl get configmaps` will show:
```
NAME                           DATA   AGE
general-configmap-5hchgdk59b   3     2m3s
general-configmap-95b7265c24   4     7s
```
What I would like is for Kustomize to simply update the already existing Configmap so that the result would look like:
```
NAME                           DATA   AGE
general-configmap-5hchgdk59b   4     2m3s
```
 Is it possible for Kustomize to recognize the difference between changing an already existing ConfigMap and creating a new one?

**Comment by chancez** [comment]
You can use `disableNameSuffixHash` in [generatorOptions](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md#generatoroptions).

**Comment by jsravn** [comment]
Related to https://github.com/kubernetes-sigs/kustomize/issues/242
