### ISSUE TITLE
Support specifying images with both tag and digest

### ISSUE THREAD

**Issue by yanniszark** [kubernetes-sigs/kustomize#2234]
Images can have the very useful form of `<image_name>:<tag>@sha256:<digest>`

This allows the best of both worlds:
* Git version is immediately visible, which enables quickly tracking down the source code.
* Protection from tag overrides / malicious actions, as the digest is immutable.

Today, kustomize's imageTransformer offers the `newTag` and `digest` options, but specifying both will result in `digest` being specified.
* We get `<image_name>@sha256:<digest>`.
* We want `<image_name>:<newTag>@sha256:<digest>`

We'd like a way to support this form.

> While this can be achieved today by placing `<tag>@sha256<digest>` in newTag, it is semantically wrong to do so.

Perhaps the imageTransformer can expose an option to enable this behavior vs the default one of just specifying the digest?

**Comment by jceb** [comment]
Whoops, sorry. Just noticed that there's a workaround. The issue can be closed.

**Comment by kaiffeetasse** [comment]
@jceb could you provide a link or source to the workaround?

**Comment by danopia** [comment]
I believe the workaround is mentioned above:

> While this can be achieved today by placing `<tag>@sha256<digest>` in newTag, it is semantically wrong to do so.
