### ISSUE TITLE
arm64 build support

### ISSUE THREAD

**Issue by brendarearden** [kubernetes-sigs/kustomize#2235]
Now that Helm 3 supports a --post-renderer flag to be set, making kustomize even easier to integrate with, is it possible to get arm64 builds? I am currently unable to use it reliably because an arm64 binary is not offered.

**Comment by odidev** [comment]
Hi,

We are working on [contour](https://github.com/projectcontour/contour) which has a dependency on this package, So we would like to know when will arm64 build will be available.

**Comment by tnxgalaxy** [comment]
you can use `kubectl kustomize` from kubectl 1.14
source: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/

**Comment by brendarearden** [comment]
@tnxgalaxy I am attempting to use this with [helm as a post renderer,](https://helm.sh/docs/topics/advanced/#post-rendering ) so I would need the binary available, is there a way to point to the binary that is included with kubectl?

**Comment by tnxgalaxy** [comment]
@brendarearden you could try writing a small wrapper script, a script you could call kustomize and that itself calls kubectl kustomize with the parameters it's given, the content could look like this:

#!/usr/bin/env bash
/path/to/kubectl kustomize $@

Please let me know if that does the job.

**Comment by Shell32-Natsu** [comment]
ARM builds will be available in next release.
