### ISSUE TITLE
kustomize unknown version

### ISSUE THREAD

**Issue by fffffreedom** [kubernetes-sigs/kustomize#2242]
i installed the kustomize by running cmd:
GO111MODULE=on go get sigs.k8s.io/kustomize/kustomize/v3@v3.3.0
or 
GO111MODULE=on go get sigs.k8s.io/kustomize/kustomize/v3
but get an unknown version kustomize:
fffffreedom:~ jonny$ kustomize version
{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:darwin GoArch:amd64}

**Comment by pwittrock** [comment]
@fffffreedom The version is specified at build time through a flag.  You would need to specify that flag when building locally.  AFAIK, there is no way to pull the tag information from the code.
