### ISSUE TITLE
What is the replacement for `bases`?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/kustomize#2243]
https://github.com/kubernetes-sigs/kustomize/blob/2a8a17e3af263c8cd61452bd2fc5e2e7d7bc5330/api/types/kustomization.go#L85-L88

I see `bases` is deprecated. What is the replacement?

**Comment by chancez** [comment]
If I understand correctly, `resources` can be used to point to a directory containing a `kustomization.yaml` for these purposes.

**Comment by pwittrock** [comment]
@chancez correct -- you can specify bases as resources

**Comment by MikaelSmith** [comment]
https://github.com/kubernetes-sigs/kustomize/issues/776#issuecomment-461459130 demonstrates they have some notable differences. Bases seems to be the better option for what I'm trying to do and several other uses I've seen.

**Comment by tolgaingenc** [comment]
But if you define bases with resources it requires the base to be "in or below" which is a bad idea if you wont dublicate base per env.  How am I supposed to put base within dev or prod?

MyRepo
├───base
│   ├───db
│   ├───frontend
│   ├───service1
│   ├───service2
└───env
    └───dev 
    └───prod

**Comment by coderatchet** [comment]
Can someone please confirm if this is/will be fixed by 1.19?

**Comment by timhughes** [comment]
@coderatchet  Added an explanation on this ticket (as far as i can work it out) https://github.com/kubernetes/kubectl/issues/891#issuecomment-731238572
