### ISSUE TITLE
build command to result in output configurations within appropriate nested directories structure if need be.

### ISSUE THREAD

**Issue by govinda-attal** [kubernetes-sigs/kustomize#2254]
We are planning to use kpt functions and kustomize along with each other.

Kpt functions when apply config changes and later if output is sink to a target directory, it can generate the output files in relevant directories. I think it is able to do so with help of these annotations: (please note config.kubernetes.io/path)

`
annotations:
      config.kubernetes.io/index: '0'
      config.kubernetes.io/path: 'ocp/kustomization.yaml'
`

It could be really handy of kustomize to keep track of file paths and help in generating output suitably.

We plan to use these (kpt and kustomize) for Anthos config-connector resources, which requires to have configs in a repo in this structure: https://cloud.google.com/anthos-config-management/docs/concepts/repo?hl=sl.

Any thoughts or direction could help.

**Comment by pwittrock** [comment]
@govinda-attal This is something we plan to tackle by rebasing kustomize on top of the same libraries used by kpt functions -- the kyaml libraries in the kustomize repo.  Will also address a number of other issues such as keeping comments and structure.

**Comment by pwittrock** [comment]
@monopole another rebase issue
