### ISSUE TITLE
provide usage of helm charts as part of build only

### ISSUE THREAD

**Issue by rverma-jm** [kubernetes-sigs/kustomize#2262]
While following the tutorial at https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md, i observe that we still need the ChartInflator plugin.
Can we handle the plugin downloading during the build phase, which allow the existing CD system to work without change. 
For ref, we are currently using spinnaker which have kustomizaton support..

**Comment by khrisrichardson** [comment]
@rverma-jm as an option you might want to keep an eye on the [kpt](https://github.com/GoogleContainerTools/kpt) project in general and what's happening in issue https://github.com/GoogleContainerTools/kpt-functions-catalog/issues/24 in particular to shift the concern of upstream configuration file synchronization to a tool dedicated to that function.
