### ISSUE TITLE
How to customize a simple namespace creation?

### ISSUE THREAD

**Issue by frgomes** [kubernetes-sigs/kustomize#2266]
I would like to replace the value of ``/metadata/name`` by the contents of an environment variable.
I've read lots of docs and I've tried lots of things, without success.
Could anyone suggest a ``kustomization.yaml`` file which can do that, please?

```
apiVersion: v1
kind: Namespace
metadata:
  name: default
```

Note: Yes, I could simply generate this file, or I could just create the namespace using an initial command ``kubectl``... yes, I know... but I don't want to do that. I want to generate a single .yaml file which contains everything I need, including the creation of the namespace.

**Comment by hscspring** [comment]
when i use a `namespace`, i got `CreateContainerConfigError`..
