### ISSUE TITLE
Support writing output to file

### ISSUE THREAD

**Issue by ppawiggers** [kubernetes-sigs/kustomize#227]
I'd like the output of `kustomize build` to be written to a file, without using ` > myfile.yaml`.

Reason: I'm playing with Google Cloud Build and I need to generated manifest in the next step. I have this step configuration:

    - name: 'kustomize:1.0.5'  # a self-built Alpine container with kustomize as entrypoint
      args: ['build', 'overlays/production', '>', 'kubernetes.yaml']

But this does not work; the part `> kubernetes.yaml` is concatenated to the location of the kustomization.yaml file, resulting in this error: `Error: specify one path to kustomization.yaml`

What does work:

    - name: 'kustomize:1.0.5'  # a self-built Alpine container with kustomize as entrypoint
      entrypoint: '/bin/sh'
      args: ['-c', 'kustomize build overlays/production > kubernetes.yaml']

But that's ugly.

Is it an option to include a parameter to write the output to a file? E.g. `kustomize build -o kubernetes.yaml overlays/production` . Or does any of you have a tip for me how to make it work with Google Cloud Build?

**Comment by robbyt** [comment]
@ppawiggers perhaps you could write a wrapper script that does this, and then call that from the cloud build? e.g.,

```
#!/bin/sh
kustomize build overlays/production > kubernetes.yaml
```

**Comment by ppawiggers** [comment]
@robbyt thanks for you reply. Yes, that's possible, but I don't like additional shell scripts in my repo, so I like to avoid that if possible.

**Comment by Liujingfang1** [comment]
We can add a `-o <path>` to write the output to a file.
