### ISSUE TITLE
Provide arm and arm64 binaries

### ISSUE THREAD

**Issue by onedr0p** [kubernetes-sigs/kustomize#2270]
It would be cool to provide support for arm and arm64 binaries on the releases page.

**Comment by brendarearden** [comment]
https://github.com/kubernetes-sigs/kustomize/issues/2235. << duplicate - we can close one in-favor of the other

**Comment by onedr0p** [comment]
Nice, I must have missed this in the search before I posted.

**Comment by brendarearden** [comment]
No worries - just hope we get the arm support!
