### ISSUE TITLE
commonLabel applied to Service without selector

### ISSUE THREAD

**Issue by palsivertsen** [kubernetes-sigs/kustomize#2273]
I'm in the process of migrating resources into Kubernetes. During this process some resources (e.g. storage) live _outside_ Kubernetes. To route to these resources one can use [this trick](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors) which involves creating a Service without selectors and manually managing the corresponding Endpoint. This only works as long as the Service is set up without any selectors. However if the `kustomization.yaml` file configuring the Service has a `commonLabels` field, then a selector for is added for every label.

**Comment by pwittrock** [comment]
Its common for folks to use commonLabels to set selectors on Services without a selector.

You may be able to work around this by putting the Service in a separate Kustomization.yaml without the commonSelectors.

**Comment by chancez** [comment]
This seems similar to my issue in #2256, take a look and see if my proposed solution seems suitable for your use-case @palsivertsen

**Comment by chancez** [comment]
@twz123 You probably need to use the `patches` transformer to do what you would like.

**Comment by twz123** [comment]
@chancez That's what I meant by "applying patches doesn't work". I suppose that commonLabels get applied _after_ the patches transformations.

**Comment by chancez** [comment]
I'm saying you need use `patches` instead of `commonLabels`, not to remove the unwanted changes to the selector.

**Comment by twz123** [comment]
Ah yes, now I understand. That's what I actually did. But it's very cumbersome, since I actually _need_ to add additional label selectors in other places.

**Comment by Shell32-Natsu** [comment]
Similar with #2034. kustomize has a builtin list of fields that will be set by `commonLabel`. You can overwrite it with you own choice. Please see https://github.com/kubernetes-sigs/kustomize/issues/2034#issuecomment-673079108

**Comment by monopole** [comment]
Please see comment at end of https://github.com/kubernetes-sigs/kustomize/issues/2034;
trying to consolidate this as a feature request, not a bug.
