### ISSUE TITLE
Feature Request: Move git cloner to to go-git

### ISSUE THREAD

**Issue by jasonrichardsmith** [kubernetes-sigs/kustomize#2281]
Is the team open to updating the git pull from "exec" to https://github.com/src-d/go-git

**Comment by yujunz** [comment]
The `master` branch has included a lite version of hashicorp/go-getter which includes git support. It does not suppress the git-cloner though, for backward compatibility. See  https://github.com/kubernetes-sigs/kustomize/pull/2278#discussion_r395190951 for details.

It sounds good to me to replace `exec` with package, but I would prefer leverage the existing `go-getter` module to introducing new dependencies.

**Comment by jasonrichardsmith** [comment]
@yujunz Go-getter looks good, but you still need git if you want to use ssh keys.

I am working on a controller that uses straight git and kustomize/krusty.  Having to use git leaves me with a pretty bloated container.  I will see if I can override the git implementation.  Thank you.
