### ISSUE TITLE
Generate yaml with the same order of original yaml

### ISSUE THREAD

**Issue by forest-hou** [kubernetes-sigs/kustomize#229]
We found when kustomize builds the yaml, it changes the order of some items. This makes diff tool not easy to catch the changes.

It is great if kustomize  can generate output with the same order of original yaml.

**Comment by Liujingfang1** [comment]
@forest-hou Do you mean the order in `kustome build` output or the order in `kustomization.yaml`? 
For the former one, kustomize adjusts the order of different resources. For example, namespace, service account and rbac resources are put in the first groups in the output. Other resources are in alphabet order. For the latter one, currently there is an issue to track #17.
