### ISSUE TITLE
RFC: Resource patch types

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#2290]
@lavalamp 
@sttts 
@apelisse 

## Current Patch Types

Currently kustomize supports the following patch types:

- Json6902
- StrategicMergePatch

## Patch Direction

Kustomize is migrating from the apimachinery unstructured libraries for working with resources to the kyaml libraries. This is motivated by:

- the need to keep yaml structure, format, comments, etc which is lost when serializing through 
 go types such as `interface{}`, `map[string]interface{}`, `type Foo struct {}`
- the need to remove all dependencies on libraries published out of kubernetes/staging
- the need to inline OpenAPI definitions directly into resource configuration types / fields

StrategicMergePatch will be move to the [kyaml version](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/kio/filters/merge.go) -- planned Q2

Json6902 will continue to serialize through map[string]interface{} until there is an implementation that works against the yaml v3 libraries.

## Server Side Apply

Server side apply implemented logic for merging resources.  @lavalamp has suggested making this available as a merge option for kustomize.  To leverage the SSA merge logic it would need to support the same semantics as the kyaml merge:

- [ ] retain yaml formatting
- [ ] have no dependencies on any code published out of kubernetes/staging
- [ ] support the same OpenAPI sources (e.g. inlined, read from file, etc)

**Comment by lavalamp** [comment]
...you're encouraging clients to directly write SMP patches ?!

We are going to delete that code! It is buggy and unmaintained.

SSA merging works at least as well and users write a more natural patch.

We lack a way to delete a field, but have talked about adding one. Do you need that feature, or are your patches additive?

**Comment by apelisse** [comment]
Few questions:
- I'm assuming you have the openapi ... (I know, that's not a question)
- Are you merging patches of different versions? I'm hoping you don't :-/
- Do you need a mechanism to remove items from an associative list or a map?
- How do you plan on implementing union and immutability?
- How do we guarantee that client-side and server-side implementations are doing the same thing?

Beside that, the implementation should be trivial.

**Comment by apelisse** [comment]
> ...you're encouraging clients to directly write SMP patches ?!

I'm assuming that it mostly look like a JMP but they handle the patchMergeKey

**Comment by pwittrock** [comment]
> I'm assuming you have the openapi ... (I know, that's not a question)

Yes

> Are you merging patches of different versions? I'm hoping you don't :-/

We support cross-cutting patches that match based on type, name and labels.  E.g. a patch could be specified to apply object meta to all resources with a given label.

> Do you need a mechanism to remove items from an associative list or a map?

TBD.  Currently the JSON patch supports this through operations.

> How do you plan on implementing union and immutability?

I'm not sure what immutability means when there is no persistent object.

> How do we guarantee that client-side and server-side implementations are doing the same thing?

What is the server in the case of merging 2 files?

**Comment by lavalamp** [comment]
> Currently the JSON patch supports this through operations

Not really, you can't reference a named list item, only an index. Not useful if you don't know what operations come after or before.

**Comment by apelisse** [comment]
> > How do you plan on implementing union and immutability?
> 
> I'm not sure what immutability means when there is no persistent object.

Yeah, I'm curious if it makes any sense and if you've thought about it.

**Comment by lavalamp** [comment]
>>How do we guarantee that client-side and server-side implementations are doing the same thing?

>What is the server in the case of merging 2 files?

The concern is that A + B = C when done on the client, but if you send the same manifests via SSA you get C'.

**Comment by pwittrock** [comment]
> We are going to delete that code! It is buggy and unmaintained.

I hear you, but it's also widely used and the default for kubectl apply today.  Has SMP been officially deprecated?

> The concern is that A + B = C when done on the client, but if you send the same manifests via SSA you get C'.

I'd like to know more about how you see this fitting into user workflows.

It's not clear to me that SSA merge will always do what users want in this context --  e.g. how would one change only the port on a [ServicePort](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#serviceport-v1-core) when patching a base.  The sorts of merges folks need for kustomize patches are different from those needed in the context SSA was designed for.

I agree we want the default behavior to be consistent with what kubectl/cli-utils uses for apply.

> We lack a way to delete a field, but have talked about adding one. Do you need that feature, or are your patches additive?

This feature will be needed by some users.  I'm not sure how many.  My guess that it is less common than additive but will be a blocker for those that need it.

**Comment by pwittrock** [comment]
@lavalamp 

How much do we want to consider changing SSA merge to meet client-side needs?  e.g. preserving yaml

**Comment by lavalamp** [comment]
SSA takes an interface now. So, it probably doesn't need to be changed at all for that.

**Comment by pwittrock** [comment]
> SSA takes an interface now. So, it probably doesn't need to be changed at all for that.

Is that a `interface{}` or `type Something interface { some functions}`

**Comment by lavalamp** [comment]
Both, actually. (that is, it takes the latter but there's a built in implementation that takes the former)

**Comment by apelisse** [comment]
The interface as it is today is mostly used to avoid copying/allocating Unstructured when unneeded. But it won't carry over the specific details that Phil would want, since it will just create an Unstructured as the output.

**Comment by lavalamp** [comment]
Ah, that's true. We need to wire in a `New()` function of some sort.

**Comment by pwittrock** [comment]
The builtin won't keep the yaml structure (comments, structure, etc).  The latter might work.

**Comment by apelisse** [comment]
> Ah, that's true. We need to wire in a New() function of some sort.

Even `New()` is difficult, because it needs to propagate specific details about every "Value", thus it would have to be super context-aware.

**Comment by lavalamp** [comment]
I'm definitely open to making the constructor. That might improve efficiency in some cases, too.

**Comment by lavalamp** [comment]
If everything is connected to a field, it should be OK? if there's random other stuff like unattached comments then yeah, that seems harder.

**Comment by pwittrock** [comment]
Everything is attached to a Node, this is mostly fields, but there are some exceptions such as the "Document" Node.

**Comment by lavalamp** [comment]
Is that root level? What if we started by copying LHS, or RHS, or maybe better, let the user pass a "blank" destination object in?

**Comment by apelisse** [comment]
Alternately, we could also do the operation in place rather than create a whole new object. We haven't optimized performance for apply (mostly updates so far), but we might want to do that eventually anyway.

**Comment by lavalamp** [comment]
Oh, of course--that sounds much simpler.

**Comment by pwittrock** [comment]
We also need to support a 3-way merge for updates (original remote repo, updated remote repo, forked copy).  Would this also be supported?

**Comment by apelisse** [comment]
We don't do 3 way merges, that's the beauty of it :-)

**Comment by pwittrock** [comment]
How would you apply changes when updating a package?

**Comment by lavalamp** [comment]
I need to understand what your system does for a 3 way merge. I would have expected a client side merge followed by using SSA to update the live object.

**Comment by lavalamp** [comment]
Oh, I see, this is like an application template update, not a live object?

**Comment by lavalamp** [comment]
I think you should consider re-running the SSA algorithm, where "live" object is the "forked copy", the fieldset / manger is set as if the original remote made an apply to the local copy, and the updated remote copy is a follow-up apply.

**Comment by pwittrock** [comment]
Can we avoid writing the fieldset to the forked copy?

**Comment by lavalamp** [comment]
You can reconstruct it if you have history for both objects. If the possible changes are constrained, it may not be needed, but that seems unlikely to be true.

You can produce a field set by diffing the original remote and current forked copy. That is probably close enough to be useful.

**Comment by pwittrock** [comment]
Sounds like this is possible then.

**Comment by lavalamp** [comment]
Yeah I think if we assume everyone did "force conflicts" changes, then the simple diff does the right thing.

**Comment by dthomson25** [comment]
Hey @pwittrock and @lavalamp, I was looking for a fix like https://github.com/kubernetes-sigs/kustomize/pull/2105 and saw this issue was opened from it. I wanted to ask how users would write Kustomize overlays for CRDs if they wanted an SMP like an experience.  I know Json6902 and MergePatch are supported out of the box, but that does not have nearly the same kind of flexibility of SMP. I have some understanding of SSA, but I'm not sure how that factors into users writing a kustomize overlay.

**Comment by lavalamp** [comment]
Personally, I'd advocate for kustomize adopting SSA's merging semantics :)

**Comment by dthomson25** [comment]
I'm not very familiar with SSA merging semantics. Do you have a link where I can read up on it more?

Since I'm still a little unclear what the final solution is going to look like, I want to give a brief use-case and confirm how it aligns with the solution. The key functionality that I'm looking for is having a common base that all environments use with an environment-specific overlay for CRDs. For example, if I have the following [base](https://gist.github.com/dthomson25/1f9e16ea7a552047e2afc8222b14ddf6), [overlay](https://gist.github.com/dthomson25/92dac1affb8477671f0be461e7c0509d), and [kustomization.yaml](https://gist.github.com/dthomson25/9de1633a99fda85fd4a68db604b4384a), I would like to get the following [result](https://gist.github.com/dthomson25/ef7c2451486f5860ac063cff0c3c3477) when I do a kustomize build which I can then apply with Kubectl. I know that I could achieve this example with a MergePatch or a JSON6902 patch, but these patches are significantly harder to maintain in a non-toy example. 

Am I wrong to assume that I would use the strageticMergePatch field in the kustomization.yaml? Or @lavalamp, are you suggesting that there should be a serviceSideApply field? If that's the case, what are the semantics for creating that overlay?

If I would still use the strageticMergePatch field in the kustomization.yaml, would kustomize talk to the API Server to merge the base and overlay and output that as the yaml?

**Comment by apelisse** [comment]
@dthomson25 Thanks for your patience! 😅 

I think a simple strategic merge patch would work if Kustomize knew the schema and could use it to merge the patch. Server-side apply some of these same mechanism but also requires knowing about the schema.

@monopole Can one specify an arbitrary schema in kustomize to find additional merge information?
