### ISSUE TITLE
Getting fails to load: plugin: not implemented when using custom generator plugin

### ISSUE THREAD

**Issue by omninonsense** [kubernetes-sigs/kustomize#2299]
I'm not sure what happens to "rotten" issues, so I've reopened the #1641 issue with the same title. I guess this can be considered a duplicate.

I am experiencing the same issue with Kustomize v3.5.4 as described in #1641:

```
kustomize version
{Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
```

Go version:

```
go version
go version go1.13.9 linux/amd64
```

This is the output of `tree`:

```
.
├── build
│   └── omninonsense.github.io
│       └── v1beta
│           └── sopsgenerator
│               └── SOPSGenerator.so
├── build_helpers.go
├── docs
│   └── kustomize-plugins.md
├── examples
│   ├── database
│   │   ├── deployment.yaml
│   │   ├── kustomization.yaml
│   │   ├── postgres.env
│   │   ├── service.yaml
│   │   └── sops.yaml
│   └── README.md
├── go.mod
├── go.sum
├── kustomize-sopsgenerator.code-workspace
├── Makefile
├── README.md
├── SOPSGenerator.go
├── SOPSGenerator_test.go
└── __test__
    ├── encrypted
    │   ├── secret.env
    │   ├── secret.json
    │   └── secret.yaml
    ├── pgp.asc
    └── plain
        ├── secret.env
        ├── secret.json
        └── secret.yaml
```

After building the plugin, I run:

```sh
cd examples
export KUSTOMIZE_PLUGIN_HOME=$(readlink -f ../build)
kustomize build --enable_alpha_plugins database/
```

Which gives me:

```
Error: loading generator plugins: plugin /home/(…)/build/omninonsense.github.io/v1beta/sopsgenerator/SOPSGenerator fails to load: plugin: not implemented
```

The plugin exists, though:
```
ls /home/(…)/build/omninonsense.github.io/v1beta/sopsgenerator/
SOPSGenerator.so
```

**Comment by omninonsense** [comment]
Alas, I figured it out. The problem was that I was downloading the `kubernetes` binary from the GitHub release. This isn't even a _kustomize_ error that's being reported, it's an error that Go itself is reporting (I think the "overloaded" use of the term plugin is what's causing some confusion, at least it did for me)

I _think_ the compiled `kustomize` on the release page comes it comes without `plugin` support, because it was compiled with `CGO_ENABLED=0`. The [`golang.org/src/plugin/plugin_stubs.go`](https://golang.org/src/plugin/plugin_stubs.go) ultimately gave me the hint to look in the right direction.

Installing Kustomize via `go get sigs.k8s.io/kustomize/kustomize/v3@v3.5.4` solves the issue. I will leave this open for now in case the maintainers want to look into this? If not, the @k8s-ci-robot/@fejta-bot will close it automatically (probably).

CC-ing you since you were part of the discussion in the issue before (sorry if it's noise): @arthurgustin, @oboukili, @snarlysodboxer

**Comment by omninonsense** [comment]
In case this is just a quirk of Kustomize (whether desired or not) that's not trivial to fix, maybe it's worth documenting it somewhere? I quickly glanced over the documentation, but haven't found it being mentioned anywhere.

**Comment by Shell32-Natsu** [comment]
Will check does this still exist.

**Comment by Shell32-Natsu** [comment]
This is still happening in the latest release (v3.8.6). However, I suspect that this is intended. Since in the [GO plugin guide](https://kubernetes-sigs.github.io/kustomize/guides/plugins/gopluginguidedexample/#install-kustomize)

> Need v3.0.0 for what follows, and you must compile it (not download the binary from the release page):

**Comment by omninonsense** [comment]
Awesome that it's documented now! 😁

**Comment by maazmmd** [comment]
```
cd /path/to/kustomization.yaml
kustomize build --enable-alpha-plugins . | kubectl apply -f -
```

Should solve the issue

**Comment by travis-jorge** [comment]
> This is still happening in the latest release (v3.8.6). However, I suspect that this is intended. Since in the [GO plugin guide](https://kubernetes-sigs.github.io/kustomize/guides/plugins/gopluginguidedexample/#install-kustomize)
> 
> > Need v3.0.0 for what follows, and you must compile it (not download the binary from the release page):

This documentation is dead. Do you know where the new one is? im stuck on this issue.
