### ISSUE TITLE
Conflation between "config set" and "config list-setters"

### ISSUE THREAD

**Issue by bzub** [kubernetes-sigs/kustomize#2308]
`config set DIR` is in the command's [documentation](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/commands/set.md), but fails with `Error: requires at least 3 arg(s), only received 1`.

Should we fix `config set` so it lists setters again, or update the documentation to use `config list-setters DIR`, or both?

**Comment by pwittrock** [comment]
Let's update the documentation to use `list-setters`.
