### ISSUE TITLE
NamePrefix support for secrets in ingress annotations

### ISSUE THREAD

**Issue by Lax77** [kubernetes-sigs/kustomize#234]
NamePrefix / name reference is currently seems to skip  for secrets used in ingress annotations.

eg annotation:
nginx.ingress.kubernetes.io/auth-secret: basic-auth

Can we expand the support for ingress annotations as well? - Thanks

**Comment by Liujingfang1** [comment]
Need to add `nginx.ingress.kubernetes.io/auth-secret` to the pathconfig in namereference transformer.
