### ISSUE TITLE
Migrate Kustomize resource infrastructure to yaml native libraries

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/kustomize#2340]
Kustomize uses `map[string]interface{}` instances for working with resources.  These drop structure and comments when serializing them.  We should keep both structure and comments.

Migrate to the kyaml libraries for this.

**Comment by pwittrock** [comment]
cc @lukadante

**Comment by monopole** [comment]
This issue may close when  #2506 closes.
Will re-review then.
