### ISSUE TITLE
shell completion: kustomize panic: runtime error: slice bounds out of range [:11] with length 10

### ISSUE THREAD

**Issue by developer-guy** [kubernetes-sigs/kustomize#2351]
I try to install kustomize command completion for zsh so first I did : 

`kustomize install-completion`

then I looked at my .zshrc file , this command added this line as follows: 

`complete -C /Users/USER/go/bin/kustomize kustomize`

then when I did kustomize TAB , there is an error occurred.

 
![Screen Shot 2020-04-08 at 21 55 51](https://user-images.githubusercontent.com/16693043/78822794-555ec500-79e4-11ea-9537-1ee6e20b2952.png)

**Comment by developer-guy** [comment]
I am using this version btw.
![Screen Shot 2020-04-08 at 22 17 26](https://user-images.githubusercontent.com/16693043/78824278-c606e100-79e6-11ea-8385-9d51fb2b7cc0.png)

**Comment by pwittrock** [comment]
@phanimarupaka would you take a look?

**Comment by developer-guy** [comment]
@phanimarupaka I want to pair with you to solve this problem, is it possible?

**Comment by phanimarupaka** [comment]
@developer-guy 

I tried to reproduce the issue and failed to do so. It's working fine for me.

![image](https://user-images.githubusercontent.com/58999035/79398716-268da500-7f36-11ea-9896-b9dc939e9f22.png)

I would recommend you to 

Run COMP_UNINSTALL=1 kustomize install-completion, restart terminal, run kustomize install-completion

If it doesn't work, uninstall zsh and reinstall it following these instructions
https://www.freecodecamp.org/news/how-to-configure-your-macos-terminal-with-zsh-like-a-pro-c0ab3f3c1156/

Let me know if none of them works. Here is the source code for the command. You might try and add some print statements, compile kustomize binary locally, try and localize the issue.
