### ISSUE TITLE
unclear error message with invalid resource yaml

### ISSUE THREAD

**Issue by pmahoney** [kubernetes-sigs/kustomize#2358]
Running kustomize 3.3.1, I have a pvc.yaml with `spec.storageClassName: `. The output of `kustomize build` was:

```
Error: <nil> is expected to be either a string or a []interface{}
```

which gives me no indication as to _where_ that error occurred. I discovered the source by my searches happening to turn up this issue: https://github.com/kubernetes-sigs/kustomize/issues/2166

Is there any way kustomize could provide more details on the source of the error? Ideally a file and line number, but even just the name of the key (storageClassName), or the resource kind, or anything would be an improvement.

**Comment by theAkito** [comment]
Stupid bot closed a perfectly valid issue, once again. 🙄 

Having a similar problem with the same error message right now, but I cannot test so easily where the actual issue is. If this feature would've been implemented, I wouldn't experience this problem, now.
