### ISSUE TITLE
Can we get a 1.0.6 release?

### ISSUE THREAD

**Issue by iamnoah** [kubernetes-sigs/kustomize#236]
Hello! I'm keen to use the set image tag functionality in our CI pipeline (we have a private registry with a port spec, so it's broken with 1.0.5.) Can we get a 1.0.6 release?

**Comment by Liujingfang1** [comment]
We will release a new version once #17 is fixed.

**Comment by Liujingfang1** [comment]
https://github.com/kubernetes-sigs/kustomize/releases/tag/v1.0.6

**Comment by iamnoah** [comment]
1.0.6 is the same tagged commit as 1.0.5 and does not contain any changes... The changelog is even the same.

**Comment by Liujingfang1** [comment]
@iamnoah My bad. Let me fix it.

**Comment by Liujingfang1** [comment]
The release is updated. It is correct now.
