### ISSUE TITLE
releases don't have binaries

### ISSUE THREAD

**Issue by pax-awitt** [kubernetes-sigs/kustomize#2370]
following the instructions for installing for linux, i went to the releases page, which contains no binaries.  since there are no binaries, the installation script provided also does not work.

**Comment by tinselspoon** [comment]
Just noticed the same thing - the release binaries are there, but you have to go back two pages before they start to show up.

See here for the binaries: https://github.com/kubernetes-sigs/kustomize/releases?after=cmd%2Fconfig%2Fv0.0.10

I'm not sure what the other releases actually are, but perhaps there is a way of filtering them out from that page.
