### ISSUE TITLE
Generate a docker image as part of release process.

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#2374]
Sign properly, store in some trusted image repo etc.

**Comment by monopole** [comment]
Will test this in next release.

**Comment by Shell32-Natsu** [comment]
Staging repo for kustomize: gcr.io/k8s-staging-kustomize/kustomize

Note this repo is a *staging* repo, the `latest` tag is following the HEAD in master branch. We will promote the stable releases to production k8s.gcr.io. Meanwhile we will tag every release in this staging repo as well.
