### ISSUE TITLE
Error: json: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type patch.StrategicMerge

### ISSUE THREAD

**Issue by hanyouqing** [kubernetes-sigs/kustomize#2390]
I wanted to add a sidecar container with kustomize, and following the docs here https://github.com/kubernetes-sigs/kustomize/blob/1dad3f09757130b4c1149a8e48eb5c076cd46c07/examples/patchMultipleObjects.md, but it doesn't work any more.  

got the error blow:

```
Error: json: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type patch.StrategicMerge
```

kubectl version:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:48Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Anyone have suggestions?

* kustomization.yaml

```
patches:
- path: patch_sidecar.yaml
  target:
    kind: Deployment
```

* patch_sidecar.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:

      - name: envoy
        image: envoyproxy/envoy
```

BTW, it seems that a large number of official documents are out of date.

Anyone can help? @phanimarupaka @novalagung @monopole

**Comment by mkuhl** [comment]
I have exactly the same issue. kubectl version v1.17.1

**Comment by hanyouqing** [comment]
> I have exactly the same issue. kubectl version v1.17.1

Any progress or solution?

**Comment by kingfai** [comment]
I hit the same thing. Is it because `patches` is deprecated? See https://github.com/kubernetes-sigs/kustomize/issues/1373#issuecomment-513401204

**Comment by hanyouqing** [comment]
> reason

Yeah, thanks! it should be the reason, we've use `kustomize` instead of `kubectl kustomize` for a while.
