### ISSUE TITLE
 delete the inventory transformer and related docs

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#2392]
The experiment described in
https://github.com/kubernetes/enhancements/pull/810
greatly informed the k8s approach to pruning/garbage
collection.  The relevant code has moved into
the client-side apply operation, and is no longer
needed in kustomize.

Code to delete:
 
- plugin/builtin/inventory
- Makefile reference to the plugin
- api/internal/target/kusttarget.go,
  code paths that call
    MakePruneConfigMap
    computeInventory
- types/garbagepolicy.go --- this struct goes away, and retain
  only code path associated with the GarbageIngore policy

Documentation (some of this also serves as E2E test data):

- docs/howItWorks.md
- docs/inventory_object.md
 
The latter doc should be drained, not deleted.  it should lead users
to a description of the replacement technology and procedures - talk to seans3@

**Comment by seans3** [comment]
Here is the link to apply/prune in `kpt live`: https://googlecontainertools.github.io/kpt/reference/live/apply/#prune

**Comment by seans3** [comment]
There should be a link to apply/prune functionality in `cli-utils`, but it does not exist yet. So initially, I think we will have some type of `coming soon` message.

**Comment by Shell32-Natsu** [comment]
@monopole Hi Jeff, so how should we update the docs/inventory_object.md?

Donny

**Comment by Shell32-Natsu** [comment]
@monopole Hi Jeff, can we close this issue?

**Comment by monopole** [comment]
belated yes. cleaning house
