### ISSUE TITLE
Support helm v3 in the chartinflator plugin

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#2396]
Partially done in  #2321 and #2394 

Please see the `TODO implement` comments in [plugin/someteam.example.com/v1/chartinflator/ChartInflator](https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/someteam.example.com/v1/chartinflator/ChartInflator)

(and enable the corresponding test).

**Comment by aodinokov** [comment]
@monopole , please see my comment [1]. If you want me to finish, just assign it to me.
The only concern I have is that unit-tests not related to this change for current master fail. And I typically don't do PRs without testing :) . I'll look into that deeply, may be I'm doing something wrong, but I remember, that it worked 20 days ago.
As an alternative you can just take these changes from my working branch

[1]
https://github.com/kubernetes-sigs/kustomize/pull/2321#issuecomment-618802406

[2]
https://github.com/aodinokov/kustomize/tree/finalize_helm_v3_support

**Comment by aodinokov** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/2416
