### ISSUE TITLE
commonAnnotations path ignored

### ISSUE THREAD

**Issue by jeusdi** [kubernetes-sigs/kustomize#2398]
Here my kustomize files structure:

    $ tree ./kustomize/base
    ./kustomize/base
    ├── configurations
    │   ├── common-annotations.yaml
    │   └── common-labels.yaml
    ├── kustomization.yaml
    ├── resources
    │   ├── deployment.yaml
    │   └── service.yaml
    └── transformers
        ├── annotations-transformer.yaml
        └── labels-transformer.yaml

My `kustomization.yaml`:

    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization

    configurations:
      - configurations/common-annotations.yaml
    
    commonAnnotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/port: '8080'
      prometheus.io/scrape: 'true'

    resources:
      - resources/deployment.yaml
      - resources/service.yaml

My `configurations/common-annotations.yaml` is:

    commonAnnotations:
        - path: spec/template/metadata/annotations
          create: true
          # group: apps
          version: apps/v1
          kind: Deployment

As you can see, I only want to add annotations on `Deployment` objects. However, 

    $ kustomize build kustomize/base
    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      name: covid-backend
    spec:
      ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      name: covid-backend
    spec:
      replicas: 2
      template:
        metadata:
          labels:
            app2: covid-backend
        spec:
          containers:
          - image: covid-backend
            ports:
            - containerPort: 8080

As you can see, it's adding annotation to all objects (service, deployment...), except on `spec/template/metadata/annotations`. It's exactly the opposite I need.

If I comment `configurations` on `kustomize.yaml`:

    $ kustomize build kustomize/base
    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      name: covid-backend
    spec:
      ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      name: covid-backend
    spec:
      replicas: 2
      template:
        metadata:
          annotations:
            prometheus.io/path: /actuator/prometheus
            prometheus.io/port: "8080"
            prometheus.io/scrape: "true"
          labels:
            app2: covid-backend
        spec:
          containers:
          - image: covid-backend
            ports:
            - containerPort: 8080

Then, annotations are added also on `spec/template/metadata/annotations`.

Here the diff:

28,31d27
<       annotations:
<         prometheus.io/path: /actuator/prometheus
<         prometheus.io/port: "8080"
<         prometheus.io/scrape: "true"

**Comment by monopole** [comment]
@Shell32-Natsu  ptal and triage this?

**Comment by Shell32-Natsu** [comment]
Will take a look

**Comment by Shell32-Natsu** [comment]
`commonAnnotation` will add the annotation to the metadata/annotations field for all resources. Annotations are also added to spec/template/metadata/annotations for Deployment, ReplicaSet, DaemonSet, StatefulSet, Job, and CronJob resources, and spec/jobTemplate/spec/template/metadata/annotations for CronJob resources.

See https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#annotations-transformer

The reason why it's not added to the `Deployment/spec/template/metadata/annotations` is your incorrect `configurations/common-annotations.yaml`. Please try this:

```
commonAnnotations:
    - path: spec/template/metadata/annotations
      create: true
      group: apps
      version: v1
      kind: Deployment
```

API version `apps/v1` is constructed by *group* `apps` and *version* `v1`.

**Comment by monopole** [comment]
@Shell32-Natsu is right.

Another alternative, which is more modern, is eschew the `configurations:` field (it's not very flexible) and use specific transformer configurations.

PTAL at this example

https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configureBuiltinPlugin.md
