### ISSUE TITLE
[HELP] SedTransformer not reached

### ISSUE THREAD

**Issue by jeusdi** [kubernetes-sigs/kustomize#2426]
Here, my plugins forler:

    $ ls kustomize/plugin/kustomize.rollout/v1/sedtransformer -l
    -rwxr-xr-x 1 jeusdi jeusdi 127 abr 30 12:05 SedTransformer

When I'm trying to perform it:

    $ kustomize build  --enable_alpha_plugins kustomize/overlays/dev

I'm getting this error:

> Error: accumulating resources: recursed accumulation of path '/home/jeusdi/projects/spring-boot-slab/kustomize/base': failure in plugin configured via /tmp/kust-plugin-config-926027305; fork/exec kustomize/plugin/kustomize.rollout/v1/sedtransformer/SedTransformer: no such file or directory: fork/exec kustomize/plugin/kustomize.rollout/v1/sedtransformer/SedTransformer: no such file or directory

It's telling me that `SedTransformer` doesn't exist. As you can see above it really exists and has `a+x` permissions.

Any ideas?

**Comment by monopole** [comment]
Try

```
KUSTOMIZE_PLUGIN_HOME=~/kustomize/plugin \
   kustomize build --enable_alpha_plugins kustomize/overlays/dev
```

this should work assuming that everything else is specified correctly

e.g. if i have a directory /tmp/foo with 

/tmp/foo/kustomization.yaml
```
generators:
- chartInflator.yaml
```
/tmp/foo/chartInflator.yaml
```
apiVersion: someteam.example.com/v1
kind: ChartInflator
metadata:
  name: notImportantHere
chartName: minecraft
```

i can run
```
KUSTOMIZE_PLUGIN_HOME=~/gopath/src/sigs.k8s.io/kustomize/plugin \
    kustomize build --enable_alpha_plugins /tmp/foo
```

where i've cloned the kustomize repo to ~/gopath/src/sigs.k8s.io/kustomize

That means that 
```
~/gopath/src/sigs.k8s.io/kustomize/plugin/someteam.example.com/v1/chartinflator/
```
exists and contains the plugin `ChartInflator`

**Comment by monopole** [comment]
you don't need to clone the kustomize repo this way; set up whatever structure you want as long as `KUSTOMIZE_PLUGIN_HOME` points to the dir tree where your plugins live
