### ISSUE TITLE
kustomize vs Server Side Apply

### ISSUE THREAD

**Issue by JCzz** [kubernetes-sigs/kustomize#2427]
Hi

Just trying to understand kustomize and saw the "Server Side Apply" in [k8s 1.81 release](https://kubernetes.io/blog/2020/04/01/kubernetes-1.18-feature-server-side-apply-beta-2/)

Can you help me understand if there is an overlap with kustomize and merging og yaml?

Thanks in advance

**Comment by JohnRusk** [comment]
This seems like a good question.  I will make a new issue to see if I can get some traction on it.
