### ISSUE TITLE
Reuse configuration, DRY

### ISSUE THREAD

**Issue by villesau** [kubernetes-sigs/kustomize#2464]
Let's say I have following configs:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cron1
spec:
  schedule: '0 3 * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 2
      template:
        spec:
          nodeSelector:
            highmem: "true"
          tolerations:
            - key: reserved-pool
              operator: Equal
              value: "true"
              effect: NoSchedule
          containers:
            - name: test-cron
              image: gcr.io/proc/app:latest
              resources:
                requests:
                  memory: "4Gi"
              command:
                [
                  'node',
                  '--max-old-space-size=8192',
                  '--unhandled-rejections=strict',
                  'test.js',
                ]
          restartPolicy: Never

```

and 

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cron2
spec:
  schedule: '0 2 * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 2
      template:
        spec:
          nodeSelector:
            highmem: "true"
          tolerations:
            - key: reserved-pool
              operator: Equal
              value: "true"
              effect: NoSchedule
          containers:
            - name: test-cron2
              image: gcr.io/proc/app:latest
              resources:
                requests:
                  memory: "4Gi"
              command:
                [
                  'node',
                  '--max-old-space-size=8192',
                  '--unhandled-rejections=strict',
                  'test2.js',
                ]
          restartPolicy: Never

```

As you see big chunks of them are identical (in the example only command and schedule differs). How do I combine single config out of it so that I can reuse or inherit it for `test-cron` & `test-cron2` with Kustomize? It's tedious to have multiple close to identical configs when one could rely on inheritance or extending the config. Due to human error some of the configs might not get updated, or then they might unnecessarily drift apart.

In optimal case I would only define schedule & command for both `test-cron` & `test-cron2`, and have the rest in shared base config. Obviously, I also do not need `schedule` or `command` in the shared base config.

How to achieve this?

**Comment by whillas** [comment]
If you use a recent version of Kustomize you can do this with overlays. Common code in the `base` dir. and each overlay pulls that in and applys patches to the parts you want https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/patches/

**Comment by Shell32-Natsu** [comment]
Please take a look at https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md

**Comment by deepakinseattle** [comment]
@villesau did you ever figure out a solution to this? I've tried using [overlays](https://github.com/kubernetes-sigs/kustomize/issues/2464#issuecomment-686810110) and [components](https://github.com/kubernetes-sigs/kustomize/issues/2464#issuecomment-707894172) but haven't figured out how to dry up my configuration. 

I'm in the same spot as you. I've got multiple cron jobs that I'd like to define as a single "base" cron template and be able to patch that (name, command, schedule) for `N` cron jobs.

**Comment by ppawiggers** [comment]
I solved it like this:

```
├── base
│   ├── kustomization.yaml
│   ├── namespace.yaml
│   └── service-account.yaml
├── base-cron-job
│   ├── cronjob.yaml
│   └── kustomization.yaml
├── cron-jobs
│   ├── my-first-cron-job
│   │   └── kustomization.yaml
│   └── my-second-cron-job
│       └── kustomization.yaml
└── overlays
    └── prod
        └── kustomization.yaml
```

`overlays/prod/kustomization.yaml`:

```
resources:
  - ../../base
  - ../../cron-jobs/my-first-job
  - ../../cron-jobs/my-second-job

images:
  - name: my-cron-job-image
    newName: some-image
    newTag: some-tag
```

and the `kustomization.yaml` per cron job:

```
namePrefix: my-first-job-

resources:
  - ../../base-cron-job

patches:
  - target:
      kind: CronJob
    patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/args
        value:
          - my-first-job

```
