### ISSUE TITLE
add annotation/label to resources being built from kustomize

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#2474]
Can we add an annotation/label to resources being built from kustomize? This annotation can be used to distinguish which resources are generated/transformed by kustomize. 

By default, this annotation is added when users run `kustomize build`. Users can disable it by a flag.

**Comment by mcristina422** [comment]
Could this include the kustomize version?

**Comment by Liujingfang1** [comment]
Yes, this can include the kustomize version.
