### ISSUE TITLE
How to pass a variable through kustomize edit set image command?

### ISSUE THREAD

**Issue by jiatongw** [kubernetes-sigs/kustomize#2475]
Hi,

I am referring to `image` examples.  https://github.com/kubernetes-sigs/kustomize/blob/master/examples/image.md

If I want to update a image to a newtag with variable, say:

`image: busybox:3.6` -> `image: busybox:'${TAG}'`, where `'${TAG}'` is a variable that I can pass runtime later. How can I pass the variable through`kustomize edit set image` command?

I tried `kustomize edit set image busybox=busybox:'${TAG}'`, `busybox=busybox:"'${TAG}'"`, `busybox=busybox:"\'${TAG}\'"`, none of them worked.

**Comment by lucbas** [comment]
We are using the edit image command as following in our pipeline:

`kustomize edit set image $DEPLOY_IMAGE`

**Comment by lucbas** [comment]
Actually, I just noticed that the edit set command successfully adds an entry in the kustomize.yaml file (base folder) for the new image.

But when building an overlay, I see that it has not been applied.

**Comment by jiatongw** [comment]
@lucbas Thanks! I'll try and report if I have any question

**Comment by jiatongw** [comment]
Close this issue. Thanks for help!
