### ISSUE TITLE
Remove dependence on k8s.io/apimachinery and related k/k libs

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#2506]
kustomize api depends on k/k/apimachinery in api/k8sdeps and api/internal/k8sdeps.

This dependency must be removed to update the kustomize functionality built into kubect (currently lagging the standalone kustomize).

As an ancillary benefit, kustomize will rebase on (and coevolve with) the kyaml libraries

This issue blocks #1500

**Comment by ofek** [comment]
Any update on this?

**Comment by Shell32-Natsu** [comment]
We need to refactor a lot of codes to free use from the apimachinery. We have limited resources so it will take some time.

**Comment by modevops** [comment]
any update on this?
