### ISSUE TITLE
Hard-wired timeout of 5s for secretGenerator commands

### ISSUE THREAD

**Issue by ivan4th** [kubernetes-sigs/kustomize#252]
Right now there's a hard-wired timeout of 5 seconds for `secretGenerator` commands, which may be an issue if the command, for example, asks user for a passphrase or performs some other action that may take more time than 5s:
https://github.com/kubernetes-sigs/kustomize/blob/7406dda074ff33aa274d3b89362121cc79c1bc98/pkg/configmapandsecret/secretfactory.go#L129-L131

One possible solution is #251 but it (at least) needs to be changed to add a timeout field to `secretGenerator` instead of adding a new command line flag.

**Comment by Liujingfang1** [comment]
We may add a timeout field to `secretArgs`. This field should be optional. If unset, use current default 5 seconds.

**Comment by monopole** [comment]
A new field in secret generator with a hard coded default sounds right to me.
