### ISSUE TITLE
how to ovveride ports in all deployment and service

### ISSUE THREAD

**Issue by rverma-jm** [kubernetes-sigs/kustomize#2523]
Wondering if we can leverage kustomization to update port in 
1. Deployment in container port, readines/liveness Probe port
2. Service port
3. In crds, like Istio's virtual service port, service monitors port.

It seems changing the port required putting multiple patches which is as good as copying the original resource.

**Comment by monopole** [comment]
to help move this along, please flesh out a minimal use case of objects with these fields to support building a unit test to demo the feature

**Comment by Shell32-Natsu** [comment]
/close

Feel free to reopen
