### ISSUE TITLE
Calling one common base image and create different image using the same base configuration.

### ISSUE THREAD

**Issue by shekhar-d** [kubernetes-sigs/kustomize#2531]
I am new to kubernetes but found it very interesting.

My use case is : I have to deploy multiple pods with change of image and few config variables by maintain a generic structure.

I am using kustomize to implement this.

I am able to create Mutiple pods by using resource in kustomize and defining deployment and config map files.

But I want to maintain a common base file which contains my memory, port and common properties.

My problem: 
I am not able to link the base deployment to multiple overlays at same time.

Below are the cases I have tried:

**1.**  I kept the same name (test) for base deployment and overlay deployment and used prefix/suffix in kustomize.
**RESULT:** error: AccumulateTarget: MergeResourcesWithErrorOnIdCollision: id '"apps_v1_Deployment|namespace-sample|~P|test|~S"' already used

**2.** I kept the same name (test) for base deployment and overlay deployment but this time overlay deployment in patches in kustomize instead of resource. 
**RESULT:** It updates the base pod configuration and run it but in this I can't create multi pods with same base deployment file.

**3.** I kept different name (base-test, test) for base deployment and overlay deployment. 
**RESULT:** No error but my purpose is not fulfilled as it created 2 different pods.

**Comment by monopole** [comment]
please explicitly show (in the issue) the simplest case of your inputs (pod.yaml files, config.yaml - whatever) and most importantly the output you expect.

**Comment by shekhar-d** [comment]
Sorry for responding late. This issue was resolved using config generator , defining labels at coorect place , and secret generator of base and overlays concept.
Closing this task from my side.
