### ISSUE TITLE
Entry `resources` from kustomization.yaml supports only relative and absolute paths

### ISSUE THREAD

**Issue by mszostok** [kubernetes-sigs/kustomize#254]
## Problem
The documentation is misleading. We can read that in the `kustomization.yaml` file under the **resources** entry we can have:
> any format that kubectl -f allows, i.e. files, directories, URLs and globs.

**Source:**
https://github.com/kubernetes-sigs/kustomize/blob/v1.0.6/pkg/types/kustomization.go#L42-L45

but unfortunately, it's not true. 

Here is a logic which loads the files from the **resources** entry:
https://github.com/kubernetes-sigs/kustomize/blob/v1.0.6/pkg/resmap/resmap.go#L154

and underlying/finally it always calls the `ioutil.ReadFile` from the standard library
https://github.com/kubernetes-sigs/kustomize/blob/v1.0.6/pkg/loader/fileloader.go#L104-L111

So URL will not be supported at all. Also, regex are also not supported, for example:
```yaml
resources:
- ../rbac/*.yaml
- ../manager/*.yaml

```

In the kubectl the have more complex logic for handling that, see: https://github.com/kubernetes/kubernetes/blob/v1.11.2/pkg/kubectl/genericclioptions/resource/builder.go#L190-L196. 

#### Tested version
```
Version: {KustomizeVersion:1.0.6 GitCommit:017c4ae0aa19195db2a51ecc5aa82c56a1f1c99b BuildDate:2018-08-10T16:45:55Z}
```
## Expectation

The documentation is adjusted and present the correct state with some examples, or the logic from the kubectl is ported to the kustomize repo.

**Comment by Liujingfang1** [comment]
@mszostok That is the intended behavior of Kusotmize. Directory and regex are not supported. The URL support will be added. 

We will update the documentation to be precise and consistent with Kustomize behavior.

**Comment by pohly** [comment]
> The URL support will be added.

Which issue tracks that? https://github.com/kubernetes-sigs/kustomize/issues/923 is about `bases`, so that's different.
