### ISSUE TITLE
SSH Custom Port and Repository Subpath Base URL

### ISSUE THREAD

**Issue by FelixRodriguezJara** [kubernetes-sigs/kustomize#2540]
Hi!

After going through docs and posts, I haven´t found a clear explanation of the format that the URL of a base repository should have.

My case is a gitlab URL connected via SSH on a custom port. I would like to access to a path of the repository, however, I can´t get to the right URL despite of I have tried many suggestions from the issues regarding this topic.

The only way I have managed to make it work is the following:

- 'ssh://git@gitlab.business-keeper.com:203/mindcurv/k8s-kustomize/vendors/kafka.git'

However, when I add the path at the end, it fails:

- 'ssh://git@gitlab.customer.com:203/mindcurv/k8s-kustomize/vendors/kafka.git//operator'

Could you please let me know how can I build this URL so I can accesss to the repository via SSH on a custom port and download a path inside?

Thank you very much.

Kind regards.

**Comment by simlun** [comment]
I had similar difficulties to get it to work, but finally this works for me on a local Bitbucket Server on a custom port, path and commit ref:

```
bases:
  - ssh://git@bitbucket.example.com:7999/myproject/myrepository.git//kustomize/sub/directory?ref=74b79527ba7bb3f86e17a61ad8eecdee18de21e1
```

Using bundled `kustomize` in `kubectl` CLI version 1.17.4.

**Comment by monopole** [comment]
We should document the supported formats, even if its just a pointer to go-getter formats.

Documentation can go here: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md#resources-1

**Comment by Shell32-Natsu** [comment]
@FelixRodriguezJara Could you please provide the error message?

**Comment by Shell32-Natsu** [comment]
@monopole There is a link to go-getter format. However go-getter doc itself is a mess. Some of them don't match the code.

**Comment by monopole** [comment]
That library is ambitious.  Maybe too ambitious.

**Comment by Shell32-Natsu** [comment]
The good news is they have created a PR for refactoring the project. https://github.com/hashicorp/go-getter/pull/255. Hopefully the issues will go away in near future.
