### ISSUE TITLE
fish completion error: "panic: COMP_POINT env should be integer, got: "

### ISSUE THREAD

**Issue by joar** [kubernetes-sigs/kustomize#2561]
The completions installed by `kustomize install-completion` for `fish` seems to be broken.

I realize the issue might be in an upstream dependency of `kustomize. Feel free to report it to the appropriate upstream, or ask me to do it.

# Steps to reproduce

```console
$ docker run --rm -it ubuntu:20.04
....
root@docker$ # now inside the container:
root@docker$ apt update && apt install -y fish curl
root@docker$ fish --version
fish, version 3.1.0
root@docker$ fish
```
from now on we're inside a fish shell
```console
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
root@docker(fish)$ curl --fail --location https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.6.1/kustomize_v3.6.1_linux_amd64.tar.gz | tar -xz kustomize
root@docker(fish)$ mv ./kustomize /usr/local/bin
root@docker(fish)$ kustomize install-completion
install completion for kustomize? y
installing...^J     
```
may need some empty inputs to cause completion to be discovered
```console
root@docker(fish)$
root@docker(fish)$ 
```
once completion has been installed, triggering any completion causes an error message to be printed:
```console
root@docker(fish)$ kustomize <TAB>panic: COMP_POINT env should be integer, got: 

goroutine 1 [running]:
github.com/posener/complete/v2.Complete(0x19cd6dd, 0x9, 0x1ca4f00, 0xc0003d7160)
	/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/complete.go:79 +0x563
github.com/posener/complete/v2.(*Command).Complete(...)
	/go/pkg/mod/github.com/posener/complete/v2@v2.0.1-alpha.12/command.go:20
main.main()
	/workspace/kustomize/main.go:21 +0x63
```

## Reproduction screencast
[![asciicast](https://asciinema.org/a/6udXiOjRh0iw5cR7ZZHcsimY7.svg)](https://asciinema.org/a/6udXiOjRh0iw5cR7ZZHcsimY7)

# Initial workaround

Modify `~/.config/fish/completions/kustomize.fish`:

```fish
function __complete_kustomize
    set -lx COMP_POINT (commandline -C)
    set -lx COMP_LINE (commandline -cp)
    test -z (commandline -ct)
    and set COMP_LINE "$COMP_LINE "
    /home/joar/src/kustomize_v3.5.4_linux_amd64/kustomize
end
complete -f -c kustomize -a "(__complete_kustomize)"
```

**Comment by monopole** [comment]
is this fish specific, or a problem with the completer?

**Comment by monopole** [comment]
can you show this is a kustomize issue?  at first glance it looks upstream in the completer

**Comment by rocketraman** [comment]
I have the same issue on fish 3.0.2. kustomize completion works fine with bash.

**Comment by Shell32-Natsu** [comment]
This should be the issue in https://github.com/posener/complete
