### ISSUE TITLE
SecretGenerator in kustomize

### ISSUE THREAD

**Issue by aleybovich** [kubernetes-sigs/kustomize#2581]
Our kustomization.yaml contains this secretGenerator:

```
secretGenerator:
    - name: my-secrets
      env: password.env
```

where password.env has key-value pairs for secrets that end up as env variables in the containers.

We used to do our deployments using `kubectl -k` and it all worked fine. Now we are trying to switch to use the latest version of kustomize, and I get an error `Error: json: unknown field "env"`

Looking thru some older issues it looks like the functionality has been removed, but it's unclear how to replace it. The documentation still has the secretGenerator examples as mine above. Any advice?

**Comment by aleybovich** [comment]
After some trial and error I realized that the functionality is still there, but kustomize uses `envs` parameter instead of `env`

**Comment by madhukar93** [comment]
kubectl uses older kustomize
