### ISSUE TITLE
How to merge env variables?

### ISSUE THREAD

**Issue by kfehrenbach** [kubernetes-sigs/kustomize#2583]
Let's assume you have the following section in a YAML:
```- env:
        - name: JAVA_OPTS
          value: |-
            -XX:+UseG1GC
            -XX:+UseStringDeduplication
            -XX:MaxMetaspaceSize=512m
            -Xmx6g -Xms6g
```
How can you add a Parameter to the env-variable JAVA_OPTS, to that the YAML now looks like:

```- env:
        - name: JAVA_OPTS
          value: |-
            -XX:+UseG1GC
            -XX:+UseStringDeduplication
            -XX:MaxMetaspaceSize=512m
            -Xmx6g -Xms6g
            -Dlogging.elasticsearch.cluster_name=logging
            -Dlogging.elasticsearch.host=elasticsearch-logging-svc
```

Is that even possible?

Thanks in advance!

**Comment by monopole** [comment]
The (alpha) valueAddTransformer can add a value into a file path - either at the end, the end or somewhere in the middle.  it does so by being told that the value in the field being modified is a filepath, and can then take appropriate action with splitting, modifying and rejoining.

We could adapt this to other types.  e.g. types that hold strings delimited by spaces (e.g. command line flags like JAVA_OPTS) or types that hold strings delimited by ":" (e.g. PATH)

**Comment by monopole** [comment]
the transformer uses the valuadd.go filter, whose test is here:
https://github.com/kubernetes-sigs/kustomize/blob/master/api/filters/valueadd/valueadd_test.go
