### ISSUE TITLE
patch multiple resources

### ISSUE THREAD

**Issue by jvluso** [kubernetes-sigs/kustomize#2584]
I am trying to create an overlay for my staging environment to add `gcr.io/jvluso/` as a prefix to every deployment's image name, and to add a few other fields. when I do this I get the following error:
```
Error: AccumulateTarget: AccumulateTarget: found multiple objects []resid.ResId{resid.ResId{gvKind:gvk.Gvk{Group:"apps", Version:"v1", Kind:"Deployment"}, name:"deployment", prefix:"live-event-client-", suffix:"", namespace:"default"}, resid.ResId{gvKind:gvk.Gvk{Group:"apps", Version:"v1", Kind:"Deployment"}, name:"deployment", prefix:"live-event-service-", suffix:"", namespace:"default"}} targeted by patch resid.ResId{gvKind:gvk.Gvk{Group:"apps", Version:"v1", Kind:"Deployment"}, name:"deployment", prefix:"", suffix:"", namespace:"default"} (ambiguous)
```
What is the appropriate way to apply a patch to multiple resources? Is there a way to do it with vars and annotations?

**Comment by pwittrock** [comment]
https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/patches/

**Comment by rvaidya** [comment]
I found the examples in here helpful: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md
