### ISSUE TITLE
sort containers behind initContainers

### ISSUE THREAD

**Issue by rdxmb** [kubernetes-sigs/kustomize#2586]
Actually, when parsing an output with `kustomize build`, the order is

```
containers:
   - name:
[...]
initContainers:
  - name:
[...]
```

as the initContainers are started before the containers, I expected:

```
initContainers:
  - name:
[...]
containers:
   - name:
[...]
```

**Comment by monopole** [comment]
yep

**Comment by pwittrock** [comment]
The fields are sorted alpha-numerically by the go serialization.

The `kustomize cfg fmt` will be available in the next release, and will provide a more intentional field ordering.

**Comment by rdxmb** [comment]
Thanks
