### ISSUE TITLE
New function wanted:The system environment variables that created in ci pipeline can automatically patched 

### ISSUE THREAD

**Issue by liangjsbfy** [kubernetes-sigs/kustomize#2588]
Example:
New build id environment variable will create in system when I run ci pipeline.I want to add this env in deployment (or service ,statefulsets etc)  labels or annotation.Here only one way is that set new env name (like BUILD_ID) in k8s yaml file and  replace it by "envsubst".This is troublesome and not elegant!

I wanted new function like Vars in kustomize ,but more extension.

**Comment by Shell32-Natsu** [comment]
https://github.com/kubernetes-sigs/kustomize/issues/1113. Maybe this is helpful.
