### ISSUE TITLE
Preserving comments and other human-readable syntax in output yaml

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/kustomize#259]
(I think this is out of scope, but please confirm.)

I'm using kustomize to systemically generate bunch of human readable templates.

So I have patches like:

```yaml
spec:
  # specify how many replicas you want here
  replicas: 3
```

that **has comments for humans**.

I have patches like the following that has **syntax making it explicit that it's string**, like:

```yaml
spec:
  loadBalancerIP: "TYPE.YOUR.IP.HERE"
```

When I do `kustomize build`:
- I lose YAML comments 
- I lose the `"` marks around the strings
- kustomize "shuffles" the YAML field orders

which makes me think `kustomize` isn't designed for machine-readable output and not for humans.

-----
 
I'm opening this issue since I'm not familiar with YAML parsing/patching code of kustomize. If it's more like a GNU patch, I suppose preserving comments could work, but it's more like deserialize/patch/serialize, comments would be lost.

/kind feature

**Comment by Liujingfang1** [comment]
As explained in #261, Kustomize doesn't preserve arbitrary comments. This is out of scope of kustomize, but a perfect feature request similar to https://github.com/go-yaml/yaml/issues/132 in yaml parsing library. 
Kustomize is not a template based either. If you just start to set up your application, you can avoid templating by using Kustomize. All the resources should be declarative and able to be piped to `kubectl apply -f`

**Comment by zhouhaibing089** [comment]
The issue go-yaml/yaml#132 you mentioned appears to be resolved and supported in yaml.v3 package.
