### ISSUE TITLE
Docs links potentially broken?

### ISSUE THREAD

**Issue by max-sixty** [kubernetes-sigs/kustomize#2591]
1. The link ` kubernetes-sigs.githubpages.io/kustomize` at https://github.com/kubernetes-sigs/kustomize/tree/master/docs
...links to: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kubernetes-sigs.githubpages.io/kustomize
...which is a 404.

2. The link `Core Docs` at https://kustomize.io/, and `Docs` from the readme of this repo
...link to https://github.com/kubernetes-sigs/kustomize/tree/master/docs
...which is potentially the file listing of a webserver?
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/5635139/84452726-6fe33380-ac0b-11ea-8b02-2cebbc8747f7.png">

**Comment by sunny0826** [comment]
Use docsy site for kustomize docs  #2576, move en docs to https://kubernetes-sigs.github.io/kustomize/

But it didn't work.

![image](https://user-images.githubusercontent.com/24563928/84462251-188fa280-aca1-11ea-843b-fbfb0414681f.png)

**Comment by sunny0826** [comment]
why closed this issue?

**Comment by monopole** [comment]
It was autoclosed by the PR, but clearly there are still lots of links to fix.
