### ISSUE TITLE
Kustomize Plugins Signature Mismatch

### ISSUE THREAD

**Issue by mvpmvh** [kubernetes-sigs/kustomize#2598]
The [go plugin documentation](https://kubernetes-sigs.github.io/kustomize/guides/plugins/#go-plugins) states that kustomize plugins must have a `plugin` type that has a method with the following signature:

`func (p *plugin) Config(   ldr ifc.Loader,   rf *resmap.Factory,   c []byte) error`

but then proceeds to list [examples](https://kubernetes-sigs.github.io/kustomize/guides/plugins/#examples-1) with the following signature:

`func (p *plugin) Config(h *resmap.PluginHelpers, c []byte) error`.

Is this a mistake?

**Comment by Shell32-Natsu** [comment]
The examples are correct

**Comment by Shell32-Natsu** [comment]
Fixed in https://github.com/kubernetes-sigs/kustomize/pull/2603
