### ISSUE TITLE
Incorrect example: `multibases` uses `resources` instead of `bases`

### ISSUE THREAD

**Issue by devin-fee-ah** [kubernetes-sigs/kustomize#2602]
I **think** this is a bug. I was having problems with `kubectl` applying `kustomize` changes, and ended up figuring out that `resources` should be `bases` in the following places:

https://github.com/kubernetes-sigs/kustomize/blob/a0072a2cf92bf5399565e84c621e1e7c5c1f1094/examples/multibases/kustomization.yaml#L1-L4

https://github.com/kubernetes-sigs/kustomize/blob/a0072a2cf92bf5399565e84c621e1e7c5c1f1094/examples/multibases/dev/kustomization.yaml#L1-L2

https://github.com/kubernetes-sigs/kustomize/blob/a0072a2cf92bf5399565e84c621e1e7c5c1f1094/examples/multibases/production/kustomization.yaml#L1-L2

https://github.com/kubernetes-sigs/kustomize/blob/a0072a2cf92bf5399565e84c621e1e7c5c1f1094/examples/multibases/staging/kustomization.yaml#L1-L2

based on the documentation here: https://kubectl.docs.kubernetes.io/pages/app_customization/bases_and_variants.html

**Comment by monopole** [comment]
`bases:` is deprecated in the 3.x series.

`resources:` does everything bases did.
