### ISSUE TITLE
Error: no matches for OriginalId on 

### ISSUE THREAD

**Issue by DenisVoloshin** [kubernetes-sigs/kustomize#2607]
I'm facing the following problem
Using 

kustomize version 
{Version:3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-28T01:07:36+01:00 GoOs:darwin GoArch:amd64}

Want to try out the sample kustomize/examples/springboot/ project

1. When I run kustomize build  overlays/production/
The getting 

`Error: accumulating resources: accumulateFile "accumulating resources from '../../base': '/Users/denisvoloshin/IdeaProjects/temp/kustomize/examples/springboot/base' must resolve to a file", accumulateDirector: "couldn't make target for path '/Users/denisvoloshin/IdeaProjects/temp/kustomize/examples/springboot/base': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/Users/denisvoloshin/IdeaProjects/temp/kustomize/examples/springboot/base'"`

looking at another project I assumed the kustomization.yaml is missed on the base folder, once I add it there
```
resources:
 - deployment.yaml
 - service.yaml
```

I got the following error

 ```
kustomize build  overlays/production/
Error: no matches for OriginalId ~G_v1_ConfigMap|~X|demo-configmap; no matches for CurrentId ~G_v1_ConfigMap|~X|demo-configmap; failed to find unique target for patch ~G_v1_ConfigMap|demo-configmap
```

The same error I'm getting on my custom project when try to build simple mutlibase config.

pls let me know if the sample project is out-of-date and what I'm ,missing in the config

**Comment by TomaszKlosinski** [comment]
I have similar error for my own manifests and I get different results with `kustomize build` command and different with `kubectl kustomize`:

```
⎈ kustomize build manifests/
Error: no matches for OriginalId apps_v1_Deployment|~X|weave-scope-app; no matches for CurrentId apps_v1_Deployment|~X|weave-scope-app; failed to find unique target for patch apps_v1_Deployment|weave-scope-app

⎈ kubectl kustomize manifests | head
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cloud.weave.works/version: v1.0.0-279-g7a5fd2f
  name: weave
---
apiVersion: v1
kind: ServiceAccount
metadata:
```

**Comment by nnz1024** [comment]
Same issue with version
```{Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:linux GoArch:amd64}```

**Comment by dvaldivia** [comment]
I also have the same problem, I think that target including `~X` in the attempted id is what could be causing the problem

I feel like `~G_v1_Service|~X|operator` is not the same as `~G_v1_Service|operator` right?

```
Error: no matches for OriginalId ~G_v1_Service|~X|operator; no matches for CurrentId ~G_v1_Service|~X|operator; failed to find unique target for patch ~G_v1_Service|operator
```

**Comment by nnz1024** [comment]
@dvaldivia You right, `~X` means "no namespace" https://github.com/kubernetes-sigs/kustomize/blob/bbb046081be615cb425a68bae1debef15b50f621/api/resid/resid.go#L42
Try to add `namespace:` field into `target:` block, it fixes the problem for me.

**Comment by blaggacao** [comment]
See also: https://github.com/kubernetes-sigs/kustomize/issues/1351
