### ISSUE TITLE
Git cloner assumes that "master" is the default branch

### ISSUE THREAD

**Issue by dsyer** [kubernetes-sigs/kustomize#2614]
It's a convention that might be changing, and it's only a convention anyway. It would be safer to use "HEAD" as a default in [cloner.go](https://github.com/kubernetes-sigs/kustomize/blob/8576acf1aa9438dc5527900650bbd975391aab9e/api/internal/git/cloner.go#L31) - that already works so it's a simple change that would have no impact on most users (only people who have a "master" branch that isn't the default "HEAD" will be affected, and they probably don't realize it's even broken).

**Comment by pwittrock** [comment]
Sounds reasonable.  I think GitHub is making some similar changes -- do you happen to know what that entails?  Perhaps we could follow their lead if it makes sense to do so.

**Comment by dsyer** [comment]
I heard about GitHub maybe changing the name of the default branch for new projects. This is broader in scope because kustomize has to work with existing repositories, whatever their default branch. Simply changing one line in cloned.go from a hard coded “master” to “HEAD” would work for all repositories, past, present and future. At least that seems to be the case to me when I’ve tried it on the command line (using `?ref=HEAD` explicitly).

**Comment by Shell32-Natsu** [comment]
go-getter is used before Kustomize's own cloner. I am not sure how does go-getter treat this. If we only change the our cloner's behavior it may have mismatch with go-getter.

**Comment by dsyer** [comment]
Seems to me to be worth keeping open?

**Comment by dsyer** [comment]
Bump

**Comment by Shell32-Natsu** [comment]
We should be able to handle an arbitrary mater/main branch. New repo on github will use main after Oct 1st 2020. https://github.com/github/renaming

/assign

**Comment by Shell32-Natsu** [comment]
> I heard about GitHub maybe changing the name of the default branch for new projects. This is broader in scope because kustomize has to work with existing repositories, whatever their default branch. Simply changing one line in cloner.go from a hard coded “master” to “HEAD” would work for all repositories, past, present and future. At least that seems to be the case to me when I’ve tried it on the command line (using `?ref=HEAD` explicitly).

`git clone` will automatically checkout `HEAD` after cloning. So what we should do is remove hardcoded `master` and only checkout another branch when `ref` is present.
