### ISSUE TITLE
Consolidate release process for modules in this repo

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#2615]
Mods to [releasing](https://github.com/kubernetes-sigs/kustomize/tree/master/releasing)
 
 - delete VERSIONS file
 - delete the bash script releasemodule.sh (assuming it hasn't changed in a while)
 - modify README.md to explain use of the new release
  i've been doing stuff like
  ```
  (cd releasing/releasing; go run . list)
  (cd releasing/releasing; go run . release kyaml patch)
  ```
 - README should have up to date explanations of all modules

just noticed getting strange errors in `list` output:
```
~/gopath/src/sigs.k8s.io/kustomize $ (cd releasing/releasing; go run . list)
2020/06/18 10:25:49 FATAL exit status 1 From github.com:kubernetes-sigs/kustomize
 ! [rejected]          kustomize/v3.2.1  -> kustomize/v3.2.1  (would clobber existing tag)
 ! [rejected]          kustomize/v3.6.0  -> kustomize/v3.6.0  (would clobber existing tag)
 ! [rejected]          pluginator/v1.1.0 -> pluginator/v1.1.0  (would clobber existing tag)
exit status 1

```
The list command should never have errors

**Comment by monopole** [comment]
@Shell32-Natsu @mortent

**Comment by monopole** [comment]
also, likely related, the `api` module isn't  showing up in list output
all go.mod files should be found and examined for tags

**Comment by Shell32-Natsu** [comment]
For the error, it looks like you have local tags and they have conflicts with remote tags. I will update the program to forcibly update local tags.

**Comment by Shell32-Natsu** [comment]
It's strange that `api` is not shown. What's the output of the list?

**Comment by Shell32-Natsu** [comment]
Should we delete the detail instructions on this [page](https://github.com/kubernetes-sigs/kustomize/blob/master/releasing/README.md)? I think it'a good document for what does releasing program do.

**Comment by mortent** [comment]
I think it is find to explain what actually happens when we run the program. We should just make it clear what are the steps the user should take to make a release and what are just helpful explanations.
