### ISSUE TITLE
Kustomize seems to still require additional configs for CRDs even if no transformations are required

### ISSUE THREAD

**Issue by jcmcken** [kubernetes-sigs/kustomize#2619]
When I add a CRD as a resource into my ``kustomization.yaml`` that I don't want kustomize to touch, but which I want deployed into the cluster, it seems that I still have to provide either the CRD schema or CRD transformations for the resource.

This doesn't really make any intuitive sense and seems rather pointless. If I don't define any transformations for a resource but I include it, ``kustomize`` should simply pass it through instead of removing it from the results. I don't want Kustomize to be the arbiter of what is or isn't a proper resource, that's the Kubernetes cluster's job. It makes ``kustomize`` brittle to changes in resource schemas and requires a lot of redundant configurations that serve zero purpose.

**Comment by jcmcken** [comment]
> 
> 
> When I add a CRD as a resource into my `kustomization.yaml` that I don't want kustomize to touch, but which I want deployed into the cluster, it seems that I still have to provide either the CRD schema or CRD transformations for the resource.
> 
> This doesn't really make any intuitive sense and seems rather pointless. If I don't define any transformations for a resource but I include it, `kustomize` should simply pass it through instead of removing it from the results. I don't want Kustomize to be the arbiter of what is or isn't a proper resource, that's the Kubernetes cluster's job. It makes `kustomize` brittle to changes in resource schemas and requires a lot of redundant configurations that serve zero purpose.

I think I found the problem. ``kustomize`` is silently removing CRDs with names containing the word ``List``. Kubernetes allows such resources (even if a list of the resource ends up looking strange, "FooListList"), but Kustomize silently gets rid of them.

**Comment by Shell32-Natsu** [comment]
@jcassee `*List` resources will be extracted from the list and be processed as a list of resources in kustomize.
