### ISSUE TITLE
Question: Support of cmdline arguments for exec-based Kpt-functions

### ISSUE THREAD

**Issue by aodinokov** [kubernetes-sigs/kustomize#2621]
I noticed that fn exec filter has an ability to keep command arguments in addition to command path[1]. But `ExecSpec` structure [2] doesn't have ability to run commands with arguments.

I found the commit that actually removes that functionality [3]. I looked through the PR [4] and wasn't able to find the exact reason why it was done.
The only guess was that the original intention for exec-based functions was - to be able to run binaries copied from docker-image locally to save time during debugging (it's much faster to run binary than build/run image), and I guess the idea was that typically those binaries don't have args.
But some binaries that run in images still can have a bit longer entry-points than just path - they may have arguments.
I was thinking about couple of additional use-cases where this feature would be usefull:
some simple functions may be done by running kustomize itself with some additional arguments, e.g. annotate, merge (probably the whole `config` subtree would suite perfectly) . That is instead of creating images.
I understand the potential risk of running executables, but since we already have that flag that allows the used to explicitly enable exec-functions, probably it would be good to return back the feature with arguments.

Question:
**What was the reason to remove exec.args? can we enable them back?**

PS
if we can:
to enable them back it's just possible to revert lines I mentioned in [3].
Another alternative is to use shlex [5] to split commandline stored in path into actual path and args.
(I guess it would be preferable to rename path in that case to cmdline, but not sure it's possible, since the interface is already defined)

[1]
https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/fn/runtime/exec/exec.go#L20
[2]
https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/fn/runtime/runtimeutil/functiontypes.go#L41
[3]
https://github.com/kubernetes-sigs/kustomize/commit/dab0f3cf2276653455ff3dcfdc7626c94164010d#diff-381ed7975274b4d58b528cc388c9f262L43

https://github.com/kubernetes-sigs/kustomize/commit/dab0f3cf2276653455ff3dcfdc7626c94164010d#diff-e07a50718371004dc2235f9638ea10d0R387
and
https://github.com/kubernetes-sigs/kustomize/commit/dab0f3cf2276653455ff3dcfdc7626c94164010d#diff-eb545950fd3de955aa3a013983b96189L167
[4]
https://github.com/kubernetes-sigs/kustomize/pull/2436

[5]
https://godoc.org/github.com/google/shlex

**Comment by aodinokov** [comment]
one more idea:
I was playing with RunFns object - it's simple and nice object, but there can be a potential drawback:
Kpt-functions currently support 3 types of functions: container, exec and starlark.
and RunFns has a dedicated fields in this type.
but the implementation of the function is a filter-function that is run for every resource in pipe.

it may look as an over-complication at this point, but I think it would be great to have some ability make container, exec and starlark as 'modules' for runfns and when I run it, it would be nice to be able to specify if I want it to use only container module, or all 3, or may be I would like to define my own filter and be able to define my own module. e.g.
my example with kustomize itself as a filter:
annotation: |
  kustomize:
    args: config annotate -kv foo=bar

or even
annotation: |
  kustomize:
     args: live ....
to be able to apply it.
Looks similar to ansible isn't it? :)
Instead of os.exec that filter could get the root of cobra cmd object and do:
`                    rootCmd := KustomizeRootCmd()`
`                    rootCmd.SetArgs(shlex.Split(filter.args))`
`                    rootCmd.Execute()`
Since kubeconfig can't be accessible from container-based kpt function, this is a potentially possible way to describe the whole pipeline almost without bash... btw `kustomize build <dir>` can be also put into list of functions.
That would allow us instead of building long pipelines in bash to build reapatable pipelines from separate functions and run them just like this:

`kustomize build <dir> | kustomize fn run --fn-path <dir>/pipeline`
or even
`kustomize fn run --fn-path <pipeline>`

**Comment by Shell32-Natsu** [comment]
I am not aware of the motivation of removing exec args. However, a function should not use command line args. They should read from stdin and use the args in functionConfig field.

**Comment by aodinokov** [comment]
Thank you @Shell32-Natsu. I asked because I wanted to run kustmomize from kpt. Was thinking to run it locally since it was 'known' binary. But 7/1 kustomize_build [1] function was added :) I'm good now 👍 I'm closing this

[1]
https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/functions/ts/src/kustomize_build.ts
