### ISSUE TITLE
Docs links still broken?

### ISSUE THREAD

**Issue by max-sixty** [kubernetes-sigs/kustomize#2628]
Not sure why https://github.com/kubernetes-sigs/kustomize/issues/2591 was closed: the docs links still seem to be broken?

Repeating:

1. The link ` kubernetes-sigs.githubpages.io/kustomize` at https://github.com/kubernetes-sigs/kustomize/tree/master/docs
...links to: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kubernetes-sigs.githubpages.io/kustomize
...which is a 404.

2. The link `Core Docs` at https://kustomize.io/, and `Docs` from the readme of this repo
...link to https://github.com/kubernetes-sigs/kustomize/tree/master/docs
...which is potentially the file listing of a webserver?
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/5635139/84452726-6fe33380-ac0b-11ea-8b02-2cebbc8747f7.png">

**Comment by monopole** [comment]
Please move this comment to #2591 so we don't have a dupe, thanks!
