### ISSUE TITLE
Allow `kustomize edit set label` (currently unsupported)

### ISSUE THREAD

**Issue by bittner** [kubernetes-sigs/kustomize#2631]
I understand from the CLI usage screens that the `edit` command supports adding and removing `commonLabels` in `kustomization.yaml`. However, it's not possible to set a `commonLabel`, which might be equivalent to:

- adding a `commonLabel` if it doesn't exist, or
- overwriting the corresponding `commonLabel`'s value if it already exists.

In theory, it would be possible to simply remove the `commonLabel` and add the new value, but the `remove` command fails when the related `commonLabel` key is not yet present.

### Proposed Solution

There should be a `kustomize edit set label` command that behaves similar to:

1. `kustomize edit remove label <key>`
1. `kustomize edit add label <key>:<value>`

... with the sole difference that the removal should never fail, or not be attempted if the corresponding `commonLabel` key is not yet present.

**Comment by bittner** [comment]
I found a warning in the [Kustomize docs](https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/commonlabels/) that may be related:

> Changing commonLabels to live resources could result in failures.

Our case is different: We have a `commonLabel` in the base configuration that we need to adapt in one of the overlays, namely the one that deploys review apps. All resource names get a suffix appended to allow them live in the same namespace. For the labels we try to implement the same approach, but updating a label is not yet possible.

**Comment by inceptio-jingzhao** [comment]
what about to use "kustomize edit add label xxx" instead?

**Comment by natasha41575** [comment]
I am looking into adding `kustomize edit set label` but you can also silence errors when the label isn't present with the -i option, as in `kustomize edit remove label -i {labelkey,labelvalue}

**Comment by natasha41575** [comment]
The functionality has been added to kustomize in the master branch and will be available in the next release

@monopole @Shell32-Natsu this issue can be closed
