### ISSUE TITLE
kustest: looks for Go plugin, even when set-up to run an exec plugin.

### ISSUE THREAD

**Issue by smyrman** [kubernetes-sigs/kustomize#2632]
While converting tests from Go plugins to Exec plugins, I discovered that `kustest` `HarnessEnchanced` appear to expect a Go plugin,  even when the harness is set-up to test an exec plugin. I am not sure why, but I guess it must fail around here:

https://github.com/kubernetes-sigs/kustomize/blob/346071897efa392a36e43919b3c62382ba2ca929/api/internal/plugins/loader/loader.go#L108

---

Here is a  generalized version of our test code, hopefully useful for reproduction:

```go
// file located in <repo>/ksutomize-plugin/example.com/v1beta1/myplugin
package main_test

func TestMyPlugin(t *testing.T) {
	teardown := setup(t) // builds MyPlugin binary in source folder.
	defer teardown()

	th := kusttest_test.MakeEnhancedHarness(t).
		PrepExecPlugin("example.com", "v1beta1", "MyPlugin")
	defer th.Reset()

	t.Run("With foo", func(t *testing.T) {
		m := th.LoadAndRunGenerator(fooInput)
		th.AssertActualEqualsExpected(m, fooExpect)
	})
}
```
The Go source-code for the exec plugin is located in the same folder.

Expecting test to pass, instead we are seeing:
```
--- FAIL: TestMyPlugin (1.15s)
    harnessenhanced.go:113: Err: expected file with Go object code at: /Users/username/.local/src/sigs.k8s.io/kustomize/plugin/example.com/v1beta1/myplugin/MyPlugin.so
    --- FAIL: TestMyPlugin/With_foo (0.00s)
        testing.go:916: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
FAIL
FAIL   github.com/org/repo/kustomize-plugin/exampl.com/v1beta1/myplugin	1.752s
FAIL
```

PS! The plugin is tested to work as expected when installed and used through `kustomize`.

**Comment by Shell32-Natsu** [comment]
Is your binary file executable after setup?

**Comment by smyrman** [comment]
Yes, it's executable.

**Comment by smyrman** [comment]
Will it always the executable from the location of the test file? Or could it be expecting a different path?

**Comment by Shell32-Natsu** [comment]
From your error output, kustomize tried to load exec plugin  `/Users/username/.local/src/sigs.k8s.io/kustomize/plugin/example.com/v1beta1/myplugin/MyPlugin`. You can use `XDG_CONFIG_HOME` or `KUSTOMIZE_PLUGIN_HOME` to specify the search path for Kustomize. See <https://kubernetes-sigs.github.io/kustomize/guides/plugins/execpluginguidedexample/>

**Comment by smyrman** [comment]
`/Users/username/.local` comes from `GOPATH=Users/username/.local` The sub-path`src/sigs.k8s.io/kustomize/plugin` is as far as I can tell, a path set-up by the test-harness, and has nothing to do with the _installation path_ which is set-up and works correctly based on `XDG_CONFIG_HOME`.

I could install the plugin to this path, but I don't see that it's being done in the example tests:
- https://kubernetes-sigs.github.io/kustomize/guides/plugins/#examples
- https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go

I would though any executable in the same folder would be _moved_ to the test folder in `GOPATH`? If it's relevant in _finding- the executable next to the source, the plugin (and executable) are not located in a separate go module; the go-module is at the repository root.

**Comment by smyrman** [comment]
Updated previous comment. In conclusion, I guess it would be useful to update the example test code in a way so that they work for code not located inside the `kustomize` repo.

**Comment by smyrman** [comment]
Tested to initalize a go module in the `ksutomize-plugin/example.com/v1beta1/myplugin` just to see if it was relevant. No change in result. Same error (still looks for `$GOPATH/src/sigs.k8s.io/kustomize/plugin/example.com/v1beta1/myplugin/MyPlugin.so`)

**Comment by Shell32-Natsu** [comment]
Kustomize will search for plugin in a special path: `$XDG_CONFIG_HOME/kustomize/plugin/${apiVersion}/LOWERCASE(${kind})`. For your test, is your `XDG_CONFIG_HOME` set to `/Users/username/.local/src/sigs.k8s.io`? You also need to update the `XDG_CONFIG_HOME` for your *test* as well. https://kubernetes-sigs.github.io/kustomize/guides/plugins/#placement

**Comment by smyrman** [comment]
`XDG_CONFIG_HOME` is set to `"/Users/username/.config"`; and the Plugin _is installed_ correctly according to the mentioned restrictions (although the test _itseld_ don't install it, and I can't see the example tests doing that). Anyway `kustomize build` _does find and run it correctly_; it's only the test Harness (`th`) that does not.

If I manually set `XDG_CONFIG_HOME` before setting up the test harness, this has _no effect_.

```go
func TestMyPLugin(t *testing.T) {
	os.Setenv("XDG_CONFIG_HOME", "/Users/username/.config")

	teardown := setup(t)
	defer teardown()

	th := kusttest_test.MakeEnhancedHarness(t).
		PrepExecPlugin("example.com", "v1beta1", "MyPlugin")
	defer th.Reset()
	...
}
```
Running the test reports the _same_ issue (looking in GOPATH for an .so file):
```
harnessenhanced.go:113: Err: expected file with Go object code at: /Users/username/.local/src/sigs.k8s.io/kustomize/plugin/example.com/v1beta1/myplugin/MyPlugin.so
```

**Comment by smyrman** [comment]
I made a reproduction repo at: https://github.com/smyrman/kustest-issues-2632

Here is a walk-through reproduction test:

```txt
$ go test ./example.com/v1beta1/myplugin/
--- FAIL: TestMyPlugin (0.48s)
    harnessenhanced.go:113: Err: expected file with Go object code at: /Users/smyrman/.local/src/sigs.k8s.io/kustomize/plugin/example.com/v1beta1/myplugin/MyPlugin.so
    --- FAIL: TestMyPlugin/With_foo (0.00s)
        testing.go:916: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
FAIL
FAIL	github.com/smyrman/kustest-issues-2632/example.com/v1beta1/myplugin	1.117s
FAIL
go test ./example.com/v1beta1/myplugin/  4.71s user 1.76s system 137% cpu 4.699 total
$ ls -l ./example.com/v1beta1/myplugin/
total 6576
-rwxr-xr-x  1 smyrman  staff  3357544 Jun 27 23:30 MyPlugin
-rw-r--r--  1 smyrman  staff     2014 Jun 27 23:23 MyPlugin.go
-rw-r--r--  1 smyrman  staff     1098 Jun 27 23:23 MyPlugin_test.go
$ mkdir -p ${XDG_CONFIG_HOME}/kustomize/plugin/example.com/v1beta1/myplugin
$ cp example.com/v1beta1/myplugin/MyPlugin ${XDG_CONFIG_HOME}/kustomize/plugin/example.com/v1beta1/myplugin
$ kustomize build --enable_alpha_plugins kustomization
apiVersion: v1
data:
  username: whatever
kind: ConfigMap
metadata:
  name: example-configmap-test
$ echo ${XDG_CONFIG_HOME}
/Users/smyrman/.config
$ go test ./example.com/v1beta1/myplugin/
--- FAIL: TestMyPlugin (0.22s)
    harnessenhanced.go:113: Err: expected file with Go object code at: /Users/smyrman/.local/src/sigs.k8s.io/kustomize/plugin/example.com/v1beta1/myplugin/MyPlugin.so
    --- FAIL: TestMyPlugin/With_foo (0.00s)
        testing.go:916: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
FAIL
FAIL	github.com/smyrman/kustest-issues-2632/example.com/v1beta1/myplugin	0.659s
FAIL
go test ./example.com/v1beta1/myplugin/  4.42s user 1.69s system 146% cpu 4.187 total
```
Again, my gopath is set in a "non-standard" way:

```txt
$ echo ${GOPATH}
/Users/smyrman/.local
```

The test don't _currently_ include a override for `XDG_CONFIG_HOME`, but that should be inherited by the environment. Notice when we run the test a second time (after having installed the plugin), it still looks for an so file in the kustomize source code only.

**Comment by smyrman** [comment]
https://github.com/kubernetes-sigs/kustomize/blob/5b1edcdd0e06fe256f634e891bd8a542347f0973/api/internal/plugins/utils/utils.go#L26

**Comment by smyrman** [comment]
Solved it. In reproduction repo:
```txt
$ mkdir plugin
$ mv example.com plugin/.
```

I didn't realize the `plugin` folder was needed for the source-code of the plugin. As this was never necesary for the Go plugins (`.so`).

**Comment by smyrman** [comment]
I also guess it never searched my local home directory, because it finds a plugin folder with `"old style $GOPATH"` first:
```
			{
				Note: "old style $GOPATH",
				F: func() string {
					return filepath.Join(
						os.Getenv("GOPATH"),
						"src", konfig.DomainName,
						konfig.ProgramName, konfig.RelPluginHome)
				},
			},
			{
				Note: "HOME with literal 'gopath'",
				F: func() string {
					return filepath.Join(
						konfig.HomeDir(), "gopath",
						"src", konfig.DomainName,
						konfig.ProgramName, konfig.RelPluginHome)
				},
			},
```

**Comment by Shell32-Natsu** [comment]
In the list which you found

https://github.com/kubernetes-sigs/kustomize/blob/441581b74521972209ffb02c2f6ddcfe1fea6d4c/api/internal/plugins/utils/utils.go#L22

the first exist dir will be used.
