### ISSUE TITLE
Any reason this isnt tracking the latest kustomize versions?

### ISSUE THREAD

**Issue by Kampe** [kubernetes-sigs/kustomize#2643]
Kustomize v2.x.x has many issues, bugs and features to be desired, is there any reason this isn't being updated?  Downstream kubectl isn't getting any updates.

**Comment by Shell32-Natsu** [comment]
There are some technical reasons that block updating kustomize version in kubectl. The most significant one is the dependence on apimachinery module.

We are working on addressing these issues.

**Comment by Shell32-Natsu** [comment]
Please see #1500 and #2506
