### ISSUE TITLE
Design proposal: Setters without comments

### ISSUE THREAD

**Issue by phanimarupaka** [kubernetes-sigs/kustomize#2649]
Here is the design proposal for implementing setters without inline comments.

https://docs.google.com/document/d/1Ve9fE_mGnkGpQnW0PXGj1Pbc6fiS9Kw--A7oabAqwSs/edit?usp=sharing

**Comment by phanimarupaka** [comment]
@pwittrock @frankfarzan  @mortent @monopole

**Comment by pwittrock** [comment]
What is the motivation for this?

**Comment by pwittrock** [comment]
Left some comments on the doc.

**Comment by Shell32-Natsu** [comment]
@phanimarupaka Can we close this issue?
