### ISSUE TITLE
Kustomize Plugins - Go plugins Caveats link is busted

### ISSUE THREAD

**Issue by jmhodges** [kubernetes-sigs/kustomize#2662]
The link on https://kubernetes-sigs.github.io/kustomize/guides/plugins/ to Go plugin caveats (at https://kubernetes-sigs.github.io/kustomize/guides/plugins/goPluginCaveats.md ) but that page is blank. Not sure where it's supposed to go.

**Comment by jmhodges** [comment]
Oh the one at the bottom of the page works! But the one in the text doesn't.

**Comment by monopole** [comment]
https://kubernetes-sigs.github.io/kustomize/guides/plugins/goplugincaveats/

please fix
