### ISSUE TITLE
Support multiple entries in KUSTOMIZE_PLUGIN_HOME

### ISSUE THREAD

**Issue by james-callahan** [kubernetes-sigs/kustomize#2684]
I'd like to have kustomize look in a few locations for plugins, e.g.
  - `/usr/local/lib/kustomize/plugins`
  - `/usr/lib/kustomize/plugins`
  - `/usr/local/share/kustomize/plugins`
  - `/usr/share/kustomize/plugins`

Can we allow `KUSTOMIZE_PLUGIN_HOME` to be a colon separated list of locations? (similar to the classic unix PATH variable)

**Comment by james-callahan** [comment]
.

**Comment by james-callahan** [comment]
@ChaturvediSulabh are you working on this?

**Comment by ChaturvediSulabh** [comment]
yes, #3791 is pending review
cc: @KnVerey @monopole
