### ISSUE TITLE
Difference between patches and patchesJson6902

### ISSUE THREAD

**Issue by mtsmfm** [kubernetes-sigs/kustomize#2705]
Here's the demo https://github.com/mtsmfm/kustomize-patches-difference-demo

`$ kustomize build patchesJson6902` gets resources patch but `$ kustomize build patches` doesn't.
Is this intentional?

It seems `patches` assumes name as regexp but `patchesJson6902` doesn't.

```
$ kustomize version
{Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}

$ kustomize build patchesJson6902
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
      - image: ${DOCKER_IMAGE}
        name: ${SERVICE_NAME}
        resources:
          requests:
            cpu: 1m
            memory: 1Mi

$ kustomize build patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
      - image: ${DOCKER_IMAGE}
        name: ${SERVICE_NAME}
```

**Comment by monopole** [comment]
The `patchJson6902` directive (an older keyword) accepts a list of 
 - `target` (Gvk, Namespace, Name)
   It must match exactly one resource.  No wildcards.
 - `path` (to a file containing the patch) or `patch` (a patch directly included in the kustomization file).
   The patch must parse as a JSON6902 patch.
The target must match exactly one resources.

rendered doc: https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/patchesjson6902/
source: https://github.com/kubernetes-sigs/kustomize/blob/master/site/content/en/api-reference/kustomization/patchesjson6902/_index.md



The `patch` directive is newer and accepts a list of 
 - `target` (Gvk, Namespace, Name, AnnotationSelector, LabelSelector)
   Namespace and Name can be regex.
   It can match more than one resource; all will be patched using the given patch.
 - `Path` (to a file containing the patch) or `Patch` (a patch directly included in the kustomization file).
If the patch doesn't parse correctly as a JSON6902 patch, it's attempted as a Strategic Merge Patch.
  
rendered doc: https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/patches/
source: https://github.com/kubernetes-sigs/kustomize/blob/master/site/content/en/api-reference/kustomization/patches/_index.md

Can someone write a PR to improve the documentation?

**Comment by monopole** [comment]
@etefera

**Comment by Shell32-Natsu** [comment]
Please file a new doc issue for this. @monopole @etefera
