### ISSUE TITLE
can we use Kustomize to manage all my Yaml file ?

### ISSUE THREAD

**Issue by cloudengineers** [kubernetes-sigs/kustomize#2710]
Hi All, 
We have containerized our application functionality into 30 applications (I mean 30 Kubernetes Pods)
For every application I have 1 single yaml file with service/deployment
I have total 30 Yaml files, can I use Kustomize to manage all this Yaml file?
Please Note: I am new to kustomize, any suggestions much appreciated 
Thank you

**Comment by monopole** [comment]
Please do so and write about it somewhere :)

30 deployments isn't a problem in terms of YAML editing.  

Kustomize is means to make it easy to describe variants of your deployments - describe some reference set of workloads, then describe variations of that for different environments and purposes.

**Comment by cloudengineers** [comment]
Thank you @monopole,

i am using Kustomize for my YAML editing
