### ISSUE TITLE
Kustomize: Istio installation error

### ISSUE THREAD

**Issue by Pradeepadtricon** [kubernetes-sigs/kustomize#2712]
[istio.zip](https://github.com/kubernetes-sigs/kustomize/files/4916607/istio.zip)

├── base
│   ├── kustomization.yaml
│   └── istio.yaml
└── Dev
 |          └── kustomization.yaml
├── Prod
       |── kustomization.yaml

Attached the yaml for reference.
[istio.zip](https://github.com/kubernetes-sigs/kustomize/files/4916610/istio.zip)

This is my Kustomise folder structure, i have kept the istio in base. base.kustomisation yaml has istio.yaml reference. 

When i try to build in dev or prod  ( kustomise build . ) I get the below error

this is giving below error -
webhooks.clientConfig.service ignored in mutation attempt

When i remove the istio.yaml file it kustomise build works fine.

**Comment by Shell32-Natsu** [comment]
Cannot reproduce. Please provide more details like the kustomize version and kustomization file content.

/label triage/not-reproducible

**Comment by Shell32-Natsu** [comment]
Feel free to reopen if you still have the issue.

/close
