### ISSUE TITLE
Delete setters v1 code and branching logic

### ISSUE THREAD

**Issue by phanimarupaka** [kubernetes-sigs/kustomize#2719]
Check if any one is using V1 setters. 
Delete [setters V1](https://github.com/kubernetes-sigs/kustomize/tree/master/kyaml/setters) folder and clean-up [branching logic](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/internal/commands/cmdset.go#L63). 

Setters V1 was very old and there are no tests in the current repo to protect them. Current version is still backwards in theory, the legacy code and branching logic exists but in reality, I checked that V1 setters are not working apparently(since past 5 releases/>2 months). We see no issues filed regarding the support of V1. I feel it is safe to delete the V1 setters folder and branching logic in cmd/config. Let me know your thoughts.

@frankfarzan @mortent @pwittrock @monopole

**Comment by mortent** [comment]
Turns out the old setters are being used: https://github.com/GoogleContainerTools/kpt/issues/831

**Comment by Shell32-Natsu** [comment]
@phanimarupaka Can we close this issue?
