### ISSUE TITLE
Directorie and file can not be complete automaticlly with tab.

### ISSUE THREAD

**Issue by hanyouqing** [kubernetes-sigs/kustomize#2729]
Here is my directory tree:

```
/project/
├── apps
│   ├── base
│   ├── production
│   ├── staging
│   └── testing
├── cluster
│   ├── base
│   ├── production
│   └── staging
```

many of my usecase is run `kustomize build apps/testing/appname | kubectl -f -` in project root directory. 

```
/path/to/my/project $ kustomize build apps/testing/appname | kubectl -f -
```

when I press `tab` after `kustomize build` directoris name is expected, but now it doesn't work even I've installed completion for kustomize by `echo yes | kustomize install-completion`

Environment:
```
$ kustomize version
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-17T14:23:17+00:00 GoOs:darwin GoArch:amd64}

$ uname -a
Darwin Youqings-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Wed May 27 17:00:02 PDT 2020; root:xnu-4570.71.80.1~1/RELEASE_X86_64 x86_64
```

Thanks!

**Comment by Shell32-Natsu** [comment]
Which kind of shell are you using? I tried with bash and latest kustomize version and what I saw is kustomize will try to auto-complete the flags for build. Is this what you see?
