### ISSUE TITLE
Revisit validation package pkg/validate

### ISSUE THREAD

**Issue by guineveresaenger** [kubernetes-sigs/kustomize#273]
As per [discussion while adding edit add label/annotation](https://github.com/kubernetes-sigs/kustomize/pull/147#discussion_r211325317), a validation package for input to match syntax was added.

This package currently has rudimentary placeholder validation. Ultimately, it should reflect api-machinery standards (pending agreement/discussion).

@monopole any additional thoughts/input?

**Comment by monopole** [comment]
nope.  fine with apimachinery
