### ISSUE TITLE
add "-f" option to be able to set path to kustomization.yaml

### ISSUE THREAD

**Issue by monotek** [kubernetes-sigs/kustomize#2736]
I'm new to kustomize and i want to kustomize several files with the same change / additon.

It seems to me that i have to create a kustomize.yaml with the exact same content in every directory i want to change the files in.

"kustomize help" did not show any option to use the commnad like:
```
kustomize build . -f /path/to/kustomization.yaml
```

Is there a reason that this is not possible?
Did i missed something?

If not, would you consider to add such option?

**Comment by monotek** [comment]
Not stale. Still interested in such function.

**Comment by Shell32-Natsu** [comment]
@monopole Is there any blocker to this feature?

**Comment by monotek** [comment]
Not stale

**Comment by KnVerey** [comment]
We discussed this at the Kustomize bug scrub today and decided not to accept this feature. Kustomize expects the entire tree of required files to exist at or below the root Kustomization itself, which is behaviour we want to preserve for both security and encapsulation reasons.

/close
