### ISSUE TITLE
No merging of created namespaces within bases

### ISSUE THREAD

**Issue by beilber** [kubernetes-sigs/kustomize#2747]
While cleaning up my cluster setup process I ran into a situation where I have two bases that each create the same namespace.  For reference this is `fluxcd/flux` and `fluxcd/helm-operator`.   When I run my `kustomize build`  I get the following error (redacted):
```
accumulateDirector: \"recursed merging from path '/xxxxxx/base/helm-operator/deploy': may not add resource with an already registered id: ~G_v1_Namespace|~X|flux\""
```

I originally was defining the bases with the git url but for testing I cloned the two repos and checked out the tag I intended to use.  No difference there.

Here is an abridged tree of my flux directory.  Just to point out the relevant parts.
```
.
├── base
│   ├── flux
│   │   ├── deploy
│   │   │   ├── flux-account.yaml
│   │   │   ├── flux-deployment.yaml
│   │   │   ├── flux-ns.yaml
│   │   │   ├── flux-secret.yaml
│   │   │   ├── kustomization.yaml
│   │   │   ├── memcache-dep.yaml
│   │   │   └── memcache-svc.yaml
│   ├── helm-operator
│   │   ├── deploy
│   │   │   ├── crds.yaml
│   │   │   ├── deployment.yaml
│   │   │   ├── kustomization.yaml
│   │   │   ├── namespace.yaml
│   │   │   ├── rbac.yaml
│   │   │   └── weave-cloud-deployment.yaml
├── install
    └── kustomization.yaml
```
I am testing with `kustomize build install/`

install/kustomization.yaml:
```
bases:
  - ../base/flux/deploy
  - ../base/helm-operator/deploy
```

The two identical namespace yamls in question are here:

https://github.com/fluxcd/flux/blob/v1.18.0/deploy/flux-ns.yaml

https://github.com/fluxcd/helm-operator/blob/v1.1.0/deploy/namespace.yaml

```
kustomize version
{Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:linux GoArch:amd64}
```

I have more I want to do here such as patches and other bases but I simplified the kustomize bits as much as I could to track down the issue and reduce the clutter.

I would expect that kustomize would be able to merge the namespace creation of both bases rather than the resulting error.

**Comment by beilber** [comment]
Just found the same issue here: https://github.com/fluxcd/flux/issues/2988

**Comment by Shell32-Natsu** [comment]
@monopole Should we allow namespace with same name be merged without error? Or we should allow any other kinds in addition to namespace.

**Comment by monopole** [comment]
This reduces to
```
cat <<EOF >kustomization.yaml
resources:
- ns1.yaml
- ns2.yaml
EOF

cat <<EOF >ns1.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: flux
EOF

cat <<EOF >ns2.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: flux
EOF

kustomize build .
```

This results in the error
```
Error: accumulating resources: accumulateFile "merging resources from 'ns2.yaml': may not add resource with an already registered id: ~G_v1_Namespace|~X|flux",
```

kustomize wants all input resources to be uniquely identified by `apiVersion`, `kind` and `metadata/name` fields (just as a cluster would).

Although kustomize allows one to _explicitly_ merge a patch (which can look like a resource) into a resource via `patch` directives that specify , this never happens _implicitly_ to fully formed resources in the input set whose names happen to match.

**Comment by monopole** [comment]
Implciltly merging like-named resources could theoretically be feature, but 
1) it would serve to hide a new class of bugs
2) it would need a convincing use case (where it solved a problem that had no other easy solution).

Closing this as WAI, please reopen with more details if you'd like more discussion

**Comment by beilber** [comment]
I am not going to reopen since you make valid points.

In the mentioned use case there are other solutions, such as tracking the two as local bases in the kustomize repo modified to not individually create the same namespace resource but rather creating the namespace at the same level we source the bases.

This does show the most value in cases where you source a base with git, where you have the "authentic" source that you may not have control over ( ie. a base of: github.com/fluxcd/flux//deploy?ref=v1.20.1 )  This appeals to me from the perspective of keeping the kustomize tidy and consistent.  However this is not a make or break situation, more a "nice to have"

Just thinking of all the base crawl and divergence it could 'potentially' prevent, is still just a "nice to have" versus what I would consider a convincing use case.
