### ISSUE TITLE
error out on invalid GVK patch target

### ISSUE THREAD

**Issue by blaggacao** [kubernetes-sigs/kustomize#2760]
```yml
patches:
- patch: |-
    - op: add
      path: /spec/template/containers[0]/env/FOO
      value: bar
  target:
    group: apps
    version: v1
    kind: Devployment    # typo
    name: baz
```

**_Shouldn't such patch error out? (because of the GVK typo)_**

This typo-ed resource is not even known to k8s.

```console
$ kustomize version
Version: {Version:3.3.1 GitCommit:f2ac5a2d0df13c047fb20cbc12ef1a3b41ce2dad BuildDate:unknown GoOs:linux GoArch:amd64}
```

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:46:15Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Shell32-Natsu** [comment]
Kustomize only checks wether the GVK can be found in resources. It doesn't check whether the input GVK is valid in k8s api. A typo kind means the target will never be found.

**Comment by blaggacao** [comment]
> the target will never be found

Maybe that circumstance can be alerted?

**Comment by Shell32-Natsu** [comment]
Target not found can have multiple different reasons. If we generate alerts for all of them then the output will be very noisy.

**Comment by blaggacao** [comment]
> multiple different reasons or even expected

Jm, I didn't consider this possibility and wasn't able to infer one. To me it seemed (and still seems) strange UX. After all the case at hand is a simple typo. What's the root cause we cannot differentiate a typo from expected "not founds"? Some missing typing somewhere?

**Comment by Shell32-Natsu** [comment]
For example, a target not found can be caused by

 - typo in the target definition
 - target resource is not in the resource file (for some reason, maybe deleted)
 - someone forgets to add the resource file to resources file list
 - a patch is used by multiple kustomization files and not all of them have target resource

It's also possible that someone copies and pastes the GVK so the wrong GVK *can* be found in resources although it's not valid.

You may also notice that kustomize doesn't generate almost any alerts or warning since kustomize should generate a valid yaml output or an error message.

**Comment by blaggacao** [comment]
I see, the first three points are unintentional, so I don't see a problem helping to maintain consistent state (in line with `kustomize`'s declarative approach).

The fourth point is questionable, since there is one stance of kustomize which promotes that all resources are under the same folder subtree. I havn't checked if this is only true for resources, but it makes equally sense for patches as well. Therefore a resources which is not present is indeed a configuration mistake. For reusability concerns, I heard that components are in the making hich should transparently lift away this concern.

> You may also notice that kustomize doesn't generate almost any alerts or warning since kustomize should generate a valid yaml output or an error message.

It does error out, though if the resource is found but the patch itself fails to apply.

So from this discussion I would reaffirm the noteworthiness of the issues. - For consistency's sake.

**Comment by blaggacao** [comment]
I wonder even more, since kustomize _does_ have notion of kubernetes schemata (at least for regular transformers's patching rules).

Else `kustomize` could also be called "`json-patcher` with plugins" - and even such patcher probably would error out if a patch target isn't found (see also behaviour of `patch`).

**Comment by andrascz** [comment]
Is there any chance reopening this?
I would second @blaggacao as we hit this via a simple resource rename, where target was not updated accordingly.
