### ISSUE TITLE
Automated per-module release notes

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#2773]
[release process]: https://github.com/kubernetes-sigs/kustomize/blob/master/releasing/README.md
[release notes]: https://github.com/kubernetes-sigs/kustomize/releases

The [release process] uses [`goreleaser`](https://goreleaser.com/) to generate the commit descriptions found in the [release notes].

The problem is that range of commits described in the notes spans only the two most recently applied tags, regardless of what those tags represent.

Since the tags are module specific, we get poor release notes, e.g. if we release `kyaml`, and follow this with a release `cmd/config`, the release of `cmd/config` will only include the commits since the `kyaml` release - likely only one or two commits.

We want a release of module `foo` to list all the commits to that module since the last release of `foo`, disregarding intervening releases of other modules.

As an optimization to this, that commit list would _omit_ listing commits that did not include files inside the `foo` module's directory tree.

**Comment by monopole** [comment]
FYI  @etefera

**Comment by monopole** [comment]
@runewake2

**Comment by runewake2** [comment]
Is #3072 related to this work?

**Comment by monopole** [comment]
yes, in the sense that generating the release notes for a particular module could be created during a run of `gorepomod release {module}`.  

I think it would be more useful for everyone if the release notes we're actually created and stored in-repo as a markdown file as a last PR before tagging the release.
That way we'd inspect them and (optionally) hand-modify them beforehand, and we could keep them as _repo_ artifacts instead of as _github_ artifacts.

We used to do that, see https://kubernetes-sigs.github.io/kustomize/blog/releases/

**Comment by runewake2** [comment]
If we're intending to change how we show or display release notes it might be good to collaborate with other projects like kubernetes-sigs/kubebuilder and kubernetes-sigs/kpt that are currently releasing their notes in a similar style. Converting to markdown files would be useful for embedding release notes on sites as well. Would patch, minor and major releases be documented differently?

We should decide if converting the format of release notes is in scope for this task though, that will grow the effort required.  Maybe worth spinning this conversation into a separate issue to avoid confusion and scope creep here.

**Comment by monopole** [comment]
the kustomize repo ships several modules; until there's only one (which might never happen, or happen many months from now), would like something hacked up that worked.

by markdown release notes, we mean just something like

 - [Title of pr](link to PR)
 - [Title of pr](link to PR)
 - etc.

nothing fancier, with pr's bound by the tags, and by the modules they changed.

The latter restriction would be eased by #2774 

i really like kubeflow's overall scheme (emoji defining the nature of the PR) but that's  more complicated (depends on Solly's bash scripts).  I'm not sure, but last i checked (some time ago) they were only shipping the kubebuilder binary, so teasing apart release notes for different modules wasn't an issue.
