### ISSUE TITLE
kustomize edit doesn't respect components field deleting it from kustomization file

### ISSUE THREAD

**Issue by vugardzhamalov** [kubernetes-sigs/kustomize#2775]
Greetings,

Not sure if  this will be in line with earlier reported issue #2310

Unfortunately 'kustomize edit' doesn't respect 'components:' field - this will end up simply deleted.

Example:
`kustomize edit set namesuffix foobar`

Current kustomize version:
`kustomize version
{Version:kustomize/v3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T00:58:46Z GoOs:linux GoArch:amd64}`

**Comment by Shell32-Natsu** [comment]
Can you provide an example of you kustomization file?

**Comment by vugardzhamalov** [comment]
Hi @Shell32-Natsu I've attached an example file (please don't forget to rename since attachments not supported in YAML):


[kustomization.txt](https://github.com/kubernetes-sigs/kustomize/files/5080620/kustomization.txt)

**Comment by Shell32-Natsu** [comment]
I cannot reproduce the issue with latest master branch (bc37ec9d88e92fe16fce241a2f9864601241d612). 

```
❯ cat kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - '../../../../../bases/fancy-base/'


nameSuffix: 'fancy-suffix'


namespace: 'fancy-namespace'


components:
  - '../../../../../components/fancy-component/'

❯ kustomize edit set namesuffix foobar

❯ cat kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../../../../bases/fancy-base/


nameSuffix: foobar


namespace: fancy-namespace


components:
- ../../../../../components/fancy-component/
```

**Comment by monopole** [comment]
confirmed w/ manual test. 

@vugardzhamalov would love to have regression coverage for this
if you have the time to contribute a test like, for example
kustomize/internal/commands/edit/set/setimage_test.go
or any of the tests in that directory
