### ISSUE TITLE
kustomize 3.8.1 removes newlines

### ISSUE THREAD

**Issue by aceeric** [kubernetes-sigs/kustomize#2779]
Here's the use case

1. Get https://download.elastic.co/downloads/eck/1.2.0/all-in-one.yaml - which has hard-coded namespaces
2. Goal is to do testing in different namespaces: create a namespace, create multiple operators, create multiple resources, integrate, test, tear down namespace, repeat
3. So build a kustomization that patches the hard-coded ECK namespace
4. kustomize build . > all-in-one-sanity-check.yaml
5. Expectation: 12 occurrences of "elastic-system" changed to "test-namespace"
6. Actual:
```
$ diff all-in-one.yaml all-in-one-sanity-check.yaml | wc -l
1831
```
Visual sanity check is impossible because kustomize removed all the newlines from the source when it generated the patch output. Is that intentional? It makes verification of the patches difficult. Ideally, it would only modify what it has been been explicitly told to modify. Or - is there a recommended other way to QA the patch?

**Comment by Shell32-Natsu** [comment]
The string style used in the `all-in-one.yaml` is *single-quoted flow scalar*. In this style, this new line character `\n` will be **ignored** when it's being parsed. If you want to keep newline, change them to use *literal block scalars*, which means adding a `|` before the strings.

Here is the string style that kustomize generates:
```
❯ cat string-style-test.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: string-style
data:
  block: |
    This
    is
    multiline string
  single-quote: 'This is a
    single line'
  double-quote: "This is a single
    line as well"

❯ kustomize build .
apiVersion: v1
data:
  block: |
    This
    is
    multiline string
  double-quote: This is a single line as well
  single-quote: This is a single line
kind: ConfigMap
metadata:
  name: string-style
```

For different yaml string styles, see https://yaml-multiline.info/ and https://stackoverflow.com/a/21699210/3317502.

**Comment by aceeric** [comment]
Thanks. Consider that I'm in the integrator role, consuming a yaml from an external vendor. This kustomize behavior puts me in the position of having to potentially pre-process a vendor's yaml to prepare it for kustomize. (Or, as I'm presently doing, spend more time initially evaluating the kustomize output to convince myself that I didn't make a mistake or there were no unintended patches.) IMO a better solution would be for kustomize to support the use case. I'm sure the underlying yaml parser could make this difficult because it is likely removing the newlines. So - I'm not offering a solution. Some ideas are: don't manipulate `description` fields? Don't manipulate _anything_ that hasn't been explicitly configured for patching? (Meaning if it's not patched, then that source yaml flows through untouched.)

**Comment by Shell32-Natsu** [comment]
The string style is clearly defined in the YAML standard so there is no problem in kustomize's behavior and it's *expected*. The source YAML file use single quote means the newline is not important in the string. If you want to validate the output of kustomize I will suggest you to use a tool which can parse YAML instead of using plain text diff.

**Comment by aceeric** [comment]
I'll offer one more consideration: in many cases the CRD YAML - including the description fields under discussion - is auto-generated by the _operator-sdk_ from comments and annotations in Go code: `operator-sdk generate crds`. In this scenario - the operator-sdk will quote - or not quote - the YAML as it sees fit according to its own rules. So I don't think it's entirely accurate to say "single quote means the newline is not important" since the Go code author is only providing source code documentation and annotations.

Integrators are working with machine-generated YAML and trying to manipulate it with kustomize. Kustomize is then performing a patch in a way that makes it difficult for integrators to validate their results. Since kustomize was the last entity that touched the YAML, it's not unreasonable that kustomize could do this in a way that recognizes it is working with machine-generated YAML in which the single ticks might have been introduced by the CRD generator with no corresponding intent by the author regarding the semantics of newlines. If none of this is convincing then please feel free to close the ticket.

**Comment by Shell32-Natsu** [comment]
Yes it's not accurate to say "not important" but at least they can be safely ignored. I will still suggest to use a tool which can understand yaml to do validation instead of using plain text diff or human eyes.
