### ISSUE TITLE
Krmfile with .yaml extension

### ISSUE THREAD

**Issue by kferrone** [kubernetes-sigs/kustomize#2786]
Can the Krmfile please allow the `.yaml` extension.

**Comment by kferrone** [comment]
I guess it's something with this file would change: https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/ext/ext.go

**Comment by Shell32-Natsu** [comment]
Which command do you want to support .yaml extension?

**Comment by kferrone** [comment]
`kustomize cfg` and all of it's subcommands use the krmfile
