### ISSUE TITLE
Create different name fields

### ISSUE THREAD

**Issue by MichaelJDrK** [kubernetes-sigs/kustomize#2788]
I'm evaluating Kustomize for our declarative Kubernetes resource definitions (=pile of YAMLs with a lot of repetition).

Now I see, that I can customize some resource definitions with a given name, e.g. I can create hundreds of "wordpress" deployments using name prefixes and suffixes. With that I avoid repetition between different stages of the same applications.

But in a real production environment, you have tons of different microservices. Each service has the same ceremonial YAML (service, deployment, pdb - maybe a secret). 
So I need to use one single set of base files and kustomize them per microservice / stage (different namespace, different image, different name and maybe some specific tweaks for that particular service). But this simple task doesn't be possible, since I HAVE to use the same name for every resource. 

Prefixing / Suffixing doesn't work, the names might have nothing in common.

Am I missing something?

**Comment by Shell32-Natsu** [comment]
Sorry I don't get the point. You said you *HAVE to use the same name for every resource* but at the same time *the names might have nothing in common*?
