### ISSUE TITLE
Different results with `kustomize build` and `kubectl kustomize`

### ISSUE THREAD

**Issue by TomaszKlosinski** [kubernetes-sigs/kustomize#2791]
Hi, I've downloaded the manifest for Weave Scope from their official website, and I made some changes in an overlay to make it read-only and adjust it for my cluster. The weird thing is that I get different results with `kustomize build` command and different with `kubectl kustomize`:

```
⎈ kustomize build manifests/
Error: no matches for OriginalId apps_v1_Deployment|~X|weave-scope-app; no matches for CurrentId apps_v1_Deployment|~X|weave-scope-app; failed to find unique target for patch apps_v1_Deployment|weave-scope-app

⎈ kubectl kustomize manifests | head
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cloud.weave.works/version: v1.0.0-279-g7a5fd2f
  name: weave
---
apiVersion: v1
kind: ServiceAccount
metadata:
```

Versions:
```
⎈ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}

⎈ kustomize version
{Version:3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T05:15:32+01:00 GoOs:darwin GoArch:amd64}
```

_Originally posted by @TomaszKlosinski in https://github.com/kubernetes-sigs/kustomize/issues/2607#issuecomment-666979067_

**Comment by webwurst** [comment]
When you use `kustomize` in version `v2.0.3` the results should be the same, see: [kubectl-integration](https://github.com/kubernetes-sigs/kustomize#kubectl-integration). Not sure, but I think also newer versions of `kubectl` stick with that `kustomize` version.

Kustomize `v3` introduced breaking changes and had new features added and so output might differ.
