### ISSUE TITLE
patchesJson6902

### ISSUE THREAD

**Issue by blaggacao** [kubernetes-sigs/kustomize#2793]
It should be clarified easily discoverabl which is the order of application of kustomize directives

for example, if I add a `/spec/serviceName` field to a `StatefulSet` and I have a `nameSuffix` `-foo` for the present leaf rendering, then do I need to specify the `serviceName` value pre- or post- appication of the name suffix.

**Comment by Shell32-Natsu** [comment]
You should be able to use both original `serviceName` and updated `serviceName`.

We have a [page](https://kubernetes-sigs.github.io/kustomize/contributing/howitworks/) about the order of kustomize transformers.
