### ISSUE TITLE
Kustomize should error if image transformer name is not used in any resources

### ISSUE THREAD

**Issue by chancez** [kubernetes-sigs/kustomize#2798]
We've had a few cases in CI where either due to a mistake, or change in an upstream base caused the image transformer to no longer match the image being used in the source manifest. This means that the image transformer silently reverts to using what's defined in the original manifest.

In my ideal world, it would error instead, but I could also see a `--strict` mode or something to that end.

**Comment by Shell32-Natsu** [comment]
Could you try to use a [validator plugin](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/validatorPlugin.md) to achieve the goal?
