### ISSUE TITLE
"failed to find unique target for patch" error on kustomization that kubectl handles

### ISSUE THREAD

**Issue by metasim** [kubernetes-sigs/kustomize#2806]
If you run this:
```
$ kubectl apply -k github.com/Yolean/kubernetes-kafka/variants/scale-1-ephemeral/?ref=v6.0.3 --server-dry-run
```
You get <details><summary>successful results</summary>
<pre>
role.rbac.authorization.k8s.io/pod-labler created (server dry run)
clusterrole.rbac.authorization.k8s.io/node-reader created (server dry run)
rolebinding.rbac.authorization.k8s.io/kafka-pod-labler created (server dry run)
clusterrolebinding.rbac.authorization.k8s.io/kafka-node-reader created (server dry run)
configmap/broker-config created (server dry run)
configmap/zookeeper-config created (server dry run)
service/bootstrap created (server dry run)
service/broker created (server dry run)
service/pzoo created (server dry run)
service/zookeeper created (server dry run)
service/zoo created (server dry run)
statefulset.apps/kafka created (server dry run)
statefulset.apps/pzoo created (server dry run)
statefulset.apps/zoo created (server dry run)
</pre>
</details>

However, if you try the same with `kustomize`
```
kustomize build github.com/Yolean/kubernetes-kafka/variants/scale-1-ephemeral/?ref=v6.0.3
```

You get
<details><summary>An error</summary>
<pre>
Error: accumulating resources: accumulateFile "accumulating resources from '../scale-1': '/private/var/folders/lr/7lb0jzbj1x951n71lpcc2cy40000gn/T/kustomize-226177435/variants/scale-1' must resolve to a file", accumulateDirector: "recursed accumulation of path '/private/var/folders/lr/7lb0jzbj1x951n71lpcc2cy40000gn/T/kustomize-226177435/variants/scale-1': no matches for OriginalId apps_v1_StatefulSet|~X|kafka; no matches for CurrentId apps_v1_StatefulSet|~X|kafka; failed to find unique target for patch apps_v1_StatefulSet|kafka"
</pre>
</details>

Is there some way of getting `kustomize` to handle the same set of specification files? Or is it not intended to be compatible with `kubectl` compatible files?

## Versions

```
$ kustomize version
{Version:3.8.1 GitCommit:0b359d0ef0272e6545eda0e99aacd63aef99c4d0 BuildDate:2020-07-16T05:11:04+01:00 GoOs:darwin GoArch:amd64}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Shell32-Natsu** [comment]
https://github.com/Yolean/kubernetes-kafka/blob/ed0844c7f9fcfccd84764ae6330fabba14b3659c/variants/scale-1/kustomization.yaml#L13

Add a `namespace: kafka` to the target.

**Comment by kanolato** [comment]
You can also make it work it with:
`kubectl kustomize github.com/Yolean/kubernetes-kafka/variants/scale-1-ephemeral/?ref=v6.0.3`
I'm unsure about why it doesn't work with kustomize directly
