### ISSUE TITLE
Binaries not available on release page

### ISSUE THREAD

**Issue by frankfarzan** [kubernetes-sigs/kustomize#2823]
Per [1]: "Download a binary from the release page"

The release page only includes source as assets not prebuilt libraries:

https://github.com/kubernetes-sigs/kustomize/releases

[1]: https://github.com/kubernetes-sigs/kustomize

**Comment by monopole** [comment]
You have to scroll down to  kustomize/v3.8.1.  The release page is autogenerated, so newer "releases" of libraries push down the kustomize binary.

**Comment by monopole** [comment]
Maybe file an issue to improve the doc?

**Comment by frankfarzan** [comment]
Scrolling down multiple pages below the fold to find release binaries is a bad UX. Can we just repurpose this to improve this? Changing docs is one way to alleviate this.
