### ISSUE TITLE
Component emptyDir is not getting merged properly

### ISSUE THREAD

**Issue by sachrajneesh** [kubernetes-sigs/kustomize#2834]
If our bases Deployment or Component overlay Deployment has volume like following
    volumes:
      - name: vol1
        emptyDir: {}
      - name: vol2
        emptyDir: {}        

When we are suing Component in final kustomization like following

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - '../../component'   
resources: 
  - '../../bases'
patchesStrategicMerge:
- overlay.yaml

And do Kustomize build 
emptyDir: {} is getting dropped in the merge, out put has only volume name without emptyDir like following.
    volumes:
      - name: vol1
      - name: vol2

**Comment by aabouzaid** [comment]
This issue happened also with me.
And it's a bit critical because it will mess up `patchesJson6902` patches because it relies on the order of the objects.

Kustomize version: 3.8.0, 3.8.1

**Comment by kierankelleher** [comment]
Same issue here. Tried to migrate from the built-in kubctl version of kustomize to 3.8.1. This blocker bug was the only issue we found so far.

**Comment by sachrajneesh** [comment]
Moderator, could you please assign this to someone?

**Comment by Shell32-Natsu** [comment]
I can't make a reproduce on my side. Could you provide the content in the `overlays.yaml`? It will be better to provide as much information as possible for me to reproduce the issue.

**Comment by Shell32-Natsu** [comment]
Since haven't heard from you for a month, close this issue. Feel free to reopen.

/close
