### ISSUE TITLE
CALL Kustomize API inside a GO project

### ISSUE THREAD

**Issue by JiyeYu** [kubernetes-sigs/kustomize#2844]
Hi there,

Is there any way to directly call kustomize's API inside a GO project to generate yaml manifest?

Seems currently the only way to execute Kustomize is type kustomize command in shell?

**Comment by monopole** [comment]
Do it the way kustomize does it

https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/internal/commands/build/build.go#L140

See the imports in that file - it's all you need
