### ISSUE TITLE
No version specified in the documentation

### ISSUE THREAD

**Issue by Josh-a-e** [kubernetes-sigs/kustomize#2846]
It would be really useful to be able to see what version of kustomize the docs are referring to.

**Comment by monopole** [comment]
The docs are in great need of improvement - but the intention is that they are consistent with the latest version

the version you install by following https://kubernetes-sigs.github.io/kustomize/installation/binaries/

**Comment by Shell32-Natsu** [comment]
Please file a doc issue if you find that the doc is inconsistent with latest version. We are happy to fix.
