### ISSUE TITLE
Feature / Windows Package Manager: Chocolatey exists, Can add Scoop too? 

### ISSUE THREAD

**Issue by GrooveCS** [kubernetes-sigs/kustomize#2849]
### Add Scoop Windows package manager to the installation page

- [GitHub: Kubernetes-sigs / Kustomize: Installation Page](https://github.com/kubernetes-sigs/kustomize/edit/master/site/content/en/installation/_index.md)
- [GitHub: Kubernetes-sigs / Kustomize: Chocolatey Page](https://github.com/kubernetes-sigs/kustomize/edit/master/site/content/en/installation/chocolatey/_index.md)

Propose the following

1.  Rename the tile of the page to Windows Installation
2.  Add instructions, examples, and resources to use Scoop
3. Leave page URL as chocolatey or create a redirect to updated URL

The related pages

- [Installation | Kustomize](https://kubernetes-sigs.github.io/kustomize/installation/)
- [Chocolatey | Kustomize](https://kubernetes-sigs.github.io/kustomize/installation/chocolatey/
)

**Comment by Shell32-Natsu** [comment]
We don't have enough resources to do this and we are not fully supported windows yet. We appreciate it if some one can take this.
