### ISSUE TITLE
Complete WNode implementation

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#2893]
In service of #2506, which will permit completion of #1500 

The methods to implement are here:
https://github.com/kubernetes-sigs/kustomize/tree/master/api/internal/wrappy/wnode.go

For details / rationale, see
https://github.com/kubernetes-sigs/kustomize/blob/master/api/krusty/internal/provider/depprovider.go

The other half of this is #2894

It's desirable to try to _reduce the WNode interface_ to reduce the implementation work.  Please file new issues if we can identify deprecations that reduce the number of methods in the WNode interface.

**Comment by Shell32-Natsu** [comment]
@monopole I think this has been finished?

**Comment by monopole** [comment]
Yes, quite some time ago.
