### ISSUE TITLE
kustomize changing the yaml formatting

### ISSUE THREAD

**Issue by lswith** [kubernetes-sigs/kustomize#291]
I've been using a specific yaml format for the kustomization.yaml files. It seems though that when I run the command `kustomize edit set imagetag <imagetag>` the file is reformatted. This is annoying when using gitops as its hard to see what's changed.

**Comment by Liujingfang1** [comment]
What version of kustomize are you using? In v1.0.6, we added the feature of preserving the comments and orders in kustomization.yaml when `edit` is called.

**Comment by Liujingfang1** [comment]
@lswith Do you still see this problem with the new version?

**Comment by lswith** [comment]
yep its working fine!

**Comment by gabegorelick** [comment]
Comments and the order of top-level elements in kustomization.yaml seem to be preserved when running something like `kustomize edit set image`, but kustomize (as of v3.8.5) still reformats the file. For example it will change indentation and alphabetize properties under `configMapGenerator`, `images`, etc.
