### ISSUE TITLE
Document status of (exec) plugins on Windows

### ISSUE THREAD

**Issue by jcassee** [kubernetes-sigs/kustomize#2924]
Not a Windows user myself, I build and release Windows versions for an exec plugin I maintain, which the Go compiler supports. However, a user recently told me that exec plugins are not supported on Windows:  goabout/kustomize-sopssecretgenerator#14. He pointed to [a short thread on Slack](https://kubernetes.slack.com/archives/C9A5ALABG/p1585924675198200).

I could not find any mention of the support for exec plugins on Windows in the documentation. If they are not supported, maybe add a notice? I can create a PR, but could be a one-liner in [plugins/_index.md](https://github.com/kubernetes-sigs/kustomize/blob/master/site/content/en/guides/plugins/_index.md).

If they are supported, we could use some help in goabout/kustomize-sopssecretgenerator#14. :smile:

**Comment by Shell32-Natsu** [comment]
I am not a windows user, at least not a windows kustomize user, too. 😆 

But I guess the exec plugin should be able to work on windows.

https://github.com/kubernetes-sigs/kustomize/blob/8d543d8483cbe481d2f07dd0c03e29d07dc1132f/api/internal/plugins/execplugin/execplugin.go#L48-L57

Here is the code which checks whether an exec plugin is actually executable. I not sure how does Go library work on windows in this case, but your user may be able to do a quick experiment on their machine and see does Go consider the file not executable.

**Comment by gochist** [comment]
I ran the following code on windows:

```go
package main

import "os"

func main() {
	f, err := os.Stat("C:\\Users\\june.yi\\Downloads\\SopsSecretGenerator_1.3.1_windows_amd64.exe")

	if err == nil {
		println(f.Mode())
		println(f.Mode() & 0111 == 0000)
	}
}

```

And the result is:

```
438
true
```

**Comment by Shell32-Natsu** [comment]
`438==0666`, which means file information that golang gets says it's not runnable.

**Comment by gochist** [comment]
@Shell32-Natsu Right. I think the method of checking whether a file is executable in Windows should be a little different. As it is, no one can use the exec plugin on Windows.

**Comment by Shell32-Natsu** [comment]
kustomize, or even kubectl, is not fully tested on Windows. At least for now, we don't have enough resources and motivation to make everything work perfectly on Windows. Please try WSL or Docker on Windows.

/close

**Comment by gochist** [comment]
@Shell32-Natsu This issue is about specifying whether the plugin supports Windows or not in the documentation. What about closing the issue after it has been reflected in the documentation?
/reopen
