### ISSUE TITLE
secretGenerator: secretRef not getting updated in version 3.8.2

### ISSUE THREAD

**Issue by madhukar93** [kubernetes-sigs/kustomize#2933]
```
$ kustomize version

{Version:3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-08-29T19:15:49+01:00 GoOs:darwin GoArch:amd64}
```

simplifying my exact project, but retaining the structure - 

```
$ tree

.
├── base
│   ├── api.yaml
│   └── kustomization.yaml
└── staging
    ├── kustomization.yaml
    ├── patch.yaml
    └── staging.env
```

```
$ cat base/api.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api
  labels:
    app:  api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app:  api
    spec:
      containers:
      - name:  api
        image: api
        env:
        - name: REDIS_PROVIDER
          value: REDIS_URL
        envFrom:
          - secretRef:
              name: api-config
```

```
$ cat base/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test
resources:
  - api.yaml
```

```
$ cat staging/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base/
patchesStrategicMerge:
  - patch.yaml
secretGenerator:
- name: api-config
  envs:
    - staging.env

```

Secrets are getting generated and applied with the api-config-_hash_, but secretRef in the deployment isn't updating to it, it's staying api-config

> EDIT: issue seems to arise when `namespace` property is present in `base/kustomization.yaml`

**Comment by Shell32-Natsu** [comment]
I cannot reproduce this issue. But I suspect the problem is `patch.yaml` since you don't provide the content in it.

**Comment by madhukar93** [comment]
It just patches the image. `patch.yaml` looks something like -
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - name: api
        image: api:v1
```
Thanks for checking in, I'll try to debug further.

**Comment by madhukar93** [comment]
Further, commenting it from `staging/kustomization.yaml` does not have an affect either

**Comment by madhukar93** [comment]
Ah confirming that when `base/kustomization.yaml` has `namespace` property, this issue arises

**Comment by Shell32-Natsu** [comment]
That makes sense. The secret resource is created without namespace (or in default namespace) and the reference in another namespace will not be updated.

**Comment by madhukar93** [comment]
Since my current context was that particular namespace itself, the resources were all applied to the correct namespace, I didn't notice that for kustomize the secret and the workloads referencing them didn't live together.
Thanks for helping out @Shell32-Natsu, closing this issue.
