### ISSUE TITLE
Feature requiest: Support parallel cloning of git endpoints

### ISSUE THREAD

**Issue by flo-02-mu** [kubernetes-sigs/kustomize#2950]
When specifying git endpoints as resources, every repo is cloned sequentially. With a big amount of git resources the download of all resources takes a significant amount of time in relation to the processing of the resources.

(Optional) parallel download of the resources (ideally: nested, but first level would already be an improvent) would improve that overall "kustomize build" time.

Current example value: With 55 git endpoints specified as base resources our kustomize build takes between 1:10min and 2:30min (depending on the network connection).

**Comment by Shell32-Natsu** [comment]
kustomize's current implementation is not gathering all repos that are needed to clone and then clone it sequentially but sequentially parse each resource and do something, then clone, then do something else, then next resource. It's not a simple work to just make "git clone" parallel. It's a really attractive proposal to make kustomize running in parallel but it requires tons of works.

**Comment by flo-02-mu** [comment]
@Shell32-Natsu 
By replacing the accumulateResources(ra *accumulator.ResAccumulator, paths []string) (*accumulator.ResAccumulator, error) method with the following code:
```go
func (kt *KustTarget) accumulateResources(
	ra *accumulator.ResAccumulator, paths []string) (*accumulator.ResAccumulator, error) {

	ctx := context.Background()
	errs, ctx := errgroup.WithContext(ctx)
	maxParallelWorkers := 16
	maxWorkers := min(len(paths), maxParallelWorkers)
	sem := semaphore.NewWeighted(int64(maxWorkers))

	for _, path := range paths {

		if err := sem.Acquire(ctx, 1); err != nil {
			fmt.Printf("Failed to acquire semaphore inside: %v", err)
			break
		}

		path := path
		errs.Go(func() error {
			defer sem.Release(1)
			// try loading resource as file then as base (directory or git repository)
			if errF := kt.accumulateFile(ra, path); errF != nil {
				ldr, errL := kt.ldr.New(path)
				if errL != nil {
					return fmt.Errorf("accumulateFile %q, loader.New %q", errF, errL)
				}
				var errD error
				ra, errD = kt.accumulateDirectory(ra, ldr, false)
				if errD != nil {
					return fmt.Errorf("accumulateFile %q, accumulateDirector: %q", errF, errD)
				}
			}
			return nil
		})
	}

	if err := errs.Wait(); err != nil {
		return nil, err
	}
	return ra, nil
}
```
, the entire loading (including the git loading) is processed in parallel. The speedup is quite nice for a high number of kustomize resources. There are two issues / questions around this though:

1. I am not sure if this can _always_ be applied or if the parallel processing should be made optional. What would be the best place to specify this? a parameter to kustomize build?
2. The unit tests are expecting the resources in a certain order which might be different when loading the resources in parallel. If the parallel loading is optional, it could be disabled by default for all the existing tests.

**Comment by Shell32-Natsu** [comment]
1. We can make the parallel process as optional and alpha in the beginning and collect more opinions.
2. Sometimes the order doesn't matter, sometimes it does. If we could support parallel accumulating, we need to add special tests.

**Comment by flo-02-mu** [comment]
In the PR I got arround the testing issue by putting the default value of parallel accumulation to 1. This way the order remains as expected. Not sure if the way I added the flag is correct though.
