### ISSUE TITLE
patches - path or patch

### ISSUE THREAD

**Issue by nagromLobo** [kubernetes-sigs/kustomize#2963]
`path` and `patch` appear to be used interchangeably to refer to the patch definition, where `path` seems to be the most widely used. Are these two separate concepts? This documentation doesn't really define a `path` so I'm assuming they are synonymous?

https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/patches/

**Comment by Shell32-Natsu** [comment]
They are different. `patch` is a patch. `path` in that doc page has two meanings depends on where it is. 1) The path to a file which contains the `patch`. 2) The path to a field in the resources where you want to apply the patch.

**Comment by nagromLobo** [comment]
Ahh makes sense. Is the best way to add clarification to the documentation to open up a PR with suggested changes?

**Comment by Shell32-Natsu** [comment]
Feel free to create a PR. https://github.com/kubernetes-sigs/kustomize/blob/master/site/content/en/api-reference/kustomization/patches/_index.md. Document improvement are wlecome!
