### ISSUE TITLE
Cronjob images are not replaced properly in 3.8.*

### ISSUE THREAD

**Issue by jeffreykog** [kubernetes-sigs/kustomize#2968]
Hi, i have an issue with batch/v1/Cronjob image replacing. In the newer versions the image tag is not replaced, in at least 3.5.4 (previous version i have used) this did work as expected. Below is a script that can be used to reproduce this scenario in both versions:

    $ docker run -it --rm debian:latest
    $ apt-get update
    $ apt-get install curl
    $ cat <<EOF > cronjob.yaml
    apiVersion: batch/v1beta1
    kind: CronJob

    metadata:
      name: clearsessions

    spec:
      schedule: "* * * * *"
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: test
                  image: test-image
    EOF

    $ cat <<EOF > kustomization.yaml
    resources:
      - cronjob.yaml

    images:
      - name: test-image
        newName: replaced-test-image
        newTag: release-1
    EOF

    $ curl -L -o kustomize_v3.5.4_linux_amd64.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
    $ tar -xzf kustomize_v3.5.4_linux_amd64.tar.gz
    $ ./kustomize build .
        # apiVersion: batch/v1beta1
        # kind: CronJob
        # metadata:
        #   name: clearsessions
        # spec:
        #   jobTemplate:
        #     spec:
        #       template:
        #         spec:
        #           containers:
        #           - image: replaced-test-image:release-1  # <-- correct replaced image
        #             name: test
        #   schedule: '* * * * *'

    $ curl -L -o kustomize_v3.8.2_linux_amd64.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.8.2/kustomize_v3.8.2_linux_amd64.tar.gz
    $ tar -xzf kustomize_v3.8.2_linux_amd64.tar.gz
    $ ./kustomize build .
        # apiVersion: batch/v1beta1
        # kind: CronJob
        # metadata:
        #   name: clearsessions
        # spec:
        #   jobTemplate:
        #     spec:
        #       template:
        #         spec:
        #           containers:
        #           - image: test-image  # <-- image is not replaced
        #             name: test
        #   schedule: '* * * * *'

As far as the kubernetes yaml spec goes, there are no changes in the format. I assume this is a bug in Kustomize. Thanks in advance for looking at this.

**Comment by Shell32-Natsu** [comment]
/dup #2758 

The fix will be in 3.8.3
