### ISSUE TITLE
Error on load config file with regex path

### ISSUE THREAD

**Issue by khanhtc1202** [kubernetes-sigs/kustomize#297]
kustomization.yaml 
```
resources:
- ingress.yml
- ./frontend/*.yml
- ./bff/*.yml
```

Error:
```
Error: loadResMapFromBasesAndResources: SemiResources: loadResMapFromBasesAndResources:
 rawResources failed to read Resources: Load from path ./frontend/*.yml failed: 
open /......../env/kustomize/speranza/base/frontend/*.yml: no such file or directory
```

Using latest version of Kustomize (1.0.7), I caught the error with the above config, but the previous version (1.0.5) of Kustomize works fine with this. Does Kustomize not support regex path anymore?  If it's still a supported syntax, how to use regex path in config file.

**Comment by Liujingfang1** [comment]
Kustomize doesn't support regexp in `kustomization.yaml` any more. We explained the reason https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#globs-in-kustomization-files

Instead, you can use regex path in `add resource` subcommand.
`kustomize edit add resource ./frontend/*.yml ./bff/*.yml`
Then those files will be added to kustomization.yaml

**Comment by khanhtc1202** [comment]
Thanks for your supporting. I will close this issue. 😄
