### ISSUE TITLE
kustomize live -- no scope for Kustmize resource

### ISSUE THREAD

**Issue by blaggacao** [kubernetes-sigs/kustomize#2979]
`./kustomize live apply --stack-trace overlays/dev/` &mdash; `v3.8.2` binary

throws:

```console
Error: can't find scope for resource Kustomization.kustomize.config.k8s.io
[...]  # cmd usage docs
```

I suspect it's the server not the Kustomization resource, but I also couldn't find any instructions or documentation about this behaviour...

**Comment by Shell32-Natsu** [comment]
`live` command has been removed in #2976

**Comment by blaggacao** [comment]
ya, seems it wasn't functional. Thanks for letting me know!
