### ISSUE TITLE
Feature request: Add path if doesn't exist with JSON patch

### ISSUE THREAD

**Issue by Evilong** [kubernetes-sigs/kustomize#2986]
With version `v3.5.4` it is not possible to add a new path with patchesJson6902.

An use case would be to add an entire path in order to add environment variables to a previously defined resource.

Example:
A simple container that is able to run without any environment variables and that can be used as base.
Then depending on the deployed environment we might want to pass some environment variables on the overlay.

At the moment I found a "_hack_" by adding a placeholder environment variable in order to have the path created.

**Comment by Shell32-Natsu** [comment]
According to json patch [rfc](https://tools.ietf.org/html/rfc6902#section-4.1), `add` operation requires *the object itself or an array containing it does need to exist, and it remains an error for that not to be the case.* So you can add a field but have to make sure the parent object/array does exist.

**Comment by Shell32-Natsu** [comment]
I suspect is there a standard way to create a *path* with JSON patch.

**Comment by realshuting** [comment]
> I suspect is there a standard way to create a path with JSON patch.

How can this be done using Kustomize?

**Comment by ebuildy** [comment]
@realshuting not with ``patchesJson6902`` , but this is possible with ``patchesStrategicMerge``.
