### ISSUE TITLE
Releases being pulled?

### ISSUE THREAD

**Issue by matedge** [kubernetes-sigs/kustomize#2993]
Hi all, just wondering why two releases have been pulled. 

We saw the note about 3.4.0 --> 3.5.1. and started using 3.5.1, which has now also been pulled?

**Comment by Shell32-Natsu** [comment]
Do you mean the release on github?

**Comment by matedge** [comment]
@Shell32-Natsu Yes, I have just begun maintaining a project that makes a call to `https://api.github.com/repos/kubernetes-sigs/kustomize/releases` and on 3 seperate occasions, the version of Kustomize appears to have been removed (3.4.0, 3.5.1, 3.5.2).
I will be moving to store my own copies, but just wondered what is the reason or am I missing something. 
Thanks

**Comment by matedge** [comment]
I did manage to resolve this by updating the clients code to call the tag directly with `https://api.github.com/repos/kubernetes-sigs/kustomize/releases/tags/kustomize/v3.4.0` I would suggest they were not paginating the initial call.
