### ISSUE TITLE
Kubebuilder quick start tutorial does not work with last release 3.8.2 of kustomize and had to downgrade

### ISSUE THREAD

**Issue by madorodam** [kubernetes-sigs/kustomize#3005]
Hi,
Trying the quick start tutorial of kubebuilder https://book.kubebuilder.io/quick-start.html (with controller generation), this does not work with last release version of kustomize 3.8.2. I had to downgrade to 3.7.0 for make deploy to work.

The error is that the 'namePrefix: example-' is not prepended to the namespace name too in its creation.
With kustomize 3.7.0 the patched namespace has name:example-system while in 3.8.2 this is kept as name:system

**Comment by camilamacedo86** [comment]
See that Kubebuilder defines the specific supported version that should be used in the Makefile. Also, shows that the new behaviour was introduced see; https://github.com/kubernetes-sigs/kustomize/issues/235

IMO: We need in kubernetes-sigs/kubebuilder#1657 upgrade the version and change how it works in kb.
