### ISSUE TITLE
Adding documentation around custom declarations

### ISSUE THREAD

**Issue by noqcks** [kubernetes-sigs/kustomize#301]
Thank you for creating this project!

Is there any documentation around the list of kustomize terms like `commonLabels`? I couldn't seem to find any. 

The only place I see it referenced is in the glossary [here](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/glossary.md#kustomization)

**Comment by Liujingfang1** [comment]
@noqcks You can take a look at this example `kustomization.yaml` https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kustomization.yaml
It shows the format and explanation for every kustomize term.

**Comment by noqcks** [comment]
Yeah, I was just looking at it the file as you commented. Thanks! I still think it would be nice to make it more apparent where to find documentation about the custom declarations.

**Comment by Liujingfang1** [comment]
I see. Maybe we can add a list of terms in docs/README.md

**Comment by noqcks** [comment]
Is there documentation for `patchesStrategicMerge`? I don't see in `docs/kustomization.yaml`

Thanks!

**Comment by Liujingfang1** [comment]
We've added documentation for both `crds` and `patchesStrategicMerge`.
