### ISSUE TITLE
kustomize edit label transformer

### ISSUE THREAD

**Issue by aaaaahaaaaa** [kubernetes-sigs/kustomize#3020]
Hi. I'm using a `LabelTransformer` to overcome the behaviour of `LabelCommon` which is applying labels to selectors. However, I need to be able to dynamically set the value of labels (specifically the tag) in the transformer (e.g. via `kustomize edit`) whenever my CI pipeline is running. Using `kustomize edit add label` currently adds a `commonLabel` configuration which bypasses the transformer.

Is there any way to achieve that?

**Comment by Shell32-Natsu** [comment]
I don't know is there any method to dynamically set the label values in LabelTransformer. You can use common text process tool like `sed` or `awk` to pre-process the LabelTransfomer config. Or you can create you own [exec plugin](https://kubernetes-sigs.github.io/kustomize/guides/plugins/execpluginguidedexample/)/[Go plugin](https://kubernetes-sigs.github.io/kustomize/guides/plugins/goplugincaveats/).

@monopole Any suggestions?

**Comment by aaaaahaaaaa** [comment]
Yeah I realise I could search and replace the values with `sed` or `awk` but it's exactly what we're currently doing with standard k8s manifests and want to move away from. And in a way it seems to kinda defeat the purpose of tools like kustomize.

I also release the topic of the selectors being written by `LabelCommon` seems to have already been discussed in length already, but I have to say... it is super annoying.

**Comment by Shell32-Natsu** [comment]
You can also try the PatchTransformer.

**Comment by keidevs** [comment]
Is there any way to change the labels value of labeltransformer using kustomize edit or Kustomize command?

**Comment by Shell32-Natsu** [comment]
@keidevs Please check `kustomize edit set label`

**Comment by arttuperala** [comment]
@keidevs The answer is actually just "no".
