### ISSUE TITLE
Error: Multiple matches for rbac.authorization.k8s.io_v1_Role

### ISSUE THREAD

**Issue by tiwalter** [kubernetes-sigs/kustomize#3021]
# Issue 

After upgrading kustomize  from `v3.8.0` to `v3.8.4` , i get the error `multiple matches for rbac.authorization.k8s.io_v1_Role`.

__I use the following structure:__
- the `base` declares two "dummy" `Roles` in two separate subfolders (namespace specified in the `kustomization.yaml` of each subfolder).
- also the `overlay` has to separate subfolders, which refer to their corresponding base yamls containing the `Roles` mentioned above.

-> We create a "dummy" `Role` for each namespace with different role configurations.

__The following error occurs when running `kustomize build`:__

`Error ... at path 'roleRef/name': multiple matches for rbac.authorization.k8s.io_v1_Role|~X|dummy:
  [rbac.authorization.k8s.io_v1_Role|namespace-1|dummy
 rbac.authorization.k8s.io_v1_Role|namespace-2|dummy` 

With the kustomize version `v3.8.0` everything works fine.

This behaviour is analog to https://github.com/kubernetes-sigs/kustomize/issues/1352, but with `Roles`

**Comment by Shell32-Natsu** [comment]
We may need to have more accurate information about the issue. Could you provide a minimum version of your files that can reproduce this issue?

**Comment by tiwalter** [comment]
Here an example for the reproduction of this issue:

__File Structure__

```
simulation
│   kustomization.yaml 
│
└─── namespace-1
│   │   kustomization.yaml 
│   │   role-ns1.yaml
│   │   rolebinding-ns1.yaml
│   
└─── folder2
│   │   kustomization.yaml 
│   │   role-ns2.yaml
│   │   rolebinding-ns2.yaml
```

[simulation.zip](https://github.com/kubernetes-sigs/kustomize/files/5261073/simulation.zip)

__Command__

``kustomize build --load_restrictor none``

__Error Message__

``
Error: obj '{"apiVersion": "rbac.authorization.k8s.io/v1", "kind": "RoleBinding", "metadata": {
    "name": "testRoleBinding", "namespace": "namespace-1"}, "roleRef": {"apiGroup": "rbac.authorization.k8s.io",
    "kind": "Role", "name": "testRole"}, "subjects": [{"kind": "ServiceAccount", "name": "testAccount",
      "namespace": "namespace-2"}]}
' at path 'roleRef/name': multiple matches for rbac.authorization.k8s.io_v1_Role|~X|testRole:
  [rbac.authorization.k8s.io_v1_Role|namespace-1|testRole
 rbac.authorization.k8s.io_v1_Role|namespace-2|testRole
]
``

**Comment by Shell32-Natsu** [comment]
The namespace in kustomization.yaml files will not be applied to the roleRef field in rolebinding files. So the `testRole` in roleRef will match 2 roles with the same name.

**Comment by tiwalter** [comment]
The namespace is not needed in the `roleRef` field in the `RoleBinding`.

If you run the command with Kustomize v.3.8.0, everything works fine.

**Comment by Shell32-Natsu** [comment]
I see. The issue is introduced in #2739, which is intended to update service account names across namespace.

**Comment by tiwalter** [comment]
In my opinion, this bug has to be fixed.

**Comment by Shell32-Natsu** [comment]
Yes. I am working on a fix.

**Comment by blaggacao** [comment]
I've observed a similar error
```
Error: obj '{"apiVersion": "rbac.authorization.k8s.io/v1", "kind": "ClusterRoleBinding", "metadata": {
    "labels": {"app.kubernetes.io/managed-by": "kapp-or-skaffold"}, "name": "spire-server-cluster-role-binding"},
  "roleRef": {"apiGroup": "rbac.authorization.k8s.io", "kind": "ClusterRole", "name": "spire-server-cluster-role"},
  "subjects": [{"kind": "ServiceAccount", "name": "spire-server", "namespace": "spire"}]}
' at path 'subjects': multiple matches for ~G_v1_ServiceAccount|spire|spire-server:
  [~G_v1_ServiceAccount|spire-infra|spire-server
 ~G_v1_ServiceAccount|spire-workstations|spire-server
]
```

but want to highlight that, while both exists:
- `~G_v1_ServiceAccount|spire-infra|spire-server`
- `~G_v1_ServiceAccount|spire-workstations|spire-server`

the matching atempt is doen against the resource _before_ the namespace transformation:
- `~G_v1_ServiceAccount|spire|spire-server`

the final output of kustomize build of only one of the conflicting branches correctly shows:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-server-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spire-server-cluster-role
subjects:
- kind: ServiceAccount
  name: spire-server
  namespace: spire-infra  # correct namespace
```
