### ISSUE TITLE
Feature: Enable to install a specific kustomize version with the "install_kustomize.sh" script

### ISSUE THREAD

**Issue by tiwalter** [kubernetes-sigs/kustomize#3022]
Actually, the https://github.com/kubernetes-sigs/kustomize/blob/master/hack/install_kustomize.sh script only installs the most recently released kustomize version.

It will be helpful to extend this script. so that we can install a specific kustomize version.

__Idea:__ 
- The script accepts an argument with the kustomize version and installs the specified version.
- The most recently released kustomize version will be installed, if there is no argument given.

**Comment by tiwalter** [comment]
Enabled by #3023.

**Comment by blaggacao** [comment]
Close?

**Comment by tiwalter** [comment]
PR is merged -> closed!

**Comment by tiwalter** [comment]
Can someone link the PR to the issue?
