### ISSUE TITLE
kustomize build changing string values to integer

### ISSUE THREAD

**Issue by sahil-sawhney** [kubernetes-sigs/kustomize#3031]
I have one of my yaml in overlays to include environment variables as follows
`COUNT: "10"`
Now when I do a Kustomize build, above content transforms to this
`COUNT: 10`
Now when I try to do a kubectl apply to this, it reports an error 
`The pod is invalid: spec.containers.env.COUNT: Invalid value: "integer": spec.containers.env.COUNT in body must be of type string: "integer"`

**Comment by Shell32-Natsu** [comment]
Please provide your kustomization.yaml file and other related files so we can reproduce it.

**Comment by sahil-sawhney** [comment]
@Shell32-Natsu I got my issue resolved. It was a problem caused by envsubst. Thanks for checking

**Comment by Shell32-Natsu** [comment]
Great to hear that!

/close

**Comment by shshe** [comment]
@sahil-sawhney We're seeing this issue on Ubuntu 20.04.1 LTS where integers in environment variables were quoted in `kustomization.yaml` but not quoted in the generated manifests after running kustomize. What did you do to resolve this issue with envsubst? Thanks!

**Comment by Shell32-Natsu** [comment]
@shshe Please take a look at #3412
