### ISSUE TITLE
Add kustomize edit add/remove transformer command

### ISSUE THREAD

**Issue by mikeyrcamp** [kubernetes-sigs/kustomize#3053]
**Is your feature request related to a problem? Please describe.**

Presently if someone wishes to add a transformer file to the `transformers`  in their kustomization.yaml they must use python or some other scripting language to modify the kustomization.yaml file rather than using the idiomatic `kustomize edit` command.

**Describe the solution you'd like**

As kustomize has a `kustomize edit add resource {filepath}` and `kustomize edit remove resource {filepath}` command to modify the resources . I'd like two additional commands for `kustomize edit add transformer {filepath}` and `kustomize edit remove transformer {filepath}` that add and remove the specified transformer.

**Describe alternatives you've considered**

Right now we can have some python scripts use ruamel.yaml or some other python library to modify the kustomization.yaml, but it would be nice to do this directly with kustomize rather than a supporting script.

**Additional context**

I'll bring this before sig-cli, and I'd be happy to contribute this feature.

**Comment by ricochet** [comment]
@monopole - ok to implement?

**Comment by monopole** [comment]
yes please!
