### ISSUE TITLE
Incorrect docs re kustomize config save?

### ISSUE THREAD

**Issue by max-sixty** [kubernetes-sigs/kustomize#3057]
**Describe the bug**

https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs#customizing-transformer-configurations

contains: 

> Save the default transformer configurations to a local directory by calling `kustomize config save -d`, and modify and use these configurations. This tutorial shows how to create custom transformer configurations:

...but `kustomize config` doesn't seem to exist in 3.8.4; nor does `kustomize cfg save`?

**Kustomize version**

{Version:kustomize/v3.8.4 GitCommit:8285af8cf11c0b202be533e02b88e114ad61c1a9 BuildDate:2020-09-19T17:31:52+01:00 GoOs:darwin GoArch:amd64}

**Platform**

MacOS

**Comment by Shell32-Natsu** [comment]
We will remove those lines about `kustomize cfg save`. Please see https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md for the customizing transformer configs.
