### ISSUE TITLE
Make setters2 suitable for use in controllers

### ISSUE THREAD

**Issue by squaremo** [kubernetes-sigs/kustomize#3058]
I'd like to be able to use `kyaml/setters2` in a Kubernetes controller. One requirement this brings up is that setter definitions cannot be retained across invocations, since in general the controller will process many objects, each of which gives rise to its own setter definitions.

At present, so far as I can determine*, `setters2` gets its definitions from `openapi`, which keeps them in a package variable -- I would have to serialise access to the global schema to avoid mixing definitions from one object with definitions from another. It would be more satisfactory if setters2 used a schema value supplied to it.

(*The visitor which is traversing the input YAML nodes to set things uses [`openapi.Resolve`](https://github.com/kubernetes-sigs/kustomize/blob/460c54064c4faf87ddd36f23aa63e3ffb92c4361/kyaml/openapi/openapi.go#L222) to find a definition given a ref, and that method returns the global schema.)

This would also need some work in `kyaml/openapi` so that e.g., `AddDefinitions` was available as a method on a schema value, as well as a func modifying the package variable.

**Comment by Shell32-Natsu** [comment]
It will be good to open a PR for this. We don't have enough resources to work on this now.

**Comment by squaremo** [comment]
Fixed in #3219. Thank you!
