### ISSUE TITLE
[Question] Selectively apply nameprefix/namesuffix in kustomize

### ISSUE THREAD

**Issue by kkishoreyadav** [kubernetes-sigs/kustomize#3062]
Currently we are using ${HOME}/bin/kustomize edit set namesuffix suffix1

But it is adding suffix1 to all of our resources like deployment.yaml and service.yaml.

We want to apply suffix1 to deployment.yaml only and not apply it to service.yaml

This is related to https://github.com/kubernetes-sigs/kustomize/issues/1700

**Comment by Shell32-Natsu** [comment]
You can configure the prefix/suffix transformer to apply suffix to specify resources. See https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs and https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configureBuiltinPlugin.md
