### ISSUE TITLE
How to pass Git credentials in a Kustomize build command? [Question]

### ISSUE THREAD

**Issue by fernandolozano** [kubernetes-sigs/kustomize#3077]
Hello,
I have a _kustomization.yaml_ file that uses a private repository as a resource:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://gitlab.com/my-user/k8s-base-cfg.git
patchesStrategicMerge:
  - app-patch.yaml
```

I want to automate this on a Jenkins Pipeline. I don't know how to pass Git credentials to the kustomize build command. Is there any option to do that?

Thank you

**Comment by Shell32-Natsu** [comment]
kustomize will use [go-getter](https://github.com/hashicorp/go-getter) to get the repo at first. If it fails it will use `git` command to clone the repo. So what you can do is make `git clone [url]` command work with your credential without human got involved.
