### ISSUE TITLE
[Question] how to add resources at runtime using "kubectl" cmd

### ISSUE THREAD

**Issue by jazzsir** [kubernetes-sigs/kustomize#3082]
Using "kustomize" command, I can add/remove resources to/from kustomization.yaml as below
```
kustomize edit add resource resource.yaml
```

But using "kubectl", I can not
```
kubectl kustomize edit add resource resource.yaml
Error: specify one path to a kustomization directory
```

**Comment by Shell32-Natsu** [comment]
kubectl is using a very old version of kustomize (v2.x). We are trying to re-integrating with kubectl but I cannot give an ETA.

/close
