### ISSUE TITLE
[Doc] No document for components

### ISSUE THREAD

**Issue by Shell32-Natsu** [kubernetes-sigs/kustomize#3090]
There is an [example](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md) for components but the [document page](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md) says *coming soon*.

**Comment by Shell32-Natsu** [comment]
Add a link to https://kubernetes-sigs.github.io/kustomize/guides/components/ in https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/components/

**Comment by apyrgio** [comment]
@pgpx: You're probably interested to this issue as well. Given your great explanation on #3142, could you perhaps reword it and add it to https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/components/?

**Comment by pgpx** [comment]
Yes, good idea - I'll give it a go.
