### ISSUE TITLE
Merge ContainerPort ports field using containerPort,protocol tuple

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#3111]
new plan: merging should look for a `x-kubernetes-list-map-keys` field and use the list to merge if the list exists, then fall back to the singular field `x-kubernetes-patch-merge-key` and use that.
The libraries must respect the intent of the schema.

see this [note](https://github.com/kubernetes-sigs/kustomize/issues/3111#issuecomment-716736823)

---- original comment below

We had to to rollback #3065 (see #3102) because we realized that if the name field isn't present, we don't fall back to merging on port.

Underlying issue was #2767

So the new task is reinstate #3065, but have a means to fall back to `containerPort` number merging if no `name` is present.

[this example]: https://github.com/GoogleContainerTools/kpt/blob/master/internal/testutil/testdata/dataset1/java/java-deployment.resource.yaml

So if someone wants to overwrite a containerPort via a patch, and there's no name field in the `port`, it should work. I.e. the 8080 in [this example] should override the original port.

The workaround for a user it to provide name fields on each `port`.

Can we put a comma-delimited list in the `x-kubernetes-patch-merge-key` field?

**Comment by monopole** [comment]
@natasha41575

**Comment by apelisse** [comment]
> Can we put a comma-delimited list in the x-kubernetes-patch-merge-key field?

You can't. But you can possibly look at `x-kubernetes-list-map-keys` which accepts a list of fields rather than just one.[1]

[1]: https://kubernetes.io/docs/reference/using-api/api-concepts/#merge-strategy

**Comment by monopole** [comment]
This goes way back:  https://github.com/kubernetes/kubernetes/issues/39188

It's a long discussion, and the issue is still open.
@brianpursley did a nice job summarizing the problem.
Here's what i think we know:

 1. From https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core,
we know that the `ports` field is a list of ContainerPort with merge key `containerPort`.

 1. People want to have multiple entries in the `ports` list that have the same `containerPort` number (i.e. using `containerPort` as a merge key was a mistake).

 1. Solutions suggested are require a `name` field and use that, or combine `containerPort` and `protocol` into a merge key - but these are API breaking changes.

kustomize is not bound by the same constraints as the API server. 

I propose we write merge code that honors multiple keys in some order, then massage the openapi schema used by kustomize to introduce a merge key list ( `name`, `containerPort`, `protocol`).  If this is fixed in upstream, we'll detect it (tests will break), and we adapt when that happens.

**Comment by apelisse** [comment]
> People want to have multiple entries in the ports list that have the same containerPort number (i.e. using containerPort as a merge key was a mistake).

It's unclear from your sentence if they want multiple entries with the same port because they want name aliases, or because they want ports with the same number on the same protocol. if the former, then the primary key should have been the name, if the latter (the current assumption, and my assumption too), then the key should be a combination of port and protocol.

**Comment by Shell32-Natsu** [comment]
> It's unclear from your sentence if they want multiple entries with the same port because they want name aliases, or because they want ports with the same number on the same protocol.

In issue #2767 there are both. The main thread if former and [this comment](https://github.com/kubernetes-sigs/kustomize/issues/2767#issuecomment-674062357) is latter.

**Comment by apelisse** [comment]
I'd like to see a good argument for the multiple names being useful. So far I'm really not convinced this is a problem. Note that the apiserver will REMOVE one of the two anyway (and maybe eventually fail, server-side apply will certainly fail), so whatever Kustomize does it somewhat irrelevant (it should probably fail).

The port/protocol combination is the new primary key for this field, and will typically result in a merge that will be strictly additive (rather than replacing), so for example: `[{port: 80, protocol: TCP}]` + `[{port: 80, protocol: TCP}]` = `[{port: 80, protocol: TCP}, {port: 80, protocol: TCP} ]`. There is no way to remove, do we want a mechanism for that?

**Comment by monopole** [comment]
I have no more context for #2767 (and the multiple names on the same port/protocol tuples).  Certainly agreed it makes no sense for kustomize to jam all this together, and the have the api server puke on it regardless. 

kustomize doesn't encourage removal; it encourages addition or mutation only.  that said, there's work in the backlog to support json 6902 removal operations.  that's beside the point though.

**Comment by monopole** [comment]
> The port/protocol combination is the new primary key for this field
Where (or when) does that show up in the openapi schema?

**Comment by apelisse** [comment]
> Where (or when) does that show up in the openapi schema?

We have that on the `containerPort` field:
`"x-kubernetes-list-map-keys": ["port", "protocol"]`

**Comment by ephesused** [comment]
Regarding possible reasons to support multiple names referring to a single port, I follow the argument that the current kubernetes implementation does not work as one might expect in that scenario.

However, kubernetes accepts resources whose containers have multiple ports with the same number but divergent names. I can see a reasonable argument that kustomize should not produce yaml that kuberetes will reject. But I don't know that kustomize should alter yaml that kubernetes accepts (even if kubernetes currently doesn't handle that data as one might expect). And, as a user, it's quite surprising when a transformer that applies a label has a side effect that alters ports.

I also think there's an argument in support of multiple names for a single port. Ports have port aliases; I can refer to port 25 as either smtp or as mail.

**Comment by apelisse** [comment]
> But I don't know that kustomize should alter yaml that kubernetes accepts (even if kubernetes currently doesn't handle that data as one might expect). 

kustomize probably has to parse the object in a representation that makes sense for it. If the object is incorrect, it probably can't do that.

> I also think there's an argument in support of multiple names for a single port. Ports have port aliases; I can refer to port 25 as either smtp or as mail.

I think it's fine if we don't have that feature though, unless it really breaks something that I'm missing?

**Comment by natasha41575** [comment]
@apelisse did you see this issue? different port names but still merging incorrectly. I was wondering what your thoughts are on that, and if in that case it makes sense to have name be the merge key
https://github.com/GoogleContainerTools/kpt/issues/1143

**Comment by ephesused** [comment]
> > I also think there's an argument in support of multiple names for a single port. Ports have port aliases; I can refer to port 25 as either smtp or as mail.
> 
> I think it's fine if we don't have that feature though, unless it really breaks something that I'm missing?

I agree. Right now I think it's fine since there's no end result breakage.

At root, there's no "right" answer until kubernetes/kubernetes#39188 is resolved. Until then, my arguments are mostly academic. It's unexpected to have a patch transformer for a label end up altering ports. On some level, kustomize is acting as a linter. But I follow why that's happening.

**Comment by monopole** [comment]
Thanks @ephesused !

Copying a comment from #3125, the current consensus is that merging should look for a `x-kubernetes-list-map-keys` field and use the list to merge if the list exists, then fall back to the singular field `x-kubernetes-patch-merge-key` and use that.  The libraries must respect the intent of the schema.

So kustomize won't merge `ContainerPort/ports` on `name`, and thus won't support having multiple names for one `{containerPort,protocol}` tuple, until the schema changes.  

A good place to lobby for a schema change would be on kubernetes/kubernetes#39188 as that's where all the context is.

**Comment by natasha41575** [comment]
Fixed by #3159, I think this can be closed now
