### ISSUE TITLE
merge or replace behaviour not working in configmapgenerator

### ISSUE THREAD

**Issue by sharvii** [kubernetes-sigs/kustomize#3124]
kustomization yaml  used is as below 

![image](https://user-images.githubusercontent.com/7362601/96593178-d2a9b180-1306-11eb-9fdd-65a7ac9f208b.png)

error received after applying below command .

kubectl apply -k .

error: id resid.ResId{gvKind:gvk.Gvk{Group:"", Version:"v1", Kind:"ConfigMap"}, name:"config", prefix:"", suffix:"", namespace:"default"} does not exist; cannot merge or replace

**Comment by Shell32-Natsu** [comment]
Please try latest kustomize version. THe version that shipped with kubectl is very old.

**Comment by sharvii** [comment]
i installed latest version of kustomize 
{Version:kustomize/v3.8.5 GitCommit:4052cd4fd8c76a17b5f64e32509f3fba9713fe75 BuildDate:2020-10-08T02:45:59Z GoOs:linux GoArch:amd64}

Still getting similar error

![image](https://user-images.githubusercontent.com/7362601/96684538-6330d200-1399-11eb-9b3d-3ef6d6c4bc7d.png)

error received on running below command 

kustomize build .

Error: merging from generator &{0xc000198fc0 {  map[] map[]} {{default config replace {[] [] [config.txt]} <nil>}}}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap"}, Name:"config", Namespace:"default"} does not exist; cannot merge or replace

**Comment by Shell32-Natsu** [comment]
Please provide the content in deployment.yaml and service.yaml.

**Comment by sharvii** [comment]
my folder structure is as below. I am not using overlay.

![image](https://user-images.githubusercontent.com/7362601/96753692-d95f2400-13ed-11eb-8e47-764b38f0bde8.png)

deployment.yaml
![image](https://user-images.githubusercontent.com/7362601/96753634-c5b3bd80-13ed-11eb-8468-6d038bee4f78.png)


service.yaml

![image](https://user-images.githubusercontent.com/7362601/96753778-f562c580-13ed-11eb-8a6b-4d63e49ae416.png)

config.txt

![image](https://user-images.githubusercontent.com/7362601/96753946-3b1f8e00-13ee-11eb-9dd7-3117f70290cd.png)

kustomize build .

Error: merging from generator &{0xc000176f90 {  map[] map[]} {{default config replace {[] [] [config.txt]} <nil>}}}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap"}, Name:"config", Namespace:"default"} does not exist; cannot merge or replace

**Comment by Shell32-Natsu** [comment]
configMapGenerator will add a hash suffix by default so you cannot refer it directly by name.

Please add

```
options:
    disableNameSuffixHash: true
```
to your configMapGenerator item.
