### ISSUE TITLE
Misleading documentation of `configMapGenerator`

### ISSUE THREAD

**Issue by benbc** [kubernetes-sigs/kustomize#3131]
The `kustomize` examples ([here](https://github.com/kubernetes-sigs/kustomize/blame/master/examples/combineConfigs.md#L254-L255)) says:

> Instead of editing configMaps, modify your declarative specification of the cluster's desired state to point deployments to new configMaps with new names. kustomize makes this easy with its configMapGenerator directive and associated naming controls. A GC process in the k8s master eventually deletes unused configMaps.

That is not the case -- there is no such GC process.

This is not a bug report about the lack of the GC process or the problem of how to handle that in a `kustomize`-based workflow (that has been reported in #1806 and #242). It is just a request to clear up that misleading bit of documentation (and ideally replace it with a hint as to how to handle the clean-up of unused `ConfigMap`s.

**Comment by Shell32-Natsu** [comment]
Thanks for the report!

**Comment by Shell32-Natsu** [comment]
And PRs are welcome. :)

**Comment by ilyakaznacheev** [comment]
Hello, I collected information on how this can be done (actually from different issues and even from docs) and added here. Nothing _really_ special, but may be helpful.
