### ISSUE TITLE
[Question] How do I label my K8 objects with the current commit?

### ISSUE THREAD

**Issue by DavidGrinberg** [kubernetes-sigs/kustomize#3148]
I have an automated deployment pipeline and of its features is labeling all objects in K8 with the git commit they came from. This is achieved by simply having 
```
metadata:
   labels:
      commit: ${COMMIT_SHA}
```
Then my CI/CD runs `envsubt` before running `kubectl apply`. How would I replicate this in Kustomize? I realize I could have
```
commonLabels:
   commit: ${COMMIT_SHA}
```
and just run `envsubt` on that, but that seems to break the whole 'no templating' paradigm of Kustomize and not really giving me any benefit. It also seems to get complicated when I end up with multiple bases. 

What is the Kustomize way of doing this?

**Comment by Shell32-Natsu** [comment]
One way is using `kustomize edit add label` to add the `commonLabels` to kustomization file dynamically.

We also have [vars](https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/vars/) for this arbitrary fields and values. However, there is a [proposal](https://github.com/kubernetes-sigs/kustomize/issues/2052) to remove it in future so this is not recommended.

**Comment by DavidGrinberg** [comment]
`kustomize edit` seems like a less than ideal solution because it quickly complicates deployment. I would go from a nice clean 1 line `kubectl apply -k` to a long chain of a bunch of `kustomize edit` calls after the fact. I have other usecases where I inject values from environment variables, so I think this would quickly get out of hand.

**Comment by Shell32-Natsu** [comment]
Another possible solution is creating your own [transformer](https://kubernetes-sigs.github.io/kustomize/guides/plugins/execpluginguidedexample/)

**Comment by maxmoehl** [comment]
Came across this while trying to achieve the same thing. I've put my current solution in [a gist](https://gist.github.com/maxmoehl/7fe32619f8503b5d29abfcc0e0f9e7df). It's a custom transformer that adds the label `app.kubernetes.io/version: ${COMMIT_HASH}` to every resource.
