### ISSUE TITLE
Feature: Apply patches to name prefixed resources

### ISSUE THREAD

**Issue by mxey** [kubernetes-sigs/kustomize#316]
Scenario: I have several instances (overlays) of an application (base) that I want to combine into combined Kustomizations to apply them as one. 

In that Kustomization, I want to apply patches. If I use the un-prefixed name of a resource, the patch will be ambiguous. If I use the prefixed name, Kustomize cannot find the resource.

**Comment by mxey** [comment]
> One possible solution is to add some enhancement on current applying patch process. When multiple objects are found for one patch, we can do a second round filtering by prefix.

I think that makes sense.

**Comment by guyromb** [comment]
+1

**Comment by jcassee** [comment]
This is becoming a problem in our situation. I have a couple of bases that are being reused in a single overlay. For example, the PersistentVolumeClaim of different Postgres bases need different sizes patched in.

@Liujingfang1 Can you give some code pointers on where that second name matching round would need to be added?

**Comment by mildred** [comment]
The fact that resources are referenced with their names without prefix and suffix applied could cause other issues such as #800 (just guessing though)

**Comment by monopole** [comment]
Calling this fixed by #1183, which is in v2.1.0.  Added a test to cover in #1278.
