### ISSUE TITLE
[Question] Would like to yaml output to split to multiple files instead of a single file

### ISSUE THREAD

**Issue by suryak** [kubernetes-sigs/kustomize#3175]
I am not able to see any documentation of how to use this. Can some point to documentation or let me know to use this feature. 

Write individual files to output path if it is a directory #960
https://github.com/kubernetes-sigs/kustomize/pull/960

**Comment by Shell32-Natsu** [comment]
If you use a directory for `-o/--output` flag, the resources will be written into individual files.

**Comment by BlackBsd** [comment]
How would i use this if I were trying to use the kustomize part of kubectl?
`kubectl kustomize <dir>`??

**Comment by flickerfly** [comment]
Last I knew, the kubectl version does not support the version of kustomize that has the -o option. This would need to be done outside kubectl.
