### ISSUE TITLE
Fix the link to release page on https://kubernetes-sigs.github.io/kustomize/installation/binaries/

### ISSUE THREAD

**Issue by Sabatino78** [kubernetes-sigs/kustomize#3179]
On the page https://kubernetes-sigs.github.io/kustomize/installation/binaries/ i see the text "Binaries at various versions for linux, MacOs and Windows are published on the [release page]." but i don't see the link to that page.
Can you add it?

**Comment by Shell32-Natsu** [comment]
Release page: https://github.com/kubernetes-sigs/kustomize/releases

Please check it when we are updating doc.

**Comment by Shell32-Natsu** [comment]
Fixed by #3140
