### ISSUE TITLE
Flux logo on https://kustomize.io/ is old

### ISSUE THREAD

**Issue by dholbach** [kubernetes-sigs/kustomize#3180]
Not sure if this is the right repo for the issue, but the Flux logo on https://kustomize.io/ is old.

Can it be replaced with e.g. https://branding.cncf.io/img/projects/flux/horizontal/color/flux-horizontal-color.png?

(Might be worth documenting in https://github.com/kubernetes-sigs/kustomize/blob/master/site/README.md or https://github.com/kubernetes-sigs/kustomize/tree/master/site/content/en/contributing where the source for the main landing page lives?)

**Comment by Shell32-Natsu** [comment]
> Not sure if this is the right repo for the issue

It's not :).

That website is not maintained by us.

**Comment by dholbach** [comment]
Who can I get in touch with about the website?

**Comment by Shell32-Natsu** [comment]
In the footer of that website, it says it's contributed by https://replicated.com/

**Comment by dholbach** [comment]
All right. I posted a message here: https://help.replicated.com/community/t/code-for-kustomize-io-site/464

**Comment by pwittrock** [comment]
We should probably reach out to replicated and see if they would be willing transfer the domain.

**Comment by dholbach** [comment]
Fixed: https://kustomize.io/ - and in the thread it looks like opening the repository is being looked into.
