### ISSUE TITLE
kustomize can not overwrite the service or deployment which be changed by manual update.

### ISSUE THREAD

**Issue by Darren-wh** [kubernetes-sigs/kustomize#3186]
Test step  as follows:
1.Preparing the deployment  and service
2.use the kustomize command to deploy service.
3.using the "kubectl edit deployment deployment" or service to add new Containers configuration and save.
Then kubernetes will do a rolling update.
4.using the kustomize command with old deployment and service code (without new Containers) to deploy service.
Then the kubernetes will do a rolling update. And you can check the service or deployment, you will find new Containers configuration is still there., it doesn't be to overwrite by the old version.
5. The Image is new but still use old configuration( The step about adding new Containers configuration).

Anybody has been this question？Please tell the root cause.

kustomize command as follows:

kustomize build --load_restrictor none /test/k8s/ |kubectl apply -f -

**Comment by Shell32-Natsu** [comment]
I suspect you should open the issue in `kubectl`. What kustomize does is just producing resources and it cannot control what it looks like after applying.

**Comment by Shell32-Natsu** [comment]
You can produce your configurations so that we can check is there an error in kustomize's result.

**Comment by Darren-wh** [comment]
yes, Today I used the kubectl command to test this case, and it still has been this problem. So it's not the issue about the customize. Thanks. 

kubectl issue:
https://github.com/kubernetes/kubernetes/issues/75394


![image](https://user-images.githubusercontent.com/32630985/98317810-2eb74a00-2018-11eb-97f5-0336986bbadb.png)
