### ISSUE TITLE
Can't install older version of kustomize because of Github limit on releases API

### ISSUE THREAD

**Issue by fallard84** [kubernetes-sigs/kustomize#3189]
I was trying to install an older version of kustomize using the official script https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh and passing the older version  (3.5.3) as an argument to the script. 

**Expected output**

The specified version of kustomize should be installed.

**Actual output**

I got the error `kustomize binary with the version 3.5.3 does not exist!` 

I looked at the script and saw that the https://api.github.com/repos/kubernetes-sigs/kustomize/releases API is used to grep the available versions. This API is limited to 100 results, and since the kustomize repo has many packages releases, only v3.8 is available in the first 100 releases.

**Platform**
macOS

**Additional context**

I am trying to automate the installation of kustomize for a team of developers. For now I am using a custom script to download the specific version I need, but I thought I would share the issue.

**Comment by Shell32-Natsu** [comment]
Thanks for report. We will try to address it (hopefully not take too long time).
