### ISSUE TITLE
install_kustomize.sh Pulls ARM instead of AMD64

### ISSUE THREAD

**Issue by SudoBrendan** [kubernetes-sigs/kustomize#3196]
**Describe the bug**

`install_kustomize.sh` downloads the wrong binary ("arm" vs "amd"), and so `tar` fails.

When running:

```sh
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/kustomize/v3.8.2/hack/install_kustomize.sh" | bash
```

I get the error:

```text
tar (child): ./kustomize_v*_linux_amd64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
cp: cannot stat './kustomize': No such file or directory
bash: line 49: ./kustomize: No such file or directory
kustomize installed to current directory.
```

**Platform**

Linux, AMD64

**Additional context**

Seems that adding an additional `grep` command for architecture ("amd" vs "arm") would solve this. Another quick win would be running `set -e` so that the script exists on errors instead of erroneously saying kustomize was installed.

**Comment by Shell32-Natsu** [comment]
This should have been fixed in master branch. Please use latest installation script. `https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh`.
