### ISSUE TITLE
patchMultipleObjects example fail to build

### ISSUE THREAD

**Issue by davide-talesco** [kubernetes-sigs/kustomize#3208]
**Describe the bug**
The demo @ https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md does not work.
The build fails with the following error:

Error: json: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type types.PatchStrategicMerge

**Actual output**
Error: json: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type types.PatchStrategicMerge

**Kustomize version**

Tried both v2.03 (kubectl v1.16.3) and 3.0.2

**Comment by monopole** [comment]
The examples are intended for use with more recent versions, in particular the 3.8 series.
If you can repo with the 3.8 series, please reopen.

**Comment by monopole** [comment]
https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.8.6
