### ISSUE TITLE
Failed to install 0.9.4 binary

### ISSUE THREAD

**Issue by realshuting** [kubernetes-sigs/kustomize#3212]
**Describe the bug**

I'm running this command to install the latest binary while it throws an error:
```
✗ curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
Error: kustomize binary with the version 0.9.4 does not exist!
```

**Expected output**
Installs Kustomize binary successfully.

**Platform**
macOS

**Comment by Shell32-Natsu** [comment]
We are doing a release today. Please check back later.

**Comment by realshuting** [comment]
@Shell32-Natsu Thanks for the response!

How can I install a specific version with one line command?

**Comment by Shell32-Natsu** [comment]
Put the version number, say v3.8.6, as an argument for install_kustomize.sh.

**Comment by realshuting** [comment]
Yes, I tried the following but got:
```
✗ curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh v0.9.3" | bash
bash: line 1: Bad: command not found
```

Seemed to be an invalid command?

**Comment by sass1997** [comment]
+1

**Comment by Shell32-Natsu** [comment]
@realshuting Try this `curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s 3.8.6`

**Comment by realshuting** [comment]
Worked thanks!

**Comment by jkirkham-ratehub** [comment]
Assuming you have curl, jq and a version of grep that supports Perl-like regex, the following work for me to fix a failing CI build:

`latest=$(curl -sL https://api.github.com/repos/kubernetes-sigs/kustomize/git/refs/tags/kustomize | jq '.[-1].ref' | grep -Po '\d+\.\d+\.\d+')

curl -sLO "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"

bash ./install_kustomize.sh $latest
`

The issue is the latest GitHub "_release_" is for kyaml so the version does not exist for kustomize.
The above example is getting a tag list from the GitHub API, grabbing the last element with jq, and then parsing out the version with grep (from `refs/tags/kustomize/v<version>`).  It does appear the GitHub API always returns a sorted list of tag refs.

**Comment by realshuting** [comment]
Add to it - `grep -Po '\d+\.\d+\.\d+'` does not work for me, changed the first command to `grep -Eo '\d+\.\d+\.\d+` and now everything works.
```
latest=$(curl -sL https://api.github.com/repos/kubernetes-sigs/kustomize/git/refs/tags/kustomize | jq '.[-1].ref' | grep -Eo '\d+\.\d+\.\d+')
curl -sLO "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
bash ./install_kustomize.sh $latest
```

Output:
```
{Version:kustomize/v3.8.6 GitCommit:c1747439cd8bc956028ad483cdb30d9273c18b24 BuildDate:2020-10-29T23:13:15Z GoOs:darwin GoArch:amd64}
kustomize installed to current directory.
```

**Comment by jkirkham-ratehub** [comment]
> 
> 
> Add to it - `grep -Po '\d+\.\d+\.\d+'` does not work for me, changed the first command to `grep -Eo '\d+\.\d+\.\d+` and now everything works.
> 
> ```
> latest=$(curl -sL https://api.github.com/repos/kubernetes-sigs/kustomize/git/refs/tags/kustomize | jq '.[-1].ref' | grep -Eo '\d+\.\d+\.\d+')
> curl -sLO "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
> bash ./install_kustomize.sh $latest
> ```
> 
> Output:
> 
> ```
> {Version:kustomize/v3.8.6 GitCommit:c1747439cd8bc956028ad483cdb30d9273c18b24 BuildDate:2020-10-29T23:13:15Z GoOs:darwin GoArch:amd64}
> kustomize installed to current directory.
> ```

I think the "Extended" regex in grep normally doesn't handle `\d`, except maybe on OSX (maybe BSD in general).  On most linux distributions you'd need to use: `grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'` (which will also work on OSX).

**Comment by realshuting** [comment]
Yes I'm on macOS, your suggestion really solved my case!

**Comment by Shell32-Natsu** [comment]
Issue for the real problem: https://github.com/kubernetes-sigs/kustomize/issues/3215
