### ISSUE TITLE
Using a generator plugin: Error: <nil> is expected to be either a string or a []interface{}

### ISSUE THREAD

**Issue by nyarly** [kubernetes-sigs/kustomize#3224]
**Describe the bug**

I'm using a modified version of the example ChartInflator. It's worked well so far, but I've added a new helm chart, and I get an error like:
```
2020/11/12 13:44:52 nil value at `envFrom.configMapRef.name` ignored in mutation attempt
2020/11/12 13:44:52 nil value at `envFrom.secretRef.name` ignored in mutation attempt
2020/11/12 13:44:52 nil value at `volumes.configMap.name` ignored in mutation attempt
2020/11/12 13:44:52 nil value at `volumes.projected.sources.configMap.name` ignored in mutation attempt
2020/11/12 13:44:52 nil value at `volumes.secret.secretName` ignored in mutation attempt
2020/11/12 13:44:52 nil value at `volumes.projected.sources.secret.name` ignored in mutation attempt
2020/11/12 13:44:52 nil value at `volumes.persistentVolumeClaim.claimName` ignored in mutation attempt
Error: <nil> is expected to be either a string or a []interface{}
```

**Files that can reproduce the issue**

[repro.zip](https://github.com/kubernetes-sigs/kustomize/files/5533539/repro.zip)

Everything needed to recreate this issue with Kustomomize 3.8.1 should be included. You'll need `yq` 3.0 (the Go version, not the jq wrapper) and `kfilt` available to run the ChartInflator.

More than anything, there's no indication of the source of the issue is - even line numbers in the logs might be instructive.

Note that running the ChartInflator directly works and emits Kubernetes YAML, but that `kustomize build --enable_alpha_plugins zeebe/` produces the error.

**Comment by Shell32-Natsu** [comment]
The problem is 
```
volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: null
```
in StatefulSet `tier-zero-zeebe`. 3.8.1 cannot handle `storageClassName: null` correctly. It has been solved in latest kustomize version.
