### ISSUE TITLE
Bad function parameter

### ISSUE THREAD

**Issue by waro163** [kubernetes-sigs/kustomize#3234]
in the function:
https://github.com/kubernetes-sigs/kustomize/blob/c464fb0a8128b16e6252eec888e919a58655654a/pkg/transformers/config/factorycrd.go#L71

is different with the function definition:
func looksLikeAk8sType(properties myProperties) bool

is this a bug?

**Comment by waro163** [comment]
![image](https://user-images.githubusercontent.com/12164123/99274151-ef34fd00-2864-11eb-91fe-2b1012b0dcd3.png)

**Comment by Shell32-Natsu** [comment]
Your reference codes are very old. Please use latest version of kustomize.

**Comment by waro163** [comment]
Thanks for your response @Shell32-Natsu, but i use the latest version kubectl, the kubectl repo is still use v2.0.3 kustomize, you can see it here: https://github.com/kubernetes/kubectl/blob/b155278f1f4a21a0be2d4f6f0037258dee4d1a22/go.mod#L47
I read the kustomize repo v2.0.3, the code is also https://github.com/kubernetes-sigs/kustomize/blob/a6f65144121d1955266b0cd836ce954c04122dc8/pkg/transformers/config/factorycrd.go#L71
https://github.com/kubernetes-sigs/kustomize/blob/v2.0.3/pkg/transformers/config/factorycrd.go#L71
how can i solve the problem? Thanks again

**Comment by Shell32-Natsu** [comment]
Use kustomize 3.8.7. We cannot update the kustomize version with kubectl for technical reasons.
