### ISSUE TITLE
kustomize version doesn't output correct version informations

### ISSUE THREAD

**Issue by Shitaibin** [kubernetes-sigs/kustomize#3243]
**Describe the bug**

`kustomize version` is not work, when I want to see the kustomize version in my host. Then I build kustomize from the master branch and tag `kustomize/v3.8.7`. I got the same result. Dose this bug affect lots of version?

```
[~/Workspace/kustomize]$ g checkout kustomize/v3.8.7
Note: switching to 'kustomize/v3.8.7'.

You are in 'detached HEAD' state. You can look around, make experimental
.....
HEAD is now at ad092cc7 Merge pull request #3216 from monopole/pin_api_v0.6.5
[~/Workspace/kustomize]$ rm `which kustomize`
[~/Workspace/kustomize]$ which kustomize
kustomize not found
[~/Workspace/kustomize]$ 
[~/Workspace/kustomize]$ cd kustomize 
[~/Workspace/kustomize/kustomize]$ go install . 
go: downloading sigs.k8s.io/kustomize/cmd/config v0.8.5
go: downloading sigs.k8s.io/kustomize/api v0.6.5
go: downloading sigs.k8s.io/kustomize/kyaml v0.9.4
[~/Workspace/kustomize/kustomize]$
[~/Workspace/kustomize/kustomize]$ kustomize version
{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:darwin GoArch:amd64}
```

**Expected output**

Correct version, Like

```
{Version: 3.8.7 GitCommit: ...}
```

**Actual output**

```
{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:darwin GoArch:amd64}
```

**Kustomize version**

No version info.

**Platform**

Tested in Linux and Mac.

**Comment by Shell32-Natsu** [comment]
These values are set dynamically when we build release versions. So this is expected if you build from source code.

**Comment by Shitaibin** [comment]
Yes. Using `-ldflags` can pass these values when build. Is any plan to add it to [Makefile](https://github.com/kubernetes-sigs/kustomize/blob/master/Makefile#L94) to show correct versions. 

`make $GOBIN/kustomize` or `make kustomize` will generate the correct program same as installed from binary.

**Comment by Shell32-Natsu** [comment]
No we don't plan to add version information by default when someone is building from source code. It's left to users.
