### ISSUE TITLE
Design for allowing more GVKN/Namespace changing in a pipeline

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#3246]
Need to flesh out an implementation plan for allowing kustomize to alter the GVKN/Namespace of resources

**Comment by natasha41575** [comment]
@monopole @Shell32-Natsu could one of you move this to "in progress", thanks!

**Comment by Shell32-Natsu** [comment]
Better to consider #3228 when you design the key/name back reference implementation.
