### ISSUE TITLE
Parameter imageTags doesn't work with digests

### ISSUE THREAD

**Issue by burdiyan** [kubernetes-sigs/kustomize#326]
When you try to use `imageTags` parameter in `customization.yaml` it doesn't work with repository digests.

The result is something like: `nginx:@sha256:8cc4d2aa73ce6d6e8750f72f7b835705d092b1cbc41bec20`

It's not working from the CLI either.

What I'm trying to achieve is to replace image tags with digests in certain overlays.

**Comment by burdiyan** [comment]
As an alternative solution digest resolution could happen passing special flag to `kustomize edit imagetags` so that digests is stored directly in the `kustomization.yaml`.

I like this one actually better than the first approach. And no additional fields are needed for image tag. The only thing is that the original defect mentioned in the first comment needs to be resolved.

**Comment by Liujingfang1** [comment]
@burdiyan We think resolving an image tag to digest is outside of the scope of Kustomize for following reasons:
- it has external dependency on the image registry and needs some credential to talk with the registry
- The output is not fully determined by a kustomization itself

If users can get the digest by other tools, maybe we can consider adding the support for `kustomize edit imagetags image:<digest>`. Then the output is deterministic.

**Comment by burdiyan** [comment]
@Liujingfang1 Yeah, I agree. The resolution is probably outside of the scope of Kustomize.

I submitted a PR for digest support in image overwrites https://github.com/kubernetes-sigs/kustomize/pull/331 so this issue will be closed as soon as the PR is merged.
