### ISSUE TITLE
kustomize edit add resource remoteurl shouldn't require validation

### ISSUE THREAD

**Issue by james-callahan** [kubernetes-sigs/kustomize#3276]
Running `kustomize edit add resource git@github.com/myorg/myrepo/kustomize/base?ref=abcdef` shouldn't require network connectivity or permission to the repo.
We generate some of our kustomizations in a locked down environment that doesn't have a valid key to the relevant repository.
Additionally, (and especially for non-locked references e.g. `?ref=master`), what may be valid today may not be valid later, and vice versa: I may be creating the kustomization before pushing.

One possible solution would be adding a flag such as `--validate=false` that just assumes the resource is valid and skips the network access

**Additional context**

  - `kustomize edit add` was added in #2768

**Comment by james-callahan** [comment]
/remove-lifecycle stale

@ChaturvediSulabh did you get anywhere with this?

**Comment by ChaturvediSulabh** [comment]
@james-callahan, Have received feedback just last week, working on implementing changes. Apologies for the delay, however, looking at the comments, this might take some more time.

**Comment by ChaturvediSulabh** [comment]
I'll try to finish the work by this weekend. Apologies for the delay.

**Comment by nikita-akuity** [comment]
Any progress on this?

**Comment by natasha41575** [comment]
Just approved https://github.com/kubernetes-sigs/kustomize/pull/5333, so closing this issue now. The `--no-verify` flag will be available in the next release.
