### ISSUE TITLE
Could service namePrefix be ommit?

### ISSUE THREAD

**Issue by liuhuiping2013** [kubernetes-sigs/kustomize#328]
our service user ${SERVICENAME}_SERVICE_HOST environment before, now i use kustomize, the env changed to ${namePrefix}${SERVICENAME}_SERVICE_HOST.

should i 
1. inject env in every POD with the ${namePrefix}, and 
2. modify source code for our service to read ${namePrefix}${SERVICENAME}_SERVICE_HOST?

but, if service resource can ommit namePrefix, then all things done.
else should i give up namePrefix?

**Comment by Liujingfang1** [comment]
`namePrefix` is optional, you can leave it as empty.
