### ISSUE TITLE
Refactor to allow more general name, kind, namespace changing 

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#3280]
After updating the GVKN/Ns, you should still be able to refer to the resource by either its original GVKN/Ns or the current one.

- [x] Add tests
- [x] Refactor PrefixSuffixTransformer and NameReferenceTransformer to use yaml annotations 
- [x] Refactor namespace changing to use yaml annotations
- [x] Allow name/kind changing via a patch

**Comment by natasha41575** [comment]
@Shell32-Natsu this is "in progress", thank you

**Comment by Shell32-Natsu** [comment]
@natasha41575 @monopole Do we have plan to support referring resource by a intermediate name instead of either current or original name? Requested in #3228

**Comment by natasha41575** [comment]
@Shell32-Natsu if we want to support that, then I can implement that after this refactoring is complete

**Comment by Shell32-Natsu** [comment]
@natasha41575 Thanks! It will be great to support it. And you may need to consider it when you refactor the NameReferenceTransformer
