### ISSUE TITLE
[Question] How to modify only specific resource

### ISSUE THREAD

**Issue by malcolm061990** [kubernetes-sigs/kustomize#3289]
Hi.
```
kustomize version
{Version:kustomize/v3.8.7 GitCommit:ad092cc7a91c07fdf63a2e4b7f13fa588a39af4f BuildDate:2020-11-14T20:06:26+00:00 GoOs:darwin GoArch:amd64}
```

I have several k8s yaml files in one dir that are handled kustomization:
```
├── base
│   ├── api.yaml
│   ├── kustomization.yaml
│   ├── react-app.yaml
│   ├── redis.yaml
└── overlays
    └── dev
        └── kustomization.yaml
```

overlays/dev/kustomization.yaml uses as a resource ../../base/kustomization.yaml
base/kustomization.yaml includes api.yaml, react-app.yaml and redis.yaml files as a resources

I want to update on k8s cluster only api without doing any changes to react-app and redis and without any changes to kustomization file.
For example, backend developers made hot fix to api. And I need to update only api.
How can I do that?

**Comment by Shell32-Natsu** [comment]
Sorry I don't get your point. If developer updates the api, you can just apply it and I suppose k8s cluster will do the update for you.

**Comment by malcolm061990** [comment]
> Sorry I don't get your point. If developer updates the api, you can just apply it and I suppose k8s cluster will do the update for you.

I mean I want to choose dynamically what resources I want to upgrade via kustomize.
For example, in one moment I want to upgrade only api, on other moment - only react-app.

**Comment by Shell32-Natsu** [comment]
Apply all the resources with api update, k8s cluster will compare them with current status and update. I cannot see the reason to use kustomize to do the selection.

**Comment by malcolm061990** [comment]
> Apply all the resources with api update, k8s cluster will compare them with current status and update. I cannot see the reason to use kustomize to do the selection.

You don't understand me.
Imagine production project that consists of 50 k8s entities. In that case we have kustomization file that handles all of 50 entities. But I don't want each time to upgrade via kustomize all 50 services (just don't want k8s cluster to compare them with its current statuses). In each moment I want to update only some specific services. As I understood, via kustomize it's impossible.

**Comment by Shell32-Natsu** [comment]
If all these files are all finally included in a single kustomization file, I don't think there is a way to build a subset of them in kustomize.

**Comment by malcolm061990** [comment]
> If all these files are all finally included in a single kustomization file, I don't think there is a way to build a subset of them in kustomize.

Thanks. Thats what I want to listen. For that case kustomize doesn't suit.
