### ISSUE TITLE
ask a general question

### ISSUE THREAD

**Issue by liuhuiping2013** [kubernetes-sigs/kustomize#329]
why prefix needed for kubernetes resources.

we already have 
1. kubectl context, kubernetes apiserver
2. namespace
to distinguish resources we ops, why resource name diff from others again.

thanks for your response.

**Comment by Liujingfang1** [comment]
`nameprefix` provides the flexibility to change the resource names. In the base overlay workflow, for different variant overlays(dev, prod), we can add different nameprefixes. Then the resources in different overlays will have different names and they can be deployed into the same namespace.
 If you prefer to put different overlays with different namespaces and leave the resource name untouched, you can also do that.

**Comment by liuhuiping2013** [comment]
thanks very much, use namespace instead of namePrefix will make diff view more clear.
