### ISSUE TITLE
Adding labels only to `.metadata.labels`

### ISSUE THREAD

**Issue by mikebryant** [kubernetes-sigs/kustomize#330]
I'd like to be able to add labels to the metadata of all objects, without them being part of the selectors.

One use case would be in our deployment pipeline, adding a label of the current git commit hash, so we can easily see which pipeline actually ran, trace back issues, stuff like that.

Currently `commonLabels` applies to selectors as well, which makes it unsuitable (As we don't want to force a rollout of all Deployments on every change, for example)

Is this something kustomize can/should support? Presumably using a different field name to `commonLabels`.

**Comment by Liujingfang1** [comment]
We will consider supporting this use case when design #91. It should provide an approach for users to add or remove different fields that they want to kustomize by transformers.

**Comment by Liujingfang1** [comment]
@mikebryant I'm thinking if `annotations` work for this case. Any ideas?

**Comment by mikebryant** [comment]
@Liujingfang1 I think that would work for the use-case I mentioned.

**Comment by Benjamintf1** [comment]
I don't think that would work for our use-case. 

Specifically, we are deploying based on some labels, this includes a common label that is un-applied via patch from specific resources(to prevent from deleting certain resources).

**Comment by mylokin** [comment]
Supporting this kind of functionality would be really neat. I was going to implement dangling resources cleanup (that were left after prev. deployments) using `commonLabels`, but found this to be impossible because labels are propagated into selectors.

**Comment by jbrette** [comment]
@mylokin @Benjamintf1 @mikebryant 

Please have a look at:
- [KEP: Kustomize FieldSpec skip ](https://github.com/kubernetes/enhancements/pull/1232)
- [PR: Skip kustomize transformers for paths](https://github.com/kubernetes-sigs/kustomize/pull/1491)
- The PR seems to address the issue as demonstrated [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0330)

**Comment by sebastiansirch** [comment]
Just in case someone is looking for a workaround: Here is an example of a transformer to add labels only to the metadata block. https://github.com/viadee/kustomize-examples/tree/master/overlays/custom-metadata-labels
