### ISSUE TITLE
Eliminate checking FlagEnableKyamlDefaultValue in tests

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#3304]
`plugin/builtin/patchstrategicmergetransformer/PatchStrategicMergeTransformer_test.go` and other tests have been modified to pass regardless of the value of FlagEnableKyamlDefaultValue, using `if` statements.

Once all these branches are eliminated, the kyaml and apimachinery code paths provide the same results (with respect to the tests).

This is probably the last blocked for  #2506

**Comment by Shell32-Natsu** [comment]
Great news!

**Comment by monopole** [comment]
To find remaining places needing attention, 

```
find ./ -name "*.go" | xargs grep IfApiMachineryElseKyaml 
find ./ -name "*.go" | xargs grep FlagEnableKyamlDefaultValue 
```

blocking issue (needs a fix)

 * [WNode.GetFieldValue doesn't understand arrays](https://github.com/kubernetes-sigs/kustomize/issues/3396)

issues with workarounds (these only happen with multiple patches at the same level which target the same resource).

 * [Patch conflation shouldn't use patching to merge patches](https://github.com/kubernetes-sigs/kustomize/issues/3394)
   workaround is don't patch at the same level with multiple distinct patches - instead use an overlay

 * kyaml code paths don't report conflicts in user specified patches; instead last patch wins
   workaround (if desired) same as above if the "last patch wins" result is undesireable.

unclear if desirable or not

* kyaml and apimachinery code paths have different behavior around quoting (or removing quotes) from bare int and bool
  primitives.

**Comment by monopole** [comment]
Per

```
clear; find ./ -name "*_test.go" | xargs egrep --before-context=2 "FlagEnableKyamlDefaultValue|IfApiMachinery"
```

Only remaining open and sorta painful issue is  #3394.

I'm in favor of proceeding with #2506 and fixing remaining issues in a pure kyaml world.

**Comment by monopole** [comment]
I'm calling this done.  All remained branching has been marked as OK, and the k8s.io deps are being removed.
