### ISSUE TITLE
Please allow logging of transformations

### ISSUE THREAD

**Issue by c10l** [kubernetes-sigs/kustomize#3307]
**Is your feature request related to a problem? Please describe.**

I need to understand why after a Kustomize upgrade one of my transformations stopped working. Without knowing what Kustomize is trying to do I'm left chasing changelogs and sparse documentation, and a lot of trial and error.

**Describe the solution you'd like**

A command-line argument that outputs useful messages about how Kustomize rendered the final YAMLs.

**Additional context**

In this particular instance, I have a `patchesJson6902` transformation that used to be applied correctly but now is just skipped. Nothing on the code has changed, the only difference is the Kustomize version.

Also please see https://github.com/kubernetes-sigs/kustomize/issues/1512

**Comment by Shell32-Natsu** [comment]
Sorry about that, to unblock you you can try to build kustomize from source code and debug it.

**Comment by Shell32-Natsu** [comment]
@monopole Maybe this is a good place to have a comment about the logging in kustomize.
