### ISSUE TITLE
no matches for OriginalId apps_v1_Deployment|~X

### ISSUE THREAD

**Issue by hmthoo** [kubernetes-sigs/kustomize#3317]
description：
Two group of the same files, The label is different. one set can be build, and the other indicates this error.

error info:
```
Error: no matches for OriginalId apps_v1_Deployment|~X|proxima; no matches for CurrentId apps_v1_Deployment|~X|proxima; failed to find unique target for patch apps_v1_Deployment|proxima
```

kustomize version:
```
# kustomize version
{Version:kustomize/v3.8.7 GitCommit:ad092cc7a91c07fdf63a2e4b7f13fa588a39af4f BuildDate:2020-11-11T23:19:38Z GoOs:darwin GoArch:amd64}
```

**Comment by Shell32-Natsu** [comment]
Please provide an example of the files that can reproduce this issue.

**Comment by hmthoo** [comment]
example: [https://github.com/hmthoo/kustomize](url)

**Comment by Shell32-Natsu** [comment]
Cannot reproduce. 

```
❯ kustomize build mamba-stable/overlays/canary
Error: trouble configuring builtin PatchStrategicMergeTransformer with config: `
paths:
- env_patch.yaml
- memorylimit_patch.yaml
- volumes_patch.yaml
`: evalsymlink failure on '/usr/local/google/home/donnyxia/kustomize_test/issue3317/kustomize/mamba-stable/overlays/canary/env_patch.yaml' : lstat /usr/local/google/home/donnyxia/kustomize_test/issue3317/kustomize/mamba-stable/overlays/canary/env_patch.yaml: no such file or directory
```
These 2 patches are not included
```
- env_patch.yaml
- memorylimit_patch.yaml
```
If I delete them from kustomization, the build works without issue.

**Comment by hmthoo** [comment]
> Cannot reproduce.
> 
> ```
> ❯ kustomize build mamba-stable/overlays/canary
> Error: trouble configuring builtin PatchStrategicMergeTransformer with config: `
> paths:
> - env_patch.yaml
> - memorylimit_patch.yaml
> - volumes_patch.yaml
> `: evalsymlink failure on '/usr/local/google/home/donnyxia/kustomize_test/issue3317/kustomize/mamba-stable/overlays/canary/env_patch.yaml' : lstat /usr/local/google/home/donnyxia/kustomize_test/issue3317/kustomize/mamba-stable/overlays/canary/env_patch.yaml: no such file or directory
> ```
> 
> These 2 patches are not included
> 
> ```
> - env_patch.yaml
> - memorylimit_patch.yaml
> ```
> 
> If I delete them from kustomization, the build works without issue.

sry. In fact，the original file include ”- env_patch.yaml
- memorylimit_patch.yaml“， i just forget delete in example.

The details are like this. When i build "mamba-canary" is ok, then the build "mamba-stable" error,  like 
![image](https://user-images.githubusercontent.com/42607426/101710331-3614bc00-3acc-11eb-854d-ec1daa16ff1d.png)
