### ISSUE TITLE
Remote loads taking too long

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#3333]
Appears related to new use of go-getter, followed by older git clone method.
May have started at PR  #3287

Had to add `--blockTimeOut 9m` (increased from default of 1m)  to ` hack/testExamplesAgainstKustomize.sh` to avoid repeatable timeouts in `examples/remoteBuild.md` test.

**Comment by monopole** [comment]
Tests that pass/fail on the basis of timeout length are generally a bad idea, but these are e2e tests and by definition cannot use mocks.  Something  has changed here; might need a binary search on the prs but checking before / after  #3287 first makes sense.

**Comment by Shell32-Natsu** [comment]
I think we should try to solve the timeout issue (maybe update the go-getter again or something). We can keep this issue open to track remote timeout problem.
