### ISSUE TITLE
PersistentVolume should not add metadata.namespace

### ISSUE THREAD

**Issue by liuhuiping2013** [kubernetes-sigs/kustomize#334]
PersistentVolume is cluster resource, like clusterrole etc, with no limitation for namespace.
so kustomize build should ommit "namespace" define in kustomization.yaml for cluster resources.

**Comment by Liujingfang1** [comment]
Thank for reporting this. Will fix it.

**Comment by monopole** [comment]
Can associate namespace omission with a list of cluster resources.  This impacts softcoding.
