### ISSUE TITLE
Enable kyaml for krusty tests

### ISSUE THREAD

**Issue by Shell32-Natsu** [kubernetes-sigs/kustomize#3343]
We need to enable kyaml for krusty tests by changing https://github.com/kubernetes-sigs/kustomize/blob/deb2b21cbe7a1b19480478e229991ac11c5478fb/api%2Fkrusty%2Foptions.go#L53 to true.

**Comment by yashvardhan-kukreja** [comment]
Hi @Shell32-Natsu . This looks like a "good first issue" and I have been looking forward to start contributing to `kustomize`.

So, do you mind if I work on this PR? :)

**Comment by Shell32-Natsu** [comment]
Thanks a lot if you can take it.😄

**Comment by monopole** [comment]
Closed by the above prs
