### ISSUE TITLE
v3.9.0 regression - configMapGenerator `behavior: merge` is not working

### ISSUE THREAD

**Issue by aaaaahaaaaa** [kubernetes-sigs/kustomize#3345]
The `behavior: merge` option of the `configMapGenerator` is not functioning properly with 3.9.0. Instead, only the literals of the overlay are kept when building the manifest, and the literals of the base are ignored.

I just tested with 3.8.8 and the issue doesn't appear there.

**Comment by sass1997** [comment]
I do also have problem with the `configMapGenerator` `behavior: merge`. Especially when I do use `vars`. I prepared small test project for this. https://github.com/sass1997/kustomize-features

**Comment by Shell32-Natsu** [comment]
3.9.0 is an *alpha* version to enable kyaml for entire kustomize. We have found some issues in it and we will remove the release soon. If you have any issue in 3.9.0 just try 3.8.8 since the kyaml is the only difference.

**Comment by max-sixty** [comment]
Is 3.9.0 tagged as an alpha release? It's now the default on brew, which is unfortunate since it's not easy to install older releases on brew.

ref https://github.com/Homebrew/homebrew-core/pull/66678

**Comment by Shell32-Natsu** [comment]
We have removed 3.9.0 release (but the tag is still there).

**Comment by ismaeIfm** [comment]
brew installs the version 3.9.0 and its broken

**Comment by ismaeIfm** [comment]
https://formulae.brew.sh/formula/kustomize

**Comment by monopole** [comment]
I think this was fixed in #3379

Will  be releasing 3.9.1 early this week (hopefully today)
