### ISSUE TITLE
JSON Patch should fail if no object matches

### ISSUE THREAD

**Issue by mxey** [kubernetes-sigs/kustomize#335]
When using JSON Patches, Kustomize only logs a warning when there is no target object:

`2018/09/10 16:27:42 Couldn't find any object to apply the json patch __Ingress___foo.yaml, skipping it.`

For strategic merge patches, Kustomize will fail if there is no target object:
`Error: failed to find an object with schema.GroupVersionKind{Group:"apps", Version:"v1", Kind:"Deployment"} to apply the patch` 

I think JSON Patch should match that behavior.

**Comment by Liujingfang1** [comment]
Sounds good. Will fix it.
