### ISSUE TITLE
How to use kustomize with a Private Docker Registry?

### ISSUE THREAD

**Issue by lswith** [kubernetes-sigs/kustomize#336]
I was curious how to use a private Docker registry with kustomize? I was thinking that it would have to be a common base for everything which needed the docker registry secret to be set?

It would be nice to have this documented as well.

**Comment by Liujingfang1** [comment]
Based on this document https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
you need to create a secret with type `docker-registry` and use that secret in your pods.

With Kustomize, as you mentioned, putting this secret into a common base for everything is a reasonable way.
