### ISSUE TITLE
Fails to build from base with go-getter URL

### ISSUE THREAD

**Issue by epcim** [kubernetes-sigs/kustomize#3378]
**Describe the bug**

/kind bug

- Fail to build from go-getter URL
- Works if the repo si cloned locally

**Files that can reproduce the issue**

kustomization.yaml:

```
bases:
- https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v1.8.1
#- argo-cd/manifests/cluster-install              ## NOTE, this actually works

```

**Expected output**

buid render manifests

**Actual output**

```
Error: accumulating resources: accumulateFile "accumulating resources from 'https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v1.8.1': YAML file [https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v1.8.1] encounters a format error.\nerror converting YAML to JSON: yaml: line 159: mapping values are not allowed in this context\n", accumulateDirector: "couldn't make target for path '/private/var/folders/wg/1plf6lvs5nl2hvpxvnrgbxf40000gn/T/kustomize-137672667/repo': unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/private/var/folders/wg/1plf6lvs5nl2hvpxvnrgbxf40000gn/T/kustomize-137672667/repo'"
```

**Kustomize version**

any latest from master

**Platform**

OSX

**Additional context**

- might be caused by some symlinks (not yet debugged)

**Comment by Shell32-Natsu** [comment]
I believe this is caused by go-getter silently failed to get the repo.

**Comment by epcim** [comment]
correct, fixed later

**Comment by Amit-Prajapati** [comment]
May I know what was the exact fix? facing exact same issue.

**Comment by aashrit93** [comment]
I too am facing the same error . My observations  :
 if i use kubectl apply -k <path to kustomization.yaml> or kustomize build <path to kustomization.yaml> i see the expected output
however when i try to use the same kustomize file with gitops ( setup using flux install, flux create source and flux create kustomization ) i see the below error during flux kustomization creation 
        * accumulateFile error: "accumulating resources from 'https://aashrit93@github.com/aashrit93/kustomize_bases.git/bases/helloworld': YAML file [https://aashrit93@github.com/aashrit93/kustomize_bases.git/bases/helloworld] encounters a format error.\nerror converting YAML to JSON: yaml: line 159: mapping values are not allowed in this context\n"
        * loader.New error: "git cmd = '/usr/bin/git fetch --depth=1 origin HEAD': exit status 128"
        *
The usecase is quite simple , its to have a kustomize setup where the
The overlays repo refers to another repository that contains the 'bases'

**Comment by Shell32-Natsu** [comment]
@aashrit93 I suppose this is because of the differences between the kustomize versions.
