### ISSUE TITLE
Remote Url for Overlay not working

### ISSUE THREAD

**Issue by lswith** [kubernetes-sigs/kustomize#338]
I've used the remote url to point to a github repo and then pointed to a subdirectory of that to target a specific overlay.

It seems that because go-getter doesn't checkout the full repo into the target location (https://github.com/hashicorp/go-getter#subdirectories) the overlay can't point to it's bases using the syntax:

```
bases:
  - ../../base/
```

**Comment by lswith** [comment]
I'm thinking that this function https://godoc.org/github.com/hashicorp/go-getter#SourceDirSubdir might need to seperate out the url from the sub dir before you can build the sub directory.

**Comment by Liujingfang1** [comment]
should be fixed by #339
