### ISSUE TITLE
CI & Release Process

### ISSUE THREAD

**Issue by pnovotnak** [kubernetes-sigs/kustomize#3381]
**Is your feature request related to a problem? Please describe.**

Y'all, I love kustomize for its ease of use. But I've had not one, not two but _three_ issues with kustomize releases producing broken output in the last year. **One was undetected and led to a major outage.**

**Describe the solution you'd like**

I would like to have the output of release candidates verified against a comprehensive suite of test cases before a release is cut for that version.

**Describe alternatives you've considered**

Other alternatives could include simply releasing beta or alpha versions and not claiming fitness for those versions until they have had some time to be verified by the community.

**Additional context**

Again, I love kustomize and really appreciate all the work you are doing (whether or not it's paid)! But I would personally really appreciate more care in the release process. I think that automated CI could have caught all three of my cases: 

- The first two we experienced were issues with dual protocol ports which were defined on kubernetes bootstrap manifests.
- [The last issue](https://github.com/kubernetes-sigs/kustomize/issues/3345) would probably manifest if the samples were run.

I or my company could potentially contribute some one-time effort if that is what is required to make this happen.

**Comment by Shell32-Natsu** [comment]
We do run all the tests before we release but in my memory most of the issue about release cannot be checked by tests, like the installation script fails when we add ARM releases. It's better to have alpha and beta release IMO.

**Comment by pnovotnak** [comment]
I think I cooked this a little spicier than I meant to. I'm sorry about that. Y'all do indeed have a good deal of testing which is definitely obvious if you look at any build.

I just don't understand how issues like this one https://github.com/kubernetes-sigs/kustomize/issues/2767 could appear, be fixed, then appear again all without a mention of it in the release notes. This might seem like a trivial detail but for instance kube-dns uses UDP and TCP together so the behavior changes there are very dangerous for cluster operators using that tool to manage kube-dns.

Regarding the latest issue, https://github.com/kubernetes-sigs/kustomize/issues/3345, I feel there ought to have been an e2e test that prevented a merge (or at least prompted a very fat fitness warning on the release).

For both issues, it was either a known issue that wasn't mentioned in the notes, or an unknown issue for lack of tests. Either is bad for an end user like me.

**Comment by Shell32-Natsu** [comment]
We added the commit history in the release note. Yeah, we need to do better in release notes.

For #3345, actually we did expect there will be issues in 3.9.0 since there was a huge change (migrating to kyaml and getting rid of apimachinery). Actually 3.9.0 should be marked as alpha. That's why I said we probably need to have a alpha/beta release.

**Comment by pnovotnak** [comment]
Yeah FWIW I think alpha / beta releases would be fine for that and I'm personally happy to test beta channels on my workstation (it's easier to grok `kubectl diff` output locally).
