### ISSUE TITLE
docs: primary cta button fails

### ISSUE THREAD

**Issue by balibebas** [kubernetes-sigs/kustomize#3423]
A primary CTA on the Kustomize.io website is failing. I realize the docs are being moved to SIGs but still, this is a primary CTA used to describe how to use Kustomize. It needs to work for this project to look remotely mature.

**Describe the bug**

<img width="743" alt="Screen Shot 2021-01-06 at 1 30 41 PM" src="https://user-images.githubusercontent.com/65664227/103733130-f803ad00-5023-11eb-8f26-15d0ea642683.png">

**Files that can reproduce the issue**

kustomize.io website homepage

**Comment by Shell32-Natsu** [comment]
kustomize.io is not maintained by us.

**Comment by balibebas** [comment]
> kustomize.io is not maintained by us.

That may be true but the presence of it affects your website UX and therefore falls into your purview. At a minimum, I'd expect maintainers to open an upstream issue and track the correction. And if it's possible there's a better place this issue couldn've been opened, you should point contributors like me to the correct place to fix the actual issue.

**Comment by Shell32-Natsu** [comment]
I cannot provide the instructions to fix this web page since I have no idea about it. I am in the same place with you😀. What I know is from the footer of the webpage, it's maintained by https://www.replicated.com.
