### ISSUE TITLE
configMapGenerator please do not generate creationTimestamp

### ISSUE THREAD

**Issue by liuhuiping2013** [kubernetes-sigs/kustomize#344]
all configmap generated have this field:
> creationTimestamp: null

but i use https://github.com/weaveworks/kubediff, compare kustomization build with k8s, will print a lot of errors like:
> .metadata.creationTimestamp: 'None' != '2018-09-10 03:42:41'

i think this issue should submit here...

**Comment by Liujingfang1** [comment]
What does the diff look like if you remove 
` ``
creationTimestamp: null
```
I guess you will still see the diff containing `createTimestamp` since `'2018-09-10 03:42:41'` is only available from the kubernetes server side.

**Comment by liuhuiping2013** [comment]
if i run follow command in my git repo, then push
>sed -i '/creationTimestamp/d' *

then all errors disappeared.

**Comment by Liujingfang1** [comment]
I see. I did a simple comparison between adding a configmap.yaml as resource and generating a configmap by ConfigMapGenerator. `CreationTimestamp` only shows up in generated configmaps. This is a inconsistency and I think we should fix it.
It might be related to marshalling part. @liuhuiping2013 Would you like to investigate the cause and fix it?

**Comment by liuhuiping2013** [comment]
i googled, if it cause by
https://github.com/kubernetes/kubernetes/pull/53464

so, we can not or should not resolve it in kustomize?
