### ISSUE TITLE
Allow transformer plugins to generate resources

### ISSUE THREAD

**Issue by KnVerey** [kubernetes-sigs/kustomize#3448]
**Is your feature request related to a problem? Please describe.**

Today, Kustomize configuration functions can invoked from a `Kustomization` using either the `generators` or the `transformers` fields. There is no field that supports a function that both generates _and_ transforms resources. This limits the ability to build flexible abstraction-based functions that may need to do both of these things. It also impedes the use of the pattern where a function intelligently detects whether a required resource already exists in the set and either generates it or augments it accordingly.

**Describe the solution you'd like**

- A transformer can optionally generate resources, and if it does, those resources are added to the resource map.
  - To guarantee that a given transformation (e.g. common labels) will be applied to *all* resources, an overlay Kustomization should be used.
- For backwards compatibility, we can require that resources generated by a transformer have a specific annotation. Unannotated resources would then continue to be rejected as they are today.
  - Kustomize would need to expose two new environment variables to plugins it runs: one indicating that it is being invoked by Kustomize, and another indicating whether it is being run as a generator or as a transformer.
  - `sigs.k8s.io/kustomize/kyaml/fn/framework` should author this annotation automatically as appropriate, based on the value of these environment variables.

**Describe alternatives you've considered**

* Change the `generators` field to allow transformations. This would require bigger changes to the way the field works, i.e. invoking each generator in sequence and exposing previous results to each. 

* Do not change the fields, but expose environment variables to plugins so that they can determine Kustomize is invoking them as a transformer/generator. Then, plugins that need to do both types of work can be listed in both fields and perform the appropriate action at the appropriate time. This requires duplication in the `Kustomization` and does not support the pattern where the plugin detects whether or not generation is necessary. It also makes plugin implementation more complex. However, it is a minimal change to Kustomize and maintains the distinction between function types.

 
**Additional context**

I am interested in making a PR for the solution described if it, or something reasonably similar in scope, is agreed to.

**Comment by monopole** [comment]
[already]: https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/someteam.example.com/v1/calvinduplicator/CalvinDuplicator.go

Thanks for writing this up, and offering to make things better.

A curt answer would be: transformers can [already] generate resources, so let's close this.

But clearly the docs, api comments, field comments etc. need improvement.  And larger things, e.g. hooks for aspect orient programming, clarification of extension mechanism, etc.  what else?   It's far from perfect.

**Comment by monopole** [comment]
oops, just went out for a walk and realized that you're right -i think  there was a hidden bug over a range of recent kustomize releases that prevented a transformer from changing the `ResMap` size (adding or removing).

A `kyaml` function called `ApplyToJson` was added as part of a refactor away from `apimachinery`.  It demanded equal sized input and output for a resource list.

That function is no longer in the code path at head, where `kyaml` use is enabled.

The plugin example i referred to above didn't exist to be part of the tests (it is now), so the bug went unseen.

FWIW, nothing in the api ever prevented a transformer from adding or removing resources - this was just a bug.

**Comment by KnVerey** [comment]
Thanks for the response! The example that prompted this issue should indeed be functionally equivalent to your CalvinDuplicator (starts off with some resources, emits those and a few extras), but I'm still encountering errors with it after building kustomize from current head and invoking `build` with `--enable_kyaml`.

These errors that made me incorrectly assume (sorry) that generation was unsupported do seem to have to do with ResMap modification: `Error: the transformer api [filtered] should not remove annotation kustomize.config.k8s.io/id`, which appears to come from [UpdateResMapValues](https://github.com/kubernetes-sigs/kustomize/blob/1d4b3fa36c8918ad884c7aaa6a055fa2d0fa9bf9/api/internal/plugins/utils/utils.go#L149). That code does appear to expect all resources to be annotated and the input and output resources to be equal. FWIW, if I fake the annotations for the purposes of experimentation, I then encounter errors about there being no match in the original set: `Error: unable to find unique match to [filtered]`.

**Comment by KnVerey** [comment]
@monopole did you have a chance to look at my last comment? I'm glad to hear that this is just a bug, but it I tried the test I described again this morning, and I'm still getting the same error with the latest master branch. I'm also able to verify that the same error occurs for exec-based functions. My theory is that the calvinduplicator test isn't reproducing the bug because it is a `.so`-based plugin that manipulates the `ResMap` directly and generates its resources with a `DeepCopy` (inheriting the bookkeeping annotations).

A simple way to reproduce the error is to modify `plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go` as follows:

```diff
Index: plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go
===================================================================
diff --git a/plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go b/plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go
--- a/plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go	(revision d88d902c25b26d679df4f27af90df3c7d1e775f6)
+++ b/plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap_test.go	(date 1612387112007)
@@ -14,13 +14,13 @@
 		PrepExecPlugin("someteam.example.com", "v1", "BashedConfigMap")
 	defer th.Reset()
 
-	m := th.LoadAndRunGenerator(`
+	m := th.LoadAndRunTransformer(`
 apiVersion: someteam.example.com/v1
 kind: BashedConfigMap
 metadata:
   name: whatever
 argsOneLiner: alice myMomsMaidenName
-`)
+`, "")
 	th.AssertActualEqualsExpected(m, `
 apiVersion: v1
 data:
```

Result:
```bash
=== RUN   TestBashedConfigMapPlugin
    harnessenhanced.go:120: Err: the transformer <hidden>/kustomize/plugin/someteam.example.com/v1/bashedconfigmap/BashedConfigMap should not remove annotation kustomize.config.k8s.io/id
--- FAIL: TestBashedConfigMapPlugin (0.24s)

FAIL
```

**Comment by KnVerey** [comment]
@monopole I attempted a fix for this: https://github.com/kubernetes-sigs/kustomize/pull/3534. I also noticed that deletion wasn't working either, so I addressed that as well. PTAL.

**Comment by monopole** [comment]
Ah that makes sense.  Thanks!

**Comment by monopole** [comment]
PS, will build a new release with this after friday.
