### ISSUE TITLE
helmchartinflationgenerator --include-crds

### ISSUE THREAD

**Issue by prios-peter-olivo** [kubernetes-sigs/kustomize#3451]
When using the helmchartinflationgenerator to generate a Helm 3 chart that includes a crds directory the helm inflation does not include the crds.

I would like to have a extraArgs value added to the generator so helm flags can be added, in this case --include-crds

Helm 3 charts are inflated with crds. 

Currently I use bash script that is pulling the crds without kustomize.

**Comment by Shell32-Natsu** [comment]
The plugin should have supported `extraArgs` option. https://kubectl.docs.kubernetes.io/guides/extending_kustomize/builtins/#_helmchartinflationgenerator_

**Comment by daurnimator** [comment]
While `extraArgs` is a useful escape hatch, shouldn't we add first party support for options like `--include-crds`?

**Comment by Shell32-Natsu** [comment]
@daurnimator It's ok to have it supported natively. We are happy to merge such PR.

**Comment by daurnimator** [comment]
Could you reopen this issue and accept it?

**Comment by Shell32-Natsu** [comment]
We will add new option for `--include-crds`. Tracked by #3819
