### ISSUE TITLE
helmchartinflationgenerator --include-crds

### ISSUE THREAD

**Issue by prios-peter-olivo** [kubernetes-sigs/kustomize#3452]
When using the helmchartinflationgenerator to generate a Helm 3 chart that includes a crds directory the helm inflation does not include the crds.

I would like to have a extraArgs value added to the generator so helm flags can be added, in this case --include-crds

Currently I use bash script that is pulling the crds without kustomize.

**Comment by Shell32-Natsu** [comment]
Duplicate of #3451

**Comment by prios-peter-olivo** [comment]
My issue was related to using kustomize v3.8.7 instead of v.3.8.8

**Comment by Shell32-Natsu** [comment]
The `extraArgs` was introduced in 3.8.8.
