### ISSUE TITLE
https://kustomize.io dead link under "kubectl Usage" tab

### ISSUE THREAD

**Issue by mancubus77** [kubernetes-sigs/kustomize#3456]
This link leading to non existed document
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/16170560/104588215-29cbe200-56bc-11eb-9daf-1edd0d8f827c.png">

https://kubectl.docs.kubernetes.io/pages/app_management/introduction.html
<img width="938" alt="image" src="https://user-images.githubusercontent.com/16170560/104588437-77484f00-56bc-11eb-902a-32af37f155ad.png">

**Comment by breezybaldwin** [comment]
@mancubus77 this has been fixed; thanks for bringing it to our attention!

**Comment by Shell32-Natsu** [comment]
Thanks @breezybaldwin
