### ISSUE TITLE
Support replace apiVersion dynamiclly

### ISSUE THREAD

**Issue by Betula-L** [kubernetes-sigs/kustomize#346]
I have two cluster with different kubelet version, i.e. 1.7.9 and 1.10.3

apiVersion of resource `ClusterRole` is also different in this two cluster:
* `rbac.authorization.k8s.io/v1beta1` - `kubelet 1.7.9` 
* `rbac.authorization.k8s.io/v1` - `kubelet 1.10.3` 

Thus, i should maintain two yaml even i use kustomize,
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
```
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
```
```
whereas, the content of this two yaml is same expect `apiVersion`.

**Comment by Liujingfang1** [comment]
Same request as https://github.com/kubernetes-sigs/kustomize/issues/61

**Comment by Liujingfang1** [comment]
close as duplicate.
