### ISSUE TITLE
base -- or -- include

### ISSUE THREAD

**Issue by liuhuiping2013** [kubernetes-sigs/kustomize#348]
i split kubernetes resources by a lots of dirs which contains kustomization.yaml.
every time we upgrade image tags, we have to modify several kustomization.yaml files just for imagetag.
so, can all kustomization.yaml include one special file just maintain the image tags for whole kubernetes environment?

In a word, i want "include" directive just like nginx, apache, sysctl.conf etc.
If not impractical, just for image tag batch modify, have any suggestions?
thanks.

**Comment by Liujingfang1** [comment]
Do you use the base overlay workflow? If you mean adding imagetags in multiple overlays, you can do that in base instead.

**Comment by liuhuiping2013** [comment]
something i forget is, deployment image registry in overlays diff from base. just like:
> base: registry1/usersvc:0.1-rc
> overlyas/alpha: registry2/usersvc:0.1

so, imagetag for registry2 appear in base have no effect.

**Comment by larslevie** [comment]
I agree with @khrisrichardson that an option to inherit things like `namespace` and `commonLabels` would help avoid duplication and the eventual out-of-sync issues that will occur. This is especially important because the answer from the Kustomize maintainers to questions about edge cases is almost universally "this can be accomplished with a more sophisticated layout."

**Comment by thecopy** [comment]
This is also an issue for us. We would like to have a kustomize.yml at the root of our repo containing common properties like project, git-repository, project-name etc.

**Comment by nabadger** [comment]
Agree on this - would love commonLabels (even commonAnnotations perhaps) to get merged here.

There's an awful lot of duplication we have in place at the moment.

**Comment by mnpenner** [comment]
I don't know what the purpose of having a base `kustomization.yaml` file is if nothing actually gets inherited? I'm having to duplicate pretty much everything into all my kustomization files.
