### ISSUE TITLE
Kustomize doesn't replace variables in (service) annotations

### ISSUE THREAD

**Issue by ajbouh** [kubernetes-sigs/kustomize#350]
FIrst, I'm really liking kustomize!

I'm using kustomize to (among other things) deploy services with ambassador. Ambassador configuration occurs via annotations on services. One case that doesn't work at all in kustomize is [configuring authentication](https://www.getambassador.io/user-guide/auth-tutorial#2-configure-ambassador-authentication).

Based on my research, this is because there is no logic to walk all annotation values and replace any `$(...)` expressions it encounters. I have a local patch that addresses this. Would this be valuable to contribute as a PR?

**Comment by Liujingfang1** [comment]
@ajbouh We are currently working on a design for #91. It will provide an approach for users to control what extra paths a tranformation should cover. For your use case, the transformation involved is the variable reference transformation, which is to resolve the variables. You will need to add the path pointing to `annotations` for Service type.

**Comment by ajbouh** [comment]
Right, I also needed to add:

```go
func (rv *refvarTransformer) Transform(resources resmap.ResMap) error {
	...
	case map[string]interface{}:
		mp := map[string]interface{}{}
		for k, v := range in.(map[string]interface{}) {
			mp[k] = expansion.Expand(v.(string), mappingFunc)
		}
		return mp, nil
	...
```

While it makes sense that you want to allow users to specify arbitrary substitutions, I think it's surprising out of the box behavior that only *some* annotations support variable references, but others do not.

I have things working locally, so this issue is an effort to smooth things out for others!

**Comment by Liujingfang1** [comment]
Vars was designed to inject names and info from one object to another object's container. It is not for arbitrary substitution. There is a workaround, which will be documented under #401.
