### ISSUE TITLE
Docs should clearly mention issues with remote resources

### ISSUE THREAD

**Issue by amisevsk** [kubernetes-sigs/kustomize#3505]
**Describe the bug**

The [docs](https://kubectl.docs.kubernetes.io/references/kustomize/resource/) suggest that resources can be files, paths, or URLs interchangeably. However, due to what seems to be an issue in go-getter (see also: https://github.com/kubernetes-sigs/kustomize/issues/2538), behaviour when trying to resolve remote resources is inconsistent and confusing -- e.g. [this comment](https://github.com/kubernetes-sigs/kustomize/issues/2538#issuecomment-729629437). The referenced issue has existed since May 2020

**Files that can reproduce the issue**

Reproduces with examples from this repo, e.g. https://github.com/kubernetes-sigs/kustomize/blob/master/examples/multibases/production/kustomization.yaml

```
kustomize build github.com/kubernetes-sigs/kustomize/examples/multibases/production/
```

**Expected output**

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: prod-myapp-pod
spec:
  containers:
  - image: nginx:1.7.9
    name: nginx
```

**Actual output**

Failure cases output is
```
Error: accumulating resources: 2 errors occurred:
	* accumulateFile error: "accumulating resources from '../base': evalsymlink failure on '/tmp/kustomize-015490485/base' : lstat /tmp/kustomize-015490485/base: no such file or directory"
	* loader.New error: "error loading ../base with git: url lacks host: ../base, dir: evalsymlink failure on '/tmp/kustomize-015490485/base' : lstat /tmp/kustomize-015490485/base: no such file or directory, get: invalid source string: ../base"



```

| URL | Works? | Notes |
|---|---|---|
| github.com/kubernetes-sigs/kustomize/examples/multibases/production | not working | syntax in docs without `?ref` |
| github.com/kubernetes-sigs/kustomize/examples/multibases/production?ref=master | works | syntax in docs |
| git::github.com/kubernetes-sigs/kustomize/examples/multibases/production | not working | `go-getter` force protocol to be git |
| git::github.com/kubernetes-sigs/kustomize/examples/multibases/production?ref=master | not working | `go-getter` force protocol to be git with `?ref` |
| https://github.com/kubernetes-sigs/kustomize/examples/multibases/production | works | not listed in docs |
| https://github.com/kubernetes-sigs/kustomize/examples/multibases/production?ref=master | works | not listed in docs |

**Kustomize version**

```
{Version:kustomize/v3.9.2 GitCommit:e98eada7365fc564c9aba392e954f306a9cbf1dd BuildDate:2021-01-17T17:44:16Z GoOs:linux GoArch:amd64}
```

**Platform**

Linux; Fedora 33

**Additional context**

**Comment by monopole** [comment]
Help wanted!

**Comment by amisevsk** [comment]
Should be resolved be https://github.com/kubernetes-sigs/kustomize/pull/3586 in v4

Never did get around to writing that doc :)
