### ISSUE TITLE
Is there a reason for PrefixSuffixTransformer not having a target/name attribute?

### ISSUE THREAD

**Issue by peteroruba** [kubernetes-sigs/kustomize#3508]
Is there a particular reason why PatchTransformer has a "target/name" attribute and PrefixSuffixTransformer doesn't? I am trying to apply transformations to only a subset of my objects, which I can narrow down with a RegEx in the target/name attribute. However, that only works with PatchTransformer, but it doesn't with PrefixSuffixTransformer.

Thanks

**Comment by Shell32-Natsu** [comment]
You can use fieldSpecs like [here](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/builtins/#_prefixsuffixtransformer_).

**Comment by peteroruba** [comment]
@Shell32-Natsu thanks for your response, however, I'm not sure we're on the same page, so I'd like to add a few more details.

Below is what I have at the moment. I restrict the top transformation to "argocd" and "gitlab" named ArgoCD applications only and would like to do the same kind of regex restriction with the PrefixSuffixTransformer as well. However, adding the regex under target/name has no effect and the PrefixSuffixTransformer ss applied to all Argo applications.

apiVersion: builtin
kind: PatchTransformer
metadata:
  name: application-apply-branch
patch: '[{"op": "replace", "path": "/spec/source/targetRevision", "value": "test"}]'
target:
  group: argoproj.io
  kind: Application
  name: ^argocd$|^gitlab$

---
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: foo
target:
  group: argoproj.io
  kind: Application
  name: ^argocd$|^gitlab$    # <- this has no effect
fieldSpecs:
  - path: spec/source/path
prefix: overlays/test/

**Comment by Shell32-Natsu** [comment]
Currently I think the `target` field is only supported in PatchTransformer. For other transformers you can only use `fieldSpecs` now. If you want to do prefix/suffix and use regex to select resource name you may have to implement your own plugin.

https://kubectl.docs.kubernetes.io/guides/extending_kustomize/execpluginguidedexample/

**Comment by monopole** [comment]
PTAL at  https://github.com/kubernetes-sigs/kustomize/blob/master/api/krusty/customconfigofbuiltinplugin_test.go

**Comment by monopole** [comment]
BTW, @peteroruba the documented examples clearly need some help!  Feel free to send PRs.

The unit tests in `api/krusty` have loads of examples, but there's no overview or guide to them.

**Comment by peteroruba** [comment]
@karlschriek Nope. Sorry for not being able to help here.
