### ISSUE TITLE
Ability to ignore files referenced in kustomization.yaml that may be missing

### ISSUE THREAD

**Issue by font** [kubernetes-sigs/kustomize#3515]
**Is your feature request related to a problem? Please describe.**

I'm trying to use `kustomize build` to generate resources from a URL and receive the following error:

```shell
→ kustomize build github.com/open-policy-agent/gatekeeper/config/overlays/mutation_webhook/?ref=v3.3.0
Error: accumulating resources: accumulateFile "accumulating resources from '../dev': '/tmp/kustomize-357849393/config/overlays/dev' must resolve to a file", accumulateDirector: "recursed accumulation of path '/tmp/kustomize-357849393/config/overlays/dev': trouble configuring builtin PatchStrategicMergeTransformer with config: `\npaths:\n- manager_image_patch.yaml\n`: evalsymlink failure on '/tmp/kustomize-357849393/config/overlays/dev/manager_image_patch.yaml' : lstat /tmp/kustomize-357849393/config/overlays/dev/manager_image_patch.yaml: no such file or directory"
```

This is caused by a [`patchesStrategicMerge` file](https://github.com/open-policy-agent/gatekeeper/blob/201a78d6096e048719395263b87618ecb5235409/config/overlays/dev/kustomization.yaml#L7-L8) that is missing because it gets generated by that repo's [`Makefile`](https://github.com/open-policy-agent/gatekeeper/blob/201a78d6096e048719395263b87618ecb5235409/Makefile#L249) before executing `kustomize build`.

**Describe the solution you'd like**

Would it be possible to have `kustomize build` be able to ignore files that may be missing? Perhaps this could be an optional flag that the `build` sub-command could accept.

**Describe alternatives you've considered**

I plan to investigate making changes to the target repo to try to have that `patchesStrategicMerge` file committed to prevent these issues.

**Additional context**

**Comment by Shell32-Natsu** [comment]
@monopole Do you think this feature request makes sense?
