### ISSUE TITLE
[Question] Possible license incompatibility issue with golangci/golangci-lint

### ISSUE THREAD

**Issue by bitscuit** [kubernetes-sigs/kustomize#3516]
The `api` module lists `github.com/golangci/golangci-lint` as a dependency https://github.com/kubernetes-sigs/kustomize/blob/api/v0.6.5/api/go.mod#L8, but `golangci-lint` is under the GPL-3.0 license https://github.com/golangci/golangci-lint/tree/v1.21.0. The entire `kustomize` project is under the Apache-2.0 license, so cannot include GPL-3.0 projects due to license incompatibility.

**Comment by Shell32-Natsu** [comment]
@monopole Can you take a look at this?

**Comment by monopole** [comment]
Thanks for asking.  That's not a library dependency.

See ./api/internal/tools/tools.go.  This is an install trick that gets the `go` tool to install a Go binary at a particular version (in this case a linter).  It presumably removes a step for contributors and cloud build environments.  

We used to do this with a shell script (maybe we still do, not sure).
