### ISSUE TITLE
patches ought to be prioritized in transformer precedence

### ISSUE THREAD

**Issue by khrisrichardson** [kubernetes-sigs/kustomize#352]
Image tag transformations aren't being applied to strategic merge patches. Given this hypothetical layout, I would expect the `bar` tag to be applied to both `foo` images, but I suspect the lack of precedence in the application of transformers results in the image tag transformation being applied prior to the patch transformation.

```bash
$ kustomize build overlays
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - image: foo
    name: c2
  - image: foo:bar
    name: c1
```

```bash
$ tree .
.
├── kustomization.yaml
├── overlays
│   ├── kustomization.yaml
│   └── pod.yaml
└── pod.yaml
```

```bash
$ cat kustomization.yaml
imageTags:
- name: foo
  newTag: bar
resources:
- pod.yaml
```

```bash
$ cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - image: foo
    name: c1
```

```bash
$ cat overlays/kustomization.yaml
bases:
- ..
patchesStrategicMerge:
- pod.yaml
```

```bash
$ cat overlays/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - image: foo
    name: c2
```

*Edit:* If I spew the contents of the data structures as the multi-transformer is iterated over, it would appear that this is not an order of operations issue, but rather another symptom of perhaps misguided expectations as described in https://github.com/kubernetes-sigs/kustomize/issues/348#issuecomment-422157647

**Comment by Liujingfang1** [comment]
@khrisrichardson In the example you give, `imageTags` is in the base and the strategic merge patch is in the overlay. This customization can't propagate from base to overlay.

**Comment by khrisrichardson** [comment]
Hi, @Liujingfang1. I realized that after submitting the issue. I will close this and post an update if I find an alternative that doesn't require duplicating parameters in kustomization files.
