### ISSUE TITLE
[Question] Is it possible to patch by name or matcher rather than position?

### ISSUE THREAD

**Issue by mnishizawa** [kubernetes-sigs/kustomize#3521]
In all the examples I see for referring to a value to replace with patches, the reference looks something like
`  path: /spec/templates/0/inputs/parameters/2/default`

To me this seems like a potential issue if someone were to move the original value from one position to another.  Is there a way to use the name or some other kind of identifier so the path could be independent of the position?

**Comment by Shell32-Natsu** [comment]
I assume you are talking about json patch. Unfortunately this path format is defined in the json patch RFC and kustomize just follows it.

**Comment by monopole** [comment]
#3492 talks about the general idea of grabbing data from some resource/field and writing it to some other field.

**Comment by natasha41575** [comment]
Closing this issue since the replacement transformer is now implemented (#3492). This will be available in an upcoming release.
