### ISSUE TITLE
[Question] Kustomize set image not working in combination with base/overlays setup

### ISSUE THREAD

**Issue by sebastianbuechler** [kubernetes-sigs/kustomize#3526]
I am using the official GKE Deployment script for Github Actions. In the end we have there:
```
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
```
This works fine when I use a basic ` kustomization.yaml` and the respective definition files. When I switch to base/overlays with the following folder structure the kustomize `edit set image` call fails to replace the new image:

```
+---kubernetes
|   +---base
|   |       deployment.yml
|   |       kustomization.yml
|   |       service.yml
|   |
|   \---overlays
|       +---prod
|       |       deployment.yml
|       |       kustomization.yml
|       |       service.yml
|       |
|       \---stage
|               deployment.yml
|               kustomization.yml
|               service.yml
```

How can I use `edit set image` when I have multiple files in this structure?

**Comment by Shell32-Natsu** [comment]
`edit set image` will set the image in the kustomization files in the *current working directory*. So you should cd into the directory and run it.

**Comment by sebastianbuechler** [comment]
@Shell32-Natsu Thank you!

This works for me now:
```
        cd ./kubernetes/base
        ../../kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        kubectl apply -k ../overlays/$ENV
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
```

**Comment by qixiaobo** [comment]
I tried to modify the newname overlay in the base and changed the newtag and found that only the overlay worked
