### ISSUE TITLE
[Question] How can I inherit from LabelTransformer?

### ISSUE THREAD

**Issue by drswobodziczka** [kubernetes-sigs/kustomize#3530]
Are there any means of **inheritance** derived for kustomize objects?

Suppose I have: 

- **LabelTransformer** defined in my base package
- **LabelTransformer** defined in my overlay package
- **Custom resource** defined in my overlay package

1. How to could I force kustomize to have my **Custom resource** labeled with both transformers? OR
2. Can I inherit from one label transformer in other one? OR
3. How can I reach transformers file from base directory inside overlays kustomization.yaml? Now I'm failing with security error =>

`(...) security; file <labels.yaml> is not in or below (...)`

**Comment by monopole** [comment]
Kustomize doesn't recognize any kind of relationship between transformers and their configuration.

You're encouraged to use overlays to get what you want.

The security error you mention pops up only when your kustomization file specifies a raw file that's outside of it's own directory (sub-directories are ok). 


See comments in https://github.com/kubernetes-sigs/kustomize/blob/master/api/loader/fileloader.go#L20

To 'get around' this, specify a directory instead, and put a kustomization file in that directory.  You can put the CR in there, and a label transformer, and in an overlay apply more transformations.
