### ISSUE TITLE
[Question] How to add labels idempotently?

### ISSUE THREAD

**Issue by Oliniusz** [kubernetes-sigs/kustomize#3531]
Hello Team, I need to be able to programmatically add labels to `kustomization.yaml` file where it can happen that the same label will be tried to be added again when rerunning a pipeline.

```
$ kustomize edit add label env:dev
Error: label env already in kustomization file
$ echo $?
1
```

In contrast to that, I have no issues with adding previously added resources:

```
$ kustomize edit add resource fluentbit
2021/02/03 19:35:01 resource fluentbit already in kustomization file
$ echo $?
0
```

How could I do that preferably without using yq, grep, sed, awk or recreating the file from the scratch?

Please let me know your ideas.

**Comment by monopole** [comment]
That's looks like an easy thing to fix in the edit command (make it not complain if the label is there already).

Anyone want to make a PR?

**Comment by Shell32-Natsu** [comment]
I can do it

**Comment by Shell32-Natsu** [comment]
You can use `-f/--force` to avoid this error message.

**Comment by Oliniusz** [comment]
Thank you, guys.

I can confirm `-f` is working for me:

```
$ kustomize edit add label env:dev -f
$ kustomize edit add label env:dev -f
$ echo $?
0
```
