### ISSUE TITLE
Broken link on kustomize.io homepage 

### ISSUE THREAD

**Issue by taurelius** [kubernetes-sigs/kustomize#3547]
**Describe the bug**
This `apply -k` link on the landing page leads to a 404, I believe it should be pointing to https://kubectl.docs.kubernetes.io/guides/config_management/introduction/ instead of https://kubectl.docs.kubernetes.io/pages/app_management/introduction.html

![image](https://user-images.githubusercontent.com/22025115/107243115-98cef900-6a24-11eb-8005-b102646b2b90.png)

Similar to #3456

**Comment by Shell32-Natsu** [comment]
For the issue on website kustomize.io, please contact contact@replicated.com.
