### ISSUE TITLE
Flag to turn off submodule cloning for remote git resources

### ISSUE THREAD

**Issue by james-callahan** [kubernetes-sigs/kustomize#3555]
**Is your feature request related to a problem? Please describe.**

We'd like to reference a remote base:

```yaml
resources:
  - git@github.com/example/somerepo/kustomize/base?ref=someref
```

However the repository has multiple large submodules (each multiple gigabytes) that result in hitting the git clone timeout of 27 seconds (https://github.com/kubernetes-sigs/kustomize/blob/065b14c5c543a5fb11d8aeb451d34821ee11f2a0/api/internal/git/gitrunner.go#L16).

I know that the base does not use any of the files brought in via submodule.

**Describe the solution you'd like**

A flag to kustomize to avoid initializing submodules; i.e. skip https://github.com/kubernetes-sigs/kustomize/blob/065b14c5c543a5fb11d8aeb451d34821ee11f2a0/api/internal/git/cloner.go#L39

This flag could be to the executable itself (e.g. `kustomize build --git-skip-submodules`), or a new query arg for git urls:

```yaml
resources:
  - git@github.com/example/somerepo/kustomize/base?ref=someref&submodules=false
```

**Describe alternatives you've considered**

Running `kustomize` with a patched `git` executable that does nothing for the `git submodule` subcommand

**Additional context**

In addition to using kustomize locally, we'd deploy kustomizations to our cluster from ArgoCD.

**Comment by stud0r** [comment]
For our use case it would already help to configure the defaultDuration.
