### ISSUE TITLE
Let kyaml keep white space formatting

### ISSUE THREAD

**Issue by jonaskello** [kubernetes-sigs/kustomize#3559]
**Is your feature request related to a problem? Please describe.**

Using [fluxcd2](https://github.com/fluxcd) with ImageUpdateAutomatation it will rewrite the kustomization.yaml file using kyaml and in doing so all whitespace is altered. Flux will commit these changes back into a gitops repo. In that commit the whole file looks like it has changed but all changes are whitespace only except for one line. This makes it very hard to tell what really changed from just looking at the commit diff. See [this issue](https://github.com/fluxcd/image-automation-controller/issues/68#issuecomment-775816455) for more background.

**Describe the solution you'd like**

I would like `kyaml` to preserve white space formatting so that flux can commit without whitespace changes.

**Comment by Shell32-Natsu** [comment]
Can you provide an example that can demonstrate what kind of whitespace format is changed?

**Comment by jonaskello** [comment]
Yes, see screenshot below (it only shows the head of the file, it is longer with more diff in total). The only real change, discounting whitespace, is the `newtag` field.

![image](https://user-images.githubusercontent.com/664076/107699501-73591e00-6cb6-11eb-911c-9bfa20cf103f.png)

**Comment by stefanprodan** [comment]
kyaml alos borks ConfigMaps, ref: https://github.com/fluxcd/image-automation-controller/issues/68#issuecomment-745187641
![102201067-e831f680-3ec5-11eb-9c6a-b3f3054c4bbe](https://user-images.githubusercontent.com/3797675/107758229-43019600-6d2f-11eb-9555-fa384db341e9.png)

**Comment by Shell32-Natsu** [comment]
@monopole This is an example of the indentation differences in go-yaml.

@stefanprodan What's the version of kustomize are you using. The issue in your image is different from the one that @jonaskello reported.

**Comment by stefanprodan** [comment]
@Shell32-Natsu [fluxcd/image-automation-controller](https://github.com/fluxcd/image-automation-controller) doesn't uses kustomize as a whole, but kyaml as a library: https://github.com/fluxcd/image-automation-controller/blob/main/go.mod#L34

```
// Force downgrade to version used by kyaml.
replace gopkg.in/yaml.v3 => gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c

require (
	sigs.k8s.io/kustomize/kyaml v0.10.9
)
```

**Comment by Shell32-Natsu** [comment]
@stefanprodan OK that should be a different issue.

**Comment by jonaskello** [comment]
/remove-lifecycle stale

This is still an issue AFAIK.

**Comment by KnVerey** [comment]
This looks to me like the changes we saw when attempting to bump go-yaml in https://github.com/kubernetes-sigs/kustomize/pull/3789. So it's ultimately being caused by kyaml using a different go-yaml version than your other tool, and go-yaml.v3 making what I'd consider to be a breaking formatting change.

Since Kustomize has long emitted the older format, we have been investigating the possibility of avoiding the change, which will likely be disruptive to many users. Relevant to this particular issue, it seems likely that that will require kyaml to interfere with the whitespace formatting goyaml currently forces. @Shell32-Natsu how feasible is that looking?

**Comment by monopole** [comment]
@stefanprodan would you please take a look at the discussion in #3946 and comment there?  Thanks!

**Comment by KnVerey** [comment]
Per #3946, the underlying yaml lib we use changed its indentation style, causing diffs like this. Kustomize pinned to an older version to keep the indentation stable, but we couldn't automatically do the same for folks using kyaml directly. As of kyaml 0.11.0, kyaml itself also uses  kustomize's preferred indentation style. The next release of kyaml will contain https://github.com/kubernetes-sigs/kustomize/pull/4043, which allows kyaml/yaml users to override the default style, and kyaml/kio to detect and retain the style in the source document.

/close
