### ISSUE TITLE
[Question] plugin was built with a different version of package github.com/pkg/errors

### ISSUE THREAD

**Issue by matkosoric** [kubernetes-sigs/kustomize#3574]
I am following these instructions to create custom plugin:
https://github.com/kubernetes-sigs/kustomize/blob/kustomize/v3.10.0/examples/secretGeneratorPlugin.md

However, there is an error caused by dependencies mismatch:

`Error: loading generator plugins: plugin kustomize/plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase.so fails to load: plugin.Open("kustomize/plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase"): plugin was built with a different version of package github.com/pkg/errors`

We tried building different versions of kustomize, installing binaries directly, downgrading versions of pkg/errors to 0.8.0 both in kustomize and example code, but without success, eventually just hitting similar errors for different packages (golang.org/x/text/transform, internal/unsafeheader, etc.).

This link is mentioned on similar issues, but it is currently broken:
https://kubectl.docs.kubernetes.io/guides/extending_kustomize/plugins

What are we doing wrong?

**Comment by Shell32-Natsu** [comment]
This is a very annoying issue in Go and I think there is no generic solution. I suggest to use exec plugin instead of Go plugin. Go plugin has its benefit, like easier to convert to built plugin but the problems like this make it less useful.

**Comment by epcim** [comment]
possibly not generic solution but there shall be steps to mitigate the issue (ie to properly build the plugin).

In my makefile I was using workaround below, however that's just partial, sparta solution and does not fix everything. Is there it golang world a way to pin to packages that were used to build binary?

And anyway, one should be given a way to build kustomize, with it's custom plugins as one piece..

```
fixmod: getmodupstream tidy vendor

getmodupstream:
        @curl -qsL "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/kustomize/$(KUSTOMIZE_VERSION)/kustomize/go.mod" \
                | egrep -v '^replace' \
                | sed 's,^module.*,module $(PLUGIN_REPOSITORY),' >| go.mod
```
