### ISSUE TITLE
`kustomize edit add *.yaml` adds the kustomization file itself.

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#3575]

**Comment by alexal** [comment]
@monopole I've reproduced the problem, but with slightly different command `kustomize edit add resource *.yml`. That will add kustomization.yml file into kustomization.yml file itself. If you do not mind, please assign this issue to me and I will work on it.

**Comment by Shell32-Natsu** [comment]
@alexal Thanks a lot!

**Comment by alexal** [comment]
Please see PR #3582.

**Comment by natasha41575** [comment]
Fixed via #3582. Thanks!
