### ISSUE TITLE
Feature req: a non-builtin plugin  that accepts a hashicorp go-getter URL

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#3585]
[go-getter URL]: https://github.com/hashicorp/go-getter#url-format
[LICENSE list]: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#cncf-allowlist-license-policy

Need a generator plugin (exec or container based, not shared lib based) that accepts
one or more [go-getter URL]s in its configuration and pulls it into the kustomize
pipeline.

Background:  go-getter's license is not on the CNCF approved [LICENSE list],  and too many deps (#3578)

**Comment by natasha41575** [comment]
Interested in having this.

/triage accepted
