### ISSUE TITLE
Convention-Based Defaults for kustomization.yaml

### ISSUE THREAD

**Issue by dlorenc** [kubernetes-sigs/kustomize#36]
Has there been any discussion on a system for convention-based defaults? It seems like many of the fields in a kustomization.yaml could be omitted if the user follows some conventional directory structure. For example, the structure outlined in the tutorials:

```
someApp
├── base
│   ├── manifest1.yaml
│   ├── manifest2.yaml
│   └── ...
└── overlays
    ├── overlay1
    │   ├── manifest1.yaml
    │   ├── manifest2.yaml
```

**Comment by Liujingfang1** [comment]
kustomize doesn't provide this kind of defaults. The names like `base`, `overlays`, `overlay1` can be other random names. I don't think adding such defaults can help a lot.
