### ISSUE TITLE
[Question]Registry images missing 3.10 & 4.0.1

### ISSUE THREAD

**Issue by Jackbennett** [kubernetes-sigs/kustomize#3607]
It's barely a week since release but does CI not publish containers? - https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/kustomize/kustomize

Thanks for landing the various updates.

**Comment by Shell32-Natsu** [comment]
The k8s official images are needed to be added manually. Will do it soon.

**Comment by Shell32-Natsu** [comment]
https://github.com/kubernetes/k8s.io/pull/1658

**Comment by Shell32-Natsu** [comment]
New images will be available after the PR merged.
