### ISSUE TITLE
Support go 1.16 module aware install with version

### ISSUE THREAD

**Issue by yhrn** [kubernetes-sigs/kustomize#3618]
**Is your feature request related to a problem? Please describe.**

Go 1.16 supports installing tools via `go install [package@version]`, which will build and install a specific version of that tool without interacting with the local go.mod. This does not work for Kustomize because its go.mod contains replace and exclude directives (more context [here](https://github.com/golang/go/issues/40276)).

It would be nice if this worked for Kustomize as well as that would allow us to handle all of our tool dependencies in a consistent and deterministic manner.

**Describe the solution you'd like**

I don't really have a suggestion for how to change the current module structure for this to work or if it is really feasible but I thought it might be worth bringing up at least.

**Comment by Shell32-Natsu** [comment]
The replacements are not included  in the a released version I believe. Are you trying to install a specific commit?

**Comment by yhrn** [comment]
No I was just doing `go install sigs.k8s.io/kustomize/kustomize/v4@v4.0.1`

**Comment by Shell32-Natsu** [comment]
https://github.com/kubernetes-sigs/kustomize/blob/516ff1fa56040adc0173ff6ece66350eb4ed78a9/kustomize/go.mod

Ok so the problem is `exclude`. @monopole can you take a look?

**Comment by yhrn** [comment]
I think this is more relevant now that go 1.17 has deprecated installing executables with `go get`.

**Comment by neha-viswanathan** [comment]
@yhrn any updates on this issue?

**Comment by yhrn** [comment]
@neha-viswanathan I just reported this, I'm not deeply involved with the development of Kustomize so I don't know how feasible this is to fix.

**Comment by natasha41575** [comment]
I'm trying to understand why these exclude statements were added.

Commits: 
- https://github.com/kubernetes-sigs/kustomize/commit/fe3321d710a327904c01a6a1e7d256e316569312
- https://github.com/kubernetes-sigs/kustomize/commit/b8a13b633577dbcba2dcadcf0e80f6586ccd64ad

I just tried removing the `exclude` statements, kustomize builds fine. I'm inclined to just remove them, but I'd really like to know their context before doing that.

**Comment by Neo2308** [comment]
The exclude statements seem to just be artifacts from older release cycles. I dont see a point in excluding apis v2 when we are already on version v10

**Comment by vitorenesduarte** [comment]
With #4387, I can now install `kustomize` with `go install`.

**Comment by yhrn** [comment]
Confirmed that I could install v4.5.2 using `go install sigs.k8s.io/kustomize/kustomize/v4@v4.5.2`. Thank you!
