### ISSUE TITLE
Errors should include the files causing the issues where possible.

### ISSUE THREAD

**Issue by nelaaro** [kubernetes-sigs/kustomize#3622]
**Files name and location should be included in errors where possible.**
I recently got this error 

    kustomize  build yaml/overlays/testing 
    kustomize  --stack-trace build yaml/overlays/testing 
    kustomize  build --stack-trace yaml/overlays/testing --stack-trace
    kustomize  build --stack-trace yaml/overlays/testing --stack-trace
    kustomize  build yaml/overlays/testing  --stack-trace 

Error

    Error: namespace transformation produces ID conflict: [{"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"config.kubernetes.io/originalNs":"default"},"name":"cattle-monitoring-system-test"}}{nsfx:false,beh:unspecified} {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"config.kubernetes.io/originalNs":"default"},"labels":{"name":"cattle-dashboards"},"name":"cattle-monitoring-system-test"}}{nsfx:false,beh:unspecified}]

Here are some additional details 

    kustomize version
    {Version:3.9.2 GitCommit:$Format:%H$ BuildDate:2021-01-20T13:20:32Z GoOs:linux GoArch:amd64}

It is much easier to understand a problem when you can contextualize it.
I understand this is a problem because I have multiple namespace resources defined and I am trying to override them to exist in one namespace. The challenge I have with this project is that it has over 200 resource files in over 50 directories. 

I have to do extra work to find and resolve these conflicts which are not as straightforward as I would like.

This is complex as the are many nested directories and the `--stack-trace` option is not producing a stack trace either. 
As there are multiple files and directories involved it might help to have a flag like `-v` or `--stack-trace` that would display the files involved in producing any relevant error.

At this point, I am just grepping for the files based on the error message and google to find a workaround.
I am not entirely sure I am working off the correct files as I am still lacking some context. 

**Additional context**

**Files paths for this project**
      
    find ./yaml/
    ./yaml/
    ./yaml/overlays
    ./yaml/overlays/production
    ./yaml/overlays/production/namespace.yaml
    ./yaml/overlays/production/kustomization.yaml
    ./yaml/overlays/testing
    ./yaml/overlays/testing/namespace.yaml
    ./yaml/overlays/testing/kustomization.yaml
    ./yaml/base
    ./yaml/base/kustomization.yaml
    ./yaml/base/rancher-monitoring
    ./yaml/base/rancher-monitoring/charts
    ./yaml/base/rancher-monitoring/charts/prometheus-node-exporter
    ./yaml/base/rancher-monitoring/charts/prometheus-node-exporter/templates
    ./yaml/base/rancher-monitoring/charts/prometheus-node-exporter/templates/psp-clusterrole.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-node-exporter/templates/daemonset.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-node-exporter/templates/psp.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-node-exporter/templates/service.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-node-exporter/templates/serviceaccount.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-node-exporter/templates/serviceaccount.yamle
    ./yaml/base/rancher-monitoring/charts/prometheus-node-exporter/templates/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-node-exporter/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/rancher-pushprox
    ./yaml/base/rancher-monitoring/charts/rancher-pushprox/templates
    ./yaml/base/rancher-monitoring/charts/rancher-pushprox/templates/pushprox-servicemonitor.yamle
    ./yaml/base/rancher-monitoring/charts/rancher-pushprox/templates/pushprox-clients.yaml
    ./yaml/base/rancher-monitoring/charts/rancher-pushprox/templates/pushprox-proxy.yaml
    ./yaml/base/rancher-monitoring/charts/rancher-pushprox/templates/pushprox-clients-rbac.yaml
    ./yaml/base/rancher-monitoring/charts/rancher-pushprox/templates/pushprox-servicemonitor.yaml
    ./yaml/base/rancher-monitoring/charts/rancher-pushprox/templates/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/rancher-pushprox/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/grafana
    ./yaml/base/rancher-monitoring/charts/grafana/templates
    ./yaml/base/rancher-monitoring/charts/grafana/templates/role.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/rolebinding.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/podsecuritypolicy.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/nginx-config.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/secret.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/clusterrole.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/service.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/serviceaccount.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/pvc.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/clusterrolebinding.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/deployment.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/configmap.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/tests
    ./yaml/base/rancher-monitoring/charts/grafana/templates/tests/test-rolebinding.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/tests/test-serviceaccount.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/tests/test-podsecuritypolicy.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/tests/test-role.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/tests/test.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/tests/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/tests/test-configmap.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/configmap-dashboard-provider.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/templates/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/grafana/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/rkeEtcd
    ./yaml/base/rancher-monitoring/charts/rkeEtcd/templates
    ./yaml/base/rancher-monitoring/charts/rkeEtcd/templates/pushprox-servicemonitor.yamle
    ./yaml/base/rancher-monitoring/charts/rkeEtcd/templates/pushprox-proxy-rbac.yaml
    ./yaml/base/rancher-monitoring/charts/rkeEtcd/templates/pushprox-clients.yaml
    ./yaml/base/rancher-monitoring/charts/rkeEtcd/templates/pushprox-proxy.yaml
    ./yaml/base/rancher-monitoring/charts/rkeEtcd/templates/pushprox-clients-rbac.yaml
    ./yaml/base/rancher-monitoring/charts/rkeEtcd/templates/pushprox-servicemonitor.yaml
    ./yaml/base/rancher-monitoring/charts/rkeEtcd/templates/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/rkeEtcd/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/custom-metrics-apiserver-auth-delegator-cluster-role-binding.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/custom-metrics-apiserver-resource-reader-cluster-role-binding.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/custom-metrics-configmap.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/custom-metrics-apiservice.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/custom-metrics-cluster-role.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/custom-metrics-apiserver-auth-reader-role-binding.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/custom-metrics-apiserver-psp.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/hpa-custom-metrics-cluster-role-binding.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/custom-metrics-apiserver-service.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/custom-metrics-resource-reader-cluster-role.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/templates/custom-metrics-apiserver-service-account.yaml
    ./yaml/base/rancher-monitoring/charts/prometheus-adapter/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics/templates
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics/templates/podsecuritypolicy.yaml
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics/templates/psp-clusterrole.yaml
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics/templates/clusterrole.yaml
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics/templates/service.yaml
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics/templates/serviceaccount.yaml
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics/templates/clusterrolebinding.yaml
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics/templates/deployment.yaml
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics/templates/psp-clusterrolebinding.yaml
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics/templates/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/kube-state-metrics/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/rkeControllerManager
    ./yaml/base/rancher-monitoring/charts/rkeControllerManager/templates
    ./yaml/base/rancher-monitoring/charts/rkeControllerManager/templates/pushprox-servicemonitor.yamle
    ./yaml/base/rancher-monitoring/charts/rkeControllerManager/templates/pushprox-proxy-rbac.yaml
    ./yaml/base/rancher-monitoring/charts/rkeControllerManager/templates/pushprox-clients.yaml
    ./yaml/base/rancher-monitoring/charts/rkeControllerManager/templates/pushprox-proxy.yaml
    ./yaml/base/rancher-monitoring/charts/rkeControllerManager/templates/pushprox-clients-rbac.yaml
    ./yaml/base/rancher-monitoring/charts/rkeControllerManager/templates/pushprox-servicemonitor.yaml
    ./yaml/base/rancher-monitoring/charts/rkeControllerManager/templates/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/rkeControllerManager/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/rkeScheduler
    ./yaml/base/rancher-monitoring/charts/rkeScheduler/templates
    ./yaml/base/rancher-monitoring/charts/rkeScheduler/templates/pushprox-servicemonitor.yamle
    ./yaml/base/rancher-monitoring/charts/rkeScheduler/templates/pushprox-proxy-rbac.yaml
    ./yaml/base/rancher-monitoring/charts/rkeScheduler/templates/pushprox-clients.yaml
    ./yaml/base/rancher-monitoring/charts/rkeScheduler/templates/pushprox-proxy.yaml
    ./yaml/base/rancher-monitoring/charts/rkeScheduler/templates/pushprox-clients-rbac.yaml
    ./yaml/base/rancher-monitoring/charts/rkeScheduler/templates/pushprox-servicemonitor.yaml
    ./yaml/base/rancher-monitoring/charts/rkeScheduler/templates/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/rkeScheduler/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/rkeProxy
    ./yaml/base/rancher-monitoring/charts/rkeProxy/templates
    ./yaml/base/rancher-monitoring/charts/rkeProxy/templates/pushprox-servicemonitor.yamle
    ./yaml/base/rancher-monitoring/charts/rkeProxy/templates/pushprox-proxy-rbac.yaml
    ./yaml/base/rancher-monitoring/charts/rkeProxy/templates/pushprox-clients.yaml
    ./yaml/base/rancher-monitoring/charts/rkeProxy/templates/pushprox-proxy.yaml
    ./yaml/base/rancher-monitoring/charts/rkeProxy/templates/pushprox-clients-rbac.yaml
    ./yaml/base/rancher-monitoring/charts/rkeProxy/templates/pushprox-servicemonitor.yaml
    ./yaml/base/rancher-monitoring/charts/rkeProxy/templates/kustomization.yaml
    ./yaml/base/rancher-monitoring/charts/rkeProxy/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates
    ./yaml/base/rancher-monitoring/templates/prometheus-operator
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/psp-clusterrole.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/servicemonitor.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/clusterrole.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/job-patch
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/job-patch/role.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/job-patch/rolebinding.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/job-patch/clusterrolebinding.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/job-patch/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/admission-webhooks/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/psp.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/service.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/serviceaccount.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/clusterrolebinding.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/deployment.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/psp-clusterrolebinding.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus-operator/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/alertmanager
    ./yaml/base/rancher-monitoring/templates/alertmanager/alertmanager.yaml
    ./yaml/base/rancher-monitoring/templates/alertmanager/servicemonitor.yaml
    ./yaml/base/rancher-monitoring/templates/alertmanager/secret.yaml
    ./yaml/base/rancher-monitoring/templates/alertmanager/psp-rolebinding.yaml
    ./yaml/base/rancher-monitoring/templates/alertmanager/psp.yaml
    ./yaml/base/rancher-monitoring/templates/alertmanager/service.yaml
    ./yaml/base/rancher-monitoring/templates/alertmanager/serviceaccount.yaml
    ./yaml/base/rancher-monitoring/templates/alertmanager/psp-role.yaml
    ./yaml/base/rancher-monitoring/templates/alertmanager/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/validate-install-crd.yaml
    ./yaml/base/rancher-monitoring/templates/grafana
    ./yaml/base/rancher-monitoring/templates/grafana/configmaps-datasources.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/servicemonitor.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/namespaces.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/scheduler.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/statefulset.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/etcd.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/namespace-by-pod.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/k8s-coredns.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/persistentvolumesusage.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/k8s-resources-namespace.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/pod-total.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/prometheus.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/node-cluster-rsrc-use.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/node-rsrc-use.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/kubelet.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/k8s-resources-workloads-namespace.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/cluster-total.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/proxy.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/workload-total.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/apiserver.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/controller-manager.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/k8s-resources-node.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/nodes.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/namespace-by-workload.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml
    ./yaml/base/rancher-monitoring/templates/grafana/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/exporters
    ./yaml/base/rancher-monitoring/templates/exporters/kubelet
    ./yaml/base/rancher-monitoring/templates/exporters/kubelet/servicemonitor.yaml
    ./yaml/base/rancher-monitoring/templates/exporters/kubelet/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/exporters/node-exporter
    ./yaml/base/rancher-monitoring/templates/exporters/node-exporter/servicemonitor.yaml
    ./yaml/base/rancher-monitoring/templates/exporters/node-exporter/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/exporters/kube-api-server
    ./yaml/base/rancher-monitoring/templates/exporters/kube-api-server/servicemonitor.yaml
    ./yaml/base/rancher-monitoring/templates/exporters/kube-api-server/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/exporters/kube-state-metrics
    ./yaml/base/rancher-monitoring/templates/exporters/kube-state-metrics/serviceMonitor.yaml
    ./yaml/base/rancher-monitoring/templates/exporters/kube-state-metrics/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/exporters/core-dns
    ./yaml/base/rancher-monitoring/templates/exporters/core-dns/servicemonitor.yaml
    ./yaml/base/rancher-monitoring/templates/exporters/core-dns/service.yaml
    ./yaml/base/rancher-monitoring/templates/exporters/core-dns/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/exporters/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus
    ./yaml/base/rancher-monitoring/templates/prometheus/psp-clusterrole.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/servicemonitor.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/nginx-config.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/clusterrole.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/psp.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/prometheus.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/service.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/serviceaccount.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kube-apiserver.rules.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kubernetes-storage.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kubelet.rules.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kube-prometheus-node-recording.rules.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kubernetes-apps.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/etcd.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/node-exporter.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/node-network.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/alertmanager.rules.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/prometheus.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kube-scheduler.rules.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kube-apiserver-availability.rules.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/general.rules.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/k8s.rules.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kubernetes-system.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kubernetes-resources.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/node.rules.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/node-exporter.rules.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/prometheus-operator.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kube-prometheus-general.rules.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/rules-1.14/kube-state-metrics.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/clusterrolebinding.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/psp-clusterrolebinding.yaml
    ./yaml/base/rancher-monitoring/templates/prometheus/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/rancher-monitoring
    ./yaml/base/rancher-monitoring/templates/rancher-monitoring/dashboard-role.yaml
    ./yaml/base/rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml
    ./yaml/base/rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml.old
    ./yaml/base/rancher-monitoring/templates/rancher-monitoring/default-dashboard.yaml
    ./yaml/base/rancher-monitoring/templates/rancher-monitoring/config-role.yaml
    ./yaml/base/rancher-monitoring/templates/rancher-monitoring/kustomization.yaml
    ./yaml/base/rancher-monitoring/templates/rancher-monitoring/hardened.yaml
    ./yaml/base/rancher-monitoring/kustomization.yaml

**Comment by Shell32-Natsu** [comment]
kustomize reads the *resource* from files and then use apply process on *resources* and has no knowledge about the file. So currently we cannot have the file path which contains the resource.

**Comment by nelaaro** [comment]
Hi

I kinda understand what you are saying. 

What doesn't make sense to me is if I give kustomize a path say `/yaml/base` inside that path is a file 
`kustomization.yaml`. You have to parse that file to find the bases, and resources that need to be processed. 

You should have some context as to what path the `kustomization.yaml` was found in. 
What bases / paths it has asked the parse to add to the list of customization resources to parse. 
  
    ./yaml/base
    ./yaml/base/kustomization.yaml

How is this information not available to the parser when it errors out. 
Should the stack trace option hit some point in the trace that comes to the calling function that has this context information available. It is traversing a directory paths and reading files.

**Comment by Shell32-Natsu** [comment]
Kustomize knows the current directory for the current kustomization, but for an individual resource, its location is not necessarily related to this path. It can be a remote file, a generated resource etc.
