### ISSUE TITLE
kustomize performance difference between v4.0.1 and v2.0.3

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes-sigs/kustomize#3627]
I have a reasonable size of directory which I can run kustomize build.

```console
$ kustomize build -o foo.yaml
$ ls -alh foo.yaml
-rw-r--r--  1 haibzhou  xxxx   308K Feb 23 19:52 foo.yaml
```

The target file is **308k**.

I can observe a huge performance drop when upgrading kustomize from v2.0.3 to v4.0.1

### v4.0.1

```console
$ time kustomize build -o foo.yaml
kustomize build -o foo.yaml  8.37s user 0.40s system 152% cpu 5.748 total
```

### v2.0.3

```console
$ time ./kustomize-v2.0.3 build -o foo.yaml
./kustomize-v2.0.3 build -o foo.yaml  0.79s user 0.16s system 96% cpu 0.991 total
```

**Platform**

macOS

**Additional context**
None

/kind bug

**Comment by Shell32-Natsu** [comment]
Kustomize needs to do lots of internal works to remove apimachinery deps and reintegrate with kukectl. We will work on removing these additional works after that.
