### ISSUE TITLE
Please release for PPC64LE architectue

### ISSUE THREAD

**Issue by ezeeyahoo** [kubernetes-sigs/kustomize#3640]
Hi,

We are working on Gardener and Kubeflow projects. Some of our code are already accepted or in pipeline. In absense of kustomize binary, we are facing some road blocks. Can I use this request to request you to release for PPC64LE architecture too.

Versions:-
3.5.4
3.2.0

Thanks

cc:@gerrith3

**Comment by Shell32-Natsu** [comment]
Our release script is [here](https://github.com/kubernetes-sigs/kustomize/blob/master/releasing/cloudbuild.sh) you can use go-releaser to build binary for ppc64le.

**Comment by ezeeyahoo** [comment]
if we get binary hosted on main repository then it will need fewer changes than having separate URLs for different archs in Dockerfile.

**Comment by gerrith3** [comment]
@ezeeyahoo Is this issue still valid?  If so could you provide an update and see if it can be tagged to someone or at least refreshed?  thanks!

**Comment by ezeeyahoo** [comment]
@gerrith3 Yes, because we are waiting for response and last release that happened 18days ago, is not listing PPC64LE.

I would request community to consider PPC64LE too for release.https://github.com/kubernetes-sigs/kustomize/issues/3640#issuecomment-787017294
