### ISSUE TITLE
Support golang io/fs FS interface

### ISSUE THREAD

**Issue by jieyu** [kubernetes-sigs/kustomize#3657]
It'll be nice that kustomize can support the new io/fs FS interface (https://golang.org/pkg/io/fs/#FS).

This would greatly simply the work to create a "virtual" filesystem layout (by embeding the manifests using the new golang 1.16 //go:embed feature), and load the manifests.

**Comment by eddiezane** [comment]
Could you please provide an ideal use case you have in mind for this?

**Comment by dashanji** [comment]
> Could you please provide an ideal use case you have in mind for this?

Hi, @eddiezane. I have the same question and could you please reopen the issue?
