### ISSUE TITLE
helmChartInflationGenerator doesn't appear to work properly with local charts

### ISSUE THREAD

**Issue by rbkaspr** [kubernetes-sigs/kustomize#3658]
**Describe the bug**
I'm attempting to take advantage of the helmChartInflationGenerator plugin to combine a locally stored, unpackaged Helm chart with a few pre- and post-install artifacts. The issue I'm running into is that the plugin always seems to be trying to reach out to the legacy stable chart repo, even if chartRepoUrl is unset and chartHome is set to the location of the unpackaged chart. Even with some mucking around with the settings, it appears that the plugin expects a properly packaged (.tar.gz) chart at whatever location it's looking in. We keep these charts vendored in our Git repo along with the Kustomize manifests because they've been modified for our particular usecase.

**Files that can reproduce the issue**
```
docs
├── chart
│   └── <unpackaged chart
├── overlay
│   ├── kustomization.yaml
│   ├── values.yaml
│   └── <additionalResources
```
``` yaml
resources:
- <additionalResources>
helmChartInflationGenerator:
- chartName: sonarqube
  chartHome: ../chart
  values: values.yaml
```

**Expected output**

Helm template + additional Kustomize objects

**Actual output**
``` bash
Error: Error: repo stable not found
: failed to run command helm pull --untar --untardir ../chart stable/sonarqube
```

**Kustomize version**
`v4.0.4`

**Platform**
Linux

**Additional context**
Helm 3.5.2

**Comment by Shell32-Natsu** [comment]
I am not familiar with helm but what helmChartInflationGenerator does is pulling the template and rendering it. If you want different behavior, try to create you own exec plugin.

**Comment by snuggie12** [comment]
depends on the contents of `< unpackaged chart` I think. The local check sees if there's a directory named `chartHome/chartName` so I think if you had `docs/chart/sonarqube/Chart.yaml` it would work.

**Comment by KnVerey** [comment]
Thanks for the report @rbkaspr ! It looks like you're right that local charts aren't supported right now. We would gladly accept PRs to:
1) Improve the error message in the meantime.
2) Implement local chart support.

Would you be interested in helping with either of those? The code for the helm generator is here: https://github.com/kubernetes-sigs/kustomize/blob/master/api/builtins/HelmChartInflationGenerator.go

/help
/triage accepted
/kind feature
