### ISSUE TITLE
Fix error thrown by golangci-lint in kyaml

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#3663]
Kyaml is currently failing the lint test, because golangci-lint v1.18 and above results in the following lint error: 

`Running error: context loading failed: package golang.org/x/net/idna: no go files to analyze`

The following is the output of go mod why:
```
~/gopath/src/sigs.k8s.io/kustomize/kyaml $ go mod why  golang.org/x/net/idna
# golang.org/x/net/idna
sigs.k8s.io/kustomize/kyaml/fieldmeta
github.com/go-openapi/spec
github.com/go-openapi/jsonreference
github.com/PuerkitoBio/purell  <-- a URL normalizer/sanitizer
golang.org/x/net/idna
```

Currently there is a [PR](https://github.com/kubernetes-sigs/kustomize/pull/3661) to move the version back down to 1.17.0, but this issue needs to be fixed so we can upgrade it again.

**Comment by monopole** [comment]
Related: https://github.com/golangci/golangci-lint/issues/825

(comment https://github.com/golangci/golangci-lint/issues/825#issuecomment-666038142)

didn't seem to help in #3661

**Comment by monopole** [comment]
kyaml linting removed in pr #3688, as it was blocking release.

**Comment by natasha41575** [comment]
The kustomize module is throwing the same error, and was downgraded in this PR: https://github.com/kubernetes-sigs/kustomize/pull/3891

Also, even after downgrading, if kustomize tries to import io/fs, it throws the error `build sigs.k8s.io/kustomize/kustomize/v4: cannot load io/fs: malformed module path \"io/fs\": missing dot in first path element\n"`
