### ISSUE TITLE
Upgrade to gopkg.in/yaml.v2 v2.4.0

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#3664]
Blocks #1500, related to kubernetes/kubernetes#98946

Both the api/go.mod and kyaml/go.mod are pinned to v2.3.0, but this has a problem:  go-yaml/yaml#670

What happens if we change to v2.4.0?

**Comment by natasha41575** [comment]
Looks like all this changes is a few unit tests. It appears that there is a line length limit in v2.4.0 and long lines are given line breaks and continue to the next line. Will make a PR to show the changes

**Comment by monopole** [comment]
line breaks are expected :+1:
