### ISSUE TITLE
Add ConfigMap back references for Knative Service

### ISSUE THREAD

**Issue by 7adietri** [kubernetes-sigs/kustomize#3671]
**Is your feature request related to a problem? Please describe.**

Similar to https://github.com/kubernetes-sigs/kustomize/issues/2564, Kustomize doesn't update `ConfigMap` names in Knative `Service` configuration.

Please add compatibility with Knative services, i.e.:

```
- path: spec/template/spec/containers/env/valueFrom/configMapKeyRef/name
  kind: Service
  group: serving.knative.dev
  version: v1
- path: spec/template/spec/containers/envFrom/configMapRef/name
  kind: Service
  group: serving.knative.dev
  version: v1
- path: spec/template/spec/volumes/configMap/name
  kind: Service
  group: serving.knative.dev
  version: v1
```

**Describe alternatives you've considered**

Adding this locally through `configurations` can be a temporary workaround.

**Additional context**

**Comment by Shell32-Natsu** [comment]
I think we don't have plan to add builtin support for non-native resources in kustomize. They should be configured by transformer configurations.
