### ISSUE TITLE
label transformer - add selector labels to pdb

### ISSUE THREAD

**Issue by naseemkullah** [kubernetes-sigs/kustomize#3703]
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#labels-transformer

It appears that  `commonLabels` are added as selector labels to deployments and services but not pod disruption budgets.

is there any reason not to? If not it would be a nice addition.

**Comment by Shell32-Natsu** [comment]
It's added. https://github.com/kubernetes-sigs/kustomize/blob/81cac9b633da89ce94ec2e15e2bc95c6f8825d1f/api/konfig/builtinpluginconsts/commonlabels.go#L140

**Comment by naseemkullah** [comment]
How does one use it? The common labels are not being added atm. Is further configuration required?

**Comment by Shell32-Natsu** [comment]
Kustomize will not create the field if it isn't there since `create: false`. So you need to make sure `spec/selector/matchLabels` does exist.

**Comment by naseemkullah** [comment]
Great, thanks.
