### ISSUE TITLE
Prevent go-openapi/{analysis,validate,strfmt} deps from leaking into api module

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#3705]
and thus leaking in to kubectl.

**Comment by monopole** [comment]
https://github.com/kubernetes/kubernetes/pull/98946#discussion_r589798392

i think i see an easy way to do this that doesn't involve module rearrangement

**Comment by liggitt** [comment]
as of https://github.com/kubernetes/kubernetes/pull/101234, I think kustomize is the only thing pulling in these dependencies... would be good to eliminate this

**Comment by gautierdelorme** [comment]
@liggitt @monopole I can give it a try. I think `k8s.io/kube-openapi` should have all the requirements.
/assign
