### ISSUE TITLE
HelmChartInflationGenerator issue

### ISSUE THREAD

**Issue by shaktiprasadrath** [kubernetes-sigs/kustomize#3707]
I have one kustomize folder with bases and overlays. I added template folder along with chart.yml and Values.yml inside the kustomize folder.

KustomizeMe
            |
            --- base/
                         --- kustomize.yml
                         --- helmchartgenerator.yml
            --- overlays/
            --- template/
                               --- deployment.yml
                               --- configmapMe.yml
            --- Chart.yml
            --- Values.yml

In the helmchartgenerator.yml, I provided the chart name as kustomizeMe.

The issue is when i am running kustomize build, it is not generating the chart..

Can someone suggest?

**Comment by Shell32-Natsu** [comment]
You don't need to add the helm files to kustomize. Please read the doc about helm generator. https://kubectl.docs.kubernetes.io/guides/extending_kustomize/builtins/#_helmchartinflationgenerator_
