### ISSUE TITLE
Resources accumulation issue with remote resources using git and depth parameter 

### ISSUE THREAD

**Issue by xakraz** [kubernetes-sigs/kustomize#3716]
### Context

We are using a kind off "off-the-shelf" pattern for our deployments environments:
* Common resources are on `master` branch of our services
* Specific environment overlays are on dedicated branches `deployment/ENV_NAME`

On the environment overlays, we usually have 

```
resources:
- github.com/MY_ORG/MY_SERVICE//deployment?ref=A_GIT_REF
```
where the `GIT_REF` is also part of the docker image tag name, which in turn refers to the commit on the `master` branch of the code included in the image.

### Issue

Some of our services are relatively "huge", and `kustomize build` takes around 15min to run.

To optimize it, we were looking for a "git shallow clone" approach and found the `depth` parameter in the [go-getter](https://github.com/hashicorp/go-getter#git-git) documentation.

It works without issues when the resources reference has this url format:

```
resources:
- github.com/MY_ORG/MY_SERVICE//deployment?ref=master&depth=1
```

But it fails when there is a git commit ref ...

```
resources:
- github.com/MY_ORG/MY_SERVICE//deployment?ref=SHORT_COMMIT_ID&depth=1
```

```
Error checking out ref: error: pathspec 'SHORT_COMMIT_ID&depth=1' did not match any file(s) known to git
Error: accumulating resources:
  accumulateFile "accumulating resources from 'github.com/MY_ORG/MY_SERVICE//deployment?ref=SHORT_COMMIT_ID&depth=1':
    evalsymlink failure on '/home/me/Sources/github.com/MY_ORG/MY_SERVICE/deployment/github.com/MY_ORG/MY_SERVICE/deployment?ref=SHORT_COMMIT_ID&depth=1':
      lstat /home/me/Sources/github.com/MY_ORG/MY_SERVICE/deployment/github.com: no such file or directory",
      loader.New "trouble checking out SHORT_COMMIT_ID&depth=1:
        exit status 1"
```

whereas, this format used to work without any issue

```
resources:
- github.com/MY_ORG/MY_SERVICE//deployment?ref=A_GIT_REF
```

## Kustomize version

```
$ kustomize version

{Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
```

## Platform

Linux

## Additional context

- [x] The SHORT_COMMIT_ID mentionned has been checked and does exists in Github
- [x] Removing the `depth` parameter makes the build working but takes time as it gets the whole history
- [x] Moving around parameters from `?ref=XXX&depth=1` to `?depth=1&ref=XXX` does not solve the issue
- [x] I have read issues regarding this topic
  * https://github.com/kubernetes-sigs/kustomize/issues/923
  * https://github.com/kubernetes-sigs/kustomize/issues/3137
  * https://github.com/kubernetes-sigs/kustomize/issues/2538#issuecomment-729629437
  * https://github.com/kubernetes-sigs/kustomize/issues/3505
- [x] I have read the issues mentioning the removal of `go-getter` like capabilities:
  * https://github.com/kubernetes-sigs/kustomize/issues/2538#issuecomment-729674300
  * https://github.com/kubernetes-sigs/kustomize/issues/2538#issuecomment-730114411
  * https://github.com/kubernetes-sigs/kustomize/pull/3586
- [x] Nevertheless, we are using kustomize `v3.6.1` which date from the 27th of May 2020 where the mentionned issues were from November 2020.

## Last but no least

It would be very great if `Kustomize` remote resources with git could support "git shallow clone".
I think it would partially answers to https://github.com/kubernetes-sigs/kustomize/issues/2460

**Comment by Shell32-Natsu** [comment]
Have you tried the the URL with go-getter directly?

**Comment by xakraz** [comment]
Ho @Shell32-Natsu ,

Thanks for answering me.

I have just tried with the latest `go-getter` binary (`v1.5.2`)

```
$ ./go-getter 'github.com/MY_ORG/MY_SERVICE//deployment?ref=SHORT_COMMIT_ID&depth=1' ./foo
2021/03/11 10:14:16 success!
```

It took 9s and I got exactly what I expected

```
foo
├── deployment.yaml
├── ingress.yaml
├── kustomization.yaml
└── service.yaml
```

**Comment by xakraz** [comment]
I have also just tried without the `depth=1` param.

It works **but took 29s !**

**Comment by Shell32-Natsu** [comment]
Kustomize uses an old version of go-getter so that may be the cause. Kustomize also has a backup cloner which uses native git command which will use `depth=1`. And go-getter has some known issues. Some discussions [here](https://github.com/kubernetes-sigs/kustomize/issues/2538)

**Comment by xakraz** [comment]
Thanks for the leads and the background.

What can I do to make it work as expected ?
Can I try something to identify clearly if it is a `go-getter` or the "backup cloner" issue ?
Should I upgrade go the latest version of `kustomize` ?

**Comment by Shell32-Natsu** [comment]
If you can construct your resource URL with a valid format but make `go-getter` fail, the backup cloner will be used. I know this sounds tricky but the `go-getter` we are using is very buggy and has a lot of unexpected behavior. We are considering to remove it.

**Comment by xakraz** [comment]
Hi @Shell32-Natsu, sorry for the delay of my answer ...

So I have double checked many things (URL format, `kustomize` versions, ...).
Since starting `v4`, `kustomize` will only support Git / http remote resources, and has built-in `depth-1` option, I have finally tested our current manifests with the latest release : `v4.0.5`

I stumble upon an issue, which is not really related to this one.
Maybe I should also post this message in a new/other issue.

Nevertheless, as you can read, we are using `ref=SHORT_COMMIT_ID` to pin our remote resources.
On one manifet (I haeve only tested one sofar), `kustomize build` fails with the short revision sha1 but succeed with the long one. Is it an issue I should dig in or is it the expected behavior ?

Thanks again for your time 🙏🏻

**Comment by Shell32-Natsu** [comment]
Hi @xakraz, thanks for your investigation! Perhaps you should create a new issue about the short commit ID and attach your error messages.

**Comment by xakraz** [comment]
Closing since kustomize > 4.x has a different way to handle remote resource.

Thx @Shell32-Natsu
