### ISSUE TITLE
yaml: invalid trailing UTF-8 octet (Kustomize parse errors)

### ISSUE THREAD

**Issue by bhagyesh18** [kubernetes-sigs/kustomize#3717]
## Summary

Issue while kustomize the Helm Chart. 

**Error:** `yaml: invalid trailing UTF-8 octet`

**Error as below**

```
Error: map[string]interface {}{"apiVersion":"rbac.authorization.k8s.io/v1beta1", "kind":"ClusterRole", "metadata":map[string]interface {}{"labels":map[string]interface {}{"app":"cert-manager", "app.kubernetes.io/instance":"gitlab", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"cert-manager", "helm.sh/chart":"certmanager-v0.10.1"}, "name":"gitlab-cert-manager-controller-certificates"}, "rules":[]interface {}{map[string]interface {}{"apiGroups":[]interface {}{"certmanager.k8s.io"}, "resources":[]interface {}{"certificates", "certificates/status", "certificaterequests", "certificaterequests/status"}, "verbs":[]interface {}{"update"}}, map[string]interface {}{"apiGroups":[]interface {}{"certmanager.k8s.io"}, "resources":[]interface {}{"certificates", "certificaterequests", "clusterissuers", "issuers", "orders"}, "verbs":[]interface {}{"get", "list", "watch"}}, map[string]interface {}{"apiGroups":[]interface {}{"certmanager.k8s.io"}, "resources":[]interface {}{"certificates/finalizers"}, "verbs":[]interface {}{"update"}}, map[string]interface {}{"apiGroups":[]interface {}{"certmanager.k8s.io"}, "resources":[]interface {}{"orders"}, "verbs":[]interface {}{"create", "delete"}}, map[string]interface {}{"apiGroups":[]interface {}{""}, "resources":[]interface {}{"secrets"}, "verbs":[]interface {}{"get", "list", "watch", "create", "update", "delete"}}, map[string]interface {}{"apiGroups":[]interface {}{""}, "resources":[]interface {}{"events"}, "verbs":[]interface {}{"create", "patch"}}}}: yaml: invalid trailing UTF-8 octet

```

There are some places with the non-UTF-8 character in maifest file. 
Image of non-UTF-8 Character [Image of NON UTF-8 CHARS FOUND IN MY MANIFEST](https://ibb.co/r4fcCzK)

I found this non-UTF-8 character. After I replaced it with regular space, it solved the issue.

## Steps to reproduce

**Using Kustomize**

`kustomize build . `

I am not patching yet and I have all rendered manifest data in all.YAML using command helm install --dry-run

```
# Kustomization.yaml
resources:
  - all.yaml
```

and I am having the following issues running command `kustomize build . `.

```
Error: map[string]interface {}{"apiVersion":"rbac.authorization.k8s.io/v1beta1", "kind":"ClusterRole", "metadata":map[string]interface {}{"labels":map[string]interface {}{"app":"cert-manager", "app.kubernetes.io/instance":"gitlab", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"cert-manager", "helm.sh/chart":"certmanager-v0.10.1"}, "name":"gitlab-cert-manager-controller-certificates"}, "rules":[]interface {}{map[string]interface {}{"apiGroups":[]interface {}{"certmanager.k8s.io"}, "resources":[]interface {}{"certificates", "certificates/status", "certificaterequests", "certificaterequests/status"}, "verbs":[]interface {}{"update"}}, map[string]interface {}{"apiGroups":[]interface {}{"certmanager.k8s.io"}, "resources":[]interface {}{"certificates", "certificaterequests", "clusterissuers", "issuers", "orders"}, "verbs":[]interface {}{"get", "list", "watch"}}, map[string]interface {}{"apiGroups":[]interface {}{"certmanager.k8s.io"}, "resources":[]interface {}{"certificates/finalizers"}, "verbs":[]interface {}{"update"}}, map[string]interface {}{"apiGroups":[]interface {}{"certmanager.k8s.io"}, "resources":[]interface {}{"orders"}, "verbs":[]interface {}{"create", "delete"}}, map[string]interface {}{"apiGroups":[]interface {}{""}, "resources":[]interface {}{"secrets"}, "verbs":[]interface {}{"get", "list", "watch", "create", "update", "delete"}}, map[string]interface {}{"apiGroups":[]interface {}{""}, "resources":[]interface {}{"events"}, "verbs":[]interface {}{"create", "patch"}}}}: yaml: invalid trailing UTF-8 octet

```

## Configuration used

There were few patches that I needed to apply on top of the GitLab helm chart and I used kustomize for that. Using helm command to deploy GitLab into Kubernetes works without any error. However, the kustomize command fails to parse YAML generated by the helm command. 

## Versions
- Kustomize Version :
  - {Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:linux GoArch:amd64}
- Chart: GitLab-4.9.1.tgz
- Helm: (`helm version`)
  - BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
- Operating: (`Operating System`)
  - NAME="Red Hat Enterprise Linux Server"
  - VERSION="7.6 (Maipo)"

## Relevant logs

I was stressed out to find the problem in kustomize, but there is an issue in rendered YAML. Also, Rendered YAML is more than 15,000 lines, very thought to identify the issues. 
Should I expect kustomize that there is a bug in kustomize to ignoring these non-utf-8 chars? if it is, it is a bug in kustomize.

**Comment by Shell32-Natsu** [comment]
From your description I think this is not an issue in kustomize. Kustomize uses `go-yaml` to pass YAML files and the error is thrown from there. Meanwhile I suspect is a YAML file with non-utf8 characters valid.

**Comment by bhagyesh18** [comment]
you mean "you suspect that YAML file with non-utf8 characters is invalid" 
Image of non-UTF-8 Character [Image of NON UTF-8 CHARS FOUND IN MY MANIFEST](https://ibb.co/r4fcCzK)

So there is issue my YAML file which has some weird space (non UTF-8 char)

**Comment by Shell32-Natsu** [comment]
Yes, you should have some issues before kustomize engaged.
