### ISSUE TITLE
Use Internal Error Library throughout Application to Display More Descriptive Error Messages (8) #278

### ISSUE THREAD

**Issue by seans3** [kubernetes-sigs/kustomize#372]
This issue is transferred from: https://github.com/kubernetes/kubectl/issues/278

Mainly we want to be able to return a list of errors, if it makes sense. The previous issue is:

 Check correctness of PATCH - that it applies correctly to an object that it finds
  Resources parse as objects
  Options are well formed - ApplicationManifest schema parses
  replacement for lint. lint is going to call this
  hierarchy of errors
  may depend on technical debt (file system) issue
e.g.

Filenot found errors

This issue may be obsolete--please groom.

**Comment by Liujingfang1** [comment]
I think we have done this especially for decoding yaml files.
