### ISSUE TITLE
Remote builds randomly timeout:  hit 27s timeout running '/usr/bin/git fetch --depth=1 origin master'

### ISSUE THREAD

**Issue by VackarAfzal** [kubernetes-sigs/kustomize#3742]
When running a build on an overlay containing multiple remote components, I randomly get timeouts

**Expected output**

Should build the overlay as expected

**Actual output**

Sometimes builds, but sometimes fails with this error message
```
Error: accumulating resources: accumulation err='accumulating resources from 'git@***************?ref=master': evalsymlink failure on '*********************** 
no such file or directory': hit 27s timeout running '/usr/bin/git fetch --depth=1 origin master'
```
**Kustomize version**

```
{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:darwin GoArch:amd64}
```

**Platform**

```
Linux/macOS
```

**Additional context**

I upgraded from 2.x to 4.x then saw this behaviour appear

**Comment by mxrss2** [comment]
https://github.com/kubernetes-sigs/kustomize/blob/017a0944383d28378ae7a2f063a630b6c124b16c/api/internal/git/gitrunner.go

@VackarAfzal  this is the code that does this -- may be an opportunity to add in a PR to override this cause its suboptimal to not be able to override it.

**Comment by daxmc99** [comment]
Adding `?timeout=90s` to the query parameters can now fix this per https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md

**Comment by Zia-Eurus** [comment]
@daxmc99 how to specify this timeout variable. can you please give a sample example?

**Comment by jasonicarter** [comment]
> @daxmc99 how to specify this timeout variable. can you please give a sample example?

This is an Airbyte example, where the `timeout=90s` is appended at the end (works for me)
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/airbytehq/airbyte.git/kube/overlays/stable?ref=master&timeout=90s
  ```

**Comment by bkanuka** [comment]
While this "works", I am currently using a remote base, which _itself_ uses a remote base that times out. This means I cannot modify the url to append the timeout.  Is there a way to adjust the remote timeout globally for kustomize?
