### ISSUE TITLE
Update docs to reflect flag hyphenation

### ISSUE THREAD

**Issue by SaschaHeyer** [kubernetes-sigs/kustomize#3746]
**Describe the bug**

The following command runs into an error

```
kustomize build --load_restrictor none
```

Error
```
Error: unknown flag: --load_restrictor
```
**Files that can reproduce the issue**

Command itself

**Expected output**

no error

**Actual output**

error

**Kustomize version**

{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:darwin GoArch:amd64}

**Platform**

mac

**Additional context**

/

**Comment by KnVerey** [comment]
In version 4+, the flag is hyphenated:

```
      --load-restrictor string   if set to 'LoadRestrictionsNone', local kustomizations may load files from outside their root. This does, however, break the relocatability of the kustomization. (default "LoadRestrictionsRootOnly")
```

**Comment by SaschaHeyer** [comment]
Thanks a lot for your very quick feedback Katrina.
Very much appreciated. 

That explains the behavior. Backreported it to kubeflow where the issue appears. 
Will close this ticket

**Comment by solarmosaic-kflorence** [comment]
@SaschaHeyer @KnVerey can we re-open this to get the documentation updated? https://kubectl.docs.kubernetes.io/faq/kustomize/#security-file-foo-is-not-in-or-below-bar -- this still mentions `--load_restrictor`

**Comment by solarmosaic-kflorence** [comment]
Caused by https://github.com/kubernetes-sigs/kustomize/pull/3601

**Comment by KnVerey** [comment]
/reopen
/retitle Update docs to reflect flag hyphenation
/help

Docs are generated from https://github.com/kubernetes-sigs/cli-experimental if you have a moment to help with this

**Comment by natasha41575** [comment]
This is fixed by https://github.com/kubernetes-sigs/cli-experimental/pull/185
