### ISSUE TITLE
[Question] Correct capitalization for fieldPath

### ISSUE THREAD

**Issue by yanniszark** [kubernetes-sigs/kustomize#3751]
The `fieldPath` field appears in `vars` and `valueAddTransformer`:
https://github.com/kubernetes-sigs/kustomize/blob/46524d3b6a90f5a08bae3e5a2cdc8b38111b5220/api/types/var.go#L68
https://github.com/kubernetes-sigs/kustomize/blob/e783af2881ae4ba57ba8011a1c854c84842484c0/plugin/builtin/valueaddtransformer/ValueAddTransformer.go#L46-L47

However, it's capitalized as `fieldpath` in the `vars` doc:
https://github.com/kubernetes-sigs/kustomize/blob/a8ece4b5f764e82b5087cf37848fd8d85044ad3b/examples/zh/vars.md#L117

Because Go's JSON library does a case-insensitive matching, both values work:
https://golang.org/pkg/encoding/json/#Unmarshal

What is the correct/recommended capitalization? We should fix the code / docs to reflect that.
cc @davidspek who noticed the vars doc
cc @monopole @Shell32-Natsu

**Comment by Shell32-Natsu** [comment]
I believe we should fix the doc.

**Comment by DavidSpek** [comment]
bump
