### ISSUE TITLE
Update docs for new labels field

### ISSUE THREAD

**Issue by Shell32-Natsu** [kubernetes-sigs/kustomize#3756]
#3743 adds a new field `labels` to the kustomization. The doc pages are needed to be updated.

 - https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
 - https://kubectl.docs.kubernetes.io/guides/config_management/labels_annotations/
 - https://kubectl.docs.kubernetes.io/guides/extending_kustomize/builtins/#usage-via-kustomizationyaml-3

#1009: Discussion about new `labels` field.

**Comment by keidevs** [comment]
When will the documentation be completed?

@Shell32-Natsu

**Comment by rdxmb** [comment]
@Shell32-Natsu why is the update of the docs a labelled with `help wanted` ? For me, `help wanted` sounds like a question for support.

**Comment by natasha41575** [comment]
The `labels` field is now documented.
