### ISSUE TITLE
Chart inflator plugin doesn't work when called via Component or Kustomization and relative paths

### ISSUE THREAD

**Issue by snuggie12** [kubernetes-sigs/kustomize#3760]
**Describe the bug**
Given the following directory structure:
```
.
├── components
│   └── prometheus-rules-helm
│       ├── prometheus-rules
│       │   ├── Chart.yaml
│       │   ├── templates
│       │   │   ├── external4xx.yaml
│       │   │   ├── external5xx.yaml
│       │   │   ├── internal4xx.yaml
│       │   │   └── internal5xx.yaml
│       │   └── values.yaml
│       ├── helm-chart.yaml
│       ├── helm-values.yaml
│       └── kustomization.yaml
├── dev
│   ├── kustomization.yaml

```
When dev either calls a `Component` or a `Kustomization` to the remote directory and `chartHome` is set to a relative path the chart will fail to generate. If I call `kustomize build` in the `components` directory everything works fine.

**Files that can reproduce the issue**

./components/prometheus-rules-helm/kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

generators:
  - helm-chart.yaml
```
./components/prometheus-rules-helm/helm-chart.yaml
```
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: prometheus-rules
# chartHome: /Users/foo/bar/baz/components/prometheus-rules-helm # this does work but doesn't transfer well to other users or argocd
chartHome: ./
chartName: prometheus-rules
chartVersion: 0.1.0
releaseName: default
releaseNamespace: default
```
./dev/kustomization.yaml
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../components/prometheus-rules-helm
```
**Expected output**
Will generate files from either directory

**Actual output**
```
Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/Users/foo/bar/baz/components/prometheus-rules-helm': Error: repo stable not found\n: failed to run command helm pull --untar --untardir ./ --version 0.1.0 stable/prometheus-rules"
```

**Kustomize version**

3.9.3

**Platform**
macOS

**Additional context**
Is there a way to do ssh for the repoURL? I could always host this in another repo, but don't have a helm chart repo or an easy way to do https based git.

**Comment by snuggie12** [comment]
If it helps determine the bug, I can get it to build if my CWD is `prometheus-rules-helm` and I `kustomize build ../../dev/`

However, I tried setting `chartHome` to `../components/prometheus-rules-helm` and running `kustomize build` from `dev` and that did not work. The idea being that while my CWD is `dev` that `chartHome` would have been interpreted from there.

So it seems something funny is going on with what directory kustomize is in when it is loading the plugin.

Also, when I run it locally in `prometheus-rules-helm`, `kustomize-values.yaml` gets written to `prometheus-rules` which I thought it was supposed to use some tmpdir?

**Comment by snuggie12** [comment]
Looks like maybe there was a similar problem with #3435 for the values file. Perhaps a similar fix can be done for `chartHome`?

Also, I think I'm close to a scenario where I don't need to specify `chartHome`, but would need #3762 working first. If that's more doable I suppose we could close this.

**Comment by natasha41575** [comment]
@Shell32-Natsu can you take a look if you have time?

**Comment by Shell32-Natsu** [comment]
Yes I will.

**Comment by jlewi** [comment]
Is this just a matter of setting the working directory when invoking helm here:
https://github.com/kubernetes-sigs/kustomize/blob/558995536d7570fb6f9dd02f07f6ffa58f46cda3/plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go#L92

Is there a way for the plugin to get the directory of the kustomization.yaml file?

**Comment by snuggie12** [comment]
I don't code, but I thought it was the wrong CWD at this point: https://github.com/kubernetes-sigs/kustomize/blob/558995536d7570fb6f9dd02f07f6ffa58f46cda3/plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go#L278

**Comment by jlewi** [comment]
Relative paths in helm files appear to work just fine using the latest version v4.1.2.

I was hitting the problem with v3.8.7.

@snuggie12 does upgrading to v4.1 work for you?

**Comment by snuggie12** [comment]
@jlewi sorry, been out of commission the past few days.

Yes, I was able to get things working with 4.1.X

**Comment by pickfire** [comment]
Do we need to wait for the next kubectl release to get this kustomize if we don't want to install kustomize separately?
