### ISSUE TITLE
Pass helm home env vars to chart inflator

### ISSUE THREAD

**Issue by snuggie12** [kubernetes-sigs/kustomize#3762]
**Is your feature request related to a problem? Please describe.**
Been having issues trying to use the chart inflator with a self-created chart. One way I might be able to get around it is by setting `chartRelease` and `helmHome` but with the defaults on my laptop it presumes cache, data, and config are sub-directories of a `helmHome`. 

**Describe the solution you'd like**
Originally I was going to ask for a `helmCacheHome` attribute, but I need this to work on my laptop and on argocd which would still mean making a directory structure that fits the code.

Instead, was curious if it was possible to just accept specific env vars like `HELM_CACHE_HOME` and if supplied use that as the value. This would allow env vars to do exactly what their supposed to do and can vary from system to system.

**Describe alternatives you've considered**
As I said, I can make all of our users and argocd setup a specific directory structure that works, but this seems pretty feasible.

**Additional context**

**Comment by mikebz** [comment]
What about just using helm to inflate things directly without using the plugin?

**Comment by snuggie12** [comment]
> What about just using helm to inflate things directly without using the plugin?

As in run `helm template foo > ./file.yaml`?? Doesn't work with a gitops style setup.

We have since worked around this by just creating a fake directory structure containing symlinks to the correct directories, but if you look at the table [here](https://helm.sh/docs/helm/helm/#helm) (apologies on behalf of helm's website that there is no anchor. you should search for "default directories depend on the Operating System") you'll see that the pattern kustomize established doesn't match up with any of the 3 official OS layouts.

If you were able to set env vars it'd be far easier than telling each developer to run a script setting up a fake directory structure of symlinks IMO.

**Comment by jkroepke** [comment]
@snuggie12 did you verify the issue still exists after https://github.com/kubernetes-sigs/kustomize/pull/3713 ?

**Comment by jkroepke** [comment]
An other use case is using the BuildContext of ArgoCD (https://argoproj.github.io/argo-cd/user-guide/build-environment/) to push notification back to the CI system though ArgoCD hooks.

**Comment by romachalm** [comment]
@jkroepke I have still this issue with kustomize 4.2

```json
{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-06-30T22:49:26Z GoOs:darwin GoArch:amd64}
```

I try to access helmCharts from private repos already configured in system. 
Therefore, I set the envar HELM_CONFIG_HOME top point at my local helm config : 
```
export HELM_CONFIG_HOME=/Users/rchalumeau/.helm
kustomize build . --load-restrictor LoadRestrictionsNone --enable-helm
```

The HELM_CONFIG_HOME keeps being set with the tmpdir : 
```
Error: Error: looks like "https://registry.xxx.io/chartrepo/charts" is not a valid chart repository or cannot be reached: failed to fetch https://registry.xxx.io/chartrepo/charts/index.yaml : 401 Unauthorized
: unable to run: 'helm pull --untar --untardir /Users/rchalumeau/go/src/gitlab.xxx.io/infra/calleocho/c8-knative/overlays/launchpad/dev/charts --repo https://registry.xxx.io/chartrepo/charts istio-ingress --version 1.1.0' 
with env=[
  HELM_CONFIG_HOME=/var/folders/cp/m2m62bv16gn_d9q5q81jqhf99rwcdq/T/kustomize-helm-458991679/helm 
  HELM_CACHE_HOME=/var/folders/cp/m2m62bv16gn_d9q5q81jqhf99rwcdq/T/kustomize-helm-458991679/helm/.cache 
  HELM_DATA_HOME=/var/folders/cp/m2m62bv16gn_d9q5q81jqhf99rwcdq/T/kustomize-helm-458991679/helm/.data
] 
(is 'helm' installed?)
```

I have also tried with `-e` flag, with no more success.

**Comment by snuggie12** [comment]
I just tested with 4.4.1 and looks like it still has the wrong env vars.

/remove-lifecycle rotten

**Comment by mikebz** [comment]
Another question - why if we just default to the current environment variables (or lack of them).  I am thinking about yanking the variables set in the builtin.
