### ISSUE TITLE
Error formating is not good

### ISSUE THREAD

**Issue by ghost** [kubernetes-sigs/kustomize#3763]
Why are the errors reported like this:

> Error: accumulating resources: 2 errors occurred:
        * accumulateFile error: "accumulating resources from '../../../../blahblah/overlays/development/someone-qa': '/home/alex/dev/company/ml-pipelines/manifests/blahblah/overlays/development/someone-qa' must resolve to a file"
        * accumulateDirector error: "recursed accumulation of path '/home/alex/dev/company/ml-pipelines/manifests/blahblah/overlays/development/someone-qa': accumulating resources: 2 errors occurred:\n\t* accumulateFile error: \"accumulating resources from '../../../base/tf-serving-gpu/': '/home/alex/dev/company/ml-pipelines/manifests/blahblah/base/tf-serving-gpu' must resolve to a file\"\n\t* accumulateDirector error: \"recursed accumulation of path '/home/alex/dev/company/ml-pipelines/manifests/blahblah/base/tf-serving-gpu': yaml: unmarshal errors:\\n  line 31: mapping key \\\"resources\\\" already defined at line 30\"\n\n"

The `\n` and `\t` all over the place make it look like something is going wrong? 

It really makes working the kustomze difficult and tedious. My heart sinks every time i see one of these messages.

{Version:kustomize/v3.9.2 GitCommit:e98eada7365fc564c9aba392e954f306a9cbf1dd BuildDate:2021-01-17T17:44:16Z GoOs:linux GoArch:amd64}

**Comment by Shell32-Natsu** [comment]
I believe the this error report has be changed in v4.0+, can you try it?

**Comment by whillas** [comment]
Great! I can't upgrade right now as everytime we use a different version we get different hashes fro configmaps and secrets and so _everything_ gets redeployed. Thanks anyway

**Comment by Shell32-Natsu** [comment]
Well, when I say "changed" I mean the format has been changed but it may not become *better*. :(
