### ISSUE TITLE
Unable to set replicas in kustomization.yaml

### ISSUE THREAD

**Issue by A830612** [kubernetes-sigs/kustomize#3769]
Unable to set replicas in kustomization.yml

**Files that can reproduce the issue**

**Expected output**

sets the replicas in the yaml file

**Actual output**

Error: json: unknown field "replicas"

**Kustomize version**

Kustomize version -
{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T22:48:12+00:00 GoOs:darwin GoArch:amd64}

**Platform**

macOS and Linux

**Comment by A830612** [comment]
![image](https://user-images.githubusercontent.com/1132918/113145040-f2210080-91fb-11eb-83b1-28a55ed4c70d.png)

**Comment by A830612** [comment]
Command ran - k kustomize path/to/kustomization.yaml

**Comment by natasha41575** [comment]
Could you provide a set of files that can reproduce the issue and the full command that you ran?
