### ISSUE TITLE
help/support: Composing manifests from reusable components

### ISSUE THREAD

**Issue by madhukar93** [kubernetes-sigs/kustomize#3785]
If I have deployments A, B, C that differ in minor ways -  the command and some labels are different  (eg: there’s a rails app for which we are running separate deployments for a JSON API, web admin panel, and Sidekiq workers - all running the same container).
Is there a way to represent the commonalities in Kustomize without having separate resource files for each of them?
I’m trying to understand if this is what Kustomize components do. I guess YAML anchors would do the job if everything was in the same file.

**Comment by Shell32-Natsu** [comment]
Doesn't base/overlay model work for you? You can put the common parts in the base and apply different transformers in different overlays.

**Comment by madhukar93** [comment]
what I'm trying is keeping the base deployment bare, with spec as null - basically just a with metadata.name, and applying patches to it for everything else as components
