### ISSUE TITLE
[Question]Is there a way to pause kustomize step until the operator successfully built on openshift?

### ISSUE THREAD

**Issue by cloudfather** [kubernetes-sigs/kustomize#3804]
I use kustomize to build all the requirements to install openshift operator and after that to create an instance from the operator.
to do it I have to run kustomization.yaml two times to ensure that everything is built.
In the first run, it always shows an error about missing crds.

**Comment by Shell32-Natsu** [comment]
Could you please provide more information about why do you need to run 2 times?

**Comment by cloudfather** [comment]
I put all the yaml files in one place for the topic.
so, for instance, In the same directory.
- installing the operator
- adding operator group
- RBAC
- create an instance.

if it is not a good practice, could you please propose something else?

Apreciated

**Comment by Shell32-Natsu** [comment]
It will be good to give us a subset of your files which can reproduce the error.

**Comment by cloudfather** [comment]
here is the example I was talking about.
https://github.com/cloudfather/argocd-deploy

**Comment by cloudfather** [comment]
was missleading. sorry for that ;)
