### ISSUE TITLE
Kustomize prefix does not prefix service.name, when using ingress apiVersion: networking.k8s.io/v1

### ISSUE THREAD

**Issue by svetlanatiffonet** [kubernetes-sigs/kustomize#3814]
I use kustomize to generate the full yaml to apply. I updated the ingress api version from `networking.k8s.io/v1beta1` to `networking.k8s.io/v1`. In the main kustomize file, I use "namePrefix". With the new ingress api version, `service.name` is not prefixed whereas with the old version `serviceName` was prefixed

With version networking.k8s.io/v1beta1: 
`kubectl kustomize .`

Renders : 
```apiVersion: v1
kind: Service
metadata:
  name: myprefix-kafka-manager-service
spec:
  clusterIP: None
  ports:
  - name: kafka-manager
    port: 9000
    protocol: TCP
    targetPort: kafka-manager
  selector:
    selecteur: my-kafka-manager
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: myprefix-kafka-manager-ingress
spec:
  rules:
  - host: myhost
    http:
      paths:
      - backend:
          serviceName: myprefix-kafka-manager-service
          servicePort: 9000
        path: /
```

With version networking.k8s.io/v1: 
`kubectl kustomize .`

Renders : 
```apiVersion: v1
kind: Service
metadata:
  name: myprefix-kafka-manager-service
spec:
  clusterIP: None
  ports:
  - name: kafka-manager
    port: 9000
    protocol: TCP
    targetPort: kafka-manager
  selector:
    selecteur: my-kafka-manager
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: myprefix-kafka-manager-ingress
spec:
  rules:
  - host: myhost
    http:
      paths:
      - backend:
          service:
            name: kafka-manager-service
            port:
              number: 9000
        path: /
        pathType: Prefix
```

**Files that can reproduce the issue**

[ingress.zip](https://github.com/kubernetes-sigs/kustomize/files/6326259/ingress.zip)

**Expected output**
I expect the kustomize command to output: 
```
      - backend:
          service:
            name: myprefix-kafka-manager-service
```

Whole Ingress output expected

```apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: myprefix-kafka-manager-ingress
spec:
  rules:
  - host: myhost
    http:
      paths:
      - backend:
          service:
            name: myprefix-kafka-manager-service
            port:
              number: 9000
        path: /
        pathType: Prefix
```

**Actual output**
See abiove (in description)

**Kustomize version**
`kubectl version`
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-31T15:33:39Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

**Platform**
Linux

**Additional context**

**Comment by natasha41575** [comment]
Could you try using kubectl 1.21? The version of kustomize shipped with prior versions of kustomize is quite old (v2), while kubectl 1.21 should be shipped with kustomize v4. 

Taking a look at kustomize's list of name references I would expect this to work with the current version of kustomize.

https://github.com/kubernetes-sigs/kustomize/blob/f8dad80a79f9d64776dfb27a3eb7c8d4b0835275/api/konfig/builtinpluginconsts/namereference.go#L281-282

**Comment by natasha41575** [comment]
Could you try with kubectl v1.21? The version of kustomize shipped with prior versions of kubectl is quite old (v2), but kubectl v1.21 is shipped with kustomize v4. Based on kustomize's list of name references, I would expect this to work with the current version of kustomize. 

https://github.com/kubernetes-sigs/kustomize/blob/f8dad80a79f9d64776dfb27a3eb7c8d4b0835275/api/konfig/builtinpluginconsts/namereference.go#L281-L282

**Comment by svetlanatiffonet** [comment]
It works. Thanks !
