### ISSUE TITLE
helmCharts doesn't support --skip-tests

### ISSUE THREAD

**Issue by qkflies** [kubernetes-sigs/kustomize#3831]
Adding onto the chain for #3815, #3816, #3819, etc.

Would like to ensure that the helm plugin has support for passing the argument `--skip-tests` as well, during the `helm template` step.

Thanks!

**Comment by monopole** [comment]
Keeping this open for investigation.

However, see https://github.com/kubernetes-sigs/kustomize/issues/3815#issuecomment-825820444 for more background on helm issues.

**Comment by bhester01** [comment]
bumping this issue. Most chart tests break CI/CD linting of yaml output as the tests don't follow basic security

**Comment by hans-d** [comment]
https://github.com/kubernetes-sigs/kustomize/issues/3815#issuecomment-825820444 remarks that anything that can be done by kustomize should be done by kustomize. As kustomize does not provide a delete (see https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/), this parameter is needed.

Besides breaking on linting issues, it will also add resources that should not be part of the deployment (as helm will delete them after the test has been run if deploying normally with helm and allowing for tests)

Regarding the workflow mentioned in the comment, a safe way and having config explicitly stored in kustomazation.yaml:
- inflate the helmchart using kustomize helm chart inflator, eg in `vendor/kustomization.yaml`
- store the output to a folder, eg `kustomize build vendor > vendor/generated/vendor.yaml`
- add kustomization.yaml `cd vendor/generated && kustomize create --autodetect`
- commit results:
  - `vendor/kustomization.yaml` (with the helm options)
  - the downloaded charts (exclude the .tgz folders) in `vendor/charts`
  - `vendor/generated/*`
- use `generated/` as resource in `base/kustomization.yaml`

that way only the location of where to store the output of `kustomize build` is outside the kustomization.yaml
