### ISSUE TITLE
Tutorial editor not working

### ISSUE THREAD

**Issue by robax** [kubernetes-sigs/kustomize#3842]
**Describe the bug**

The web editor available at https://kustomize.io/tutorial is not working

**Files that can reproduce the issue**

Any yaml file.

**Expected output**

A patch in the right-hand panel is supposed to be generated.

**Actual output**

No patch is generated, and the endpoint appears to 500 in a call to JSON.parse().

**Additional context**

Possible duplicate of https://github.com/kubernetes-sigs/kustomize/issues/2190#issuecomment-827261765

**Comment by robax** [comment]
@natasha41575 Would you happen to know who maintains the kustomize.io site or if it's abandoned?

**Comment by natasha41575** [comment]
I'm really not sure about kustomize.io; https://kubectl.docs.kubernetes.io/references/ is where the core documentation is.

@Shell32-Natsu @monopole Where is kustomize.io maintained and is it still in use?

**Comment by irgeek** [comment]
At the bottom of the kustomize.io site is says:

> Website contributed by [Replicated](https://replicated.com/)

I looked through the repos under [their GitHub org](https://github.com/replicatedhq), but I don't see one for kustomize.io.

I did a quick correlation of contributors to this repository and people in the Replicated org and I managed to find @laverya -- maybe they can find out internally how the kustomize.io site is managed and help to get the tutorial page either fixed or removed.

**Comment by natasha41575** [comment]
/remove-lifecycle stale

I have the contact email of someone at replicated and I will be reaching out to them shortly

**Comment by gruberdev** [comment]
Any update on this? It seems the tutorial still does not work. 

The reason as to why it stopped working seems to be a problem with this specific endpoint: [api.kustomize.io/kustomize/patch](https://api.kustomize.io/kustomize/patch) because the [/apply](https://api.kustomize.io/kustomize/apply) endpoint, which is called upon trying to modify a manifest, successfully answers the requests.

**Comment by natasha41575** [comment]
kustomize.io is not a domain that belongs to us. We are still working with the people who own it to get it transferred.

**Comment by natasha41575** [comment]
kustomize.io and general docs progress will be tracked in #4338
