### ISSUE TITLE
Temp filepath incorrect when chart has a forward slash in the name

### ISSUE THREAD

**Issue by snuggie12** [kubernetes-sigs/kustomize#3851]
**Describe the bug**
When trying to install an artifactory helm chart via the generator we are getting errors that a directory can't be found. That's due to the chart name literally being `jfrog/artifactory`.

**Files that can reproduce the issue**
```
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: artifactory
chartName: jfrog/artifactory
chartRepoUrl: "https://repo.chartcenter.io"
chartVersion: "11.4.4"
releaseName: artifactory
releaseNamespace: jfrog
```

**Expected output**

**Actual output**
```
Error: open /private/var/folders/dq/tf5dnbm131x_5fhkwxjzt7440000gn/T/kustomize-743692074/chart/jfrog/artifactory/kustomize-values.yaml: no such file or directory
# I imagine it's supposed to be jfrog\/artifactory
```

**Kustomize version**
4.1.0

**Platform**
macOS

**Additional context**
Haven't tried the new helm stuff (non generator) so if that works can I get an example?

**Comment by Shell32-Natsu** [comment]
I am not sure chart name with forward slash in chart name is fully supported in helm. https://github.com/helm/helm/issues/9017

**Comment by snuggie12** [comment]
Well, I don't disagree that it's a bad pattern, but it seems easy enough to fix on the kustomize side. 

What do you suggest? Make an issue with jfrog?

**Comment by snuggie12** [comment]
Though it does seem to be frowned upon in helm 3, I guess `/` is more common with OCI registries so I think this will have to be solved eventually.

FWIW I tried to make a PR for this, but don't know golang very well and after successfully running `helm pull` by making the directory `jfrog-artifactory` instead of two directories it actually names the directory/tgz `artifactory`.
