### ISSUE TITLE
Remote Resource + OpenAPI -> CRD patches overwrite instead of merge (schema ignored)

### ISSUE THREAD

**Issue by iamnoah** [kubernetes-sigs/kustomize#3852]
**Describe the bug**

A kustomization that combines a remote resource and a resource using openapi schema may result in the openapi schema (openapi.path) being ignored, and custom resources not being correctly merged.

See here: https://github.com/iamnoah/kustomize-remote-crd-merge-bug

**Expected output**

The containers of the two `MyKind` CRDs should be merged by name.

**Actual output**

The array of containers from the patch overwrites the base and the special container is lost.

**Kustomize version**

4.1.2

**Platform**

macOS

**Additional context**

I've shown in my test repo that reordering may fix the issue there, but since the corruption doesn't necessarily produce an error on apply, it is hard to know if anything else is being corrupted, especially in the larger project this was found in, with multiple remote resources that may also include CRDs.

**Comment by sshiba** [comment]
I am experiencing same issue on Ubuntu 18.04.

**Comment by natasha41575** [comment]
you have to edit the document provided by kustomize openapi fetch with the correct merge keys and patch strategy, see the extensions x-kubernetes-patch-merge-key and x-kuberenetes-patch-strategy in the docs here: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/openapi/

**Comment by natasha41575** [comment]
I believe `x-kubernetes-merge-key` and `x-kubernetes-patch-strategy` can only be set when the type is array (i.e. at the same level as `type:array` in the schema). I see you've set it in other places where kustomize can't do anything with it (e.g. [this line](https://github.com/iamnoah/kustomize-remote-crd-merge-bug/blob/e8766c17b109686e2536f3e41ffdfaf0aabf2403/base/crds.json#L378)) because it's set on a property of type string.

You can see the builtin OpenAPI schema as a reference for where these extensions are allowed: https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/openapi/kubernetesapi/v1204/swagger.json

**Comment by natasha41575** [comment]
Closing because this is not a bug with kustomize, and more to do with a lack of clarity on where and how the patch extensions should be used. Hopefully some day we will have an automatic tool for this.

**Comment by iamnoah** [comment]
@natasha41575 please run the examples in the repo. There is different output based on the ordering in `resources:`. There do appear to be some invalid annotations (which, by the way, are from the output of kustomize's openapi dump command) but there are valid annotations on array objects that are merged in one case but not the other.

**Comment by natasha41575** [comment]
Sorry - github has been behaving kind of strangely for me and I meant to edit a previous comment and see it's been removed instead.

Repeating that comment here for people who look at this later:

I believe `x-kubernetes-patch-merge-key` and `x-kubernetes-patch-strategy` are only supposed to be used with objects of type array and I see some places in that repo where they are placed on objects of type string. 

Anyways - I'll run the examples in the repo. Thank you for bringing the reordering issue to our attention, I'll take a look when I can.

**Comment by madhukar93** [comment]
@natasha41575 I've tried the same with an array of objects as well (for the [data in external secrets](https://github.com/external-secrets/kubernetes-external-secrets/blob/master/charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml#L77)), and didn't have success either. I shall also push an example to demonstrate.

**Comment by iamnoah** [comment]
FWIW, I have updated my sample repo to remove the invalid annotations and the problem persists.

**Comment by iamnoah** [comment]
Just an update: This is still an issue as of Kustomize 4.2.0

```shell
> kustomize version
{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-07-01T00:44:28+01:00 GoOs:darwin GoArch:amd64}
```

**Comment by iamnoah** [comment]
I can't reproduce this in v4.4.1, so I supposed we can /close
