### ISSUE TITLE
Release notes for v1.0.8 need to be fixed

### ISSUE THREAD

**Issue by m1kola** [kubernetes-sigs/kustomize#387]
Currently [release notes for kustomize v1.0.8](https://github.com/kubernetes-sigs/kustomize/releases/tag/v1.0.8) contain the following:

> will add following content to kustomization.YAML
> 
> ```
>  imageTags:	imageTags:
> - name: nginx	
>   newTag: 1.8.0
> - name: my-app	
>   newTag: latest
> - name: alpine
>   digest: sha256:24a0c4b4a4c0eb97a1aabb8e29f18e917d05abfe1b7a7c07857230879ce7d3d3
> ```

I believe it should be something like this:

> will add following content to kustomization.YAML
> 
> ```
> imageTags:
> - name: nginx	
>   newTag: 1.8.0
> - name: my-app	
>   newTag: latest
> - name: alpine
>   digest: sha256:24a0c4b4a4c0eb97a1aabb8e29f18e917d05abfe1b7a7c07857230879ce7d3d3
> ```

Note duplicated `imageTags:` and space before the first `imageTags:` occurrence.

---

/kind documentation

**Comment by Liujingfang1** [comment]
@m1kola Yes, you are right. Do you want to fix it?
