### ISSUE TITLE
kio.LocalPackageReadWriter should provide file system abstraction

### ISSUE THREAD

**Issue by campoy** [kubernetes-sigs/kustomize#3873]
**Is your feature request related to a problem? Please describe.**

Testing any program using `kio.LocalPackageReadWriter`, `kio.LocalPackageReader`, or `kio.LocalPackageWriter` is quite cumbersome due to its lack of abstraction allowing to fake the file system it reads from. This leads to very complex test cases where temp directories need to be created and destroyed continuously.

**Describe the solution you'd like**

I would like these types to include a [`FileSystem`](https://pkg.go.dev/sigs.k8s.io/kustomize/api/filesys#FileSystem) field in they would use in order to interact with the file system. By default, this would be set to interact with the actual file system so the change would be backwards compatible.

**Describe alternatives you've considered**

There are other packages providing a similar file system abstraction that we could consider.

- [sigs.k8s.io/kustomize/pkg/fs](https://pkg.go.dev/sigs.k8s.io/kustomize/pkg/fs#FileSystem) also provides a FileSystem interface that seems to be very similar, I'm not sure which one we should be using or whether this one in the one mentioned above should be unified eventually.

- Go 1.16 comes with an [`fs`  package](https://golang.org/pkg/io/fs/) but this would force kustomize and all its users to update to Go 1.16, which seems a non-starter.

**If this issue is accepted, I would like to provide a PR I have already been working on.**

**Comment by monopole** [comment]
Thanks!

Just to add some history, the impls of https://pkg.go.dev/sigs.k8s.io/kustomize/api/filesys#FileSystem are both in that package (same package as the ifc).   The main ctors one would use at injection points are

 - [MakeFsOnDisk](https://github.com/kubernetes-sigs/kustomize/blob/master/api/filesys/fsondisk.go#L20)  (for the [kustomize CLI](https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/commands/commands.go#L35) and tests that must have a disk file (e.g. plugin compiler tests)).
 - [MakeFsInMemory](https://github.com/kubernetes-sigs/kustomize/blob/master/api/filesys/fsnode.go#L64) (for the vast majority of tests, e.g. [harness use](https://github.com/kubernetes-sigs/kustomize/blob/master/api/testutils/kusttest/harness.go#L25)).

The goal was to just meet kustomize's IO needs, so no chmod, chown, seeking, truncating, etc.

Despite being in the same package, I think the two impls are independent.  We could move them into subpackages to make that easier to prove, but it hasn't come up.

**Comment by KnVerey** [comment]
/remove-lifecycle stale

The PRs implementing this are all complete; only one left to merge.

**Comment by KnVerey** [comment]
/close

The implementation merged a while ago
