### ISSUE TITLE
`unmarshal errors` from `helmCharts`

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#3878]
**Describe the bug**

`unmarshal errors` when templating helm chart from kustomize

**Files that can reproduce the issue**

kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: ambassador
  releaseName: ambassador
  repo: https://getambassador.io
```

**Expected output**

helm template output

**Actual output**

```sh
❯ kustomize build --enable-helm
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 12: mapping key "app.kubernetes.io/instance" already defined at line 9
  line 28: mapping key "app.kubernetes.io/instance" already defined at line 25
```

**Kustomize version**

```
{Version:kustomize/v4.1.2 GitCommit:a5914abad89e0b18129eaf1acc784f9fe7d21439 BuildDate:2021-04-15T23:23:37+01:00 GoOs:darwin GoArch:amd64}
```

**Platform**

macOS

**Additional context**

n/a

**Comment by eduardo-manrique** [comment]
I'm having this issue in Fluxcd, i guess they could be using the kustomize helmcharts for the postrender, i make them work fixing the duplicate labels in the manifests labels section
