### ISSUE TITLE
Re-enable tests disabled in #3880

### ISSUE THREAD

**Issue by Shell32-Natsu** [kubernetes-sigs/kustomize#3881]
Some tests are disabled in #3880 because the images they use disappeared. 

The images include:
- `gcr.io/kustomize-functions/example-cockroachdb`
- `gcr.io/kustomize-functions/example-tshirt`
- `gcr.io/kustomize-functions/example-validator-kubeval`

**Comment by Shell32-Natsu** [comment]
cc @monopole

**Comment by annasong20** [comment]
/triage accepted

For anyone who wants to pick up this issue, you can
* replace the removed transformer container with [this one](https://github.com/kubernetes-sigs/kustomize/blob/4fc02497ae7de4b1f7e31656e13720d4e719dcc0/cmd/config/internal/commands/e2e/e2econtainerconfig/Makefile). You can reference [this test that uses the container](https://github.com/kubernetes-sigs/kustomize/blob/4fc02497ae7de4b1f7e31656e13720d4e719dcc0/cmd/config/internal/commands/e2e/e2e_test.go#L339)
* look for an existing generator container in the kustomize repo to replace the removed container in the [`TestFnContainerGenerator`](https://github.com/kubernetes-sigs/kustomize/pull/3880/files#diff-34d93fef5d3973a037f7871d2010ebaa89547617081d5f672bac16be3bf88160L92) test. If you can't find such a container in the repo, you can use a simple generator container from [the kpt catalog](https://catalog.kpt.dev/).

**Comment by antoooks** [comment]
Since it's been stale for a while, can I take this over? @yutaroyamanaka 

cc @natasha41575 @annasong20

**Comment by antoooks** [comment]
Seems this issue is already addressed and patch has been merged but somehow it still placed in `TODO:`

https://github.com/kubernetes-sigs/kustomize/pull/5111

I think we can move this.

@natasha41575 @annasong20

**Comment by charles-chenzz** [comment]
/close

resolve by https://github.com/kubernetes-sigs/kustomize/pull/5111
