### ISSUE TITLE
Error still found on "HelloWorld" example

### ISSUE THREAD

**Issue by dove-young** [kubernetes-sigs/kustomize#3896]
Same as issue https://github.com/kubernetes-sigs/kustomize/issues/3479

I am using kubectl v1.20 to run examples in https://github.com/kubernetes-sigs/kustomize/tree/master/examples/helloWorld

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"c8d1f56fb3e20d7ee2b4e0280425ef95a013e9ee", GitTreeState:"clean", BuildDate:"2021-03-20T23:43:28Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+bafe72f", GitCommit:"bafe72fb05eddc8246040b9945ec242b9f805935", GitTreeState:"clean", BuildDate:"2021-03-14T16:01:39Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
```

And I kept slip at error `error: json: unknown field "metadata"`

```kubectl apply -k /tmp/tmp.fRhMynmO20/base
error: json: unknown field "metadata"
```

It can be passed by using `kustomize build`.  But it took me really long time to reach to issue 3479 to find the root cause. 

And there is a follow up question. Since there are always breaking gaps between `kustomize` specs and `kubectl apply -k`, how can I  ship my manifest to customers and wish it should luckly not be broken?

**Comment by Shell32-Natsu** [comment]
Kustomize has been re-integrated with kubectl since kubectl 1.21.0. https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#kustomize-updates-in-kubectl
