### ISSUE TITLE
How to apply nameSuffix or namePrefix to namespace objects?

### ISSUE THREAD

**Issue by KarstenSiemer** [kubernetes-sigs/kustomize#3904]
Since "Avoiding Prefix Transformer for Namespace resource #2742" was merged, nameSuffix or namePrefix isn't applied to namespaces any more.
We heavily relied on that mechanism and cannot update until we've found a solution on how to still apply them to namespace resources.
We dynamically deploy our applications for Github pull requests using argoCD application crd objects. We just apply a nameSuffix using their integrated kustomization feature. We then test the new app to either approve or deny the PR.
The nameSuffix to the namespace ( in our case just a PR number and a few letters ) ensures that the no apps from any pull requests ever collide.
Now that namespaces aren't suffixed anymore makes all our apps collide, which naturally keeps us from updating.
The objects themselves don't really collide since their names differ due to the suffix, but the namespace ones do. 
We would really really like to separate by namespace, this makes secret and networking safety a lot easier.

How can I still apply a suffix to namespace objects?
I have tried using transformer configuration but that config is just ignored. I can't get the namespace to be suffixed.

```
❯ tree
.
├── configurations.yaml
├── kustomization.yaml
├── kustomizeconfig
│   └── namespace.yaml
└── ns.yaml

1 directory, 4 files
```

```
❯ cat kustomizeconfig/namespace.yaml
nameSuffix:
- path: metadata/name
namePrefix:
- path: metadata/name
```
```
❯ cat ns.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: argocd-pipeline
```
```
❯ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml

nameSuffix: -suffix
namePrefix: prefix-

configurations:
  - configurations.yaml
```
```
❯ cat configurations.yaml
nameSuffix:
- path: metadata/name
namePrefix:
- path: metadata/name
```
```
❯ kustomize build
apiVersion: v1
kind: Namespace
metadata:
  name: argocd-pipeline
```
```
❯ kustomize version
{Version:kustomize/v4.1.2 GitCommit:a5914abad89e0b18129eaf1acc784f9fe7d21439 BuildDate:2021-04-15T23:23:03+01:00 GoOs:darwin GoArch:amd64}
```
any help is greatly appreciated 🙏 

Only thing we figured is to not ship the namespace with manifest and implicitly create it using argocd. But that completely removes the ability to apply any annotations or labels to the namespace that gets created and thus removes a lot of abilities when it comes to monitoring or istio and such.

We could also do it the default way and just deploy everything into the unsuffixed namespace, but if possible I'd love to still have the ability to add a suffix to a namespace if I really wanted to. Not adding a suffix on default is understandable but prohibiting it by ignoring transformer options appears inconsistent to me

**Comment by natasha41575** [comment]
Is there a reason you prefer suffixing the namespaces over setting a new namespace via the `namespace` field?

**Comment by KarstenSiemer** [comment]
Yes, setting the namespace field inside kustomize would require me to alter the manifest itself requiring a new git commit.
ArgoCD application crd allows injecting additional kustomize fields to the manifest but `namespace` is not one of them.
The ArgoCDs application crd's destination namespace field only works for manifest objects which do not already have a namespace, so it cannot alter objects that already are assigned to a namespace. So none of these feature bring me closer to what I actually need

**Comment by natasha41575** [comment]
IIUC, your request is to revert https://github.com/kubernetes-sigs/kustomize/pull/2742 so that prefixes and suffixes are applied to namespace objects as well? I'm not sure we can do that, given the large number of requests (https://github.com/kubernetes-sigs/kustomize/issues/1899) for it to be done. 

Another way to suffix values will be the new replacements field (see the [tests here ](https://github.com/kubernetes-sigs/kustomize/blob/0f614e92f72f1b938a9171b964d90b197ca8fb68/api/filters/replacement/replacement_test.go#L910)). 

With this, you will be able to target any field e.g.

```
targets:
- select: 
     kind: Namespace
  fieldPaths: 
  - metadata.name
  options:
    delimiter: '-'
    index: 99 # any large number will cause the source value to be suffixed
```

This feature will be released shortly and documentation is coming soon. Does this sound like something that would work for your use case?

**Comment by KarstenSiemer** [comment]
Thanks @natasha41575! I do not request for #2742 to be reverted. It's fine for me that namespaces aren't suffixed on default. I am just looking for a way to still do it and would not mind some extra configuration. All I am looking for is a way to pass suffix information from the argocd application crd into the manifest, if that will work with the replacements field I am happy :-)

**Comment by natasha41575** [comment]
@KarstenSiemer I was assuming you would like to target all objects of kind `Namespace`, which you can do easily with 

```
targets:
- select:
     kind: Namespace
```

> A prefix would be easier in this case, because one would always know the index of it.

That's true; prefixes are easier so if that makes sense for your use case I would suggest doing that instead. The replacements transformer is available in the latest release, if you would like to try it out and provide further feedback.

**Comment by KarstenSiemer** [comment]
We've decided for a different solution using kustomize. Thanks for the help though 👍

**Comment by RappC** [comment]
@KarstenSiemer Would still be interesting to know what other solution you decided on.

**Comment by KarstenSiemer** [comment]
@RappC sure! 
We simply used a nameReference and applied to namespace.
e.g
kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
 kind: Kustomization

 configurations:
   - configuration.yaml
```
configuration.yaml:
```
nameReference:
   - version: v1
     kind: Service
     fieldSpecs:
       - version: v1
         kind: Namespace
         path: metadata/name
```

In this case you need to add the namespace object to your kustomize manifest and need a service with the exact same name as the namespace. Any pre/post-fix to the manifest will be applied to the service first and then passed to the namespace.
If you don't have a senseful service, you could use any other object like a empty configmap which is just there to rename the namespace. In our case, we only want to change the namespace name in development environments and only add such a modifier object in that case. In prod nothing of such is included

**Comment by abdennour** [comment]
from our side, we crafted a helm chart with a single template of kind Application.  The helm chart has a logic to assign namespace destination as per some Values. Whenever we want to create new ArgoCD App, we use that helm chart as wrapper.
