### ISSUE TITLE
Audit and delete site/ and docs/ directories

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#3915]
The content moved in Nov 2020 (#3182) which is long enough for crawlers to adjust.
Besides, the redirect links often 404, and when they land on real content, the content is not as intended

Close issue when there are no dead links from this repo regarding docs, and both site/ and docs/ are gone

**Comment by KnVerey** [comment]
Note that this is still being published via Github Pages at https://kubernetes-sigs.github.io/kustomize/ (largely redirects), and kustomize.io is still pointing to that site with its "core docs" link. So steps here:
1) Repoint kustomize.io to the current docs
1) Audit content and make a removal PR
2) Deactivate Github Pages
3) Merge removal PR

**Comment by KnVerey** [comment]
/reopen

This still needs to be done.
