### ISSUE TITLE
Kustomize for multiple services

### ISSUE THREAD

**Issue by jayanvg** [kubernetes-sigs/kustomize#3918]
We have the below folder structure for our kustomize setup. 

base-manifest:
     kustomization.yaml
     deployment.yaml
     services.yaml
     ingress.yaml
base-services:
     kustomization.yaml
     service-a:
         kustomization.yaml
     service-b:
         kustomization.yaml
overlay:
     dev:
            kustomization.yaml
     qa:
           kustomization.yaml

The command: kubectl kustomize overlay/dev

What are the possible options if we don't want to create ingress for service-b?

**Comment by monopole** [comment]
Kustomize is (intentionally) bad at deleting things (see eschewed features).

It's best to add the ingress in the overlay where you want to use it, and omit it from the base.
