### ISSUE TITLE
CommandResultsChecker should allow for formatting the result before checking for equality

### ISSUE THREAD

**Issue by aw185176** [kubernetes-sigs/kustomize#3919]
**Is your feature request related to a problem? Please describe.**

When I use https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml@v0.10.19/fn/framework/frameworktestutil#CommandResultsChecker I have to ensure that my function catalog outputs normalized results (because out-of-order arrays will fail the test).  We have a decent catalog of functions internally and use our normalizer function as part of pipeline to format/normalize all output, so we do not want to additionally do this in the internal logic of functions.

**Describe the solution you'd like**

It would be nice if the checker didn't fail for array order, or if it was possible to provide a post-command-execution hook that could be used to normalize results before they are checked against the expected results

**Comment by KnVerey** [comment]
After playing with some options, I have a proposal in https://github.com/kubernetes-sigs/kustomize/pull/3939. That PR gives both ProcessorResultsChecker and CommandResultsChecker two new fields:


```go
        type AssertionFunc func(t *testing.T, expected string, actual string)

	// OutputAssertionFunc allows you to swap out the logic used to compare the expected output
	// from the fixture file to the actual output.
	// By default, it performs a string comparison after normalizing whitespace.
	OutputAssertionFunc AssertionFunc

	// ErrorAssertionFunc allows you to swap out the logic used to compare the expected error
	// message from the fixture file to the actual error message.
	// By default, it interprets each line of the fixture as a regex that the actual error must match.
	ErrorAssertionFunc AssertionFunc
```

This should let you do either of the things you proposed (post-process the output or change what you assert about it). What do you think?

**Comment by aw185176** [comment]
I think I could make either of those work, thank you for the prompt return. 

In this setup, would it be possible to call the built-in assertion func from, eg, an `OutputAssertionFunc` so that its basically a thin wrapper that lets me normalize the manifests?

**Comment by KnVerey** [comment]
Yes, the PR currently exposes the default assertion funcs, so you could call e.g. `frameworktestutil.RequireStrippedStringsEqual(t, expected, actual)` from your custom assertion. Wrapping `testify` assertions should also work nicely.

**Comment by aw185176** [comment]
Awesome, thanks for confirming.  This would work swimmingly

**Comment by KnVerey** [comment]
Closed by https://github.com/kubernetes-sigs/kustomize/pull/3939

/close
