### ISSUE TITLE
Field "patches:" doesn't like multiple patches in one patch file.

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#3929]
This works as expected:

```
resources:
- ../base
patchesStrategicMerge:
- patch1.yaml
- patch2.yaml
```

So does this:
```
resources:
- ../base
patches:
- path: patch1.yaml
- path: patch2.yaml
```

so does this, where `twoPatchesInOneFile.yaml` contains `patch1.yaml` and `patch2.yaml` separated by `---`:

```
resources:
- ../base
patchesStrategicMerge:
- twoPatchesInOneFile.yaml
```

This, however, fails:
```
resources:
- ../base
patches:
- path: twoPatchesInOneFile.yaml
```

**Comment by monopole** [comment]
Actually, I think this is WAI.

The semantics of the `patches:` field call for _one_ patch, applied to _N_ targets .

**Comment by natasha41575** [comment]
@monopole just FYI I looked at patches and applied the same logic when writing the `replacements` field; it can only have one replacement in a path

**Comment by monopole** [comment]
right, makes sense.

**Comment by james-callahan** [comment]
I'm hoping this can be reopened: having multiple patches in a file was quite useful for grouping related functionality together.

**Comment by iamnoah** [comment]
Agree with @james-callahan, a `patches` that doesn't accept multiple patches per file isn't a suitable replacement for `patchesStrategicMerge`. Grouping GVKN patches in a single file is incredibly useful. Removing `patchesStrategicMerge`  without a suitable replacement breaks tons of applications.
