### ISSUE TITLE
Reduce public surface of sigs.k8s.io/kustomize/api module

### ISSUE THREAD

**Issue by KnVerey** [kubernetes-sigs/kustomize#3942]
In preparation for releasing v1 of this module, we need to reduce its public surface.

Preliminary guidance on what to do with the current packages:
- [ ] builtins (generated code from legacy plugins): Internal (https://github.com/kubernetes-sigs/kustomize/pull/4300 does this and leaves aliases)
- [ ] hasher (for secret and configmap generation): Internal, or maybe kyaml
- [ ] ifc (single file with interfaces): Internal except maybe KustHasher and Validator
- [ ] Image (utils for parsing image field): Move to image transformer
- [ ] konfig: internal
- [ ] krusty: keep external but rename it to e.g. “build” or “runner”
- [ ] kv: internal
- [ ] loader: internal
- [ ] provenance: probably needs to stay external for the linker, but confirm
- [ ] provider: internal
- [ ] resmap: needs to stay external as long as the go plugins exist
- [ ] testutils: try to make internal, but not a big deal
- [ ] filesys: move to kyaml (https://github.com/kubernetes-sigs/kustomize/pull/3997 does this but leaves aliases)

/project Release kustomize api 1.0.0

**Comment by KnVerey** [comment]
Once this is done, it could be interesting to add a https://github.com/joelanford/go-apidiff check like the KubeBuilder repo uses

**Comment by KnVerey** [comment]
@campoy had an interesting approach to this in https://github.com/kubernetes-sigs/kustomize/pull/3997: leave behind a type alias to give people more time to cut over. For packages we suspect others may be using, we could do something similar, and have v1 remove all the type aliases at once.

**Comment by natasha41575** [comment]
> builtins (generated code from legacy plugins): Internal (Move api/builtin to internal #4300 does this and leaves aliases)

Something we discovered in doing this task was that StringPrefixer and DatePrefixer (two plugins in `plugins/someteam.example.com/v1`) depend on the public function `NewPrefixSuffixTransformerPlugin`. I think we have three options here:

1. Copy some of the code from the PrefixSuffixTransformer plugin out to the `someteam.example.com` folder for StringPrefixer and DatePrefixer to use. I would suggest not doing this option; I think these example plugins have been around for a long time and we should make a firm decision about what we want their future to be.
2. Promote StringPrefixer and DatePrefixer to `builtins`.
3. Deprecate StringPrefixer and DatePrefixer, and remove them when we remove the type aliases in `api/builtins`. 

I am somewhat leaning toward option 3, but I don't know how many users are using these plugins. If we think they are useful, we should promote them to `builtins`; otherwise, we should remove them.

**Comment by KnVerey** [comment]
Option 3 makes sense to me. Unless I'm missing something StringPrefixer seems completely redundant with PrefixSuffixTransformer / the upcoming separate PrefixTransformer. DatePrefixer generates unstable output, which is not something we want to encourage, so I definitely don't want to promote it. 

If we change our minds about deprecating Go plugins, we should invent replacement examples that use kyaml for their implementation. Otherwise, I think it will be fine to remove them.

**Comment by yuwenma** [comment]
> Something we discovered in doing this task was that StringPrefixer and DatePrefixer (two plugins in plugins/someteam.example.com/v1) depend on the public function NewPrefixSuffixTransformerPlugin. I think we have three options here:

yeah, I also asked the usage of these two transformers `StringPrefixer` and `DatePrefixer ` in kustomize slack channel. No ones acknowledge the usages.  +1 to #3

**Comment by varshaprasad96** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/5193 intends to internalize loader APIs by keeping only the necessary methods external.

**Comment by varshaprasad96** [comment]
A few updates/questions while looking into the codebase:

1. Hasher: Hasher has one exported method named: [SortArrayAndComputeHash](https://github.com/kubernetes-sigs/kustomize/blob/api/v0.14.0/api/hasher/hasher.go#L17) which is not used anywhere else in the repository. Is this a supported public facing API that is commonly used? I would not like to make it internal, and break the users.

2. ifc: Apart from Validator and KustHasher, the KvLoader interface is being implemented at other places (in kustomize commands) - [ref](https://github.com/search?q=repo%3Akubernetes-sigs%2Fkustomize%20KvLoader&type=code), hence leaving it as is.

3. Image: https://github.com/kubernetes-sigs/kustomize/pull/5261

4. konfig: konfig has 2 important helpers - DefaultKustomizationFileName and RecognizedKustomizationFileNames which are being used in kustomize/commands  (eg). However, the builtinconstants have been moved to internal. https://github.com/kubernetes-sigs/kustomize/pull/5262

5. krusty: This needs to be external

6.  kv: kv.NewLoader is being used at multiple places in kustomize edit command (ref) and most importantly here. Though it wraps the loader, which in tern runs their own validation and Load, leaving this as is as it seems an useful API to export (pl correct me if I'm wrong).

7. loader: https://github.com/kubernetes-sigs/kustomize/pull/5193

8. provenance: Needs to be external for pluginator (ref), kustomize build command tests and most importantly while printing the kustomize version.

9. provider: https://github.com/kubernetes-sigs/kustomize/pull/5206

10. resmap: Needs to stay external for plugins

11. testutils: needs to stay external as they are being used as helpers in builtin cmd tests

**Comment by natasha41575** [comment]
Thank you @varshaprasad96! We will get your open PRs merged and then we can consider this issue closed once those are in.

**Comment by natasha41575** [comment]
I think we can consider this issue completed for now, thanks @varshaprasad96!
