### ISSUE TITLE
Remove starlark dependencies from api module

### ISSUE THREAD

**Issue by KnVerey** [kubernetes-sigs/kustomize#3943]
As requested in https://github.com/kubernetes/kubernetes/pull/98946, we need to make it possible to use Kustomize as a library without pulling in a starlark dependency. Starlark functionality should remain available in the standalone kustomize binary, but this should be done via injection so that it does not affect kubectl. We can revisit this decision if starlark functions graduate out of alpha, but for now, we don't expose them in kubectl at all.

**Comment by mikebz** [comment]
I think this is a great idea.  In general I would probably look for limiting the number of "extension points" in kustomize because it can lead to security issues.

**Comment by KnVerey** [comment]
We are instead going to remove Starlark support entirely: https://github.com/kubernetes-sigs/kustomize/issues/4349
