### ISSUE TITLE
Breaking whitespace changes in go-yaml upgrade

### ISSUE THREAD

**Issue by KnVerey** [kubernetes-sigs/kustomize#3946]
As discovered in https://github.com/kubernetes-sigs/kustomize/pull/3789, upgrading go-yaml causes whitespace changes in the output. This may be seriously disruptive to some users, as committing build results is a common practice for both testing and GitOps workflows.

We need to either:
A) Prevent the whitespace changes. Presumably this involves kyaml interfering with the marshalling process. Related to https://github.com/kubernetes-sigs/kustomize/issues/3559
B) Release the go-yaml bump in a major version bump (i.e. kustomize 5.0).

This issue is urgent because although we can pin the version used by the standalone kustomize binary, kubernetes/kubernetes has already upgraded to a more recent version. This presumably means the next kubectl release will include the breaking changes as of right now (TBC).

**Comment by monopole** [comment]
[commit]: https://github.com/go-yaml/yaml/commit/ae27a744346343ea814bd6f3bdd41d8669b172d0
[gopkg.in/yaml.v3]:  https://github.com/go-yaml/yaml
[kyaml]: https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/go.mod#L35
[api]: https://github.com/kubernetes-sigs/kustomize/blob/master/api/go.mod#L18
[just before]: https://github.com/go-yaml/yaml/commit/9f266ea9e77c4c7aab4cf02650570e7c7b3031a5

This issue will probably get some interest/questions down the road, so adding some history.

In a [commit] on 2020-May-04, marshaling code in [gopkg.in/yaml.v3] changed indenting from

```
favorites:
  fruit: apple
  car: ford
fruits
- apple
- orange
```

to

```
favorites:
  fruit: apple
  car: ford
fruits
  - apple
  - orange
```

Kustomize and all its tests assume the older more compact behavior, where the hyphens don't 'consume' an indent.


The modules in this repo ([kyaml] and [api]) use `replace` directives to pin to the commit [just before] this indentation change (back to 2020-Mar-13).  


[commits]: https://github.com/go-yaml/yaml/commits/v3
[its go-yaml dependence]: https://github.com/kubernetes/kubernetes/blob/master/go.mod#L476

Meanwhile, 

- kubectl has pinned [its go-yaml dependence] past this commit moving up to 2020-Jun-15
- in general there have been [commits] to go-yaml fixing various bugs and improving YAML comment retention
- kyaml clients (including kustomize) need those fixes
- maintaining a fork of go-yaml for kustomize while also seamlessly integrating into kubectl isn't a headache anyone wants
- although we could send a PR into go-yaml exposing a means to pick an indentation style, that's exactly the kind of knob that the Go community would never add to the `go fmt` tool.

Suggest we do this:

 1.  In a standalone kubectl PR, figure out how far we can upgrade kubectl w/r to [gopkg.in/yaml.v3] without breaking k8s tests. Let's try for the current latest, which is 2021-Jan-07.
 
 1. Dust off https://github.com/kubernetes-sigs/kustomize/pull/3789, and adjust its pinning as needed (it currently stands at 2021-Jan-07).

1. Release kustomize v5 with the indentation change and make a bunch of noise about it for folks that have downstream tests to adjust.

**Comment by monopole** [comment]
The upgrade of k8s to yaml.v3 circa 2020-Jun-15 happened in kubernetes/kubernetes#100490 on 2021 Apr 20 - just a few weeks ago.

Were the dozen or so later commits to yaml.v3 that this PR could have grabbed intentionally kept out?  Meaning step 1 above wouldn't make it past code rev?

@howardjohn
@gautierdelorme

**Comment by monopole** [comment]
Some of the issues in various repos related to this:

- Let kyaml keep white space formatting https://github.com/kubernetes-sigs/kustomize/issues/3559
- Add Config for Array Indentation Spacing https://github.com/redhat-developer/vscode-yaml/issues/172
- Breaking whitespace changes in go-yaml upgrade https://github.com/kubernetes-sigs/kustomize/issues/3946
- Support configurable indent https://github.com/go-yaml/yaml/issues/202
- v3 - Configurable or autodetected list indentation https://github.com/go-yaml/yaml/issues/720
- v3: (Encoder) setting indentation for sequences https://github.com/go-yaml/yaml/issues/661
- Indentation with --indent/-I does not work as expected https://github.com/mikefarah/yq/issues/825

**Comment by stefanprodan** [comment]
@monopole for Flux users, I think it's best to autodetected and keep the original indentation, unlike go fmt, Kubernetes users are not accustom to strict formatting since kubectl does no such enforcement.

**Comment by KnVerey** [comment]
After further thought, we're exploring both options 2 and 3 @monopole mentioned above. Option 1 is likely a no-go even if we were to cut a new major version of Kustomize, because of the issue of inconsistency with kubectl, which is definitely not able to change.

**Comment by monopole** [comment]
The PR for option 3 is https://github.com/go-yaml/yaml/pull/746

**Comment by mikebz** [comment]
https://github.com/go-yaml/yaml/pull/750

**Comment by natasha41575** [comment]
https://github.com/go-yaml/yaml/pull/753

**Comment by natasha41575** [comment]
Closing this in favor of #4033, which includes a summary of the decision made and what we need to do moving forward.
