### ISSUE TITLE
Automically create patch yaml based on two overlays?

### ISSUE THREAD

**Issue by harryge00** [kubernetes-sigs/kustomize#3957]
Currently, different clusters have their own deployment yamls in our team. And we want to migrate to kustomize. However,  I didn't find a tool to create patch yaml based on two different deployment yamls. 

For example, the current layout:
```
   ├── dev
    │   ├── dep.yaml
    │   
    ├── prod
    │   └── dep.yaml
    └── staging
        └── dep.yaml
```
We want to change to 
```
├── base
│   ├── dep.yaml
│   └── kustomization.yaml
└── overlays
    ├── dev
    │   ├── kustomization.yaml
    │   └── patch.yaml
    ├── prod
    │   ├── kustomization.yaml
    │   └── patch.yaml
    └── staging
        ├── kustomization.yaml
        └── patch.yaml
```
So we have to create patch yaml. Now we make `dev/dep.yaml` the base file and create patch manually. This can take a long time since our file is very long and may raise error.

I was wondering if there is a command or other tool to create such patch? If the answer is no, I am happy to contribute

**Comment by natasha41575** [comment]
There is a library used heavily by the kubernetes community to create patches: https://github.com/evanphx/json-patch. Would this help your use case?
