### ISSUE TITLE
kustomize fn run should support running containerized fns on K8s without docker

### ISSUE THREAD

**Issue by jlewi** [kubernetes-sigs/kustomize#3958]
**Is your feature request related to a problem? Please describe.**

I would like to use `kpt fn run` inside CI/CD pipelines that run in a cluster. [kpt fn run](https://github.com/kubernetes-sigs/kustomize/blob/f61b075d3bd670b7bcd5d58ce13e88a6f25977f2/kyaml/fn/runtime/container/container.go) currently relies on shelling out to docker.  As a result, when running in cluster one needs to run docker in docker as illustrated by the [tekton example](https://googlecontainertools.github.io/kpt/guides/consumer/function/export/tekton/).

My understanding is that mounting the docker socket into a container creates security concerns and is generally not best practice.

**Describe the solution you'd like**

I'd like `kpt fn run` to support launching containerized fns on a cluster (e.g. by creating a Pod) without requiring docker. Ideally the experience would be similar to skaffold build in that kpt would start the pod, upload the YAMLs to be processed (e.g. output of kpt fn source) and then download the resulting output.

**Describe alternatives you've considered**

Running docker in docker as described in the kpt docs
https://googlecontainertools.github.io/kpt/guides/consumer/function/export/tekton/

**Comment by Shell32-Natsu** [comment]
You should probably create issue in [kpt repo](https://github.com/GoogleContainerTools/kpt).

**Comment by jlewi** [comment]
@Shell32-Natsu this belongs in kpt even though the code in question lives inside kustomize? 
https://github.com/kubernetes-sigs/kustomize/blob/f61b075d3bd670b7bcd5d58ce13e88a6f25977f2/kyaml/fn/runtime/container/container.go

I'd actually like the function to be supported by `kustomize fn run` ; I realize now I wrote `kpt fn run` by accident.

**Comment by Shell32-Natsu** [comment]
> @Shell32-Natsu this belongs in kpt even though the code in question lives inside kustomize?
> https://github.com/kubernetes-sigs/kustomize/blob/f61b075d3bd670b7bcd5d58ce13e88a6f25977f2/kyaml/fn/runtime/container/container.go
> 
> I'd actually like the function to be supported by `kustomize fn run` ; I realize now I wrote `kpt fn run` by accident.

Technically yes, kpt feature request should go to kpt repo even the actual code is in kyaml.

**Comment by jlewi** [comment]
Done;

Duplicate of GoogleContainerTools/kpt#2158
