### ISSUE TITLE
Replace Resource.refBy with annotations

### ISSUE THREAD

**Issue by KnVerey** [kubernetes-sigs/kustomize#3976]
The field `Resource.refBy` is used to track the IDs of resources that refer to the current resource as it propagates up the Kustomization stack. 

This information isn't available to an out-of-process transformer, but like all other RNode metadata (e.g. the history of previous resource names in the transformation pipeline) it should be. This can be accomplished by moving the field's data to an annotation. https://github.com/kubernetes-sigs/kustomize/blob/master/api/resource/resource.go#L26

The fix should include tests that name references are correctly applied in the presence of KRM functions.

Similar to #3975.

**Comment by natasha41575** [comment]
> The fix should include tests that name references are correctly applied in the presence of KRM functions.

Could you clarify this requirement with an example? I'm not sure I understand the relationship between `Resource.refBy` and KRM functions
