### ISSUE TITLE
Restore kustomize windows build disabled for v4.2.0

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#4028]
[kustomize/v4.2.0]: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.2.0

[disabled]: https://github.com/kubernetes-sigs/kustomize/pull/4027

The windows build was failing in goreleaser for unknown reasons during the attempt to release [kustomize/v4.2.0].

In the interests of making the kubectl integration deadline with a new release, the windows build was [disabled] and a canned version for windows isn't offered for v4.2.0.  It can appear in a patch release.

Possibly related to #4001

**Comment by KnVerey** [comment]
We should consider doing a `goreleaser build` (https://goreleaser.com/quick-start/#dry-run) in CI to help discover problems like this ahead of release time in the future.

**Comment by juergenzimmermann** [comment]
Unfortunately, the latest Windows release is `4.1.3` while the latest linux release is `4.3`.

**Comment by juergenzimmermann** [comment]
@monopole @KnVerey @natasha41575 Is there any chance to get 4.4 for Windows, too? The latest Windows release is still 4.1.3.

**Comment by natasha41575** [comment]
It might take some time because none of us have windows machines, but we are working on a fix.

**Comment by olljanat** [comment]
It should enough if you can make cross build working with command like:
`GOOS=windows GOARCH=amd64 go build`

Some of us Windows users can help with testing after that.

**Comment by natasha41575** [comment]
/unassign

If there is anyone with a windows machine that would like to dig deeper into why the windows build fails, we would greatly appreciate that.

**Comment by natasha41575** [comment]
Agh sorry 've been meaning to add a `make build`, but here is how you build it:

From inside the [kustomize/kustomize](https://github.com/kubernetes-sigs/kustomize/tree/master/kustomize) directory, run `go install .`

**Comment by natasha41575** [comment]
Windows build is reenabled in 4.4.1.

**Comment by juergenzimmermann** [comment]
@natasha41575 Thank you! It works fine.
