### ISSUE TITLE
yaml.v3 fork maintenance story

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#4033]
### Background

Upgrading go-yaml causes a breaking indentation change for kustomize. The details are described in [this comment](https://github.com/kubernetes-sigs/kustomize/issues/3946#issuecomment-855172892). To remedy this issue, we added a [PR to go-yaml](https://github.com/go-yaml/yaml/pull/753) in the hopes that it would be accepted in time for the k/k code freeze (July 8, 2021). There was no response for the go-yaml maintainer, so we forked the go-yaml library under kyaml/internal to use the old indentation: [link to forking PR](https://github.com/kubernetes-sigs/kustomize/pull/4013). This fork will also integrated into [kubernetes via kustomize-in-kubectl](https://github.com/kubernetes/kubernetes/pull/103419). 

### Maintenance

[There is a script](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/internal/forked/update-go-yaml.sh) that will allow us to pull in new commits from yaml.v3 when needed. If there are urgent security fixes in yaml.v3 upstream, we will need to prioritize pulling those commits in and back-porting them into kustomize release branches. We will need to ensure that the security fixes are pulled into the fork integrated in k/k.

### Future

Whenever the sequence indentation style is made configurable in yaml.v3 upstream, we need to upgrade to the newest version of yaml.v3 and remove the internal fork. 

See instructions at https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/internal/forked/update-go-yaml.sh

The following issues need to be resolved upstream:
https://github.com/go-yaml/yaml/issues/755
https://github.com/go-yaml/yaml/issues/720

**Comment by KnVerey** [comment]
We've sent a reminder ping on our PR today. If we end up carrying the internal fork past the current k/k release, we should reconsider our options, such as approaching API Machinery about a permanent fork, or maybe supporting/leveraging the effort to have kubernetes-sigs/yaml use v3 (https://github.com/kubernetes-sigs/yaml/pull/61 mentions a KEP for v2 of that lib).

**Comment by natasha41575** [comment]
https://github.com/kubernetes-sigs/yaml/pull/76 is a PR that started the work of creating the official go-yaml fork. Remaining work here would be:

- Address the comments on that PR. There is a comment here https://github.com/kubernetes-sigs/yaml/pull/76#issuecomment-1528020524 that has a link to suggested changes, you can pull in Jordan's changes into your fork and create a PR based off of that. 
- Once the fork is merged, remove the internal fork in kustomize and change our dependency to point to the new fork.

**Comment by natasha41575** [comment]
Jordan has pinged me on the go-yaml fork PR, so I'm going to try to wrap it up soon.

**Comment by natasha41575** [comment]
go-yaml fork is created and we have removed our internal fork!
