### ISSUE TITLE
No Windows asset for Kustomize 4.2.0

### ISSUE THREAD

**Issue by juergenzimmermann** [kubernetes-sigs/kustomize#4041]
**Describe the bug**

There is no Windows asset for Kustomize 4.2.0 at https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.2.0 as it is for 4.1.3 at https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.1.3

**Expected output**

.tar.gz file for Windows at https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.2.0

**Actual output**

No .tar.gz file for Windows at https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.2.0

**Platform**

Windows

**Comment by natasha41575** [comment]
Thanks for filing the issue, I am closing this as a duplicate of https://github.com/kubernetes-sigs/kustomize/issues/4028.

We are aware of the problem and will look into it when we can!
