### ISSUE TITLE
[Question] "CreateOnly" for Secrets / Configmaps

### ISSUE THREAD

**Issue by gprossliner** [kubernetes-sigs/kustomize#4101]
Hi Folks!

For a small tool, I use kustomize for the deployment.
One object that is deployed is a Secret, containing Application Configuration.

This Secret should only be created, but left untouched when I redeploy, because it contains only the initial default Configuration, including the name of the values. The User has to manually fill alter those values, because they contain data that is not automated (like URL and API Key for external server).
Obliviously it's very annoying to reconfigure on every upgrade.

* Is there a way to mark a Secret (or ConfigMap) as "CreateOnly" or "NoOveride" in kustomize?
* If not can you suggest a solution or workaround?

Thanks

**Comment by natasha41575** [comment]
> This Secret should only be created, but left untouched when I redeploy, because it contains only the initial default Configuration, including the name of the values.

Could you explain a bit more what you mean? Do you mean that the Secret should be created, but that kustomize shouldn't apply any transformations to it? It might help if you provide an example of a kustomization for what you are looking for.

**Comment by gprossliner** [comment]
> Could you explain a bit more what you mean? Do you mean that the Secret should be created, 
> but that kustomize shouldn't apply any transformations to it? It might help if you provide an example of a kustomization for what you are looking for.

Not really. I'll try again:

1. In my kustomize I define a Secret object named "app-config", which contains default settings
2. (first install) The user creates all objects with `kubeclt apply -k ..`
3. The user manually updates the Secret "app-config" to set an URL and API Key for an external service
4. If configured correctly, after restarting the pods, all should be good
5. After some time the tool should be upgraded to a new version
6. (upgrade) The user performs the upgrade by running `kubeclt apply -k  ..` again
7. kustomize resets the "app-config" Secret with the initial default settings, the manual changes have been overwritten

This is a problem, because I don't want the user to reconfigure (step 3) after every upgrade

What I want:
I need to find a way that kustomize doesn't overwrite the Secret if it is already created, and may contain manual changes.

**Comment by natasha41575** [comment]
IIUC, you want kustomize to check if the cluster has the Secret, and not edit it if it is there?

That is well beyond the scope kustomize as it does not communicate with the cluster. All kustomize does is take your local files as input, and produce some output. Kubectl then takes the output of kustomize and applies it to the cluster.

 If you don't want the secret to be included in the output of kustomize, you have to remove it from the input.

**Comment by gprossliner** [comment]
Thanks. I was kinda expecting that.
