### ISSUE TITLE
Problem with kustomize build: may not add resource with an already registered id

### ISSUE THREAD

**Issue by leon-marcel** [kubernetes-sigs/kustomize#4104]
Hi guys i hope you are able to help me. 
We have multiple projects and we want to deploy them with one _kustomization.yaml_. When i try to use kustomize build to build the files the error `may not add resource with an already registered id: rbac.authorization.k8s.io_v1_ClusterRoleBinding|~X|nv-icinga-monitoring:cluster-monitoring-view` occurs.

I built a sample project which reproduced this error. ( Idk if its a bug or if im just missing something)

Directory Tree:
```
.
├── default
│   ├── kustomization.yaml
│   ├── namespace.yaml
│   └── rolebindings.yaml
└── stage
    ├── icinga_monitoring
    │   ├── cluster_roles.yaml
    │   ├── kustomization.yaml
    │   ├── namespace.yaml
    │   └── service_accounts.yaml
    ├── kustomization.yaml
    └── project
        ├── kustomization.yaml
        ├── namespace.yaml
        └── rolebindings.yaml
```
The two projects are **icinga_monitoring** and **project**.
The kustomization.yaml within the folder stage looks like this:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./icinga_monitoring/
  - ./project/
```

The cluster role binding  *nv-icinga-monitoring:cluster-monitoring-view* mentioned in the error message comes from the **default/rolebinding.yaml** file and looks like this:
```
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nv-icinga-monitoring:cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: icinga-monitor
  namespace: icinga-monitor
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io

```

The Service Account *icinga_monitor* is defined within the *stage/icinga_monitoring/service_accounts.yaml* file.
The ClusgterRole *cluster-monitoring-view* is defined within the *stage/icinga_monitoring/cluster_roles.yaml* file.

The default (base) is referred in the two files *stage/icinga_monitoring/kustomization.yaml* and *stage/project/kustomization.yaml*.

icinga_monitoring kustomization:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../default/

namespace: icinga-monitoring

patchesStrategicMerge:
  - namespace.yaml

resources:
  - cluster_roles.yaml
  - service_accounts.yaml
```
project kustomization:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../default/

namespace: project

patchesStrategicMerge:
  - namespace.yaml

resources:
  - rolebindings.yaml
```

**What i've tried:**

- It seems that the error only occurs as soon as more than one project as resource within the kustomization.yaml file is present. If i remove either the line ./project/ or ./icinga_monitoring/ from the kustomization.yaml (within the stage folder) no error occurs.
- I've tried to move the ClusterRoleBinding definition from the default (base) to each project. I created a new **cluster_rolebindings.yaml** for each project and added the definition to them. Then i added the explicit namespace definition to each of them. Tried to `kustomize build` it. Nearly the same error occurs: `may not add resource with an already registered id: rbac.authorization.k8s.io_v1_ClusterRoleBinding|projects|nv-icinga-monitoring:cluster-monitoring-view`

Output of `kustomize version`:
`{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-07-01T00:44:28+01:00 GoOs:darwin GoArch:amd64}`

I don't know if i am missing something or its a bug. I hope somebody can help me.

I've created a repo which contains the example project : https://github.com/leon-marcel/kustomize-error-sample

Best Regards,

Leon

**Comment by natasha41575** [comment]
The problem is that you are using the same base in two different overlays without changing its ID, resulting in two resources with the same ID. You can fix this by adding name prefixes, e.g. 

icinga_monitoring kustomization:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: monitoring-

bases:
  - ../../default/

namespace: icinga-monitoring

patchesStrategicMerge:
  - namespace.yaml

resources:
  - cluster_roles.yaml
  - service_accounts.yaml
```

project kustomization:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: project-

bases:
  - ../../default/

namespace: project

patchesStrategicMerge:
  - namespace.yaml

resources:
  - rolebindings.yaml
```

**Comment by leon-marcel** [comment]
Sry for my late reply.
So i changed both kustomization's according to your reply but still get the same error message.

**Comment by leon-marcel** [comment]
sorry for my late reply. It worked! Thanks a lot!
