### ISSUE TITLE
[Question] how to debug outpu of kustomise from kubectl

### ISSUE THREAD

**Issue by Krzysztof-Lempicki** [kubernetes-sigs/kustomize#4105]
Hi, 

I am using `kustomise` with `kubectl` like this:

```
kubectl --kubeconfig $LOCATION apply -k .
```

I want to know how I can debug kustomise result of this command?
Is any flag to print kustomise result into console?

**Comment by natasha41575** [comment]
You can run the command `kubectl kustomize` to see the output of kustomize.
