### ISSUE TITLE
v4.2.0 missing in k8s.gcr.io 

### ISSUE THREAD

**Issue by maxres-fr** [kubernetes-sigs/kustomize#4106]
**Describe the bug**
 v4.2.0 is missing in k8s.gcr.io, see https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/kustomize/kustomize?gcrImageListsize=30.

 **Expected output**

 Able to pull the image
 
 **Actual output** 
 ```
 ❯ docker pull k8s.gcr.io/kustomize/kustomize:v4.2.0
Error response from daemon: manifest for k8s.gcr.io/kustomize/kustomize:v4.2.0 not found: manifest unknown: Failed to fetch "v4.2.0" from request "/v2/kustomize/kustomize/manifests/v4.2.0".

 ```
 
 similar to: #2165 and kubernetes/k8s.io#2165
 
 I'd open a PR but I don't think I can get the hash.

**Comment by natasha41575** [comment]
PR is here https://github.com/kubernetes/k8s.io/pull/2540
