### ISSUE TITLE
kustomize globbing incorrectly includes dot files

### ISSUE THREAD

**Issue by telmich** [kubernetes-sigs/kustomize#4108]
**Describe the bug**

Using

```
kustomize edit add configmap dns-test4 --from-file='./zones/*'
```

with a directory that contains dotfiles like .dynamicweb, .empty, .staticweb, etc., the generated configmap contains:

```
  - zones/.dynamicweb
  - zones/.empty
  - zones/.staticweb
  - zones/0.1.0.0.0.c.5.e.a.0.a.2.ip6.arpa

...
```

This is obviously not how shell globbing would work and is suprising to have these files included.

**Files that can reproduce the issue**

```
mkdir zones
touch zones/a
touch zones/.a-hidden
```

```
kustomize edit add configmap dns-test4 --from-file='./zones/*'
```

**Expected output**

No dot files included in the configmap.

**Actual output**

dot files are included in the configmap.

**Kustomize version**

```
{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-06-30T22:49:26Z GoOs:linux GoArch:amd64}
```

**Platform**

Linux

**Additional context**

While this bug report is about the dot file issue, related note:

I have read #217, #189, #218, #207 and I believe the exclusion of globbing inside the configmapgenerator is a mistake, because it **adds redundant information** and leads to **inconsistent** configurations.

An easy example: We have a lot of different applications that write to a single git repository containing DNS zones files in the directory `zones/`.  None of the applications is k8s aware and none of it has to be. A static kustomization.yaml in the top of the repository with the configmapgenerator **could** just include zones/*.

Now, because of the omission of that feature, an extra k8s aware step

```
./kustomize edit add configmap dns-test4 --from-file='./zones/*'
```
(which does not correctly work with dotfiles, thus this bug report as well)

needs to be introduced in the pipeline. However various flows will not run this step. Such as:

- using a `GitRepository` with a `Kustomization` like in flux v2, will *skip* the edit step, a potentially outdated kustomization.yaml is applied
- using `kubectl apply -k` from a pipeline/CI - requiring an extra round of (git clone, kustomize edit, git push) and adds extra complexity to store the generated kustomization.yaml inside a git repo, but not to retrigger the rebuild

While I see some "fundamental world views" in the other tickets, I believe the kustomize workflows would be simpler, easier to understand and better to maintain with globbing support and I kind ask to review the globbing support. Especially if kubectl had support for it, users can still decide to use `kustomize edit` if they want to.

**Comment by KnVerey** [comment]
I agree with you that the dotfiles being included feels unexpected. I'd suggest filtering them out after the results are returned here: 

https://github.com/kubernetes-sigs/kustomize/blob/7fae7d1bd63ef5f9ea0c2e11593581ed5974fbe9/kustomize/commands/edit/add/flagsandargs.go#L88

/triage accepted
/help
