### ISSUE TITLE
edit set with more than 125 characters renders invalid yaml

### ISSUE THREAD

**Issue by adberger** [kubernetes-sigs/kustomize#4119]
**Describe the bug**

When the key of `edit set value` or `edit set annotation` has more than 124 characters, the rendered output seems invalid.

**Command that can reproduce the issue**

```
kustomize edit set annotation abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkl/abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk:value
```

**Expected output**

```
commonAnnotations:
  abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghij/abc: value
```

**Actual output**

```
commonAnnotations:
  ? abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghij/abc
  : value
```

**Kustomize version**

v4.2.0

**Additional context**

Related PR where the bug was discovered: https://github.com/kubernetes-sigs/kustomize/pull/4073

I tracked the issue down to the `JSONToYAML` function from the go yaml package (v1.2.0).

kf.Write(m)
-> data, err := mf.marshal(kustomization)
---> content, err := marshalField(field, kustomization)
-----> return yaml.Marshal(k)
-------->y, err := JSONToYAML(j)

https://imgur.com/a/4LiqB1v

`Println(t)` the output seems still correct
`Println(s)` the output is wrong

The problematic part seems to be somewhere in the `Marshal` function of the yaml.v2 package (v2.4.0):

```
func Marshal(in interface{}) (out []byte, err error) {
	defer handleErr(&err)
	e := newEncoder()
	defer e.destroy()
	e.marshalDoc("", reflect.ValueOf(in))
	e.finish()
	out = e.out
	return
}
```

My go knowledge isn't enough to really understand where the problem is, maybe someone can help me on this one.

**Comment by natasha41575** [comment]
If the problem is in yaml.v2 package (v2.4.0) we may need to submit a PR or issue to https://github.com/go-yaml/yaml/. In our experience we haven't received much of a response there (the maintainer is very busy).
