### ISSUE TITLE
Caching option for remote resources

### ISSUE THREAD

**Issue by twz123** [kubernetes-sigs/kustomize#414]
When using kustomize with remote locations, it can get tedious to always refetch remote resources, especially when dealing with large git repos and/or during edit/test cycles of kustomizations.

I saw that go-getter can handle existing git repos and update them. What about supporting a CLI option to specify a local cache directory to store remote files in, so that files (especially git repos) won't get downloaded over and over again during subsequent invocations of `kustomize build`?

**Comment by Liujingfang1** [comment]
This is no plan on that at this moment.

**Comment by anarcher** [comment]
IMHO, It's great if the caching works when building. :-)

**Comment by bcbrockway** [comment]
This would be really useful to us. Currently every clone of every remote repo takes around 11-12 seconds. Multiply that by as many as you reference and you can easily end up with rendering times of > 1m. I'd love to see either a cache or some kind of optimisation of the git clone.

**Comment by ringerc** [comment]
See also https://github.com/kubernetes-sigs/kustomize/issues/2460
