### ISSUE TITLE
Allow for directory recursion to be disabled

### ISSUE THREAD

**Issue by Tzrlk** [kubernetes-sigs/kustomize#4142]
I have a bottom-up configuration for kustomizations that is apparently disallowed in 2.0, and after reviewing the relevant issues (namely #596), found that it was a deliberate decision to forbid this design pattern. What I'm surprised at is that the decision was taken not to turn off implicit scanning of subdirectories, but to throw an error if they're found.

Given that a bottom-up configuration is a valid design pattern if implicit subdirectory scanning is disabled, could a flag be added to either the cli, or the configuration for each root that could prevent this scanning?

**Comment by KnVerey** [comment]
/triage needs-information

You're correct that this was an intentional change. Could you please provide more information on why the recommended directory structure does not work for you?

**Comment by Tzrlk** [comment]
For context, I'm working on a flux v2 application, where a number of separate applications are configured with some dependencies between them due to operator-based CRD deployment.

The structure I started with was as follows:
```
/
|- apps/
| |- app_1/
| | |- aws/
| | | |- app_1_aws_patch.yml
| | | \- kustomization.yaml
| | |- azure/
| | | |- app_1_azure_patch.yaml
| | | \- kustomization.yaml
| | |- app_1_resource.yml
| | \- kustomization.yaml
| | |- (etc.)
\- profiles/
  |- aws/
  | |- app_1.yml (/apps/app_1/aws)
  | \- kustomization.yaml
  |- azure/
  | |- app_1.yml (/apps/app_1/azure)
  | \- kustomization.yaml
  |- app_1.yml (/apps/app_1)
  |- app_2.yml
  \- kustomization.yaml
```
I then had to change it to this:
```
/
|- apps/
| |- app_1/
| | |- _base
| | | |- app_1_resource.yml
| | | \- kustomization.yaml
| | |- aws/
| | | |- app_1_aws_patch.yml
| | | \- kustomization.yaml
| | \- azure/
| |   |- app_1_azure_patch.yaml
| |   \- kustomization.yaml
| |- app_2/
| | |- (etc.)
\- profiles/
  |- _base/
  | |- app_1.yml (/apps/app_1/_base)
  | |- app_2.yml
  | \- kustomization.yaml
  |- aws/
  | |- app_1.yml (/apps/app_1/aws)
  | \- kustomization.yaml
  \- azure/
    |- app_1.yml (/apps/app_1/azure)
    \- kustomization.yaml

```
This means that to refer to the default implementation of an app, I either have to create a "default" permutation of the base, or refer to the _base folder. In some ways this ends up being neater, and in other ways messier, especially when permutations start multiplying out (e.g. _base -> aws -> _base -> <customer>).

Clearly this isn't the end of the world, as I've demonstrably worked around the issue, but having the option to turn off automatic scanning seems like a reasonable feature. It seems odd to me that it even auto-scans at all if there's an explicit resource configuration present; is there a difference between auto-scanning a directory and specifying it in the `resources` list?

**Comment by KnVerey** [comment]
Thank you for the details about your case. Kustomize doesn't automatically recurse over subdirectories. Does the error you're seeing talk about the root containing a visited root? If so, what's going on is that Kustomize keeps track of directories it has already visited and enforces certain rules about the relationship between them to prevent designs that lead to cycles, to keep Kustomizations self-contained and to make remote Kustomizations safer to use. You can find more details about this in the comment on the code in question:

https://github.com/kubernetes-sigs/kustomize/blob/master/api/loader/fileloader.go#L20-L71

**Comment by Tzrlk** [comment]
Right, after reading through the implementation, I can see the issue. Allowing this pattern would require either a recursive search, or passing a hash of loader paths around. The `RestrictionRootOnly` implementation of `loadRestrictorFunc` has no context beyond the file paths themselves. Even the most efficient implementation would require checking the hash for path "ownership" every time a resource is loaded. Definitely solveable, but more technical complexity than it's worth. Pity.
