### ISSUE TITLE
Kustomize throwing evalsymlink failure

### ISSUE THREAD

**Issue by yash97** [kubernetes-sigs/kustomize#4149]
**Describe the bug**

I trying to build kustomize from remote url.
This is what i did:

- target="https://github.com/kubernetes-sigs/kustomize/tree/master/examples/multibases/dev"
-  kustomize build $target
- getting error
```
Error: evalsymlink failure on '/private/var/folders/9c/tf3g9z1501730tpj8ptt4bb40000gp/T/kustomize-853640537/tree/master/examples/multibases/dev' : lstat /private/var/folders/9c/tf3g9z1501730tpj8ptt4bb40000gp/T/kustomize-853640537/tree: no such file or directory
```

**Files that can reproduce the issue**

**Expected output**

**Actual output**

**Kustomize version**

Version:kustomize/v4.2.0

**Platform**

macOs
**Additional context**

**Comment by natasha41575** [comment]
The following does succeed:

`target="https://github.com/kubernetes-sigs/kustomize/examples/multibases/dev/"`
`kustomize build $target`

When you are using `https://github.com/kubernetes-sigs/kustomize/tree/master/examples/multibases/dev`, what's happening is that kustomize is cloning `https://github.com/kubernetes-sigs/kustomize` and then looking for a top-level directory called `tree`. The URL should be of the format <REPO>/<PATH TO FILE>/?ref=<REF>

**Comment by EvanCarroll** [comment]
@natasha41575  I'm also getting this error with 

```
https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml
```

which is suspicious because the `/releases/` should certainly not trigger the cloning behavior.
