### ISSUE TITLE
v4.3.0 missing in k8s.gcr.io

### ISSUE THREAD

**Issue by harmjanblok** [kubernetes-sigs/kustomize#4153]
**Describe the bug**

v4.3.0 is missing in k8s.gcr.io, see https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/kustomize/kustomize?gcrImageListsize=30.

**Expected output**

Able to pull the image

**Actual output**

```
docker: Error response from daemon: manifest for k8s.gcr.io/kustomize/kustomize:v4.3.0 not found: manifest unknown: The named manifest is not known to the registry.
```

**Comment by mikebz** [comment]
I think @natasha41575 is publishing this now.

**Comment by natasha41575** [comment]
PR to add the image is here https://github.com/kubernetes/k8s.io/pull/2644
