### ISSUE TITLE
Cannot install via install_kustomize.sh

### ISSUE THREAD

**Issue by wgj** [kubernetes-sigs/kustomize#4159]
**Describe the bug**
`curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash` fails to install Kustomize. curl-pipe-bash was found via [this page](https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/) in documentation.

**Expected output**

Download binary of Kustomize.

**Actual output**

```
$ curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
tar (child): ./kustomize_v*_linux_amd64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Kustomize version**

I've tried running `install_kustomize.sh` with `4.3.0` and `4.2.0`, along with no parameter.

**Platform**

Linux

**Additional context**

```
$ cat /etc/issue
Debian GNU/Linux 10 \n \l

$ uname -a
Linux 5c8427738d54 4.15.0-1106-aws #113-Ubuntu SMP Fri Jun 18 21:31:27 UTC 2021 x86_64 GNU/Linux
```

**Comment by dario617** [comment]
Same here issue here :/

**Comment by greglanthier** [comment]
:FYI: https://github.com/kubernetes-sigs/kustomize/commit/7d0b7e21137a72ffc190d16735d5c6e8b44b84b4 has reverted the change for the moment.

**Comment by natasha41575** [comment]
We've reverted the PR that caused this issue!
