### ISSUE TITLE
Error when installing binaries using curl command

### ISSUE THREAD

**Issue by realshuting** [kubernetes-sigs/kustomize#4161]
**Describe the bug**

I'm following this [page](https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/) to install the binaries directly while it throws the following error:
```
➜   curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

tar: Error opening archive: Failed to open './kustomize_v*_darwin_amd64.tar.gz'
```

**Files that can reproduce the issue**
See the above command.

**Expected output**

**Actual output**

**Kustomize version**

**Platform**

**Additional context**

**Comment by natasha41575** [comment]
See https://github.com/kubernetes-sigs/kustomize/issues/4159
