### ISSUE TITLE
[Question] Is there any other way to reference the same base in two overlays without using namePrefix or nameSuffix? reference to #4104

### ISSUE THREAD

**Issue by leon-marcel** [kubernetes-sigs/kustomize#4173]
Hello folks,

I recently had a problem with kustomize build and opened an issue here #4104 .
The supplied solution worked and the kustomize build could execute.

The only problem I have with this solution is that the name of our kubernetes resources are now mangled. 
We use kustomization for our config management and have one overlay for each of our projects. 
At the time we use a shell script which iterate over each project and applies the kustomization. Our plan is to use FluxCD to automatically deploy the projects and update them. For this, I have created one Kustomization that included each Project Kustomization as a Resource. 

Our naming convention looks like this **company-project** .  So now if I use namePrefix for each kustomization, for instance the resource quotas are named like this **project-company-project-quota**.

Is there any way to bypass the problem without using namePrefix or nameSuffix?

Details about project structure and the error message can be viewed in the referenced issue. (#4104)

Any help would be appreciated

**Comment by natasha41575** [comment]
Could you provide some details about what you do with the output? The reason that you can't reuse the same base without altering the names is that you will now have multiple resources with the same GVKNN, which doesn't make sense to apply to a cluster.

**Comment by leon-marcel** [comment]
Our use case is that we use one overlay for each project in our config management for our openshift cluster. 
The overlay defines project specific resources, for instance ResourceQuotas - these differ for each project. 

It used to be no problem because in our installation process (e.g. the config of the openshift cluster) we used a shell script that iterates over each project and applies it once at a time - obviously there is no same id error because there is only one overlay, which references the base. 

Now our goal is to use FluxCD, it's a tool to automatically deploy or update the cluster when some changes are pushed to the repository. Therefore, you create a custom resource which references one kustomization file. Now we bundle all projects (we include all project specific Kustomizations as Resource) in one Kustomization File.

**Comment by natasha41575** [comment]
To confirm, are you trying to end up with a kustomization file that has multiple resources with the same GVKNN? 

We are trying to understand how that could work in practice. If you were to deploy something like that, kubectl would fail to deploy all the resources because all resources need to have a unique GVKNN. Is FluxCD separating the output of kustomize build somehow in such a way that this is not a problem?

**Comment by leon-marcel** [comment]
FluxCD just takes the output of kustomization and applies it. I don't know why they got the same GVKNN, shouldn't the difference between the overlays be enough to create two resources with distinct ID's? The namespace differs for each overlay so in my opinion there should not be a problem with deployment the resources, should it? If i build each kustomization separately it works just fine. If i use the namePrefix or nameSuffix the name label is changed for each resource. Is the GVKNN just based on the name label? Wouldn't it be possible for kustomize to distinct them by the namespace and create separate Resources?
