### ISSUE TITLE
OpenAPI schema declared in components is not overriding the builtin

### ISSUE THREAD

**Issue by ciis0** [kubernetes-sigs/kustomize#4179]
Is there a way to globally change the default OpenAPI schema used?

When for example used with OpenShift resource, strategic merges do not work due to missing schema.

I can add them via `openapi.path` in every kustomization.yaml, but then I have to copy OpenShifts Schema to all my folders, due to the load restrictor.

I does not seem like the OpenAPI used by Components is "inherit" by the Kustomizations including them.

Demo Repo: https://github.com/ciis0/kustomize-4179

**Comment by natasha41575** [comment]
> I does not seem like the OpenAPI used by Components is "inherit" by the Kustomizations including them.

While it is not possible for an overlay to "inherit" the OpenAPI schema from the base, I'd expect that it should be able to "inherit" it from a component. I.e. `./demo-overlay+component-openapi.sh` should work if I understand correctly. 

This sounds like a bug, and I will dig into it a little more.

/assign
/kind bug
/triage accepted

**Comment by natasha41575** [comment]
/retitle OpenAPI schema declared in components is not overriding the builtin.

**Comment by ciis0** [comment]
Is there a time horizon for the next release that will include the fix?
