### ISSUE TITLE
make kustomize work with CRD

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#42]
make name prefixing, labels|annotations and updating name reference work for CRDs
The original issue is https://github.com/kubernetes/kubectl/issues/338

**Comment by monopole** [comment]
notes here: https://docs.google.com/document/d/1yrZpmKAUpHR9z6f9bPQmpcLZS5QKdqQSQ8Tty_XKWWo/edit

**Comment by schweikert** [comment]
Could you make the docs document public?

**Comment by mengqiy** [comment]
@schweikert 
The document is viewable to the [`kubernetes-dev` group](https://groups.google.com/forum/#!forum/kubernetes-dev ) as usual :)

**Comment by schweikert** [comment]
@mengqiy Ah yes, thanks for letting me know! I joined the group and now I can see it.
