### ISSUE TITLE
Stop using ci-kustomize-periodic-default-gke job

### ISSUE THREAD

**Issue by spiffxp** [kubernetes-sigs/kustomize#4214]
Related:
- Part of: https://github.com/kubernetes/test-infra/issues/23778

The job should be migrated to not depend on proprietary/hosted clusters, and instead use a cluster that is provisioned by open source software, e.g.
- kubernetes/kops
- kubernetes-sigs/kind
- kubernetes/kubernetes/cluster/kube-up.sh with --provider=gce

The job is currently continuously failing, so if it's not actively being used, another option is to delete it entirely, ref: https://testgrid.k8s.io/sig-cli-misc#kustomize-periodic-default-gke

**Comment by spiffxp** [comment]
Tests appear to be failing with
```
Running: ../examples/integration_tests.sh
W0929 15:21:33.661] go: cannot find main module, but found .git/config in /go/src/sigs.k8s.io/kustomize
W0929 15:21:33.662] 	to create a module there, run:
W0929 15:21:33.662] 	go mod init
W0929 15:21:33.663] Failed to install kustomize.
```

**Comment by natasha41575** [comment]
@KnVerey @monopole considering that we have our own expansive suite of tests, do you think this job is necessary to keep? Can we drop it?

**Comment by spiffxp** [comment]
If you're cool with removing it, I've preemptively opened up https://github.com/kubernetes/test-infra/pull/23826 for your LGTM

**Comment by monopole** [comment]
This appears to run https://github.com/kubernetes-sigs/kustomize/blame/master/examples/ldap/integration_test.sh
I don't think this test is useful; 
i don't see a case where the e2e tests for kustomize could pass and this test would fail.
I say drop it.
