### ISSUE TITLE
Replace go-spew dependency as it seems be abandoned

### ISSUE THREAD

**Issue by mcbenjemaa** [kubernetes-sigs/kustomize#4218]
**Is your feature request related to a problem? Please describe.**

The go-spew is no longer maintained github.com/davecgh/go-spew 
Relates to kubernetes/kubernetes#103942

**Describe the solution you'd like**
Replace github.com/davecgh/go-spew with its alternatives:
in kubernetes we are trying to migrate to https://github.com/kr/pretty

**Describe alternatives you've considered**

**Additional context**

Wait until this PR is merged kubernetes/kubernetes#105282

**Comment by natasha41575** [comment]
If the dependency is being removed in kubernetes, I agree that we should make the same migration in kustomize.

/kind cleanup
/triage accepted

**Comment by natasha41575** [comment]
@mcbenjemaa Are you planning to make the PR to kustomize to do the migration, or were you hoping we could take it on?
