### ISSUE TITLE
Move `api/internal/git` to `api/git`.

### ISSUE THREAD

**Issue by Bolodya1997** [kubernetes-sigs/kustomize#4231]
## Is your feature request related to a problem? Please describe.

I am implementing some code to prefetch all used images referenced from `kustomize.yaml` before processing `kubectl apply -k` - it is needed to improve tests stability. To work with remote bases I am currently using https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/git/repospec.go for extracting git repo spec from URL and further processing it, and it is very helpful.
Unfortunately it is located in `api/internal/git` package, so it cannot be imported and can only be copy-pasted and so it probably will need to be manually updated in some future.

## Describe the solution you'd like

Can it be moved from `api/internal/git` package to just `api/git`?

**Comment by natasha41575** [comment]
Closing as I don't think we would like t support this request at the moment. Please feel free to respond if you have further questions or concerns!
