### ISSUE TITLE
kustomize build error accumulating resources

### ISSUE THREAD

**Issue by devopsguru339** [kubernetes-sigs/kustomize#4263]
**Describe the bug**
One of the resources in kustomization.yaml is a raw JSON file hosted in gitlab. I'm able to view that raw JSON, but the kustomize command gets an error when accumulating the data, when I run the `kustomize build overlays/env` command in 

Folder Structure:
```
.
|-- base/
|---- kustomization.yaml
|-- overlays/
|---- env/
|------ namespace.yaml
|------ kustomization.yaml
```

**Files that can reproduce the issue**

kustomization.yaml
```
namespace: bizx-ns2dev

resources:
- ../../base
- https://gitlab.orgName/api/v4/projects/<ID>/repository/files/<PATH_TO_FILE>/raw?private_token=<PRIVATE_TOKEN>&ref=main
```

**Expected output**

**Actual output**
```
Error: accumulating resources: accumulation err='accumulating resources from 'https://gitlab.orgName/api/v4/projects/<ID>/repository/files/<PATH_TO_FILE>/raw?private_token=<PRIVATE_TOKEN>&ref=main': missing Resource metadata': git cmd = '/usr/bin/git fetch --depth=1 origin main': exit status 128
```

**Kustomize version**
```
v4.4.0
```

**Platform**
```
MacOS Monteray 12.0.1
```

**Comment by natasha41575** [comment]
Would you be able to provide a JSON file that can reproduce the error? The error message `missing Resource metadata` implies that the file in question is not a kubernetes object with an apiVersion, kind, or name. Is that the case?

**Comment by devopsguru339** [comment]
You may be correct. Here is the beginning of the JSON:
```
{
    "format": "kubernetes",
    "version": 1,
    "systemType": "eng",
    "kubernetes": {
      "cluster": "cluster-name"
    },
    ...
    ...
 }
```

**Comment by natasha41575** [comment]
Kustomize resources are required to be [kubernetes objects](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/) - when transforming the YAML files kustomize is using the resource information stored in the `apiVersion`, `kind`, and `metadata.name` fields to keep track of each resource and transform it according to the kubernetes specification.

Is there something specific you are trying to do by having a JSON file in your configuration? I'm curious if your use case can be solved by some other kustomize feature.

**Comment by devopsguru339** [comment]
Well the apiVersion and kind will be based off of internal tooling. The entire environment is in JSON.

**Comment by natasha41575** [comment]
> Well the apiVersion and kind will be based off of internal tooling.

I'm not sure I understand. Are you expecting kustomize to treat a JSON file that doesn't have `apiVersion`, `kind`, or `metadata.name` as a kubernetes resource? These fields must be populated before being transformed by kustomize, or they are not kubernetes objects and kustomize won't know what to do with them.

**Comment by maazmmd** [comment]
I'm getting the same issue any help here, please?? Been stick for a while unable to resolve the issue

**Comment by maazmmd** [comment]
Using the same structure
.
|-- base/
|---- kustomization.yaml
|-- overlays/
|---- env/
|------ namespace.yaml
|------ kustomization.yaml

**Comment by balavellingiri** [comment]
I have facing exactly the issue as reported. I'm not able to call the customization files into the bases construct from a internal remote repo

**Comment by project-administrator** [comment]
Same issue with kustomize cli. 
However, fluxcd kustomize-controller works with the same code, maybe because it's a bit different from kustomize, e.g. this fluxcd feature: "generates the kustomization.yaml file if needed"
