### ISSUE TITLE
`kustomize build` should output resource of KRM Spec format 

### ISSUE THREAD

**Issue by yuwenma** [kubernetes-sigs/kustomize#4275]
**Is your feature request related to a problem? Please describe.**

kustomize proposed [the KRM function specification](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md) and it potentially can be further expanded to integrate with other KRM function specification tools (e.g. kpt). 

**Describe the solution you'd like**

Add a "--format" flag to `kustomize build` which format the output in the form of KRM function specification (ResourceList)

**Comment by yuwenma** [comment]
@bgrant0607

**Comment by bgrant0607** [comment]
This would facilitate passing the output to other tools that operate on ResourceList.

It looks like this was previously discussed here:
https://github.com/kubernetes-sigs/kustomize/issues/3979#issuecomment-901260180
