### ISSUE TITLE
Document helmCharts support for values.yaml

### ISSUE THREAD

**Issue by HariSekhon** [kubernetes-sigs/kustomize#4309]
I've got various `values.yaml` files saved for helm and would like `helmCharts` to be able to reference and use them without having to switch to using `valuesInline`.

**Describe the solution you'd like**

An alternative field to `valuesInline` such as `valuesFile` that takes a file and does the same as a `helm template ... -f values.yaml` would.

**Describe alternatives you've considered**

I'm currently using `helm template ... -f values.yaml  > template.yaml` and sourcing the resulting template.yaml in the `kustomization.yaml` to work around this issue, avoiding helmCharts entirely if I need to use any values customization as I want to keep my `values.yaml` separate and portable from the `kustomization.yaml` instead of inline.

**Comment by HariSekhon** [comment]
Update:

I found a doc which has valuesFile already:

https://cloud.google.com/anthos-config-management/docs/how-to/use-repo-kustomize-helm

and have tried that, but I didn't see this in the Kustomization documentation here:

https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/

**Comment by gbonnefille** [comment]
Same here: the documentation seems to treat the (obsolete) helmChartInflationGenerator and not the helmCharts: field.

**Comment by HariSekhon** [comment]
Btw I solved this usage myself via testing using the above GCP doc I found and you can reference it here in my Kubernetes repo:

https://github.com/HariSekhon/Kubernetes-configs/blob/825c1b69ada46129d30c4cbd6183f1ca5683dd01/kustomization.yaml#L110

**Comment by gbonnefille** [comment]
There are a lot of issues with this documentation. I started a contribution (https://github.com/gbonnefille/cli-experimental/tree/improve-helmchart-documentation) but I felt discouraged due to the need of CLA just for documentation patch.

I hope someone will find my contribution, copy paste it and apply it, without any credits...
