### ISSUE TITLE
Is it intentional that kustomize elements (e.g. patches) don't get processed in included kustomization files?

### ISSUE THREAD

**Issue by OOPMan** [kubernetes-sigs/kustomize#4317]
I am using kustomize v4.4.0 and noticed that kustomization elements like `patches` and `images` only seem to work in the initial `kustomization.yaml` file that is processed. These elements in `kustomization.yaml` files included via a `resources` element do not seem to get processed at all. 

Is this intentional?

**Comment by natasha41575** [comment]
Could you provide a sample of your input? If you provide a directory in the `resources` field that contains a kustomization.yaml file, it will treat that directory as a base kustomization, and run the configuration defined in that base kustomization.yaml file, before passing on the base resources to the parent kustomization.

**Comment by OOPMan** [comment]
@natasha41575 I'll see if I can come up with a minimal working example, since I can't really share the exact files I'm working with

**Comment by OOPMan** [comment]
@natasha41575 Okay, I put together a minimal example and attached it. To test, run with `kustomize build test/clients/myclient/dev/concrete`

What I was hoping to be to do was have my individual applications apply patches to the ingress definitions to add their own ingress configurations. 

Unfortunately it seems like when `test/applications/a-mock-service/base/kustomization.yaml` is processed it doesn't have any visibility of the ingress resource included in `test/clients/myclient/dev/concrete/kustomization.yaml`, even if I include the ingress resource before the application resource. Unfortunately I can't include the ingress resource in `test/applications/a-mock-service/base/kustomization.yaml` either as this causes kustomize to complain about redefinition.

I'm not sure there is a solution for this other than for me to do what I'm doing in my actual project right now, in which I placed the patches in my `kustomization.yaml` that includes the ingress resource...

[test.zip](https://github.com/kubernetes-sigs/kustomize/files/7628567/test.zip)

**Comment by natasha41575** [comment]
It sounds like you might benefit from using a component rather than a base. The documentation is here: https://kubectl.docs.kubernetes.io/guides/config_management/components/

Could you give this a try and let me know if you have any questions or trouble with it?

**Comment by OOPMan** [comment]
I'll take a look and see if I can get some results using components :-)
