### ISSUE TITLE
[Question] FYI there's a certificate error showing for kustomize.io site

### ISSUE THREAD

**Issue by noahjd** [kubernetes-sigs/kustomize#4324]
In chrome, there's a certificate error when connecting to kustomize.io
NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by natasha41575** [comment]
kustomize.io was not our website; the domain has literally just been transferred to us. We will take a bit of time to figure out what we want to do with it.

**Comment by natasha41575** [comment]
kustomize.io and general docs progress will be tracked in #4338
