### ISSUE TITLE
kustomize build - Error: unable to find one of

### ISSUE THREAD

**Issue by JCzz** [kubernetes-sigs/kustomize#4331]
Have you seen the following from this tutorial:
https://kubectl.docs.kubernetes.io/guides/introduction/kustomize/#1-make-a-kustomization-file

It says `kustomize build ~/someApp` but nothing is created - see error beneath?

MacOs:
Version 12.0.1

kustomize version

    {Version:kustomize/v4.4.1 GitCommit:b2d65ddc98e09187a8e38adc27c30bab078c1dbf BuildDate:2021-11-11T23:27:14Z GoOs:darwin GoArch:amd64} 

kustomize build .

    Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '<path>'

**Comment by natasha41575** [comment]
What is the content of your `~/someApp/kustomization.yaml` file?

**Comment by JCzz** [comment]
Thanks @natasha41575

My mistake, I missed the concept - I thought it would create the kustomize.yaml file. After creating it and configure it, it worked as expected.
