### ISSUE TITLE
Tutorial link on kustomize.io leads to 404

### ISSUE THREAD

**Issue by lennartjuette** [kubernetes-sigs/kustomize#4333]
When trying to click the tutorial link on https://kustomize.io I'm being redirected to https://kustomize.io/tutorial which presents a 404 / Page not found error

**Files that can reproduce the issue**

Example:

Try to navigate to https://kustomize.io/tutorial
    or
Open https://kustomize.io/ and click the "Tutorial" link.

**Expected output**

Some kind of tutorial.

**Actual output**

"Page not found" - 404 Error

```
─lennart.juette@WM-OFKB-LEJ2 ~
╰─$ date && curl -v  https://kustomize.io/tutorial                                                                                                                                  130 ↵
Wed Dec  8 13:06:38 CET 2021
*   Trying 104.198.14.52...
* TCP_NODELAY set
* Connected to kustomize.io (104.198.14.52) port 443 (#0)

[...BLABLABLA...]

> GET /tutorial HTTP/2
> Host: kustomize.io
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 404
< cache-control: public, max-age=0, must-revalidate
< content-type: text/html; charset=utf-8
< date: Wed, 08 Dec 2021 12:06:19 GMT
< etag: 1534274041-ssl
< strict-transport-security: max-age=31536000
< x-nf-request-id: 01FPCZ0GMB6JRZ6MXPCDVHY7C0
< content-length: 3154
< server: Netlify
< age: 20
<
<!DOCTYPE html>
<html>
  
[...BLABLABLA...]

        <div class="body">
          <p>Looks like you've followed a broken link or entered a URL that doesn't exist on this site.</p>
          
[...BLABLABLA...]

* Connection #0 to host kustomize.io left intact
* Closing connection 0
```

**Kustomize version**

N/A

**Platform**

N/A

**Additional context**

N/A

**Comment by natasha41575** [comment]
kustomize.io has just been transferred from a 3rd party company to us. We will take some time to revamp the docs following this transfer.

**Comment by natasha41575** [comment]
kustomize.io/general docs progress will be tracked in https://github.com/kubernetes-sigs/kustomize/issues/4338
