### ISSUE TITLE
Pass openapi to KRM Functions

### ISSUE THREAD

**Issue by KnVerey** [kubernetes-sigs/kustomize#4351]
Today, each extension that needs to patch custom resources, it will need to anticipate and embed the required openapi documents itself. This makes extensions less portable across Kustomizations.

We should consider extending the KRM Function specification to include an openapi field that can be used to pass the openapi documents the end user gives Kustomize through to functions declaratively. 

Natasha tells me this has been considered in the past, and has performance implications due to the size of the documents. We could consider doing this on an opt-in basis by adding a field to the KRM Functions schema in Catalog.

**Comment by natasha41575** [comment]
cc @mengqiy
