### ISSUE TITLE
replacements by path include should allow  multiple replacements in one file

### ISSUE THREAD

**Issue by yannick** [kubernetes-sigs/kustomize#4356]
it should be possible to include one replacement file that contains an array of replacements

**Comment by natasha41575** [comment]
I have no objections to this feature; kustomize should be able to recognize when there is one replacement (the current way that it works) or if there is a list of replacements.

/triage accepted

**Comment by tamboliasir1** [comment]
Hi @natasha41575 can you please give me bit insight for where to start.. I think I can work on this.

**Comment by natasha41575** [comment]
resolved by #4485
