### ISSUE TITLE
"Try it" Tutorial Link on homepage is broken

### ISSUE THREAD

**Issue by GuyPaddock** [kubernetes-sigs/kustomize#4360]
**Describe the bug**
1. Visit https://kustomize.io/.
2. Click "Try It" under the "Tutorial" section.

**Expected output**
The tutorial page comes up.

**Actual output**
The link leads to https://kustomize.io/tutorial, which does not exist. A 404 page appears instead.

**Comment by natasha41575** [comment]
See https://github.com/kubernetes-sigs/kustomize/issues/4338 for the current status of the documentation and our goals.

/kind duplicate
