### ISSUE TITLE
[Question] Is there a KRM plug-in registry?

### ISSUE THREAD

**Issue by GuyPaddock** [kubernetes-sigs/kustomize#4382]
I know that the specification for KRM plug-ins mentioned that a plug-in registry is envisioned. Apologies if I missed the ticket that's covering that, but is there such a registry available?

We've crafted a KRM transformer plug-in that we believe could be quite useful for teams that are deploying applications that use pre-allocated PVs and PVCs in each environment (e.g., a multi-tenant system where storage for each tenant comes from a different share or different storage account).

The plug-in:
https://github.com/Inveniem/kustomize-storage-config-transformer

**Comment by natasha41575** [comment]
There will be a registry very shortly! You can keep an eye on https://github.com/kubernetes-sigs/krm-functions-registry.

**Comment by GuyPaddock** [comment]
Thanks, @natasha41575!
