### ISSUE TITLE
kustomize.io Tutorial Link 404

### ISSUE THREAD

**Issue by highb** [kubernetes-sigs/kustomize#4389]
**Describe the bug**
When I click on the "Try it" link on the main page...
![Screen Shot 2022-01-14 at 16 15 42-0800](https://user-images.githubusercontent.com/759848/149600622-53e2a02e-ddd4-4634-a8af-fefe355dcf74.png)

I get a 404.
![Screen Shot 2022-01-14 at 16 15 51-0800](https://user-images.githubusercontent.com/759848/149600630-3e5eb858-9f21-4d3d-b44a-3c085e58334b.png)

Additionally, the `apply -k` docs link further down the page as show in this screenshot is also a 404.
![image](https://user-images.githubusercontent.com/759848/149600825-c67d89c0-5443-4962-abdd-3dfe984d8f53.png)

**Files that can reproduce the issue**

Go to https://kustomize.io/ and click on "Try it"

**Expected output**

A tutorial

**Actual output**

404

**Kustomize version**

N/A

**Platform**

macOS

**Additional context**

**Comment by natasha41575** [comment]
@irvifa Are you planning to work on this? If so, please feel free to assign it to yourself.

**Comment by KnVerey** [comment]
Closed by https://github.com/replicatedcom/kustomize-www/pull/19

We can consider restoring the tutorial as part of #4338 , but for now we've removed the broken links.
