### ISSUE TITLE
git cloner uses local filesystem instead of `fSys`

### ISSUE THREAD

**Issue by Haegi** [kubernetes-sigs/kustomize#4390]
**Describe the bug**

When using `kustomize` in `go` (`sigs.k8s.io/kustomize/api/krusty`), it is currently not possible to use a in-memory filesystem (`filesys.MakeFsInMemory()`) and a remote target.

This happends because everything operates on the in-memory filesystem passed to the `Run()` method, despite the `cloner` (`git.Cloner`).

The stacktrace for this:
 * The [cloner](https://github.com/kubernetes-sigs/kustomize/blob/6e82b210a9e0651cc8392d2931c64348137b82ff/api/loader/fileloader.go#L207) 
 doesn't get a `fSys` (`filesys.FileSystem`) passed.

    => Here it is already to later because the cloner doesn't know anything about a `fSys`.
 * The `ClonerUsingGitExec` instanciates a [newCmdRunner](https://github.com/kubernetes-sigs/kustomize/blob/6e82b210a9e0651cc8392d2931c64348137b82ff/api/internal/git/cloner.go#L17).
 * The `newCmdRunner` will create a [newTmpConfirmedDir](https://github.com/kubernetes-sigs/kustomize/blob/6e82b210a9e0651cc8392d2931c64348137b82ff/api/internal/git/gitrunner.go#L29).
 * `newTmpConfirmedDir` will create a temporary dir on the machine. See [here](https://github.com/kubernetes-sigs/kustomize/blob/6e82b210a9e0651cc8392d2931c64348137b82ff/kyaml/filesys/confirmeddir.go#L20).

**Files that can reproduce the issue**

main.go

```go
package main

import (
	"fmt"
	"os"

	"sigs.k8s.io/kustomize/api/krusty"
	"sigs.k8s.io/kustomize/api/types"
	"sigs.k8s.io/kustomize/kyaml/filesys"
	"sigs.k8s.io/yaml"
)

func main() {
	fSys := filesys.MakeFsInMemory()
	kustomization := types.Kustomization{
		Resources: []string{
			"github.com/kubernetes-sigs/kustomize/examples/multibases?ref=v1.0.6",
		},
	}

	bytes, err := yaml.Marshal(kustomization)
	if err != nil {
		fmt.Print(err)
		os.Exit(1)
	}

	err = fSys.WriteFile("kustomization.yaml", bytes)
	if err != nil {
		fmt.Print(err)
		os.Exit(1)
	}

	kustomizer := krusty.MakeKustomizer(krusty.MakeDefaultOptions())
	_, err = kustomizer.Run(fSys, ".")
	if err != nil {
		fmt.Print(err)
		os.Exit(1)
	}
}

```

go.mod
```go
module xxx

go 1.16

require (
	sigs.k8s.io/kustomize/api v0.10.1
	sigs.k8s.io/kustomize/kyaml v0.13.0
	sigs.k8s.io/yaml v1.3.0
)
```

**Expected output**

No error and kustomize does it things (clone the repo and so on).

**Actual output**

```
accumulating resources: accumulation err='accumulating resources from 'github.com/kubernetes-sigs/kustomize/examples/multibases?ref=v1.0.6': '/github.com/kubernetes-sigs/kustomize/examples/multibases?ref=v1.0.6' doesn't exist': '/private/var/folders/t6/msc_f56j073427s1kv0jb4gr0000gn/T/kustomize-1859347002/examples/multibases' doesn't exist
```

**Kustomize version**

[kustomize api v0.10.1](https://pkg.go.dev/sigs.k8s.io/kustomize/api@v0.10.1)

**Platform**

macOS(arm64)

**Additional context**

**Comment by natasha41575** [comment]
While I agree that this is annoying, especially when writing tests, I'm not sure if there is a feasible solution. `FsInMemory` is a fake filesystem that is backed by a private struct [`fsNode`](https://github.com/kubernetes-sigs/kustomize/blob/69e52282643f261b8228607f6bc7b08d667aa552/kyaml/filesys/fsnode.go#L24). 

For the git cloner to be able to clone to a file system in memory, it would have to clone the repo and then copy all of the contents into a tree of `fsNode`s. This is a nontrivial, expensive task, especially if the cloned repository is quite large.

What is your use case for wanting to use an in-memory file system along with remote targets? We have some examples of tests if that's what you're looking for, but all of our tests with remote targets use the local filesystem and need to clean themselves up afterward.

/triage under-consideration

**Comment by Haegi** [comment]
Thanks for the explanation. You’re right, it could be very expensive in some cases.

We want some environment variable substitution for kustomization files. To allow something like:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/kubernetes-sigs/kustomize/examples/multibases?ref=${REPO_TAG}
```

I guess this would be a quite big change to the current kustomize codebase.
Therefore, we built some custom logic around `kustomizer.Run()`, which traverses the kustomization file and replaces the placeholders with environment variables.
In this case, we also have to copy the files from the local filesystem to the in-memory filesystem. But this in not a big deal because we know how small our repositories are at the moment.

**Comment by natasha41575** [comment]
Though practically I think we should consider if there is a way to go about this without introducing a very expensive operation to kustomize, the issue itself is still valid and we can discuss implementation details if someone has a proposal for it.

/triage accepted
