### ISSUE TITLE
[Question] Environment Variables for Containerized KRM Functions

### ISSUE THREAD

**Issue by devstein** [kubernetes-sigs/kustomize#4394]
Hi 👋  I maintain [KSOPS](https://github.com/viaduct-ai/kustomize-sops) a popular kustomize plugin. I'd like to migrate it to the new KRM style plugins, ideally as a containerized KRM function. In order to do so, the container needs access to credentials to decrypt the SOPS encrypted resources. 

Is it possible to configure environment variable or volume mounts for Containerized KRM functions? 

Related Issue: https://github.com/kubernetes-sigs/kustomize/issues/4290

**Comment by devstein** [comment]
One option seems to be to pursue KRM exec functions and rely on the fix proposed in [this PR](https://github.com/kubernetes/enhancements/pull/3097). Would this approach make sense?

**Comment by natasha41575** [comment]
From [the plugin graduation KEP ](https://github.com/kubernetes/enhancements/blob/9fe3861938a1ec8fd7d0b0db4fb93e317f6bed71/keps/sig-cli/2953-kustomize-plugin-graduation/README.md)(which we are currently working towards):

> The env field for container plugins will be deprecated. In line with Kustomize's principles, plugin configuration should be passed in the KRM object and should not be affected by the execution environment. The network and storage mount options will be retained, as they are needed to support some common generator plugin use cases. Guidance on their appropriate use will be added to the plugin developer documentation. 

To answer your question, storage mounts are currently supported (via the `mount` option) and we plan to keep them around. Let me know if you'd like an example of how to do this, I can dig one up.

Env vars however are somewhat misaligned with kustomize principles. In general we believe that everything should be available declaratively in the plugin configuration file, and checked into version control. However, I do empathize with the case of wanting to pass in credentials - that's not something you would want to put directly into your config files. @mengqiy @KnVerey WDYT? 

> One option seems to be to pursue KRM exec functions and rely on the fix proposed in this PR. Would this approach make sense?

Yes, using KRM exec functions will allow you to use env vars and files on your filesystem without needing to pass them along into a container.

**Comment by devstein** [comment]
Hi @natasha41575 thanks for getting back to me! 

Is the example in [this issue](https://github.com/kubernetes-sigs/kustomize/issues/4290) a valid example of the `mount` option? 

Environment variables are preferable, but for the KSOPS use-case, we could also mount the credentials as volume (i.e `~/.aws/credentials` in the KMS case). 

KRM exec function is appealing because it will be the simplest migration for KSOPS users.

**Comment by natasha41575** [comment]
@devstein Yes, that is an example of how to use mounts for containerized functions. If mounting the credentials as a volume works for you then that would be the way to go. Evidently mounting does not always work as detailed in the issue you linked, but we will fix it when we can. That issue would be a good place to look for updates.   

I confirmed that we are planning to deprecate and remove passing along environment variables into functions. This aligns with our principles of maintaining all configuration explicitly in files that can be checked into version control. 

/kind support
/triage not-an-issue

/unlabel needs-kind
/unlabel needs-triage
