### ISSUE TITLE
Allow static compilation without `CGO_ENABLED=1`

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kustomize#4397]
**Is your feature request related to a problem? Please describe.**
Building kustomize (or more importantly, anything that depends on kustomize, which includes many kubernetes libraries), cannot be built with `-static` and `CGO_ENABLED=1` without warnings.

For example:
```
$ CGO_ENABLED=1 go build -ldflags '-extldflags "-static"' -tags="netgo,osusergo" ./
go: downloading github.com/olekukonko/tablewriter v0.0.4
go: downloading github.com/mattn/go-runewidth v0.0.7
# sigs.k8s.io/kustomize/kustomize/v4
/usr/bin/ld: /tmp/go-link-603970615/000001.o: in function `pluginOpen':
/usr/local/go/src/plugin/plugin_dlopen.go:20: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

The build still works. However, its concerning to ignore this warning, because while I can reason that I do not use plugins in kustomize, its plausible that later a dependency will start using plugins in a way that *does* impact me, and I will not notice because the warning is ignored.

**Describe the solution you'd like**

It would be great to have the ability to disable `plugin` imports. This could be done by adding a new build tag so that users can opt into disabling plugin support

**Describe alternatives you've considered**

Keep ignoring the warning, with risk. Or attempt to not import this code at all.

**Comment by KnVerey** [comment]
/triage accepted

> It would be great to have the ability to disable plugin imports. This could be done by adding a new build tag so that users can opt into disabling plugin support

We would be open accepting this feature if it can be done relatively non-invasively. That said, this is caused by Kustomize's Go plugin support here:

https://github.com/kubernetes-sigs/kustomize/blob/8dab94964f7a3e4e9700ba9bd3eaba333c29be37/api/internal/plugins/loader/loader.go#L282

And we are deprecating Go plugins, which should make this problem go away along with them.

**Comment by eddiezane** [comment]
A user with glibc (and maybe musl?) won't be impacted (maybe?) but it will impact Windows users because [Go plugins aren't supported](https://cs.opensource.google/go/go/+/refs/tags/go1.17.7:src/plugin/plugin_dlopen.go).

@howardjohn can you please share more about what you're doing with statically linking this?

**Comment by howardjohn** [comment]
We are just a fairly standard Kubernetes controller. We do not depend on kustomzie directly and do not care about kustomize plugins, we just get the dependency transitively through a kubectl import. We want to statically build to ease deployment (single binary in SCRATCH container vs shipping glibc)

**Comment by eddiezane** [comment]
> We are just a fairly standard Kubernetes controller. We do not depend on kustomzie directly and do not care about kustomize plugins, we just get the dependency transitively through a kubectl import. 

Gotcha. Until Go plugins are removed we can probably move this behind a build tag.

> We want to statically build to ease deployment (single binary in SCRATCH container vs shipping glibc)

I am probably missing something but in this case wouldn't you want to set `CGO_ENABLED=0`?

**Comment by howardjohn** [comment]
> I am probably missing something but in this case wouldn't you want to set CGO_ENABLED=0?

Unfortunately we need CGO_ENABLED=1 for other reasons unrelated (building with boringssl)
