### ISSUE TITLE
[Question] Applying multiple overlays dynamically

### ISSUE THREAD

**Issue by dmsolow** [kubernetes-sigs/kustomize#4408]
Let's say I have a single base, and multiple "types" of overlay. For example I might use overlays to specify one of three environments (dev, stag, prod). But I also might have three separate overlays which alter the docker image (a, b, c) used in the base. This might look like:
```
.
├── base
│   └── kustomization.yaml
└── overlays
    ├── environment
    │   ├── dev
    │   │   └── kustomization.yaml
    │   ├── prod
    │   │   └── kustomization.yaml
    │   └── stag
    │       └── kustomization.yaml
    └── image
        ├── a
        │   └── kustomization.yaml
        ├── b
        │   └── kustomization.yaml
        └── c
            └── kustomization.yaml
```

Let's say I want to possibly deploy any combination of the two types of overlays. So I might want to deploy image `a` to environment `dev`, or image `c` to environment `stag`, and so on. That gives 3x3=9 possible different combinations. How should I implement this scenario in kustomize? I know that I could create 9 different overlays, but this doesn't scale if I add more options.

Ideally there would be a way to dynamically specify multiple overlays to combine when I run the kustomize command. So I could run `kubectl kustomize ./overlays/environment/prod/ ./overlays/image/b` but this doesn't appear to work. Any ideas?

**Comment by FalconerTC** [comment]
I would love to know what the recommended approach here is!
