### ISSUE TITLE
Consider deprecating `kustomize edit add base`

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#4412]
It does the same thing as `kustomize edit add resource`, is there a need to have both? I could perhaps see the argument for keeping both, but limiting `kustomize edit add base` to only being able to add kustomization directories (i.e. bases), and limiting `kustomize edit add resource` to only being able to add resource files. However, currently you can add any existing file or directory to the `resources` with both commands, so it feels a bit redundant. 

/kind deprecation
/triage under-consideration

**Comment by yuwenma** [comment]
+1 to deprecate `kustomize edit add base`. I like the fact that kustomize API is backward compatible by mapping deprecated fields to new features. How about mapping `kustomize edit add base` to `kustomize edit add resource` and giving a warning that this cmd will be deprecated soon. 

Agree that limiting `kustomize edit add base` to only add kustomization directories  does not give much value.
