### ISSUE TITLE
Multiline string error

### ISSUE THREAD

**Issue by pmacieje** [kubernetes-sigs/kustomize#4415]
**Describe the bug**

When try to deploy with fluxcd that use kustomize a simple mercure resource with subscriberJwtKey parameter as multiline string it's failed. When do it directly with kubectl it works. Problem apears because kustomize got problem with characters as "-----" in provided string.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - mercure-helm-release.yaml

```

mercure.yaml

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mercure
spec:
  releaseName: mercure
  chart:
    repository: https://charts.mercure.rocks
    name: mercure
    version: 0.13.0
  values:
    dev: true
    subscriberJwtAlg: "RS512"
    subscriberJwtKey: |-
      -----BEGIN PUBLIC KEY-----
      MoooIjANBgkqhkiG9w0BAQOOOOOQ8AMIIBCgKCAQEAs3akgQewFsEvJHAUB1Ey
      7v+BDbt2oeE2uSg4s7MgM7oe/HjOsA0rOtzV1G+oUK7V4HLK/6OhD0F8dsL+BrOC
      PSbSJYBeGB8EugW08ZSizK/IRJW5AwjgzgPYzh+0QMHJqqj2soaoyZltAgqFDZt8
      SXAVL6uP0AFb1UgIjveOHT4pGOR7bJ5mBlC0FFNmI3zIpOOOOOldup80A/VwF+hs
      8+ARu+G34n5OQL0+RbRlunZt3a6LKMdfDD08/ddZPY/WTgbd/NUIseAWYwYVY7KH
      by9pgk5OkqF6xmLPVnzS+lWcfqLm08+M2x7ctuZcf3rJhgHUVkoCOAHZtCIOH9zh
      ooooAQAB
      -----END PUBLIC KEY-----
...
```

...
-->

**Expected output**

helmrelease.helm.fluxcd.io/mercure created

**Actual output**

err="loading resources from repo: error executing generator command \"XDG_CONFIG_HOME=$(dirname `pwd`) kustomize build . --enable_alpha_plugins\" from file \"../.flux.yaml\": exit status 1\nerror output:\n2022/01/24 08:35:59 Error while decoding YAML object. Err was: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string \"json:\\\"apiVersion,omitempty\\\"\"; Kind string \"json:\\\"kind,omitempty\\\"\" }\n

**Kustomize version**

fluxcd v.1.2.3
Kustomize v.3.8.7

**Platform**

EKS/AWS

**Additional context**

When deply the resource directly with:

kubectl apply -f mercure.yaml 

everything works fine.

But when use flux with kustomize got output with error.

**Comment by KnVerey** [comment]
I see you're using Kustomize v.3.8.7, which is a pretty old version. Major improvements to YAML handling have been made since then, and `kustomize build` succeeds with your sample using v4.4.1. 

/close
