### ISSUE TITLE
not able to install 3.2.0, 3.2.1, 3.2.2, 3.2.3 on windows

### ISSUE THREAD

**Issue by romanzdk** [kubernetes-sigs/kustomize#4417]
Can someone suggest how to install 3.2.0 version of kustomize on Windows, please?

I need specifically v3.2.0 on Windows. I am following this tutorial.

Source code: https://github.com/kubernetes-sigs/kustomize/releases/tag/v3.2.0

I downloaded the zip file and installed Go. However when I run go install . inside that kustomize folder i get: no Go files in path/kustomize/.. Also tried step by step aforementioned tutorial but same error..

Trying to install via https://github.com/kubernetes-sigs/kustomize/blob/master/hack/install_kustomize.sh ./install_kustomize.sh 3.2.0 I get: Version v3.2.0 does not exist.

When I try ./install_kustomize.sh 3.2.1 I get:

tar (child): ./kustomize_v*_windows_amd64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

I also tried downloading 3.2.0.tar.gz file, and unzipping it but whats next? Go connot build/install it, there are no kustomize executable either.. I do not know.. I am clueless...

Env: Windows 10, executing in GIT Bash

**Comment by natasha41575** [comment]
> I downloaded the zip file and installed Go. However when I run go install . inside that kustomize folder i get: no Go files in path/kustomize/.. Also tried step by step aforementioned tutorial but same error..

Within `kustomize`, there is another directory called `kustomize`. Are you running `go install .` inside the `path/kustomize/kustomize` directory or just `path/kustomize`? Please try the former if you haven't yet.

/kind support

**Comment by romanzdk** [comment]
yeah, that worked, but only for 3.2.1+. 3.2.0 does not have that folder inside

**Comment by natasha41575** [comment]
Could you elaborate on why you specifically need 3.2.0, and why 3.2.1 won't suffice? 3.2.0 is a very old version of kustomize and we may not be able to prioritize supporting old versions.

**Comment by romanzdk** [comment]
Because of the installation on Kubeflow https://github.com/kubeflow/manifests/tree/v1.4-branch#prerequisites

**Comment by natasha41575** [comment]
If kubeflow is compatible with kustomize 3.2.0, it should also be compatible with 3.2.1. Have you tried this out? I’m curious what errors you would get, as there shouldn’t be any breaking changes between 3.2.0 and 3.2.1.

**Comment by romanzdk** [comment]
Yeah, 3.2.1 worked. Issue was I was not able to install 3.2.0 following the published tutorials.
