### ISSUE TITLE
[Question] How to apply a kustomization containing helmCharts

### ISSUE THREAD

**Issue by janbols** [kubernetes-sigs/kustomize#4435]
I followed the example described in https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md.
It creates a chart in the base dir.

I now want to apply the kustomization using `kubectl apply -k dev`. This gives the following:
```
➜  tmp.h6x5IPNa3Q kubectl apply -k dev               
error: accumulating resources: accumulation err='accumulating resources from '../base': '/tmp/tmp.h6x5IPNa3Q/base' must resolve to a file': recursed accumulation of path '/tmp/tmp.h6x5IPNa3Q/base': trouble configuring builtin HelmChartInflationGenerator with config: `
name: minecraft
releaseName: moria
repo: https://itzg.github.io/minecraft-server-charts
valuesInline:
  minecraftServer:
    difficulty: hard
    eula: true
    rcon:
      enabled: true
version: 3.1.3
`: must specify --enable-helm
```
How can I apply this kustomization? Specifying `--enable-helm` is not allowed and returns ...
```
➜  tmp.h6x5IPNa3Q kubectl apply -k dev --enable-helm
error: unknown flag: --enable-helm
See 'kubectl apply --help' for usage.
```

The only workaround now is to comment out the `helmCharts` section in the base kustomization.yml. Is this the way it should be?

**Comment by juame** [comment]
Hi @janbols 
I guess this is related to the integration of kustomize in kubectl. See https://github.com/kubernetes/kubectl/issues/1144.

**Comment by epcim** [comment]
```
KUSTOMIZE_ARG ?= --stack-trace --enable-alpha-plugins --load-restrictor LoadRestrictionsNone --enable-exec --enable-helm
```
you need `--enable-alpha-plugins` on older versions

otherwise today with KRM function, you can start using rendering outside of kustomize, example: https://github.com/epcim/gitops-infra/blob/master/cluster/sys/adguard/fnRenderHelm.yml

**Comment by KnVerey** [comment]
> I guess this is related to the integration of kustomize in kubectl. See kubernetes/kubectl#1144.

This is correct. See the explanation on that issue, and #4401 for the longer term plan for Helm support.

/close
