### ISSUE TITLE
Different base contents in stages

### ISSUE THREAD

**Issue by savujevi** [kubernetes-sigs/kustomize#4458]
Hello,

what is the best practise in the case I have to stage an update of a content in the base folder of a repo to different stages avoiding the visibility of the update in the different stages at the same time.

Thank you for your help.

Best regards,
    Sascha Vujevic

**Comment by KnVerey** [comment]
/triage needs-information
/kind support

Can you please provide more detail on your workflow, in particular what you mean by "staging" updates?
