### ISSUE TITLE
[Question] customers last-mile modifications best practices 

### ISSUE THREAD

**Issue by noamApps** [kubernetes-sigs/kustomize#4473]
Hello, 
We are developing a product that optionally supports on-prem deployments, in many cases customers must insert inevitable "last-mile" modifications - settings storage classes, node selectors/affinities, tuning resource limitations and much more.

In helm,  this is straight-forward as all those modifications are made possible in a single file (values.yaml), users are not required to be familiar with the application structure and manifests, but it comes with the significant price of maintaining helm templates, which adds a considerable complexity and requires the engineers to familiarize themselves with yet another toolkit.

kustomize is much more simpler to maintain development-wise, and the overlays-oriented architecture is much clearer IMO, and  provide stronger guarantees regarding the artifacts integrity, but I've yet to understand how do I make those artifacts accessible for users modifications.

For now, I've created a temporary solution that adds helm template stubs around components I want to enable modifications in, it is extremely hacky and will not scale as we grow (it takes the kustomize output, and uses `yq` and `sed` to add the required helm templating stubs).

I would be happy to know if there is a way to create an application that is managed by kustomize, but allows users to add modifications in an easy and sensible way.

Thank you very much and best regards,

Noam Levy

**Comment by criztovyl** [comment]
have you considered [replacements](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/)?

**Comment by KnVerey** [comment]
/kind support

The usual Kustomize way is for the end user to write an overlay Kustomization that describes the changes they need to make. Unlike with helm templating, there is no restriction on what the end user can modify that way--they can change whatever they need to, which is especially useful if their needs are very heterogeneous. You could provide samples of what these overlays typically look like, and have the end users fork them to tailor them to their needs. If this paradigm doesn't work for you, please provide more details on the situation.

On the flip side, if you *do* want to create a formal API describing specific changes commonly need to make in a higher-level way, I recommend taking a look at extensions: https://kubectl.docs.kubernetes.io/guides/extending_kustomize/. With an extension, you can abstract over the most common transformations yourself, while still leaving users the ability to further customize its output with Kustomize.

**Comment by noamApps** [comment]
Hey, thank you for the detailed response!

I agree that the flexibility kustomize provide by removing the need for templating is a big advantage, but in our case for example, I have overlays for development/production, and once I build the production flavor, I have only two ways to deliver it - either a single file which is very hard to grasp, or completely deconstructed (with -o dir/) in a way that doesn't represent the app is it is. but the more significant pain-point is that I require the user to know *where* to patch, which requires them to get familiar with the application, and requires me to maintain a very detailed documentation regarding patch destinations for different kind of modifications, pre-templating allows me to be the responsible for the "where" question, and the user is left with only changing the values.

The second approach you've suggested is very interesting, If I will be able to create a plugin that will support a kustomization file that will mimic helm's values.yaml approach, especially mapping 1:many values and taking care of patching according to the value - it can really ease the adoption of kustomize among our clients, generally speaking I think it will ease the adoption of kustomize in general as probably a lot people are transitioning to kustomize rather that starting with it, but maybe I'm just making the problem bigger than it actually is 👍 

Thank you!

**Comment by criztovyl** [comment]
> especially mapping 1:many values

I do not quite understand what you mean by 1:n / one-to-many values, but I am intrigued to now, do you mind expanding on that? (Just curious.)

**Comment by noamApps** [comment]
Sorry for the ambiguity, I meant the ability to state a value once, and refer to it multiple times in different k8s objects and in different object sections. For example, in helm I can define a variable once in the values.yaml file, and add it as a suffix in a k8s object and as an annotation value in another, not necessarily a practical example but I hope it's clearer now.

**Comment by criztovyl** [comment]
yup, that makes it more clear, thx!
