### ISSUE TITLE
GetFieldValue doesn't work with fields that contain dots(.)

### ISSUE THREAD

**Issue by Goodwine** [kubernetes-sigs/kustomize#4487]
**Describe the bug**

`rnode.GetFieldValue` doesn't work correctly when the target field contains a `.`

For example when I call `rnode.GetFieldValue("foo.bar")` this function will try to find field "bar" within field "foo" instead of finding the field "foo.bar"

**Files that can reproduce the issue**

```go
package v1alpha1

import (
	"testing"

	"github.com/stretchr/testify/require"
	"sigs.k8s.io/kustomize/kyaml/kio"
	"sigs.k8s.io/kustomize/kyaml/yaml"
)

const input = `
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world-app
    foo.appname: hello-world-foo
`

func TestGetFieldValue(t *testing.T) {
	data, err := kio.ParseAll(input)
	require.NoError(t, err)

	labelRNode, err := data[0].Pipe(yaml.Lookup("metadata", "labels"))
	require.NoError(t, err)

	app, err := labelRNode.GetFieldValue("app")
	require.NoError(t, err)
	require.Equal(t, "hello-world-app", app)

	fooAppName, err := labelRNode.GetFieldValue("foo.appname")
	require.NoError(t, err)
	require.Equal(t, "hello-world-foo", fooAppName) // no field named 'foo.appname'
}
```

**Expected output**

`labelRNode.GetFieldValue("foo.appname")` should return `hello-world-app`

**Actual output**

`labelRNode.GetFieldValue("foo.appname")` returns an error because there is no field `foo`

**Kustomize version**

```go.mod
require sigs.k8s.io/kustomize/kyaml v0.13.1
```

**Additional context**

If my pod was defined as:
```yaml
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world-app
    foo.appname: hello-world-foo
    foo:
      appname: wtf       # <--------
```
then it would have "worked" but it would have returned `wtf` instead of `hello-world-app`.

**Workaround**

I can still use `rnode.Pipe(yaml.Lookup("foo.appname"))` and I can also use `m, err := rnode.Map()` followed by `m["foo.appname"]`, it just caught me offguard

**Comment by natasha41575** [comment]
/triage accepted

There are these path splitters in api, with a TODO to move them to kyaml that allow escaping delimiters. Part of this issue would to be to finally do that TODO, and use it in `rnode.GetFieldValue`, so that you can do something like `rnode.GetFieldValue("foo\.bar")`.

**Comment by Goodwine** [comment]
Is there an example of something that was migrated over from `strings.Split` to the better path splitters in case this is something I could try to work on?


In hindsight I guess it makes sense `obj.foo.bar` doesn't work because in regular JSON I would do `obj["foo.bar"]`, I guess what was surprising to me is that I expected `GetFieldValue` **not** to recursively go down the path, the name of the function made me think I was extracting the value of the key/field

**Comment by natasha41575** [comment]
It's used in the replacements filter here: https://github.com/kubernetes-sigs/kustomize/blob/6950a0d246408e9c321cfe28a9daf67ffd32dc9b/api/filters/replacement/replacement.go#L116

The purpose is to traverse a path that looks like `metadata.annotations.config\.kubernetes\.io/local-config`. This lets you target something like

```
metadata:
  annotations:
    config.kubernetes.io/local-config: # this is the target field here
```

**Comment by r0ushann** [comment]
hello! I'm interested in this issue. please guide me.

**Comment by NikhilSharmaWe** [comment]
@natasha41575 So I think there is no need to make any changes in the repo since it is not a bug, am I right ?
Could you please inform if we need some improvements, I will look forward to work on it.

**Comment by natasha41575** [comment]
See my comment above: https://github.com/kubernetes-sigs/kustomize/issues/4487#issuecomment-1050093935. This explains the work that needs to be done to resolve this issue.
