### ISSUE TITLE
kustomize should provide a way to set variables using cluster scope

### ISSUE THREAD

**Issue by sullyvon** [kubernetes-sigs/kustomize#4488]
When doing kustomize apply you are running with kubectl scope which means you should have cluster scope.

kustomize should have a way to target values from existing cluster scope

clusterscope.namespace.object.blah

kubectl/oc for example it would be nice to be able to programmatically dig into cluster scope to get the infrastructureName

a variable target set that points to

clusterscope.cluster.status.infrastructureName

oc get -o jsonpath='{.status.infrastructureName}{"\n"}' infrastructure cluster

This would make it easier to programatically create machinesets aligned to the current cluster infrastructureName

I'm sure there are many many other situations where this would make since.

Per [0] which I think explains the issue but feel like the solution is hacky because your gitops code strays from what is created lot of dependence now on that operator working right confusing look at what gets created versus what's in git

"The second limitation is that it is hard to create configurations that depend on the current state of a cluster. Existing GitOps operators expect all of the parameters to be passed from the source repositories without the ability to discover values based on the state of existing objects within the cluster (this is not fully accurate in the case of Flux and [Helm](https://helm.sh/), because Flux supports using the Helm [lookup](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function) function). One such example that highlights this issue is that most Kubernetes clusters (including OpenShift) have the concept of a base domain (the domain that all FQDNs of endpoints exposed by the cluster share). This naturally becomes a parameter that would be needed across a variety of cluster and user level configurations, including applications deployed to the cluster."

[0] https://cloud.redhat.com/blog/enhancing-gitops-with-the-patch-operator

**Comment by natasha41575** [comment]
> When doing kustomize apply you are running with kubectl scope which means you should have cluster scope.

Unfortunately, that is not how kustomize works. Communicating with the cluster is specifically out of scope for kustomize, it is a client-side tool only. Running `kubectl apply -k` is a convenient way of doing `kustomize build | kubectl apply`, so at no point does kustomize have access to cluster.

Please reopen with a more specific example if I've misunderstood.
