### ISSUE TITLE
https://kubernetes-sigs.github.io/kustomize is down

### ISSUE THREAD

**Issue by AndersBennedsgaard** [kubernetes-sigs/kustomize#4500]
**Describe the bug**
Kustomize's GitHub pages is down with the message:

> There isn't a GitHub Pages site here.

This also includes the https://kubernetes-sigs.github.io/kustomize/contributing/bugs/ guide :sweat_smile: 

**Expected output**

200

**Actual output**

404

**Kustomize version**

main branch

**Platform**

Firefox on Linux

**Comment by KnVerey** [comment]
The Github pages site's content moved to https://kubectl.docs.kubernetes.io years ago now, so we just deactivated it intentionally. The page you're looking for specifically is at https://kubectl.docs.kubernetes.io/contributing/kustomize/bugs/. Were you trying to access it through a direct link, or is there a link to the old site somewhere that we missed in the cleanup?

**Comment by AndersBennedsgaard** [comment]
Ah, I didn't know that. Well, the `README.md` contains several references to it (such as the installation guide as I was looking for), and also the `install kustomize` button at https://kustomize.io/

**Comment by kallisti5** [comment]
I just ran into this too lol.   There are no direct links to https://github.com/kubernetes-sigs/kustomize from kustomize.io either

**Comment by KnVerey** [comment]
Thanks for pointing those out! I've fixed the readme and opened https://github.com/replicatedcom/kustomize-www/pull/20 to fix kustomize.io.

> There are no direct links to https://github.com/kubernetes-sigs/kustomize from kustomize.io either

There's one at the bottom, in the "Community" section. Please note that this page was recently donated to us, and we just kicked off a project to consolidate the five places Kustomize documentation was spread across: #4338. Deactivating the old github pages site was a first step in that process.

**Comment by AndersBennedsgaard** [comment]
@KnVerey having just cloned the repository to my local machine and run `grep "kubernetes-sigs.github.io/kustomize" -rs`, it seems there still are 1570 references to the github.io page. 
Out of these, 1 is found in [kustomize/commands/edit/add/addpatch.go](https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/commands/edit/add/addpatch.go), [hack/krmFunctionBenchmark/readme.md](https://github.com/kubernetes-sigs/kustomize/blob/master/hack/krmFunctionBenchmark/readme.md), [.github/ISSUE_TEMPLATE/bug_report.md](https://github.com/kubernetes-sigs/kustomize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), 2 are found in [site/config.toml](https://github.com/kubernetes-sigs/kustomize/blob/master/site/config.toml), and 1565 references are found somewhere in the [docs](https://github.com/kubernetes-sigs/kustomize/blob/master/docs)

**Comment by KnVerey** [comment]
The vast majority there are the site itself, since we haven't merged the code deletion PR yet (#4491). #4503 removes the other three you found, thanks!
