### ISSUE TITLE
Transformer examples file is missing docs on namespace transformer

### ISSUE THREAD

**Issue by larsks** [kubernetes-sigs/kustomize#4506]
**Describe the bug**

The documentation at https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs is missing any information about configuring the namespace transformer.

**Files that can reproduce the issue**

- https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md

**Comment by KnVerey** [comment]
Our main transformer documentation is currently at https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_namespacetransformer_

We're working on a rewrite of our docs in #4338 and should probably merge the examples file you linked with that documentation in the new version.

/kind documentation
/triage accepted
