### ISSUE TITLE
[doc] Document immutable generatorOption

### ISSUE THREAD

**Issue by gaeljw** [kubernetes-sigs/kustomize#4510]
Supporting immutable configmap has been done in https://github.com/kubernetes-sigs/kustomize/pull/3795 but it's not documented anywhere.

It would be nice to have it in the official documentation, either on the configMapGenerator section and/or the generatorOptions section.

**Comment by KnVerey** [comment]
/triage accepted

Our docs are sourced from https://github.com/kubernetes-sigs/cli-experimental if you're able to contribute the fix for this.

**Comment by gaeljw** [comment]
Thanks for the information. Here you go: https://github.com/kubernetes-sigs/cli-experimental/pull/254 :)
