### ISSUE TITLE
Is there a way to output into multiple files?

### ISSUE THREAD

**Issue by TimShilov** [kubernetes-sigs/kustomize#4528]
Hello,
I'm using Kustomize to prepare K8s resourses. The problem is I have a lot of resources and the output file is getting too big which makes it hard to read and formatting tools like Prettier that we use in pre-commit hook are getting stuck on it.

Is there a way to force output into multiple smaller files instead of just one file? Since the resulting file has lots of small separate documents I think that should be possible.

**Comment by natasha41575** [comment]
Unfortunately, no, kustomize does not have any mechanism to output the resources into separate files. There is an `--output` flag that lets you dump the output into a file, but it puts all the resources in the same file.

@KnVerey what's your opinion on a flag that would cause the output to be written to different files, 1 resource per file?

**Comment by KnVerey** [comment]
> @KnVerey what's your opinion on a flag that would cause the output to be written to different files, 1 resource per file?

It reminds me of `kustomize cfg` -- taking a collection of resources and analyzing/sorting/distributing it in some way is not a problem unique to resources generated by Kustomize. I'm not in favour of adding a dedicated feature for it. Maybe we can consider a new `cfg` subcommand, but really, I'd prefer to see `cfg` become an independently maintained tool rather than grow.

**Comment by lsloan** [comment]
A workaround…
```sh
kustomize build directory_name | csplit - /^---$/ '{*}'

# Requires `yq` to query values from YAML files
for i in xx*; do sed '/^---$/,1d' $i > $(yq '.kind + "-" + .metadata.name + ".yaml"' $i); done

rm xx*
```
Note: If `csplit` gives an error about the `{*}` repeat-count pattern, it means that version of `csplit` only supports splitting a specific number of times.  This can be remedied by installing GNU coreutils to get its version of `csplit` (e.g. using Homebrew to install `coreutils` will provide `gcsplit`) or by manually changing `*` to a specific number, found by trial and error.

**Comment by staylorx** [comment]
Adding this for posterity, but this works for what I need for breaking up the files. It assumes the name "manifests" exists as a folder, in my case ready for ArgoCD:

```
mkdir manifests
kustomize build k8s/base -o manifests`
```

If the folder _doesn't_ exist one will get a large file named "manifests" with all the yaml in it.
