### ISSUE TITLE
[Question] Nested envFrom injection

### ISSUE THREAD

**Issue by rafalix1337** [kubernetes-sigs/kustomize#4539]
Hello,

I'm trying to add envs injection based on `envFrom`

A simplified structure looks something like that:

```
├── base
│   ├	─ backend
	│   ├── backend.properties
	│   ├── app1
	│   │   ├── app1_backend.properties
		├	── deployment.yaml
	│   │   ├── ingress.yaml
	│   │   ├── kustomization.yaml
	├── common.properties
	├── frontend
	│   ├── app1
    	│   ├── app1_frontend.properties
	│   │   ├── deployment.yaml
	│   │   ├── ingress.yaml
	│   │   ├── kustomization.yaml
	│   │   └── service.yaml
	│   ├── frontend.properties
	│   └── kustomization.yaml
	└── kustomization.yaml
```

I would like to generate properties on the main level(common), backend/frontend level, and particular app level.
So I was trying to add the following patch on main level and it works:
```
  - op: add
	path: /spec/template/spec/containers/0/envFrom
	value:
	- configMapRef:
		name: common-properties
```

and following code to nested directories(backend/frontend/particular app)
```
- op: add
  path: "/spec/template/spec/containers/0/envFrom/-"
  value:
    configMapRef:
      name: backend-properties
```

But it doesn't work with the following error:
```
add operation does not apply: doc is missing path: "/spec/template/spec/containers/0/envFrom/-": missing value
```

I have seen some examples on GitHub where that syntax was used: https://github.com/search?l=YAML&p=1&q=%2Fspec%2Ftemplate%2Fspec%2Fcontainers%2F0%2FenvFrom%2F-&type=Code (you have to be logged in to see results) And I'm not sure this stopped work on specific Kustomize version(I'm using the newest version - 4.5.3) or it never worked

I have already written some Kustomize patches and syntax with `/-` to resources usually worked fine to resources that already exist on the manifest. 
It's possible to inject that `envFrom` on different levels?

**Comment by rafalix1337** [comment]
I found a workaround to my problem, it's less comfortable than the way I was trying to but it's working :) I added my workaround solution and unsuccessful try in git repository. You can see: https://github.com/rafalix1337/kustomize-issue-71622398

Firstly, I was trying to add generating config maps and injecting envs on different levels like backend/frontend/specific app but this was causing an error. You can see code in the directory not_working_example

In the workaround, I left generating config maps on specific levels but the injecting envs I had to move to one place, in my case kustomization.yaml on the main level. You can see code in the directory working_example

**Comment by KnVerey** [comment]
Thanks for providing the full samples--it really helps! The problem with your not-working sample is that the `/-` means to append and will not work if the key in question doesn't already exist. One possible solution is to add `envFrom: []` to each of your initial deployment definitions to ensure the key will always exist when you try to append. Alternatively, you can selectively change the jsonpatches to not have the `-` suffix when they are the first patch in the series.

If I've misunderstood, please reopen.

/kind support
/triage resolved
/close
