### ISSUE TITLE
Kustomize stuck on outdated goreleaser version

### ISSUE THREAD

**Issue by KnVerey** [kubernetes-sigs/kustomize#4542]
Kustomize is currently relying on goreleaser's `--skip-validate` flag to ignore the fact that our tags are not pure semver (because they have module prefixes). That flag was [deprecated long ago, and removed in v0.180.0 in Sept 2021](https://goreleaser.com/deprecations/?h=depre#skipping-semver-validations). Multi-module repos like our are supposed to move to the ["monorepo" feature]( https://goreleaser.com/customization/monorepo/), which requires a [paid Pro license](https://goreleaser.com/pro/).

#4571 manually installs v0.179.0 into a container with Go 1.18 so that we aren't stuck building with the old Go version the  corresponding official goreleaser container bundles. But this is still a risk for us in the medium to long term.

Potential options:
- Pay for a Pro license?
- Stop using goreleaser? (what does the rest of the project do?)

FYI @natasha41575 this seems pretty important and may be high effort

**Comment by jzelinskie** [comment]
The CNCF provides budget for things like this. I think you should just purchase goreleaser and support @caarlos0

**Comment by caarlos0** [comment]
I'm also happy to give a discount as it is for OSS :)

**Comment by pre** [comment]
If there’s budget, I don’t understand the urge to ”not pay” for useful tools. 

The cumulative cost for finding an alternative is of course zero if the voluntary work doesn’t cost anything (except if someone performs this as part of their salary job ..)

I doubt the license cost is that much for an open source project, especially if there’s support from the author.

**Comment by koba1t** [comment]
I think this issue was resolved with merge for https://github.com/kubernetes-sigs/kustomize/pull/5239. 
/close
