### ISSUE TITLE
[Question] Order of different kind of patches?

### ISSUE THREAD

**Issue by cconnert** [kubernetes-sigs/kustomize#4557]
Question #727 explains well how patches are applied in regards to overlays. But it falls short of explaining:

- How patches & components interact with one and another. E.g I got several partial patches within components which are applied at some level. As far as I figured those are applied in declaration order. Is that correct (basically same as for `resource)?`
- Second when applying different kind of patches (e.g `patches` and `patchesStrategicMerge`) to the same resource how are they order? For now I figured that e.g. `patchesStrategicMerge` seems to be applied before `patches`. The declaration order does not matter. So in which order are `patchesStrategicMerge`,  `patchesJson6902` and `patches` applied?

A in depth explanation with examples would be a great addition as documentation.

**Comment by natasha41575** [comment]
I believe the order of transformers is determined here: https://github.com/kubernetes-sigs/kustomize/blob/e5041bae6f3b536b764f96c1cf72d332a9c68c43/api/internal/plugins/builtinhelpers/builtins.go#L14

which suggests that the order is `patchesJson6902`, `patchesStrategicMerge` and then `patches`.

If you would like to control the order of transformers, you can invoke them via the `transformers` field. There's an example of that here: https://github.com/kubernetes-sigs/kustomize/issues/4476

**Comment by natasha41575** [comment]
Btw, feel free to contribute documentation. Kustomize docs live here: https://kubectl.docs.kubernetes.io/references/kustomize/, it could probably use an extra "Transformers" section. The repo that hosts this site is here: https://github.com/kubernetes-sigs/cli-experimental

/kind documentation
/kind question
/triage accepted

**Comment by cconnert** [comment]
Thanks for the detailed explanation. I'll try to find some time to contribute and enhance the documenation
