### ISSUE TITLE
Support OpenAPI Remote Schema

### ISSUE THREAD

**Issue by mvgmb** [kubernetes-sigs/kustomize#4566]
**Is your feature request related to a problem? Please describe.**

My organization is going to use Custom Resources to deploy applications by defining CRDs that will be used by all teams. Therefore, a custom OpenAPI schema is required to define merge keys and patch strategy.

Currently, Kustomize's OpenAPI `path` attribute only accepts local schemas. This means we need to distribute a copy of the OpenAPI schema to all teams, which is impractical.

**Describe the solution you'd like**

To centralize the OpenAPI schema in a remote server (e.g. AWS S3). This would facilitate any future CRD resource updates since all Kustomize builds would always use the most recent schema.

**Proposed Solution**

From my local testing, all it would need to change is how the OpenAPI schema is loaded by letting the Loader handle the given path.

https://github.com/kubernetes-sigs/kustomize/blob/49c0ed13263ed75e2a7c5d444479fda85f29d993/api/krusty/kustomizer.go#L79

Proposed changes:
```go
bytes, err = ldr.Load(openApiPath)
```

In addition to the `path` attribute being able to reference a remote schema, it'd continue to support local schema.

**Comment by natasha41575** [comment]
I am OK with openapi schema coming from a remote file. Feel free to submit a PR for this change. 

/triage accepted
/kind feature

**Comment by Sineaggi** [comment]
We just found out about `openapi.path` today, and we're in the same boat of needing to distribute a copy of our schema.

Would love to see `openapi.path` support remote resources similar to `configurations`.

**Comment by natasha41575** [comment]
This will be available in the next release.
