### ISSUE TITLE
[Question] Is it possible to use already existing in k8s ConfigMap/Secret in replacements?

### ISSUE THREAD

**Issue by makubit** [kubernetes-sigs/kustomize#4573]
I have a use case where I want to replace a cert in my resources, but this cert is already deployed in the k8s environment in a different namespace. Is it possible to refer in replacements to existing resources (or some other way)? 
I couldn't find anything similar in the documentation.

**Comment by natasha41575** [comment]
The short answer is no, this isn't possible. 

> but this cert is already deployed in the k8s environment

Kustomize is a client-side _only_ tool, so communicating with the cluster is out of scope for kustomize. `replacements` (or any other transformer for that matter) can only refer to resources that are rendered during the execution of `kustomize build`. 

Please reopen if you would like to discuss more.
