### ISSUE TITLE
Not work with remote repo

### ISSUE THREAD

**Issue by Spartaques** [kubernetes-sigs/kustomize#4575]
Kustomize version:
{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}
as i expected version is the latest because it was installed from here:
https://kubectl.docs.kubernetes.io/installation/kustomize/source/#install-the-kustomize-cli-from-local-source-with-cloning-the-repo
with version v4.5.2.

I have the next file structure:
![image](https://user-images.githubusercontent.com/29341175/162588603-cd26d2be-ff96-4edc-8ca3-6b1383f1c835.png)

It works well using kustomize build from local files like this:
![image](https://user-images.githubusercontent.com/29341175/162588627-0b6fed6b-b9e1-4878-bc60-b0f5c7fc4bcd.png)

But when i use remote git url it crashes with error:

```
Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Unknown desc = `kustomize build /tmp/git@bitbucket.org_retainly-bitb_k8s/k8s/overlays/dev`
 failed exit status 1: Error: accumulating resources: accumulation err='accumulating resources from './../../base': '/tmp/git@bitbucket.org_retainly-bitb_k8s/k8s/base' must resolve to a file':
  recursed accumulation of path '/tmp/git@bitbucket.org_retainly-bitb_k8s/k8s/base': accumulating resources:
   accumulation err='accumulating resources from 'core': '/tmp/git@bitbucket.org_retainly-bitb_k8s/k8s/base/core' must resolve to a file':
   recursed accumulation of path '/tmp/git@bitbucket.org_retainly-bitb_k8s/k8s/base/core': accumulating resources: accumulation err='accumulating resources from
   'services/core-api-service.yaml': evalsymlink failure on '/tmp/git@bitbucket.org_retainly-bitb_k8s/k8s/base/core/services/core-api-service.yaml'
   : lstat /tmp/git@bitbucket.org_retainly-bitb_k8s/k8s/base/core/services: no such file or directory': evalsymlink failure on
   '/tmp/git@bitbucket.org_retainly-bitb_k8s/k8s/base/core/services/core-api-service.yaml' : lstat /tmp/git@bitbucket.org_retainly-bitb_k8s/k8s/base/core/services: no such file or directory
```

So the question is why it not works with remote files? 
For now i try to use ArgoCD with my kustomize manifest files, but it not work.

**Comment by KnVerey** [comment]
/triage needs-information

Can you please provide the Kustomization you're working with and the directory structure (or even better, the entire sample that is not working for you)?
