### ISSUE TITLE
Expand var replacements to include annotations on StatefulSet

### ISSUE THREAD

**Issue by tis-rpage** [kubernetes-sigs/kustomize#4586]
Expand var replacements to include annotations on StatefulSet resources to match parity with Deployment replacements.

From `https://github.com/kubernetes-sigs/kustomize/blob/master/api/konfig/builtinpluginconsts/varreference.go`:
```yaml
- path: spec/template/metadata/annotations
  kind: Deployment
```
Add:
```yaml
- path: spec/template/metadata/annotations
  kind: StatefulSet
```

**Comment by natasha41575** [comment]
Vars are slated for deprecation (https://github.com/kubernetes-sigs/kustomize/issues/4049), so we will not be adding any additional features for it. We encourage you to migrate to replacements (https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/) if possible.
