### ISSUE TITLE
`kubectl edit -k` command doesn't work at all

### ISSUE THREAD

**Issue by sahilrajput03** [kubernetes-sigs/kustomize#4598]
https://github.com/kubernetes/kubernetes/issues/109598

Is this bug belongs to this repo of or the official kubernetes repo .., can someone suggest me this?

**Comment by KnVerey** [comment]
Assuming you are referring to `kubectl edit` rather than `kustomize edit` (which is not available in kubectl), the issue belongs on the kubectl side. It seems like your question there has already been answered.

/close
