### ISSUE TITLE
Tags and Releases named by the version number only.

### ISSUE THREAD

**Issue by Harmelodic** [kubernetes-sigs/kustomize#4601]
**Is your feature request related to a problem? Please describe.**

Some automation tools, like [Renovate](https://github.com/renovatebot/renovate), are able to update versions based on Releases/Tags of software on GitHub.

With weird names for tags/releases, it makes it much harder to do automated updates.

**Describe the solution you'd like**

Tags and releases named like: `4.5.2`

**Comment by natasha41575** [comment]
> Tags and releases named like: 4.5.2

We aren't having "weird release tags" for no reason. We maintain multiple modules in this repo that are released separately (kyaml, api, cmd/config, and kustomize). 

If there is a precedent elsewhere in the kubernetes ecosystem or generally on Github, then we can consider following that convention. There is at least one other example that I can find with multi module release tags ([link](https://danielflower.github.io/2015/03/08/The-Multi-Module-Maven-Release-Plugin-for-Git.html)), which has tags like `module-v0.0.0`. This is different from our `module/v0.0.0`, but AFAICT, there isn't a standard. 

I would argue that it is the responsibility of the automation tool, not kustomize, to understand and decode release tags in multimodule repos.
