### ISSUE TITLE
Produce darwin/arm64 binaries for v3

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kustomize#4612]
**Is your feature request related to a problem? Please describe.**
We cannot upgrade the stable go/v3 plugin in kubebuilder to use kustomize v4 and we would like to provide on it the support for  darwin/arm64. In this way, we would like to ask for v3 binaries in this architecture. 

**Describe the solution you'd like**

Be able to use the install.sh script to also install darwin/arm64 binaries for v3

**Comment by KnVerey** [comment]
Can you please provide more information on why you cannot upgrade to v4, and whether or not this is permanent? v4 is more than a year old now, and we do not currently have a long-term support policy for v3.

**Comment by camilamacedo86** [comment]
Hi @KnVerey, 

From v3 to v4, we have a MAJOR bump. Then that means breaking changes. ( besides, I know that you tried to make it us much backwards compatible as possible ) 

For Kubebuilder we have stable plugins which use v3; we will provide a new alpha version that uses v4 to allow people to begin to upgrade and experiment with that as we begin to use v4 and its new features. 

But we do not wish to remove the support for the stable plugins ( which does scaffolds using kustomize v3 ) now, and we would like to allow users which are running the things in Apple Silicon still be able to use the scaffolds done with v3 and the stable versions. 

So to do that, we would like to have v3 binaries in this architecture. Since producing the binaries in the architecture is not a really huge effort would be lovely if you could accept this one. I am doing the PR for that.

**Comment by KnVerey** [comment]
I think the reason it doesn't already exist is that go-releaser itself didn't support that architecture at the time of the release in question. darwin/arm64 support [first appeared in v0.156.0](https://github.com/goreleaser/goreleaser/commit/6b26fe4106123cbc1c0fe551927f89ae6cda6475), and [the last v3 release used v0.155.0](https://github.com/kubernetes-sigs/kustomize/blob/602ad8aa98e2e17f6c9119e027a09757e63c8bec/releasing/cloudbuild.yaml#L39). We started producing darwin/arm64 with v4.2, where we [upgraded to v0.172.1](https://github.com/kubernetes-sigs/kustomize/commit/4fd7269643baf1f65666fa45694625147caeb05b).

**Comment by camilamacedo86** [comment]
HI @KnVerey, 

Could we not update the goreleaser?

**Comment by KnVerey** [comment]
Yes, in theory we could make some new commits to the release branch and create a new tag. But the effort/risk isn't nothing, since we've never actually tried to do this before. For one thing, I recently discovered that the cloud build wasn't using the specified tag, so we'd need to cherry-pick a version of [this change](https://github.com/kubernetes-sigs/kustomize/pull/4537/commits/5833f4ca800d22b1d5fca869c9d26289f9f36e18). There were major internal/dependency changes between v3 and v4, and dependencies could be another source of surprises since we do not vendor. Other similar dragons could be lurking, which makes me quite unenthusiastic about attempting this.

> From v3 to v4, we have a MAJOR bump. Then that means breaking changes. ( besides, I know that you tried to make it us much backwards compatible as possible )

Yes, there were a few. I wasn't yet heavily involved in the project, but I know we had to drop support for some remote URL formats and changed underscored flags to use dashes. Is your project definitely affected by the specific changes that were made?

**Comment by camilamacedo86** [comment]
HI @KnVerey, 

We have a proposed solution for moving forward with kustomize v4. See: https://github.com/kubernetes-sigs/kubebuilder/pull/2583 (there you can check why we cannot just begin to provide kustomize v4 vi the current stable plugin used to scaffold projects) 

So, to allow Apple Sillicon users uses the default current and stable implementation (which is the goal that we are trying to achieve with this request) we would like to also have the kustomize v3 bin for this architecture. In this way, we are moving forward to use and provide the solution with kustomize v4 but we are also allowing users still using the stable and current implementation in this case. Note that we will need to support the current implementation for a long period. Then, having the kustomize v3 bin in this format would be very helpful for us.

**Comment by natasha41575** [comment]
@camilamacedo86 @gquillar Is it an option for you to build these binaries yourself from the release branches' source code? Given our limited resources, we don't have a precedent for supporting old versions and generally only cherry pick commits for security-related issues.

**Comment by camilamacedo86** [comment]
Hi @natasha41575, 

I have two concerns with that: 

a) Currently, the releases have not been done by the tags ( so it is tough to know what version we are releasing by ourselves ). Would it be possible to fix this one at least? 
b) What would be the steps to build the bin? Could you provide the steps after git checkout the tag? What are the commands required?

**Comment by camilamacedo86** [comment]
Hi @natasha41575, @KnVerey,

Could you please give a hand on this one?
