### ISSUE TITLE
Resource urls don't support ports

### ISSUE THREAD

**Issue by annasong20** [kubernetes-sigs/kustomize#4622]
**Describe the bug**
Our [remote targets specification](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md) supports git clone urls, which can include a port. However, when specifying a port in urls under the `resources` field, I get an error.

**Files that can reproduce the issue**
The [TestRemoteResourcePort](https://github.com/kubernetes-sigs/kustomize/blob/master/api/krusty/remoteload_test.go#L167) test case in remoteload_test.go currently throws errors, though it shouldn't. 

Note that the ssh sub-test will **locally** run without error once this port issue is resolved. However, the ssh sub-test will still fail on the server, unless [the server acquires ssh keys](https://github.com/kubernetes-sigs/kustomize/issues/4620#issuecomment-1118956749). We skip this sub-test for the same reason. 

**Expected output**
We currently compare the output of TestRemoteResourcePort to the errors kustomize throws from its inability to process the ports. The actual expected output of a successful build is the value of the variable [multiBaseDevExampleBuild](https://github.com/kubernetes-sigs/kustomize/blob/master/api/krusty/remoteload_test.go#L25).

**Actual output**
The current output is an error, which is specified in TestRemoteResourcePort.

**Kustomize version**
We observe this behavior on the master branch, at commit [17b42a9](https://github.com/kubernetes-sigs/kustomize/commit/17b42a99f5c5981c9d773f80a6833734e7ce36ac).

**Comment by sbathgate** [comment]
Just for reference, this is a blocker for my team as we enforce ssh on a specific port within our orgs self managed GitLab.

**Comment by annasong20** [comment]
FYI, I don't know why, but the https port sub-test asks the user to enter their username and password. The result is the same regardless of whether the user enters their credentials. However, if the user does, the sub-test takes about 1/2 the time to run.
