### ISSUE TITLE
How to set label on secret created by ServiceAccount?

### ISSUE THREAD

**Issue by dominikjeske** [kubernetes-sigs/kustomize#4651]
Is there any way to set label on secret created by ServiceAccount? For now it is the only secret I'm not able to configure with label.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forum-sa
```

![image](https://user-images.githubusercontent.com/3872348/170069551-e78d2f10-4ffd-496d-93da-dec20f959e05.png)

**Comment by KnVerey** [comment]
It is possible to imperatively label resources using kubectl: https://kubectl.docs.kubernetes.io/references/kubectl/label/

That said, this issue is not related to Kustomize, since the resource in question is not generated by it and Kustomize is client-side-only.

/close
