### ISSUE TITLE
kustomize always re-configures generated secrets even though they have not changed

### ISSUE THREAD

**Issue by hholst80** [kubernetes-sigs/kustomize#4653]
Why does apply state it will "configure" the secret (not leave it untouched), even though it has not changed and the hash suffix is the same?

This creates a lot of confusion in our CI/CD pipeline.

```
❯ cat kustomization.yaml 
secretGenerator:
- name: regcred
  files:
    - .dockerconfigjson=config.json
  type: kubernetes.io/dockerconfigjson

❯ kubectl apply -k . --dry-run=server
secret/regcred-48fm68k8b2 configured (server dry run)
```

```
❯ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1

❯ kubectl cluster-info
Kubernetes control plane is running at https://[snip]:6443
CoreDNS is running at https://[snip]:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://[snip]:6443/api/v1/namespaces/kube-system/services/https:metrics-server:https/proxy
[...]
```

**Comment by KnVerey** [comment]
That message is generated by kubectl not kustomize. I think this may be the same issue you're reporting: https://github.com/kubernetes/kubernetes/issues/66450

/close

**Comment by hholst80** [comment]
The message is generated by kubernetes itself because the asset generated is as far as kubernetes is concerned - changed - not the same - as the one previously generated. I strongly suspect the base64 encoding is at fault here.

**Comment by KnVerey** [comment]
If you read the linked issue closely, you will see that what you're describing affects many resource types, and is not associated with resources generated by Kustomize in particular. Kustomize's test suite has many character-sensitive tests that would fail if the output changed from one build to the next. If you have a sample that can reproduce different output being generated by Kustomize, that is definitely something we want to fix, so feel free to reopen, or better, open a PR with the test case.

**Comment by hholst80** [comment]
```
❯ kubectl apply -n qwer -k . --dry-run=server
configmap/config-files-2gf4hhk9f2 created (server dry run)
secret/regcred-4mbmdtc7f5 created (server dry run)

❯ kubectl apply -n qwer -k .                 
configmap/config-files-2gf4hhk9f2 created
secret/regcred-4mbmdtc7f5 created

❯ kubectl apply -n qwer -k . 
configmap/config-files-2gf4hhk9f2 unchanged
secret/regcred-4mbmdtc7f5 configured

❯ kubectl apply -n qwer -k . 
configmap/config-files-2gf4hhk9f2 unchanged
secret/regcred-4mbmdtc7f5 configured

❯ cat kustomization.yaml 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: config-files
    files:
      - prometheus.yml
secretGenerator:
  - name: regcred
    files:
      - .dockerconfigjson=config.json
    type: kubernetes.io/dockerconfigjson
❯ 
```

```
❯ kustomize build|kubectl apply -n qwer -f - --dry-run=server
configmap/config-files-2gf4hhk9f2 unchanged (server dry run)
secret/regcred-4mbmdtc7f5 configured (server dry run)

❯ kustomize build|kubectl apply -n qwer -f -                 
configmap/config-files-2gf4hhk9f2 unchanged
secret/regcred-4mbmdtc7f5 configured

❯ kustomize build|kubectl apply -n qwer -f -
configmap/config-files-2gf4hhk9f2 unchanged
secret/regcred-4mbmdtc7f5 configured

❯ kustomize build|kubectl apply -n qwer -f -
configmap/config-files-2gf4hhk9f2 unchanged
secret/regcred-4mbmdtc7f5 configured
```

**Comment by KnVerey** [comment]
Can you please provide one complete sample (Kustomization and all files required to build it) of the Kustomize side only, showing that Kustomize itself is producing different output between builds? Given the known issue I linked, please do not involve kubectl in the reproduction case.

**Comment by natasha41575** [comment]
What @KnVerey is trying to say is that `kubectl apply -k` is a shortcut for doing `kustomize build | kubectl apply -f`. To verify this issue, we need to know the contents of your `kustomization.yaml` file, and the contents of any files that `kustomization.yaml` references. If running `kustomize build` repeatedly on these files produces different output from one build to the next, then we have a bug. Otherwise, the issue is unrelated to kustomize.

**Comment by hholst80** [comment]
It is here, I am sure you can find it. Stalebot has not even started polluting this issue with noise. ;-)

**Comment by natasha41575** [comment]
@hholst80 Yes, I saw that already and using the kustomization.yaml you've provided and the `config.json` script you've provided, I'm not able to produce different output when running `kustomize build` multiple times on the same output. Again, if you have an example that can demonstrate the issue on the _kustomize_ side, please share, otherwise we can end the discussion here.

**Comment by brandond** [comment]
This is an issue with how kubernetes stores the base64-encoded data; it has nothing to do with kustomize or kubectl. You can see the issue quite plainly just by getting the secret:

```yaml
apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJhdXRoIjogImRYTmxjbnh3WVhOeiIKICAgIH0KICB9Cn0K
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{".dockerconfigjson":"ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7Ci\nAgICAgICJhdXRoIjogImRYTmxjbnh3WVhOeiIKICAgIH0KICB9Cn0K\n"},"kind":"Secret","metadata":{"annotations":{},"name":"regcred-fmf5kd2f52","namespace":"default"},"type":"kubernetes.io/dockerconfigjson"}
  creationTimestamp: "2022-08-02T23:08:44Z"
  name: regcred-fmf5kd2f52
  namespace: default
  resourceVersion: "827"
  uid: 08b90f69-909c-4e4a-92be-4ae2a20745cb
```

Note that the `last-applied-annotation` has the base64-encoded value with two newlines in it, while the actual secret is normalized and does not contain any newlines. This is because internally the apiserver stores it as a `[]byte`; the base64-encoding is handled by the codec when it is serialized back to json or yaml. As long as these two representations differ, `kustomize` and `kubectl apply` will report that the resource is being changed.

A naive workaround looks something like this:
```bash
kustomize build | yq -j e | sed 's|[\\]n||g' | kubectl apply -f -
```

**Comment by hholst80** [comment]
I know all this. The question is why nobody cares to fix it?

**Comment by natasha41575** [comment]
This is not an issue with kustomize, discussion belongs in the kubernetes repo.

**Comment by brandond** [comment]
> The question is why nobody cares to fix it?

I don't know, why don't **you** care to fix it? It's open source software. Clearly this is more of a problem for you than most people, you should open a PR!
