### ISSUE TITLE
[Question] Missing tagged container image for v4.5.5?

### ISSUE THREAD

**Issue by larsks** [kubernetes-sigs/kustomize#4665]
Kustomize 4.5.5 was released several days ago, but the corresponding tag doesn't exist on the image repository:

```
$ podman pull k8s.gcr.io/kustomize/kustomize:v4.5.5
Trying to pull k8s.gcr.io/kustomize/kustomize:v4.5.5...
Error: initializing source docker://k8s.gcr.io/kustomize/kustomize:v4.5.5: reading manifest v4.5.5 in k8s.gcr.io/kustomize/kustomize: manifest unknown: Failed to fetch "v4.5.5" from request "/v2/kustomize/kustomize/manifests/v4.5.5".
```

I assumed these tags were generated automatically as part of the release workflow; is something broken?

**Comment by KnVerey** [comment]
It should now be available since https://github.com/kubernetes/k8s.io/pull/3788 has merged
