### ISSUE TITLE
`kustomize localize` repetitive base

### ISSUE THREAD

**Issue by annasong20** [kubernetes-sigs/kustomize#4672]
**Describe the bug**
According to the way [`kustomize localize`](https://github.com/kubernetes-sigs/kustomize/blob/master/proposals/22-04-localize-command.md) is currently designed, multiple overlays that reference the same remote base will produce multiple copies of said base, which is against kustomize design principles.

**Files that can reproduce the issue**
Say we have the setup below:
```
#/overlay1/kustomization.yaml
resources:
- https://github.com/kubernetes-sigs/kustomize//examples/multibases/base?ref=v3.3.1
namePrefix:
  woo
```
```
#/overlay2/kustomization.yaml
resources:
- https://github.com/kubernetes-sigs/kustomize//examples/multibases/base?ref=v3.3.1
namePrefix:
  hoo
```

**Expected output**
After we run `kustomize localize`, we would like for the remote base to be downloaded once and used by both overlays. This would match the current layout `kustomize build` expects for a completely local setup.

**Actual output**
Instead, we get the following file structure:
```
├── overlay1
 │         └── kustomization.yaml
 │         └── localized-files
 │                     ...     # many intermediate directories
 │                   └── base
└── overlay2
           └── kustomization.yaml
           └── localized-files
                       ...     # many intermediate directories
                     └── base
```
where there is a copy of the base for each overlay.

**Kustomize version**
`kustomize localize` has yet to be implemented in source code, but regardless, the master branch is on [this commit](https://github.com/kubernetes-sigs/kustomize/commit/1c5393216672c87d5bd553ba255d8dd3044bbf0c).

**Comment by annasong20** [comment]
We can't think of a better alternative at the moment. 

Because kustomize believes in encapsulated kustomizations, it goes against kustomize philosophy to download the remotes into the root that `localize` is being called from. Moreover, because kustomize doesn't support absolute directory paths, we can't download the remotes to some global folder.

We'll revisit this issue if there's a need for it.

**Comment by natasha41575** [comment]
I think we can close this issue. There doesn't seem to be a way to address this issue that doesn't violate kustomize's constraints. We can reopen if there is demand.

/close
