### ISSUE TITLE
[Question] helmChartInflationGenerator doesn't generate new chart when changing chartVersion 

### ISSUE THREAD

**Issue by thang-tran11** [kubernetes-sigs/kustomize#4676]
I'm using helmChartInflationGenerator to generate the manifest via helm-chart.
I have changed chartVersion but my workload doesn't change anything?
I must remove the folder chart!!!

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmChartInflationGenerator:
  - chartName: spinnaker
    chartRepoUrl: https://helmcharts.opsmx.com/
    chartVersion: 2.2.6 ->change 2.2.7
    releaseName: test
    releaseNamespace: spinnaker
    values: values_helm.yaml

Are there ways to change chartVersion but we needn't remove the chart folder?

**Comment by ChristianCiach** [comment]
Duplicate of https://github.com/kubernetes-sigs/kustomize/issues/3848

Just another example for why autoclosing stale issues suck.
