### ISSUE TITLE
[Question]HTTP Wrapper API

### ISSUE THREAD

**Issue by wibed** [kubernetes-sigs/kustomize#4681]
Is there a http wrapper api in planning, or around?

**Comment by KnVerey** [comment]
If you're asking whether the Kubernetes community provides a hosted version of Kustomize as a service, the answer is no. We provide [binaries](https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/) and [docker images](https://kubectl.docs.kubernetes.io/installation/kustomize/docker/). If that's not what you meant, feel free to reopen with more information.

/kind support
/triage resolved
/close
