### ISSUE TITLE
[Question] Possible problematic commands

### ISSUE THREAD

**Issue by Chever-John** [kubernetes-sigs/kustomize#4688]
Command `mv -t` in this [`.md` file](https://github.com/kubernetes-sigs/kustomize/blob/master/site/content/en/docs/Getting%20started/first_kustomization.md#:~:text=mv%20%2Dt%20base%20deployment.yaml%20kustomization.yaml%20service.yaml) does not work.

I think it is the wrong command after searching the manuals with the command `man mv`.

Maybe we should change it from `mv -t base deployment.yaml kustomization.yaml service.yaml` to `mv deployment.yaml kustomization.yaml service.yaml base`.

And then you will see the expected result.

**Comment by Chever-John** [comment]
It is my pleasure to fix this typo error, if possible.

**Comment by KnVerey** [comment]
Fixed by https://github.com/kubernetes-sigs/kustomize/pull/4689
/close
/triage accepted
/kind documentation
