### ISSUE TITLE
Allow disabling of suffix hashes on merged ConfigMaps generated from ConfigMapGenerators

### ISSUE THREAD

**Issue by elisshafer** [kubernetes-sigs/kustomize#4693]
**Is your feature request related to a problem? Please describe.**

Say there is some shared out of scope ConfigMapGenerator that is composed into a given cluster's configuration multiple times through multiple apps' ConfigMapGenerators merging into the shared ConfigMapGenerator in various commands to `kustomize build` and we'd like some ConfigMaps to have a suffix hash at the end of the name, and others to not have a suffix hash appended.

**Describe the solution you'd like**

I'd like to be able to specify

```yaml
- name: example 
  behavior: merge
  options:
    disableNameSuffixHash: true
```

and for the resulting ConfigMap to not have a suffix hash appended to the specified name.

**Describe alternatives you've considered**

A desired solution may be to use a suffix hash in some of the ConfigMaps that are generated from the shared ConfigMapGenerator but not use a suffix hash in other ConfigMaps.

**Additional context**

**Comment by KnVerey** [comment]
This sounds reasonable to me. It looks like `disableNameSuffixHash` is effectively ignored in merge scenarios, because if it is true, that means we _don't_ add an internal suffixing annotation to the resource, and the annotation from the base will be merged in. Wdyt @natasha41575 ?

/triage under-consideration

**Comment by natasha41575** [comment]
>  It looks like disableNameSuffixHash is effectively ignored in merge scenarios, because if it is true, that means we don't add an internal suffixing annotation to the resource, and the annotation from the base will be merged in.

That sounds like a bug to me, I'm on board with accepting this issue.

**Comment by elisshafer** [comment]
I can take a look at making a PR for this if this works for others?

**Comment by elisshafer** [comment]
/remove-lifecycle stale

Got caught up in some other things lately since making this issue, I'll have a PR out soon
