### ISSUE TITLE
install script currently parse "aarch64" to "amd64"

### ISSUE THREAD

**Issue by Yufeireal** [kubernetes-sigs/kustomize#4696]
When I was building Docker image based on Ubuntu(arm64):20.04 image. This part of code will assgin $arch to "amd64".. This script will pretend my machine arch as amd64 and then execute some files that can only be executed in amd64 architecture, of course, throw some errors.. Though the script commented only support arch: amd64, arm64... But I think arm64 and aarch64 are pretty the same thing? Can we add something when check the command output is **aarch64** then assign the **arch=arm64**?
See the code:
`# Supported values of 'arch': amd64, arm64, ppc64le, s390x
case $(uname -m) in
x86_64)
    arch=amd64
    ;;
arm64)
    arch=arm64
    ;;
ppc64le)
    arch=ppc64le
    ;;
s390x)
    arch=s390x
    ;;
*)
    arch=amd64
    ;;
esac
` 
from https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh
My personal opinion:
This is actually because when running the command `uname -m` on Ubuntu, the output is "aarch64"; when running on mac M1, the output is "arm64".. Can we add one more if condition in this script to support Ubuntu aarch64?

**Comment by harry1064** [comment]
Hi @Yufeireal 
Can you provide more detail like which command is giving you error?

**Comment by KnVerey** [comment]
/triage accepted

Would be solved by https://github.com/kubernetes-sigs/kustomize/pull/4619

**Comment by KnVerey** [comment]
Closed by https://github.com/kubernetes-sigs/kustomize/pull/4619
