### ISSUE TITLE
[Question] Ingress/certificates replacements in overlays without vars

### ISSUE THREAD

**Issue by ohardy** [kubernetes-sigs/kustomize#4721]
Hi,

Just checked #4099, closed but without any solution for me.

I have "hosts” to change in ingress/certificates depending on the environment so I tried:
- Common replacements in base and configMapGenerator in each overlay, doesn't work (Cf #4099)
- Common replacements in overlay, doesn't work either because security (is not in or below blah blah)

So nothing works. Two solutions work but gives something far too complicated and difficult to maintain:
- Duplicate replacements in each overlay
- Use patches in each overlay
- Duplicate ingress/certificates in each overlay

Keyword “vars” work really nice for this problem, but it's deprecated, so now, what is the solution to that ?

**Comment by annasong20** [comment]
Hi @ohardy, I'm not sure what your exact setup is, but given that you said "duplicate replacements in each overlay" works, I assume having the same `replacements` in each kustomization works and you just want to be DRY.

If this is the case, I'd recommend you use the kustomize field [`components`](https://kubectl.docs.kubernetes.io/guides/config_management/components/), which can contain transformers without `resources` and run on existing resources in the kustomization where the `components` are referenced. You'd only need to create 1 `Component` containing your `replacements` and reference that `Component` in each kustomization layer. An example of this would look like the following:

each layer's `kustomization.yaml`
```yaml
components:
- ../replacement-component
```

`replacement-component/kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
# your repeated replacements here
```

If I've made incorrect assumptions about your setup, feel free to follow up.
