### ISSUE TITLE
commonLabels in base kustomization.yaml is not applied to overlay resources.

### ISSUE THREAD

**Issue by cm-yamasaki-michihiro** [kubernetes-sigs/kustomize#474]
`commonLabels` in base `kustomization.yaml` add labels to all resources which designated in base `kustomization.yaml`, but not to any resource which specified in overlay `kustomization.yaml`.

**Comment by Liujingfang1** [comment]
@cm-yamasaki-michihiro That is the intended behavior of Kustomize. You can all `commonLabels` in the overlay then all resources will have them.
