### ISSUE TITLE
[Question] Is it possible to only apply the resource when it  doesn't exists? 

### ISSUE THREAD

**Issue by f91og** [kubernetes-sigs/kustomize#4749]
I am now migrating a deployment from python script to kustomize, but encounter one problems. In the deploy script, it use `-init true` args to control whether deploy initial resource or not when first release, if it is not first release, then skip init steps, otherwise do initial step.
So my question is whether I can use kustomize to implement this or not, apply the resources when they are not exists, it it exists then skip the deployment for these resources.

**Comment by KnVerey** [comment]
Kustomize is a client-side-only tool, so any communication with live clusters (including to find out if something exists) is out of scope for it. That said, in most cases you can use `kubectl apply` to create what doesn't exist and update what has changed. You may find the documentation on object management helpful: https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/

/kind support
/triage resolved
/close
