### ISSUE TITLE
Generator Annotations 

### ISSUE THREAD

**Issue by sethpollack** [kubernetes-sigs/kustomize#4750]
When should I use:

```
internal.config.kubernetes.io/generatorBehavior: merge
internal.config.kubernetes.io/needsHashSuffix: enabled
```

vs

```
kustomize.config.k8s.io/behavior: merge
kustomize.config.k8s.io/needs-hash: "true"
```

**Comment by KnVerey** [comment]
Annotations with the "internal" prefix are details of the current implementation of Kustomize and should not be used directly. The only exception is a [couple specific annotations](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md#internal-annotations) that are part of the KRM Function specification and can be referenced by function authors (but still should never be added or seen by end users).

Out of curiosity, where did you find references to those annotations?

/kind support

**Comment by sethpollack** [comment]
I'm using this in my KRM plugin and its adding those annotations.

```
	return p.h.ResmapFactory().FromSecretArgs(
		kv.NewLoader(p.h.Loader(), p.h.Validator()), p.SecretArgs)
```
