### ISSUE TITLE
Does kustomize support patching batch/v1 Job?

### ISSUE THREAD

**Issue by MattGarner-N** [kubernetes-sigs/kustomize#4765]
Hello,

Does kustomize support patching:

apiVersion: batch/v1
kind: Job

Every time I try and patch a job it errors that it cannot find a unique target, e.g.:
failed to find unique target for patch Job.v1.batch/cert-manager-startupapicheck.cert-manager

**Comment by KnVerey** [comment]
Yes, it has been supported since v4.3.

/kind support
/triage duplicate 
of https://github.com/kubernetes-sigs/kustomize/issues/4261 and others
