### ISSUE TITLE
Better error message while loading remote file 

### ISSUE THREAD

**Issue by wim-de-groot** [kubernetes-sigs/kustomize#4788]
### Problem
The problem is that if a remote file is used as resource and that file is part of a git repository that the status code is not shown in the error message. This status code could be helpful for debugging the problem.

### Location
The part of code that I am talking about is located over [here](https://github.com/kubernetes-sigs/kustomize/blob/23de1499c27b1d040e90c8094051fe960661196a/api/loader/fileloader.go#L318).

### Solution
I would like to include the status code and HTTP error message into the message saying "URL is a git repository". I can create a fork and pull request myself, but I need to know if this solution is in line with your vision of this project.

### Preview
```go
return nil, errors.Errorf("%w: status code %d (%s), and URL is a git repository", ErrHTTP, resp.StatusCode, http.StatusText(resp.StatusCode))
```

**Comment by wim-de-groot** [comment]
I added this request 8 days ago, but there is still no reaction. Is there any indication on if I add this pull request?

**Comment by KnVerey** [comment]
@mightyguava recently proposed something similar [here](https://github.com/kubernetes-sigs/kustomize/pull/4783/files/1287caf46a0301a28396af2bf0769e8f47c5bac8#diff-0a2a043ac09e972046124503e8c93e4e7141cfc13deff446afb1aa3e328ee8c5). I agree with the improvement, but the code in question has a test coverage problem described in https://github.com/kubernetes-sigs/kustomize/issues/4807 that needs to be addressed before we can make any changes to it.

/triage accepted
blocked by #4807
