### ISSUE TITLE
[Question] Unexplainable error on kustomize build

### ISSUE THREAD

**Issue by fuero** [kubernetes-sigs/kustomize#4804]
We are encountering an error in a rather complex setup. Here's a minimalized example:

```bash
#!/bin/bash
mkdir -p ./cluster/_tenant/foo
cat << __EOF > ./cluster/_tenant/foo/nginx.configmap.patch.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  allow-snippet-annotations: "false"
__EOF
mkdir -p ./cluster/_tenant/foo
cat << __EOF > ./cluster/_tenant/foo/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: nginx.configmap.patch.yaml
__EOF
mkdir -p ./cluster/_tenant
cat << __EOF > ./cluster/_tenant/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - foo/
__EOF
mkdir -p ./cluster/envs/dev
cat << __EOF > ./cluster/envs/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
components:
  - ../../_tenant/
__EOF
mkdir -p ./cluster/base/nginx-other
cat << __EOF > ./cluster/base/nginx-other/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../nginx-inc

namespace: ingress-nginx-internal
nameSuffix: -internal
__EOF
mkdir -p ./cluster/base/nginx
cat << __EOF > ./cluster/base/nginx/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../nginx-inc
__EOF
mkdir -p ./cluster/base
cat << __EOF > ./cluster/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx/
  - nginx-other/
__EOF
mkdir -p ./nginx-inc/repo
cat << __EOF > ./nginx-inc/repo/deploy.yaml
---
apiVersion: v1
data:
  allow-snippet-annotations: "true"
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
__EOF
mkdir -p ./nginx-inc/repo
cat << __EOF > ./nginx-inc/repo/kustomization.yaml
resources:
  - deploy.yaml
__EOF
mkdir -p ./nginx-inc
cat << __EOF > ./nginx-inc/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - repo/
__EOF
```

When calling `kustomize` like this:

```bash
kustomize build . --load-restrictor LoadRestrictionsNone` in cluster/envs/dev
```

It yields:

> Error: accumulating components: accumulateDirectory: "recursed accumulation of path '/tmp/test/cluster/_tenant': accumulating components: accumulateDirectory: \"recursed accumulation of path '/tmp/test/cluster/_tenant/foo': multiple matches for Id ConfigMap.v1.[noGrp]/ingress-nginx-controller.ingress-nginx; failed to find unique target for patch ConfigMap.v1.[noGrp]/ingress-nginx-controller.ingress-nginx\""

We assumed that transformers were fully applied to `nginx` and `nginx-other` before the resources that include them are fully processed, thus making this error impossible. What do we miss? How would we accomplish what we are trying to do (applying `nginx-inc` twice, only with different names)?

**Comment by seh** [comment]
You're applying the _cluster/_tenant/foo_ _Component_ after you've accumulated the _cluster/base/nginx_ and _cluster/base/nginx-other_ _Kustomizations_, but I'm pretty sure that the name reference tracking is applied "all the way up to the top, until the end," so that the _nginx.configmap.patch.yaml_ file's targeting of "ingress-nginx/ingress-nginx-controller" winds up seeing two candidate targets, because _kustomize_ is trying to accommodate you targeting a resource before it got renamed.

See Katrina's comment in https://github.com/kubernetes-sigs/kustomize/issues/4444#issuecomment-1028290804 for a similar case, and Natasha's comment in https://github.com/kubernetes-sigs/kustomize/issues/4050#issuecomment-877456820 for working around the challenge.

**Comment by fuero** [comment]
I tried the example you referenced which looks quite similar to what I posted initially. With `patches:` it works fine as advertised, with transformers it does not - it shows the behaviour I mentioned. So it's not the structure (if I'm not mistaken), but the transformers that don't work as expected. I'd classify that as a bug.

**Comment by natasha41575** [comment]
@seh Thanks for providing the explanation and links to a common issue we receive. 

> With patches: it works fine as advertised, with transformers it does not

Do you mind providing a minimal example showing how you used it with `transformers`? I agree that if the same configuration works with `patches`, but not with `transformers`, there is an issue. 

/triage needs-information
/kind bug
//remove-lifecycle stale

**Comment by seh** [comment]
I think you meant to refer to @fuero there, but I remain curious to follow the discussion nonetheless.

**Comment by fuero** [comment]
Here's the example - I stuck pretty close to the workaround proffered in the comment on #4050, run `build.sh` to generate and diff the files.
[mwe.tar.gz](https://github.com/kubernetes-sigs/kustomize/files/10536442/mwe.tar.gz)

I'd expect both result to be the same, but they differ:

```patch
--- mwe/build.yaml	2023-01-30 15:06:03.698447968 +0100
+++ mwe_broken/build.yaml	2023-01-30 15:06:03.761781826 +0100
@@ -19,11 +19,10 @@
 metadata:
   creationTimestamp: null
   labels:
-    app: app
+    app: app_a
     env: dev
-    overlay: dev_a
-  name: app_a
-  namespace: app
+  name: app-a
+  namespace: app_a
 spec:
   replicas: 1
   selector:
@@ -47,11 +46,10 @@
 metadata:
   creationTimestamp: null
   labels:
-    app: app
+    app: app_b
     env: dev
-    overlay: dev_b
-  name: app_b
-  namespace: app
+  name: app-b
+  namespace: app_b
 spec:
   replicas: 1
   selector:
```
