### ISSUE TITLE
[Question] exactly how is -hash suffix computed on different resources

### ISSUE THREAD

**Issue by hholst80** [kubernetes-sigs/kustomize#4815]
I want to be bug-for-bug compatible with the way Kustomize works on generated resources. How is the -suffix hash computed?

**Comment by KnVerey** [comment]
The HashTransformer implements the suffixing:

https://github.com/kubernetes-sigs/kustomize/blob/a612cd2b7e53a6464fa9793080f8c5d9b702d4c8/plugin/builtin/hashtransformer/HashTransformer.go#L20-L39

The hasher itself seems to be exposed, so you could even use it directly (though note that the api module is still pre-v1 and as such we reserve the right to make breaking changes to its interfaces when needed by Kustomize itself):

https://github.com/kubernetes-sigs/kustomize/blob/123a5d6e56ea9b54e88342c497cbb39cca248a8d/api/hasher/hasher.go#L60-L76
