### ISSUE TITLE
commonLabels in components should be scoped to component level

### ISSUE THREAD

**Issue by jaisojar** [kubernetes-sigs/kustomize#4821]
**Is your feature request related to a problem? Please describe.**

I tried using commonLabels in a component with a deployment, but the components commonLabels seem to overwrite the commonLabels of the base. I would be nice if I could use the commonLabels so that it applies only for the resources in the component, for example if I want to have a selector for the pods for the component only.

**Describe the solution you'd like**

I would like either that the commonLabels would only apply to the resources defined in the component, or, that there would be a new kustomization, which would allow adding having scoped common labels.

**Describe alternatives you've considered**

Maybe I shouldn't use components for this use case, what I was trying to achieve was having a dependency resource in my local minikube dev environment, but when I apply to test or production, that would be replaced by the actual endpoint. If I have multiple components, then the commonLabels of the last component would overwrite all other components, so it seems to me this could be an accident or something that isn't by design. But perhaps the part in the components guide is a bit misleading, it says that having a dev environment is specifically one of the use cases.

**Additional context**

[See this guide](https://kubectl.docs.kubernetes.io/guides/config_management/components/)

**Comment by aabouzaid** [comment]
I just came to open an issue for the same problem.

It's not clear to me why the component's `commonLabels` overwrites the label of the resource :thinking:

**Comment by aabouzaid** [comment]
That's probably the same as #3770 but still not answered.
TBH, for me, it's confusing behaviour!

**Comment by tricktron** [comment]
The proposed solution here would in my opinion also play very nicely with the [best practices for common labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). E.g. the `app.kubernetes.io/component` label defined in the components `kustomization.yml` should only apply to the component.

**Comment by KnVerey** [comment]
The fact that transformers in components modify resources from the base that imports them is fundamental to the feature; indeed, that is what distinguishes a Component from a Kustomization. From the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1802-kustomize-components#proposal) that introduced them:

> A component with transformers can transform the resources that an overlay has previously specified in the resources field. Components with patches do not have to include the target resource in their resources field.

Having this not apply to all transformers universally would be somewhat infeasible technically and an even more confusing user experience IMO. As for how to organize your configuration in light of this, unfortunately the maintainers do not have bandwidth to consult on individual setups. I suggest reaching out with more details on your setup to the Kustomize community in the [Kubernetes Forum](https://discuss.kubernetes.io/) or the `#kustomize` channel in [Kubernetes Slack](https://slack.k8s.io/).

/close
