### ISSUE TITLE
[Question] What is the correct way of telling which version of kustomize has what features?

### ISSUE THREAD

**Issue by yogeshgadge** [kubernetes-sigs/kustomize#4827]
Question in the title but I wanted to find out since what version `Replacements` and `Components` are supported.

But a better question is do we have the schema's for `kustomization.yaml` by versions  somewhere because I googled and I can't find anywhere other than the Schema Store but that doesn't support it ?

**Comment by KnVerey** [comment]
Right now the only way in most cases is to look through the [release notes](https://github.com/kubernetes-sigs/kustomize/releases?q=kustomize%2F&expanded=true). We had a discussion a while back about how we could do better, and some of the complexities of versioning this project (API version vs CLI version vs module version) in https://github.com/kubernetes-sigs/kustomize/issues/4121. I've re-opened and frozen that older issue.

/kind documentation
/triage duplicate 
/close
in favour of https://github.com/kubernetes-sigs/kustomize/issues/4121

**Comment by yogeshgadge** [comment]
@KnVerey Can't comment on the #4121 and I see people pointing to a feature table and documentation which is good but why not maintain a kubernetes JSON schema. I believe there are some issues/requests  regarding not having schema. 

If documentation table must be generated, including deprecation warnings it can contain those and docs can be generated from it.

Some unit tests `kubeval` can be used to force update this schema ensuring it is up to date.
