### ISSUE TITLE
[Question] Is there a easy way to use patch in my own program?

### ISSUE THREAD

**Issue by dayeguilaiye** [kubernetes-sigs/kustomize#4843]
In my program, I need to do exactly same thing as kustomize's patching, such as patchStrategicMerge / patchJson6902 / Patch.

But I found that the core code of patching is not for yaml file, it is for resource.Resource / types.PatchStrategicMerge instead.

So I wonder is there a easier way to do this, like kustomize.PatchFile(src, dest string) (I didn't found any like this), 
or is there any other github repo can do this?

**Comment by KnVerey** [comment]
The tools in [the `kyaml` module](https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml@v0.13.10) are the closest thing we have to what you're looking for, but they are definitely all Kubernetes-resource-oriented. For example:
- [kyaml's `merge2` package](https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml@v0.13.10/yaml/merge2#Merge) is what the SMP transformer ultimately uses. It takes RNodes, which you can get by using [kio.ByteReader](https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml@v0.13.10/kio#ByteReader) to read your files. For jsonpatch, we're using github.com/evanphx/json-patch.
- You could also load RNodes using kio.ByteReader (see above) for use with the API package's [SMP](https://pkg.go.dev/sigs.k8s.io/kustomize/api@v0.12.1/filters/patchstrategicmerge) and [jsonpatch](https://pkg.go.dev/sigs.k8s.io/kustomize/api@v0.12.1/filters/patchjson6902) filters. A caveat on this option is that the api module is very much in service of Kustomize and has no backwards compatibility guarantees at all. The kyaml module is also alpha series, but is designed to be a generic toolkit for use beyond Kustomize.
- In terms of higher-level tools, the kyaml function framework has a [TemplateProcessor](https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml/fn/framework#example-TemplateProcessor-Patch) that can apply (optionally Go-templated) patches to resources, among other things. You can get k8s yaml files into the ResourceList type it wants by using it with [`framework.Execute`](https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml@v0.13.10/fn/framework#Execute). 

I hope that helps. Feel free to re-open if your question is not resolved.
/kind support
/area kyaml
/triage resolved
/close
