### ISSUE TITLE
Security vulnerability fixed but needing a new tag

### ISSUE THREAD

**Issue by panbanda** [kubernetes-sigs/kustomize#4864]
We have some production images using argo which depends on `kyaml`.  It is throwing two HIGH risk vulnerabilites.

- https://security.snyk.io/vuln/SNYK-GOLANG-GOPKGINYAMLV3-2841557
- https://security.snyk.io/vuln/SNYK-GOLANG-GOPKGINYAMLV3-2952714

This line already fixes it: https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/go.mod#L44

However, the latest version of kyaml is v0.13.9.  Is there a timeline for the new release with this fix in place?  Anything I can help to contribute to this release?

**Comment by natasha41575** [comment]
We are currently planning to release in early December. Does that timeline work for you?

**Comment by panbanda** [comment]
Yeah that should work.  I'll continue to watch this. Thank you much!

**Comment by annasong20** [comment]
https://github.com/kubernetes-sigs/kustomize/releases/tag/kyaml%2Fv0.13.10 has been released!

/close
