### ISSUE TITLE
Refactor repospec code to be more readable

### ISSUE THREAD

**Issue by annasong20** [kubernetes-sigs/kustomize#4866]
**Describe the bug**

`RepoSpec` readability issues include:

- [x] The function [`parseGitURL`](https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/git/repospec.go#L111) in `RepoSpec` currently has 7 return values. This makes differentiating between the return values more difficult than it needs to be and prone to error. Potential solutions:

  * return a `RepoSpec` instead of the 7 fields of `RepoSpec`
  * parse different parts of the url by calling several helper functions in `NewRepoSpecFromURL` directly
  
  An example of this can be found [here](https://github.com/kubernetes-sigs/kustomize/pull/4741/files#diff-109bb418d3031aaee374127b42b05a6845a4fb528a637c734a84270be49d8c8fR112).
- [ ] Rename [`OrgRepo`](https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/git/repospec.go#L35) given reasoning: https://github.com/kubernetes-sigs/kustomize/pull/4863#discussion_r1020538635
- [ ]  Rename [`Host`](https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/git/repospec.go#L31), as suggested in: https://github.com/kubernetes-sigs/kustomize/pull/4779#discussion_r957657978
  * Rename `SchemeAuth`
  * Split into multiple fields `Scheme`, `UserInfo`, `Host`, `Port`, which gives calling code, like [`kustomize localize`](https://github.com/kubernetes-sigs/kustomize/blob/master/proposals/22-04-localize-command.md), more information
- [ ] Decide how to handle `url.Parse()` error for `orgRepo`, `Path`, and query, as suggested here: https://github.com/kubernetes-sigs/kustomize/pull/4863#discussion_r1020556788

**Version**
Kustomize master branch, commit https://github.com/kubernetes-sigs/kustomize/commit/e724e25fecaae65ccf0b48e2e09e5c533cfc7de8

**Comment by natasha41575** [comment]
I think we should make this issue an umbrella issue to track the refactoring we want to do for repoSpec. WDYT about retitling it to "Refactor repospec code to be more readable" and listing this particular issue as one of the things we want to do? Then we can add more to this issue as we go along, like the suggestion here https://github.com/kubernetes-sigs/kustomize/pull/4863#discussion_r1020538635 - rather than filing a separate issue for each thing.

**Comment by annasong20** [comment]
> I think we should make this issue an umbrella issue to track the refactoring we want to do for repoSpec. WDYT about retitling it to "Refactor repospec code to be more readable" and listing this particular issue as one of the things we want to do? Then we can add more to this issue as we go along, such as the suggestion here [#4863 (comment)](https://github.com/kubernetes-sigs/kustomize/pull/4863#discussion_r1020538635) - rather than filing a separate issue for each thing.

Love the idea!

**Comment by natasha41575** [comment]
@koba1t would you be interested in taking this issue?

**Comment by kishorerj** [comment]
@annasong20 @natasha41575 I am looking at starting my contribution journey in K8 and would like to pick this up.. Can u please assign it to me?

**Comment by koba1t** [comment]
Hello @kishorerj!
Thanks for taking this issue!
We're waiting for your PR!

**Comment by kishorerj** [comment]
@koba1t @annasong20 @natasha41575  I created the draft PR with changes to the first task mentioned in the issue above (replace 7 return values with repo spec). https://github.com/kubernetes-sigs/kustomize/pull/4891. I built the code and also ran the tests to ensure there are no impacts.. Since this is my first change, I have to do a few pending items on CLA which I will get sorted soon. Also will be committing changes for the other issue tasks mentioned here

**Comment by kishorerj** [comment]
@annasong20 @natasha41575 I have created PR for the first task as mentioned above, you can take a look at it. I need more details for the second task. What are we trying to achieve here. Maybe an example will help.. Also whats the best way to get connected on this issue? Do i ping in slack, set up a zoom meeting?

**Comment by annasong20** [comment]
@kishorerj and I synced offline. I edited the issue with examples and more context.

**Comment by kishorerj** [comment]
> @kishorerj and I synced offline. I edited the issue with examples and more context.

Thanks Anna for giving more context.. This helps

**Comment by kishorerj** [comment]
@annasong20 I have opened this PR for review.. https://github.com/kubernetes-sigs/kustomize/pull/4900.
It has fixes for Task1 that you have mentioned in this issue.. I will open seperate PRs for other tasks

**Comment by kishorerj** [comment]
> @koba1t @annasong20 @natasha41575 I created the draft PR with changes to the first task mentioned in the issue above (replace 7 return values with repo spec). #4891. I built the code and also ran the tests to ensure there are no impacts.. Since this is my first change, I have to do a few pending items on CLA which I will get sorted soon. Also will be committing changes for the other issue tasks mentioned here

Please ignore this PR.. I have closed it.. Please consider https://github.com/kubernetes-sigs/kustomize/pull/4900

**Comment by kishorerj** [comment]
@KnVerey @natasha41575  @annasong20 For2nd task any suggestions on what could be the name instead of OrgRepo ? .. How about repo or repoRoot or repoRootPath .. ? Any opinion?

**Comment by annasong20** [comment]
2. I don't have a strong preference. Maybe `repoPath` for `OrgRepo` and `rootPath` for `Path`? Will defer to @KnVerey, @natasha41575 
4. I'm leaning towards returning an error. In the case we're parsing an `OrgRepo`, we'll be returning an error anyway if we set it to the empty string. In the case of `Path`, I find it strange to treat the repo as the target root if we can't parse the path. Granted, the error might not result from an invalid `OrgRepo` or `Path`; maybe `url.Parse` just has a different spec than that of acceptable `OrgRepo`s and `Path`s for certain edge cases. However, until we stop using `url.Parse` to extract `OrgRepo`, `Path`, we should return the error to signify to users we don't know how to handle the input. I also don't have all context, so again will defer to @KnVerey, @natasha41575

**Comment by KnVerey** [comment]
> 2. I don't have a strong preference. Maybe repoPath for OrgRepo and rootPath for Path? 

I like `repoPath` for `OrgRepo`. For `Path`, I suggest `KustRootPath` to clarify that it isn't the repo or clone root.

> 4. I'm leaning towards returning an error. In the case we're parsing an OrgRepo, we'll be returning an error anyway if we set it to the empty string. In the case of Path, I find it strange to treat the repo as the target root if we can't parse the path. Granted, the error might not result from an invalid OrgRepo or Path; maybe url.Parse just has a different spec than that of acceptable OrgRepos and Paths for certain edge cases. However, until we stop using url.Parse to extract OrgRepo, Path, we should return the error to signify to users we don't know how to handle the input. 

My instinct is also to return the error, though it is possible the larger test suite (I only ran a subset previously) might reveal a reason not to do this. Let's try it and discuss further on the PR if needed.

**Comment by kishorerj** [comment]
@annasong20 @natasha41575 @KnVerey pushed the changes for name changes  in the PR https://github.com/kubernetes-sigs/kustomize/pull/4922.  I am not clear on task3 . Next I will pick up task 4 on handling url.parse() error and try to push this on Monday/Tuesday
