### ISSUE TITLE
Latest kyaml not compatible with latest api ?

### ISSUE THREAD

**Issue by eddycharly** [kubernetes-sigs/kustomize#4896]
It looks like this is incompatible:

```
	sigs.k8s.io/kustomize/api v0.12.1
	sigs.k8s.io/kustomize/kyaml v0.13.10
```

This triggers the compile error:
```
# sigs.k8s.io/kustomize/api/internal/plugins/fnplugin
../../../../go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/plugins/fnplugin/fnplugin.go:60:9: too many return values
        have (*runtimeutil.FunctionSpec, error)
        want (*runtimeutil.FunctionSpec)
```
Am I missing something ?

**Comment by KnVerey** [comment]
That's very possible unfortunately. We have released kyaml much more recently than api. We're planning to release the whole module stack again in a couple weeks. Do you have a more urgent need to use latest kyaml + the api module?

/kind releasing

**Comment by eddycharly** [comment]
Nothing very urgent, I'm just trying to keep my dependencies up to date.

**Comment by KnVerey** [comment]
I'll go ahead and close this then, since it will automatically be solved by the upcoming release.

/close

**Comment by eddycharly** [comment]
> by the upcoming release

@KnVerey is this going to happen soon ?

**Comment by Rubemlrm** [comment]
hi @KnVerey hope that it's all fine with you and happy new year.

It's possible to have a time expectation for the new release? I have a situation in which we need to upgrade to the last version per company requirements, but with this behavior, I'm not able to do that.

**Comment by KnVerey** [comment]
We were originally planning to do it several weeks ago, but with illness and other complications we were not able to get everything in before the holidays. We're now aiming for next week.

**Comment by Rubemlrm** [comment]
@KnVerey thank you for the feedback. It's totally comprehensible that situation, hope that it's all fine now in terms of health.
