### ISSUE TITLE
Kustomize throws wrong error message for remote base failure

### ISSUE THREAD

**Issue by shoekstra** [kubernetes-sigs/kustomize#4935]
### What happened?

Hi!

We use a private GitHub repository to host our manifests/kustomizations and add tags when a base folder is updated and ref this tag in our overlay, example:

```
bases:
  - github.com/myOrg/myRepo//kubernetes/myApp/base?ref=myApp-v2
```

Running kustomize locally, using this format, everything is great. Running via GitHub Action, it does not recognise this is a git URL and instead tries to access the path on the local filesystem, e.g.

```
Error: accumulating resources: accumulation err='accumulating resources from 'github.com/myOrg/myRepo//kubernetes/myApp/base?ref=myApp-v2': evalsymlink failure on '/home/runner/work/myRepo/myRepo/kubernetes/myApp/envs/dev/github.com/myOrg/myRepo/kubernetes/myApp/base?ref=myApp-v2' : lstat /home/runner/work/myRepo/myRepo/kubernetes/myApp/envs/dev/github.com: no such file or directory': git cmd = '/usr/bin/git fetch --depth=1 origin myApp-v2': exit status 128
```

We have tried install kustomize via an action, via the bash installer, and using the pre-installed version in the Ubuntu runner.

We tried some other variations:

Prepending the path with `git::https://` in my `kustomization.yaml` as suggested in another issue to the following:

```
bases:
  - git::https://github.com/myOrg/myRepo//kubernetes/myApp/base?ref=myApp-v2
```

No issue running locally, via GitHub Action:

```
Error: accumulating resources: accumulation err='accumulating resources from 'git::https://github.com/myOrg/myRepo//kubernetes/myApp/base?ref=myApp-v2': evalsymlink failure on '/home/runner/work/myRepo/myRepo/kubernetes/myApp/envs/dev/git::https:/github.com/myOrg/myRepo/kubernetes/myApp/base?ref=myApp-v2' : lstat /home/runner/work/myRepo/myRepo/kubernetes/myApp/envs/dev/git::https:: no such file or directory': git cmd = '/usr/bin/git fetch --depth=1 origin myApp-v2': exit status 128
```

Trying with just `https://` prepended:

```
bases:
  - https://github.com/myOrg/myRepo//kubernetes/myApp/base?ref=myApp-v2
```

This gets us a step further:

```
Error: accumulating resources: accumulation err='accumulating resources from 'https://github.com/myOrg/myRepo//kubernetes/myApp/base?ref=myApp-v2': URL is a git repository': git cmd = '/usr/bin/git fetch --depth=1 origin myApp-v2': exit status 128
```

### What did you expect to happen?

Kustomize to correctly generate the manifests when run via GitHub Action as when run locally.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a private GitHub repository and a setup a base folder with any resource(s)
2. Create a tag (e.g. base-v1)
3. Reference that tag in your overlay
4. Create a GitHub Action that runs `kustomize build path/to/overlay`

### Expected output

Successfully generated manifests.

### Kustomize version

v4.5.7

### Operating system

Linux

**Comment by natasha41575** [comment]
I think this is a legitimate bug in the sense that kustomize is throwing the wrong error. Kustomize will first try to load elements under `bases` as paths; if that fails, it will try to load them as URLs. It seems here that your Github Action is failing to reach your private Github repo and then kustomize is outputting the wrong error. If it works locally, then it's possible that your Github Action has some sort of authentication failure. I would suggest you try to see if a simple `git clone` works from your Github Action and debug from there. 

On the kustomize side, we should make sure that we are throwing the correct error. The relevant bit of code is here, for anyone who wants to take a stab at fixing this: https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/target/kusttarget.go#L408

Please feel free to reopen this if you have any further questions or things to discuss.

**Comment by natasha41575** [comment]
/retitle Kustomize throws wrong error message for remote base failure

/triage accepted

**Comment by annasong20** [comment]
#4807 documents the confusing behavior that you see.

**Comment by natasha41575** [comment]
Thanks @annasong20! I think we can close this one in favor #4807. @shoekstra, please feel free to reopen if you find more to discuss or have further questions.
