### ISSUE TITLE
Add option to create namespace resource

### ISSUE THREAD

**Issue by Firehed** [kubernetes-sigs/kustomize#4938]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I would like the option to create the `namespace` resource as part of the `kustomization`, and/or intelligently resolve conflicts if they arise.

### Why is this needed?

Background: 

I have a Kustomize-based gitops workflow. The simplified version is that there's a base for each `web` and `backend`, containing a typical collection of resources (deployments, HPA, Ingress, etc). 

There are also several overlays for various environments, e.g. `backend-staging`, `backend-production`, `web-staging`, etc. These use the `namespace` option in the kustomization so that they can be deployed into a single cluster, for efficient use of physical resources. In order to support this, each of the bases includes a `kind: Namespace` resource file:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: placeholder
```

The placeholder name is, of course, updated to the value in the Kustomization, along with the other resources.

_However_, I now have a need to co-deploy my backend and web bases into a single overlay with a single namespace. When trying to do so, Kustomize complains that there are two conflicting resources: `Error: accumulating resources: accumulation err='accumulating resources from '../../base/web': '/***/gitops/base/web' must resolve to a file': recursed merging from path '/***/gitops/base/web': may not add resource with an already registered id: Namespace.v1.[noGrp]/placeholder.[noNs]`.

This makes sense, because the two (placeholder) files are identical and cannot be combined. You'll note that they exist due to a gap in Kustomize functionality: the `namespace` kustomization only _sets_ the namespace metadata, it does not create the resource.

If instead, it were possible to do something like:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/backend
- ../../base/web
namespace:
  create: true
  name: my-namespace
```
and get a `kustomize build` output of:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
# ...
```
this would avoid the need to have the various "placeholder" Namespace resources in place.

### Can you accomplish the motivating task without this feature, and if so, how?

I can move the placeholder `namespace` resources from the bases to the overlays. This causes a lot of repeated data, and is something more likely to be missed when new overlays are created.

I might be able to accomplish the same thing by having two different overlays that both contain the same `namespace` value. This would conflict with several of our internal naming conventions, and would lead to a lot of confusion.

### What other solutions have you considered?

I've also looked into the name prefixes and suffixes. They're inappropriate for our cluster due to internal needs, and I'm not confident they'd resolve the issue.

### Anything else we should know?

There are a couple of other open tickets relating to additional control over namespace behavior through Kustomization files, dating back to at least 2019. It seems as though there's an ongoing need to enhance how Kustomize interacts with namespaces.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by natasha41575** [comment]
This issue on its own makes sense to me. It sounds like you're looking for something like a `NamespaceGenerator`, and off the top of my head I can't think of another way to achieve your goal with existing features. That said, I don't want to be hasty and will take some time to look into the current NamespaceTransformer a little more to see what's currently possible, but I'm not necessarily opposed to the feature you are suggesting here.

@KnVerey It would be great to have your opinion on this as well.

/triage under-consideration

**Comment by Firehed** [comment]
Thank you @natasha41575 ! 

Just to be explicit for my use-case, I'm _not_ looking for hash-suffixed namespace names like ConfigMapGenenerator and SecretGenerator produce by default. But as long as it could be targeted with `generatorOptions.disableNameHashSuffix: true` or similar (without impacting the suffixes for CMs/Secrets, which are desirable for many workflows) I think that would work great 👍

**Comment by mpeters-tha** [comment]
I'm stuck with same issue. I need a namespace per env (dev/stagging/prod) but I'm refering to external kustomization resources that are out of my scope and might define (or not) a namespace. 
So either I define one on my side and it will fails if the external resource has defined one as well, or it might fails if I don't define one and they are not defining one as well in the external resources.

**Comment by lburja** [comment]
I'd appreciate as well to be able to create namespaces via kustomization.yaml files. 

namespace:
  create: true
  name: my-namespace

**Comment by CNC5** [comment]
This feature would be awesome to have.
