### ISSUE TITLE
google/shlex is archived

### ISSUE THREAD

**Issue by pacoxu** [kubernetes-sigs/kustomize#4963]
https://github.com/kubernetes-sigs/kustomize/blob/9bc75c16d922f0ee78f6e7351e41d39ae6b8ca69/api/go.mod#L8

follow up of https://github.com/kubernetes/kubernetes/pull/114912

github.com/google/shlex  is archived.

**Comment by pacoxu** [comment]
I cannot find a valid replacement for this.
- https://github.com/anmitsu/go-shlex is newer but has not been updated since 2020 and has no releases.

**Comment by KnVerey** [comment]
Hmm, I guess we'll have to look more deeply at what we use this for. There is only one usage:

https://github.com/kubernetes-sigs/kustomize/blob/8ab4b8d167898ab04a6a398111e1ada97f46e859/api/internal/plugins/execplugin/execplugin.go#L96

/triage accepted
/kind cleanup

**Comment by pacoxu** [comment]
Not sure if https://pkg.go.dev/mvdan.cc/sh/v3@v3.6.0/shell can help in this case.

**Comment by pacoxu** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/5006#discussion_r1128095488 may be a workaround to maintain it in util.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/utils/pull/300 may be a fix, but as we have no new requirements on it. I prefer to do nothing now.

**Comment by pohly** [comment]
> Hmm, I guess we'll have to look more deeply at what we use this for. There is only one usage:
> 
> https://github.com/kubernetes-sigs/kustomize/blob/8ab4b8d167898ab04a6a398111e1ada97f46e859/api/internal/plugins/execplugin/execplugin.go#L96

Note that google/shlex does not handle POSIX correctly:
https://go.dev/play/p/jiQpbBDQGUD

```
package main

import (
	"fmt"

	"github.com/google/shlex"
)

func main() {
	args, _ := shlex.Split(`"\[Flaky\]"`)
	fmt.Printf("%q", args)

	// Prints ["[Flaky]"], should be ["\\[Flaky\\]"] because
	// a shell (bash in my case) leaves the backslash in place:
	// $ echo "\[Flaky\]"
	// \[Flaky\]
}
```
[github.com/anmitsu/go-shlex](http://github.com/anmitsu/go-shlex)  handles this when using POSIX mode.
