### ISSUE TITLE
github.com/pkg/errors is archived

### ISSUE THREAD

**Issue by pacoxu** [kubernetes-sigs/kustomize#4964]
### What happened?

        "sigs.k8s.io/kustomize/api",
        "sigs.k8s.io/kustomize/kustomize/v4",
        "sigs.k8s.io/kustomize/kyaml"

### What did you expect to happen?

as github.com/pkg/errors is archived

follow up of https://github.com/kubernetes/kubernetes/pull/114912

**Comment by KnVerey** [comment]
/triage accepted
/close
Fixed by #4970
