### ISSUE TITLE
CI check for undesired dependencies

### ISSUE THREAD

**Issue by KnVerey** [kubernetes-sigs/kustomize#4982]
kubernetes/kubernetes has a list of unacceptable dependencies that they check in CI. Since we are subject to the same requirements, we should add the same check. This would help us avoid surprises when we go to update kustomize in kubectl.

https://github.com/kubernetes/kubernetes/blob/e51fe4a61cca7f4a0875630da433f280b52c138a/hack/lint-dependencies.sh

We will need to think carefully about how to source the dependencies list itself. If we pick it up live, everyones PR will instantly start to fail if k/k adds something we already depend on to the list, which happened with a few archived packages recently. Do we want that?

**Comment by natasha41575** [comment]
> We will need to think carefully about how to source the dependencies list itself. If we pick it up live, everyones PR will instantly start to fail if k/k adds something we already depend on to the list, which happened with a few archived packages recently. Do we want that?

One option is to leave this CI check as optional. If we see it failing, we file an issue for the problematic dependency and mark that issue as release blocking.

**Comment by antoooks** [comment]
The script on k/k checks 4 things:
1. undesired dependencies listed on `unwanted-dependencies.json`. I believe this file is updated manually and unless we have exactly the same blocked dependencies as k/k we have to maintain our own block list.
2. outdated dependencies
3. non-canonical dependencies
4. unused dependencies

Should we cover all things for this issue or just the undesired dependencies @natasha41575

**Comment by koba1t** [comment]
I feel this problem is scoped in upgrading kustomize in Kubectl.
I think it is enough to check the dependencies list in the `unwanted-dependencies.json` file.

**Comment by antoooks** [comment]
@koba1t are you referring to k/k's `unwanted-dependencies.json` file or you agree that we should maintain ours?

**Comment by koba1t** [comment]
I think that is enough to refer to unwanted-dependencies.json in the k/k repo.
