### ISSUE TITLE
Test against number of patches applied

### ISSUE THREAD

**Issue by paul-bormans** [kubernetes-sigs/kustomize#4987]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Often we find ourselves debugging and fixing patches because they tend to break when say upstream manifests changes.

For instance:
```
          - patch:
              - op: add
                path: /my/path/to/resource
                value: ...
```
Would have a different result if /my/path/to/resource existed or not.

It would be very helpfull to be able to specify as part of the patch spec, the "expectations". For instance:
- the number of changes/patches applied for the given patch.

If these expectations do not match an error should be raised.

### Why is this needed?

Prevents incorrect or broken patches

### Can you accomplish the motivating task without this feature, and if so, how?

Today when working with patches we always run build with and without the patch and compare the output, but still you need to review the diff (for instance using yaml-diff) to decide if the behavior is as expected; it's errorprone.

### What other solutions have you considered?

Use of diff tooling as mentioned.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by KnVerey** [comment]
/triage needs-information

Can you please provide a more detailed reproduction case for us to consider? When I attempt to apply an `op: add` patch to a path that does not exist, I get an error, which it sounds like is the outcome you were looking for.
