### ISSUE TITLE
Getting error: Version vX.X.X does not exist or is not available for linux/amd64.

### ISSUE THREAD

**Issue by halim-lee** [kubernetes-sigs/kustomize#5033]
### What happened?

Ran the following command to install kustomize v3.8.7:
```
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s 3.8.7
```
And I got the following:
```
Version v3.8.7 does not exist or is not available for linux/amd64.
```

Error occurred on Ubuntu 22.04.1 LTS and it happens to the latest release v5.0.0 as well.

### What did you expect to happen?

Install kustomize successfully

### How can we reproduce it (as minimally and precisely as possible)?

Try running the following command:
```
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s X.X.X
```
`X.X.X` being the release

### Kustomize version

v3.8.7

### Operating system

Linux

**Comment by kimdre** [comment]
+1

**Comment by ephesused** [comment]
Perhaps run like so:

```
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -sx 3.8.7
```

The -x will output execution details from the script.

**Comment by simonoff** [comment]
there is an issue with github token

**Comment by gaetancollaud** [comment]
> there is an issue with github token

Thank you, this was my issue. Solved it with 
```
unset GITHUB_TOKEN
```
