### ISSUE TITLE
Add openshift crd's 

### ISSUE THREAD

**Issue by danielraq** [kubernetes-sigs/kustomize#5057]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Could you add openshift crd to default kustomize configuration?
More details:
https://github.com/adnovum/kustomize-openshift

### Why is this needed?

It woult improve my work

### Can you accomplish the motivating task without this feature, and if so, how?

yes. Adding them manualy

### What other solutions have you considered?

none

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by KnVerey** [comment]
Thank you for putting together a collection of CRDs folks can use to more easily work with Kustomize + OpenShift. However, including configuration for APIs that are not part of core Kubernetes is out of scope for Kustomize's own core.

/triage out-of-scope
/close
