### ISSUE TITLE
Image transformer is not applied to HelmChartInflationGenerator generated resources if split out to component

### ISSUE THREAD

**Issue by Unveraenderbar** [kubernetes-sigs/kustomize#5071]
### What happened?

I have a set of Helm Charts, that is hydrated by kustomize via the HelmChartInflationGenerator, and then get ImageTagTransformers applied to the generated results
```
generators:
- ../../clusters/dev-stage/dev-env # kustomization with HelmChartInflationGenerator resources, get them rendered

images:
- name: .*/opapolicyagent/opa
  newTag: v7.77.7777
```
This works fine -- but of course, it immediately turns out that the (in reality rather lengthy) list of image transformation specs has to be split out of the root kustomization for reuse.
But, as soon as this is done (as a Component) , the image transformations are no longer applied!
What makes me think this is a bug is that the image tags _are_ changed in a Deployment that is loaded directly as a resource, i.e.
```
resources:
- sample-deployment.yaml # image tag transformation included as component is applied to this resource!

generators:
- ../../clusters/dev-stage/dev-env # image tag transformation included as component is *not* applied to generated resources!!

components:
- ../../overlays/image-specs/dev-env-image-tags.yaml # contains image tag transformations shown above
```

### What did you expect to happen?

The image tag transformations should be applied to all resources, no matter whether these are included statically or generated dynamically, and regardless of the transformations being given in-place in the root kustomizaton or split out into a component.

### How can we reproduce it (as minimally and precisely as possible)?

[image-transformation-as-component-failure.zip](https://github.com/kubernetes-sigs/kustomize/files/10874523/image-transformation-as-component-failure.zip)

Change directory to created by unpacking archive given above, then execute
```
kustomize build --enable-helm . | grep image:
```

### Expected output

```
      - image: helm-hello-world:8.8.8
      - image: helm-hello-world:8.8.8
```

### Actual output

```
      - image: helm-hello-world:8.8.8
      - image: helm-hello-world:1.0.0
```

### Kustomize version

v5.0.0

### Operating system

Linux and Windows

**Comment by natasha41575** [comment]
I am not that familiar with Components, but this line from the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1802-kustomize-components#goals) stands out to me:

> A kustomization that is marked as a Component has basically the same capabilities as a normal kustomization. The main distinction is that they are evaluated after the resources of the parent kustomization (overlay or component) have been accumulated, and on top of them.

From this line, I agree that Components should be applied on top of resources from both the `resources` field and from any `generators`. I can also reproduce the issue on my end from the zip you provided (thank you very much for that).

/triage accepted
