### ISSUE TITLE
Parallelize pulling remote resources

### ISSUE THREAD

**Issue by blairdrummond** [kubernetes-sigs/kustomize#5075]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

When a kustomize manifest has many references to remote-bases, pull them in parallel instead of sequentially.

[Previous requests](https://github.com/kubernetes-sigs/kustomize/issues/2950) to parallelize pulling of remote bases were rejected due to amount of effort. However I'm hoping that it can be reconsidered for the `localize` subcommand, as it would provide a significant speedup.

### Why is this needed?

Pulling lots of git references can be quite slow, and it is leading to inconvenient build times. When I parallelize the process manually I'm seeing a 5x speedup in my builds, down from ~20 seconds to ~4 seconds.

### Can you accomplish the motivating task without this feature, and if so, how?

I have a kustomize setup that uses remote bases as "modules" with many modules composed into a cluster, which becomes a tree pattern like `{group}/{application}/kustomization.yaml`. So I had an easy layout to parallelize with a bash script

(note, I also needed to clean up some symlinks so I used a `cp -rL` command in here to manage that

```bash
#!/bin/bash
# fastbuild.sh
# This command is 5x faster than the `kustomize build . --load-restrictor LoadRestrictionsNone`
# that I normally have to use.

rm -rf .clone && mkdir .clone
cp -rL * .clone

# The following is equivalent (for this layout) to:
# 
# kustomize localize .clone .clone-localized \
# && mv .clone-localized .clone
# 
# However, the command below is 5x faster due to parallelism

pushd .clone
for path in */*/kustomization.yaml; do
    kdir=$(dirname $path)
    (
        kustomize localize $kdir ${kdir}-localized \
        && rm -rf $kdir \
        && mv ${kdir}-localized $kdir
    ) &
done
popd

echo "Waiting for all builds to finish"
wait $(jobs -p)

kustomize build .clone
rm -rf .clone
```

### What other solutions have you considered?

I have considered the following, not sure which would work:

**Try making the git clones faster through caching**
- Tactic: Trying to modify my .gitconfig to point to local copies of the modules
- Tactic: Set up a local git proxy with caches of the upstream repos to speed up clones?

**Try to reduce the number of remote modules**
- Could bypass this with git submodules? But those usually lead to regrets
- Could try to refactor my manifests to consolidate modules together?

**Could accept slow build times**

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by natasha41575** [comment]
I agree with the assessment in https://github.com/kubernetes-sigs/kustomize/issues/2950 that parallelizing pulling down git repos for `kustomize build` would be difficult and require a large refactor, but it might be interesting to see if we could achieve this with `kustomize localize` to provide a performance boost.

If someone has a proposed implementation plan, we'd be happy to take a look and discuss further.

/triage under-consideration

**Comment by komapa** [comment]
👋🏼 Hello, and agree you might not want to parallelize checkouts but how about dedupping checkouts? We have a problem where we have several services in a repo that all include the exact same git remote, down to the branch and those are being checked out several times. Can you at least checkout once per unique resource or is this also part of the complexity? Thank you!
