### ISSUE TITLE
It seems like kustomize is unable to use a helm binary that is installed by snap

### ISSUE THREAD

**Issue by thoraage** [kubernetes-sigs/kustomize#5094]
### What happened?

See https://stackoverflow.com/questions/75764866/kustomize-doesnt-seem-to-find-helm

I tried to follow this very nice guide: https://github.com/kubernetes-sigs/kustomize/blob/kustomize/v4.1.0/examples/chart.md

I get this error message when I try to build: 

```
$ kustomize build --enable-helm --helm-command /snap/bin/helm --load-restrictor LoadRestrictionsNone $DEMO_HOME/base
Error: unable to run: '/snap/bin/helm version -c --short' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-1398637062/helm HELM_CACHE_HOME=/tmp/kustomize-helm-1398637062/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-1398637062/helm/.data] (is '/snap/bin/helm' installed?)
```

I downloaded a binary version from the [helm release page](https://github.com/helm/helm/releases) and specifying that binary with `--helm-command` seems to remove the problem entirely.

### What did you expect to happen?

I expected to get a yaml of built k8s-objects instead of an error message.

### How can we reproduce it (as minimally and precisely as possible)?

Try to build a `helm` chart with `kustomize` with a `snap`-installed `helm`-binary.

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

v5.0.1

### Operating system

Linux

**Comment by justinsb** [comment]
Not the author of the code, but I've been playing with this recently.  kustomize is using `exec.Command` to run `helm`, so it shouldn't matter if it's in the home directory.  I would always prefer to use an absolute path if specifying `--helm-command` personally, but it looks like relative paths do work.

One thing to be sure of is that the copied is executable (i.e. `chmod +x /usr/local/bin/helm`).  It looks like we're not printing the error, which is making it a bit harder to diagnose what's going wrong.  You could also try running `/usr/local/bin/helm version` just to be sure that it is correctly installed.

Similarly, if you still have the snap installed, it would be interesting to see what the output is from running `/snap/bin/helm version -c --short`

**Comment by thoraage** [comment]
I removed the snap-version when I thought that was the problem, but reinstalled when I realised it wasn't. This is the answer I get when I running it manually:

```
$ /snap/bin/helm version -c --short
v3.10.1+g9f88ccb
```

Please note that in my last entry I was actually moving the same binary around on the disk and referred to it absolutely and relatively. The only pattern I saw was that it works within the home directory and doesn't work outside the home directory.

Is there any way I can get the helm-error message that kustomize doesn't print?

**Comment by justinsb** [comment]
I sent https://github.com/kubernetes-sigs/kustomize/pull/5099 so you could try that (e.g. `gh pr checkout 5099; go run ./kustomize build --enable-helm <mydir>`)

**Comment by thoraage** [comment]
I think it was snap after all; although not the `helm` installation. The `kustomize` binary was also installed by `snap`. I removed it and installed a binary version instead and then everything worked like a charm. 

It could be related to `kustomize` installed as regular `snap`-application and `helm` installed as "classic" `snap`-application.

Nevertheless, it was a very weird problem; sorry for any inconvenience.

**Comment by justinsb** [comment]
Thanks for updating!  Does snap sandbox applications?  If so maybe we need to allowlist helm in the sandbox for the kustomize snap?

**Comment by thoraage** [comment]
Yes it's sandboxed, but since you still just execute the `kustomize` binary name it's easy to be unaware of. I didn't know how `snap` worked, but it seems it needs an connection that have to be added in the description. I asked at the source of it: https://github.com/abskmj/snapcraft-kustomize/issues/18

**Comment by natasha41575** [comment]
> I think it was snap after all; although not the helm installation. The kustomize binary was also installed by snap. I removed it and installed a binary version instead and then everything worked like a charm.

It could be related to kustomize installed as regular snap-application and helm installed as "classic" snap-application.

Nevertheless, it was a very weird problem; sorry for any inconvenience.

From this comment, it sounds like this is unrelated to kustomize itself and more so about snap, so I'm going to close this issue so that it doesn't show up in our trackers. Please feel free to continue the discussion to find a solution to your problem if you'd like.
