### ISSUE TITLE
Kustomize config generator with finalizer

### ISSUE THREAD

**Issue by balu-ce** [kubernetes-sigs/kustomize#5151]
### What happened?

We use configmapgenerator to generate config map but I am trying to add finalizer to it . It is not allowing

### What did you expect to happen?

I needed to have a common finalizer in config map

### How can we reproduce it (as minimally and precisely as possible)?

- name:test
  files:
  - tf.json
  options:
    disableNameSuffixHash: true

### Expected output

kind: configMap
apiVersion: v1
metadata:
   name: test
   finalizer:
      - kubernetes
data:
  tf.json: {}

### Actual output

```yaml

```

### Kustomize version

5

### Operating system

Linux

**Comment by natasha41575** [comment]
@balu-ce I think you can create a configMap with a finalizer if you combine the configmapgenerator with a patch that adds the finalizer to it. Have you tried that?

**Comment by balu-ce** [comment]
@natasha41575 My config map name will be dynamically changing. Without knowing the name , I hope we cannot define the patch
