### ISSUE TITLE
cannot find object

### ISSUE THREAD

**Issue by OmegaDroid** [kubernetes-sigs/kustomize#518]
Hi I'm having some issues adding namespaces, config maps and ingresses. I'm not having any issues creating deployments or services.

My namespace looks like this::

    apiVersion: v1
    kind: Namespace
    metadata:
        name: dh-local

The error I'm getting is::

    Error: failed to find an object with gvk.Gvk{Group:"", Version:"v1", Kind:"Namespace"} to apply the patch

I'm running the latest version of kustomize::

    Version: {KustomizeVersion:1.0.10 GitCommit:383b3e798b7042f8b7431f93e440fb85631890a3 BuildDate:2018-10-26T23:12:01Z GoOs:unknown GoArch:unknown}

For ``kubectl`` I'm ruining::

    Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Thanks

**Comment by Liujingfang1** [comment]
@OmegaDroid From the error message, it looks like you added the namespace file to `patches` field. Can you add it to `resources` list instead?

**Comment by OmegaDroid** [comment]
:man_facepalming: Thanks a lot, I spent far too long trying to fix this...
