### ISSUE TITLE
Create contributor guide

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#5199]
Should cover

- how to fork kustomize/make a PR
- how to build kustomize locally 
- brief description of some of the important `make` targets (this should cover how to run the tests locally)
- a link to https://github.com/kubernetes-sigs/kustomize/blob/master/ARCHITECTURE.md

We should add this to the existing CONTRIBUTING.md under "dev guides". The existing dev guides are out of date, I think we should just remove those links from there (maybe we can consider updating them later), and replace them with the above information.

**Comment by ashutosh887** [comment]
I would like to work on this @natasha41575

**Comment by ashutosh887** [comment]
Thanks @annasong20 

Should I continue working on it?

\assign

**Comment by ashutosh887** [comment]
Thanks @annasong20 
Should I start working on it?

**Comment by annasong20** [comment]
Hi @Shekharcodess, are you still working on this issue? We plan to increase its priority, so if you aren't, someone else might assign themselves. Also left a comment on #5209.
