### ISSUE TITLE
Migrate exmaples from `patchesStrategicMerge` to `patches`

### ISSUE THREAD

**Issue by danistrebel** [kubernetes-sigs/kustomize#5200]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Clean up referenfces for `patchesStrategicMerge` by replacing them with `patches`

### Why is this needed?

`patchesStrategicMerge` was removed in >=5.0.0 (via https://github.com/kubernetes-sigs/kustomize/pull/4911)

### Can you accomplish the motivating task without this feature, and if so, how?

not in >= 5.0.0

### What other solutions have you considered?

N/A

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉

**Comment by ashutosh887** [comment]
@danistrebel Is this issue resolved?

**Comment by danistrebel** [comment]
Not sure I understand your question. I created the linked PR to fix the issue.

**Comment by ElSamhaa** [comment]
@danistrebel I don't think that `patchesStrategicMerge` is being deprecated as per [this](https://github.com/kubernetes-sigs/kustomize/pull/4911#issue-1480481792).

> This PR drops support for a very old style of patches. "Legacy patches" refers to being able to supply in the patches field what patchesStrategicMerge does now. We are not dropping support for any of the [documented fields](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/).

AFAIU, this is about removing redundancy.

**Comment by koba1t** [comment]
I'm so sorry for the delayed response.
I think that is valuable work. 

/triage accepted
/kind documentation

/assing @danistrebel
