### ISSUE TITLE
Allow static builds (disabling plugins)

### ISSUE THREAD

**Issue by sagikazarmark** [kubernetes-sigs/kustomize#5219]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I'd like to resubmit #4477 that adds the ability to disable plugins.

### Why is this needed?

In some cross-compilation cases (namely on ARM64) compilation (or rather linking) fails when plugins are enabled. I haven't been able to figure out why (yet), but for now it seems easier to just disable plugins (since we don't use them anyway).

### Can you accomplish the motivating task without this feature, and if so, how?

Not really

### What other solutions have you considered?

The alternative is maintaining a fork of kustomize adding this feature

### Anything else we should know?

This has already been discussed in #4397 and submitted in #4477.

The primary arguments against adding this were:

- having to test two different builds
- Go plugins were going away anyway

We are one year later and Go plugins are still there. Also, normal uses of kustomize wouldn't require disabling plugins, so I'd say there is no need to test this independently.

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉

**Comment by koba1t** [comment]
Hi @sagikazarmark 

I think [this PR](https://github.com/kubernetes-sigs/kustomize/pull/5525) has resolved this request.
If you have any opinions or needs discuss, please feel free to open this PR!

/triage resolved
/close
