### ISSUE TITLE
Kustomize unable to produce windows and darwin ARM binaries

### ISSUE THREAD

**Issue by natasha41575** [kubernetes-sigs/kustomize#5220]
Related issues:
- https://github.com/kubernetes-sigs/kustomize/issues/4542
- https://github.com/goreleaser/goreleaser/issues/3835

TL;DR the outdated version of goreleaser we are stuck on (see the above issue) does not let us build windows and darwin ARM bindaires with go 1.20+. 

The solution here will most likely be to revamp the release process - I think we should see what does the rest of kubernetes do for releasing (maybe prow?) and follow a similar model.

**Comment by natasha41575** [comment]
If anyone is interested in picking this up, I think first steps would be to look around other k8s projects or talk to other k8s leads about how they do their releases and see if we can use similar tools. Then, leave your research findings here and we can try to converge on a decision.

**Comment by koba1t** [comment]
## other k8s projects
- [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder): using `golereaser` and using [actions/upload-artifact](https://github.com/kubernetes-sigs/kubebuilder/blob/47e6cab305336e1a7a5d577dc3c1500a445a70d1/.github/workflows/release.yml#L21-L33) for binary upload.
- [kops](https://github.com/kubernetes/kops): `go build` with their [Makefile](https://github.com/kubernetes/kops/blob/6b0b655d4089466f3be1e251d60669ad00befed0/Makefile#L193)
- [cluster-api](https://github.com/kubernetes-sigs/cluster-api): `go build` in docker for their [Makefile](https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L976-L997C8)
- [kwok](https://github.com/kubernetes-sigs/kwok): `go build` command on [their script](https://github.com/kubernetes-sigs/kwok/blob/876ac0fc4c14b7f55d2a47f4d06473605bb9879a/hack/releases.sh#L186)

**Comment by natasha41575** [comment]
I think `go build` is okay for releasing kustomize.

We will also need to think about how we release the other modules (`kyaml`, `api`, `cmd/config`) and the published docker image. 

The image needs to get pushed to a specific gcr registry managed by the k8s test-infra group (you can find the link on the releasing instructions page). If the current release infrastructure is not using goreleaser to release the docker image, then we can probably leave that the way it is. 

Releasing folder: https://github.com/kubernetes-sigs/kustomize/tree/master/releasing

**Comment by koba1t** [comment]
> The image needs to get pushed to a specific gcr registry managed by the k8s test-infra group (you can find the link on the releasing instructions page). If the current release infrastructure is not using goreleaser to release the docker image, then we can probably leave that the way it is.

In the container image build step, goreleaser is not executed and the artifacts built by goreleaser are not used.

**Comment by koba1t** [comment]
> We will also need to think about how we release the other modules (kyaml, api, cmd/config) and the published docker image.

I plan to use the simple shell scripts for building binaries and using GitHub CLI for creating GitHub Releases with every module(kyaml, api, cmd/config, and kustomize).

**Comment by natasha41575** [comment]
Thanks @koba1t! Feel free to get started. Please also update [the releasing instructions doc](https://github.com/kubernetes-sigs/kustomize/blob/master/releasing/README.md) with your PR.

**Comment by koba1t** [comment]
@natasha41575 

I update the [the releasing doc](https://github.com/kubernetes-sigs/kustomize/pull/5239/files#diff-1c26b5fcb097fb1cc3d7132cd193224d8437d930cf5cb38b81386c0034fdd8df), and I make `ready for review` [this PR](https://github.com/kubernetes-sigs/kustomize/pull/5239).
If you can, Please check this PR!

**Comment by pre** [comment]
Can we already start holding our breath?

**Comment by natasha41575** [comment]
I just approved https://github.com/kubernetes-sigs/kustomize/pull/5239, so I think we can consider this issue fixed. We're going to try out the new release process with the next release and I have my fingers crossed that we'll be able to ship the windows and darwin arm binaries.

**Comment by pre** [comment]
@natasha41575 when could we expect a new kustomize release?  The latest MacOS release is a four-month-old 5.0.3 from May.

**Comment by samrocketman** [comment]
Any ETA on next?  Ideally, you'd cut a release just to create the arm binaries if nothing else.  I see maintainers closed my and others' issues on this as dupes saying it will be in the next release but still no release.

**Comment by pre** [comment]
The current latest release for ARM is now 5 months old. 🤷🏼

**Comment by aaronromeo** [comment]
I recently ran into this. Turns out it was a PEBCAK. My GITHUB_TOKEN value was incorrect. The unfortunately, the error isn't clear as the value of `releases` (https://github.com/kubernetes-sigs/kustomize/blob/f3fedac42997470040e1fd574ad2518fad47f61a/hack/install_kustomize.sh#L141C5-L141C13) isn't being checked for this particular error.
