### ISSUE TITLE
Document `$patch: delete`

### ISSUE THREAD

**Issue by lindhe** [kubernetes-sigs/kustomize#5249]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

There's rumors going around the Internet that there is a `$patch: delete` thing one can use to delete objects in Kustomize. But I am unable to find any information about it in [the documentation](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/).

### Why is this needed?

Because it's nice to be able to use Kustomize to its fullest.

### Can you accomplish the motivating task without this feature, and if so, how?

Not easily.

### What other solutions have you considered?

n/a

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by lindhe** [comment]
I found that there's some example code [here](https://kubectl.docs.kubernetes.io/guides/example/inline_patch/#patch-delete) that actually uses `$patch: delete`, but it's completely without any comments discussing it.

Also, that page shows there's a `$patch: replace` directive too! I didn't know that. This just goes to show the need for having proper documentation over at https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/

**Comment by sebhoss** [comment]
AFAIK these `$patch` directives are just part of [strategic merge patches](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md) and their usage is explained [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md#basic-patch-format). That said, that document is deprecated & it would be really cool to find this information on the kustomize site!

**Comment by leifmadsen** [comment]
Example exists within the inlinePatch documentation: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/inlinePatch.md#inline-patch
