### ISSUE TITLE
Missing darwin/arm64 binaries

### ISSUE THREAD

**Issue by alecthomas** [kubernetes-sigs/kustomize#5260]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

darwin/arm64 binaries have been missing from the releases since 5.0.3. Could we have them back please?

### Why is this needed?

...

### Can you accomplish the motivating task without this feature, and if so, how?

darwin/amd64 binaries work but are obviously slower

### What other solutions have you considered?

.

### Anything else we should know?

.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by koba1t** [comment]
Thanks report!
This problem was trucked below issue. Please check!
- https://github.com/kubernetes-sigs/kustomize/issues/5220

/close
