### ISSUE TITLE
Support consize files and folders structure and ability to apply files not only folders

### ISSUE THREAD

**Issue by vit-h** [kubernetes-sigs/kustomize#5266]
### Eschewed features

- [ ] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

I want to have a way to skip creatin folders for every microservice I have.

Option 1:
base/service1.yml
base/service1-k.yml
base/service2.yml
base/service2-k.yml

dev/service1.yml
dev/service1-k.yml
dev/service2.yml
dev/service2-k.yml

Option 2: kustomize file which can have all the service specific yaml data as a yaml, not just a string after '|'
base/service1-k.yml
base/service2-k.yml

dev/service1-k.yml
dev/service2-k.yml

kubectl apply -k ../envs/dev/service1-k.yml
error: must build at directory: ' ../envs/dev/service1-k.yml': file is not directory

### Why is this needed?

to simplify files and folders structure

### Can you accomplish the motivating task without this feature, and if so, how?

yes, have to add tons of kustomize.yaml files and lots of folders

### What other solutions have you considered?

not to use kustomize

### Anything else we should know?

no

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by gaeljw** [comment]
You should clarify with a concrete example (files and content) IMHO. It's hard to understand what is bothering you right now.

**Comment by vit-h** [comment]
@gaeljw  I want to skip creating folders for service.yaml + kustomization.yml when I am kustomizing only one file.
So will be great to support some naming convention to allow this file structure:

dev/service1.yml
dev/service1-k.yml
dev/service2.yml
dev/service2-k.yml 

or support some way to put service.yaml + kustomization.yml in one file

dev/service1-k.yml
dev/service2-k.yml
