### ISSUE TITLE
Add the --no-verify flag to `kustomize localize`

### ISSUE THREAD

**Issue by annasong20** [kubernetes-sigs/kustomize#5276]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Currently, the [`kustomize localize`](https://kubectl.docs.kubernetes.io/references/kustomize/cmd/localize/) command does not give users the option to automatically run `kustomize build` to verify the localized copy before command return. This feature is documented in the command's [KEP](https://github.com/kubernetes-sigs/kustomize/blob/master/proposals/22-04-localize-command.md).

We would like to give users the option to specify the `--no-verify` flag for `kustomize localize`. When not specified, `kustomize localize` should run `kustomize build` on both the source Kustomization and localized copy and compare their output. When specified, the command should only localize, without running `kustomize build`.

### Why is this needed?

This feature is needed to graduate `kustomize localize` to beta, as stated in the [KEP](https://github.com/kubernetes-sigs/kustomize/blob/master/proposals/22-04-localize-command.md).

### Can you accomplish the motivating task without this feature, and if so, how?

It was agreed upon in the KEP that this feature would be a nice convenience to users.

### What other solutions have you considered?

The localization works without this feature, but this helps users avoid the need to run `kustomize localize`, then `kustomize build` themselves to check.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by rayandas** [comment]
Apologise for my recent inactivity, as I had to attend to some personal matters over the past couple of weeks. I'm now back and will continuing the implementation from where I left off last time.

**Comment by ncapps** [comment]
I haven't had time to making meaningful progress on this issue. I am unassigning myself in case someone else would like to pick it up.

/unassign

**Comment by sanaasy** [comment]
this issue has been completed!

**Comment by stormqueen1990** [comment]
This has been done as part of #5544.

/close
