### ISSUE TITLE
Document CLI section of Reference

### ISSUE THREAD

**Issue by annasong20** [kubernetes-sigs/kustomize#5278]
This is a sub-task of #4338.

Fill in the [CLI section under Reference](https://github.com/kubernetes-sigs/kustomize/blob/master/site/content/en/docs/Reference/kustomize_cli.md) in our internal [`site` directory](https://github.com/kubernetes-sigs/kustomize/tree/master/site). This involves migrating existing `Commands` content on the [`SIG CLI` site](https://kubectl.docs.kubernetes.io/references/kustomize/cmd/), as documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1Aaal0Ou10xeDkh_COWkg_r00R0I-Il_t5G2ad6W3jWc/edit#gid=0) and filling in any gaps you see. Note also the [Notes](https://docs.google.com/document/d/1galldpW27fSyKr9JAdKcCHVJ2qEa40Mng1jTop7xong/edit?pli=1#heading=h.jh4o5c89dw5) on the Docs project.

Note the other documentation issue #5279 for the Reference section. Note also the structural changes to the Reference section in #5247. This is only my attempt to mimic the [Kubernetes doc](https://kubernetes.io/docs/reference/kubectl/) and is by no means authoritative. You can use the Kubernetes site as reference or choose a cleaner layout of preference. Solely as a nice to have, I'd be curious to see how we could automate this.

**Comment by ncapps** [comment]
PR is ready for review: https://github.com/kubernetes-sigs/kustomize/pull/5304
