### ISSUE TITLE
Where is darwin arm64 binary?

### ISSUE THREAD

**Issue by yuyuvn** [kubernetes-sigs/kustomize#5310]
### What happened?

In kustomize v5.0.x, there is darwin_arm64 build binary in release assets.
But is dispeare from v5.1.x

### What did you expect to happen?

darwin_arm64 build is included in release assets

### How can we reproduce it (as minimally and precisely as possible)?

none

### Kustomize version

5.1.1

### Operating system

None

**Comment by natasha41575** [comment]
See https://github.com/kubernetes-sigs/kustomize/issues/5220
