### ISSUE TITLE
Deprecate ImageTagTransformer legacy filter

### ISSUE THREAD

**Issue by annasong20** [kubernetes-sigs/kustomize#5325]
The `ImageTagTransformer` backing the Kustomize `images` field is currently backed by 2 filters. We should deprecate the [`legacy filter`](https://github.com/kubernetes-sigs/kustomize/blob/kustomize/v5.1.1/plugin/builtin/imagetagtransformer/ImageTagTransformer.go#L31). #4814 motivated this issue.

I've noticed the following differences between the non-legacy and legacy filters. The deprecation assignee should investigate the two more thoroughly to ensure that the legacy filter deprecation doesn't have unintended consequences.
* The legacy filter applies to all fields named [`containers` and `initContainers`](https://github.com/kubernetes-sigs/kustomize/blob/master/api/filters/imagetag/legacy.go#L43) regardless of field path. Users can workaround this by specifying [`FieldSpecs`](https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/imagetagtransformer/ImageTagTransformer.go#L38) for the non-legacy filter.
* The legacy filter behaves the same regardless of whether the user invokes the image tag transformer via the Kustomize `images` or `transformers` field. The non-legacy requires users to pass in `FieldSpecs` when invoked via the `transformers` field.

As a result of the subpar UX in the 2nd bullet, #4404 blocks the legacy filter's deprecation.

**Comment by natasha41575** [comment]
If someone wants this to move forward more quickly, you can start by taking a look at the blocking issue https://github.com/kubernetes-sigs/kustomize/issues/4404. It is currently assigned to someone, but AFAIK they haven't started it yet.
