### ISSUE TITLE
Kustomize version is always devel, but should be v5.x.x

### ISSUE THREAD

**Issue by denist-huma** [kubernetes-sigs/kustomize#5339]
### What happened?

```sh
$ /home/denis/huma/compose-operator/bin/kustomize version
(devel)
```

I have a part of Makefile to download kustomize and check that it is of recent v5, and I want a semver out of `kustomize version` call.

```sh
## Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
KUSTOMIZE_VERSION ?= v5.1.0

KUSTOMIZE ?= $(LOCALBIN)/kustomize
.PHONY: kustomize
kustomize: $(KUSTOMIZE) ## Download kustomize locally if necessary. If wrong version is installed, it will be removed before downloading.
$(KUSTOMIZE): $(LOCALBIN)
	@if test -x $(LOCALBIN)/kustomize && ! $(LOCALBIN)/kustomize version | grep -q $(KUSTOMIZE_VERSION); then \
		echo "$(LOCALBIN)/kustomize version is not expected $(KUSTOMIZE_VERSION). Removing it before installing."; \
		rm -rf $(LOCALBIN)/kustomize; \
	fi
	test -s $(LOCALBIN)/kustomize || GOBIN=$(LOCALBIN) GO111MODULE=on go install sigs.k8s.io/kustomize/kustomize/v5@$(KUSTOMIZE_VERSION)
```

### What did you expect to happen?

```sh
$ /home/denis/huma/compose-operator/bin/kustomize version
v5.1.0
```

### How can we reproduce it (as minimally and precisely as possible)?

```sh
$ kustomize version
(devel)
```

### Kustomize version

v5.1.0

### Operating system

Linux

**Comment by sarab97** [comment]
Seems like the go build of kustomize isnt getting tagged with version. But brew installation does have proper tag of version

**Comment by sarab97** [comment]
Will need to look into how to pass version when building with go. Otherwise commit id will be added in place of version.
/triage accepted

**Comment by varshaprasad96** [comment]
This is how we do in some of the operator-framework projects. Adding info here in case it helps in fixing the issue:

The [buildinfo](https://github.com/kubernetes-sigs/kustomize/blob/ded76df3af04dce787a0e484c9cebd8de404f8d0/api/provenance/provenance.go#L53) returns debug.Module (https://cs.opensource.google/go/go/+/refs/tags/go1.21.1:src/runtime/debug/mod.go;l=62), which contains all the dependencies of the build. We search for latest tag for our module (eg: https://github.com/operator-framework/helm-operator-plugins/blob/d00d0092fe5c2a7776a678b7dcee4085cbccfe01/internal/version/version.go#L67), it would be [sigs.k8s.io/kustomize/kustomize](http://sigs.k8s.io/kustomize/kustomize) in our case, and I assume it would give us the tag with which we add could `+dirty` (or any other better name `+local`). So no dependency on git, we just get the tag from go's build info.
