### ISSUE TITLE
Version 5.0.0 breaks referencing a remote repo containing git LFS files

### ISSUE THREAD

**Issue by LoicFerrot** [kubernetes-sigs/kustomize#5355]
### What happened?

When running `kustomize build` with a version above or equal `v5.0.0` and referencing a remote repo, I get a `Smudge error: Error downloading path/to/lfs/file`. (see below for the complete error).

The same error arises with kustomize `v5.1.1`, `v5.0.0`, but not `v4.5.7`.

#### Workaround
Setting `GIT_LFS_SKIP_SMUDGE=1`, like `GIT_LFS_SKIP_SMUDGE=1 kustomize build` solves the issue for `v5.1.1` and `v5.0.0`, (if you don't need the LFS resources, obviously).

### What did you expect to happen?

`kustomize build` with version `>=5.0.0` does not throw an error, and builds the manifests.

### How can we reproduce it (as minimally and precisely as possible)?

All the following target formats lead to the same output.
```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/my-org/my-repo/k8s?ref=lf-test
- git@github.com:my-org/my-repo/k8s?ref=lf-test
- ssh://git@github.com/my-org/my-repo/k8s?ref=lf-test
- git::https://github.com/my-org/my-repo/k8s?ref=lf-test  # + additional warning
```
Other info:
- The git LFS (large file storage) file is not referenced by the `kustomization.yaml` on the remote
- Cloning the repo with `git clone` works normally
- Removing the LFS file causing the error just shifts the error to another LFS file
- Removing ALL the LFS files from the repo makes the problem disappear
- `git version 2.40.0`, `git-lfs/3.0.2 (GitHub; linux amd64; go 1.18.1)` (same behavior with `git-lfs/3.4.0`)

### Expected output

```yaml
# some K8s manifests
```

### Actual output

```
Error: accumulating resources: accumulation err='accumulating resources from 'https://github.com/my-org/my-repo/k8s?ref=lf-test': URL is a git repository': failed to run '/usr/bin/git checkout FETCH_HEAD': Downloading path/to/lfs/file (28 MB)
Error downloading object: path/to/lfs/file (0e6f029): Smudge error: Error downloading path/to/lfs/file (0e6f029a3e8782ecbf2e93967f77ea5ec9f8ec6d3165509874cfa576368232cb): batch request: missing protocol: ""

Errors logged to '/tmp/kustomize-3047604471/.git/lfs/logs/20231002T165139.490132154.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: path/to/lfs/file: smudge filter lfs failed
: exit status 128
```

### Kustomize version

5.0.0

### Operating system

Linux

**Comment by sarab97** [comment]
Missing origin in git caused this issue. PR #5353 fixes this issue. 
@LoicFerrot you can check this with the latest master code.
Closing for now.
/close

**Comment by LoicFerrot** [comment]
@sarab97 I can confirm, the issue disappeared when building from the source and using the master branch.
I will wait for the next release, thank you!
