### ISSUE TITLE
Latest releases missing darwin-arm64

### ISSUE THREAD

**Issue by samrocketman** [kubernetes-sigs/kustomize#5359]
### What happened?

Old releases https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.3

Contain AMD64 and ARM64 for both Mac and Linux.

### What did you expect to happen?

Current release
https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.1.1

missing some binaries; namely MacOS ARM64

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Expected output

N/A

### Actual output

N/A

### Kustomize version

5.1.1

### Operating system

MacOS

**Comment by sarab97** [comment]
This issue is already covered in #5220 and is closed. The new release process will fix this.
/close

**Comment by samrocketman** [comment]
I've asked for an ETA here (to circle back to this closed issue; I'll followup in the other issue from now on)

https://github.com/kubernetes-sigs/kustomize/issues/5220#issuecomment-1758293774
