### ISSUE TITLE
Archive format changed

### ISSUE THREAD

**Issue by VivaLaPanda** [kubernetes-sigs/kustomize#5396]
### What happened?

Was it intentional for the archive format to change with the latest release? It broke out builds (because the output is now in `output/kustomize` instead of the root. We can adjust our builds if needed, but wanted to make sure this was intentional before doing so.

### What did you expect to happen?

Archive unpacks to `output/kustomize` instead of `kustomize`

### How can we reproduce it (as minimally and precisely as possible)?

Download the archive, open it up, look at the directory

### Kustomize version

5.2.0

### Operating system

Linux

**Comment by j-chao** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/5397 might fix this?

**Comment by gabrielcho** [comment]
Can confirm this change broke pipelines on my end when installing Kustomize through [install_kustomize.sh](https://github.com/kubernetes-sigs/kustomize/blob/master/hack/install_kustomize.sh)
I get:  `cp: cannot stat './kustomize': No such file or directory`  as a result of this format change.

**Comment by j-chao** [comment]
@gabrielcho 
FYI, you can mitigate this by explicitly passing a version for install_kustomize.sh:
ie: `./install_kustomize.sh v5.1.0`

**Comment by natasha41575** [comment]
We have a fix in progress and will fix as soon as possible, in the meantime if you rely on the output format, it is advised to use the previous kustomize version.

**Comment by natasha41575** [comment]
Resolved
