### ISSUE TITLE
Kustomize logo is sketchy on kustomize.io top banner... and where can i find the logo svg ?

### ISSUE THREAD

**Issue by stockersky** [kubernetes-sigs/kustomize#5399]
### What happened?

Kustomize logo on the kustomize.io banner looks sketchy.

<img width="173" alt="image" src="https://github.com/kubernetes-sigs/kustomize/assets/22478549/53841bdd-65a3-48f8-97b7-bc3d1539e99d">

Looks like the last character is truncated...
Seems like this logo is displayed from this source : https://kustomize.io/images/main_spritesheet.svg

But my main question is : **where can I find some Kustomize logos SVG files ?** 
I am looking for it for diagram s& docs.
I could not find it here : https://github.com/kubernetes-sigs/kustomize.
Any idea where to find those logos, please :) ?

### What did you expect to happen?

- Kustomize logo could display properly. 
- Kustomize logo(s) could be available either on the website, either on the github repo.

### How can we reproduce it (as minimally and precisely as possible)?

go to kustomize.io

### Kustomize version

last one of course

### Operating system

MacOS

**Comment by natasha41575** [comment]
We didn't create the kustomize.io website and are still working on trying to change it, so I don't know where the image is from. Closing as this isn't really an issue with kustomize.

I am curious why you need it?

**Comment by stockersky** [comment]
@natasha41575 : I am looking for Kustomize logos/icons in svg or png format for those tasks :
- I am writing an article on a blog about Kustomize and I'd like to add some figures/images to make it more attractive to readers
- I am also creating diagrams : Kubernetes github provides icons sets but the Kustomize icon/logo is not part of it.

Do you have any idea where to find the Kustomize logo/icon (SVG, png), please ? That would be really helpful !

**Comment by stockersky** [comment]
Well, actually, this one looks quite right : https://www.pngegg.com/en/png-vencp/download

**Comment by olivergondza** [comment]
@natasha41575, The logo can be nicely extracted from that SVG, I would happily do that and contribute it back to the project. But, (and I am completely ignorant of the kustomize project history), what is the license of https://kustomize.io/images/main_spritesheet.svg?

Can its derived worked be distributed under a free license? Does the community even want to keep on using this imagery? Thanks!

**Comment by olivergondza** [comment]
@koba1t, can you please advise? Thanks!

**Comment by koba1t** [comment]
@olivergondza 
I believe we don't have a control of that site.
You can find site data on below repo.
https://github.com/replicatedcom/kustomize-www

**Comment by olivergondza** [comment]
@koba1t, thanks for pointing to that repo!

@breezybaldwin, I see you have contributed the kustomize.io logo there in https://github.com/replicatedcom/kustomize-www/commit/bd0e32448b5ec45e45ed40d771385cae4a0e4d2e. Is there any better source of the kustomize logo alone? I see it is under Apache License 2 in the repo. Thanks!

**Comment by olivergondza** [comment]
@breezybaldwin, gentle ping

**Comment by olivergondza** [comment]
To close the loop on the usage of the kustomize.io logo, with the digest of the legal recommendation given.

Until we can reliably track the creator / owner of the original logo and get them to approve its OSS usage, it has to be taken as a copyrighted material.

Presenting this on the cli-sig meeting (2025-10-01), it was decided not to use this design, but work with the community to find a new one instead.
