### ISSUE TITLE
Releases >=5.2.0 missing checksums.txt

### ISSUE THREAD

**Issue by kennethredler** [kubernetes-sigs/kustomize#5403]
### What happened?

[Release 5.1.1](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.1.1) and before included `checksums.txt` in release artifacts.

The 5.2.0/1 releases are missing `checksums.txt`.

### What did you expect to happen?

Release should include a file with checksums of the binaries.

### How can we reproduce it (as minimally and precisely as possible)?

Look at 5.2.0/1 GitHub release.

### Expected output

Checksum txt

### Actual output

<file-absent>

### Kustomize version

5.2.0/1

### Operating system

Linux

**Comment by kennethredler** [comment]
![Screenshot_20231019-231519](https://github.com/kubernetes-sigs/kustomize/assets/22832065/a6f4c6cd-7a08-4a9b-a125-27c1b231cbfe)
![Screenshot_20231019-231442](https://github.com/kubernetes-sigs/kustomize/assets/22832065/444a60fa-857c-4df2-b850-e805a514fa02)

**Comment by MPV** [comment]
For example, ArgoCD makes use of these files for verifying new versions of Kustomize, as per:
- https://github.com/argoproj/argo-cd/blob/973565e194c094d163d2fd0873364d0e36951806/hack/installers/checksums/add-kustomize-checksums.sh#L7

For example in PRs such as:
- https://github.com/argoproj/argo-cd/pull/15703

**Comment by MPV** [comment]
Judging by the diff in:
- https://github.com/kubernetes-sigs/kustomize/pull/5239

...it seems to have caused this (FYI @koba1t).

**Comment by natasha41575** [comment]
@koba1t Could you look into adding a checksums.txt to the assets created by the release process? The manual steps required to create this are in the description of this PR here: https://github.com/argoproj/argo-cd/pull/16054. I think we can probably put it in a script that we run during the release.

/assign @koba1t

**Comment by koba1t** [comment]
@natasha41575 @kennethredler 
Sorry, I missed that when I wrote the release scripts.
I'll fix it soon.

**Comment by kennethredler** [comment]
Excellent. Thank you!

**Comment by natasha41575** [comment]
FYI to those tracking this issue, I have manually added a checksums.txt to kustomize 5.2.1.
