### ISSUE TITLE
Documentation: Kubernetes kustomize documentation references Hashicorp URL format, which is outdated

### ISSUE THREAD

**Issue by smp4** [kubernetes-sigs/kustomize#5460]
### What happened?

The current Kubernetes documentation for [kustomization resources](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/) directs users to the Hashicrop go-getter URL format as the source of truth for how to specify remote resources.

However, according to the documentation in this repository, [kustomize - remoteBuild.md](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md), hashicorp go-getter URL format is now a legacy format for Kustomize resource definitions in kustomization.yaml files.

Moreover, the [Kubernetes documentation](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/) doesn't make any mention of most of the *very* useful information at [remoteBuild.md](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md).

As an example, I had trouble trying to install ArgoCD from their [ha/install.yaml](https://github.com/argoproj/argo-cd/blob/master/manifests/ha/install.yaml), listing the github URL and repo directory path to the yaml file, until reading [remoteBuildmd](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md) and realising that only a raw GitHub URL will work. I do not see a mention of requiring raw GitHub URLs for remote files.

I am filing this as a bug rather than feature request because it seems to need a fix, rather than an addition.

### What did you expect to happen?

The information at [remoteBuild.md](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md) should be available in the Kubernetes documentation at [kustomization resources](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/resource/).

### How can we reproduce it (as minimally and precisely as possible)?

compare the docs in this repo to the docs hosted at kubernetes.io.

### Kustomize version

v5.0.1 in kubectl 1.27. 

### Operating system

Linux

**Comment by smp4** [comment]
I would add that when using the following URL format:

```yaml
# kustomize.yaml
...
resources:
- https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml
```

the error I would receive from kustomize was:

```bash
...
error: accumulating resources: accumulation err='accumulating resources from '../../base': '/tmp/local-git-repo/bootstrap/base' must resolve to a file': recursed accumulation of path '/tmp/local-git-repo/bootstrap/base': accumulating resources: accumulating resources from 'https://github.com/argoproj/argo-cd/blob/master/manifests/ha/install.yaml': MalformedYAMLError: yaml: line 195: mapping values are not allowed in this context in File: https://github.com/argoproj/argo-cd/blob/master/manifests/ha/install.yaml
```

I'm new to kubernetes and it was not at all clear for the first couple of hours of debugging that `mapping values are note allowed in this context` had anything to do with an incorrect URL specification. Perhaps the error messages could be cleaned up a little?

Kustomize has been a great tool otherwise so far :)

**Comment by koba1t** [comment]
Thanks for reporting this problem with the documents.
I think the code of resources was updated below PR, but that document wasn't updated.
https://github.com/kubernetes-sigs/kustomize/pull/4030

This kustomize repo does not manage that document. 
https://github.com/kubernetes-sigs/cli-experimental/blob/a8847ee7bf57590c7905817859c13db17d0d5893/site/content/en/references/kustomize/kustomization/resource/_index.md#L26-L33
Feel free to assign this issue to you if you think you want to fix it.

And the error message problem while loading the remote files has already been opened here.
If you want to do anything, please feel free to comment below.
https://github.com/kubernetes-sigs/kustomize/issues/4788

/triage accept
/kind documentation
/label good-first-issue
/help

**Comment by devppratik** [comment]
I can work on this
/assign

**Comment by ashnehete** [comment]
Since the current assignee hasn't created a PR in more than 6 months
/assign
