### ISSUE TITLE
Unexpected json-patch dependency version

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/kustomize#5474]
In https://github.com/kubernetes-sigs/kustomize/pull/5197, a dep on `gopkg.in/evanphx/json-patch.v5` was added. This linked https://github.com/kubernetes/kubernetes/pull/118384 as rationale, which added a dep on `github.com/evanphx/json-patch/v5`. Later, https://github.com/kubernetes/kubernetes/pull/120327 reverted the #118384.

There are two concerns:
* If the reason to bump to v5 was to follow k/k, then given k/k reverted the change this may need to be re-evaluated
* `gopkg.in/evanphx/json-patch.v5` is used instead of `github.com/evanphx/json-patch/v5`, which differs from the rest of the kubernetes ecosystem and results in duplicate imports. 

cc @skitt

**Comment by skitt** [comment]
I agree #5197 should be reverted. Regarding the latter point, gopkg.in is the documented import, so I think that’s what should be used.
