### ISSUE TITLE
Kustomize raise error "argument list too long" with large yaml structure 

### ISSUE THREAD

**Issue by serngawy** [kubernetes-sigs/kustomize#5480]
### What happened?

We have a kustomize plugin that we use to generate CRs [siteConfig-kustomize-plugin](https://github.com/serngawy/cnf-features-deploy/tree/largeSC/ztp/siteconfig-generator-kustomize-plugin) . With large SiteConfig CR definition similar to the one defined [here](https://github.com/serngawy/cnf-features-deploy/blob/largeSC/ztp/siteconfig-generator-kustomize-plugin/testSiteConfig/large-siteconfig.yaml) executing command `$ kustomize build --enable-alpha-plugins ./` return error as below 
```
/usr/bin/kustomize build --enable-alpha-plugins ./
Error: failure in plugin configured via /tmp/kust-plugin-config-2157113498; fork/exec kustomize/plugin/ran.openshift.io/v1/siteconfig/SiteConfig: argument list too long: fork/exec kustomize/plugin/ran.openshift.io/v1/siteconfig/SiteConfig: argument list too long
make: *** [Makefile:32: test] Error 1

```
While executing the plugin binary alone with the same yaml file it works and generate the expected output as [here](https://github.com/serngawy/cnf-features-deploy/tree/largeSC/ztp/siteconfig-generator) 
```
$ make build
$ ./siteconfig-generator -manifestPath ../source-crs/extra-manifest  large-siteConfig.yaml
```

Is there a limitation for the yaml structure that kustomize can process in terms; number of line OR bytes size ?

### What did you expect to happen?

We expect the generated output from the SiteCoinfig kustomize plugin through kustomization.yaml should be equal to the output [here](https://github.com/serngawy/cnf-features-deploy/blob/largeSC/ztp/siteconfig-generator/out.txt)

### How can we reproduce it (as minimally and precisely as possible)?

First we need to build the siteConfig kustomize plugin following the steps [here](https://github.com/serngawy/cnf-features-deploy/tree/largeSC/ztp/siteconfig-generator-kustomize-plugin)

```
$ git clone https://github.com/serngawy/cnf-features-deploy.git -b largeSC
$ cd cnf-features-deploy/ztp/siteconfig-generator-kustomize-plugin/
# Then you can run make test it will download kutomize , build the plugin and run $ kustomize build for our example file.
$ make test
```
The kustomization.yaml as [below](https://github.com/serngawy/cnf-features-deploy/blob/largeSC/ztp/siteconfig-generator-kustomize-plugin/kustomization.yaml)

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
 - testSiteConfig/large-siteconfig.yaml
```

### Expected output

Expected output should be similar to [that](https://github.com/serngawy/cnf-features-deploy/blob/largeSC/ztp/siteconfig-generator/out.txt)

### Actual output

```
/usr/bin/kustomize build --enable-alpha-plugins ./
Error: failure in plugin configured via /tmp/kust-plugin-config-2157113498; fork/exec kustomize/plugin/ran.openshift.io/v1/siteconfig/SiteConfig: argument list too long: fork/exec kustomize/plugin/ran.openshift.io/v1/siteconfig/SiteConfig: argument list too long
```

### Kustomize version

v5.2.1

### Operating system

Linux

**Comment by andreaskaris** [comment]
The problem here is that kustomize exceeds the max length for args/environment variables that the Linux kernel permits:
```
akaris@workstation siteconfig-generator-kustomize-plugin (largeSC)]$ dlv exec /home/akaris/development/go/bin/kustomize -- build --enable-alpha-plugins ./
Type 'help' for list of commands.
(dlv) b execplugin.go:176
Breakpoint 1 set at 0xe32164 for sigs.k8s.io/kustomize/api/internal/plugins/execplugin.(*ExecPlugin).invokePlugin() /home/akaris/development/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.16.0/internal/plugins/execplugin/execplugin.go:176
(dlv) c
(...)
(dlv) print p.path
"kustomize/plugin/ran.openshift.io/v1/siteconfig/SiteConfig"
(dlv) print f.Name()
Command failed: can not call optimized function os.(*File).Name when regabi is in use
(dlv) print p.args
[]string len: 0, cap: 0, nil
(dlv) print input
[]uint8 len: 0, cap: 0, nil
(dlv) config max-array-values 128
(dlv) print cmd.Env
[]string len: 75, cap: 168, [
(...)
	"KUSTOMIZE_PLUGIN_CONFIG_STRING=apiVersion: ran.openshift.io/v1\nkind: SiteConfig\nmetadata:\n  name: ex-ocp1\n  namespace: ex-ocp1\nspec:\n  baseDomain: example.com\n  clusterImageSetNameRef: ocp-4.12\n  clusters:\n  - additionalNTPSources:\n    - 10.10.11.50\n    apiVIP: 10.10.10.5\n    clusterLabels:\n      common: true\n      group: ex1\n      sites: ex-ocp1\n    clusterName: ex-ocp1\n    clusterNetwork:\n    - cidr: 10.10.11.0/14\n      hostPrefix: 31\n    ingressVIP: 10.10.10.6\n    networkType: OVNKubernetes\n    nodes:\n    - bmcAddress: redfish-virtualmedia://10.10.10.25/redfish/v1/Systems/1\n      bmcCredentialsName:\n        name: ex-ocp1-secret\n      bootMACAddress: 00:00:00:00:00:80\n      bootMode: UEFI\n      hostName: master01\n      nodeNetwork:\n        config:\n          dns-resolver:\n            config:\n              server:\n              - 10.10.11.10\n              - 10.10.11.11\n          interfaces:\n          - ipv4:\n              enabled: false\n            ipv6:\n              enabled: false\n  ...+134106 more",
```

Here's the manpage for execve:
```
man execve
(...)
   Limits on size of arguments and environment
       Most UNIX implementations impose some limit on the total size of the command-line argument (argv) and environment (envp) strings that may be passed to a new program.  POSIX.1 al‐
       lows an implementation to advertise this limit using the ARG_MAX constant (either defined in <limits.h> or available at run time using the call sysconf(_SC_ARG_MAX)).

       Before  Linux 2.6.23, the memory used to store the environment and argument strings was limited to 32 pages (defined by the kernel constant MAX_ARG_PAGES).  On architectures with
       a 4-kB page size, this yields a maximum size of 128 kB.

       On Linux 2.6.23 and later, most architectures support a size limit derived from the soft RLIMIT_STACK resource limit (see getrlimit(2)) that is in force at the time  of  the  ex‐
       ecve()  call.  (Architectures with no memory management unit are excepted: they maintain the limit that was in effect before Linux 2.6.23.)  This change allows programs to have a
       much larger argument and/or environment list.  For these architectures, the total size is limited to 1/4 of the allowed stack size.  (Imposing the 1/4-limit ensures that the  new
       program  always  has some stack space.)  Additionally, the total size is limited to 3/4 of the value of the kernel constant _STK_LIM (8 MiB).  Since Linux 2.6.25, the kernel also
       places a floor of 32 pages on this size limit, so that, even when RLIMIT_STACK is set very low, applications are guaranteed to have at least  as  much  argument  and  environment
       space as was provided by Linux 2.6.22 and earlier.  (This guarantee was not provided in Linux 2.6.23 and 2.6.24.)  Additionally, the limit per string is 32 pages (the kernel con‐
       stant MAX_ARG_STRLEN), and the maximum number of strings is 0x7FFFFFFF.
(...)
```

However, that's actually not the problem that we're running into, but the per argument max size. Sorry for the link behind a paywall:
https://access.redhat.com/solutions/21118

What that KCS says is this:
```
[akaris@workstation test-argument-size]$ cat /usr/include/linux/binfmts.h
(...)
/*
 * These are the maximum length and maximum number of strings passed to the
 * execve() system call.  MAX_ARG_STRLEN is essentially random but serves to
 * prevent the kernel from being unduly impacted by misaddressed pointers.
 * MAX_ARG_STRINGS is chosen to fit in a signed 32-bit integer.
 */
#define MAX_ARG_STRLEN (PAGE_SIZE * 32)
#define MAX_ARG_STRINGS 0x7FFFFFFF
(...)
```

```
[akaris@workstation test-argument-size]$ echo "$(getconf PAGE_SIZE) * 32" | bc
131072
```

Easy to try out with:
```
[akaris@workstation test-argument-size]$ cat main.go
package main

import (
	"fmt"
	"math/rand"
	"os"
	"os/exec"
)

var letterRunes = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")

func RandStringRunes(n int) string {
	b := make([]rune, n)
	for i := range b {
		b[i] = letterRunes[rand.Intn(len(letterRunes))]
	}
	return string(b)
}

func getEnv(str string) []string {
	env := os.Environ()
	toAppend := "KUSTOMIZE_PLUGIN_CONFIG_STRING=" + string(str)
	fmt.Printf("env var to append, length is %d\n", len(toAppend))
	env = append(env,
		toAppend,
	)
	return env
}

func main() {
	cmd := exec.Command("env")
	cmd.Env = getEnv(RandStringRunes(131041))

	_, err := cmd.Output()
	// fmt.Println("result: ", string(result))
	fmt.Println("err: ", err)
}
```

```
[akaris@workstation test-argument-size]$ go run .
env var to append, length is 131072
err:  fork/exec /usr/bin/env: argument list too long
```

Whereas it passes with one character less

**Comment by andreaskaris** [comment]
For some weird reason, kustomize passes the configuration both via the path of a temp file:
https://github.com/kubernetes-sigs/kustomize/blob/f72db33d5e7b38794e3b9e5be07de30cdb651ab6/api/internal/plugins/execplugin/execplugin.go#L157

And via env variable `KUSTOMIZE_PLUGIN_CONFIG_STRING`:
https://github.com/kubernetes-sigs/kustomize/blob/f72db33d5e7b38794e3b9e5be07de30cdb651ab6/api/internal/plugins/execplugin/execplugin.go#L188

I have strong reason to believe that the latter is a legacy way of calling plugins (both a github search and a google search don't really yield a whole lot of results):
https://github.com/search?q=%22KUSTOMIZE_PLUGIN_CONFIG_STRING%22&type=code&p=2

**Comment by andreaskaris** [comment]
According to the documentation, https://kubectl.docs.kubernetes.io/guides/extending_kustomize/exec_plugins/
`An exec plugin is any executable that accepts a single argument on its command line - the name of a YAML file containing its configuration (the file name provided in the kustomization file).`
Therefore, I'm even more sure that the env var is something legacy and most likely shouldn't be used by plugins

**Comment by serngawy** [comment]
Thanks Andreas for following.  The fix is working I tested locally but just to clarify do we will still have a limit for much larger files ? you mentioned "kustomize exceeds the max length for args/environment variables that the Linux kernel permits" OR that was just to explain ?

**Comment by andreaskaris** [comment]
That was just to explain. kustomize fails because the environment variable `KUSTOMIZE_PLUGIN_CONFIG_STRING=<VALUE>`  (the total combined string of env var name + equals sign + env var content) exceeds PAGE_SIZE * 32 = 131072 characters.

That environment variable is filled with the entire config string (which in the case of SiteConfig is quite long). However, according to the documentation, and that's also what the SiteConfig plugin is using, the config string (yaml) should be passed via a reference to a temporary file.

My fix simply drops the environment variable when it's too long. I actually think that the env variable serves no purpose nowadays. However, I decided to keep it if it's smaller for backwards compatibility. I'll check with the kustomize maintainers if it can be dropped altogether or if there's a better fix for this.

Be it as it may, the offender is clearly the long env variable

**Comment by koba1t** [comment]
Hi @serngawy @andreaskaris 
Looks like this code using the [deprecated legacy exec plugin](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/exec_plugins/).
We don't continue to support this plugin system. Could you consider moving [krm exec function](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/exec_krm_functions/) that is currently developing now?

**Comment by andreaskaris** [comment]
Hi koba1t! thanks for your feadback - as far as I understood (correct me if I'm wrong), the exec function is currently in alpha state and it does thus not have a stable API. I totally get that the legacy plugin is deprecated, but isn't it a lot to ask people to move to an alpha feature instead?

**Comment by andreaskaris** [comment]
I also posted an IMO reasonable bug fix here: https://github.com/kubernetes-sigs/kustomize/pull/5510 :-)

**Comment by andreaskaris** [comment]
Just to clarify what I mean: while kustomize is in this "weird in-between" state of having a deprecated exec feature and an alpha exec feature, IMO it makes sense to fix the broken deprecated feature especially considering that it's a small fix

**Comment by koba1t** [comment]
Hi @andreaskaris 

> while kustomize is in this "weird in-between" state of having a deprecated exec feature and an alpha exec feature

If I remember correctly, all kustomize plugins are still in alpha status, and it's not weird. Just the legacy exec plugin can't go out of the alpha phase and is deprecated in the alpha stage.
https://kubectl.docs.kubernetes.io/guides/extending_kustomize/

**Comment by koba1t** [comment]
Varsha was also commented on it. We need more comprehensive tests if we accept your PR.
https://github.com/kubernetes-sigs/kustomize/pull/5510

The reason we do not remove deprecated features is for the sake of the users who currently use them. We need to be certain your PR doesn't break the current function.

**Comment by andreaskaris** [comment]
Ah it makes sense then given that they're all in alpha. Thanks for the clarification! I'll add some tests as soon as I get a free moment, thanks!
