### ISSUE TITLE
Postprocessing output with regex replace

### ISSUE THREAD

**Issue by tomaszkiewicz** [kubernetes-sigs/kustomize#549]
Hi, 

I love kustomize, it makes life soooo easy :)

I'd like to suggest some new feature that will be especially useful in some cases like:

1. Certificate templating
2. Ingress templating

In above cases we have to change almost everything in patch files in order to just replace domain name for certificate or ingress.

3. ConfigMap templating

At the moment it's not possible to change config map data, you have to provide some new config map in overlay to alter the one from base.

The suggested feature works like that:

1. You add postprocessing entries in kustomize.yaml:

```
bases:
- ...
resources:
- ...
outputPostprocessing:
- regex:
    match: "xxxxxx"
    replace: "yyyyy"
- regex:
    match: "z??z"
    replace: "aaa"
```

2. kustomize generates output as always
3. After output is built and before it is written (https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/commands/build/build.go line 146) we start processing regexp matches and do all replacements
4. The output is written to file or stdout

I know that it's possible to use sed on kustomize output but it'd be nice to have a "swiss army knife" for all k8s-related things instead of additional scripts or makefiles :)

In the future this outputPostprocessing can be easily extended with another processors like "env vars replace" etc.

If you like the idea I can implement such feature and send PR for that.

Best regards

Łukasz Tomaszkiewicz

**Comment by Liujingfang1** [comment]
Postprocessing is not a bad idea, but I have a lot of concern on replace regex. It will lead kustomize towards templating, which we want to avoid. @monopole WDYT?

**Comment by tomaszkiewicz** [comment]
I know it's a little "hacky" but it's also very powerful and elastic and you can handle many cases with it.

E.g. I have a repository with "curated" addons for k8s that are adjusted to work with each other: https://github.com/tomaszkiewicz/k8s-addons/ 
I use this repo to deploy multiple k8s envs as well as an example for trainings etc.

I'd like to provide some adjusted templates for things like ingresses or certificates:
https://github.com/tomaszkiewicz/k8s-addons/blob/master/k8s-1.11.2/k8s-dashboard/ingress.yaml
https://github.com/tomaszkiewicz/k8s-addons/blob/master/k8s-1.11.2/k8s-dashboard/certificate.yaml

At the moment I have to deploy patches for ingresses which contains more than 10 lines to just patch hostname, which is also not very intuitive for people that use the examples or write some additional scripts/makefiles just to make some simple replacements.

I imagine kustomize.yaml as a single unit of adjustment, where you can specify all adjustments per environment and simply run kustomize build (or kubectl as I saw your PR for kubectl) and have all changes generated and ready to deploy.

I think that regex matches in many cases are simpler to understand than complex json or strategic merge patches.

As the alternative I can suggest and implement some generic way to process output like executing specified commands and piping the output - this will not include regexes directly in kustomize but will enable users to specify adjustments using external tools like sed or envsubst.

BTW: do you have any "vision document" for kustomize, so I can adjust my future PR to be aligned with the vision?

**Comment by tomaszkiewicz** [comment]
Yes, you can probably make it work, but it doesn't allow you to things like replacement in config maps. Also I see that you have to explicite specify (I've only got quick look at the code of vars) which paths are affected :(

**Comment by curtisallen** [comment]
👍 on this suggestion, however, I'm not tied to regex I'd love to have a simple find and replace post processor.

**Comment by Liujingfang1** [comment]
We don't plan to support regex replacing in kustomize. See the detailed explanation in [Unstructured edits](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#unstructured-edits).
