### ISSUE TITLE
nameprefix as a flag to build command

### ISSUE THREAD

**Issue by vshiva** [kubernetes-sigs/kustomize#551]
This is a feature request to support specifying of the name prefix flag as an input while invoking build command. This can be handy when using the same overlay to orchestrate a blue / green deployment. 

` build deployments/overlays/staging --name-prefix blue`

**Comment by Liujingfang1** [comment]
Kustomize doesn't allow build time flags that will affect the resources. https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#build-time-side-effects-from-cli-args-or-env-variables
