### ISSUE TITLE
Support for patch files hosted in git repos

### ISSUE THREAD

**Issue by jesse-fabric** [kubernetes-sigs/kustomize#5517]
It seems as though the `patches` stanza does not support yaml files stored in git repos currently. It would be very helpful if it did, similar to the `resources` stanza.

In `resources`, you can do something similar to the following to load up kustomizations from a git repo:

```
resources:
- ssh://git@github.com/org/repo/path/to/kustomization/dir
```

The above works for private repos too, as long as you have valid SSH creds locally. It would be great if we could do something similar for `patches`, such as:

```
patches:
- path: ssh://git@github.com/org/repo/path/to/patch.yaml
```

The use-case for my organization is we have a gitops repo that stores patch yaml files with the current image versions, and we would like to be able to use the remote git files from that repo as patches to ensure we stay in sync with what's current when running `kustomize`.

Any guidance or feedback would be super helpful, thanks!

**Comment by grubitwo** [comment]
It would be great if we could do something like that too similar for `replacements`, such as:

```
replacements:
- path: ssh://git@github.com/org/repo/path/to/replacements.yaml
```
