### ISSUE TITLE
Do not add namespace to cluster-scoped CRD objects

### ISSUE THREAD

**Issue by mgoodness** [kubernetes-sigs/kustomize#552]
[CRDs can be namespace- or cluster-scoped](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition) by setting `spec.scope` to `Namespaced` or `Cluster`. If a CRD is cluster-scoped, kustomize should not add `metadata.namespace` to objects of that kind.

Note that while there's no harm in adding `metadata.namespace` to a cluster-scoped CRD object (Kubernetes ignores it), it does show up as a "diff" in GitOps-style CD systems like Argo.

**Comment by jessesuen** [comment]
This is an interesting problem. Kustomize does not currently talk to a Kubernetes cluster and has no facility to determine whether or not it is appropriate to add namespace to a custom resource object. I'm not sure how kustomize can decide this unless it sees the custom resource definition as part of the deployed manifests.

If kustomize is unable to determine whether or not to omit namespace during manifest generation, then diffing tools like Argo CD will probably need add some special case logic for `metadata.namespace` to basically ignore mismatches on empty string vs. non-empty strings.

**Comment by mgoodness** [comment]
Good point - it hadn't occurred to me that kustomize can't look into a CRD's spec to determine its scope. Hopefully transformer configurations can be extended to support not adding a namespace to cluster-scoped resources.

E.g.
```yaml
namespace:
- path: metadata/namespace
  create: false
  kind: ClusterIssuer
```

**Comment by primeroz** [comment]
Any update on this ? 

We are having the same problem with a cluster scoped CRD

**Comment by jbrette** [comment]
@mgoodness @primeroz @jessesuen 

Please have a look at:
- [KEP: Kustomize FieldSpec skip ](https://github.com/kubernetes/enhancements/pull/1232)
- [PR: Skip kustomize transformers for paths](https://github.com/kubernetes-sigs/kustomize/pull/1491)
- The PR seems to address the issue as demonstrated [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0552)

**Comment by redbaron** [comment]
can someone reopen this issue? it is still relevant

**Comment by psalaberria002** [comment]
We just hit this issue. Any reason why it is not opened?

**Comment by gkarthiks** [comment]
Hi, any updates on this scenario? I am facing this with the custer-scoped CR with Kustomize and ArgoCD, being kustomize adding the namespaces to it, the ArgoCD is not ignoring the namespace on that but throwing an error.
