### ISSUE TITLE
kustomize install from binaries with curl no longer working 

### ISSUE THREAD

**Issue by johnrozen** [kubernetes-sigs/kustomize#5557]
### What happened?

curl "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
no longer works as of 2/27/24
returns
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104

### What did you expect to happen?

install kustomize in the working directory

### How can we reproduce it (as minimally and precisely as possible)?

curl "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

### Expected output

```yaml

```

### Actual output

```yaml

```

### Kustomize version

?

### Operating system

None

**Comment by koba1t** [comment]
Hi @johnrozen 
That command is working on my computer.

So, I think that problem is caused by your computer or something.
Please check your environment.

/triage out-of-scope
