### ISSUE TITLE
`testcase-multibases-nonconflict` fails if RoleBinding is a ClusterRoleBinding

### ISSUE THREAD

**Issue by vreon** [kubernetes-sigs/kustomize#557]
To reproduce the problem, change the RoleBinding to a ClusterRoleBinding in `pkg/commands/build/testdata/testcase-multibases-nonconflict/base/rolebinding.yaml`:

```
$ kustomize build combined
Error: Multiple matches for name noGroup_v1_ServiceAccount|noNamespace|b-:base-|serviceaccount|noSuffix:
  [noGroup_v1_ServiceAccount|noNamespace|a-:base-|serviceaccount|noSuffix noGroup_v1_ServiceAccount|noNamespace|b-:base-|serviceaccount|noSuffix]
```

**Comment by jcassee** [comment]
I have a similar problem, but with PersistentVolumeClaim:

https://github.com/jcassee/kustomize-conflict-issue

**Comment by looztra** [comment]
Same problem as @vreon with a `ServiceAccount` and a `ClusterRoleBinding`, test case files can be found at <https://github.com/looztra/kustomize-multibase-multiple-match-error>

**Comment by almariah** [comment]
@Liujingfang1 Any update about that issue. I have the same problem 

```
error: Multiple matches for name ~G_v1_ServiceAccount|ingress-gateway|~P|nginx-ingress-serviceaccount|-office:
  [~G_v1_ServiceAccount|ingress-gateway|~P|nginx-ingress-serviceaccount|-office ~G_v1_ServiceAccount|ingress-gateway|~P|nginx-ingress-serviceaccount|-private ~G_v1_ServiceAccount|ingress-gateway|~P|nginx-ingress-serviceaccount|-public]
```

**Comment by looztra** [comment]
I'm sorry but it doesn't fix my usecase showcased at https://github.com/looztra/kustomize-multibase-multiple-match-error

```bash
╰─» asdf global kustomize v2.0.3
╰─» kustomize build overlays/both/
Error: Multiple matches for name ~G_v1_ServiceAccount|apps-integration|~P|faros|~S:
  [~G_v1_ServiceAccount|apps-integration|~P|faros|~S ~G_v1_ServiceAccount|apps-demo|~P|faros|~S]

╰─» asdf global kustomize v2.1.0
╰─» kustomize build overlays/both/
Error: string case - multiple matches for ~G_v1_ServiceAccount|~X|faros:
  [~G_v1_ServiceAccount|apps-demo|faros
 ~G_v1_ServiceAccount|apps-integration|faros
]

╰─» asdf global kustomize v3.0.2
╰─» kustomize build overlays/both/
Error: string case - multiple matches for ~G_v1_ServiceAccount|~X|faros:
  [~G_v1_ServiceAccount|apps-demo|faros
 ~G_v1_ServiceAccount|apps-integration|faros
]

```

**Comment by Liujingfang1** [comment]
Released a new version 3.0.3 with the fix from #1344. @looztra Can you try with this release?

**Comment by looztra** [comment]
@Liujingfang1  I will. But I think the release tag is wrong (3.0.3 instead of v3.0.3) and breaks installers like `asdf` for instance

**Comment by looztra** [comment]
confirmed. This fixed my use case (also referenced in #1352 )

Thank you!

**Comment by jbrette** [comment]
@looztra @Liujingfang1 @jcassee @vreon @almariah I do believe this [PR]( https://github.com/kubernetes-sigs/kustomize/pull/1378) solve your issue. 

Have a look at the following test:
- [Issue 0557](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0557)
- [Issue 0557 c](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0557_c)

The PR #1344 is working fine as long as the cluster wide object are referring to other object (for instance ClusterRoleBinding referring to serviceaccounts). But the main different with the @jcassee  is that a clusterwide object (persistentvolume) was referred by non clusterwide.

**Comment by looztra** [comment]
I confirm that V3.0.3 fixed the problem in my use case

Le lun. 22 juil. 2019 à 05:43, Jerome Brette <notifications@github.com> a
écrit :
