### ISSUE TITLE
Handle nil input during transform

### ISSUE THREAD

**Issue by twz123** [kubernetes-sigs/kustomize#560]
When kustomizing manifests that specify nil objects that are subject to transformers, kustomize errors out with `Error: <nil> is not expected to be a primitive type`.

This happens for me if I try to kustomize certain pre-rendered helm charts from charts/stable using helm template. It seems that there are a few charts that e.g. specify `env` or `annotations` and so on via values.yaml. If leaving those values empty in the values, those fields get rendered "empty" as `env:` or `annotations:`. While it's debatable if that's good practice (in contrast to just skip those fields completely in the chart if they're empty), it seems that those manifests are happily accepted by the API server. Hence I'd like to be able to kustomize them as is.

Workaround is to use some dummy values in the chart's values, so that they're not empty anymore.

**Comment by monopole** [comment]
Which version of kustomize? 

Or rather - can you repo this with head?

**Comment by monopole** [comment]
Nvmd, see the problem.
