### ISSUE TITLE
Delete temp dir when using githubLoader

### ISSUE THREAD

**Issue by asm76** [kubernetes-sigs/kustomize#566]
1. `kustomize version`
 `Version: {KustomizeVersion:1.0.10 GitCommit:383b3e798b7042f8b7431f93e440fb85631890a3 BuildDate:2018-10-26T23:12:01Z GoOs:unknown GoArch:unknown}`

2. `ls -ld /tmp/kustomize-*`
`ls: cannot access '/tmp/kustomize-*': No such file or directory`

3. `kustomize build github.com/kubernetes-sigs/kustomize//examples/helloWorld | wc -l`
`63`

4. `ls -d /tmp/kustomize-*`
`/tmp/kustomize-226899135`

5. `kustomize build github.com/kubernetes-sigs/kustomize//examples/helloWorld | wc -l`
`63`

6. `ls -d /tmp/kustomize-*`
`/tmp/kustomize-226899135  /tmp/kustomize-453311822`

**Comment by monopole** [comment]
I'll fix this if its still a problem.

**Comment by monopole** [comment]
Looks like this was fixed in #570 (i did some refactoring, and touched the cleanup code path).

Thanks for the great bug report though.
