### ISSUE TITLE
Apply KRM functions in batches

### ISSUE THREAD

**Issue by Homulvas** [kubernetes-sigs/kustomize#5673]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Following the suggestion in https://github.com/kubernetes-sigs/kustomize/issues/5173 we have implemented our own resource transformers. While this generally works we have run into a performance issue where for a big enough target each transformer takes maybe a second or two to process. Now this alone wouldn't be that bad but each additional transformer impacts the runtime linearly. This leads to cases where the time spent applying the transformers is the majority of the whole build.

### Why is this needed?

Piping the complete input/output for each KRM function separately is inefficient and makes builds very slow for big enough targets. 

### Can you accomplish the motivating task without this feature, and if so, how?

One possible workaround is to have all transformations inside a single transformer file. However, this makes the transformers hard to use as you have to treat them with special care.

### What other solutions have you considered?

A workaround has been described above.

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by koba1t** [comment]
Hi @Homulvas 
Thanks for submitting the feature request.
I understand what your problem is.

I'm so sorry, but I can't understand what you think about `batches` at your request.

My guess is that your transformer takes a few minutes to start, and you want to process many yamls all at once. 
Isn't that right?

/triage needs-information

**Comment by koba1t** [comment]
Sorry, I didn't understand what you want now.
What do you think about the problem?

Do you care about the call overhead of a custom transformer?

I think the current custom transformer interface looks like can `batch` processing.
https://github.com/kubernetes-sigs/kustomize/blob/e3a7615ccb84506cee74e576d05e636aaa4542ad/kyaml/fn/framework/framework.go#L16-L58
