### ISSUE TITLE
Create a new release of Kustomize with the latest patch version of Go

### ISSUE THREAD

**Issue by louisjimenez** [kubernetes-sigs/kustomize#5731]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Can a new release of Kustomize with the latest patch version of Go be provided? Thank you!

### Why is this needed?

The last release and patch version is from nearly 2 months ago.

### Can you accomplish the motivating task without this feature, and if so, how?

n/a

### What other solutions have you considered?

n/a

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by louisjimenez** [comment]
Hello, friendly ping on this.

**Comment by koba1t** [comment]
@louisjimenez 
I created a new release of kustomize.
https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.4.3

```
kob@Yugos-MacBook-Air ~ % ./kustomize version
v5.4.3
kob@Yugos-MacBook-Air ~ % go version ./kustomize
./kustomize: go1.21.12
```

**Comment by louisjimenez** [comment]
Thank you!
