### ISSUE TITLE
Handling Authentication Errors in install_kustomize.sh`

### ISSUE THREAD

**Issue by viniciusdc** [kubernetes-sigs/kustomize#5755]
### What happened?

The install_kustomize.sh script is designed to download and install the kustomize binary. However, if a `GITHUB_TOKEN` is set in the environment but is invalid or expired, the script fails with authentication errors, such as Bad credentials. 

```
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}
```

Currently, the script attempts to authenticate with GitHub using the `GITHUB_TOKEN` but does not handle cases where this token is incorrect or invalid, leading to confusing error messages like:
```shell
Version v5.4.3 does not exist or is not available for linux/amd64.
```

If the support for the token is expected in the installation script, extending the validation to consider such errors sounds reasonable. I assume this extra block would be enough, at least to give the end user some guidance (mostly when inspecting CI logs):

```bash
# Check for authentication errors
if [[ $releases == *"Bad credentials"* ]]; then
  echo "Authentication failed: Invalid GITHUB_TOKEN. Please check or remove your token."
  exit 1
```
https://github.com/kubernetes-sigs/kustomize/blob/27d508fa039d9f5f03c6ae666114e4c138690c2f/hack/install_kustomize.sh#L144-L147

### What did you expect to happen?

The script should handle authentication errors gracefully and provide a clear message indicating that there is an issue with the `GITHUB_TOKEN`.

### How can we reproduce it (as minimally and precisely as possible)?

1. Set an invalid or expired `GITHUB_TOKEN` in your environment.
2. Run the [install_kustomize.sh](https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh) script locally passing a desired version: 
   - `bash install_kustomize.sh 5.4.3`
4. Observe the script's failure due to authentication errors from GitHub.

### Expected output

downloaded binary

### Actual output

```shell
Version v5.4.3 does not exist or is not available for linux/amd64.
```

### Kustomize version

5.4.3

### Operating system

Linux

**Comment by michelgokan** [comment]
Any solution for this @viniciusdc ? I get this error 99% of the time and it only works by seldomly by chance!
