### ISSUE TITLE
Patch an object in-place

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#587]
Is it possible to use kustomize to patch an object which is not one of the resources defined in kustomization.yaml?

For example, if I want to add an annotation to kube-system like.

```
kubectl patch ns kube-system -p '{"metadata": {"annotations": {"iam.amazonaws.com/allowed-roles": "[\"*\"]"}}}'
```

How could I do it in kustomize?

**Comment by Liujingfang1** [comment]
kustomize doesn't support that.

`kube-system` is special, but for other namespaces, you can manage them with annotations by kustomize.

**Comment by yujunz** [comment]
Thanks for the explanation.

**Comment by shokohsc** [comment]
@Liujingfang1 😭 but fair.



> kustomize doesn't support that.
> 
> `kube-system` is special, but for other namespaces, you can manage them with annotations by kustomize.

Please how one would (or should ?) patch say, coredns deployment cpu/memory requests and limits, if the tool used to deploy the cluster (kubespray) could not allow it at the time, said cluster was deployed ?
