### ISSUE TITLE
git ssh URLs no longer work

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes-sigs/kustomize#598]
`kustomize build git@github.com:fake/fake-repo` no longer works since https://github.com/kubernetes-sigs/kustomize/blob/29f03dfb55815e11766200d46f05edf787ab8e3f/pkg/loader/gitcloner.go#L73 forces `https` prefix. This used to work when using go-getter in 1.0.10 and is now broken in 1.0.11.

**Comment by Liujingfang1** [comment]
Same issue as #585
