### ISSUE TITLE
Merge custom configurations

### ISSUE THREAD

**Issue by brushmate** [kubernetes-sigs/kustomize#606]
As of kustomize 1.0.11 it is possible to add custom configurations in kustomization.yaml. Unfortunately I always have to configure all configuration keys even if I only want to change one of them. I wanted to add some `varReference`s and added this to my `kustomization.yaml`:

    configurations:
    - ../../config/varreference.yaml

With this configuration kustomize failed with `Error: fieldSpecs is not expected to be nil`. Adding all other configurations solved it:

    configurations:
    - ../../config/commonannotations.yaml
    - ../../config/commonlabels.yaml
    - ../../config/nameprefix.yaml
    - ../../config/namereference.yaml
    - ../../config/namespace.yaml
    - ../../config/varreference.yaml

I think it would be much more convenient to use the default configuration and merge all custom configurations (also from bases: #605) into it.

**Comment by monopole** [comment]
Will do.  This (if nothing else) will force a minor version change.
