### ISSUE TITLE
kustomize edit add base does not support remote bases

### ISSUE THREAD

**Issue by pst** [kubernetes-sigs/kustomize#611]
Trying to add a remote base like this: `$ kustomize edit add base 'https://storage.googleapis.com/dev.catalog.kubestack.com/postgresql-latest-clusterwide.txz'` fails with `Error: https://storage.googleapis.com/dev.catalog.kubestack.com/postgresql-latest-clusterwide.txz does not exist`.

Adding it to the bases manually, then running kustomize build works.

```
bases:
 - https://storage.googleapis.com/dev.catalog.kubestack.com/postgresql-latest-clusterwide.txz
```

**Comment by pst** [comment]
@Liujingfang1 @monopole I came back to this today and have a few questions to understand the direction you're taking and how and if there is room for what I'm trying to do. Which is basically building a catalog of curated remote bases.

Previously go-getter from Hashicorp was used and this is how I made the https/txz archive above work as remote bases. The issue was about the difference in adding a base manually vs. using `kustomize edit add base`, which did not allow remote bases because it was hardcoded to local paths only.

But looking at the code now trying to submit a PR to fix this it seems go-getter isn't used anymore. It also seems as if now, only git, and only if github, amazon or microsoft hosted is supported for remote bases? If I understand the loaders correctly.

Is this simply because you cleaned up the code base or because you have objections to supporting anything but git for remote bases?

**Comment by Liujingfang1** [comment]
> But looking at the code now trying to submit a PR to fix this it seems go-getter isn't used anymore. It also seems as if now, only git, and only if github, amazon or microsoft hosted is supported for remote bases? If I understand the loaders correctly.

Yes, only git repos are supported

> Is this simply because you cleaned up the code base or because you have objections to supporting anything but git for remote bases?

When used `go-getter`, it added >1000 files in /vendor directory. This blocked the Kustomize integration in Kubectl. So we decided to remove it and use our own implementation.

**Comment by pst** [comment]
Thanks for the update. I'm trying a "vendoring" of bases approach for now, like here for example: https://www.kubestack.com/catalog/prometheus Will close this issue for now.

**Comment by pst** [comment]
I'm looking forward to https://github.com/kubernetes-sigs/kustomize/pull/684 to improve the adding the base step.
