### ISSUE TITLE
Make clusterLevelKinds configurable

### ISSUE THREAD

**Issue by twz123** [kubernetes-sigs/kustomize#617]
Currently, clusterLevelKinds are hardcoded.

https://github.com/kubernetes-sigs/kustomize/blob/8f701a00417a812558a7b785e8354957afa469ae/pkg/gvk/gvk.go#L143-L149

Since they influence how transformers work (e.g. for resolving namereferences), it would be good to have some means of configuring those, too. Consider name references between Cluster-Level CRD kinds and any other kind.

**Comment by Liujingfang1** [comment]
Similar issue #552

**Comment by gacopl** [comment]
please add priorityclass to this wonderful hardcode... I'm sure there are a lot more missed from this list
