### ISSUE TITLE
Respect ordering in kustomization resources array

### ISSUE THREAD

**Issue by yanc0** [kubernetes-sigs/kustomize#65]
It can be extremely useful for namespace creation. Namespace have to be created before all objects you want to place inside. Example:

```shell
$ cat kustomization.yaml 
commonLabels:
  app: hello
resources:
- namespace.yaml
- cm.yaml

$ kustomize build .

apiVersion: v1
data:
  hello.txt: |
    "hello"
kind: ConfigMap
metadata:
  labels:
    app: hello
  name: hello-config-ck54t29m9k
  namespace: hello
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: hello
  name: hello

$ kustomize build . | kubectl apply -f -      
namespace "hello" created
Error from server (NotFound): error when creating "STDIN": namespaces "hello" not found
```

Namespace manifest is situated at the end of stdout, which cause that error message.

**Comment by Liujingfang1** [comment]
I think the way `kustomize build` processing resources does respect ordering since internally it appends a resource to an array. The ordering is lost when the output is encoded into yaml. 
https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/resmap/resmap.go#L46
```
func (m ResMap) EncodeAsYaml() ([]byte, error) {
	ids := []resource.ResId{}
	for gvkn := range m {
		ids = append(ids, gvkn)
	}
	sort.Sort(IdSlice(ids))
```
@monopole @mengqiy Do you remember why we added a sorting here?

**Comment by monopole** [comment]
Sort added for some semblance of stability.  Without the sort of keys, the output order of resources would be essentially random.

We could modify the sort to put namespaces first.  To preserve general order as specified in the kustomization files, across all the mapping and merging, would require a more powerful approach, e.g. upon first read establish some kind of order index, and use that index when spitting things back out.

**Comment by tkellen** [comment]
If you're going to special case namespaces, maybe it would make more sense to leave the sorting as-is and have usage of the `namespace` key (from #54) automatically generate the namespace as the first resource in the output of `kustomize build`?

PS: Hello! I am a new user of kustomize and I'd just like to say that I am *so thankful* this project is being created. Every template-based solution I've worked with seems like madness.

**Comment by Liujingfang1** [comment]
Usually the resources contain a `Namespace` object, kustomize doesn't create it again.
I will put the namespaces first, then other objects.

**Comment by SleepyBrett** [comment]
This is not an ideal solution. Currently I have another object that as a side effect creates namespaces and in the same kustomize stack I would like to have some objects that I need in those namespaces I know will be created. The object that creates those namespace is not itself a namespace object.

**Comment by schlichtanders** [comment]
I am also stumbling upon this. Thought that kustomize respects ordering, however a webhook gets created too late and my deploy fails because of this.

It would be great if kustomize simply respects the given ordering of resources so that developers have control over it.

**Comment by SleepyBrett** [comment]
two years later and this is STILL A HUGE PROBLEM.
