### ISSUE TITLE
Correct versioning?

### ISSUE THREAD

**Issue by leominov** [kubernetes-sigs/kustomize#656]
I understand that project under active development, but have not clue – why you does't support semantic versioning?

```
Given a version number MAJOR.MINOR.PATCH, increment the:
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

There is some problem with it?

New release with bunch of bug fixes doesn't support previously released Patch because specs are changed. Is it sounds good?

**Comment by monopole** [comment]
:+1: Acknowledged.  

We've been incrementing PATCH only, when we should have incremented MINOR a few times.

When we finally remove some things currently marked deprecated, that will trigger a MAJOR increment.

**Comment by monopole** [comment]
Closing as in Yes We Will Do This :)

**Comment by leominov** [comment]
Yeah!)
