### ISSUE TITLE
Variable reference support is incomplete

### ISSUE THREAD

**Issue by mxey** [kubernetes-sigs/kustomize#67]
The variable reference feature added in #52 does not support expanding in `args`, only `command`. Also it only considers Jobs and StatefulSets so far. 

https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/transformers/refvars.go#L20

I considered sending a PR for adding `args` support because I tripped up on it, but I figured there should maybe be a more generic solution rather than listing lots of resource kinds that have containers in them.

**Comment by Liujingfang1** [comment]
@mxey Variable reference support should work for container command and args by design. Thank you for reporting this issue. Feel free to send a PR. We also considered a more generic solution. Before it is available, we can keep using hard coded `pathConfigs`.
