### ISSUE TITLE
Image transforms should support transformer configs

### ISSUE THREAD

**Issue by EronWright** [kubernetes-sigs/kustomize#686]
The kustomize tool is presently hardcoded as to where an image reference may appear, e.g. container spec.   Other resource types (incl CRDs) may contain an image reference. 

The transformer config concept makes it possible to extend the locations where kustomize would look to apply an image transformation. 

Related to #402.

**Comment by Liujingfang1** [comment]
@EronWright The way `Kustomize` performs image transformation is to look for `containers` and `initContainers` and update images in them. If other resource types use PodTemplate, image transformer should support them as well.

**Comment by ringerc** [comment]
This is now supported using image transformer configs; see https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/images/README.md
