### ISSUE TITLE
Kustomize Office Hours

### ISSUE THREAD

**Issue by sethpollack** [kubernetes-sigs/kustomize#723]
It would be really great to have some time to chat about the roadmap, design decisions, etc...

**Comment by monopole** [comment]
Hi, thanks.  

At least one of the main contributors has been showing up at [sig-cli meetings](https://github.com/kubernetes/community/tree/master/sig-cli) since the project started, and sometimes there's kustomize talk.  Lets try that first since it's already a commitment.

**Comment by sethpollack** [comment]
Ok, I'll try and join those meetings. Thanks!
