### ISSUE TITLE
[bug] Generated configmaps appear on console

### ISSUE THREAD

**Issue by sascha-coenen** [kubernetes-sigs/kustomize#729]
Since I updated to kustomize 1.0.11, it prints generated configmaps to the console even though I pipe the output to kubectl.

For instance, I run the following command in bash:
>> kustomize build eks/druid/0.13/indexer/middleman  |  kubectl apply -f -

The output of kustomize should become the input for kubectl.
Yet, when I submit the above command, I first see the generated configmaps emitted to the console followed by the deployment status that kubectl logs out.

It would be great it this could be fixed and released soon, as this is impacting the user experience when working with kustomize a lot.

**Comment by Liujingfang1** [comment]
This should have been fixed in version 2.
