### ISSUE TITLE
Release a patch for v1.0.11 with log noise reduced

### ISSUE THREAD

**Issue by wmedlar** [kubernetes-sigs/kustomize#739]
Merging generated resources produces a wealth of logging noise, making it very difficult to debug especially when used with scripts. It would be wonderful if you could release a patched version of v1.0.11 with the [fix from master](https://github.com/kubernetes-sigs/kustomize/commit/77b44f570a77073662f069b09b8bd8636027c580) cherry-picked in.

**Comment by monopole** [comment]
Sorry, we we're just too bogged down.

[2.0.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/v2.0.0) is out now so please try that.

**Comment by wmedlar** [comment]
I'm afraid we can't upgrade until we come up with a workaround for the removal of secretGenerator.commands.
