### ISSUE TITLE
Support kustomization.yml vs yaml for Windows

### ISSUE THREAD

**Issue by vDMG** [kubernetes-sigs/kustomize#765]
Hello,

Besides the merged commit #502 in windows we still have an error. Kustomize is only looking for kustomization.**yaml** file even if a kustomization.**yml** file exist.

**Kustomize:** 
```
kustomize_1.0.11_windows_amd64.exe version
Version: {KustomizeVersion:1.0.11 GitCommit:8f701a00417a812558a7b785e8354957afa469ae BuildDate:2018-12-04T18:42:24Z GoOs:unknown GoArch:unknown}
```

**OS:** Windows 10 Entreprise

**Error message:** kustomize_1.0.11_windows_amd64.exe build .\overlays\preprod\
Error: open [...]\overlays\preprod\kustomization.yaml: The system cannot find the file specified.

It was necessary to rename my kustomization.yml file in kustomization.yaml to generate my manifests.

Any idea why the fixe doesn't works ?

**Comment by Liujingfang1** [comment]
Can you try kustomize from the head? We updated the code for dealing with different kustomization file names in #721.

**Comment by Liujingfang1** [comment]
Version 2.0.0 is released. It supports `kustomization.yml`.
