### ISSUE TITLE
"Load from path ../<etc> failed: security, file '...' is not in or below '...'

### ISSUE THREAD

**Issue by hach-que** [kubernetes-sigs/kustomize#766]
I just upgraded to the latest HEAD to get support for `files` in `secretGenerator` and it looks like there's some "security" mechanism that's been added that breaks our workload:

```
FATA[0011] exiting dev mode because first run failed: deploy failed: reading manifests: kustomize build: Running [kustomize build services/kubernetes/dev]: stdout , stderr: Error: rawResources failed to read Resources: Load from path ../admin.yaml failed: security; file '../admin.yaml' is not in or below '/home/.../services/kubernetes/dev'
```

How do I bypass this?

**Comment by hach-que** [comment]
Moving kustomization.yaml to the top-level directory of the repository isn't an option either, since we have different kustomization files for different environments, and the filename is as far as I can tell, hard-coded.

**Comment by Liujingfang1** [comment]
@hach-que The files in `secretGenerators` need to be relative paths in the kustomization directory or subdirectory. `../admin.yaml` goes outside the kustomization directory. This is blocked in Kustomize 2.0.0.

**Comment by hach-que** [comment]
@Liujingfang1 2.0.0 blocks relative paths everywhere as far as I can tell.

The issue is that `kustomization.yaml` is hard-coded, so how can I have two different kustomization targets when they need to draw on the contents of the Git repository? I can't use relative parent paths anymore.

Imagine I have a directory structure like this (right now):

```
- dev
  - some_dev_specific_file.yaml
  - kustomization.yaml
- prod
  - some_prod_specific_file.yaml
  - kustomization.yaml
- some_files_used_by_both.yaml
```

With relative paths blocked, your proposal is now to put the kustomization.yaml file in the parent directory, like this:

```
- dev
  - some_dev_specific_file.yaml
- prod
  - some_prod_specific_file.yaml
- some_files_used_by_both.yaml
- kustomization.yaml (prod)
- kustomization.yaml (dev????? filename clash!)
```

Except that doesn't work because you can't have two files both named `kustomization.yaml` in the top level directory. There doesn't appear to be any way to override the path or name of the `kustomization.yaml` file either when invoking `kustomize`.

**Comment by mohnishkodnani** [comment]
Kubebuilder framework by default produces the following directory structure. 
default
- kustomization.yaml
- patch_XYZ.yaml
rbac:
- rbac_role.yaml
manager: 
- manager.yaml

In the default kustomization, rbac and manager folders are mentioned as resources. 

Now if  I have to create overlays I create
overlays/production
- kustomization.yaml 

Here I put base as the default. 
But then it complains that rbac/rbac_role.yaml is not under default

**Comment by Liujingfang1** [comment]
@hach-que  You can put the files used by both to base and include that base in both dev and prod.
```
- base
   - some_files_used_by_both.yaml
   - kustomization.yaml
- dev
  - some_dev_specific_file.yaml
  - kustomization.yaml
- prod
  - some_prod_specific_file.yaml
  - kustomization.yaml
```

@mohnishkodnani I'm not sure I understand your problem. The base `default` has resources `rbac` and `managers`, but the overlay doesn't work. Is that the problem you mean?

**Comment by adeshmukh-quizlet** [comment]
@Liujingfang1 I ran into the same issue after upgrading to `kustomize 2.x`. I was able to fix the problem by following your tip! To summarize the change I needed to make:

I have the following folder structure:
```
$ tree -d
.
├── base
└── overlays
    ├── staging
    └── production
```

To fix the problem:
1. I added file `base/kustomization.yaml` with:
```yaml
resources:
- my-service.yaml
```
2. Updated `overlays/staging/kustomization.yaml` and `overlays/production/kustomization.yaml` to replace:
```yaml
resources:
- ../../base/my-service.yaml
-patches:
...
```
... with ...
```yaml
bases:
- ../../base/
patchesStrategicMerge:
...
```

**Comment by jgonera** [comment]
Could you elaborate what was the motivation for blocking paths that are above given `kustomization.yaml`?

**Comment by bryanlarsen** [comment]
This is really annoying.

I had to go from 

- base
   - file1.yaml
   - file2.yaml
   - file3.yaml
- dev
  - some_dev_specific_file.yaml
  - kustomization.yaml
- prod
  - some_prod_specific_file.yaml
  - kustomization.yaml

to 

- base1
   - file1.yaml
   - kustomization.yaml
- base2
   - file2.yaml
   - kustomization.yaml
- base3
   - file3.yaml
   - kustomization.yaml
- dev
  - some_dev_specific_file.yaml
  - kustomization.yaml
- prod
  - some_prod_specific_file.yaml
  - kustomization.yaml

What I really want:

- base
  - file1.yaml
  - file2.yaml
  - file3.yaml
dev-kustomization.yaml
prod-kustomization.yaml

**Comment by jcassee** [comment]
> You can put the files used by both to base and include that base in both dev and prod.

I believe it is not possible to reuse common patches in this way?

**Comment by shanna** [comment]
My use case is I have a few secrets used by applications not run in kubernetes (mobile, desktop and IOT) and I'd rather not have multiple copies or a makefile to shuffle files around before kustomize is run.

```
secrets/
    ...
platform/
  ios/
    ...
  android/
    ...
  k8s/
    base/
    next/
    production/
```

**Comment by monopole** [comment]
One can share patches in HEAD:

https://github.com/kubernetes-sigs/kustomize/blob/master/docs/FAQ.md#security-file-foo-is-not-in-or-below-bar

The code is in, and will be in release 2.1, coming in a week or two.  Need to write docs and a add some more tests for other stuff.

**Comment by develar** [comment]
> hared by using bases

Ok, but secretGenerator it is not resource, it is part of `kustomization.yaml`. It seems that `kubectl create secret generic tls --from-file=./certs/tls.cert --from-file=./certs/tls.key` is the only solution now :( (security doesn't matter — it is used for local, since no doubt for production secrets created in another way).

**Comment by akhy** [comment]
cannot share patches anymore 😢

**Comment by pavel1269** [comment]
> cannot share patches anymore 😢
> 
> edit: it works with `--load_restrictor` flag, but somehow the flag doesn't work when using `kubectl kustomize`

The flag is in kustomize v3 according to this: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/FAQ.md#security-file-foo-is-not-in-or-below-bar
But kubectl contains kustomize v2 according to this: https://github.com/kubernetes-sigs/kustomize#kubectl-integration

**Comment by andredasilvapinto** [comment]
What if you want to be able to easily remove one of the resources from one of the overlays without affecting the other overlays sharing the same base?

Kustomize doesn't allow patches to remove resources defined in base and apparently doesn't allow for inclusion of common resources outside the overlay directory, so it seems to be basically forcing duplication of YAML files?

**Comment by kim-sardine** [comment]
> > cannot share patches anymore cry
> > edit: it works with `--load_restrictor` flag, but somehow the flag doesn't work when using `kubectl kustomize`
> 
> The flag is in kustomize v3 according to this: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/FAQ.md#security-file-foo-is-not-in-or-below-bar
> But kubectl contains kustomize v2 according to this: https://github.com/kubernetes-sigs/kustomize#kubectl-integration

Thanks @pavel1269 

with v3.9.2, `kustomize build --load_restrictor none PATH` works!

**Comment by sramanujan** [comment]
> Resources should be shared by using bases - they can be located anywhere.
> 
This is literally false. They cannot be located anywhere, which is the fundamental reason why users are complaining. 

Two poorly designed features (probably not so poor when individually used) have broken the idea of using Kustomize to `customise` configuration: 1) an inaccurate recursion detection - only checks for whether a folder is accessible by a yaml and not if it is actually linked, and 2) requiring all files to be under or on the same level of a yaml

This functionality is most likely breaking security by having users change their directory structures to have entire projects under one folder which is inside a repository.

**Comment by nguyenlamlll** [comment]
I cannot understand this Kustomize team. (I'm sorry). So, everyone is complaining and explain that the relative-path block is very counterintuitive and the team just comes passing by casually, saying "NO" with little useful explanation? 
Huh..?

**Comment by solarmosaic-kflorence** [comment]
https://kubectl.docs.kubernetes.io/faq/kustomize/#security-file-foo-is-not-in-or-below-bar

**Comment by flickerfly** [comment]
Did Kustomize 4 remove the load_restrictor option entirely? 

```bash 
$ kustomize version
{Version:kustomize/v4.1.2 GitCommit:a5914abad89e0b18129eaf1acc784f9fe7d21439 BuildDate:2021-04-15T20:38:06Z GoOs:windows GoArch:amd64}
$ kustomize build --load_restrictor none variant/default
Error: unknown flag: --load_restrictor
```

**Comment by Zallin** [comment]
@flickerfly the following works for v4.0.5 
`kustomize build --load-restrictor LoadRestrictionsNone`

**Comment by swapnild2111** [comment]
It's `--load_restrictor` <-- note the underscore sign

**Comment by solarmosaic-kflorence** [comment]
@swapnild2111 that is for version 3. In version 4 it is `--load-restrictor`. See https://github.com/kubernetes-sigs/kustomize/issues/3746
