### ISSUE TITLE
Binaries missing for the 2.0.0 release

### ISSUE THREAD

**Issue by tanordheim** [kubernetes-sigs/kustomize#767]
Hi there! I couldn't help noticing that it seems like the 2.0.0 release has gone out the door (judging from the docs and git tags) - but it seems there are no binary releases available for it under the Releases page for the project.

Is this intended, or has it just not happened yet? I noticed the release was pretty fresh, so.

Thanks!

**Comment by Liujingfang1** [comment]
@tanordheim Can you check it again? There should be 3 binaries for different operating systems.

**Comment by monopole** [comment]
Just downloaded and ran the [linux version](https://github.com/kubernetes-sigs/kustomize/releases/download/v2.0.0/kustomize_2.0.0_linux_amd64) (see links [here](https://github.com/kubernetes-sigs/kustomize/releases/tag/v2.0.0))

```
$ ./kustomize_2.0.0_linux_amd64 version
Version: {KustomizeVersion:2.0.0 GitCommit:0184d5b69700607a1b9280f303152e2959bc19e7 BuildDate:2019-02-05T20:46:24Z GoOs:unknown GoArch:unknown}
```

seems ok.

Please reopen if this you can reproduce a problem.
