### ISSUE TITLE
BUG - $patch: delete with namespace in kustomization.yaml

### ISSUE THREAD

**Issue by michalschott** [kubernetes-sigs/kustomize#768]
kustomize 1.0.11

```
➜  cat kustomization.yaml
---
bases:
  - ../../../apps/clamav

namespace: clamav

patches:
  - clamav-pdb.yaml
```

```
➜  cat clamav-pdb.yaml
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: clamav
$patch: delete
```

```
➜  kustomize build .
---
metadata:
  namespace: mgmt
```

**Comment by Liujingfang1** [comment]
@michalschott What do you expect as the output?

**Comment by michalschott** [comment]
I'd expect empty output. My intention in that case was to completely remove object defined in `clamav-pdb.yaml` patch - it is empty w/o using `namespace` in `kustomisation.yaml`.

**Comment by Liujingfang1** [comment]
@michalschott This is an interesting example. If I remove the `namespace` from kustomization.yaml, the output will be empty. Let me dig into this and see what causes the `namespace` being in the output.
