### ISSUE TITLE
add note on availability inside kubectl

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/kustomize#772]
Can we add a note to the beginning of readme saying:

> kustomize is now available on kubectl v1.X and can be used through "kubectl apply" command by specifying a directory that has a kustomization.yaml.

I'm actually not sure if it's in kubectl already, but came here to find out that.

**Comment by monopole** [comment]
Not there yet.  Will do when/if it happens.  Will leave this open as a placeholder, thanks
