### ISSUE TITLE
Support envsubst style variable expansion

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/kustomize#775]
Kustomize currently supports simple $(VAR_NAME) expansion. What about using envsubst style more flexible options? 

https://github.com/drone/envsubst works well in my experience.

**Comment by monopole** [comment]
Thanks, we should probably have a faq.

Kustomize supports a structured form of $VAR substitution - it's not template style.

envsubst is called out as something we're currently eschewing:
https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#unstructured-edits

One is of course free to do this sort of thing in a pipe/
