### ISSUE TITLE
kustomize build shows error in v2.0.0 release

### ISSUE THREAD

**Issue by kfoozminus** [kubernetes-sigs/kustomize#776]
`kustomize build <dir>` shows the following error -

```
Error: rawResources failed to read Resources: Load from path ../rbac/rbac_role.yaml failed: security; file '../rbac/rbac_role.yaml' is not in or below '/home/<...>/go/src/github.com/<...>/kubebuilder-sample/config/default'
```

Rolled back to previous release and it works.

**Comment by kfoozminus** [comment]
kustomization.yaml contains -

```
resources:                                                                                                                                                                                                     
 - ../rbac/rbac_role.yaml                                                                                                                                                                                       
 - ../rbac/rbac_role_binding.yaml                                                                                                                                                                               
 - ../manager/manager.yaml                                                                                                                                                                                      
 - ../rbac/auth_proxy_service.yaml                                                                                                                                                                              
 - ../rbac/auth_proxy_role.yaml                                                                                                                                                                                 
 - ../rbac/auth_proxy_role_binding.yaml 
```

tried moving `manager` and `rbac` folder to the directory where kustomization.yaml is. and changing to -

```
resources:                                                                                                                                                                                                     
 - /rbac/rbac_role.yaml                                                                                                                                                                                       
 - /rbac/rbac_role_binding.yaml                                                                                                                                                                               
 - /manager/manager.yaml                                                                                                                                                                                      
 - /rbac/auth_proxy_service.yaml                                                                                                                                                                              
 - /rbac/auth_proxy_role.yaml                                                                                                                                                                                 
 - /rbac/auth_proxy_role_binding.yaml 
```

also tried changing them to absolute path like `/home/.../rbac/..`

still gives same error.

**Comment by mgoodness** [comment]
Probably due to #700.

In kustomize v2 `kustomization.yaml` can only refer to files in the same directory as itself, or in subdirectories. Only `bases` can refer to outside paths.

```
bases:
- ../base <- ok

resources:
- deployment.yaml <- ok
- foo/service.yaml <- ok
- ../pdb.yaml <- not ok
- ../baz/rbac.yaml <- not ok
```

**Comment by max-sixty** [comment]
For people coming back to this error — `bases` works but is deprecated.

For maintainers — what's the recommended way for people to handle this case?

**Comment by Shell32-Natsu** [comment]
`bases` is replaced by `resources`. Just use `resources` like `bases`.

**Comment by max-sixty** [comment]
What about this case?

> In kustomize v2 `kustomization.yaml` can only refer to files in the same directory as itself, or in subdirectories. Only `bases` can refer to outside paths.

**Comment by Shell32-Natsu** [comment]
In kustomize V2, `bases` is used. In V3, `resources` is used to refer bases. Although you can still use `bases` in V3 but as you said it's deprecated.

**Comment by max-sixty** [comment]
I think we're talking past each other. Does `resources` allow referring to outside paths? If not, what should people use?

**Comment by Shell32-Natsu** [comment]
Since `resources` has the same capability with `bases` so if `bases` can access then `resources` can. That's what I was talking about.

**Comment by Shell32-Natsu** [comment]
Will try to check it on my side

**Comment by Shell32-Natsu** [comment]
OK I made a mistake. You can refer an outside `base` directory but not a single YAML file.

**Comment by max-sixty** [comment]
Converting outside references to directories is very reasonable! Thanks

**Comment by mamiu** [comment]
@Shell32-Natsu 

I still don't get it. `bases` are deprecated. As you can see [here](https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/bases/).

> The `bases` field was deprecated in v2.1.0

And `resources` don't support referring to a parent directory or file. If I refer to a directory like so:

```yaml
resources:
  - ../../resources
```

I get the error:

```
Error: rawResources failed to read Resources: Load from path ../../resources failed:
'../../resources' must be a file (got d='/<PATH TO MY PROJECT>/manifests/resources')
```

And if I refer to the `kustomization.yaml` in the `../../resources` directory...

```yaml
resources:
  - ../../resources/kustomization.yaml
```

... I get this error message:

```
Error: rawResources failed to read Resources: Load from path ../../resources/kustomization.yaml failed:
security; file '../../resources/kustomization.yaml' is not in or below '/<PATH TO MY PROJECT>/manifests/envs/dev'
```

So the question to the maintainers from @max-sixty:

> What's the recommended way for people to handle this case?

**Comment by mamiu** [comment]
As I said I'm using `kubectl kustomize` which still [seems to be kustomize v2.0.3](https://github.com/kubernetes-sigs/kustomize#kubectl-integration).

Since I'm using kustomize in a CI/CD pipeline I've now created a [custom image](https://github.com/mamiu/kube-deploy) that uses the latest version of kustomize. That solved the issue for me.

For others who're looking into that in the future: It still may take some time until the latest version of kustomize is included in kubectl (according to [this FAQ page](https://kubernetes-sigs.github.io/kustomize/faq/#kubectl-doesnt-have-the-latest-kustomize-when-will-it-be-updated)).

**Comment by webern** [comment]
I'm using `kubectl kustomize` as I expect customers to be. I'm not sure how to find the version of kustomize but assume it's close (i.e. v2.X.X, not v3) as the previous comment.

Where do I find the documentation for v2? I have written kustomization.yaml files that seem to work with v3 when I try `kustomize build` but which cannot be applied with `kubectl apply -k`. I'm not 100% sure its version differences causing the issue, but I'd like to follow the documentation for when customers would be expected to use (`kubectl apply -k`).

Thanks.
