### ISSUE TITLE
Document the kustomization.yaml spec

### ISSUE THREAD

**Issue by ant31** [kubernetes-sigs/kustomize#777]
I found only examples of the kustomization.yaml, it makes it complex to learn the format, especially since the example doesn't expose/explain all fields. 

Would it be possible to provide a spec doc similar to the kubernetes API reference?

For now the most useful resource I found is:
https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/types/kustomization.go

**Comment by monopole** [comment]
https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kustomization.yaml

It's linked from several places, but perhaps not enough.

Not fancy, but we try to keep it correct.  We could replace it, but someone would have to delete it and fix all the links to it and their surrounding text.

**Comment by ant31** [comment]
@monopole this isn't a spec but an example.
It is very useful, but not complete, I can find several example of fields that are missing. 
The example file doesn't have to be replaced. 
I am speaking of a spec like(openapi) :
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#pod-v1-core
or less fancy:
https://github.com/kubernetes-sigs/application#application-objects

It could be linked as a comment in the https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kustomization.yaml. It doesn't required to update the current documentations. 
```
# Example kustomization.yaml content.
#
# This file declares the customization provided by
# the kustomize program.
# 
# The complete spec reference can be viewed at: https://.....
```

**Comment by Liujingfang1** [comment]
We added a list of kustomize features on https://kubernetes.io/docs/concepts/overview/object-management-kubectl/kustomization/#kustomize-feature-list

**Comment by michaelbannister** [comment]
@Liujingfang1 an OpenAPI spec or a CRD for the `Kustomization` resource itself would still be really helpful – especially now IntelliJ's Kubernetes plugin can validate against custom resources if given a spec: https://plugins.jetbrains.com/plugin/10485-kubernetes

**Comment by shapirus** [comment]
This issue should be reopened.
