### ISSUE TITLE
secretGenerator to use Vault

### ISSUE THREAD

**Issue by gitirabassi** [kubernetes-sigs/kustomize#787]
The new secretGenerator uses: `LiteralSources `, `FileSources`, `EnvSource`.

I wonder if a `VaultSources` would be useful?
Using vault from Hashicorp as single source of truth for credentials without ever persisting them on disk unencrypted.

If this is approved I can provide a PR with some code implementing this

**Comment by monopole** [comment]
please consider using @sethpollack 's [secret generator plugin plan](https://groups.google.com/d/msg/kubernetes-sig-cli/MY6hjg2-J-0/bDfwF89SAwAJ)

We'll have some process (likely  just a PR) for graduating from plugin (which requires more download work for the user) to a 'builtin' secret generator.

The code change would be minimal given a plugin.

A plugin is just a Go package, so you go from loading it to importing it.  The plugin name would become a a reserved word in the secret generator stanza, a sibling to `goplugin`.
