### ISSUE TITLE
Make generated configmaps composable

### ISSUE THREAD

**Issue by sascha-coenen** [kubernetes-sigs/kustomize#79]
Using generated config maps (via configMapGenerator) seems to work only in simple base-overlay setups.
However, referencing a base that contains a generated config map fails in several scenarios:

given the following arrangement:
```
- base
  +- myapp
      +- mycomponent
           - kustomization.yaml
              - namePrefix "myapp-"
              - configMapGenerator constructs "mycomponent-config" with mode "create"
       +- mycomponent2
            ...
- overlay
  + - dev
       +- myapp
            +- mycomponent
                - kustomization.yaml
                   - bases: 
                      - ../../../../base/myapp/mycomponent 
                   - namePrefix "dev-"
                   - configMapGenerator merges additional config-key into "mycomponent-config" with mode "merge"
            +- mycomponent2
                 ...
            - kustomization.yaml
               - bases:
                  - mycomponent.yaml
                  - mycomponent2.yaml

```

If I run "kustomize build dev/myapp/mycomponent" all is good. 
Same for "kustomize build/dev/myapp/mycomponent2" - all good. 
When I run "kustomize build "dev/myapp" which points to the kustomization file that only declares the two subcomponents and does nothing else, I get the following exception:

> Error: No merge or replace is allowed for non existing gvkn types.GroupVersionKindName{GVK:schema.GroupVersionKind{Group:"", Version:"v1", Kind:"ConfigMap"}, Name:"mycomponent-config"}

Same error happens when trying to merge/replace a configmap from within an overlay, if that config map has been declared in a base as a merged configmap.
To explain it perhaps more simply: only a single merge/replace is possible via a configmap generator. After that, no other kustomization setup can refer to it anymore without causing an error.

**Comment by Liujingfang1** [comment]
This is totally not intentional. We need to fix it.
