### ISSUE TITLE
README steps for springboot example don't explain how to use kustomize with the sample contents

### ISSUE THREAD

**Issue by adeshmukh-quizlet** [kubernetes-sigs/kustomize#792]
# Summary
The README.md steps for the springboot example work perfectly fine. However they do not explain how to use kustomize with the contents of the springboot example. In particular, I was looking for an example that illustrates how to organize kustomization for multiple environments. The contents of the springboot example are exactly what I was looking for. But attempting to use kustomize with those files results in an error.

# Info
* `git --no-pager log -1 --pretty=format:%H`
```
e65b45f96964498c45d3b38b23d39c5893024a57
```
* `kustomize version`
```
Version: {KustomizeVersion:2.0.1 GitCommit:ce7e5ee2c30cc5856fea01fe423cf167f2a2d0c3 BuildDate:2019-02-08T00:57:04Z GoOs:unknown GoArch:unknown}
```

# Steps to reproduce
```bash
cd $(mktemp -d)
git clone git@github.com:kubernetes-sigs/kustomize.git
cd kustomize/examples/springboot

kustomize build ./overlays/production
```
Results in:
```
Error: couldn't make target for ../../base: No kustomization file found in /private/var/folders/14/_aslfskcm641/T/tmp.nUTItI4z/kustomize/examples/springboot/base. Kustomize supports the following kustomization files: kustomization.yaml, kustomization.yml, Kustomization
```

**Comment by Liujingfang1** [comment]
@adeshmukh-quizlet You can follow the steps in the README file to create those kustomization.yaml.
https://github.com/kubernetes-sigs/kustomize/blob/master/examples/springboot/README.md

**Comment by adeshmukh-quizlet** [comment]
@Liujingfang1 Thanks for taking a look at this issue and responding. Like I mentioned in my report, I am able to follow the steps mentioned in the README.md, but they do not correspond to the _content_ in that folder.

In particular, I'm looking for an example that shows how one can organize kustomization of the same base for multiple environments. i.e. say I have 2 environments **staging** and **production**. I would like to know how I could go about organizing the `kustomization.yaml` for these environments while referring to the same base.

It appears that the directory structure worked with `kustomize 1.x`, but due to the new security constraints with `kustomize 2.x`, the base reference outside the target directory does not work anymore.

**Comment by Liujingfang1** [comment]
I see. We'll add the complete layout for this example and make sure it works with 2.0.

**Comment by adeshmukh-quizlet** [comment]
FWIW, I was able to get my core use case of managing customizations per-environment per my comment on another issue: https://github.com/kubernetes-sigs/kustomize/issues/766#issuecomment-465348108

I was also able to get the springboot sample working by making a couple of changes to the files as illustrated in the attached patch file.

[kustomize-issue-792-patch.txt](https://github.com/kubernetes-sigs/kustomize/files/2886274/kustomize-issue-792-patch.txt)

**Comment by Liujingfang1** [comment]
@adeshmukh-quizlet Would you like to create a PR for this?
