### ISSUE TITLE
Kustomize 2.0.x breaks re-use of patches

### ISSUE THREAD

**Issue by jskold** [kubernetes-sigs/kustomize#798]
I have a structure that looks like this:

```
.
├── app1
│   ├── base
│   │   ├── deployment.yaml
│   │   ├── ingress.yaml
│   │   ├── kustomization.yaml
│   │   └── service.yaml
│   └── overlays
│       ├── dev
│       │   └── kustomization.yaml
│       ├── prod
│       │   └── kustomization.yaml
│       └── stage
│           └── kustomization.yaml
├── app2
│   ├── base
│   │   ├── deployment.yaml
│   │   ├── ingress.yaml
│   │   ├── kustomization.yaml
│   │   └── service.yaml
│   └── overlays
│       ├── dev
│       │   └── kustomization.yaml
│       ├── prod
│       │   └── kustomization.yaml
│       └── stage
│           └── kustomization.yaml
└── patches
    ├── ingress-host-dev.yaml
    └── ingress-host-stage.yaml
```

Both app1 and app2 apply the patches (ingress-host-dev.yaml and ingress-host-stage.yaml) to modify the ingress host in their  dev and stage overlays. This worked flawlessly in Kustomize 1.x and it saved me from having to duplicate a lot of configuration. In Kustomize 2.x this no longer works, resulting in this error: `Error: security; file '../../../patches/ingress-host-dev.yaml' is not in or below '/app1/dev'`

Is there some other way to achieve this kind of re-use of patches? I've tried using symlinks and bases but that doesn't seem to work.

**Comment by vreon** [comment]
I've been successfully using a structure like this:

```
.
├── bases
│   ├── app1
│   │   ├── deployment.yaml
│   │   ├── ingress.yaml
│   │   ├── kustomization.yaml
│   │   └── service.yaml
│   └── app2
│       ├── deployment.yaml
│       ├── ingress.yaml
│       ├── kustomization.yaml
│       └── service.yaml
└── overlays
    ├── dev
    │   ├── ingress-host-dev.yaml
    │   └── kustomization.yaml
    ├── prod
    │   └── kustomization.yaml
    └── stage
        ├── ingress-host-stage.yaml
        └── kustomization.yaml
```

**Comment by Liujingfang1** [comment]
@vreon Thank you for providing this example.
@jskold You need to restructure your config directories. Put the patches into the bases. Then include the case in different overlays. In this way, the patches will be effective in different overlays.

**Comment by jskold** [comment]
@vreon thanks for the example! I guess I'll restructure my config to look similar to the way you describe.

**Comment by jgonera** [comment]
@Liujingfang1 @vreon This is a problem for me too, but my configuration is different and the proposed solution doesn't work. Folder structure:

```
.
├── base
│   ├── config-maps
│   ├── kustomization.yaml
│   └── resources
│       └── app.yaml
├── common
│   ├── patches
│   │   └── debug.yaml
└── overlays
    ├── dev
    │   ├── config-maps
    │   ├── kustomization.yaml
    │   ├── patches
    │   └── resources
    ├── prod
    │   ├── config-maps
    │   ├── kustomization.yaml
    │   ├── patches
    │   └── resources
    └── stage
        ├── config-maps
        ├── kustomization.yaml
        ├── patches
        └── resources
```

Now let's say I use `common/patches/debug.yaml` in both `overlays/dev/kustomization.yaml` and `overlays/stage/kustomization.yaml` like this:

```yaml
bases:
- ../../base
patchesStrategicMerge:
- ../../common/patches/debug.yaml
```

That patch applies a change to the resource defined in `base/resources/app.yaml` so I can't create another base (e.g. `/base-debug`) and put the patch there because then I will get the following error:

```
Error: AccumulateTarget: failed to find an object with apps_v1_Deployment|app to apply the patch
```

I suppose this happens because a base can't apply a patch to a resource defined in another base. How can I solve this? I don't want to have a copy of `debug.yaml` in both overlays because the content would be exactly the same.
