### ISSUE TITLE
Support for ephemeral field editing

### ISSUE THREAD

**Issue by LandonTClipp** [kubernetes-sigs/kustomize#806]
First issue, sorry if I'm violating any guidelines.

As far as I'm aware, the only command-line method for editing fields edits the actual kustomization file. It would be nice if there were a way to specify fields to edit from the command line that applied _only to that particular build_.

For instance, doing something like:

```
kustomize edit set image imgname=url.to.repo/imgname:v1.0.0
kustomize build
```
modifies the kustomization file, however I propose something like
```
kustomize build edit set image imgname=url.to.repo/imgname:v1.0.0
```
which would build the image using the new image name _only for this build_ and would leave the kustomization file untouched. Has this already been discussed before? If not, what are your thoughts?

**Comment by Liujingfang1** [comment]
@LandonTClipp The build time side effects from args is not intended to be supported. Please see the explanation [here](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#build-time-side-effects-from-cli-args-or-env-variables).
