### ISSUE TITLE
CRD's don't load for cert-manager

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#815]
The source file https://github.com/jetstack/cert-manager/blob/v0.6.2/deploy/manifests/00-crds.yaml

A 2-line kustomization.yaml:
```
crds:
  - 00-crds.yaml
```
yields the error:
```
Error: LoadCRDs: error unmarshaling JSON: json: cannot unmarshal string into Go value of type common.OpenAPIDefinition
```
and no other info.

**Comment by donbowman** [comment]
It appears no crds work, this example gives the same result:

```
apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com 
spec:
  group: stable.example.com 
  version: v1 
  scope: Namespaced 
  names:
    plural: crontabs 
    singular: crontab 
    kind: CronTab 
    shortNames:
    - ct
```

**Comment by lxfontes** [comment]
hai don, I think this is related to
https://github.com/kubernetes-sigs/kustomize/issues/480#issuecomment-432455884

**Comment by Liujingfang1** [comment]
The `crds` in kustomization.yaml is used to list open API definition files. Please take a look at the documentation [here](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kustomization.yaml#L203).

For CRD, what  you really need is to customize the transformer configurations in Kustomize. This can be done by adding openAPI definition files in `crds` or by adding custom configurations directory. The latter way is simpler. Please take a look at an [example](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/crd) for it.

**Comment by donbowman** [comment]
I'm sorry, i don't agree w/ this closure of the issue.

1. there's no error message that is useful. If we don't support the standard format (as defined in all of the other kubernetes documentation) at least say so in the eror
2. why can't we take the same input format that is sent to kubernetes? Now you want me to have 2 files in my directory structure that are the same contents but different format, one to apply w/ kubectl and one for internal use?

This is astonishing for a user. why not work like kubectl? there can't be additional info present given the yaml is all that is fed to k8s to start w/.

**Comment by Liujingfang1** [comment]
@donbowman I think you have some misunderstanding of the usage of `crds` or `configurations`. For the yaml you provided, you just need to list it under `resources`. Then when you piped the kustomize output to apply, that CRD will be applied to your cluster.

I agree that we need to improve the error message here. I opened a PR for it. #833

**Comment by donbowman** [comment]
I still don't buy this issue closure.

I do not understand why `kustomize` needs a different file format for the CRD than Kubernetes via kubectl. THis makes maintenance impossible. There cannot be anything in this alternate format that can't be derived (since kubernetes only received the YAML format).

E.g. if I define my CRD in yaml, and then send to Kubernetes api via kubectl, I don't want to use an alternate format to kustomize. FInd a way to make it work like kubectl. There's no missing information, the origin definition is as it is in the Kubernetes documentation.

**Comment by Timoses** [comment]
This feels very odd and strange.
Why is `crds` even needed then? Shouldn't the kubernetes CRD definition suffice?

**Comment by BarthV** [comment]
I'm hitting this issue too. This is reaaly painful since almost all CRD in the community are provded as kube API yaml.

If you keep going in that direction, please provide a simple way to translate kube yaml CRD into openapi spec (directly in kubectl if possible)

Otherway, please consider using Kube yaml as kustomize input.

**Comment by chancez** [comment]
Why can't kustomize simply pull the openAPI definition from CRDs? My understanding is without knowing the openAPI spec it doesn't know how to merge properly when defining kustomizations using them. Otherwise you need a `configuration`?

**Comment by arianvp** [comment]
Hmm bit surprised this was closed as well. https://github.com/kubernetes-sigs/kustomize/issues/2825 seems related.  
Kustomize having this behaviour by default sounds like a complete no-brainer to me.

I worked around this weird quirk using the following hack, using `yq` to extract the OpenAPI spec from the CRD, if anbody else ends up here through Google as well.

```
cat ./minio-operator/operator-kustomize/crds/minio.min.io_tenants.yaml | yq .spec.validation.openAPIV3Schema.properties  > openapi-spec.yaml
```

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minio-operator
crds:
  # TODO: Upstream this
  - openapi-sepc.yaml
```
