### ISSUE TITLE
Dependency update needed because of golang/x/net change

### ISSUE THREAD

**Issue by wenjiaswe** [kubernetes-sigs/kustomize#823]
Here is the background: a deadlock issue in older version of golang/x/net was causing[ some problems](https://github.com/kubernetes/kubernetes/issues/70819) in kubernetes, to fix that, kubernetes needs a new version of golang/x/net that has the fix for the deadlock issue.

[Here is the K8s PR that is trying to update golang/x/net dependency](https://github.com/kubernetes/kubernetes/pull/71501), however, in this new golang/x/net version, a commit merge the httplex package into httpguts: [golang/net@cbb82b5](https://github.com/golang/net/commit/cbb82b59bc5199680c5bf34109e12097095dca9b), which has impact on more vendors, including [kustomize](https://github.com/kubernetes/kubernetes/pull/71501#issuecomment-466739003).

I think we will need to update golang/x/net dependency in kustomize.

One more Xref: [Unable to update to newer dependencies like docker etc](https://github.com/kubernetes/kubernetes/issues/74413)
cc @PrasadG193

**Comment by Liujingfang1** [comment]
@wenjiaswe Is there any timeline for this need to fixed? Thank you.

**Comment by wenjiaswe** [comment]
@Liujingfang1 I think @PrasadG193 does have a workaround right now, but I do think this could go in ASAP. @PrasadG193 already has a fix now, if you could help review and approve it, it would be great! Thank you!
