### ISSUE TITLE
imageTag truncated when private repo name contains port number

### ISSUE THREAD

**Issue by acheaito** [kubernetes-sigs/kustomize#831]
Consider the image name
`artifactorytest.mycompany.com:443/docker-virtual/image1`
and the kustomization
`images:
  - name: artifactorytest.mycompany.com:443/docker-virtual/image1
    newTag: v2019.1`

When I run kustomize build, it truncates the image name at the port number and applies the tag, resulting in `artifactorytest.mycompany.com:v2019.1`

Tested with kustomize 2.0.2

**Comment by Liujingfang1** [comment]
Should be fixed by #837
