### ISSUE TITLE
Testing framework for Windows

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#834]
At the time of writing, commits to the repo only have to pass [bin/pre-commit.sh](https://github.com/kubernetes-sigs/kustomize/blob/master/bin/pre-commit.sh), which currently runs only on linux.

Would be nice to have this script, or it's equivalent, run on a Windows node, so we could have more confidence in a Windows release.

edit: 21 aug 2019; would be happy to just have the unit tests being run on windows.  linux / darwin tests also cover all the examples, but we can skip that for a windows release.

**Comment by kenmaglio** [comment]
I can easily assist ( and have actually started it already ) to convert the shell script to powershell.
I have the skeleton working, but I am not familiar at all with knowing if the tests / linting are working correctly.

**Comment by pwittrock** [comment]
Yes please!  I took a swing at this but hit a wall.  FWIW, here are some of the issues I encountered with Windows:

- [ ] Not sure if `curl` exists on windows (`wget` does and we could switch to that if need be)
- [ ] Need to install `tree` command with choco
- [ ] Lint script doesn't work because the GOOS name it gets isn't recognized

[Instructions for windows on Travis](https://docs.travis-ci.com/user/reference/windows/)

**Comment by pwittrock** [comment]
@kenmaglio Please ping me or @monopole on Slack when you have a PR out.  GitHub notifications are a firehose.

**Comment by brendandburns** [comment]
@kenmaglio let me know if you want help on this.

**Comment by monopole** [comment]
Hey @kenmaglio Thanks!

Beyond getting stuff to work in powershell, we also need a place to run it - and as Phil mentioned travis recently started to support windows.

The travis setup is here https://github.com/kubernetes-sigs/kustomize/blob/master/.travis.yml - apologies if that's all obvious.  So it will need mods too.

**Comment by kenmaglio** [comment]
I have a WIP PR - I have built a PowerShell script that replicates the same tests for windows. 

[WIP: Windows Precommit / Testing #838](https://github.com/kubernetes-sigs/kustomize/pull/838)

**Comment by kenmaglio** [comment]
> 
> 
> Yes please! I took a swing at this but hit a wall, so would be great to have your expertise. FWIW, here are some of the issues I encountered with Windows:
> 
>     * [ ]  Not sure if `curl` exists on windows (`wget` does and we could switch to that if need be)
> 
>     * [ ]  Need to install `tree` command with choco
> 
>     * [ ]  Lint script doesn't work because the GOOS name it gets isn't recognized
> 
> 
> [Instructions for windows on Travis](https://docs.travis-ci.com/user/reference/windows/)
> 
> Adding OSX tests in #835

@pwittrock 
So **curl** is replaced with a few different things in PowerShell.
Invoke-WebRequest, Invoke-RestRequest   or for just downloading a file...

```PowerShell
(New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')
```

The **tree** command I believe is the ability to do  ```./...```  ?
If so - built into PowerShell

I can't actually tell if the **lint** script is working or not, as I had to turn on verbose.
There's no output that I get - other than it spins stuff up, and reports success.

@brendandburns Please!
I'm going to be at a little bit of a loss trying to ensure these function run the same. And also getting Travis setup correctly.  I utilize Jenkins and know that - but not yet delved into travis or appveyor.

**Comment by brendandburns** [comment]
fwiw, Azure Pipelines (https://azure.microsoft.com/en-us/services/devops/pipelines/) is also free for open source projects and has good windows support in case Travis doesn't work out (starting w/ Travis makes sense)

**Comment by kenmaglio** [comment]
@brendandburns I have actually looked into that ( only because really it's old TFS which I've done a ton ).  Only thing then is possibly getting it to pull the source from github and not it's own repo.

**Comment by kenmaglio** [comment]
For those who don't have windows - just to see where I've gotten to thus far.
![kustomze-test-run](https://user-images.githubusercontent.com/3901017/53686368-b13c2200-3ceb-11e9-87b0-d09595962e55.gif)

**Comment by monopole** [comment]
Looked like a race condition on a temp file - can you paste the stack trace into the discussion on #840 please?

**Comment by kenmaglio** [comment]
Updated [#840 ](https://github.com/kubernetes-sigs/kustomize/pull/840)

**Comment by kenmaglio** [comment]
Sorry I haven't had much time to work on the travis side of the PR. I hope to be able to look at is soon.

**Comment by monopole** [comment]
@alexeldeib Just saw your work referenced in https://github.com/kubernetes-sigs/kustomize/pull/1374#issuecomment-513506466

If you want to send a PR, i'd be happy to help get it in.

**Comment by monopole** [comment]
To be clear - lets just get the unit tests to run, and some kind of minimal test to run the binary merely to assure it gets built, and we can get a windows release out.  No need to reproduce the mdrip-based example coverage (i think that would be too hard given the bash-isms and unix-isms in the example code blocks).
