### ISSUE TITLE
Issue #821 was closed without solving the issue

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#836]
kustomize re-orders config causing fail when crd or admission webhook used #821 https://github.com/kubernetes-sigs/kustomize/issues/821

this included a test case that was simple. The PR that was created to `close` this problem https://github.com/kubernetes-sigs/kustomize/pull/822 did not fix the issue, nor did it include the test case.

The `ValidatingWebhookConfiguration` is emitted after its use, causing a failure to apply, and then later no ability to delete, and a lockup, leaving me with a Namespace that is permanently stuck in 'deleting'.

I retested with 16d1b20ed61dfab4e84fea898ca9d1048edb3120 (which includes d5c87345555be01c6755221236fc506b47cc9f02)

testcase attached. If you run kustomize build from the overlays/global/cert-manager dir, | kubectl apply -f, you will see the error
[cm.tar.gz](https://github.com/kubernetes-sigs/kustomize/files/2919722/cm.tar.gz)

```
deployment.apps/cert-manager created
cronjob.batch/cert-manager-webhook-ca-sync created
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
apiservice.apiregistration.k8s.io/v1beta1.admission.certmanager.k8s.io created
job.batch/cert-manager-webhook-ca-sync created
certificate.certmanager.k8s.io/cert-manager-webhook-ca created
certificate.certmanager.k8s.io/cert-manager-webhook-webhook-tls created
issuer.certmanager.k8s.io/cert-manager-webhook-ca created
issuer.certmanager.k8s.io/cert-manager-webhook-selfsign created
Error from server (InternalError): error when creating "/tmp/l": Internal error occurred: failed calling webhook "clusterissuers.admission.certma

nager.k8s.io": the server could not find the requested resource
Error from server (InternalError): error when creating "/tmp/l": Internal error occurred: failed calling webhook "clusterissuers.admission.certmanager.k8s.io": the server could not find the requested resource
Error from server (InternalError): error when creating "/tmp/l": Internal error occurred: failed calling webhook "clusterissuers.admission.certmanager.k8s.io": the server could not find the requested resource
```
[as-built.zip](https://github.com/kubernetes-sigs/kustomize/files/2919736/as-built.zip)

If we look at the file it build (attached), you can see why.

**Comment by pwittrock** [comment]
@donbowman Would this solve your problem?

kubernetes/enhancements#865

**Comment by monopole** [comment]
Please just continue on the same issue.  We can reopen it trivially, and retain context in one place.   I apologize for the abrupt closure.

If you wish, copy the comments above over to #821
