### ISSUE TITLE
`kustomize edit fix` has a side effect to screw the original format

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#848]
Tried `kustomize fix` and it does not just fix the missing field, but seems also auto format the file. And this leads to a side effect to screw the original format.

```
 - ../../../bases/foo
+- ../../../bases/ambassador

 namespace: iva-prod

-patches:
+patchesStrategicMerge:
 - foo.yaml

+
+  ## CAVEAT: do not use S3 for state store, since it is too slow to list
+  # - STATE_STORE=s3://state-bucket
+
 configMapGenerator:
-- name: foo
+- behavior: merge
   literals:
   - ENVIRONMENT=iva-prod-daisy-nvaiinfracn-com
   - DATA_STORE=s3://data-bucket
-  ## CAVEAT: do not use S3 for state store, since it is too slow to list
-  # - STATE_STORE=s3://state-bucket
   - STATE_STORE=/state
-  behavior: merge
+  name: foo
+- behavior: merge
+  literals:
+  - AMBASSADOR_ID=bar
+  name: ambassador
+apiVersion: kustomize.config.k8s.io/v1beta1
+kind: Kustomization
```

**Comment by Liujingfang1** [comment]
@yujunz Yes, it does. I guess what you mean is the order of `name` and `behavior` inside the configMapGenerator. 
We want `kustmize edit` to keep the comments and order of fields. For example, after a edit for your kustomization.yaml, the order of `namespace`, `configMapGenerator` don't change. It has some internally logic to handle the kustomization.yaml content. However, the sub-field order like `name` or `behavior` is not kept.

**Comment by yujunz** [comment]
Not exactly. Order does not matter that much. I want to preserve the inline comments with the code. Note that `## CAVEAT` is moved to an unrelated place. It is expected to stick with `-STATE_STORE=/state`

**Comment by Liujingfang1** [comment]
When yaml files are loaded into an object, the comments are all dropped. If the library handling yaml files could preserve comments, we can leverage that. Without such functionality from a yaml library, Kustomize uses a special [type ](https://github.com/kubernetes-sigs/kustomize/blob/46bd38e89d8325ed45a7134af4bb693c13f9f754/pkg/commands/kustfile/kustomizationfile.go#L100) to record the field and associated comments. This is only for the top level comments. The inline comments are all moved the top level comments.

**Comment by yujunz** [comment]
Understood. This probably means `kustomize edit fix` is not recommend for fix yaml with comments at the moment. It is not a high frequent requirement any way.
