### ISSUE TITLE
diff doesn't compare uncustomized resources to customized resources

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#85]
RawResourses purports to return uncustomized resources so they
can be diffed against customized resources.

However, 
applicationImpl.RawResources
calls a.rawResources
calls a.subAppResources()
which does a for loop over the bases, calling subapp.SemiResources() for each base.
That function performs transformation.

So RawResources only skips transforming the resources in the topmost kustomization file.

See TODO in TestRawResources2 - that test shouldn't pass
https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/app/application_test.go#L289

**Comment by monopole** [comment]
after the refactor in #89, the call flow is

`MakeUncustomizedResMap`
calls `loadResMapFromBasesAndResources`
which calls `loadCustomizedBases`

so the problem, if one sees it that way, is more obvious.

When performing a _diff_ where the kustomization involves an overlay, in the so-called uncustomized half of the operation, the overlay won't be customized, but underlying bases will be.  So the diff will only show up at the level of the topmost overlay.

**Comment by Liujingfang1** [comment]
@monopole  I start to consider a different set of problems. This might be out of the scope of kustomize. If kustomize (or with help of git or other tools) can provide `diff` between current kustomization and the last kustomization applied to k8s cluster. Based on the diff, kubectl apply will do roll out as well as delete obsolete objects.

**Comment by monopole** [comment]
The goal was to do something like
```
 diff <(find . -name "*.yaml") <(kustomize build .)
```
but that in itself is poorly defined given the existence of secret and configmap generators.

This just doesn't make sense, i don't think its worth fixing - lets kill the command .

I presume there are yaml processing tools somewhere that could compare unmodified resources to kustomize output, and the user could elide the secrets and configmaps.

@Liujingfang1 @droot anyone WDYT?

**Comment by Liujingfang1** [comment]
@monopole I'm ok with killing the diff command. So far we haven't seen any user mentioning that they have used this command. 
Removing this command will also give the code a clear logic.
