### ISSUE TITLE
Nested folder structure of overlays not working with 2.X any more

### ISSUE THREAD

**Issue by krinklesaurus** [kubernetes-sigs/kustomize#851]
Hi,

`kustomize version` output is
```
Version: {KustomizeVersion:2.0.2 GitCommit:b67179e951ebe11d00125bdf3c2670e88dca8817 BuildDate:2019-02-25T16:53:32Z GoOs:darwin GoArch:amd64}
```

using version `1.0.8` the following folder structure worked for me

```
.
├── app1
    ├── rev1
    │   ├── kustomization.yaml
    │   └── rev1.yaml
    ├── rev2
    │   ├── kustomization.yaml
    │   └── rev2.yaml              
    ├── kustomization.yaml
    └── service.yaml
├── app2
    ├── rev1
    │   ├── kustomization.yaml
    │   └── rev1.yaml
    ├── rev2
    │   ├── kustomization.yaml
    │   └── rev2.yaml              
    ├── kustomization.yaml
    └── service.yaml
kustomization.yaml
global.yaml    
```

where `global.yaml` contained some global configuration parameters, `service.yaml` in `app1` defined the common configuration properties for the app1, and the `revX.yaml` files contained the most specific configuration properties for the specific revision of app1. 

`kustomization` files look as following:

`global.yaml`
```
resources:
  - base.yaml
```

`service.yaml`
```
bases:
  - ../
patches:
  - service.yaml
```

`revX.yaml`
```
bases:
  - ../
patches:
  - revX.yaml
```

I could simply call `kustomize build ./app1/rev1` and `global.yaml`, `service.yaml`, and `rev1.yaml` where merged into one configuration file.

However, changing to version 2.0.2 this is not possible anymore. Error is

```
Error: couldn't make loader for ../: cycle detected: candidate root '/blabla/app1' contains visited root '/blabla/app1/rev1'
```

I tried moving the overlays into an `overlays` directory and the global files into a `base` folder but did not succeed. The usage of the `service.yaml` files within a **nested** folder structure is crucial for me as otherwise I'd have to maintain the same configuration parameters in every revision folder. Can you help or tell me what I'm doing wrong here? 

Thanks

**Comment by Liujingfang1** [comment]
@krinklesaurus You can't have an overlay inside a base directory. 

How about this directory structure
```
.
├── apps
│   ├── app1
│   │   ├── base
│   │   │   ├── kustomization.yaml
│   │   │   └── service.yaml
│   │   └── overlays
│   │       ├── rev1
│   │       │   ├── kustomization.yaml
│   │       │   └── rev1.yaml
│   │       └── rev2
│   │           ├── kustomization.yaml
│   │           └── rev2.yaml
│   └── app2
│       ├── base
│       │   ├── kustomization.yaml
│       │   └── service.yaml
│       └── overlays
│           ├── rev1
│           │   ├── kustomization.yaml
│           │   └── rev1.yaml
│           └── rev2
│               ├── kustomization.yaml
│               └── rev2.yaml
└── base
    ├── global.yaml
    └── kustomization.yaml
```

**Comment by nhooyr** [comment]
Docs need an update. RIght now https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configGeneration.md#establish-base-and-staging recommends the OP's approach.

**Comment by monopole** [comment]
Thanks for the bug report!  Please see the new [FAQ](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/FAQ.md#security-file-foo-is-not-in-or-below-bar).

**Comment by monopole** [comment]
@nhooyr agreed - docs need an update

**Comment by bcouetil** [comment]
8 months later I'm coming here following the exact same course of action 😉

**Comment by 123BLiN** [comment]
same 😭
