### ISSUE TITLE
`go get github.com/kubernetes-sigs/kustomize` fails

### ISSUE THREAD

**Issue by pwfff** [kubernetes-sigs/kustomize#855]
`cannot load k8s.io/api/admissionregistration/v1alpha1: cannot find module providing package k8s.io/api/admissionregistration/v1alpha1`

See https://github.com/kubernetes/client-go/issues/551#issuecomment-462619473

**Comment by pwfff** [comment]
Some more details, Go 1.12.0, with module support on.

```
$ go get github.com/kubernetes-sigs/kustomize
go: finding k8s.io/api/admissionregistration/v1alpha1 latest
go: finding k8s.io/api/admissionregistration latest
go: finding k8s.io/api latest
build github.com/kubernetes-sigs/kustomize: cannot load k8s.io/api/admissionregistration/v1alpha1: cannot find module providing package k8s.io/api/admissionregistration/v1alpha1
```

**Comment by Liujingfang1** [comment]
@pwff Try `go get sigs.k8s.io/kustomize`

**Comment by pwfff** [comment]
That fails with `build sigs.k8s.io/kustomize: cannot load k8s.io/api/admissionregistration/v1alpha1: cannot find module providing package k8s.io/api/admissionregistration/v1alpha1` as well.

**Comment by pwfff** [comment]
Also, I found this issue in the meantime: https://github.com/kubernetes/client-go/issues/569
So I suppose once that's fixed, this will be as well. I'm not sure if y'all could pin that package before then though.
