### ISSUE TITLE
Command completion for bash and/or zsh

### ISSUE THREAD

**Issue by mamoit** [kubernetes-sigs/kustomize#856]
This is definitely a first world problem, and a very low priority feature request, but I think it could be really handy for new users to explore commands and for the other users to speed up their flow.

`kubectl`, `kops`, `helm`, and so many others all have this feature and I've grown quite fond of it.

They all follow the `<programName> completion <shell>` schema.

**Comment by cmur2** [comment]
I think it is more than a first world problem as it really increases productivity...

**Comment by purificant** [comment]
Command completion would be a very welcome addition.

My use case is switching from using kustomize build shipped in kubectl 1.14 (`kubectl apply -k overlays/prod`) to a standalone kustomize to use the latest version (v3.0.0) (`kustomize build overlays/staging | kubectl apply -f -`). I immediately felt the lack of command completion and a google search led me here. There are of course workarounds, aliases, scripts, etc. Having this work out of the box would improve quality of life.

**Comment by ChrisEke** [comment]
Just dropping in to mention that thanks to #3110 this now works. E.g: 

`kustomize completion bash >/etc/bash_completion.d/kustomize`

**Comment by mamoit** [comment]
@ChrisEke Thanks! Didn't notice the release of the feature :tada:
