### ISSUE TITLE
Strconv.atoi invalid syntax #816 not resolved by #832

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#859]
In #816  I gave an example of a type of syntax error in the input yaml that lead rise to a non-useful error. In this case, it did not indicate the file or line or object or type of error, it just said:

```
Error: strconv.Atoi: parsing "": invalid syntax
```

#832  was created, ostensibly to address this.
However, it does exactly the same thing with input file as given in #816 . 

I fetched from master, verified commit 78cbff16ef15b5e41d2c10b3baaeb5fffd06d7ed was present, ran `go build`, and then `./kustomize build /tmp/x`

```
$ ./kustomize build /tmp/x
Error: strconv.Atoi: parsing "": invalid syntax
```

The syntax error is the missing `-` at the end of the op:

```
$ cat /tmp/x/default-issuer.yaml 
---
- op: add
  path: /spec/template/spec/containers/0/args/
  value: --default-issuer-kind=ClusterIssuer 
- op: add
  path: /spec/template/spec/containers/0/args/
  value: --default-issuer-name=letsencrypt
```

So I don't think this PR addresses the issue, the behaviour is unchanged.

My expectation is that I get file:line information, something useful I can go and find my syntax error. Its too complex to binary search down otherwise.

**Comment by Liujingfang1** [comment]
The line number if not available for Kustomize. I opened an issue in the library for json-patch. https://github.com/evanphx/json-patch/issues/75

**Comment by donbowman** [comment]
even so...
there's no change in the output w/ the PR. So its not clear how the PR solves the original issue?
can it at least talk about the object type its processing?

**Comment by donbowman** [comment]
/remove-lifecycle rotten

the upstream code has had some improvement https://github.com/evanphx/json-patch/issues/75 so changing the dependency would help.
