### ISSUE TITLE
Improper use of os.Stat

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#86]
`os.Stat` is called directly in the bowels of the code, despite having a means to mock it, meaning it's impossible to inject a fakefs there.

```
find ./ -name "*.go" | grep -v vendor/| xargs grep os.Stat\(
```

Likewise, there's an `if` statement that ignores an error check on the result of os.Stat here:

> https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/resmap/secret.go#L63

if the error isn't ignored (and it should not be) then application_test fails (with secret generation).

I noticed this when investigating #85 

So this issue is to 
 * remove if statements that ignore errors from os.Stat
 * properly plumb use of the fs interface down into the code so that calls to os.Stat can be mocked (this is done correctly in other code  - see use of https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/fs/fs.go#L30
 * fix behavior and any failing tests

it would be even better to completely divorce the transformation/generation stage from the filesystem by loading everything into memory first, retaining a FS like tree as needed, but that's a bigger issue to maybe attempt later

**Comment by uthark** [comment]
Hi! I'd like to work on the issue.

**Comment by Liujingfang1** [comment]
@uthark sounds good and thank you. Let me know if you need any help.

**Comment by Liujingfang1** [comment]
@uthark I'll review it today
