### ISSUE TITLE
How to merge variable?

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#863]
I got the following error when I define a variable which already existed in base. 

```
Error: MergeVars: var GATEWAY_ACM_CERT already encountered
```

Is it possible to merge the variables like `configMapGenerator`, which has a `merge` behavior setting?

**Comment by Liujingfang1** [comment]
Why do you need to use the same var name?
If the field that `vars` refers to is from a ConfigMap, you can use `merge` or `replace` to override the ConfigMap data. As a result, the field content will also be changed.

**Comment by yujunz** [comment]
I was trying to override the ACM cert in different environment to *another* ConfigMap key. Yes, it is possible to have a workaround using more ConfigMaps.

**Comment by rayer4u** [comment]
There is a scene, the var SERVICE_NAME defined in base and used in pods args. It's important to override it to unify naming style. 
In other words, can change base service name?

**Comment by eterna2** [comment]
@Liujingfang1 

my usecase is I am referencing from multiple third-party kustomize, which happens to use the same var name. 

Wondering if it is possible to scope var to within its individual kustomize context?
