### ISSUE TITLE
Loading data paths above root

### ISSUE THREAD

**Issue by brushmate** [kubernetes-sigs/kustomize#865]
I just updated from v1.0.11 to v2.0.2 and noticed that since #700 it's not possible to generate config maps from resources outside of the kustomization root anymore. So far we manage our kustomizations inside a Maven project which has basically this structure:

```
src/
└── main/
    ├── filters/
    │   ├── stage/
    │   │   └── environment.properties
    │   └── prod/
    │       └── environment.properties
    └── k8s/
        ├── base/
        │   ├── deployment.yaml
        │   ├── ingress.yaml
        │   ├── kustomization.yaml
        │   └── service.yaml
        └── overlays/
            ├── stage/
            │   ├── env_patch.yaml
            │   └── kustomization.yaml
            └── prod/
                ├── env_patch.yaml
                ├── kustomization.yaml
                ├── replicas_patch.yaml
                └── resources_patch.yaml
```

The overlays should generate configmaps from the properties files under `filters`.  So far this was not a problem with th following kustomization:

```
bases:
- ../../base

patchesStrategicMerge:
- env_patch.yaml

configMapGenerator:
- name: configmap
  files:
  - environment.properties=../../../filters/stage/environment.properties
```

I guess the ideal solution would be to move the properties files to their respective kustomization roots, but unfortunately they are still used during the Maven build and I can not easily change that. What do you think about adding a flag to kustomize which allows us to disbale the root check? Or a flag that allows us to specify a different resource root?

**Comment by Liujingfang1** [comment]
@brushmate I suggest to add `kustomization.yaml` to both `filters/stage` and `filters/prod` containing a configMapGenerator. Then in the `stage` and `prod` overlays, include corresponding base.

**Comment by brushmate** [comment]
I thought about that as well, but that means having the same file at two places and not having all k8s related things under one directory. I was hoping that there is another solution.

**Comment by Liujingfang1** [comment]
It's not necessary to have all resources or config files under one directory. They can be from different directories via different `bases`.

**Comment by Kruptein** [comment]
I agree with @brushmate that this currently just adds unncessary extra files.

I have a setup like this:
```
├── components
│   ├── packager
│   │   ├── base
│   │   │   ├── deployment.yaml
│   │   │   ├── kustomization.yaml
│   │   │   └── service.yaml
│   │   └── overlays
│   │       ├── develop
│   │       │   ├── image.yaml
│   │       │   └── kustomization.yaml
│   │       └── replicas
│   │           ├── kustomization.yaml
│   │           └── replicas.yaml
│   └── redis
│   └── ...
└── namespaces
    └── A
        └── kustomization.yaml
   └── B
   └── ...
```
in which A/kustomization ideally would look like:

```
namespace: docler
bases:
- ../../components/packager/base
patches:
- ../../components/packager/overlays/replicas/replicas.yaml
- ../../components/packager/overlays/develop/image.yaml
```
and that B/kustomization can handpick a different set of patches.

However currently I would have to add a new overlay A and B to each component to handpick the patches and then use that overlay as the base in namespaces/A, which is just cumbersome.

I assume there must have been some technical reason why this is no longer supported, but I couldn't find any explanation as to why in PR 700

**Comment by brushmate** [comment]
I think it was a security consideration which is described in #693.

**Comment by Kruptein** [comment]
I see, understandable then.

Maybe an optional configuration setting to allow files ending in .yaml or some way to change the root could help then.

I guess I'll have to use the more verbose way for now.

**Comment by jawsper** [comment]
For anyone finding this like I did, `kustomize build --load-restrictor LoadRestrictionsNone` disables the root check.
