### ISSUE TITLE
V2 lack of usability without file upwards path imports.

### ISSUE THREAD

**Issue by frejsoya** [kubernetes-sigs/kustomize#868]
After upgrading to v2..x We have had to significantly alter our setup for the worse, as we now have to reorder a lot of files with scripts, so it fits with the setup we already had. This should be an unneeded redirection. 
The setup we have is a simple a simple scaffolding setup with makefile and kustomize such that:

- New projects are started easily with good defaults for multiple environments
- You can easily add per project kustomizations using patches.

I think the combination of 

- Only one kustomize.yaml per directory
- No reference paths upwards that directory (except for bases)

Makes any kind of directory structure overly complicated to achive the above.

The setup we have:
A shared place in a submodule for resources:
```
shared/
├── service
│   ├── deployment.yaml
│   ├── kustomization.yaml
│   └── service.yaml
└── resources
    ├── ingress.yaml
    ├── nginx-ingress.yaml
    └── patches
        ├── deployment-replicas.yaml
        └── replace-with-nodeport.yaml
```
And then per project (which in this case references a service)
```
project/
├── dev
│   └── kustomization.yaml
├── local
│   └── kustomization.yaml
└── prod
    └── kustomization.yaml
```
Before I could reference patches directly, but now have to copy everything into a new structure and then apply kustomize.  Even sharing patches/resources between environments is impossible (without repeatedly adding superfluous kustomization.yaml files and using bases)

I understand that for security reasons it was decided only to reference bases upwards. It's not entirely clear for me though. If this remains a requirement then I think a small fix should improve this:

Today there is no definition of a project root, except where the kustomization yaml  is located. And those are often at the leaves of a directory structure. Further, I don't believe there would be a security issue if we could have some definition of a project root and anything above that root could be imported.
```

kustomize build <path>
```
would read `<path>/kustomization.yaml` and relative paths in  `<path>/kustomization.yaml` would allow reading resources and patches from any path inside the current working directory of kustomize execution.

**Comment by Liujingfang1** [comment]
Related to https://github.com/kubernetes-sigs/kustomize/issues/759

**Comment by monopole** [comment]
Thanks for the bug report!  Please see the new [FAQ](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/FAQ.md#security-file-foo-is-not-in-or-below-bar).
