### ISSUE TITLE
Add `kustomize edit remove resource`

### ISSUE THREAD

**Issue by narg95** [kubernetes-sigs/kustomize#873]
Hi,

I would like to work in a PR to remove resources from a kustomization file. Currently you can only add.

Please give me your opinion and if there is something important to consider.

Thanks !

**Comment by Liujingfang1** [comment]
I think it should be similar to `kustomize edit add resource`:
- accept multiple filepath. Those filepath should be relative path rooted at current directory
- If a matched item found in `resources` list, remove it from that list.
- If no match found, skip it

**Comment by Liujingfang1** [comment]
Here is a related request #725
