### ISSUE TITLE
prune all unused configmaps/secrets

### ISSUE THREAD

**Issue by nhooyr** [kubernetes-sigs/kustomize#876]
Is there an automated way to do this?

**Comment by donbowman** [comment]
what i have been doing is:
`kustomize build . | kubectl apply -f - --prune -l app=MYLABEL`

make sure the label is set properly tho.

**Comment by Liujingfang1** [comment]
We plan to improve the pruning functionality in kubectl, see the [KEP](https://github.com/kubernetes/enhancements/pull/810).

**Comment by nhooyr** [comment]
@donbowman thanks, will use that for now.

That's awesome @Liujingfang1, looking forward to it.

**Comment by cppforlife** [comment]
@nhooyr @donbowman you may want to check out https://get-kapp.io if you run into trouble with --prune.
