### ISSUE TITLE
Finish goplugins (release blocker)

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#881]
Per the [kep](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/kustomize-secret-generator-plugins.md) we need some more work goplugins started in #760 

Release blockers:

 - [x] kustomize reads config (plugins specifically) from (a subdir of) `$HOME/.config`, and should honor `XDG_CONFIG_HOME`  (see [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)) as an override to this location.

 - [x] need flag `--alpha_enable_goplugin_and_accept_panic_risk` and associated [behavior](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/kustomize-secret-generator-plugins.md#mitigation-1).  The help for this flag should explain the problem.

Nice to haves:

 - [ ] the existing three forms of KV generation (env, literals, files) should be expressible as `pluginType:builtin`.

 - [ ] the existing `edit fix` command, which reads a kustomize file, updates it to new behavior, and writes it out again, should be modified to convert the three existing forms to builtin plugin form.

**Comment by sethpollack** [comment]
I can open some more PR's to add the rest of this.

**Comment by monopole** [comment]
Nice.

Now that you knocked off literals builtin, can you do env and files too? 

And add add some tests like this : https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/target/generatoroptions_test.go#L97
to cover them?  In some new file (builtinplugins_test.go?)

Thanks!

**Comment by sethpollack** [comment]
Ok working on it, also working on `kustomize edit fix`

**Comment by monopole** [comment]
ah thanks - i'm out :)

**Comment by Liujingfang1** [comment]
The goplugin in `secretGenerator` is removed. Kustomize recommends to write generator plugin for that.
