### ISSUE TITLE
Feature request: support `.netrc` for https credentials

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#894]
HTTP credentials may be required for some private repository. It would be nice to support `.netrc` to provide them, just like the way terraform remote module does.

For example
``` shell
kustomize build
Username for 'https://code.internal.local':
```
I would expect it loads the credential from `~/.netrc`

``` shell
machine code.internal.local
login yujunz
password secret
```

**Comment by Liujingfang1** [comment]
You can set ssh to access the private repos. Then you won't see the username prompts.

**Comment by yujunz** [comment]
The problem is that the repo is quite huge, e.g. *giga bytes mono repository*. It seems git+ssh does not support partial clone well.

I'm pulling the source from some web browse plugin like [gitiles](https://github.com/google/gitiles) which provides https access only.

**Comment by yujunz** [comment]
It seems plain tarball url is not supported at all,  only GitHub, Azure repo and AWS code commit repo is supported. Is that so?

https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/git/repospec.go#L145

 cc @monopole who seems to be the owner of git related code.

**Comment by yujunz** [comment]
Suppressed by #923
