### ISSUE TITLE
skip kustomize transformers for paths

### ISSUE THREAD

**Issue by Liujingfang1** [kubernetes-sigs/kustomize#896]
This is a feature request for allowing users to skip paths for transformers.

Kustomize uses a series of transformers to set fields for all resources inside one kustomization directory. Those transformers include
- name prefix transformer
- name suffix transformer
- namespace transformer
- common label transformer
- common annotation transformer

Each of these transformers modifies resource configuration by changing the value of a certain path inside the resource. The paths that a transformer can modify is from a set of configurations.  Here are some transformer configurations
```
namePrefix:
- path: metadata/name

commonLabels:
- path: metadata/labels
  create: true
- path: spec/selector
  create: true
  version: v1
  kind: Service
```
Kustomize allow users to add extra configurations so that the transformers can perform as expect for non core types. However, if users want to skip a path in certain transformer, they couldn't do that since Kustomize lacks the customization to skip a path.

There have been quite a few requests, which are looking for a feature to skip certain path. Here is the list of those requests.
- Make cluster level kind configurable  https://github.com/kubernetes-sigs/kustomize/issues/617
- Do not add namespace to cluster scoped CRDs https://github.com/kubernetes-sigs/kustomize/issues/552
- Skipping nameprefix for some resource kind https://github.com/kubernetes-sigs/kustomize/issues/519
- Adding labels only to metadata.labels https://github.com/kubernetes-sigs/kustomize/issues/330
- Skip adding labels to certain paths https://github.com/kubernetes-sigs/kustomize/issues/519
- Unable to disable commonLabels injection using transformer config: `Error: conflicting fieldspecs` https://github.com/kubernetes-sigs/kustomize/issues/817

**Comment by yujunz** [comment]
It seems I can't assign my self for it, @Liujingfang1  😄

**Comment by orirawlings** [comment]
Does this issue supersede #91? I'm just trying to make sense of the network of linked issues.

**Comment by alenkacz** [comment]
@Liujingfang1 is anyone working on this? Would you be interested in community contribution?

**Comment by jbrette** [comment]
@alenkacz @verult @orirawlings @yujunz 

Please have a look at:
- [KEP: Kustomize FieldSpec skip ](https://github.com/kubernetes/enhancements/pull/1232)
- [PR: Skip kustomize transformers for paths](https://github.com/kubernetes-sigs/kustomize/pull/1491)

**Comment by yujunz** [comment]
Left some comments in the KEP.

**Comment by micnncim** [comment]
/reopen
/remove-lifecycle rotten

Any update? Seems some of parts haven't been implemented yet like https://github.com/kubernetes-sigs/kustomize/blob/b2ba82a0bdc23fb70dd07a575e2db04732dff29c/plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go#L28-L34.

**Comment by Shell32-Natsu** [comment]
@micnncim You can use the *explicit way* described [here](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/builtins/) to override the fieldSpec for buitlin plugins.

**Comment by micnncim** [comment]
@Shell32-Natsu I tried it and confirmed it works well as I expected. Thanks!

**Comment by mukundjalan** [comment]
@Shell32-Natsu the link you provided seems to be broken. Can you please provide reference to the new page for this feature?
