### ISSUE TITLE
version displayed is unknown

### ISSUE THREAD

**Issue by scraly** [kubernetes-sigs/kustomize#899]
Hi,

I installed kustomize and when I execute kustomize version command, instead of obtain the version of kustomize I have "inknown":

```
$ kustomize version
Version: {KustomizeVersion:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}
```

Thx.

**Comment by Liujingfang1** [comment]
This has been fixed in 2.*.
