### ISSUE TITLE
feature request: scale (statefulset, deployment, jobs, ...)

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#900]
The largest number of patches I have all have a single line: changing the `replicas`.

This is making the maintenance much harder, each overlay now has ~50 patches just for scale purposes. (e.g. in `dev` I scale to 3 in this statefulset, 4 deployments here, this job has X parallelism).

It would be nice if this were handled like the image tag, that there was a single/couple line in kustomisation.yaml that could have type/name/scale rather than the separate file w/ the header w/ the include for `strategic` merge.

**Comment by SudoBrendan** [comment]
Just leaving a trail for others who searched "kustomize scale" instead of "kustomize replicas" like I did:

https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md#replicacounttransformer
