### ISSUE TITLE
Namespace generated is missing document separator

### ISSUE THREAD

**Issue by donbowman** [kubernetes-sigs/kustomize#902]
When stacking multiple kustomize outputs together it becomes apparent that the emitted namespace is missing the `---`.

Also, when a namespace is included and added to `resources`, it has the document separator removed.

This is preventing doing e.g.
```
for i in *
do
kustomize build $i
done | kubectl apply -f -
```

```
$ kustomize build .
apiVersion: v1
kind: Namespace
metadata:
  name: x
---
apiVersion: v1
data:
  druid_segmentCache_locations: '[{"path": "var/druid/segment-cache", "maxSize": 32000000000,
    "freeSpacePercent": 1.0, "blahblahblah":"9999999999"}]'
kind: ConfigMap
metadata:
  name: foo-b66gf6d7t6
  namespace: X
$ cat kustomization.yaml 
namespace: X

resources:
  - namespace.yaml

configMapGenerator:
  - name: foo
    literals:
      - 'druid_segmentCache_locations=[{"path": "var/druid/segment-cache", "maxSize": 32000000000, "freeSpacePercent": 1.0, "blahblahblah":"9999999999"}]'
don@cube[gke-noctest]:y
$ cat namespace.yaml 
---
apiVersion: v1
kind: Namespace
metadata:
  name: x
```

**Comment by Liujingfang1** [comment]
This can be fixed by appending a `---` to the end of kustomize output.

**Comment by donbowman** [comment]
i'm not sure how i would do that tho. you mean have a 2nd command that does an echo --- ?

**Comment by Liujingfang1** [comment]
Maybe following command
```
for i in *
do
kustomize build $i
echo "---"
done | kubectl apply -f -
```

**Comment by donbowman** [comment]
so yeah, i understand the workaround.
but why does it omit the doc separator from namespace? Even if i explicilty add?

it should produce valid yaml i think.

**Comment by ryandbump** [comment]
I think this is a reasonable ask. Appending the output from kustomize to a file or stream seems like a fairly common workflow and it could be enabled by ensuring that the output always starts with a document separator. 

Looking at the `EncodeAsYaml` function, writing a leading document separator is explicitly avoided but I am not sure I understand the reasoning for that. 
https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/resmap/resmap.go#L66-L73

**Comment by wfernandes** [comment]
Is it possible to revisit this issue? It seems like an easy fix unless prepending `---` to the yaml output of `kustomize build` is breaking some convention.

**Comment by wfernandes** [comment]
/reopen
/remove-lifecycle stale

Keeping this open until we have a valid reason as to why this is not possible. If there is no issue in supporting this maybe a little guidance on where we can look at to create a PR. Thanks 🙂

**Comment by rdxmb** [comment]
can this be reopened please?

I wanted to create my output with 

```
mkdir build
kustomize build . --output build
```

and am trying to deploy the output via

`cat build/* | ssh NODE kubectl apply -f -`

This does not work because of the missing separator

**Comment by hylowaker** [comment]
Any progress?
