### ISSUE TITLE
path format inconsistent

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kustomize#906]
The format of defining a path in [`fieldRef`](https://github.com/kubernetes-sigs/kustomize/blob/7574f07be35cb05f7a83c00e71838527e5d198b7/pkg/types/var.go#L46) is different from in [`varRef`](https://github.com/kubernetes-sigs/kustomize/blob/2c0c0c9497b46661b1b9399da05d621eb8d45836/pkg/transformers/config/transformerconfig.go#L36).

`fieldRef` path uses a jsonpath-like format. e.g. [here](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/wordpress/README.md#bind-the-variables-to-k8s-object-fields)
`varRef` path uses a Unix style format. e.g. [here](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/crd#adding-a-custom-resource)

It doesn't worth a breaking change in v2.X, but kustomize maintainers should know that.

**Comment by mengqiy** [comment]
cc: @Liujingfang1

**Comment by Liujingfang1** [comment]
The format of `fieldRef` is consistent with [the downward api](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#the-downward-api) format. I don't think we need to change that.
