### ISSUE TITLE
[Doc] document kustomize support escape special characters in path

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/kustomize#907]
I have a resources look like:
```
...
metadata:
  annotations:
    foo.k8s.io/bar: baz
...
```
I was trying to use the CRD features documented at
https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/crd#adding-a-custom-resource.
I didn't find a document stating that kustomize actually supporting escaping special characters in path, e.g. `matadata/annotations/foo.k8s.io\/bar` until @Liujingfang1 told me that.
It should be documented somewhere.

**Comment by Liujingfang1** [comment]
We can add a note to this file https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs

**Comment by John-Lin** [comment]
I found that put a `\` before `/` isn't working but replace `/` to `~1` would work. Is it correct for documents? @Liujingfang1 

see #1256

**Comment by Shell32-Natsu** [comment]
@John-Lin `~1` is used in json patch path.

**Comment by John-Lin** [comment]
@Shell32-Natsu
I see, so for the json patch path should use `~1` and the document is covering for transformer configuration.

**Comment by edrandall** [comment]
IMNSHO this should be re-opened: other than in this bug, that `~1` means escaped `/` is both surprising and still undocumented.   Moreover:
* `examples/transformerconfigs` would not be the right place.
* Perhaps `examples/jsonpatch.md` is the most relevant, in the yaml example
* An example alone does not make up for explicit reference information.   A note alongside explaining that RFC-6901 JSON Pointer specification applies here, would be good.
