### ISSUE TITLE
feature request: create ConfigMap from directories

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#914]
Currently, kustomize can create ConfigMap from literals and files. Why not supporting directory as well?

Expecting behavior like `kubectl create ConfigMap config --from-file directory/`

See https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-directories

**Comment by Liujingfang1** [comment]
You can use `kustomize edit add configmap map-name --from-file=directory/*`

**Comment by michaelbannister** [comment]
@Liujingfang1 then the help text for `kustomize edit add configmap` needs to be improved. It reads as though it's valid to pass a directory path:

```
Usage:
  kustomize edit add configmap NAME [--from-file=[key=]source] [--from-literal=key1=value1] [flags]

Flags:
      --from-file strings          Key file can be specified using its file path, in which case file basename will be used as configmap key, or optionally with a key and file path, in which case the given key will be used.  Specifying a directory will iterate each named file in the directory whose basename is a valid configmap key.
```

The syntax you described above does work, but it doesn't seem intuitive and I had to quote the file path or escape the `*` to prevent shell expansion.

**Comment by Liujingfang1** [comment]
@michaelbannister Agree. Would like to open a PR to improve the help message?

**Comment by michaelbannister** [comment]
If someone can describe exactly (or point me to tests for) the acceptable syntax I’d be happy to open a PR, but I don’t want to write help text based on trying to guess the behaviour! 🙂

**Comment by bittner** [comment]
The part

> Specifying a directory will iterate each named file in the directory whose basename is a valid configmap key

... is obviously not true. Dropping this portion of the text should be sufficient.

Did this ever work? -->

> each named file in the directory whose basename is a valid configmap key

Can someone explain what the described behavior is or was meant to be?
