### ISSUE TITLE
Support hashicorp/go-getter format http url as remote base

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#923]
Original requirement from #894 .

Currently only local files and git is supported in kustomzie. When the bases is stored in a large mono-repo, let's say giga bytes, it is not feasible to clone the whole repository to fetch just one base.

The following features in `hashicorp/go-getter` satisfies such requirements perfectly, i.e.

- [ ] [subdirectory](https://github.com/hashicorp/go-getter#subdirectories)
- [ ] [checksumming](https://github.com/hashicorp/go-getter#checksumming)
- [ ] [unarchiving](https://github.com/hashicorp/go-getter#unarchiving)

**Comment by Liujingfang1** [comment]
Please note that we don't plan to use `hashicorp/go-getter` in Kustomize since it brings a large number of dependencies. 
It would be nice to have Kustomize work flexible with different types of remote targets, but the implementation should be
either inside Kustomize or dependent on a very small number of libraries.

**Comment by yujunz** [comment]
> we don't plan to use `hashicorp/go-getter`

I think I saw it in code somewhere. Is it already removed? It does not have to be `hashicorp/go-getter`. Just need support for go-getter format http url.

**Comment by objectiveous** [comment]
+1.

**Comment by pohly** [comment]
I'm a bit confused. The documentation says that `bases` entries can have hashicorp URL format:
https://github.com/kubernetes-sigs/kustomize/blob/177297c0efb92ec2d7eea8f20c65c1d11c6ae7ef/docs/kustomization.yaml#L130-L133

Is that incorrect and the actual implementation expects something else, or only supports a subset of the hashicorp implementation?

**Comment by yujunz** [comment]
I saw some recent update about plugin (see https://github.com/kubernetes-sigs/kustomize/commit/f6e01cfda788b7e2765807163d312359bdb98d10 )

Is it feasible to exec go-getter as a plugin? It has a standalone executable. (see https://github.com/hashicorp/go-getter#installation-and-usage). 

@Liujingfang1

**Comment by Liujingfang1** [comment]
@yujunz You could write a generator plugin which executes go-getter. This plugin can fetch the files or directories with only raw K8s resources. 

The generator plugins assumes the output is a list of K8s resources. If the remote URL doesn't have a kustomization.yaml and only contains raw K8s resources, the plugin can just load them and write them into a [resmap](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/resmap/resmap.go#L33). 

If the remote URL contains a kustomization.yaml, the plugin has to run a `kustomize build` and then write the output into a resmap. In the case, the plugin depends on kustomize itself, which seem like a improper direction.

**Comment by yujunz** [comment]
Is plugin limited to generator? 

Can we also extend loader with external plugin?

**Comment by Liujingfang1** [comment]
Currently plugins are either generators or transformers, loaders are not included. If you have any thoughts, feel free to write a KEP for it.

**Comment by yujunz** [comment]
A simple plugin for go-getter: https://github.com/yujunz/kustomize-go-getter

**Comment by JohnPaton** [comment]
So just to be clear, the comment that @pohly referenced, and [the remote build example](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md#url-format), are not accurate currently?

**Comment by yujunz** [comment]
What the examples says is true.

> The url should follow hashicorp/go-getter URL format. Here are some example urls pointing to Github repos following this convention.

What is also true is that only **a subset** of all hashicorp/go-getter URL formats are supported.

**Comment by JohnPaton** [comment]
Thanks for clarifying.

For other people who are searching: I was asking this because I was trying to use a remote resource from a private repository over ssh. The correct format turned out to be: 

```yaml
resources:
  - ssh://github.com/username/repo_name.git//path/to/dir?ref=branch_name
```

**Comment by pohly** [comment]
> What is also true is that only a subset of all hashicorp/go-getter URL formats are supported.

And which subset is that?

**Comment by yujunz** [comment]
Only some of the git repo spec

See https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/git/repospec_test.go

**Comment by Liujingfang1** [comment]
@yujunz Would you like to add this generator plugin  https://github.com/kustless/kustomize-plugins/tree/master/gogetter as an example generator in Kustomize repo and write some docs for it?

**Comment by yujunz** [comment]
Please refer to https://github.com/kubernetes-sigs/kustomize/blob/master/examples/goGetterGeneratorPlugin.md
