### ISSUE TITLE
How to avoid data duplication without variable literals or template-like features?

### ISSUE THREAD

**Issue by mathportillo** [kubernetes-sigs/kustomize#930]
Hello guys,
First of all thanks for the amazing work!
How to avoid duplication of data and all its consequences without globs?

For example, I have an kubernetes application that uses a WEB_HOST address in three places:
- a pod: as an env variable, so it can send e-mail with the right links
- a ingress: so it can load balance based on that host
- a certmanager Certificate dnsName: so it can create https certificate for that host

This **web host address are different on my production and staging** environments
How would be the proper way to handle the above example?

with the current kustomize variable feature, that works only with referencing, I could take care of the ingress reference (reading from the pod or from a configMap). But vars wouldn't expand on a custom resource like certmanager certficate.

The options I can think of are:
- should I, for every server environment, create a patch for every different reference of WEB_HOST in my templates? This has awful reusability and a desynchronization risk (data that should be the same and are not, caused by human error or something else)
- should I use sed or something imperative?
- should I edit the default config so that vars could be applied to certmanager Certificates? if so, how?

my confusion is:
Is there a real benefit in [eschewing this functionality](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#unstructured-edits) to avoid problems if all the available solutions for it brings back the same problems?

maybe there is a way to deal with this that I can't see.

Thanks for the help!

**Comment by Liujingfang1** [comment]
> with the current kustomize variable feature, that works only with referencing, I could take care of the ingress reference (reading from the pod or from a configMap). But vars wouldn't expand on a custom resource like certmanager certficate.

`Vars` also work for custom resources. For example, I want var to work in the path `spec/beeRef/action` in kind `MyKind`. Then I'll add custom configurations as
```
#kustomization.yaml
configurations:
- mykind.yaml

# mykind.yaml contains
varReference:
- path: spec/beeRef/action
  kind: MyKind
```
For more details, please take a look at the[ CRD example](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/crd).

**Comment by mathportillo** [comment]
Nice!
Thanks a lot.
