### ISSUE TITLE
upgrade kustomize to use go modules

### ISSUE THREAD

**Issue by kkasravi** [kubernetes-sigs/kustomize#949]
kubernetes go modules have been merged to master and published to staging repositories. The reason for k8sdeps (staging vs public) should be resolvable using go replace directives in the go.mod file.

**Comment by Dean-Coakley** [comment]
@kkasravi I don't understand the k8sdeps part of your issue but it looks like this change has already landed in: https://github.com/kubernetes-sigs/kustomize/commit/e191ff53ddd4d680c84aeac40703d0af36decc83 unless I'm mistaken.

This issue can be closed?

**Comment by kkasravi** [comment]
yes, thanks

**Comment by ian-howell** [comment]
Is there any intention to update the kuberenetes/client-go versions? The current versions are more than a year old

**Comment by kkasravi** [comment]
Yes, see #3368
