### ISSUE TITLE
namePrefix in base breaks patchesJson6902 in overlay

### ISSUE THREAD

**Issue by pohly** [kubernetes-sigs/kustomize#972]
For a reproducible test, see https://github.com/kubernetes-sigs/kustomize/pull/971

I'm using kustomize master, currently 177297c0efb92ec2d7eea8f20c65c1d11c6ae7ef

I'm trying to patch a DaemonSet, but kustomize keeps complaining that it `couldn't find target apps_v1beta2_DaemonSet|~X|~P|pmem-csi-node|~S`.
The target is defined as:
```
patchesJson6902:
- target:
    group: apps
    version: v1beta2
    kind: DaemonSet
    name: pmem-csi-node
  path: lvm-patch.yaml
```
and there such a DaemonSet in the output when I comment out that part above:
```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: pmem-csi-node
```

The problem is that the base has `namePrefix: pmem-csi-`, so `pmem-csi-node` is the result of a rename.

It works when using `name: node`.

This looks like a layering violation to me. The overlay shouldn't have to know how the base produces its output. For example, it might use `namePrefix` now and later get changed to .yaml files where that prefix gets inserted by hand. Then the output is the same, but the overlay no longer works.

It also is non-obvious to the user. It cost me a few hours to figure out the reason for the `couldn't find target` error, because I was matching my `target` specification against the output of the base.

**Comment by pohly** [comment]
Also, is there some documentation about the matching criteria in `target`? By trial-and-error I found out that group+version+kind seem to have to match exactly (i.e. one cannot leave out group or version if the base has it). Is it possible to match just by name, assuming that the name is unique? What is the `~X`, `~P`, '~S` that is shown in the error message?

**Comment by jcassee** [comment]
See also #316
